---
title: Custom Field
page-title: Custom Field component | Vaadin components
description: Use Custom Field for wrapping multiple components as a single field.
meta-description: Learn how to create and configure custom fields for unique input needs in Vaadin.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/custom-field}/elements/vaadin-custom-field[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/customfield/CustomField.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/custom-field}/packages/custom-field[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-custom-field-flow-parent[Java]'
---


= Custom Field

:components-path-prefix: ../

// tag::description[]
Custom Field is a component for wrapping multiple components as a single field.
// end::description[]
It provides standard input field features like label, helper, validation, and data binding. Use it to create custom input components.

[.example,themes="lumo,aura"]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/custom-field/custom-field-basic.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/customfield/DateRangePicker.java[tags=snippet,indent=0,group=Flow]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/customfield/CustomFieldBasic.java[render,tags=snippet,indent=0,group=Flow]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/customfield/LocalDateRange.java[tags=snippet,indent=0,group=Flow]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Appointment.java[tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/custom-field/react/custom-field-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Basic Usage

Custom Field is optimized for wrapping the following components:

- <<../text-field#,Text Field>>
- <<../number-field#,Number Field>>
- <<../password-field#,Password Field>>
- <<../text-area#,Text Area>>
- <<../select#,Select>>
- <<../combo-box#,Combo Box>>
- <<../date-picker#,Date Picker>>
- <<../time-picker#,Time Picker>>

It can also be used to give a label, helper, and other field features for components that don't have them built-in, such as <<../list-box#,List Box>>.


== Value Type & Format

The type, format, and further propagation of the Custom Field value are handled differently in Java, and in Lit and React. The following two sections explain how you might configure these aspects depending on the programming language or approach you prefer.

ifdef::flow[]
=== Java

Custom Field is a generic class that accepts a value type. The value type can be anything: String, List, a bean, or something else.

When the type is specified, you need to establish how the Custom Field's value should propagate to the child components and vice versa. The value propagation heavily depends on the Custom Field's structure, contained components, and their types. For this reason, no default implementation is provided. Instead, Custom Field provides two methods that should be implemented manually: `generateModelValue`; and `setPresentationValue`.

The `generateModelValue` method defines how to generate a Custom Field value from the child components values. Custom Field triggers this method to update its value when a child component emits a change DOM event on the client-side. In this method, you typically need to collect values from all child components and return a single value of the Custom Field type based on those values.

The `setPresentationValue` method receives a Custom Field value and defines how to distribute it to the child components. Custom Field triggers this method to update child component values when its value changes programmatically on the server-side. In this method, you typically need to split the given value into parts and apply them to each individual child component, respectively.

The following example shows how to set up value propagation, using a bean as the value type:

[.example]
--

[source, java]
----
class Phone {
    private final String code;
    private final String number;

    public Phone(String code, String number) {
        this.code = code;
        this.number = number;
    }

    public String getCode() {
        return code;
    }

    public String getNumber() {
        return number;
    }
}

class PhoneField extends CustomField<Phone> {
    private final Select code = new Select();
    private final TextField number = new TextField();

    public PhoneField() {
        ...

        add(code, number);
    }

    @Override
    protected Phone generateModelValue() {
        return new Phone(code.getValue(), number.getValue());
    }

    @Override
    protected void setPresentationValue(Phone value) {
        code.setValue(value.getCode());
        number.setValue(value.getNumber());
    }
}
----
--
endif::[]


=== Lit & React

Custom Field supports only string values. However, it does provide control over the format of the value with a parser and formatter. The parser and formatter define how Custom Field's value should be split to child component values and vice versa. When a child component emits a change event or the Custom Field's value changes programmatically, Custom Field propagates values based on the result of the parser or formatter.


==== Parser

When Custom Field's value changes programmatically, Custom Field passes this value to the parser. The parser is supposed to convert this value into an array of child values, arranged in the order their components appear in the DOM. Custom Field then assigns these values to the child components using their value property.

The default parser returns an array of child component values, splitting the value by the `\t` character.


==== Formatter

When Custom Field detects a change event from a child component, it collects the value properties from all child components and passes them as an array to the formatter. The array contains child values in the order their components appear in the DOM. The formatter is supposed to transform this array into a single string value. The Custom Field then updates its value based on the string returned by the formatter.

The default formatter returns a concatenation of the child component values, separated by the `\t` character.

You can customize the value format by defining your own value formatter and parser, as shown in the following example:

[.example]
--

[source,ts]
----
<source-info group="Lit"></source-info>
render() {
  return html`
    <!-- Phone Custom Field -->
    <vaadin-custom-field
      .formatValue="${([code, number]: unknown[]) => {
        return code && number ? [code, number].join('|') : '';
      }}"
      .parseValue="${(value: string) => {
        return value ? value.split('|') : ['', ''];
      }}"
    >
      <!-- Country code -->
      <vaadin-select></vaadin-select>

      <!-- Phone number -->
      <vaadin-text-field></vaadin-text-field>
    </vaadin-custom-field>
  `
}
----

[source,tsx]
----
<source-info group="React"></source-info>
function Example() {
  return (
    // Phone Custom Field
    <CustomField
      formatValue={([code, number]: unknown[]) => (code && number ? [code, number].join('|') : '')}
      parseValue={(value: string) => (value ? value.split('|') : ['', ''])}
    >
      {/* Country code */}
      <Select />

      {/* Phone number */}
      <TextField />
    </CustomField>
  );
}
----
--


== Native Input Fields

Custom Field works with native HTML elements. The `whitespace` variant can be used when components without an outer margin are used within Custom Field to compensate for the missing space between the label and the component itself.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/custom-field/custom-field-native-input.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/customfield/PaymentInformationField.java[tags=snippet,indent=0,group=Flow]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/customfield/CustomFieldNativeInput.java[render,tags=snippet,indent=0,group=Flow]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/customfield/PaymentInformation.java[tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/custom-field/react/custom-field-native-input.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


[discussion-id]`CB7FDF39-7653-4DF0-A0C0-9C2A2EE7EDBA`
