---
title: Styling
page-title: How to style the Custom Field component | Vaadin components
description: Styling API reference for the Custom Field component.
meta-description: Learn to style the Vaadin Custom Field component to align with your application’s design requirements.
order: 50
---
= Custom Field Styling


== Style Variants

The following variants are supported:

[cols="1,3,1"]
|===
| Variant | Description | Supported by

|Small
|Used to make label, helper, and error message smaller
|Lumo

|Helper above field
|Used to position the helper above the field, and below the label
|Aura, Lumo

|Whitespace
|Adds padding below the label for wrapping components without outer margin
|Lumo

|===

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/custom-field/custom-field-size-variants.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/customfield/MoneyField.java[tags=snippet,indent=0,group=Flow]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/customfield/CustomFieldSizeVariants.java[render,tags=snippet,indent=0,group=Flow]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/customfield/Money.java[tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/custom-field/react/custom-field-size-variants.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

[NOTE]
Custom Field doesn't propagate its style variant to the individual field components it wraps. Each individual component's style variant must be set individually.

include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-custom-field`


=== States

Required:: `vaadin-custom-field+++<wbr>+++**[required]**`
Focused:: `vaadin-custom-field+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-custom-field+++<wbr>+++**[focus-ring]**`
Read-only:: `vaadin-custom-field+++<wbr>+++**[readonly]**`
Disabled:: `vaadin-custom-field+++<wbr>+++**[disabled]**`
Not empty:: `vaadin-custom-field+++<wbr>+++**[has-value]**`
Hovered:: `vaadin-custom-field+++<wbr>+++**:hover**`


=== Contents

Field contents:: `vaadin-custom-field+++<wbr>+++** > your-element-here**`
Field elements wrapper:: `vaadin-custom-field+++<wbr>+++**::part(input-fields)**`


=== Label

Field with label:: `vaadin-custom-field+++<wbr>+++**[has-label]**`
Label:: `vaadin-custom-field+++<wbr>+++**::part(label)**`
Label text:: `vaadin-custom-field+++<wbr>+++** > label**`
Required indicator:: `vaadin-custom-field+++<wbr>+++**::part(required-indicator)**`


=== Helper and Validation Error

Field with helper:: `vaadin-custom-field+++<wbr>+++**[has-helper]**`
Helper:: `vaadin-custom-field+++<wbr>+++**::part(helper-text)**`
Helper text:: `vaadin-custom-field+++<wbr>+++** > [slot="helper"]**`
Invalid field:: `vaadin-custom-field+++<wbr>+++**[invalid]**`
Field with error message:: `vaadin-custom-field+++<wbr>+++**[has-error-message]**`
Error message:: `vaadin-custom-field+++<wbr>+++**::part(error-message)**`
Error message text:: `vaadin-custom-field+++<wbr>+++** > [slot="error-message"]**`
