---
title: Board
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/board}/#/elements/vaadin-board[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/board/Board.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/board}/packages/board[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-board-flow-parent[Java]'
---

= Board

// tag::description[]
Board is a powerful and easy-to-use layout element for building responsive views.
// end::description[]
It reorders the components inside it on different screen sizes while maximizing the use of available space.


[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/board/board-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/demo/component/board/example-indicator.ts[group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/demo/component/board/example-chart.ts[group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/board/BoardBasic.java[render,tags=snippet,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/board/ExampleIndicator.java[group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/board/ExampleChart.java[group=Java]
----
endif::[]
--

Use Board to create responsive views and dashboards that work on any screen size.

== Responsive

Board is responsive by default, meaning that it doesn't require any custom development.
Its layout is automatically optimized and adjusted based on the screen size, ensuring that the components utilize all available space.

== Rows & Columns

Board is made up of rows.
Each row supports up to four columns and can contain up to four components.

=== Nested Rows

Rows can be nested for finer-grained control of how certain areas of the layout behave on resize, and how they are rendered.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/board/board-nested.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/demo/component/board/example-indicator.ts[group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/demo/component/board/example-chart.ts[group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/board/BoardNested.java[render,tags=snippet,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/board/ExampleIndicator.java[group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/board/ExampleChart.java[group=Java]
----
endif::[]
--

=== Column Wrapping

Columns automatically wrap on to new lines as the viewport narrows.
The wrapping behavior for a row with four columns and four components is shown below.

[IMPORTANT]
Use the draggable split handle to resize the layout and see how the columns wrap.


[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/board/board-column-wrapping.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/board/BoardColumnWrapping.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

--

=== Column Span

By default, the components in a row share the space equally.
A component can be made to stretch across two or three columns by setting its column span.

The possible combinations are shown below:

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/board/board-column-span.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/board/BoardColumnSpan.java[render,tags=snippet,indent=0,group=Java]

...

include::{root}/src/main/java/com/vaadin/demo/component/board/BoardColumnSpan.java[render,tags=createBoard,indent=0,group=Java]
----
endif::[]
--

== Breakpoints

Board adjusts its layout based on the layout container width.
The following three container widths, called breakpoints, trigger a layout change:

|===
| Breakpoint | Container width | Max number of columns

| large
| ≥ 960 pixels
| 4

| medium
| 600–959 pixels
| 2 or 3footnote:[A row with three equal-width components doesn't wrap until the small breakpoint.]

| small
| < 600 pixels
| 1
|===

Breakpoints can be customized by overriding the CSS custom properties `--vaadin-board-width-small` and `--vaadin-board-width-medium`.

=== Breakpoint-Specific Styling

You can apply different styles for each breakpoint, for example to change the font size and space between components.

[IMPORTANT]
Use the draggable split handle to resize the layout and see how the board styling changes at different breakpoints.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/board/board-breakpoints.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,css]
----
include::{root}/frontend/themes/docs/board.css[tags=breakpoint,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/board/BoardBreakpoints.java[render,tags=snippet,indent=0,group=Java]
----

[source,css]
----
include::{root}/frontend/themes/docs/board.css[tags=breakpoint,indent=0,group=Java]
----
endif::[]
--
