---
title: Password Field
description: Password Field is an input field for entering passwords.
---


= Password Field

The input is masked by default, so onlookers can't see the password as it's entered. The masking can be toggled, though, by using an optional reveal button.

On mobile devices, the last entered letter is shown for a brief moment, while the user is entering the password, for them to ensure what was entered is correct. This is useful since users tend to make more errors with the small keyboard when using mobile devices.

[source,tsx]
----
<PasswordField label="Password" value="Ex@mplePassw0rd" />
----

// TODO: define {article} and fix relative link
:component-name: Password Field
:text-field-features: true
include::../_shared.asciidoc[tag=field-features]


== Reveal Button

The reveal button allows the user to disable masking of the password, and thereby see the value they have entered. This is especially helpful on mobile devices, as mentioned already, where typing is more error-prone. In cases where this feature isn't desired, though, you can disable it.

[source,tsx]
----
<PasswordField
  label="Password"
  value="Ex@mplePassw0rd"
  revealButtonHidden
/>
----

:component-path: password-field
include::{articles}/react/components/_vaadindocs.adoc[]
