---
title: Time Picker
description: Time Picker is an input field for entering or selecting a specific time.
---

= Time Picker

[source,tsx]
----
<TimePicker label="Alarm" value="07:00" />
----

The time can be entered directly using a keyboard or by choosing a value from a set of predefined options presented in an overlay. The overlay opens when the field is clicked or any input is entered when the field is focused.

// TODO: define {article} and fix relative link
:component-name: TimePicker
:text-field-features: true
include::../_shared.asciidoc[tag=field-features]

== Step

Time Picker's step parameter defines the interval (in seconds) between the items displayed in the overlay.
It also specifies the amount by which the time increases/decreases using the kbd:[Up]/kbd:[Down] arrow keys (when the overlay is disabled).

The default step is one hour (that is, `3600`).
Unlike <<../number-field#,Number Field>>, Time Picker accepts values that don't align with the specified step.

[source,tsx]
----
<TimePicker label="Meeting time" step={60 * 30} value="12:30" />
----

.Use common steps
[NOTE]
The step must divide an hour or day evenly.
For example, _"15 minutes"_, _"30 minutes"_ and _"2 hours"_ are valid steps, whereas _"42 minutes"_ isn't.

The displayed time format changes based on the step.

[source,tsx]
----
<TimePicker label="Meeting time" step={1} value="15:45:08" />
----

:component-path: time-picker
include::{articles}/react/components/_vaadindocs.adoc[]
