---
title: Styling
order: 50
---
= Styling

include::../_styling-section-intros.adoc[tag=selectors]

[Horizontal, labelwidth=33]
Root element:: `vaadin-menu-bar`


=== States
[Horizontal, labelwidth=33]
Disabled:: `vaadin-menu-bar+++<wbr>+++**[disabled]**`
Single button visible:: `vaadin-menu-bar+++<wbr>+++**[has-single-button]**`


=== Buttons
[Horizontal, labelwidth=33]
Button element:: `vaadin-menu-bar-button`
Button text:: `vaadin-menu-bar-button+++<wbr>+++**::part(label)**`
Hovered button:: `vaadin-menu-bar-button+++<wbr>+++**:hover**`
Focused button:: `vaadin-menu-bar-button+++<wbr>+++**[focused]**`
Disabled button:: `vaadin-menu-bar-button+++<wbr>+++**[disabled]**`
Button with a menu:: `vaadin-menu-bar-button+++<wbr>+++**[aria-haspopup]**`
Button with opened menu:: `vaadin-menu-bar-button+++<wbr>+++**[expanded]**`
Overflow button:: `vaadin-menu-bar-button+++<wbr>+++**[slot="overflow"]**`
Overflow button icon:: `vaadin-menu-bar-button+++<wbr>+++**[slot="overflow"] > [aria-hidden]**`
Button rich content wrapper:: `vaadin-menu-bar-button+++<wbr>+++** > vaadin-menu-bar-item**`
Button icon:: `vaadin-menu-bar-button+++<wbr>+++** > vaadin-menu-bar-item > vaadin-icon**`


=== Overlay
[Horizontal, labelwidth=33]
Overlay element:: `vaadin-menu-bar-overlay`
Overlay background:: `vaadin-menu-bar-overlay+++<wbr>+++**::part(overlay)**`
Overlay content wrapper:: `vaadin-menu-bar-overlay+++<wbr>+++**::part(content)**`
Nested sub-menu overlay:: `vaadin-menu-bar-overlay+++<wbr>+++**[modeless]**`


=== Items
[Horizontal, labelwidth=33]
Item element:: `vaadin-menu-bar-item`
Hovered item:: `vaadin-menu-bar-item+++<wbr>+++**:hover**`
Focused item:: `vaadin-menu-bar-item+++<wbr>+++**[focused]**`
Disabled item:: `vaadin-menu-bar-item+++<wbr>+++**[disabled]**`
Item with a nested sub-menu:: `vaadin-menu-bar-item+++<wbr>+++**[aria-haspopup]**`
Item with expanded sub-menu:: `vaadin-menu-bar-item+++<wbr>+++**[expanded]**`
Item content wrapper:: `vaadin-menu-bar-item+++<wbr>+++**::part(content)**`
Checked item:: `vaadin-menu-bar-item+++<wbr>+++**[menu-item-checked]**`
Checked item indicator:: `vaadin-menu-bar-item+++<wbr>+++**[menu-item-checked]::part(checkmark)**`
Checked item indicator icon:: `vaadin-menu-bar-item+++<wbr>+++**[menu-item-checked]::part(checkmark)::before**`
Submenu indicator icon:: `vaadin-menu-bar-item+++<wbr>+++**::after**`
Separator element:: `vaadin-menu-bar-overlay+++<wbr>+++** [role="separator"]**`
