---
title: Styling
page-title: How to style the Menu Bar component | Vaadin components
description: Styling API reference for the Menu Bar component.
meta-description: Customize the appearance of the Vaadin Menu Bar component to align with your application's theme.
order: 50
---
= Styling

include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-menu-bar`


=== States

Disabled:: `vaadin-menu-bar+++<wbr>+++**[disabled]**`
Single button visible:: `vaadin-menu-bar+++<wbr>+++**[has-single-button]**`


=== Buttons

Button element:: `vaadin-menu-bar-button`
Button text:: `vaadin-menu-bar-button+++<wbr>+++**::part(label)**`
Hovered button:: `vaadin-menu-bar-button+++<wbr>+++**:hover**`
Focused button:: `vaadin-menu-bar-button+++<wbr>+++**[focused]**`
Disabled button:: `vaadin-menu-bar-button+++<wbr>+++**[disabled]**`
Button with a menu:: `vaadin-menu-bar-button+++<wbr>+++**[aria-haspopup]**`
Button with opened menu:: `vaadin-menu-bar-button+++<wbr>+++**[expanded]**`
Overflow button:: `vaadin-menu-bar-button+++<wbr>+++**[slot="overflow"]**`
Overflow button icon:: `vaadin-menu-bar-button+++<wbr>+++**[slot="overflow"] > [aria-hidden]**`
Button rich content wrapper:: `vaadin-menu-bar-button+++<wbr>+++** > vaadin-menu-bar-item**`
Button icon:: `vaadin-menu-bar-button+++<wbr>+++** > vaadin-menu-bar-item > vaadin-icon**`


=== Sub-Menu

Sub-menu element:: `vaadin-menu-bar-submenu`
Sub-menu background:: `vaadin-menu-bar-submenu+++<wbr>+++**::part(overlay)**`
Sub-menu content wrapper:: `vaadin-menu-submenu+++<wbr>+++**::part(content)**`
Nested sub-menu:: `vaadin-menu-bar-submenu+++<wbr>+++**[modeless]**`


=== Items

Item element:: `vaadin-menu-bar-item`
Item content wrapper:: `vaadin-menu-bar-item+++<wbr>+++**::part(content)**`
Checked item indicator:: `vaadin-menu-bar-item+++<wbr>+++**[menu-item-checked]::part(checkmark)**`
Checked item indicator icon:: `vaadin-menu-bar-item+++<wbr>+++**[menu-item-checked]::part(checkmark)::before**`
Submenu indicator icon:: `vaadin-menu-bar-item+++<wbr>+++**::after**`
Separator element:: `vaadin-menu-bar-submenu+++<wbr>+++** [role="separator"]**`

==== Item States

Hovered item:: `vaadin-menu-bar-item+++<wbr>+++**:hover**`
Focused item:: `vaadin-menu-bar-item+++<wbr>+++**[focused]**`
Disabled item:: `vaadin-menu-bar-item+++<wbr>+++**[disabled]**`
Item with a nested sub-menu:: `vaadin-menu-bar-item+++<wbr>+++**[aria-haspopup]**`
Item with expanded sub-menu:: `vaadin-menu-bar-item+++<wbr>+++**[expanded]**`
Checked item:: `vaadin-menu-bar-item+++<wbr>+++**[menu-item-checked]**`
