---
title: Configuration
order: 4
layout: page
---

= Configuration

The Vaadin Observability distribution by default sets the service name as `vaadin` and disables default vaadin- and servlet instrumentation.

The default instrumentation is disabled as a Vaadin application, that is a single page application, sends different requests for the same page making the defaults less helpful.

== Instrumentation Configuration

Instrumentation can easily be configured in the `agent.properties` file that is used with the JavaAgent.

=== Service Configuration

`service` attributes have special handling and are used to differentiate traces form different servers that are still for the same service that exist at the same time (e.g. horizontally scaled services).

Service attributes are as follows:

* `service.name` is an attribute that is used to distinguish a service by name.
+
For Vaadin Observability this defaults to `vaadin`
* `service.namespace` helps to distinguish a group of services
* `service.instance.id` helps to distinguish instances of the same service that exist at the same time
+
Must be unique for each instance of the same `service.namespace`, `service.name` pair
* `service.version` semver version string of the service

Only `service.name` has a default value as it is the only one required.

For detailed information see https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/#service[Service]

=== Disabled Default Instrumentation

The by default disabled instrumentation modules are:

* java-http-client
* jetty
* jetty-httpclient
* servlet
* tomcat

To enable any of these, add to the `agent.properties` file the line `otel.instrumentation.${instrumentationName}.enabled=true`

