---
title: Configuration
order: 4
layout: page
---

= Configuration

The Vaadin Observability distribution by default sets the service name as `vaadin` and disables default vaadin- and servlet instrumentation.

The default instrumentation is disabled because a single-page Vaadin application sends different requests for the same page making the defaults less helpful.

== Instrumentation Configuration

Instrumentation can be configured in the `agent.properties` file that is used with the Java agent.

=== Service Configuration

`service` attributes have special handling and are used to differentiate traces form different servers that are still for the same service that exist at the same time (e.g. horizontally scaled services).

Service attributes are as follows:

* `service.name` is an attribute that is used to distinguish a service by name.
+
For Vaadin Observability this defaults to `vaadin`
* `service.namespace` helps to distinguish a group of services
* `service.instance.id` helps to distinguish instances of the same service that exist at the same time
+
Must be unique for each instance of the same `service.namespace`, `service.name` pair
* `service.version` Semantic Versioning string of the service version

Only `service.name` has a default value as it is the only one required.

For detailed information see https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/#service[Service]

=== Disabled Default Instrumentation

The by default disabled instrumentation modules are:

* java-http-client
* jetty
* jetty-httpclient
* servlet
* tomcat

To enable any of these, add this line to the `agent.properties` file:
[source,properties]
----
`otel.instrumentation.${instrumentationName}.enabled=true`
----

