---
title: Behavior-Driven Development
order: 100
---

= Behavior-Driven Development

Behavior-Driven Development (BDD) is a development methodology based on test-driven development, where development starts from writing tests for the software-to-be. BDD involves using a _ubiquitous language_ to communicate between business goals (i.e., the desired behavior) and tests to ensure that the software fulfills those goals.

The BDD process starts by collecting business requirements expressed as _user stories_, as is typical in agile methodologies. A user with a _role_ requests a _feature_ to gain a _benefit_.

Stories can be expressed as number of _scenarios_ that describe different cases of the desired behavior. Such a scenario can be formalized with the following three phases:

pass:[<!-- vale Vaadin.FirstPerson = NO -->]

* _Given_ that I have calculator open,

* _When_ I push calculator buttons,

* _Then_ the display should show the result.

pass:[<!-- vale Vaadin.FirstPerson = YES -->]


This kind of formalization is realized in the JBehave BDD framework for Java. The TestBench Demo includes a JBehave example, where the above scenario is written as the link:https://github.com/vaadin/testbench-demo/blob/master/src/test/java/com/vaadin/testbenchexample/bdd/CalculatorSteps.java[following test class]:

[.example]
--
[source,java]
----
<source-info group="CalculatorSteps.java"></source-info>
public class CalculatorSteps extends ChromeSteps {

    private KeypadElement calculator;

    @BeforeScenario
    public void setElements() {
        calculator = $(KeypadElement.class).first();
    }

    @When("I push $buttons")
    public void enter(String buttons) {
        calculator.calculate(buttons);
    }

    @Then("the display should show $result")
    public void displayShows(String result) {
        assertEquals(result, calculator.getDisplayValue());
    }
}
----
[source,java]
----
<source-info group="ChromeSteps.java"></source-info>
// extend TestBench helper class for extra testing features
public class ChromeSteps extends AbstractBrowserDriverTestBase {

    // open webpage before test
    @BeforeScenario(order = 100)
    public void beforeScenario() {
        getDriver().get("http://" + IPAddress.findSiteLocalAddress() + ":8080");
    }

}
----
--

This demo employs the page object defined for the application UI, as described in <<page-objects#,Creating Maintainable Tests using Page Objects>>. Such scenarios are included in one or more stories, which need to be configured in a class extending `JupiterStories`.

In this example, TestBench is used to manage `WebDriver` and browser configuration. This is done in the link:https://github.com/vaadin/testbench-demo/blob/master/src/test/java/com/vaadin/testbenchexample/bdd/SimpleBDDCalculationIT.java[SimpleBDDCalculationIT.java] class. It defines how story classes can be found dynamically by the class loader and how stories are reported.

For further information on this, see the JBehave website at https://jbehave.org/.


[discussion-id]`5115165C-951D-436A-8F3F-C7BB2F83A054`
