[discrete]
=== Changes affecting custom styling of components


[discrete]
==== Input field components

These changes apply to all input field components, with the exception of Checkbox. Please see sections for individual components for details and other component-specific changes.

[discrete]
===== Labels
Labels have been changed to slotted child elements.
While the `[part=”label”]` selector still works, some derived selectors may need to be adjusted.
The `:empty` selector no longer works correctly to distinguish empty and non-empty labels, and should be replaced by the `[has-label]` attribute selector:
[source,css]
----
/* Before */
[part=”label”]:not(:empty) {...}

/* After */
[has-label] [part="label"] {...}
/* Or, to target the slotted element itself */
[has-label] ::slotted(label) {...}
----

[discrete]
===== Error messages
Error messages have been changed to slotted child elements. While the `[part=”error-message”]` selector still works, some derived selectors may need to be adjusted. The `:empty` selector no longer works correctly on these and should be replaced with attribute selectors for the appropriate states:
[source,css]
----
/* Before */
[part="error-message"]:not(:empty) {...}

/* After */
[has-error-message] [part="error-message"] {...}
----

[discrete]
===== Required indicators
Required indicators now have their own shadow parts, instead of being pseudo-element children of the `label` part:
[source,css]
----
/* Before */
[part="label"]::after {...}

/* After */
[part="required-indicator"]::after {...}
----

[discrete]
===== Default text field width
The CSS property that defines the default width of text input fields was renamed to `vaadin-field-default-width`:
[source,css]
----
/* Before */
--vaadin-text-field-default-width: 20em;

/* After */
--vaadin-field-default-width: 20em;
----



[discrete]
===== Text field derivatives refactored
The following components used to be based on the Text Field component, and were mostly styled through it:

* Combo Box
* Date Picker
* Number Field and Integer Field
* Select
* Time Picker

These have now been refactored to no longer be based on Text Field, which means that they need to be styled separately from it. Please see upgrade guides for each of these separately below.



[discrete]
==== Button

The styling of disabled buttons has changed from reduced opacity to a separate grayscale coloring, which may affect custom styling of buttons: secondary and tertiary buttons now use `--lumo-disabled-text-color` for text, while primary buttons use `--lumo-contrast-30pct` for background and `--lumo-base-color for text`.



[discrete]
==== Charts

The default colors in charts have changed in Vaadin 23 to better match the Lumo and Material themes. You can revert to the old color scheme by switching to the “classic” theme:

[source,java]
----
chart.getElement().setAttribute("theme", "classic");
----



[discrete]
==== Checkbox and Radio Button

Unlike most input field components, Checkboxes and Radio Buttons no longer have a `label` shadow part, so the label must be targeted as a child element:
[source,css]
----
/* Before */
[part="label"] {...}

/* After */
::slotted(label) {...}
----



[discrete]
==== Checkbox Group

See changes common to all <<Input field components>>.



[discrete]
==== Combo Box

* See changes common to all <<Input field components>>.
* See changes to <<Text Field>>, as these also apply to Combo Box.

[discrete]
===== Styles no longer inherited from Text Field
This component is no longer based on Text Field, so all styles previously applied via Text Field need to be applied to it separately:

* Using a theme folder, place the styles in `/components/vaadin-combo-box.css`
* Or, in Flow, with `@CssImport(..., themeFor="vaadin-combo-box")`

[discrete]
===== Overlay and list items
The selection checkmarks in them have been moved to their own shadow parts:
[source,css]
----
/* Before */
:host::before {...}

/* After */
[part="checkmark"]::before {...}
----

[discrete]
===== Miscellaneous
The `vaadin-text-field-container` internal wrapper has been renamed `vaadin-combo-box-container`. _(Note: this is an internal element whose styling is not supported)_.


[discrete]
==== Confirm Dialog

Styles should now target the `vaadin-confirm-dialog-overlay` element instead of `vaadin-confirm-dialog`.



[discrete]
==== CRUD

Depending on the editor position, styles for the CRUD’s editor should now target either the `vaadin-crud` element itself (for _aside_ and _bottom_ positions) or `vaadin-crud-dialog-overlay` (for the _overlay_ position), instead of `vaadin-dialog-layout`.



[discrete]
==== Date Picker

* See changes common to all <<Input field components>>.
* See changes to <<Text Field>>, as those also apply to Date Picker.

[discrete]
===== Styles no longer inherited from Text Field
This component is no longer based on Text Field, so all styles previously applied via Text Field need to be applied to it separately:

* Using a theme folder, place the styles in `/components/vaadin-date-picker.css`
* Or, in Flow, with `@CssImport(..., themeFor="vaadin-date-picker")``

[discrete]
===== Miscellaneous
* The `vaadin-text-field-container` internal wrapper has been renamed `vaadin-date-picker-container`. _(Note: this is an internal element whose styling is not supported)._
* The calendar overlay’s week number text color has changed from `--lumo-tertiary-text-color` to `--lumo-secondary-text-color`.



[discrete]
==== Date Time Picker

* See changes common to all <<Input field components>>.
* See changes to <<Text Field>>, as those also apply to Date Time Picker.

[discrete]
===== Styles no longer inherited from Custom Field
This component is no longer based on Custom Field, so all styles previously applied via Custom Field need to be applied to Date Time Picker separately:

* Using a theme folder, place the styles in `/components/vaadin-date-time-picker.css`
* Or, in Flow, with `@CssImport(..., themeFor="vaadin-date-time-picker")`

[discrete]
===== Slotted Date Picker and Time Picker
The Date Picker and Time Picker sub-fields are now slotted children of the Date Time Picker:
[source,css]
----
/* Before */
[part="date"] {...}
[part="time"] {...}

/* After */
::slotted([slot="date-picker"]) {...}
::slotted([slot="time-picker"]) {...}
----

The internal `slot-container` wrapper has been renamed `slots`. _(Note: this is an internal element whose styling is not supported)._



[discrete]
==== Grid

The color and opacity of inactive sort indicators was changed from `--lumo-body-text-color` at 0.2 opacity (0.6 on hover) to `--lumo-tertiary-text-color` (`--lumo-body-text-color` on hover) at 1.0 opacity.



[discrete]
==== Horizontal and Vertical Layout

Vertical Layout and Horizontal Layout refactored to use the css `gap` property for spacing between components, instead of margins. This makes it possible to use `flex-wrap` for wrapping the contents of these layouts without spacing conflicts. Custom margins applied to components in these layouts will now be applied _in addition to_ the spacing instead of _overriding_ the spacing.



[discrete]
==== Icons

Icons are now rendered as `vaadin-icon` elements instead of `iron-icon`.
[source,css]
----
/* Before */
::slotted(iron-icon) {...}

/* After */
::slotted(vaadin-icon) {...}
----



[discrete]
==== Number Field and Integer Field

* See changes common to all <<Input field components>>.
* See changes to <<Text Field>>, as those also apply to Number Field and Integer Field.

[discrete]
===== Styles no longer inherited from Text Field
This component is no longer based on Text Field, so all styles previously applied via Text Field need to be applied to it separately:

* Using a theme folder, place the styles in `/components/vaadin-number-field.css`
* Or, in Flow, with `@CssImport(..., themeFor="vaadin-number-field")`



[discrete]
==== Password Field

All styles still inherited from <<Text Field>>, so the same changes apply to it.



[discrete]
==== Radio Button Group

* See changes common to all <<Input field components>>.
* See <<Checkbox and Radio Button>> for changes to Radio Button.



[discrete]
==== Select

See changes common to all <<Input field components>>.

[discrete]
===== Styles no longer inherited from Text Field
This component is no longer based on Text Field, so all styles previously applied via Text Field need to be applied to it separately:

* Using a theme folder, place the styles in `/components/vaadin-select.css`
* Or, in Flow, with `@CssImport(..., themeFor="vaadin-select")``

[discrete]
===== New list item element
List items are now `vaadin-select-item` elements instead of `vaadin-item` (although they extend the latter, so styles applied to `vaadin-item` apply to `vaadin-select-item` as well).
[source,css]
----
/* Before (in styles.css) */
vaadin-select-overlay vaadin-item {...}

/* After (in styles.css) */
vaadin-select-item {...}
----

[discrete]
===== Selection checkmarks
The selection checkmarks in them have been moved to their own shadow parts:
[source,css]
----
/* Before */
:host::before {...}

/* After */
[part="checkmark"]::before {...}
----

[discrete]
===== Value displayed in field
The value displayed in the field uses the new item element too, and is now a child of a new `vaadin-select-value-button` internal component, and is easiest to access as a regular child element of Select:
[source,css]
----
/* Before (in vaadin-item) */
[part="value"] vaadin-item {...}

/* After (in styles.css) */
vaadin-select vaadin-select-item {...}
----

[discrete]
===== Placeholder text
The value placeholder text needs to be targeted a bit differently from other similar fields:
[source,css]
----
/* Before */
[part="value"]:placeholder-shown {...}

/* After */
::slotted([placeholder]) {...}
----



[discrete]
==== Tabs

The color of inactive tabs has been changed from `--lumo-contrast-60pct` to `--lumo-secondary-text-color`.



[discrete]
==== Text Area

See changes common to all <<Input field components>>.

[discrete]
===== Slotted native input element
The native `<textarea>` element is now a slotted child element, and the value shadow part has been removed:
[source,css]
----
/* Before */
[part="value"] {...}

/* After */
::slotted(textarea) {...}
----

This also affects selectors for the placeholder text:
[source,css]
----
/* Before */
[part="value"]::placeholder {...}
/* or */
[part="value"]:placeholder-shown {...}

/* After */
::slotted(textarea:placeholder-shown) {...}
----



[discrete]
==== Text Field

See changes common to all <<Input field components>>.

[discrete]
===== Other text input components no longer based on Text Field
Note that the following components that used to be based on Text Field no longer are so, and need to be styled separately instead of inheriting styles from Text Field:

* Combo Box
* Date Picker
* Number Field
* Select
* Time Picker

However, the same structural changes were made to these as to Text Field, so the following changes and corresponding instructions apply to them as well.

[discrete]
===== Slotted native input element
The native `<input>` element is now a slotted child element, and the value shadow part has been removed:
[source,css]
----
/* Before */
[part="value"] {...}

/* After */
::slotted(input) {...}
----

This also affects selectors for the placeholder text:
[source,css]
----
/* Before */
[part="value"]::placeholder {...}
/* or */
[part="value"]:placeholder-shown {...}

/* After */
::slotted(input:placeholder-shown) {...}
----

[discrete]
===== Placeholder text color
Placeholder text now uses the `--lumo-secondary-text-color` color property, instead of `--lumo-body-text-color` with 0.5 opacity.



[discrete]
==== Time Picker

* See changes common to all <<Input field components>>.
* See changes to <<Text Field>>, as those also apply to Number Field and Integer Field.

[discrete]
===== Styles no longer inherited from Text Field
This component is no longer based on Text Field, so all styles previously applied via Text Field need to be applied to it separately:

* Using a theme folder, place the styles in `/components/vaadin-time-picker.css`
* Or, in Flow, with `@CssImport(..., themeFor="vaadin-time-picker")`



[discrete]
==== Upload

The `clear-button` part was renamed `remove-button`:
[source,css]
----
/* Before */
[part="clear-button"] {...}

/* After */
[part="remove-button"] {...}
----

