---
tab-title: Usage
layout: tabbed-page
title: Split Layout
description: How to set up a split layout of two content areas in which items may be selected and dragged between each.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/split-layout}/#/elements/vaadin-split-layout[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/splitlayout/SplitLayout.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/split-layout}/packages/split-layout[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-split-layout-flow-parent[Java]'
---


= Split Layout

// tag::description[]
Split Layout is a component with two content areas and a draggable split handle between them.
// end::description[]
This page explains how to add this component to your project and how to configure it.
 
[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/splitlayout/split-layout-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutBasic.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/splitlayout/react/split-layout-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

== Orientation

The default orientation is horizontal, placing the content areas side by side.
The orientation can also be vertical.

Orientation should be set based on the content and the screen size.
The user can also be allowed to choose which orientation they want to use.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/splitlayout/split-layout-orientation.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutOrientation.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/splitlayout/react/split-layout-orientation.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

== Splitter Position

The initial splitter position is determined by the default size of the two content area components.
Their height and width affect the position when using a vertical and horizontal orientation, respectively.

The initial split position can also be explicitly set using a percentage value.
When using vertical orientation, the split layout must have an explicit height for this to work.
This can be either an absolute or a percentage value.
When using a percentage value, ensure that ancestors have an explicit height as well.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/splitlayout/split-layout-initial-splitter-position.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutInitialSplitterPosition.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/splitlayout/react/split-layout-initial-splitter-position.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

The splitter respects the minimum and maximum size of the content area components.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/splitlayout/split-layout-min-max-size.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutMinMaxSize.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/splitlayout/react/split-layout-min-max-size.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

The split can be adjusted programmatically, for example by using a Button.
This is useful when the user wants to toggle between certain positions.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/splitlayout/split-layout-toggle.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutToggle.java[render,tags=snippet,indent=0,group=Java]

...

include::{root}/src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutToggle.java[render,tags=setstyles,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/splitlayout/react/split-layout-toggle.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

== Theme Variants

Split Layout has two theme variants: `small` and `minimal`.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/splitlayout/split-layout-theme-small.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutThemeVariants.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/splitlayout/react/split-layout-theme-small.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

The `small` theme variant makes the divider smaller.
The `minimal` theme variant hides the visual divider.
Both variants only show the split handle on hover and aren't ideal for touch devices.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/splitlayout/split-layout-theme-minimal.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutMinimalThemeVariants.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/splitlayout/react/split-layout-theme-minimal.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

When using the `minimal` theme variant, it's recommended to somehow suggest the split between the two sides, for example by styling one side as a layer on top of the other.

While these variants reduce visual clutter, they make it less obvious to the user that the content is resizable.

== Best Practices

* Don't use Split Layout when either content area has, or should have, a fixed size.

* Split Layouts can be difficult to use in responsive applications, due to the splitter position being percentage-based, so that the content scales with the viewport.

* Use Split Layout to give the user the ability to adjust the layout.
  However, if only specific positions, such as collapsed and expanded, are useful to the user, use a toggle button instead.
  Non-adjustable layouts should use Ordered Layouts or Flex Layout.


[discussion-id]`10387B24-0DDF-4FC8-B5F9-B6319633D354`

++++
<style>
[class^=PageHeader-module-descriptionContainer] {display: none;}
</style>
++++
