---
title: Styling
page-title: How to style the Split Layout component | Vaadin
description: Styling API reference for the Split Layout component.
meta-description: Learn various ways to customize and style the Vaadin Split Layout component in your applications.
order: 50
---
= Split Layout Styling

== Style Variants

Split Layout supports the following style variants:

[cols="1,3,1"]
|===
| Variant | Description | Supported by

|`small`
|Makes the visual divider smaller
|Aura, Lumo

|`minimal`
|Hides the visual divider completely
|Lumo

|===

=== Small

The `small` theme variant makes the visual divider smaller, giving more space to the content areas.

Please note that this variant shows the split handle only on hover, which isn't ideal for touch devices.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/splitlayout/split-layout-theme-small.ts[render,tags=snippet,indent=0,group=Lit]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutThemeVariants.java[render,tags=snippet,indent=0,group=Flow]
----

[source,tsx]
----
include::{root}/frontend/demo/component/splitlayout/react/split-layout-theme-small.tsx[render,tags=snippet,indent=0,group=React]
----

--

=== Minimal

The `minimal` style variant hides the visual divider completely. When using this variant, it's still recommended to somehow indicate the split between the two sides, for example by styling one side as a layer on top of the other.

Please note that this variant shows the split handle only on hover, which isn't ideal for touch devices.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/splitlayout/split-layout-theme-minimal.ts[render,tags=snippet,indent=0,group=Lit]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutMinimalThemeVariants.java[render,tags=snippet,indent=0,group=Flow]
----

[source,tsx]
----
include::{root}/frontend/demo/component/splitlayout/react/split-layout-theme-minimal.tsx[render,tags=snippet,indent=0,group=React]
----

--

include::../_styling-section-theming-props.adoc[tag=style-properties]

[cols="2,1"]
|===
| Property | Supported by

| `--vaadin-split-layout-handle-background`
| Aura, Lumo

| `--vaadin-split-layout-handle-size`
| Aura, Lumo

| `--vaadin-split-layout-handle-target-size`
| Aura, Lumo

| `--vaadin-split-layout-splitter-background`
| Aura, Lumo

| `--vaadin-split-layout-splitter-size`
| Aura, Lumo

| `--vaadin-split-layout-splitter-target-size`
| Aura, Lumo

|===

include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-split-layout`


=== States

Horizontal split:: `vaadin-split-layout+++<wbr>+++**[orientation="horizontal"]**`
Vertical split:: `vaadin-split-layout+++<wbr>+++**[orientation="vertical"]**`


=== Parts

Splitter bar:: `vaadin-split-layout+++<wbr>+++**::part(splitter)**`
Splitter drag handle:: `vaadin-split-layout+++<wbr>+++**::part(handle)**`
Splitter visual handle:: `vaadin-split-layout+++<wbr>+++**::part(handle)::after**`
First content:: `vaadin-split-layout+++<wbr>+++** > [slot="primary"]**`
Second content:: `vaadin-split-layout+++<wbr>+++** > [slot="secondary"]**`
