---
title: Tree Grid
layout: tabbed-page
tab-title: Usage
page-links: \
https://github.com/vaadin/vaadin-flow-components/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-grid-flow}\[Flow {moduleMavenVersion:com.vaadin:vaadin-grid-flow}], \
https://github.com/vaadin/vaadin-grid/releases/tag/v{moduleNpmVersion:vaadin-grid}\[Web Component {moduleNpmVersion:vaadin-grid}]
section-nav: incomplete
---

= Tree Grid

// tag::description[]
Tree Grid is a component for displaying hierarchical tabular data grouped into expandable and collapsible nodes.

// end::description[]

[.example]
--

[source,typescript]
----
include::../../../../frontend/demo/component/treegrid/treegrid-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::../../../../src/main/java/com/vaadin/demo/component/treegrid/TreeGridBasic.java[render,tags=snippet,indent=0,group=Java]
// ----

// [source, java]
// ----
// include::../../../../src/main/java/com/vaadin/demo/domain/Person.java[group=Java,tags=snippet]
// ----

--

.Work In Progress
[NOTE]
====
The usage examples for this component are currently in progress. In the meantime, you can view the previous examples for the web component and the Java/Flow component.

[.buttons]
- https://vaadin.com/components/vaadin-tree-grid/html-examples[Web Component Examples]
- https://vaadin.com/components/vaadin-tree-grid/java-examples[Java Component Examples]
====

.Features shared with Grid
[NOTE]
====
Tree Grid is an extension of the Grid component and all of Grid’s features are available in Tree Grid as well.
====


== Tree Column

The tree column is a column that contains the toggles for expanding and collapsing nodes. Nodes are opened and closed by clicking a tree column’s cell. They can also be toggled programmatically.

[.example]
--

[source,typescript]
----
include::../../../../frontend/demo/component/treegrid/treegrid-column.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::../../../../src/main/java/com/vaadin/demo/component/treegrid/TreeGridColumn.java[render,tags=snippet,indent=0,group=Java]
// ----

// [source, java]
// ----
// include::../../../../src/main/java/com/vaadin/demo/domain/Person.java[group=Java,tags=snippet]
// ----

--

== Rich Content

Like Grid, Tree Grid supports rich content.

[.example]
--

[source,typescript]
----
include::../../../../frontend/demo/component/treegrid/treegrid-rich-content.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::../../../../src/main/java/com/vaadin/demo/component/treegrid/TreeGridRichContent.java[render,tags=snippet,indent=0,group=Java]
// ----

// [source, java]
// ----
// include::../../../../src/main/java/com/vaadin/demo/domain/Person.java[group=Java,tags=snippet]
// ----


== Best Practises

Tree Grid is not meant to be used as a navigation menu.

== Related Components

[cols="1,2"]
|===
|Component |Usage Recommendations

|<<../grid#,Grid>>
|Component for showing tabular data.

|<<../gridpro#,Grid Pro>>
|Component for showing and editing tabular data.

|<<../crud#,CRUD>>
|Component for creating, displaying, updating and deleting tabular data.

|===
