---
title: Getting Started
tab-title: Overview
order: 1
layout: tabbed-page
---

[[designer.installing.environment]]
= Getting Started with Vaadin Designer


== Download a Vaadin Project

To begin, download and import an empty Vaadin starter project.
This starter project is used throughout this tutorial to add views created with Vaadin Designer.

Click on the following button to download the starter application (zip file):

https://github.com/vaadin/designer-tutorial/archive/latest-initial.zip[Download starter,role="button secondary water"]

Next, extract the downloaded project, and import it as a Maven project into IntelliJ IDEA or Eclipse.

== Install Designer

Vaadin Designer can work with either IntelliJ IDEA or Eclipse.
Follow the Designer installation instructions for your IDE.
The tutorial uses IntelliJ IDEA, but everything demonstrated is also available in Eclipse.

xref:intellij#[IntelliJ IDEA, role="button secondary water"] or xref:eclipse#[Eclipse, role="button secondary water"]
