---
title: Getting Started
tab-title: Overview
order: 1
layout: tabbed-page
---

[[designer.installing.environment]]
= Getting Started With Vaadin Designer

== Prerequisites

Before you can start developing a Vaadin application with Designer, you need to install the necessary development tools and set up a Vaadin project.

Follow the first articles of the xref:{articles}/flow/tutorial#[In-Depth Course]:

. xref:{articles}/flow/tutorial/project-setup#[Project Setup]
. xref:{articles}/flow/tutorial/components-and-layouts#[Components and Layouts]
. xref:{articles}/flow/tutorial/database-access#[Accessing the Database]

As an alternative, you can skip the steps above and download the end result of directly: https://github.com/vaadin-learning-center/crm-tutorial/archive/03-database-and-backend.zip[download the project as a zip from GitHub].

== Install Designer

Next, follow the Designer installation instructions for your IDE.
The tutorial uses IntelliJ IDEA, but everything demonstrated is also available in Eclipse.

xref:intellij#[IntelliJ IDEA, role="button secondary water"] or xref:eclipse#[Eclipse, role="button secondary water"]

.Google Chrome is required
[IMPORTANT]
When you open a design file with Designer, the source code shows in your IDE, while the visual editor opens up in the Chrome browser. https://www.google.com/chrome/[Install Google Chrome] if you haven't already.

.Node.js not detected on macOS
[CAUTION]
====
On macOS, you might encounter an issue where Designer is not able to detect Node.js on our system path.
A workaround is to create a symbolic link, for example:

[source,terminal]
sudo ln -s /Users/username/.nvm/versions/node/v14.15.0/bin/node /usr/local/bin/

See https://github.com/vaadin/designer/issues/2377[GitHub issue] for more information.
====
