---
tab-title: Usage
layout: tabbed-page
title: Popover
page-title: Popover component | Vaadin components
description: Popover is a generic overlay whose position is anchored to an element in the UI.
meta-description: Use the Vaadin Popover component as an overlay whose position is anchored to an element in the user interface.
version: since:com.vaadin:vaadin@V24.5
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/popover}/#/elements/vaadin-popover[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/popover/Popover.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/popover}/packages/popover[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-popover-flow-parent[Java]'
---

= Popover

// tag::description[]
A generic overlay whose position is anchored to an element in the UI.
// end::description[]

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/popover/popover-notification-panel.ts[render,tags=snippet,indent=0,group=Lit]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/popover/PopoverNotificationPanel.java[render,tags=snippet,indent=0,group=Flow]
----

[source,tsx]
----
include::{root}/frontend/demo/component/popover/react/popover-notification-panel.tsx[render,tags=snippet,indent=0,group=React]
----

[source,css]
----
include::{root}/frontend/themes/docs/popover-notification-panel.css[]
----
--

Popovers support focusable, interactive content, and can be used to build virtually any type of anchored overlays from custom drop-down fields and drop-down buttons to and interactive tooltips.

The popover’s position is anchored to an element in the UI, called the *target element*, by calling `setTarget()`. The actual content of the popover's overlay is added to it as with any other component container.

Popovers differ from <<../dialog#,Dialogs>> in that they are visually anchored to a target element, and they differ from <<../tooltip#,Tooltips>> in that they can be focused and support rich, interactive content.

== Opening and Closing

Popovers can be configured to open and close based on different pointer and keyboard based triggers. See <<typical-use-cases, Typical Use Cases>> for examples.

=== Opening Triggers

Three target element triggers can be configured to open the popover:

- *Click*: clicking the target element, or pressing kbd:[Space] when the target element has focus (*default*)
- *Hover*: hovering over the target element
- *Focus*: focusing the target element

[.example.show-code]
--

[source,java]
----
<source-info group="Flow"></source-info>
Popover popover = new Popover();
popover.setOpenOnClick(false);
popover.setOpenOnHover(true);
popover.setOpenOnFocus(true);
----

[source,typescript]
----
<source-info group="Lit"></source-info>
<vaadin-popover .trigger="${['hover', 'focus']}"></vaadin-popover>
----

[source,tsx]
----
<source-info group="React"></source-info>
<Popover trigger={['hover', 'focus']} />
----

--

All three triggers can be enabled simultaneously. If no opening trigger is enabled, the popover can only be opened programmatically.

The hover and focus opening triggers have a configurable opening delay.

[.example.show-code]
--

[source,java]
----
<source-info group="Flow"></source-info>
Popover popover = new Popover();
popover.setHoverDelay(500);
popover.setFocusDelay(500);
----

[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-popover hover-delay="500" focus-delay="500"></vaadin-popover>
----

[source,tsx]
----
<source-info group="React"></source-info>
<Popover hoverDelay={500} focusDelay={500} />
----

--

=== Closing Triggers

The following triggers close the popover by default:

- *Target click*: Clicking the target element (non-modal popovers only)
- *Outside click*: clicking anywhere outside the overlay (can be disabled)
- *Esc*: pressing kbd:[Esc] (can be disabled)

[.example.show-code]
--

[source,java]
----
<source-info group="Flow"></source-info>
Popover popover = new Popover();
popover.setCloseOnEsc(false);
popover.setCloseOnOutsideClick(false);
----

[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-popover no-close-on-esc no-close-on-outside-click></vaadin-popover>
----

[source,tsx]
----
<source-info group="React"></source-info>
<Popover noCloseOnEsc noCloseOnOutsideClick />
----

--

Additionally:

- When opened on hover, the popover closes on mouseout, i.e. when the pointer leaves the target element and the overlay.
- When opened on focus, the popover closes on blur, i.e. when focus is no longer on the target element or in the overlay.

The mouseout closing trigger has a configurable delay.

[.example.show-code]
--

[source,java]
----
<source-info group="Flow"></source-info>
Popover popover = new Popover();
popover.setHideDelay(500);
----

[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-popover hide-delay="500"></vaadin-popover>
----

[source,tsx]
----
<source-info group="React"></source-info>
<Popover hideDelay={500} />
----

--


=== Auto Focus

Keyboard focus can be automatically moved to the Popover when it opens. This is recommended for popovers with interactive content that the user is expected to interact with. Modal popovers have auto-focus behavior by default. Popovers opened with hover or focus should not use auto-focus.

[.example.show-code]
--

[source,java]
----
<source-info group="Flow"></source-info>
Popover popover = new Popover();
popover.setAutofocus(true);
----

[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-popover autofocus></vaadin-popover>
----

[source,tsx]
----
<source-info group="React"></source-info>
<Popover autofocus />
----

--


== Positioning

By default, popovers open below their target element, horizontally centered to its midpoint, but the positioning options allow this to be changed to any edge or corner, depending on what is most appropriate for the use case.

The popover’s position is automatically maintained if the target element scrolls within the viewport. If there is insufficient space in the viewport for the desired positioning, the popover automatically shifts to fit within the viewport.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/popover/popover-positioning.ts[render,tags=snippet,indent=0,group=Lit]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/popover/PopoverPositioning.java[render,tags=snippet,indent=0,group=Flow]
----

[source,tsx]
----
include::{root}/frontend/demo/component/popover/react/popover-positioning.tsx[render,tags=snippet,indent=0,group=React]
----
--

=== Target Gap

The distance between the popover and the target element can be customized by setting the following CSS properties on the Popover component:

- `--vaadin-popover-offset-top`
- `--vaadin-popover-offset-bottom`
- `--vaadin-popover-offset-start`
- `--vaadin-popover-offset-end`

=== Target Arrow

Popovers can render a wedge-shaped arrow tip pointing at the target element.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/popover/popover-arrow.ts[render,tags=snippet,indent=0,group=Lit]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/popover/PopoverArrow.java[render,tags=snippet,indent=0,group=Flow]
----

[source,tsx]
----
include::{root}/frontend/demo/component/popover/react/popover-arrow.tsx[render,tags=snippet,indent=0,group=React]
----
--

== Configuring Delays

The delay before popover opens can be configured separately for hover and focus. There is no delay
before the popover appears on click or when opening programmatically.

The delay before popover closes -- when the pointer leaves the target element -- can also be configured separately. On blur, though, the popover is closed immediately to avoid confusion when focusing another element.

[.example.show-code]
--
ifdef::flow[]
[source,java]
----
// Global delay configuration:
Popover.setDefaultFocusDelay(2000);
Popover.setDefaultHoverDelay(1000);
Popover.setDefaultHideDelay(1000);

// Overriding delays for a particular popover:
Popover popover = new Popover();
popover.setHoverDelay(0);
----
endif::[]

ifdef::lit[]
[source,typescript]
----
import { Popover } from '@vaadin/popover';

// Global delay configuration:
Popover.setDefaultFocusDelay(2000);
Popover.setDefaultHoverDelay(1000);
Popover.setDefaultHideDelay(1000);

// Overriding delays for a particular popover:
<vaadin-popover .hoverDelay=${500}></vaadin-popover>
----
endif::[]

ifdef::react[]
[source,tsx]
----
import { Popover } from '@vaadin/popover';

// Global delay configuration:
Popover.setDefaultFocusDelay(2000);
Popover.setDefaultHoverDelay(1000);
Popover.setDefaultHideDelay(1000);

// Overriding delays for a particular popover:
<Popover hoverDelay={500} />
----
endif::[]

--


== Dimensions

By default, the Popover’s size is determined by its contents, but an explicit width and height can be set on the Popover itself.

Contents that exceed the width of the popover will scroll.

The maximum width of popovers is limited to the width of the viewport, minus a small margin that can be customized with CSS by overriding the `inset` property of the `vaadin-popover-overlay` element.

== Modality

A modal Popover blocks the user from interacting with the rest of the user interface while open, automatically moves focus from the target element to the Popover, and traps keyboard focus within it.

When combined with an outside click closing trigger, modality prevents accidentally triggering other UI elements when clicking outside the Popover to close it.

By default, modal popovers do not render a modality curtain (or _backdrop_), but one can be enabled separately. A modality curtain can be useful for de-emphasizing the UI in the background and to give a visual indication that the rest of the UI is blocked from user interaction.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/popover/popover-modal.ts[render,tags=snippet,indent=0,group=Lit]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/popover/PopoverModal.java[render,tags=snippet,indent=0,group=Flow]
----

[source,tsx]
----
include::{root}/frontend/demo/component/popover/react/popover-modal.tsx[render,tags=snippet,indent=0,group=React]
----
--


== Accessibility

By default, the Popover overlay has the ARIA role `dialog`. This can be changed to another role to provide appropriate semantics for the type of content and interaction in the popover (see <<typical-use-cases, Typical Use Cases>> for examples).

- `menu`: when the content is a list of actions or links
- `listbox`: when the content is a list form which you can select one or more items
- `grid`: when the content is a tabular structure from which you select an item
- `tree`: when the content is a hierarchical list

Remember that, unlike <<../tooltip#,Tooltip>>, the contents of a Popover are _not_ automatically announced by screen readers when it opens. Consider using a live region to announce non-interactive popovers, and ensure keyboard access to interactive popovers.

The target element is automatically applied `aria-controls` (with a reference to the Popover overlay), `aria-haspopup` (with the overlay’s role as the value), and `aria-expanded` (set to `true` when open, and to `false` otherwise).

An accessible name can be provided for the overlay using the ARIA label API:

[.example.show-code]
--

[source,java]
----
<source-info group="Flow"></source-info>
Popover popover = new Popover();
popover.setAriaLabel("Label");
// OR
popover.setAriaLabelledby("label-element-id");
----

[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-popover accessible-name="Label"></vaadin-popover>
<vaadin-popover accessible-name-ref="label-element-id"></vaadin-popover>

----

[source,tsx]
----
<source-info group="React"></source-info>
<Popover accessibleName="Label" />
<Popover accessibleNameRef="label-element-id" />
----

--

== Typical Use Cases

Here are a few examples of common use cases for the Popover component with recommended configurations.

=== Drop-Down Field

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/popover/popover-dropdown-field.ts[render,tags=snippet,indent=0,group=Lit]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/popover/PopoverDropdownField.java[render,tags=snippet,indent=0,group=Flow]
----

[source,tsx]
----
include::{root}/frontend/demo/component/popover/react/popover-dropdown-field.tsx[render,tags=snippet,indent=0,group=React]
----
--

- Opens on click, focus
- Closes on kbd:[Esc], blur, outside click, target click, and programmatically upon selection
- Modal, no modality curtain (drop-down fields typically don’t have curtains)
- Auto-focused
- ARIA role `dialog`
- ARIA label _“Select a date range”_

=== User Menu

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/popover/popover-user-menu.ts[render,tags=snippet,indent=0,group=Lit]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/popover/PopoverUserMenu.java[render,tags=snippet,indent=0,group=Flow]
----

[source,tsx]
----
include::{root}/frontend/demo/component/popover/react/popover-user-menu.tsx[render,tags=snippet,indent=0,group=React]
----

[source,css]
----
include::{root}/frontend/themes/docs/popover-user-menu.css[]
----
--

- Opens on click
- Closes on kbd:[Esc], outside click, target click
- Modal, no modality curtain (small popovers like this usually don’t need them)
- ARIA role `menu` (the overlay’s content is a menu; although there are non-list elements, they are not interactive, nor do they need to be announced by screen readers)
- ARIA label _“User menu”_

Note: if the popover only needs to contain menu items, consider using a <<../menu-bar#,Menu Bar>> or <<../context-menu#,Context Menu>> instead.

=== Notification Panel

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/popover/popover-notification-panel.ts[render,tags=snippet,indent=0,group=Lit]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/popover/PopoverNotificationPanel.java[render,tags=snippet,indent=0,group=Flow]
----

[source,tsx]
----
include::{root}/frontend/demo/component/popover/react/popover-notification-panel.tsx[render,tags=snippet,indent=0,group=React]
----

[source,css]
----
include::{root}/frontend/themes/docs/popover-notification-panel.css[]
----
--

- Opens on click
- Closes on kbd:[Esc], outside click, target click
- Modal, no modality curtain (small popovers like this usually don’t need them)
- ARIA role `dialog` (although mainly a list, there interactive non-list elements as well)
- ARIA labelled-by pointing to heading in overlay
- Arrow variant

=== Rich, Interactive Tooltip

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/popover/popover-interactive-tooltip.ts[render,tags=snippet,indent=0,group=Lit]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/popover/PopoverInteractiveTooltip.java[render,tags=snippet,indent=0,group=Flow]
----

[source,tsx]
----
include::{root}/frontend/demo/component/popover/react/popover-interactive-tooltip.tsx[render,tags=snippet,indent=0,group=React]
----
--

- Opens on hover, focus
- Closes on kbd:[Esc], outside click (as well as mouseout and blur)
- Non-modal
- Not auto-focused
- ARIA role `dialog` (`tooltip` would be invalid due to interactive contents)
- ARIA labelled-by pointing to heading in overlay
- Positioned above target
- Arrow variant

=== Anchored Modal Dialog

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/popover/popover-anchored-dialog.ts[render,tags=snippet,indent=0,group=Lit]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/popover/PopoverAnchoredDialog.java[render,tags=snippet,indent=0,group=Flow]
----

[source,tsx]
----
include::{root}/frontend/demo/component/popover/react/popover-anchored-dialog.tsx[render,tags=snippet,indent=0,group=React]
----
--


- Opens on click
- Closes on kbd:[Esc], outside click
- Modal, with curtain
- Auto-focused
- ARIA role `dialog`
- ARIA labelled-by pointing to heading in the overlay

Note: if the dialog doesn’t benefit from being anchored-positioned to another element, consider using a <<../dialog#,Dialog>> instead.


== Related Components

[cols="1,2"]
|===
|Component |Usage Recommendation

|<<../dialog#,Dialog>>
|Use instead of Popover if there is no need to visually associate it with another UI element.
Modal dialogs are a better option for transactional operations.
Modal dialogs provide full-stack modality (e.g. keyboard shortcuts defined in the UI behind are blocked while the Dialog is open)


|<<../tooltip#,Tooltip>>
|Use instead of Popover if the content is just text.

|<<../context-menu#,Context Menu>>
|Use instead of Popover if the content is a list of actions or toggles.

|<<../menu-bar#,Menu Bar>>
|Same as Context Menu, but with built-in trigger buttons.
|===
