---
title: Styling
page-title: How to style the Popover component | Vaadin components
description: Styling API reference for the Popover component.
meta-description: Style the Vaadin Popover component to align it with your application's design requirements.
order: 50
---
= Popover Styling

== Style Variants

Popover supports the following style variants.

[cols="1,3,1"]
|===
| Variant | Description | Supported by

|`arrow`
|Makes the arrow visible
|Aura, Lumo

|`small`
|Used for compact UIs
| Lumo

|===


include::../_styling-section-theming-props.adoc[tag=style-properties]

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-popover-arrow-border-radius`
|Aura, Lumo

|`--vaadin-popover-arrow-size`
|Aura, Lumo

|`--vaadin-popover-background`
|Aura

|`--vaadin-popover-border-color`
|Aura

|`--vaadin-popover-border-radius`
|Aura

|`--vaadin-popover-border-width`
|Aura

|`--vaadin-popover-offset-bottom`
|Aura, Lumo

|`--vaadin-popover-offset-end`
|Aura, Lumo

|`--vaadin-popover-offset-start`
|Aura, Lumo

|`--vaadin-popover-offset-top`
|Aura, Lumo

|`--vaadin-popover-padding`
|Aura

|`--vaadin-popover-shadow`
|Aura

|`--vaadin-overlay-backdrop-background`
|Aura

|===


include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-popover`


=== States

Modal:: `vaadin-popover+++<wbr>+++**[modal]**`
With backdrop:: `vaadin-popover+++<wbr>+++**[with-backdrop]**`


=== Parts

Modality curtain (backdrop):: `vaadin-popover+++<wbr>+++**::part(backdrop)**`
Popover surface:: `vaadin-popover+++<wbr>+++**::part(overlay)**`
Content wrapper:: `vaadin-popover+++<wbr>+++**::part(content)**`
Arrow element:: `vaadin-popover+++<wbr>+++**::part(arrow)**`

=== Style Variants

Arrow:: `vaadin-popover+++<wbr>+++**[theme~="arrow"]**`
