---
title: Configuration
description: Customizing the configuration of a Hilla application for both the development environment and for execution.
---
// tag::content[]

= Configuration

// TODO nothing to configure here - why is the content here?
// == Live-reload during development

// When running the application in development mode, all modifications in the `frontend` folder are compiled automatically.
// Refreshing the browser is enough to see the updates in the application.

// .Server restart is required
// [NOTE]
// When adding [filename]`index.ts` or [filename]`index.html`, the application server needs to be restarted to update the entry point and the bootstrap template.


== TypeScript compiler options

The TypeScript compiler requires a [filename]`tsconfig.json` file.
If there is no [filename]`tsconfig.json` in the project root, the `vaadin-maven-plugin` generates one.
The default configuration looks similar to the following:

.`tsconfig.json`
[source,json]
----
{
  "compilerOptions": {
    "sourceMap": true,
    "inlineSources": true,
    "module": "esNext",
    "target": "es2017",
    "moduleResolution": "node",
    "strict": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "experimentalDecorators": true,
    "baseUrl": "frontend",
    "paths": {
      "Frontend/*": [
        "*"
      ]
    }
  },
  "include": [
    "frontend/**/*.ts",
    "frontend/index.js",
    "types.d.ts"
  ],
  "exclude": []
}
----

// end::content[]
