---
title: Overview
order: 1
layout: page
---

= Overview of Vaadin Flow

Flow is a Java web framework for building modern web apps and websites.
You can create UIs in Java, or use HTML templates to create the UI, and then bind it to any backend using Java.

The basic features in Flow are:

* An architecture that lets you concentrate on the UI.
No need to think about client-server communication.

* A set of carefully crafted UI components that focus on both the end-user and developer experience.

* Powerful abstraction layers to build your own reusable UI components with either Java or HTML templates.

* Data binding API to connect UI components to any backend using type-safe Java.

* Router API to create hierarchical page structures for the user to navigate.

== Topics

Vaadin Flow documentation is arranged in the following sections and we recommend reading it in this order.

<<application/application-overview#, Creating a Flow Application>>::
Basics of creating an application using Flow.

<<routing/routing-overview#, Routing and Navigation>>::
Vaadin applications consist of one or more views and routing defines how URL addresses are mapped to those views.
Navigating around the application works together with routing.

<<components/components-overview#, Using Vaadin Components>>::
Vaadin comes with a rich set of user interface components, which you can use both in Flow and Fusion views.
This section describes their basic functionalities and how to use them in Flow applications.

<<binding-data/tutorial-flow-components-binder#, Binding Data to Components>>::
You can bind data sources directly to components so that if the data changes, the components are automatically updated, and vice versa, when the user changes the values in the input components, the values are automatically updated to the data source.
This is handled by the [classname]#Binder# and some assisting classes.

// TODO REORGANIZE
// == Importing JavaScript
// * <<importing-dependencies/tutorial-importing#,Importing JavaScript>>

<<creating-components/creating-components-overview#, Creating Components>>::
In addition to using Vaadin components, you can create your own.
At simplest it is done by composition from existing components.
That is in fact how you create a view in Flow applications.
You can also create a component by binding it to a custom JavaScript/TypeScript component.

<<element-api/tutorial-properties-attributes#, Manipulating DOM with Element API>>::
You can control the HTML DOM in the browser from the server-side using the Element API.
This enables one way to make new components purely in server-side Java.

<<web-components/integrating-a-web-component#, Integrating Web Components>>::
The most advanced way to create a component is to integrate a JavaScript web component.

<<templates/tutorial-template-intro#, Building Views with Templates>>::
In addition to imperative Java code, you can build views declaratively using templates.
The components in such a template can be bound directly to data items.

<<dnd/generic-dnd#, Drag and Drop>>::
Vaadin allows drag-and-drop between components as well as between the UI and the operating system.

<<spring/tutorial-spring-basic#, Using Vaadin with Spring>>::
Vaadin is well suited for using it with the Spring Framework.
Spring is part of the recommended toolchain, and in fact Vaadin applications are by default Spring Boot applications.

<<cdi/tutorial-cdi-basic#, Using Vaadin with CDI>>::
CDI or Contexts and Dependency Injection is a framework for injecting dependency objects in different contexts.
It is part of the Java EE platform, but similar in purpose to autowiring in Spring.

////
TODO Is this removed?
<<portlet-support/portlet-01-overview#, Vaadin Portlet Support>>::
Vaadin applications can run as portal portlets in addition to servlets in a servlet container or standalone Spring-Boot applications.
////

<<embedding/tutorial-webcomponent-intro#, Embedding Flow Applications>>::
In addition to running Vaadin a application in a web page, you can embed it in a web page, which could be part of some other application.

<<pwa/tutorial-pwa-introduction#, Progressive Web Applications (PWA)>>::
Progressive Web Applications are applications run in a browser, but that be installed to a mobile device or to desktop much like a normal application.
They have the ability to work offline and have access to phone's resources.

<<advanced/tutorial-application-lifecycle#, Advanced Topics>>::
This is a collection of miscellaneous important topics and features that you may need in Vaadin applications.
