---
title: Upgrade Guide Generator
order: 30
---

= Upgrade Guide Generator
:!toc:

pass:[<!-- Vale Vaadin.Versions = NO -->]

Instructions for upgrading to the latest Vaadin version. To run applications or components developed with Vaadin 7 or 8 inside an application written using the latest version, see <<{articles}/tools/mpr/overview#,Multiplatform Runtime>>.

pass:[<!-- Vale Vaadin.Versions = YES -->]


[source,typescript, role="render-only embedded"]
----
include::{root}/frontend/demo/upgrade-tool/upgrade-tool.ts[render, persistent]
----

////
Upgrading instructions are all loaded to the page as hidden by default.
The upgrade tool manipulates the visibility of the instructions via their classnames depending on the user's selected options.

This is the description of the classnames:

.all:
    Upgrading instructions that should appear regardless of the user's selected configurations.

.v{from-version}-{to-version}:
    For example, v14-17, will be used by the upgrade tool to show the marked instructions if the user selects to see the instructions for the v14 -> v17 path.
    If there are no upgrading instructions directly for the v14 -> v17 path, the app will then display all the intermediate upgrade paths (i.e. v14->v15, v15->v16, and v16-v17).
    This classname should be added only once above the heading of the upgrading instructions.

.flow:
    Upgrading instructions that should appear if the user selects Flow. When placed under a heading that is marked using the v{from-version}-{to-version} classname, the content
     marked with the flow classname will only appear if the user selects that version. 

.fusion:
.spring:
.ts:
.styling:
    Same as flow classname for Fusion-, Spring-, TS-, and styling-related changes respectively.

////

++++
<style>
[class*=all]:is(div, .openblock, h2), 
[class*=v1]:is(div, .openblock, h2),
[class*=v2]:is(div, .openblock, h2),
[class*=v3]:is(div, .openblock, h2),
[class*=v4]:is(div, .openblock, h2),
[class*=flow]:is(div, .openblock, h2), 
[class*=fusion]:is(div, .openblock, h2), 
[class*=spring]:is(div, .openblock, h2), 
[class*=ts]:is(div, .openblock, h2),
[class*=styling]:is(div, .openblock, h2)
{
    display: none;
}
</style>
++++

[.all]
== Before You Start

[.all]
--
include::common/_before-upgrade.adoc[]
--

[.spring]
--
include::common/_before-upgrade-spring.adoc[]
--

[.v14-23]
== Vaadin 14 to 23 Upgrade Guide

The 14 to 23 upgrading instructions are available in the following <<{articles}/upgrading/essential-steps#,separate chapter>>.

[.v14-15]
== Upgrade Steps | 14 -> 15

[.flow]
--
include::flow/_14-15.adoc[]
--

[.fusion]
--
include::fusion/_14-15.adoc[]
--

[.v15-16]
== Upgrade Steps | 15 -> 16

[.flow.fusion]
--
include::common/_15-16.adoc[]
--

[.v16-17]
== Upgrade Steps | 16 -> 17

[.flow.fusion]
--
include::common/_16-17.adoc[]
--

[.v17-18]
== Upgrade Steps | 17 -> 18

[.ts]
--
include::common/_17-18.adoc[]
--

[.flow]
--
include::flow/_17-18.adoc[]
--

[.fusion]
--
include::fusion/_17-18.adoc[]
--

[.v18-19]
== Upgrade Steps | 18 -> 19

[.flow]
--
include::flow/_18-19.adoc[]
--

[.fusion]
--
include::fusion/_18-19.adoc[]
--

[.v19-20]
== Upgrade Steps | 19 -> 20

[.flow]
--
include::flow/_19-20.adoc[]
--

[.fusion]
--
include::fusion/_19-20.adoc[]
--

[.v20-21]
== Upgrade Steps | 20 -> 21

[.ts]
--
include::typescript/_20-21.adoc[]
--

[.flow]
--
include::flow/_20-21.adoc[]
--

[.fusion]
--
include::fusion/_20-21.adoc[]
--

[.v21-22]
== Upgrade Steps | 21 -> 22

[.ts]
--
include::typescript/_21-22.adoc[]
--

[.flow]
--
include::flow/_21-22.adoc[]
--

[.fusion]
--
include::fusion/_21-22.adoc[]
--

[.styling]
--
include::styling/_21-22.adoc[]
--

[.v22-23]
== Upgrade Steps | 22 -> 23

[.flow.fusion]
--
include::common/_22-23.adoc[]
--

[.flow]
--
include::flow/_22-23.adoc[]
--

[.fusion]
--
include::fusion/_22-23.adoc[]
--

[.all]
== After You Finish

[.all]
--
include::common/_after-upgrade.adoc[]
--
