---
title: Messages
layout: tabbed-page
tab-title: Usage
page-links:
  - https://github.com/vaadin/flow-components/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-messages-flow}[Flow {moduleMavenVersion:com.vaadin:vaadin-messages-flow}]
  - https://github.com/vaadin/web-components/releases/tag/v{moduleNpmVersion:vaadin-messages}[Web Component {moduleNpmVersion:vaadin-messages}]
---

= Messages

// tag::description[]
Messages is a collection of components to display messages and to build chats and comment sections.
// end::description[]

[.example]
--
[source,html]
----
include::{root}/frontend/demo/component/messages/message-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/messages/MessagesBasic.java[render,tags=snippet,indent=0,group=Java]
----
--

== Components Included

Messages consists of two main components.

* Message list, for displaying a list of messages.
* Message input, for letting the user fill in new messages.

== Message List

Message List allows you to show a list of messages.
The messages in the list can be populated with the `items` property.
The `items` property is of type `Array`, with JSON objects in it.
Each JSON object is a single message.
You can configure the text content, information about the sender and the time of sending for each message.

[.example]
--
[source,html]
----
include::{root}/frontend/demo/component/messages/message-list-component.ts[render,tags=snippet,indent=0,group=TypeScript]
----
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/messages/MessageListComponent.java[render,tags=snippet,indent=0,group=Java]
----
--

== Message Input

`<vaadin-message-input>` is a Web Component for sending messages.
Message is a component for showing a single message with an author, message and time.
It consists of a text area that grows on along with the content, and a send button to send message.
The message can be sent by one of the following actions:

- by pressing Enter (use Shift + Enter to add a new line)
- by clicking the `submit` button.

[.example]
--
[source,html]
----
include::{root}/frontend/demo/component/messages/message-input-component.ts[render,tags=snippet,indent=0,group=TypeScript]
----
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/messages/MessageInputComponent.java[render,tags=snippet,indent=0,group=Java]
----
--

== Theming

You can style individual messages by adding a theme property to some of the items and providing css using that theme. This can be usefull, for example, to highlight the current user's own messages.

[.example]
--
[source,css]
----
include::{root}/frontend/themes/docs/components/vaadin-message-with-theme.css[render,tags=snippet,indent=0,group=CSS]
----
[source,html]
----
include::{root}/frontend/demo/component/messages/message-list-with-theme-component.ts[render,tags=snippet,indent=0,group=TypeScript]
----
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/messages/MessageListWithThemeComponent.java[render,tags=snippet,indent=0,group=Java]
----
--

== Related Components

[cols="1,2"]
|===
|Component |Usage recommendations

|<<../avatar#,Avatar>>|Rendering user image as avatar.

|===
