---
title: Alternatives
page-title: Alternative ways of starting a Vaadin project
description: Learn about alternative ways to start a Vaadin project.
meta-description: Discover alternative ways to start a Vaadin project, including non-Spring Boot starters and different setup methods beyond the recommended approach.
layout: tabbed-page
tab-title: Overview
order: 20
---


= Alternative Ways of Starting a Vaadin Project

The recommended way to start a Vaadin project is by using https://start.vaadin.com[Vaadin Start], which generates a ready-to-run Spring Boot and Maven based project. However, there are alternative ways to start a Vaadin project, depending on your preferences and requirements.


== Non-Spring Boot Templates

Projects created via https://start.vaadin.com[Vaadin Start] are based on Spring Boot and Maven. However, if you prefer a different technology stack, you can also find _Hello World_ starter templates for other frameworks here:

* https://github.com/vaadin/skeleton-starter-flow[Flow / Java, Maven, and Jetty]
* https://github.com/vaadin/base-starter-flow-quarkus[Flow / Java, Maven, and Quarkus]
* https://github.com/vaadin/base-starter-spring-gradle[Flow / Java, Gradle, and Spring Boot]
* https://github.com/vaadin/skeleton-starter-kotlin-spring[Flow / Kotlin, Maven, and Spring Boot]
* https://github.com/vaadin/skeleton-starter-hilla-react-gradle[Hilla / React, Gradle, and Spring Boot]


[IMPORTANT]
Some guides, such as <<{articles}/getting-started#,Getting Started>> and <<{articles}/building-apps#,Building Apps>>, may not fully apply to projects that are not based on Spring Boot and Maven.

== Other Ways to Start a Project

section_outline::[]
