---
tab-title: Usage
layout: tabbed-page
title: Icons
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:vaadin-lumo-styles}/#/elements/vaadin-icon[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/icon/Icon.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/blob/v{moduleNpmVersion:vaadin-lumo-styles}/packages/vaadin-lumo-styles/vaadin-iconset.js[Lumo Icons] / https://github.com/vaadin/web-components/blob/v{moduleNpmVersion:vaadin-lumo-styles}/packages/icons/vaadin-iconset.js[Vaadin Icons]'
---

= Icons

The icon component can render SVG and font icons. Two icon collections are available out of the box.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/icons/icon-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/icons/IconBasic.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/icons/react/icon-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Default Icon Collections

Two icon collections are available through Vaadin dependencies: Vaadin Icons and Lumo Icons. The Flow API provides enums for these collections that makes them easy to use out of the box.

=== Vaadin Icons

Vaadin Icons is a collection of over 600 icons.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/icons/vaadin-icons.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/icons/VaadinIcons.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/icons/react/vaadin-icons.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


The <<./default-icons#,Default Icons>> tab contains a listing of the full Vaadin Icons collection.

==== Lumo Icons

Lumo Icons are used in the default Lumo theme for Vaadin components.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/icons/lumo-icons.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/icons/LumoIcons.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/icons/react/lumo-icons.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

Lumo Icons are rendered on a 24×24 pixel canvas with a 16×16 pixel active area for the icon itself and 4 pixels of whitespace around the icon.

The Default Icons tab contains a listing of the full Lumo Icons collection.

== Using Third Party Icons

Third party icons can be rendered with the icon component. Three common formats are supported: standalone SVG files, SVG sprites and icon fonts.

=== Standalone SVG Images

Standalone SVG images can be rendered as inline SVG icons using the icon component.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/icons/svg-standalone.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/icons/SvgStandalone.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/icons/react/svg-standalone.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

Thanks to inline SVG rendering, the icon can be styled with CSS for example to change its fill color or stroke.

The advantage of standalone SVG images is that only the icons actually needed in the UI are loaded into the browser.

=== SVG Sprites

SVG sprites are SVG files containing multiple images wrapped into `<symbol>` tags. An id attribute on the symbol tag is used to identify the images.

Using an image from an SVG sprite is similar to using a standalone SVG image – just append the symbol id to the file path, prefixed by #:

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/icons/svg-sprites.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/icons/SvgSprites.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/icons/react/svg-sprites.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

Like standalone SVG images, sprite icons are also rendered as inline SVG for styling support.

The advantage of using an SVG sprite is that only one file needs to be loaded into the browser. Custom SVG sprites containing only the icons needed in the application can provide performance benefits over standalone SVG images.

Many https://www.google.com/search?q=svg+sprite+generator[third party tools for creating SVG sprites,window=_blank] are available.

=== Icon Fonts

Icon fonts are loaded into the UI through a combination of

- A font file (usually placed in the theme folder)
- A https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face[`@font-face` declaration,window=_blank] (usually in a stylesheet provided with the font and imported into your theme’s master stylesheet `styles.css`)
- Optionally, a stylesheet with CSS classes representing the font and the icons in it, usually also imported into `styles.css` (may be included in same stylesheet as the `@font-face` declaration)

The desired icon can be specified in three different ways, depending on the font and stylesheets provided:

- Icon-specific CSS class, such as “fa-calendar” (requires a stylesheet defining CSS classes for each icon, usually bundled with the icon font)
- Ligature, such as “calendar” (requires an icon font that supports ligatures)
- Character code, such as “f199”, corresponding to the codepoint of the icon’s glyph in the font

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/icons/icon-fonts.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/icons/IconFonts.java[render,tags=snippet,indent=0,group=Java]
----

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/icons/react/icon-fonts.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]

[source,css]
----
include::{root}/frontend/themes/docs/icon-fonts.css[]
----
--


.styles.css
[source, css]
----
@import url('fontawesome/solid.css');
@import url('fontawesome/fontawesome.css');
----


.Example using FontAwesome
[source]
----
// theme folder:
themes/
  └── my-theme/
      ├── styles.css
      └── fontawesome/
          ├── fontawesome.css (classes for individual icons in the font)
          ├── solid.css (stylesheet with @font-face declaration)
          └── fa-solid-900.woff2 (icon font)
...
----

.solid.css
[source, css]
----
@font-face {
  font-family: 'Font Awesome 6 Free';
  font-style: normal;
  font-weight: 900;
  font-display: block;
  src: url("fa-solid-900.woff2") format("woff2"), url("fa-solid-900.ttf") format("truetype"); 
}
----

.Font-face Declaration Must Be Global CSS
[NOTE]
====
The `@font-face` declaration defining the icon font family must be placed in a global stylesheet, not in a Shadow DOM stylesheet.
====


.Using Icon Font Stylesheets Inside a Shadow Root
[NOTE]
====
To use CSS classes for icon fonts inside a Shadow DOM, such as that of a Lit template, they must be loaded into it separately. The easiest way to do this is to load them as part of the application’s theme, and <</create-ui/templates/styling-templates#,apply the theme inside the Shadow DOM>> with `applyTheme()`.
====

The font can also be defined using its font-family name (as defined in the @font-face declaration).

[.example]
--

ifdef::lit[]
[source, html]
----
<vaadin-icon font-family="Material Icons" ligature="home"></vaadin-icon>
----
endif::[]

ifdef::flow[]
[source, java]
----
// font-family name for font, ligature for icon
FontIcon fi3 = new FontIcon();
fi3.setFontFamily("Material Icons");
fi3.setLigature("home");
----
endif::[]

ifdef::react[]
[source, tsx]
----
<Icon fontFamily="Material Icons" ligature="home" />
----
endif::[]

--

Note that the rendering quality of icon fonts is inferior to SVGs, especially in smaller sizes.

== Icon Configuration

=== Color and Other Styles

The icon's fill color can be set to any CSS color value.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/icons/icons-color.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/icons/IconsColor.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/icons/react/icons-color.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

=== Size and Padding

The icon component has a property for setting the desired outer size of the icon in pixels. This automatically sets the icon’s width and height to the same value, as icons are rendered in a square (1:1) aspect ratio by default.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/icons/icons-sizing.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/icons/IconsSizing.java[render,tags=snippet1,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/icons/react/icons-sizing.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

The internal padding of the icon can be adjusted to compensate for the lack of surrounding whitespace in the icon itself.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/icons/icons-padding.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/icons/IconsPadding.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/icons/react/icons-padding.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

== Accessibility

Screen readers are not able to announce icons correctly out of the box. In fact, the icon component is built in a way that is completely ignored by assistive technologies by default.

However, in most cases, there should not be any need to make icons screen reader friendly on their own. Instead, the component, such as Button, in which the icon is used, should provide a screen reader friendly accessible name.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/icons/icons-accessibility.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/icons/IconsAccessibility.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/icons/react/icons-accessibility.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

In cases where icons are used to convey information on their own, such as in a table column to convey a value in a graphical manner, they need to be provided with an accessible name and an ARIA image role attribute in order to be correctly announced by screen readers.

[.example]
--
ifdef::lit[]
[source, html]
----
<vaadin-icon icon="vaadin:star" role="img" aria-label="Favorite"></vaadin-icon>
----
endif::[]

ifdef::flow[]
[source, java]
----
Icon favoriteStatusIndicator = VaadinIcon.STAR.create();
favoriteStatusIndicator.getElement().setAttribute("role", "img");
favoriteStatusIndicator.getElement().setAttribute("aria-label", "Favorite");
----
endif::[]

ifdef::react[]
[source, tsx]
----
<Icon icon="vaadin:star" role="img" aria-label="Favorite" />
----
endif::[]

--


[discussion-id]`47B97C93-9646-4D2A-882F-C4F709D3D099`
