---
title: Styling
order: 50
---
= Styling

include::../_styling-section-intros.adoc[tag=selectors]


=== Overlay
[Horizontal, labelwidth=33]
Root element:: `vaadin-confirm-dialog-overlay`
Modality curtain (backdrop):: `vaadin-confirm-dialog-overlay+++<wbr>+++**::part(backdrop)**`
Dialog surface:: `vaadin-confirm-dialog-overlay+++<wbr>+++**::part(overlay)**`

=== Header
[Horizontal, labelwidth=33]
Header:: `vaadin-confirm-dialog-overlay+++<wbr>+++**::part(header)**`
Title wrapper:: `vaadin-confirm-dialog-overlay+++<wbr>+++**::part(title)**`
Title element:: `vaadin-confirm-dialog-overlay+++<wbr>+++** > [slot="title"]**`
Header custom content wrapper:: `vaadin-confirm-dialog-overlay+++<wbr>+++**::part(header-content)**`

=== Content Area
[Horizontal, labelwidth=33]
Content area:: `vaadin-confirm-dialog-overlay+++<wbr>+++**::part(content)**`
Message:: `vaadin-confirm-dialog-overlay+++<wbr>+++**::part(message)**`

=== Footer
[Horizontal, labelwidth=33]
Footer:: `vaadin-confirm-dialog-overlay+++<wbr>+++**::part(footer)**`
Confirm button:: `vaadin-confirm-dialog-overlay+++<wbr>+++** > [slot="confirm-button"]**`
Reject button:: `vaadin-confirm-dialog-overlay+++<wbr>+++** > [slot="reject-button"]**`
Cancel button:: `vaadin-confirm-dialog-overlay+++<wbr>+++** > [slot="cancel-button"]**`