---
title: Getting started
description: Step-by-step guide on how to use Observability Kit in an application.
order: 100
---
:lit:
// tag::content[]

= Getting Started with Observability Kit
:sectnums:

== Create a Hilla Application

You can create a Hilla application by entering the following from the command-line:

ifdef::lit[]
[source,bash]
----
npx @hilla/cli init <your-project-name>
----
endif::[]

ifdef::react[]
[source,bash]
----
npx @hilla/cli init --react <your-project-name>
----
endif::[]

== Download & Configure

Observability Kit consists of two parts: the Starter dependency and the Agent.

[role="since:dev.hilla:hilla@V2.1"]

=== Starter dependency

The Starter dependency can be added to your project by adding the following to the `pom` file:

.`pom.xml`
[source,xml]
----
<dependency>
  <groupId>dev.hilla</groupId>
  <artifactId>observability-kit-starter</artifactId>
</dependency>
----

To process the observability endpoint that comes along with the starter, add the following configuration to your `hilla-engine-plugin`.

[source,xml]
----
<configuration>
    <parser>
        <packages>
            <package>dev.hilla.observability</package>
        </packages>
    </parser>
</configuration>
----

=== Agent

The Observability Kit Agent is based on the OpenTelemetry standard and is packaged as a jar file.

.Download the Agent jar file
[IMPORTANT]
The Agent cannot be used as a dependency. It must be downloaded separately.

link:https://repo1.maven.org/maven2/com/vaadin/observability-kit-agent/2.1.0/observability-kit-agent-2.1.0.jar[Download Observability Kit Agent, role="button secondary water"]

Once the Agent has finished downloading to the project directory, it needs to be configured to export telemetry to one or more observability tools. In this guide, traces are exported to Jaeger; metrics are sent to Prometheus. To do this, create an [filename]`agent.properties` file in the project directory with the following content:

.`*agent.properties*`
[source,properties]
----
otel.traces.exporter=jaeger
otel.exporter.jaeger.endpoint=http://localhost:14250
otel.metrics.exporter=prometheus
otel.exporter.prometheus.host=0.0.0.0
otel.exporter.prometheus.port=9464
----

== Setup Infrastructure

This guide uses Jaeger to process traces, and Prometheus to process metrics. They both run locally and are suitable for development and testing.

https://www.jaegertracing.io/[Jaeger] is a tool for collecting traces.

https://www.jaegertracing.io/download/[Download Jaeger, role="button secondary water"]

Extract the contents of the downloaded archive (tar.gz file).
Open a terminal to the Jaeger directory and start Jaeger:

[source,terminal]
----
./jaeger-all-in-one
----

https://prometheus.io/[Prometheus] is a tool for collecting metrics.

https://prometheus.io/download/[Download Prometheus, role="button secondary water"]

Extract the contents of the downloaded archive (tar.gz file).
Create a Prometheus configuration with a scraper that reads metrics data from the OpenTelemetry exporter:

.config.yml
[source,yaml]
----
global:
  scrape_interval: 15s # Default is every 1 minute.

scrape_configs:
  - job_name: 'opentelemetry'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9464']
    # Host and port need to match the
    # OpenTelemetry prometheus exporter configuration
----

Open a terminal to the Prometheus directory and start Prometheus with the configuration file:

[source,terminal]
----
./prometheus --config.file=/PATH/TO/config.yml
----

Remember to substitute the correct path to the [filename]`config.yml` file.

== Setup frontend package

To complete the setup process, you need to install and initialize the client-side component of the kit.

Use the following command in your terminal to install the package:

[source,terminal]
----
npm install @hilla/observability-kit-client
----

Next, open the `frontend/index.ts` file and add the following code:

[source,typescript]
----
import { init } from '@hilla/observability-kit-client';
import { ObservabilityEndpoint } from 'Frontend/generated/endpoints.js'

init(ObservabilityEndpoint.export);
----

== Run the Application

You're now ready to run your application. Create a production build with the following command:

[source,bash]
----
mvnw package -Pproduction
----

Then run the packaged JAR file from the [filename]`target` folder:

[.example]
--

Run the application using the Java binary and pass the respective arguments for the Agent and configuration like so:
[source,terminal]
----
<source-info group="JAR file"></source-info>
java -javaagent:PATH/TO/vaadin-opentelemetry-javaagent-VERSION.jar \
     -Dotel.javaagent.configuration-file=PATH/TO/agent.properties \
     -jar myapp.jar
----

Create a file, [filename]`setenv.bat` in your Tomcat installation's [filename]`bin` folder. This script runs automatically with the startup script.

Copy the content below and paste it into that file. Be sure to change it, though, to your particular installation's file paths. Then start Tomcat using [filename]`bin/startup.bat`.
[source,terminal]
----
<source-info group="Tomcat (Windows)"></source-info>
set CATALINA_OPTS=%CATALINA_OPTS% -javaagent:PATH\TO\vaadin-opentelemetry-javaagent-VERSION.jar
set OTEL_JAVAAGENT_CONFIGURATION_FILE=PATH\TO\agent.properties
----

Create a file, [filename]`setenv.sh` in your Tomcat installation's [filename]`bin` folder. This script runs automatically with the startup script. Copy the content below and paste it into that file. Be sure to change it, though, to your particular installation's file paths. Then start Tomcat using [filename]`bin/startup.sh`.
[source,terminal]
----
<source-info group="Tomcat (macOS/Linux)"></source-info>
export CATALINA_OPTS="$CATALINA_OPTS -javaagent:PATH/TO/vaadin-opentelemetry-javaagent-VERSION.jar"
export OTEL_JAVAAGENT_CONFIGURATION_FILE=PATH/TO/agent.properties
----

Start Jetty and pass the respective arguments for the Java agent and the agent configuration:

[source,terminal]
----
<source-info group="Jetty"></source-info>
java -javaagent:PATH/TO/vaadin-opentelemetry-javaagent-VERSION.jar \
     -Dotel.javaagent.configuration-file=PATH/TO/agent.properties \
     -jar /PATH/TO/jetty_home/start.jar
----

If you want to run an application with the agent through Maven for testing, set the `MAVEN_OPTS` variable as shown below. Then run your Maven goal, for example, `mvn jetty:run`.
[source,terminal]
----
<source-info group="Maven (Windows)"></source-info>
set MAVEN_OPTS="-javaagent:PATH\TO\vaadin-opentelemetry-javaagent-VERSION.jar -Dotel.javaagent.configuration-file=PATH\TO\agent.properties"
----

If you want to run an application with the agent through Maven for testing, set the `MAVEN_OPTS` variable as shown below. Then run your Maven goal, for example, `mvn jetty:run`.
[source,terminal]
----
<source-info group="Maven (macOS/Linux)"></source-info>
export MAVEN_OPTS="-javaagent:PATH/TO/vaadin-opentelemetry-javaagent-VERSION.jar -Dotel.javaagent.configuration-file=PATH/TO/agent.properties"
----
--

.Replace placeholder paths and version.
[NOTE]
Remember to correct the path to the [filename]`agent.properties` file, as well as the path and version of the Agent `.jar` file.

// end::content[]
