---
title: Styling
page-title: How to style the Avatar component | Vaadin components
description: Styling API reference for the Avatar and Avatar Group components.
meta-description: Customize the appearance of the Avatar component in Vaadin applications.
order: 50
---
= Avatar Styling


== Style Variants

Avatar and Avatar Group support the following style variants:

[cols="1,3,1"]
|===
| Variant | Description | Supported by

|`reverse`
|Reverses the stacking order of avatars in Avatar Group
|Aura, Lumo

|`large`
|Large avatar size
|Lumo

|`small`
|Small avatar size
|Lumo

|`xlarge`
|Extra large avatar size
|Lumo

|`xsmall`
|Extra small avatar size
|Lumo

|===


include::../_styling-section-theming-props.adoc[tag=style-properties]

=== Common Properties

[cols="1,2,2"]
|===
| Feature | Property | Supported by

|Avatar size
|`--vaadin-avatar-size`
|Aura, Lumo

|Avatar background
|`--vaadin-avatar-background`
|Aura, Lumo

|Avatar border width
|`--vaadin-avatar-border-width`
|Aura

|Avatar border color
|`--vaadin-avatar-border-color`
|Aura

|Avatar Group overlap
|`--vaadin-avatar-group-overlap`
|Aura, Lumo

|Avatar Group overlap border width
|`--vaadin-avatar-group-overlap-border`
|Lumo

|===

=== User Color Properties

[cols="1,2,2"]
|===
| Feature | Property | Default Value

|User color 0
|`--vaadin-user-color-0`
|`#df0b92`

|User color 1
|`--vaadin-user-color-1`
|`#650acc`

|User color 2
|`--vaadin-user-color-2`
|`#097faa`

|User color 3
|`--vaadin-user-color-3`
|`#ad6200`

|User color 4
|`--vaadin-user-color-4`
|`#bf16f3`

|User color 5
|`--vaadin-user-color-5`
|`#084391`

|User color 6
|`--vaadin-user-color-6`
|`#078836`

|===


include::../_styling-section-intros.adoc[tag=selectors]

=== Avatar

Root element:: `vaadin-avatar`
Hovered avatar:: `vaadin-avatar+++<wbr>+++**:hover**`
Focused avatar:: `vaadin-avatar+++<wbr>+++**[focused]**`
Avatar with color index:: `vaadin-avatar+++<wbr>+++**[has-color-index]**`
Overflow avatar:: `vaadin-avatar+++<wbr>+++**[slot="overflow"]**`
Expanded overflow avatar:: `vaadin-avatar+++<wbr>+++**[aria-expanded="true"]**`
Avatar icon:: `vaadin-avatar+++<wbr>+++**::part(icon)**`
Avatar abbreviation:: `vaadin-avatar+++<wbr>+++**::part(abbr)**`


=== Avatar Group

Root element:: `vaadin-avatar-group`
Avatar in group:: `vaadin-avatar-group+++<wbr>+++** > vaadin-avatar**`


=== Overlay

Overlay background:: `vaadin-avatar-group+++<wbr>+++**::part(overlay)**`
Overlay content wrapper:: `vaadin-avatar-group+++<wbr>+++**::part(content)**`
Menu inside overlay:: `vaadin-avatar-group-menu`
Item element:: `vaadin-avatar-group-menu-item`
Hovered item:: `vaadin-avatar-group-menu-item+++<wbr>+++**:hover**`
Focused item:: `vaadin-avatar-group-menu-item+++<wbr>+++**[focused]**`
Item content wrapper:: `vaadin-avatar-group-menu-item+++<wbr>+++**::part(content)**`
Item avatar:: `vaadin-avatar-group-menu-item+++<wbr>+++** > vaadin-avatar**`
