---
title: Styling
order: 50
---
= Styling

include::../_styling-section-intros.adoc[tag=selectors]


=== Avatar
[Horizontal, labelwidth=33]
Root element:: `vaadin-avatar`
Hovered avatar:: `vaadin-avatar+++<wbr>+++**:hover**`
Focused avatar:: `vaadin-avatar+++<wbr>+++**[focused]**`
Avatar with color index:: `vaadin-avatar+++<wbr>+++**[has-color-index]**`
Overflow avatar:: `vaadin-avatar+++<wbr>+++**[slot="overflow"]**`
Expanded overflow avatar:: `vaadin-avatar+++<wbr>+++**[aria-expanded="true"]**`
Avatar icon:: `vaadin-avatar+++<wbr>+++**::part(icon)**`
Avatar abbreviation:: `vaadin-avatar+++<wbr>+++**::part(abbr)**`


=== Avatar Group
[Horizontal, labelwidth=33]
Root element:: `vaadin-avatar-group`
Avatar in group:: `vaadin-avatar-group+++<wbr>+++** > vaadin-avatar**`


=== Overlay
[Horizontal, labelwidth=33]
Overlay element:: `vaadin-avatar-group-overlay`
Overlay background:: `vaadin-avatar-group-overlay+++<wbr>+++**::part(overlay)**`
Overlay content wrapper:: `vaadin-avatar-group-overlay+++<wbr>+++**::part(content)**`
Listbox element (overlay contents):: `vaadin-avatar-group-overlay+++<wbr>+++** > vaadin-list-box**`
Item element:: `vaadin-avatar-group-overlay+++<wbr>+++** > vaadin-list-box > vaadin-item**`
Hovered item:: `vaadin-avatar-group-overlay+++<wbr>+++** > vaadin-list-box > vaadin-item:hover**`
Focused item:: `vaadin-avatar-group-overlay+++<wbr>+++** > vaadin-list-box > vaadin-item[focused]**`
Item content wrapper:: `vaadin-avatar-group-overlay+++<wbr>+++** > vaadin-list-box > vaadin-item::part(content)**`
