== Preparing the Application for Production

It is important to build a separate production-optimized version of the application before deploying it.
In development mode, Vaadin has a live-reload widget, debug logging, and uses a quick, but unoptimized, frontend build that includes source maps for easy debugging.
Unoptimized frontend bundles can contain several megabytes of JavaScript.

The [filename]#pom.xml# file includes a `production` profile configuration that prepares an optimized build which is ready for production.

=== Using a PostgreSQL Database in Production

During development, the application has used an in-memory H2 database.
This is convenient and works well for a single user.
In production, you want to use something more robust and persistent.
Heroku's free tier supports PostgreSQL, so can configure your application to use that.

First, add the PostgreSQL dependency in the production profile of [filename]#pom.xml#:

.`pom.xml`
[source,xml,highlight=4-9]
----
<profile>
 <id>production</id>
 <!-- Omitted -->
 <dependencies>
   <dependency>
     <groupId>org.postgresql</groupId>
     <artifactId>postgresql</artifactId>
   </dependency>
 </dependencies>
</profile>
----

Next, configure how JPA should handle schema generation.
Add the following two properties to the end of [filename]#application.properties#.

.`src/main/java/resources/application.properties`
[source]
----
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
----

.Avoid data loss
[WARNING]
====
This setup recreates the database on every deployment.
If you are working with real data, you should use `ddl-auto=none` and instead use a database migration tool like https://www.liquibase.org/[Liquibase] or https://flywaydb.org/[Flyway], so you can evolve the database schema without losing data.
====

=== Building a Production-Optimized JAR

Build the application with the `production` profile:

[source,bash]
----
mvn clean package -Pproduction
----

This builds a production-optimized JAR file in the `target` folder.

== Creating a Heroku Account and Installing the Heroku CLI

Complete the following steps to create a Heroku account and install the Heroku CLI.

1. Go to https://signup.heroku.com/, create a new account, and verify your email.
2. Go to https://devcenter.heroku.com/articles/heroku-cli and follow the instructions for installing the CLI on your operating system.

== Deploying a Vaadin Application to Heroku

Use the Heroku CLI to create and deploy your application.

. Log in:
+
[source,terminal]
----
heroku login
----
. Install the Heroku Java plugin:
+
[source,terminal]
----
heroku plugins:install java
----
. The project uses Java 11, whereas Heroku expects Java 8 projects by default.
To ensure that Heroku would run a Java 11 environment, create a [filename]#system.properties# file under the project's root directory with the following content:
+
.`system.properties`
[source]
----
java.runtime.version=11
----
. Create a new application.
Replace APPNAME with a name of your choice.
APPNAME is part of the URL, like https://APPNAME.herokuapp.com, so choose a name that is unique and easy to remember.
+
[source,terminal]
----
heroku create APPNAME
----
. Enable the PostgreSQL plugin for the newly created application.
+
[source,terminal]
----
heroku addons:create heroku-postgresql -a APPNAME
----
. Deploy the production-optimized JAR file you created in the previous section.
+
[source,terminal]
----
heroku deploy:jar target/fusioncrmtutorial-1.0-SNAPSHOT.jar -a APPNAME
----
. Open the application in your browser.
+
[source,terminal]
----
heroku open
----
. View the application logs, if anything went wrong.
+
[source,terminal]
----
heroku logs --tail
----
