---
title: Azure Cloud Kit
description: Deploy your Vaadin application to Azure Cloud.
section-nav: commercial
---


= Azure Cloud Kit

:commercial-feature: Azure Cloud Kit
:kit-trial: true
include::{articles}/flow/_commercial-banner.asciidoc[opts=optional]

With Azure Cloud Kit, you can quickly deploy your Vaadin application to Microsoft's Azure Cloud. It's based on Kubernetes Kit, which means that all of the features of Kubernetes Kit are also available in Azure Cloud Kit. Both Kits enable the following:

- Non-disruptive rolling updates that don't interrupt user sessions, thus reducing the cost and the inconvenience of after-hours deployments;
- Horizontal scalability, saving on cloud costs by allowing your application to scale down without impacting active user sessions -- and scale up when needed;
- High availability, enabling users to keep their active sessions and continue using your application even if a server fails; and
- Serialization helpers that make it faster and easier to leverage fully horizontal scaling and fail-over.

In addition to these features, Azure Cloud Kit has the added benefit of facilitating the deployment of your application to Azure Cloud. Azure Cloud Kit does this by providing a set of Infrastructure as Code (IaC) templates you can use to deploy your application to Azure Cloud. These templates are based on the Azure Kubernetes Service (AKS), a managed Kubernetes service that makes it easy to deploy and manage Kubernetes clusters.

Before using the Azure Cloud Kit, read <<{articles}/flow/tools/kubernetes/getting-started#, Getting Started with Kubernetes Kit>> to learn more about how to prepare your application to be serializable in order to enable scalability, high availability, and rolling updates. Then test those functionalities in a local Kubernetes setup. After you've confirmed that everything is working as expected in a local setup, come back to this page to deploy your application to the Azure Cloud.


== Topics

section_outline::[]

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++