---
title: Interaction
order: 60
page-links:
  - https://github.com/vaadin/vaadin-lumo-styles/blob/v{moduleNpmVersion:vaadin-lumo-styles}/style.html[Source]
---

= Interaction

Use these CSS Custom Properties to apply consistent interaction styles for components.
// TODO: restore after porting customization docs, replace line above
// Use these <<../customization/css-custom-properties#,CSS Custom Properties>> to apply consistent interaction styles for components.

.Only available in Lumo
[NOTE,role=small]
This documentation applies only to the Lumo theme.

:import-name: lumo
:module-name: style
include::_shared.asciidoc[tag=importing]


== Clickable Cursor

How clickable items are indicated to the users of pointer devices (the mouse) can be configured to suit your application's target audience.

You can either follow the “web” approach and use the pointer (hand) cursor for clickable items, or the “desktop” approach and use the default (arrow) cursor.

++++
<style>
</style>
++++

[.property-listing.previews, cols="1,>1"]
|===
| Description | CSS Custom Property

| [.preview(--lumo-clickable-cursor).shape.l]*Cursor* +
| [custom-property]#--lumo-clickable-cursor#
|===


[discussion-id]`31882558-8FBE-4D61-93D9-C98F689CF190`

