---
title: Size and Space
order: 30
page-links:
  - https://github.com/vaadin/vaadin-lumo-styles/blob/v{moduleNpmVersion:vaadin-lumo-styles}/sizing.html[Source (size)]
  - https://github.com/vaadin/vaadin-lumo-styles/blob/v{moduleNpmVersion:vaadin-lumo-styles}/spacing.html[Source (space)]
---

= Size and Space

Use these CSS Custom Properties to apply consistent sizing and spacing across your application.
// TODO: restore after porting customization docs, replace line above
// Use these <<../customization/css-custom-properties#,CSS Custom Properties>> to apply consistent sizing and spacing across your application.

.Only available in Lumo
[NOTE,role=small]
This documentation applies only to the Lumo theme.

:import-name: lumo
:module-name: size;space
include::_shared.asciidoc[tag=importing]


== Size

Use these properties to adjust the sizing of regular elements (buttons, text fields, list items).

Medium is the standard size, and it is primarily used to size buttons, text fields and list items.
If you adjust the sizing, make sure to keep it large enough for touch targets.

See <<icons#size,Icons>> for properties that affect the sizing of icons.

[.property-listing.previews, cols="1,>1"]
|===
| Description | CSS Custom Property

| [.preview(--lumo-size-xl).space]*Extra Large* +
Minimum data grid header row height
| [custom-property]#--lumo-size-xl#

| [.preview(--lumo-size-l).space]*Large* +
Large button
| [custom-property]#--lumo-size-l#

| [.preview(--lumo-size-m).space]*Medium* +
Button and input field height, data grid row height
| [custom-property]#--lumo-size-m#

| [.preview(--lumo-size-s).space]*Small* +
Small button and input field height
| [custom-property]#--lumo-size-s#

| [.preview(--lumo-size-xs).space]*Extra Small* +
| [custom-property]#--lumo-size-xs#
|===


=== Compact Sizing

Lumo has a compact sizing preset available.
It reduces the font size and the sizing and spacing of all components, allowing you to place more components on the screen.

Apply compact sizing by importing the style sheet, which sets new values for the
<<typography#,Typography>> and the <<size>> and <<space>> CSS properties.
ifdef::web[]
You can https://github.com/vaadin/vaadin-lumo-styles/blob/v{moduleNpmVersion:vaadin-lumo-styles}/presets/compact.html[view the values] from the source code.
endif::web[]

.`Java`
[source,java]
----
@JsModule("@vaadin/vaadin-lumo-styles/presets/compact.js")
@Theme(Lumo.class)
public class CompactApp extends Div {
}
----

== Space

Use these properties to adjust the inter-component spacings: the space outside a regular component (button, text field) or inside a container component (layouts, grid cells).

[.property-listing.previews, cols="1,>1"]
|===
| Description | CSS Custom Property

| [.preview(--lumo-space-xl).space]*Extra Large* +
| [custom-property]#--lumo-space-xl#

| [.preview(--lumo-space-l).space]*Large* +
| [custom-property]#--lumo-space-l#

| [.preview(--lumo-space-m).space]*Medium* +
| [custom-property]#--lumo-space-m#

| [.preview(--lumo-space-s).space]*Small* +
| [custom-property]#--lumo-space-s#

| [.preview(--lumo-space-xs).space]*Extra Small* +
| [custom-property]#--lumo-space-xs#
|===


[discussion-id]`B01EF7DD-2C1D-4BBC-BE33-9A8E48EC85B2`

