---
title: Styling
page-title: How to style the CRUD component | Vaadin components
description: Styling API reference for the CRUD component.
meta-description: Style the Vaadin CRUD component for a polished and user-friendly data management interface.
order: 50
---
= Crud Styling

== Style Variants

CRUD supports the following style variants:

[cols="1,3,1"]
|===
| Variant | Description | Supported by

|`no-border`
|Removes border around the CRUD component
|Aura, Lumo

|===


include::../_styling-section-theming-props.adoc[tag=style-properties]

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-crud-background`
|Aura

|`--vaadin-crud-border-color`
|Aura

|`--vaadin-crud-border-width`
|Aura

|`--vaadin-crud-border-radius`
|Aura

|`--vaadin-crud-toolbar-background`
|Aura

|`--vaadin-crud-toolbar-padding`
|Aura

|===

The following properties are specific to the editor, when it is positioned aside or at the bottom:

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-crud-editor-max-height`
|Aura, Lumo

|`--vaadin-crud-editor-max-width`
|Aura, Lumo

|`--vaadin-crud-header-color`
|Aura

|`--vaadin-crud-header-font-size`
|Aura

|`--vaadin-crud-header-font-weight`
|Aura

|`--vaadin-crud-header-line-height`
|Aura

|`--vaadin-crud-header-padding`
|Aura

|`--vaadin-crud-form-padding`
|Aura

|`--vaadin-crud-footer-background`
|Aura

|`--vaadin-crud-footer-gap`
|Aura

|`--vaadin-crud-footer-padding`
|Aura

|===


include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-crud`


=== Grid

Grid element:: `vaadin-crud+++<wbr>+++** > vaadin-grid**`
Grid element, non-Flow:: `vaadin-crud+++<wbr>+++** > vaadin-crud-grid**`
Edit button in grid:: `vaadin-crud-edit`
Edit button icon:: `vaadin-crud-edit+++<wbr>+++**::part(icon)::before**`
Toolbar below grid:: `vaadin-crud+++<wbr>+++**::part(toolbar)**`

_See <<../grid/styling#,Grid selectors>> for details on styling the grid_

=== Toolbar

Toolbar:: `vaadin-crud+++<wbr>+++**::part(toolbar)**`
New item button:: `vaadin-crud+++<wbr>+++** > vaadin-button[slot="new-button"]**`

=== Editor

Editor header:: `vaadin-crud+++<wbr>+++**::part(header)**`
Editor footer:: `vaadin-crud+++<wbr>+++**::part(footer)**`
Editor title:: `vaadin-crud+++<wbr>+++** > [slot="header"]**`
Editor form:: `vaadin-crud-form`
Save button:: `vaadin-crud+++<wbr>+++** > vaadin-button[slot="save-button"]**`
Cancel button:: `vaadin-crud+++<wbr>+++** > vaadin-button[slot="cancel-button"]**`
Delete button:: `vaadin-crud+++<wbr>+++** > vaadin-button[slot="delete-button"]**`

=== Side/Bottom Edit Panel

CRUD with editor on the side:: `vaadin-crud+++<wbr>+++**[editor-position="aside"]**`
CRUD with editor at the bottom:: `vaadin-crud+++<wbr>+++**[editor-position="bottom"]**`
Editor panel:: `vaadin-crud+++<wbr>+++**::part(editor)**`
Editor scroller (content above toolbar):: `vaadin-crud+++<wbr>+++**::part(scroller)**`

=== Edit Dialog

Modality curtain (backdrop):: `vaadin-crud+++<wbr>+++**::part(backdrop)**`
Dialog surface:: `vaadin-crud+++<wbr>+++**::part(overlay)**`
Content area:: `vaadin-crud+++<wbr>+++**::part(content)**`
