---
title: Cookie Consent
layout: tabbed-page
tab-title: Usage
page-links: \
https://github.com/vaadin/vaadin-flow-components/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-cookie-consent-flow}\[Flow {moduleMavenVersion:com.vaadin:vaadin-cookie-consent-flow}], \
https://github.com/vaadin/vaadin-cookie-consent/releases/tag/v{moduleNpmVersion:vaadin-cookie-consent}\[Web Component {moduleNpmVersion:vaadin-cookie-consent}]
section-nav: incomplete, commercial
---

= Cookie Consent

:commercial-feature-included: Cookie Consent is
include::{root}/articles/_commercial-banner.asciidoc[]

// tag::description[]
Cookie Consent aims to help you comply with privacy laws such as GDPR and CCPA.
They require users be informed and explicitly give consent to the usage of cookies.
// end::description[]

By default, the banner is shown at the top of the screen with a predefined text, a link to https://www.cookiesandyou.com[cookiesandyou.com] which explains what cookies are, and a consent button.

.Work In Progress
[NOTE]
====
The usage examples for this component are currently in progress. In the meantime, you can view the previous examples for the web component and the Java/Flow component.

[.buttons]
- https://vaadin.com/components/vaadin-cookie-consent/html-examples[Web Component Examples]
- https://vaadin.com/components/vaadin-cookie-consent/java-examples[Java Component Examples]
====

== Localization

Cookie Consent is fully customisable.
You can customise the message, the “Learn More” link, the “Dismiss” button, as well as the component’s position.

== Positioning

Cookie Consent can be positioned in the viewport in 4 non-stretched positions, or stretched across the top or bottom:



[cols="2"]
|===

|Top left
|Top right

|Bottom left
|Bottom right
|===

[cols="1"]
|===

|Top (stretch, default)

|Bottom (stretch)
|===

On smaller viewports, the component always takes up the entire width of the viewport.

== Theming

Cookie Consent’s theme is modified using CSS.
