---
title: Cookie Consent
layout: tabbed-page
tab-title: Usage
page-links:
  - https://github.com/vaadin/flow-components/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-cookie-consent-flow}[Flow {moduleMavenVersion:com.vaadin:vaadin-cookie-consent-flow}]
  - https://github.com/vaadin/web-components/releases/tag/v{moduleNpmVersion:vaadin-cookie-consent}[Web Component {moduleNpmVersion:vaadin-cookie-consent}]
section-nav: commercial
---

= Cookie Consent

:commercial-feature-included: Cookie Consent is
include::{root}/articles/_commercial-banner.asciidoc[opts=optional]

// tag::description[]
Cookie Consent aims to help you comply with privacy laws such as GDPR and CCPA.
// end::description[]
They require users be informed and explicitly give consent to the usage of cookies.

:example-scale: 0.8
include::../_shared.asciidoc[tag=scaled-examples]

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/cookieconsent/cookie-consent-basic.ts[render,frame,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/cookieconsent/CookieConsentBasic.java[render,frame,tags=snippet,indent=0,group=Java]
----

--

By default, the banner is shown at the top of the screen with a predefined text, a link to https://www.cookiesandyou.com[cookiesandyou.com] which explains what cookies are, and a consent button.

== Localization

Cookie Consent is fully customizable.
You can customize the message, the "Learn More" link, the "Dismiss" button, as well as the component's position.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/cookieconsent/cookie-consent-localization.ts[render,frame,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/cookieconsent/CookieConsentLocalization.java[render,frame,tags=snippet,indent=0,group=Java]
----

--

== Positioning

Cookie Consent can be positioned in the viewport in 4 non-stretched positions, or stretched across the top or bottom:

[cols="<,>"]
|===
|Top left
|Top right

|Bottom left
|Bottom right
|===

[cols="^"]
|===
|Top (stretch, default)
|Bottom (stretch)
|===

On smaller viewports, the component always takes up the entire width of the viewport.

== Theming

Cookie Consent's theme is modified using CSS.

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/cookieconsent/cookie-consent-theming.ts[render,frame,tags=snippet,indent=0,group=TypeScript]
----

[source,css]
----
include::{root}/frontend/themes/docs/cookie-consent-theming.css[]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/cookieconsent/CookieConsentTheming.java[render,frame,tags=snippet,indent=0,group=Java]
----
----
--
