---
title: Cookie Consent
layout: tabbed-page
tab-title: Usage
page-links:
  - https://github.com/vaadin/vaadin-flow-components/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-cookie-consent-flow}[Flow {moduleMavenVersion:com.vaadin:vaadin-cookie-consent-flow}]
  - https://github.com/vaadin/vaadin-cookie-consent/releases/tag/v{moduleNpmVersion:vaadin-cookie-consent}[Web Component {moduleNpmVersion:vaadin-cookie-consent}]
section-nav: incomplete, commercial
---

= Cookie Consent

:commercial-feature-included: Cookie Consent is
include::{root}/articles/_commercial-banner.asciidoc[opts=optional]

// tag::description[]
Cookie Consent aims to help you comply with privacy laws such as GDPR and CCPA.
They require users be informed and explicitly give consent to the usage of cookies.
// end::description[]

.Work In Progress
[NOTE]
====
The usage examples for this component are currently in progress. In the meantime, you can view the previous examples for the web component and the Java/Flow component.

[.buttons]
- https://vaadin.com/components/vaadin-cookie-consent/html-examples[Web Component Examples]
- https://vaadin.com/components/vaadin-cookie-consent/java-examples[Java Component Examples]
====

.Scaled down examples
[IMPORTANT]
The examples on this page are scaled down so that their viewport-size dependant behavior can be demonstrated.
Some examples change their behavior also based on your browser viewport size.

++++
<style>
/* absolute positioning is needed in Chrome for iframes
  to clip the contents inside the border-radius */

/* Aim for 16:9 aspect ratio for "desktop" examples */
.example:not(.mobile) .render {
  position: relative;
  padding: 0;
  padding-top: 52%;
  min-height: 0 !important;
  border: 1px solid var(--docs-divider-color-2);
  border-radius: 0;
  margin: var(--docs-space-s);
  margin-bottom: var(--docs-space-xs);
}

.example {
  /* Just enough to keep "desktop" mode when docs are at max-width */
  --scale: 0.58;
}

/* Examples that want to keep stay in "desktop" mode on all viewport sizes */
@media (max-width: 1260px) {
  .example.desktop {
    --scale: 0.495;
  }
}

@media (max-width: 960px) {
  .example.desktop {
    --scale: 0.47;
  }
}

@media (max-width: 580px) {
  .example.desktop {
    --scale: 0.28;
  }
}

.example:not(.mobile) iframe {
  position: absolute;
  border-radius: 5px;
  transform: scale(var(--scale));
  max-width: calc(100% / var(--scale)) !important;
  width: calc(100% / var(--scale)) !important;
  height: calc(100% / var(--scale));
  transform-origin: 0 0;
  top: 0;
  left: 0;
}

/* Aim for "standard" portrait phone dimensions */
.example.mobile .render {
  min-height: 0 !important;
  width: 256px;
  height: 510px;
  padding: 0;
  margin: 0 auto;
  background: transparent;
}

.example.mobile iframe {
  position: absolute;
  width: 320px !important;
  height: 620px;
  overflow: hidden;
  transform: scale(0.75);
  transform-origin: 32px 120px;
  border-radius: 32px;
  box-shadow: 0 0 0 10px black, 0 3px 22px black;
}
</style>
++++



[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/cookieconsent/cookie-consent-basic.ts[render,frame,tags=snippet,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/demo/component/cookieconsent/example-base.ts[group=TypeScript]
----

//[source,java]
//----
//include::{root}/src/main/java/com/vaadin/demo/component/cookieconsent/CookieConsentBasic.java[render,tags=snippet,indent=0,group=Java]
//----

--

By default, the banner is shown at the top of the screen with a predefined text, a link to https://www.cookiesandyou.com[cookiesandyou.com] which explains what cookies are, and a consent button.

== Localization

Cookie Consent is fully customizable.
You can customize the message, the "Learn More" link, the "Dismiss" button, as well as the component’s position.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/cookieconsent/cookie-consent-localization.ts[render,frame,tags=snippet,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/demo/component/cookieconsent/example-base.ts[group=TypeScript]
----

//[source,java]
//----
//include::{root}/src/main/java/com/vaadin/demo/component/cookieconsent/CookieConsentLocalization.java[render,tags=snippet,indent=0,group=Java]
//----

--

== Positioning

Cookie Consent can be positioned in the viewport in 4 non-stretched positions, or stretched across the top or bottom:

[cols="<,>"]
|===
|Top left
|Top right

|Bottom left
|Bottom right
|===

[cols="^"]
|===
|Top (stretch, default)
|Bottom (stretch)
|===

On smaller viewports, the component always takes up the entire width of the viewport.

== Theming

Cookie Consent’s theme is modified using CSS.

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/cookieconsent/cookie-consent-theming.ts[render,frame,tags=snippet,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/demo/component/cookieconsent/example-base.ts[group=TypeScript]
----

//[source,java]
//----
//include::{root}/src/main/java/com/vaadin/demo/component/cookieconsent/CookieConsentTheming.java[render,tags=snippet,indent=0,group=Java]
//----

--
