---
title: Flex Layout
page-title: Flex Layout component | Vaadin components
description: Flex Layout allows to adjust placement if child components based on flex-box properties in Flow.
meta-description: Learn how to use Vaadin Flex Layout component to arrange components according to flex-box properties you provide. Explore customization options, styling tips, and practical examples.
section-nav: badge-flow
page-links:
  - 'API: https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/orderedlayout/FlexLayout.html[Java]'
  - 'Source: https://github.com/vaadin/flow-components/blob/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/src/main/java/com/vaadin/flow/component/orderedlayout/FlexLayout.java[Java]'
---


= Flex Layout

// tag::description[]
Flex Layout places components in rows or columns. Items expand to fill additional space or shrink to fit into smaller spaces.
// end::description[]
It uses https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox[Flexbox] layout properties
to achieve the desired layout.

From client-side perspective, it is simply a `div` element with `style="display:flex"`, thus no web-component equivalent is provided.
The Flow API adds helpful constants and methods to make the configuration of it simple, and straightforward.


[.example]
--

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/flexlayout/FlexLayoutBasic.java[render,tags=snippet,indent=0,group=Flow]
----
--

By default, items in Flex Layout are arranged in a single row / horizontally without any wrapping, but there are various different configuration options, thanks to some helper methods. This correlates to `flex-wrap` CSS property.

== Direction

By default, https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox[Flexbox] arranges items horizontally in a row. This behavior can be changed by setting a different direction. This correlates to `flex-direction` CSS property.

[.example]
--

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/flexlayout/FlexLayoutDirection.java[render,tags=snippet,indent=0,group=Flow]
----
--

|===
|Value |Description

|`ROW`
|The items are displayed horizontally, as a row.

|`ROW_REVERSE`
|The items are displayed horizontally, as a row in reverse order.

|`COLUMN`
|The items are displayed vertically, as a column.

|`COLUMN_REVERSE`
|The items are displayed vertically, as a column in reverse order.

|===


== Wrap mode

You can control how item overflow (items not fitting in a single line) are handled by choosing a wrap mode.

[.example]
--

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/flexlayout/FlexLayoutWrap.java[render,tags=snippet,indent=0,group=Flow]
----
--


|===
|Value |Description

|`NOWRAP`
|If the items use up too much space they will overflow.

|`WRAP`
|If items are not able to fit into a single row, they are allowed to wrap into the next line.

|`WRAP_REVERSE`
|If items are not able to fit into a single row they are allowed to wrap into the next line. Additionally, the order of the items will be reversed.

|===


== Content Alignment

You can position components in various positions by adjusting the content alignment. This correlates to the `align-content` CSS property.

[.example]
--

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/flexlayout/FlexLayoutContentAlignment.java[render,tags=snippet,indent=0,group=Flow]
----
--

|===
|Value |Description

|`START`
|Items are positioned at the beginning of the container.

|`END`
|Items are positioned at the end of the container.

|`CENTER`
|Items are positioned at the center of the container.

|`STRETCH`
|Items are stretched to fit the container.

|`SPACE_BETWEEN`
|Items are distributed evenly inside the container. The first item is flush with the start, the last is flush with the end.

|`SPACE_AROUND`
|Items are distributed evenly inside the container. Items have a half-size space on either end.

|===

== Item Alignment

You can align components in various ways by adjusting the item alignment. This correlates to the `align-items` CSS property.

Specific items can be aligned differently from the setting used on the layout. This correlates to the `align-self` CSS property.

[.example]
--

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/flexlayout/FlexLayoutItemAlignment.java[render,tags=snippet,indent=0,group=Flow]
----
--

|===
|Value |Description

|`START`
|Items are positioned at the beginning of the container.

|`END`
|Items are positioned at the end of the container.

|`CENTER`
|Items are positioned at the center of the container.

|`STRETCH`
|Items are stretched to fit the container.

|`BASELINE`
|Items are positioned at the baseline of the container.

|`AUTO`
|The element inherits its parent container's align-items property, or "stretch" if it has no parent container.

|===


== Item Order

You can set the order of the components inside the flex layout. The order property specifies the order of a component relative to the rest of the components inside the same layout. The default value is 0, and setting 0 can be used to remove an existing order for a component. This correlates to the `order` CSS property.

[.example]
--

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/flexlayout/FlexLayoutItemOrder.java[render,tags=snippet,indent=0,group=Flow]
----
--


TODO expanding items
TODO ORDER
TODO BASIS
TODO update banner