version: "3"

services:
  docs-app:
    image: vaadin/docbuilder:latest
    environment:
      - "DOCS_PROXY_VAADIN_HOSTNAME=docs"
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: npm run develop
    volumes:
      - docbuilder-maven:/root/.m2
      - docbuilder-pnpm:/root/.pnpm-store
      - docbuilder-gatsby-cache:/docs-app/.cache
      - docbuilder-gatsby-public:/docs-app/public
      - .:/docs
      - ~/.vaadin/proKey:/root/.vaadin/proKey
    links:
      - docs

  docs:
    image: vaadin/docbuilder:latest
    expose:
      - "8080"
    restart: unless-stopped
    working_dir: /docs
    command: mvn
    volumes:
      - docbuilder-maven:/root/.m2
      - docbuilder-pnpm:/root/.pnpm-store
      - docbuilder-vaadin-node-modules:/root/.vaadin/node_modules
      - .:/docs

volumes:
  docbuilder-maven:
  docbuilder-pnpm:
  docbuilder-gatsby-cache:
  docbuilder-gatsby-public:
  docbuilder-vaadin-node-modules:
