version: "3"

services:
  docs-app:
    image: vaadin/docbuilder:latest
    environment:
      - "DOCS_PROXY_VAADIN_HOSTNAME=docs"
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - docbuilder-m2:/root/.m2
      - docbuilder-pnpm:/root/.pnpm-store
      - docbuilder-gatsby-cache:/docs-app/.cache
      - .:/docs
      - ~/.vaadin/proKey:/root/.vaadin/proKey
    links:
      - docs
  docs:
    image: vaadin/docbuilder:latest
    expose:
      - "8080"
    restart: unless-stopped
    working_dir: /docs
    command: mvn
    volumes:
      - docbuilder-m2:/root/.m2
      - docbuilder-pnpm:/root/.pnpm-store
      - .:/docs
volumes:
  docbuilder-m2:
  docbuilder-pnpm:
  docbuilder-gatsby-cache:
