// This TypeScript modules definition file is generated by vaadin-maven-plugin.
// You can not directly import your different static files into TypeScript,
// This is needed for TypeScript compiler to declare and export as a TypeScript module.
// It is recommended to commit this file to the VCS.
// You might want to change the configurations to fit your preferences

// The combo box connector imports an untyped @vaadin/combo-box module whose
// declaration ships as a separate ambient .d.ts in jar-resources. Nothing
// imports that file, and jar-resources is excluded from the include globs,
// so it has to be referenced explicitly for the connector to type-check.
// An import would turn this file into a module and break its ambient
// declarations, hence the reference directive.
// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="./frontend/generated/jar-resources/vaadin-combo-box/vaadin-combo-box-placeholder.d.ts" />
declare module '*.css?inline' {
  import type { CSSResultGroup } from 'lit';
  const content: CSSResultGroup;
  export default content;
}

declare module '*.css';

// Merges into the shared window.Vaadin.Flow interface declared by the Flow
// connectors in jar-resources. loadOnDemand is normally defined by
// generated-flow-imports.js, which the examples do not load, so
// init-flow-namespace.ts provides a stand-in.
interface VaadinFlow {
  loadOnDemand?(id: string): Promise<unknown>;
}

// Allow any CSS Custom Properties
declare module 'csstype' {
  interface Properties {
    [index: `--${string}`]: any;
  }
}
