---
title: Flow
page-title: TODO Write page-title
description: TODO Write description
meta-description: TODO Write meta-description
order: 5
---


= Create a Custom Field in Flow
:toclevels: 2

Write a short introduction about what the user will find on this page.


== Custom Fields in Flow

When you want multiple components to behave as a single form field, or you have a component that doesn’t support integration with Binder, setting labels, or displaying helper text, you should encapsulate those components in a Custom Field.
To create a Custom Field in Flow, you need to define a class that extends the `CustomField` base class and specify the value type that represents the combined value of its internal components.
You'll also need to implement two key methods:

* `generateModelValue()`: Computes the field’s value from the values of its internal components.
* `setPresentationValue(T value)`: Distributes the given value to the internal components.
These methods are automatically invoked when a value changes either on the client side (`generateModelValue`) or on the server side (`setPresentationValue`).

// TODO maybe as info?
The internal components you embed can be any class that extends the Component class. This includes (but is not limited to) <<{articles}/components#,Vaadin Components>> like `TextField`, `DatePicker`, or `Grid`; <<{articles}/flow/create-ui/standard-html#,HTML element wrappers>> like `Input`, `Div`, or `NativeButton`; and third-party components from https://vaadin.com/directory[Vaadin Directory] add-ons.


// TODO gotcha on value-change events?

== Data Binding

There are two primary ways to work with values in a Custom Field:

* Direct interaction with the Custom Field instance
* Integration through Binder

The right approach depends on your use case. If the Custom Field is part of a larger form that maps to a data object, you should typically bind it using `Binder`. However, if the field is standalone, such as when it's used only to filter content in the UI, it may be more appropriate to interact with it directly.

Both approaches are covered below.

=== Direct interaction

Since CustomField implements the HasValue interface, it supports the same API used by other form field components in Vaadin.

You can retrieve and set values using:
```java
myCustomField.getValue();      // Retrieve current value
myCustomField.setValue(value); // Update value
```

To react to value changes, you can register a listener:
```java
myCustomField.addValueChangeListener(listener);
```

It's recommended to use a lambda expression (for short handlers) or a method reference to keep your code concise.

The ValueChangeEvent provides:

* `event.getValue()` – the new value
* `event.getOldValue()` – the previous value
* `event.getSource()` – the source component (your Custom Field)
* `event.isFromClient()` – whether the change originated from the client side

```java
myCustomField.addValueChangeListener(event -> {
    if (event.isFromClient()) {
        var value = event.getValue();
        fullNameDiv.setText("Updated name: %s %s".formatted(value.getFirstName(), value.getLastName()));
    }
});
```

=== Using Binder

Binding a Custom Field works the same way as with built-in components like `TextField` or `ComboBox`. If you’re already familiar with Binder setup and validation, the process will feel familiar.

Example binding:
```java
binder.forField(myCustomField)
    .withValidator(new MyValidator())
    .bind(MyBinderObject::getName, MyBinderObject::setName);
```

In this example, the `MyBinderObject.getName()` (and `setName(..)`) should match the same object type as the Custom Field's value, meaning if your Custom Field extends `CustomField<MyNameObject>` the return type for `MyBinderObject.getName()` should be `MyNameObject`.

Once the binding is configured, calling `binder.setBean(myObject)` or `binder.readBean(myObject)` will automatically populate your Custom Field with the correct value.

== Label

When you extend a `CustomField`, it provides built-in support for setting a label, just like standard Vaadin field components. This means you can use `customField.setLabel("My Field");` to assign a label, and it will behave and appear consistently with other Vaadin input components, making it easy to maintain a uniform design across your forms.


=== Custom Labels for Internal Inputs

In more advanced use cases, your Custom Field might need a special label that cannot be achieved with just styling the label. In such cases, you should:

* Use the `NativeLabel` component to create accessible and styled labels.
* Override the `getLabel()` and `setLabel(String)` methods in your Custom Field to interact with your custom label logic.
* Link each label to its corresponding input using either:
  ** `label.setFor(Component)` (direct reference)
  ** `label.setFor(String)` (by ID)

The input component should have a unique ID set via `input.setId(String)`.

If you have multiple inputs, you can:

* Use individual `NativeLabel` elements for each input.
* Or assign a shared label by setting the `aria-labelledby` attribute on each input to point to a common label ID.


==== Example: Custom Label Handling
```java
public class MyCustomField extends CustomField<Integer> {
    // ...
    private final NativeLabel label;
    private final Input input;

    public MyCustomField(String label) {
        input = createInput();
        label = new NativeLabel(label);
        label.setFor(input);

        var layout = new Div(label, input);
        add(layout);
    }

    @Override
    public String getLabel() {
        return label.getText();
    }

    @Override
    public void setLabel(String labelText) {
        label.setText(labelText);
    }

    private Input createInput() {
        var input = new Input();
        // Generate a (very likely) unique field id
        input.setId("my-custom-field-" + RandomGenerator.getDefault().nextInt(1, 100_000));
        return input;
    }
}
```


== Validation

When you extend a `CustomField`, it provides built-in support for displaying the field errors and marking the field as invalid.
This means you can use `customField.setErrorMessage("My Field")` to specify an error message, mark field as invalid with `customField.setInvalid(true)'` so that it displays the error message, and applies "invalid" styling to the field. Built-in implementation will behave and appear consistently with other Vaadin input components, making it easy to maintain a uniform design across your forms.

Field that is attached to a binder and that has validators specified will automatically handle the visibility and content of the error message within the field.

=== Using built-in error message of an internal component

If you just want to move validation to an internal component of your Custom Field, it is as simple as overriding a few methods.
In the following example, we have a Custom field that displays button and a text field side-by-side, but instead of the error message appearing under the combined field, we want it to be displayed only under the text field. For that to work we need to override:

* `isInvalid()` to use both the invalid state from the custom field and internal field.
* `setInvalid(boolean)` to set the invalid state on both the custom field and internal field.
* `getErrorMessage()` to retrieve the error message only from the internal field.
* `setErrorMessage(String)` to set the error message only on the internal field.

```java
public class ButtonTextFieldCustomField extends CustomField<String> {

    private final Button button = new Button("My button");
    private final TextField textField = new TextField();

    public ButtonTextFieldCustomField() {
        var layout = new HorizontalLayout(button, textField);
        add(layout);
    }

    @Override
    public boolean isInvalid() {
        return super.isInvalid() || textField.isInvalid();
    }

    @Override
    public void setInvalid(boolean invalid) {
        super.setInvalid(invalid);
        textField.setInvalid(invalid);
    }

    @Override
    public String getErrorMessage() {
        return textField.getErrorMessage();
    }

    @Override
    public void setErrorMessage(String errorMessage) {
        textField.setErrorMessage(errorMessage);
    }

    @Override
    protected String generateModelValue() {
        return textField.getValue();
    }

    @Override
    protected void setPresentationValue(String s) {
        textField.setValue(s);
    }
}

```

=== Using a custom element for error messages

In more advanced use cases, your Custom Field might need to display the errors in a separate element.
There are several things that you will need to do to achieve this.

* Use an appropriate element / component that will contain the error message (usually `Div`)
* Give your element / component a unique `id` (you will likely need to generate part of it).
* Use `aria-describedby` on your `input` elements to link them to the error message, by setting its value
to the error message element `id`. When there is no error message, you should remove the reference to the error message element.
This is required for screen readers to provide user with info about the error.
* Handle the visibility of the error message element(s) yourself. Usually you should hide it if the component is marked as valid
(you can override the `setInvalid(boolean)` method and add code to handle this) and reveal it if it's invalid and there's
an error message to be shown.

```java
private final Div errorDiv = new Div();

public MyCustomField() {
    errorDiv.setId("my-custom-field-error-" + uniqueFieldNumber);

    Input input = createInput();

    var layout = new Div(label, errorDiv, input);

    add(layout);
}

@Override
public String getErrorMessage() {
    return errorDiv.getText();
}
@Override
public void setErrorMessage(String errorMessage) {
    errorDiv.setText(errorMessage);
}

@Override
public void setInvalid(boolean invalid) {
    super.setInvalid(invalid);
    if (invalid) {
        errorDiv.setVisible(true);
        input.getElement().setAttribute("aria-describedby", errorDiv.getId().orElse(""));
    } else {
        errorDiv.setVisible(false);
        input.getElement().removeAttribute("aria-describedby",);
    }
}

```

// TODO internal validation

Explain how to handle required fields and validation errors in a custom field.
You can assume the reader already knows how to add validators to the Binder.


== Styling

Explain how to style the custom field if needed.


== Accessibility

Explain how to make the custom field accessible.


[.collapsible-list]
== Try It

Introduce the mini-tutorial here. The user should download the skeleton and then follow the steps in the tutorial to build and test a custom field.


.Set Up the Project
[%collapsible]
====
To start, generate a <<{articles}/getting-started/start#,walking skeleton with a Flow UI>>, <<{articles}/getting-started/import#,open>> it in your IDE, and <<{articles}/getting-started/run#,run>> it with hotswap enabled.
====


.Step 2
[%collapsible]
====
Step 2 goes here
====


.Step 3
[%collapsible]
====
Step 2 goes here
====


.Final Thoughts
[%collapsible]
====
Summarize the tutorial.
====
