---
title: Native Image Compilation
description: How to compile a Hilla application into a native image using GraalVM.
order: 40
---

= [since:dev.hilla:hilla@v2]#Native image compilation with GraalVM#

Hilla uses Spring Boot 3 and supports native image compilation with GraalVM. By compiling an application into a native image, you can benefit from much faster startup times (i.e., in milliseconds) and lower memory consumption compared to running the application on the JVM.



== Requirements

Before you begin, ensure that you have a JDK with GraalVM support. To check whether you have a JDK with GraalVM support, execute the following in your terminal like so:

[source,bash]
----
java -version
----

If the output contains the following text, you have a JDK with GraalVM support installed:

----
GraalVM
----

If not, you can install one by following the instructions in the link:https://www.graalvm.org/latest/docs/getting-started/#install-graalvm[Install GraalVM] section of the GraalVM documentation, or by using the link:https://sdkman.io/[SDKMAN] tool.


== Compilation

To compile your Hilla application into a native image, you'll need to perform a couple of steps. First, Compile your application using Maven by executing the following at the command-line in the project root directory:

[source,bash]
mvn -Pproduction -Pnative native:compile

This compiles your application with the production and native profiles enabled. The native profile instructs Maven to use the GraalVM native image compiler for the compilation process.

The next step is to run the application. The compilation creates the native image in the target directory. To run the application, execute the following from the command-line:

[source,bash]
----
./target/<app-name>
----

Your Hilla application is now running as a native image, benefiting from faster startup times and lower memory consumption.


== More Resources

For more information on native image compilation and instructions on creating Docker images using build packs, see the link:https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html[Spring Boot Reference Guide].
