---
title: Native Image Compilation
description: Learn how to compile your Hilla application to a native image with GraalVM.
order: 40
---

= Native Image Compilation with GraalVM 

Hilla 2 uses Spring Boot 3 and supports native image compilation with GraalVM. By compiling your application into a native image, you can benefit from startup in milliseconds and lower memory consumption compared to running the application on the JVM.

This documentation page guides you through the process of compiling your Hilla project into a native image using GraalVM.

== Requirements

Before you begin, ensure you have a Hilla 2.0 (or later) project and a JDK with GraalVM support.


== Compilation Steps

To compile your Hilla application into a native image, follow these steps:

=== Step 1: Compile the Application

Compile your application using Maven by executing the following command in the project root directory:

[source,bash]
mvn -Pproduction -Pnative native:compile

This command compiles your application with the production and native profiles enabled. The native profile instructs Maven to use the GraalVM native image compiler for the compilation process.

=== Step 2: Run the Application

The compilation creates the native image in the target directory. To run the application, execute the following command:

[source,bash]
----
./target/<app-name>
----

Your Hilla application is now running as a native image, benefiting from faster startup times and lower memory consumption.

== Additional Resources

For more information on native image compilation and instructions on creating Docker images using build packs, see the link:https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html[Spring Boot Reference Guide].