---
title: Production build, database, and cloud deployment
order: 150
layout: page
page-title: Hilla production builds and deployment
description: Learn how to optimize your Hilla application for production and deploy it to Heroku
---

= Production Mode and Cloud Deployment to Heroku

In this last chapter, you prepare the CRM application for production and deploy it to Heroku.
The tutorial uses Heroku because it's simple and comes with a free tier that doesn't require a credit card when signing up.
The free tier also includes PostgreSQL support.

.You can deploy Hilla applications on any cloud provider
[NOTE]
====
You can deploy Hilla applications on any cloud provider or hosting service that supports Java.
The project also contains a `Dockerfile` that you can use for container deployments. https://vaadin.com/learn/tutorials/cloud-deployment/[Learn more about deploying to different cloud providers.]
====

This chapter covers:

* Hilla production builds,
* creating a Heroku account,
* installing the Heroku CLI,
* creating and deploying a Heroku application.

include::{articles}/lit/tutorials/todo/index.adoc[tag=heroku-steps,leveloffset=-1]

== Conclusion and Next Steps

Congratulations, you have now built a full-stack PWA and deployed it to Heroku.

Did you like the tutorial? Did you find anything that didn't seem right? Reach out to me on Twitter https://twitter.com/marcushellberg[@marcushellberg] or https://discord.gg/vaadin[Hilla's Discord chat] server.

Now that you have a running application, you can use it to experiment further or as a foundation for your next idea.

pass:[<!-- vale Vale.Terms = NO -->]
Happy hacking, and ping us https://twitter.com/vaadin[@vaadin] on Twitter to show off the cool stuff you have built.

pass:[<!-- vale Vale.Terms = YES -->]

=== Helpful Links

- https://github.com/vaadin-learning-center/fusion-crm-tutorial[Source code GitHub repository]
- https://discord.gg/vaadin[Hilla Discord chat]
- https://vaadin.com/forum[Hilla Forum]
- https://vaadin.com/docs/ds/components[Vaadin components]
- https://vaadin.com/comparison[Compare Hilla with React, Angular, and Vue]
