---
title: Defining Routes
description: Using the Route annotation to define route URLs
order: 10
---

= Defining Routes

You can use the [annotationname]`@Route` annotation to define any component as a route target for a given URL fragment.

*Example*: Defining the [classname]`HelloWorld` component as the default route target (empty route) for your application.

[source,java]
----
@Route("")
public class HelloWorld extends Div {
    public HelloWorld() {
        setText("Hello world");
    }
}
----

*Example*: Defining the [classname]`SomePathComponent` component as the target for the specific route `"some/path"`.

[source,java]
----
@Route("some/path")
public class SomePathComponent extends Div {
    public SomePathComponent() {
        setText("Hello @Route!");
    }
}
----

Assuming your application is running from the root context, when the user navigates to `\http://example.com/some/path`, either by clicking a link in the application or entering the address in the address bar, the [classname]`SomePathComponent` component is shown on the page.

If you omit the `@Route` annotation parameter, the route target is derived from the class name.
The derived name will be in lower case and the trailing *View* will be removed.
Also, *MainView* or *Main* names will be mapped to *root* (_value will be_ *""*).

For example:

- [classname]`MyEditor` becomes `"myeditor"`
- [classname]`PersonView` becomes `"person"`
- [classname]`MainView` becomes `""`

== Creating Route Aliases

You can also use `@RouteAlias` to create aliases for routes. 
A primary route created by `@Route` is required.
It is possible to create multiple aliases for a route.

*Example*: Adding two `@RouteAlias` annotations for `HomeView`. Navigating to `"home"` or `"main"` will navigate to the same view as the main route.
[source,java]
----
@Route("")
@RouteAlias("home")
@RouteAlias("main")
public class HomeView extends Div {
    public HomeView() {
        setText("Hello @Route!");
    }
}
----