---
title: Build a Project
page-title: How to make a production build of a Vaadin application
description: Make a production build of your Vaadin application.
meta-description: Learn to make a production build of your Vaadin application. Use the Vaadin Maven plugin to optimize frontend resources, minimize dependencies, and package your app for deployment.
order: 40
---


= Build a Project

Up to this point, the walking skeleton has been <<run#,running in development mode>>. Once you've added meaningful features, you can deploy your application to production. To do that, you have to make a production build. The build gathers necessary frontend resources and dependencies. It then transpiles, minimizes and bundles them to make the application load faster.


== Make a Production Build

In the walking skeleton, you use the Vaadin Maven plugin to make a production build. You do this by activating the `package` goal, like this:

[.example]
--
[source,bash,subs="+attributes"]
----
<source-info group="macOS / Linux"></source-info>
./mvnw clean package
----

[source,powershell,subs="+attributes"]
----
<source-info group="Windows"></source-info>
mvnw clean package
----
--

Once the build has finished, check the `target` directory. If your skeleton was named `my-application`, you should find a file called `my-application-1.0-SNAPSHOT.jar`.

The `package` goal not only builds the frontend, but also excludes the development server bundle since it contains features that aren't used in production.


== Build a Docker Image

The walking skeleton includes a `Dockerfile` that allows you to package your application as a Docker image.

.Install Docker
[IMPORTANT]
You must install Docker on your system before you can build an image.

Run the following command from your project root to build the image:

[source,terminal]
----
docker build -t my-application:latest .
----

This command builds your application in production mode and produces a Docker image tagged `my-application:latest`.


=== Building with Commercial Components

If your application uses commercial components, you need a <</flow/configuration/licenses#,licence key>>.

When building locally with Maven, the Vaadin Maven plugin detects the license automatically. For Docker builds, you must pass the key explicitly as a secret:

[.example]
--
[source,bash,subs="+attributes"]
----
<source-info group="macOS / Linux"></source-info>
docker build -t my-application:latest --secret id=proKey,src=$HOME/.vaadin/proKey .
----

[source,powershell,subs="+attributes"]
----
<source-info group="Windows"></source-info>
docker build -t my-application:latest --secret "id=proKey,src=$($env:USERPROFILE)\.vaadin\proKey" .
----
--

If you need to use an offline key, you can pass it like this:

[.example]
--
[source,bash,subs="+attributes"]
----
<source-info group="macOS / Linux"></source-info>
docker build -t my-application:latest --secret id=offlineKey,src=$HOME/.vaadin/offlineKey .
----

[source,powershell,subs="+attributes"]
----
<source-info group="Windows"></source-info>
docker build -t my-application:latest --secret "id=offlineKey,src=$($env:USERPROFILE)\.vaadin\offlineKey" .
----
--

.A Peek Under the Hood
[NOTE]
====
The `--secret` option works because the provided `Dockerfile` in the walking skeleton mounts the files, parses them and passes them on to Maven:

[source,docker]
----
# (Previous build steps omitted for brevity)
# ...

RUN --mount=type=cache,target=/root/.m2 \
    --mount=type=secret,id=proKey \
    --mount=type=secret,id=offlineKey \
    sh -c 'PRO_KEY=$(jq -r ".proKey // empty" /run/secrets/proKey 2>/dev/null || echo "") && \
    OFFLINE_KEY=$(cat /run/secrets/offlineKey 2>/dev/null || echo "") && \
    ./mvnw clean package -DskipTests -Dvaadin.proKey=${PRO_KEY} -Dvaadin.offlineKey=${OFFLINE_KEY}'
----    

For more information about build secrets in Docker, see the https://docs.docker.com/build/building/secrets/[Docker documentation].
====
