---
title: Next Steps
page-title: Add features to your Vaadin project
description: Add features to your Vaadin project to turn it into a full-featured application.
meta-description: Turn your Vaadin project into a fully functional application by adding views, navigation, data handling, security, and a production-ready database.
order: 100
---


= Expand your Vaadin Project

You have now created, started, and built your first Vaadin project. Now it is time to start adding features to it, turning it into a fully functional application. The <<{articles}/building-apps#,Building Apps>> section of the documentation contains all the resources you need.


== Add Views & Navigation

Expand your application by adding multiple views and enabling navigation between them. See the <<{articles}/building-apps/views#,Views & Navigation>> guides for step-by-step instructions.


== Add Data

Integrate data handling into your application with forms, validation, and interactive grids. Learn how to manage user input and display dynamic content by following the <<{articles}/building-apps/forms-data#,Forms & Data>> guides.


== Implement Security

Secure your application with user authentication and authorization. Refer to the <<{articles}/building-apps/security#,Security>> guides to learn how.


== Use a Real Database

Replace the in-memory H2 database with a production-ready database. Follow the <</building-apps/forms-data/add-flyway#,Add Flyway>> and <</building-apps/forms-data/replace-h2#,Replace H2>> guides for details.
