---
title: Session Expiration
description: How to detect session expiration, for example to show a login view to the user.
order: 141
---
// tag::content[]

= Handling Session Expiration

You can use the built-in <<../client-middleware#, middleware>> [classname]`InvalidSessionMiddleWare` to detect when a user session expires.

This middleware requires a function as a constructor parameter (type of `OnInvalidSessionCallback`).
The function should return a promise of [classname]`LoginResult`, containing the metadata of a login result, including:

`error`::
Indicates whether the login attempt has failed.

`token`::
In the event of a successful login, this is the cross-site request forgery (CSRF) prevention token, which can be extracted from the [filename]`index.html` page.
See <<configuring#csrf, CSRF protection of Hilla endpoints>> for more information.

`errorTitle`::
A short text describing a login error.

`errorMessage`::
A more detailed explanation of the login error.



== Example

As an example, you can use the `InvalidSessionMiddleware` to show a login view to the user.

[.example]
--
[source,typescript]
----
include::{root}/frontend/demo/fusion/authentication/handle-session-expiration/connect-client.ts[]
----
[source,typescript]
----
include::{root}/frontend/demo/fusion/authentication/handle-session-expiration/login-overlay.ts[]
----
--

// end::content[]
