---
title: Feature Flags
description: Feature flags is a mechanism that allows you to enable and test experimental features. You can also temporarily switch back to legacy and deprecated behaviors, to have time to migrate away from them, until they are removed.
order: 160
---

= Feature Flags

The following listings contain all experimental and legacy features.
They are also listed in the [classname]`com.vaadin.experimental.FeatureFlags` (https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/experimental/FeatureFlags.html[JavaDoc]) class.

== Experimental Features

// Prevent names from wrapping
++++
<style>
dl code {
  word-break: initial !important;
}
</style>
++++

`enforceFieldValidation`::
Enforce client / constraint / binder validation

`spreadsheetComponent`::
Spreadsheet component (Pro)

`hillaPush`::
Push support in Hilla

`hillaEngine`::
Multi-module engine in Hilla

`collaborationEngineBackend`::
Collaboration Engine backend for clustering support

[deprecated:com.vaadin:vaadin@V23.2]#`mapComponent`#::
Map component (Pro)
+
[small]#Since Vaadin 23.2, the Map component can be used without the feature flag.#

== Legacy Features

`oldLicenseChecker`::
Old license checker

`webpackForFrontendBuild`::
Use webpack for front-end builds


== Managing Feature Flags

Feature flags can be managed in different ways:

- using Vaadin Developer Tools;
- editing the feature flags properties file;
- setting Java system properties.

System properties always have the highest priority.
Since they are not written into the feature flags properties file, they are valid only for a single execution.

=== Using Vaadin Developer Tools

. Click the Vaadin Developer Tools icon button in your application in bottom right corner of the browser, when running in development mode.
. Open the [guilabel]*Experimental Features* tab.
. Click the toggle buttons to enable or disable features.
. Restart the application.

=== Editing the Properties File

. Create or edit the [filename]`src/main/resources/vaadin-featureflags.properties` file in your application folder.
. Add a line for every feature in the format of `com.vaadin.experimental.<FEATURE_NAME>=true`, for example:
+
.`vaadin-featureflags.properties`
[source,properties]
----
vaadin.experimental.enforceFieldValidation=true
----
. To disable a feature remove the corresponding line or set the value to `false`.
. Restart the application.

=== Setting Java System Properties

On the command line, IDE launch configuration or tool configuration (for example Spring Boot Maven plugin), set a system property for every feature flags to be enabled or disabled.
The property name should be in the format `vaadin.<FEATURE_NAME>`, for example:

[source,terminal]
-Dvaadin.enforceFieldValidation=true

To temporarily disable a feature, use `false` as property value, for example:

[source,terminal]
-Dvaadin.enforceFieldValidation=false
