---
title: Licenses
description: Validate and troubleshoot commercial Vaadin licenses.
order: 150
---

= License Validation and Troubleshooting

Vaadin core includes an extensive set of technologies and components that are free to use.
Vaadin core is available under the terms of the Apache License 2.0, which allows you to use the included technologies and components in any project, even commercially.

You only need a commercial license if you use one of the commercial components (such as, Vaadin Charts) or tools (such as, Vaadin TestBench).
If your project includes such components or tools, a commercial license is needed for development and to build the production application.
In general, you do not need a license after deploying the application into production.
However, the only exception is if you are using Collaboration Engine, in which case a license is needed for the production environment as well as it is priced per end user.

== License Validation on a Local Machine

pass:[<!-- vale Vale.Terms = NO -->]

On a local machine, the licenses for commercial components are checked automatically using your https://vaadin.com[vaadin.com] login.
The first time you are using a commercial product, you will be asked to log in to https://vaadin.com[vaadin.com] to validate your license.

pass:[<!-- vale Vale.Terms = YES -->]
Once validated, you will be able to use the product in your project.
Under the hood, a license key is created in your machine at the following location:


.Windows
[source,terminal]
%HOMEPATH%\.vaadin\proKey 

.macOS and Linux
[source,terminal]
~/.vaadin/proKey


pass:[<!-- vale Vale.Terms = NO -->]

If your local development environment is offline and cannot reach https://vaadin.com[vaadin.com], you need to download an offline license key.

pass:[<!-- vale Vale.Terms = YES -->]
The offline license key is tied to a *Machine ID* that you submit to https://vaadin.com/pro/validate-license to retrieve the license key.
You can find your *Machine ID* in the logs when you try to use a component offline without an existing license key.

Once you download the generated [filename]#offlineKey# file, you should place it in your _home_ directory:

[source]
~/.vaadin/offlineKey (macOS/Linux) or %HOMEPATH%\.vaadin\offlineKey (Windows)

== License Validation on a CI or Build Server


. Alternatively, you can supply the license key using a system property
+
If defined, the `vaadin.proKey` system property will be used instead of the file in the home directory.
The format of the system property is
+
[source]
-Dvaadin.proKey=<login-email>/<key starting with pro->

For CI/CD servers, you need to download a **server license key**.
Server license keys can only be used for production builds.
You can download a server license key (an [filename]#offlineKey# file) from https://vaadin.com/myaccount/licenses.

You should place the [filename]#offlineKey# file in the _home_ directory of the CI server:

[.example]
--
[source]
----
<source-info group="Windows"></source-info>
%HOMEPATH%\.vaadin\offlineKey
----

[source]
----
<source-info group="macOS/Linux"></source-info>
~/.vaadin/offlineKey
----
--


== Common License Questions and Issues

=== License Validation Fails Because Of Proxy Settings

If you are behind a proxy, you may need to configure proxy settings for your IDE.

* Eclipse: https://mkyong.com/web-development/how-to-configure-proxy-settings-in-eclipse/
* IntelliJ Idea: https://www.jetbrains.com/help/idea/settings-http-proxy.html


=== I Get A Trial Message Although I Have A Valid License

Check if you have a valid license by going to https://vaadin.com/pro/validate-license.
If not, either your company's license administrator has not yet assigned a seat for you, or the license is no longer valid.

=== SSLHandshakeException With Multiplatform Runtime

There is a known error in `SSLHandshakeException` reported by users of WebSphere Liberty and WildFly in Docker: https://vaadin.com/forum/thread/18444677/running-mpr-project-on-websphere-liberty-fails-with-suncertpathbuilderexcep.

=== Where Can I Get Help With License Related Issues?

You can contact license@vaadin.com for further assistance.


[.discussion-id]
D56655EB-4310-49FF-8A81-E790235E1420
