---
title: License
description: Configure Vaadin license for your projects.
order: 40
---

== Scenarios Which A License Is Not Needed
=== Only Free Components Are Used

No license is needed if you are only using the core, free components.

=== Production Use (Except Collaboration Engine)

In general, after deploying the application into production you don't need a subscription to use commercial Vaadin components and features.
A valid Vaadin subscription is only needed for development and to build the production application.

The only exception for this rule is the **Collaboration Engine**, which is priced per end user.

== License Validation Process

The licenses for commercial components are checked through your https://vaadin.com login. 
The first time you are using a commercial product, it will ask you to log in to vaadin.com to validate your license.

You only need to manually install the license key when running on a CI/build server.

=== License Validation when offline
If your development environment is offline and cannot reach https://tools.vaadin.com, you need to download an offline license.
The offline license is tied to a *Machine Id* that you submit to https://vaadin.com/pro/validate-license to retrieve the license.
You can find your  *Machine Id* in the logs when you try to use a component offline without a license.

== Common Tasks
=== Check If You Have A Pro, Prime, Or Enterprise License

Check by going to https://vaadin.com/pro/validate-license. 

Please find Vaadin's open source licensing terms https://vaadin.com/license[here].

=== Assign License Seats For Team Members

*For Team Members*:

License seats can be assigned only by either the license owner or the administrator. 
Please contact your team's license administrator.

[#4975B5B5-D08B-4662-8B79-816E1609A1B0,admin-license-management]
*For license owner or administrator*: 

. Login to vaadin.com.
. Click on your avatar at the top-right corner.
. Select *My Account*.
. Team management

=== Re-Assign The License When A Developer Leaves The Team
The license owner or administrator can reassign the seat to someone else by either:

. Following the steps to <<4975B5B5-D08B-4662-8B79-816E1609A1B0, manage licenses>>.
. Sending an email to license@vaadin.com for assistance.

=== Use The License With TestBench, Designer, Multiplatform Runtime (MPR)
You can install the ProKey to your development machine or CI server via instructions https://vaadin.com/pro/validate-license[here].

=== Use the License on CI/CD Servers

If you need a license for a build or CI server, you don't need a separate license seat for it.
You can just use one of the existing developer licenses.

You have two options to install your license on your server.

. Copy the license from your _home_ directory to the _home_ directory on the server.
+
The license file is installed at
+
*Windows*
[source,terminal]
%HOMEPATH%\.vaadin\proKey 
+
*Mac/Linux*
[source,terminal]
~/.vaadin/proKey
+
If you do not have a license installed on your development machine, yoiu can also download your personal *proKey* file from https://vaadin.com/pro/validate-license[here].

. Supply the license information using a system property
+
If defined, the `vaadin.proKey` system property will be used instead of the file in the home directory. The format of the system property is
+
[source]
-Dvaadin.proKey=<login-email>/<key starting with pro->

==== Use Vaadin With Offline CI/CD Servers

For CI/CD servers that are offline and cannot reach https://tools.vaadin.com, you need to download an **offline CI license**.
This offline license can only be used for production builds.
You can get this license by:

. Go to https://vaadin.com/pro/validate-license.
. Select *Generate and offline license for CI only*.

== Troubleshoot Common License Issues

=== I Get A Trial Message Although I Have A Valid License
Check if you have a valid license by going to https://vaadin.com/pro/validate-license. 
If not, either your company's license administrator has not yet assigned a seat for you, or the license is no longer valid.

=== This Application Is Using Components Which Are A Part Of A Vaadin Subscription
Check if you have a valid license by going to https://vaadin.com/pro/validate-license.

Clear Vaadin cookies and try again.

Please make sure that you use the same window.

Sometimes, ad-blockers or 3rd party cookie denial could be blocking the license check. 
If this is the case, the error message *only* appears in development mode when in localhost. 
When the application is deployed into production and accessed from outside it will not show, thus the message *is not be visible to the end users* of the application.

=== Why Does My Student License Show As A Trial?
Sometimes a student license shows as a trial, but the license is a valid Vaadin Pro student license and works normally.

Students can check the student program state by opening the profile menu or at https://vaadin.com/myaccount/subscriptions.

=== Why Is My Github Student Status Not Verified?
Please re-apply for the student program at https://vaadin.com/student-program.
If the problem continues, please contact us in the Vaadin https://discord.gg/vaadin[Discord channel].

=== License Validation Fails Because Of Proxy Settings

If you are behind a proxy, you may need to configure proxy settings for your IDE.

* Eclipse: https://mkyong.com/web-development/how-to-configure-proxy-settings-in-eclipse/
* IntelliJ Idea: https://www.jetbrains.com/help/idea/settings-http-proxy.html

=== SSLHandshakeException With Multiplatform Runtime
There is a known error in  SSLHandshakeException reported by users of WebSphere Liberty and WildFly in Docker: https://vaadin.com/forum/thread/18444677/running-mpr-project-on-websphere-liberty-fails-with-suncertpathbuilderexcep

== Where can I get help with license related issues?

Please contact license@vaadin.com for further assistance.