---
title: Installation of Dependencies
description: Learn how to manually install Control Center's dependencies.
order: 20
---


= Installation of Dependencies

This guide explains how to install the required dependencies of Control Center without utilizing cluster-wide administrator permissions.


== NGINX Ingress Controller

The https://kubernetes.github.io/ingress-nginx/[Ingress NGINX Controller] manages external access to services in your cluster. You can install it by running the following command:

.Terminal
[source,bash]
----
helm upgrade --install ingress-nginx ingress-nginx \
  --repo https://kubernetes.github.io/ingress-nginx \
  --namespace ingress-nginx \
  --create-namespace \
  --version 4.11.3
----


== Cert-Manager

https://cert-manager.io[Cert-Manager] is a Kubernetes add-on that automates the management of TLS certificates. You can install it by running the following command:

.Terminal
[source,bash]
----
helm upgrade --install cert-manager cert-manager \
  --repo https://charts.jetstack.io \
  --namespace cert-manager \
  --create-namespace \
  --set crds.enabled=true \
  --version v1.16.1
----


== CloudNativePG

https://cloudnative-pg.io[CloudNativePG] is a PostgreSQL database that Control Center uses to store application data. You can install it by running the following command:

.Terminal
[source,bash]
----
helm upgrade --install cnpg cloudnative-pg \
  --repo https://cloudnative-pg.github.io/charts \
  --namespace cnpg-system \
  --create-namespace \
  --version v0.22.1
----


== Keycloak

https://www.keycloak.org[Keycloak] is an open-source identity and access management solution that Control Center uses for authentication. You can install it by running the following commands:

.Terminal
[source,bash]
----
kubectl create namespace control-center
----

.Terminal
[source,bash]
----
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/25.0.6/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
----

.Terminal
[source,bash]
----
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/25.0.6/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
----

.Terminal
[source,bash]
----
kubectl -n control-center apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/25.0.6/kubernetes/kubernetes.yml
----
