---
title: Getting Started
description: Learn how to use Control Center.
order: 20
---


= Getting Started


== Prerequisites

To ensure a smooth start with Control Center, you should have the following setup ready:

- A running Kubernetes cluster is essential. This could be a cloud-based Kubernetes service like https://cloud.google.com/kubernetes-engine[Google Kubernetes Engine (GKE)], https://aws.amazon.com/eks[Amazon EKS], or https://azure.microsoft.com/en-us/products/kubernetes-service[Azure AKS], or a locally managed cluster using https://www.docker.com/products/docker-desktop[Docker Desktop] or https://minikube.sigs.k8s.io[minikube]. The choice depends on your project needs and scalability considerations.
- https://helm.sh[Helm] is a powerful Kubernetes package manager. It simplifies the deployment and management of applications on Kubernetes. Ensure you have Helm installed and configured to interact with your cluster.


== Deploy Control Center

The journey begins with deploying Control Center to your Kubernetes cluster. This step involves using Helm, the Kubernetes package manager, which simplifies the deployment process and sets up Control Center with the necessary configurations. Open your terminal and execute the following command:

[source,bash]
----
helm install control-center oci://docker.io/vaadin/control-center \
    -n control-center --create-namespace \
    --set serviceAccount.clusterAdmin=true \
    --set service.type=LoadBalancer --set service.port=8000
----

This command does several things:

- `helm install control-center oci://docker.io/vaadin/control-center`
tells Helm to install the Control Center package from the specified repository;
- `-n control-center --create-namespace`
ensures that a dedicated namespace is created for Control Center, keeping it isolated from other applications;
- `--set serviceAccount.clusterAdmin=true`
grants Control Center administrative privileges, allowing it to manage cluster resources effectively;
- `--set service.type=LoadBalancer --set service.port=8000`
configures the service to use a load-balancer (ideal for cloud deployments) and sets the service port to 8000 (this works on local cluster, otherwise use any port that works to connect to your cloud provider).

[NOTE]
====
You're not required to grant Control Center administrative privileges on the cluster, but that allows automatic installation of required dependencies. If you don't grant the privileges, you'll need to install any required resource manually.
====
