---
title: Upgrading
page-title: Upgrading Vaadin Control Center
description: How to upgrade Vaadin Control Center from an older version to the latest.
order: 110
---


= Upgrading Control Center

Instructions how to upgrade Vaadin Control Center from an older version to the latest version.


== From 1.0 to 1.1

In general, it's important and beneficial to use the latest version of software. The Vaadin Control Center is no different in this way. How you migrate from one version to another can depend on how old is the version you're currently using.

== Upgrading from 1.1 or Later

To upgrade Control Center from version 1.1 or later to the latest version, you can use the `helm upgrade` command. This command updates the Docker image of the Control Center deployment to the new version. Assuming you installed Control Center using `control-center` as the installation name and namespace, execute the following command:

[source,bash]
----
helm upgrade --install control-center oci://docker.io/vaadin/control-center \
    -n control-center \
    --reuse-values
----

.Securing your data
[TIP]
Although nothing should happen to Control Center-managed databases and users when upgrading, it is advisable to perform a xref:../database/backups.adoc[Backup] before proceeding with an upgrade to prevent any data loss.


== Upgrading from 1.0

To upgrade Control Center from version 1.0 to a later version, you'll need to perform three tasks:

- Add a configuration property to the Control Center configmap;
- Create a secret that holds the email and password for the Control Center user that was created with the installation wizard; and
- Set the Docker image of the Control Center deployment to the new version.

All the example commands on this page assume that Control Center was installed in the namespace called, `control-center`.


=== New Necessary Configuration Property

Control Center 1.1 and later versions use a configuration property that doesn't exist in version 1.0. If this property is missing, your deployment won't work after upgrading. To prefer for this possibility, edit the configmap for Control Center to add the following under the `data` segment:

[source,yaml]
----
# data:
  vaadin.control-center.keycloak.admin-secret: control-center-keycloak-initial-admin
----

To edit the Control Center configmap, execute the following from the command-line:

[source,bash]
----
kubectl -n control-center edit configmap control-center
----


=== Secret for Control Center User Credentials

You'll need to set up a secret which holds the email and password of the main Control Center user. These values must be the same as what was entered during the installation process of version 1.0, in the installation wizard. Assuming the email was `user@example.com` and the password was `examplepassword123`, you would execute the following:

[source,bash]
----
kubectl -n control-center create secret generic control-center-user \
--from-literal=email=user@example.com \
--from-literal=password=examplepassword123
----

You'll have to adjust these values, though, for your email address and password.


=== Upgrading Docker Image

The last step is done when you upgrade your deployed Control Center application to use an updated image. Assuming your Control Center deployment is named, `control-center`, upgrade its Docker image by executing this:

[source,bash]
----
kubectl -n control-center set image deployment/control-center app=vaadin/control-center-app:version
----

Replace `version` with the version to which you want to upgrade. For example, to upgrade to version 1.1.0, you would use `1.1.0`.
