---
title: Context Menu
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-context-menu/{moduleNpmVersion:vaadin-context-menu}/#/elements/vaadin-context-menu[Web Component] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/contextmenu/ContextMenu.html[Java]'
  - 'Source: https://github.com/vaadin/vaadin-context-menu[Web Component] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-context-menu-flow-parent[Java]'
---

= Context Menu

// tag::description[]
Context Menu is a component that you can attach to any component to display a context menu.
// end::description[]
The menu appears on right (default) or left click.
On a touch device, a long press opens the context menu.

// tag::example-instructions[]
[IMPORTANT]
Open the Context Menu by right-clicking (mouse) or long-pressing (touch) a Grid row.
// end::example-instructions[]

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-basic.ts[preimport,hidden]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuBasic.java[render,tags=snippet,indent=0]
----
--

== Dividers

You can use dividers to separate and group related content.
Use dividers sparingly to avoid creating unnecessary visual clutter.

include::index.asciidoc[tag=example-instructions]

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-dividers.ts[preimport,hidden]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuDividers.java[render,tags=snippet,indent=0]
----
--

== Checkable Menu Items

Checkable Menu Items can be used to toggle a setting on and off.

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-checkable.ts[preimport,hidden]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuCheckable.java[render,tags=snippet1,indent=0]

...

include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuCheckable.java[render,tags=snippet2,indent=0]
----
--

== Hierarchical Menu

Context Menu, like Menu Bar, supports multi-level sub-menus.
You can use a hierarchical menu to organize a large set of options and group related items.

include::index.asciidoc[tag=example-instructions]

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-hierarchical.ts[preimport,hidden]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuHierarchical.java[render,tags=snippet,indent=0]
----
--

== Custom Items

You can customize the items to include more than a single line of text.

include::index.asciidoc[tag=example-instructions]

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-presentation.ts[preimport,hidden]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuPresentation.java[render,tags=snippet1,indent=0]
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuPresentation.java[render,tags=snippet2,indent=0]

...

include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuPresentation.java[render,tags=snippet3,indent=0]
----
--

== Disabled Menu Items

You can disable menu items to show that they are unavailable.

include::index.asciidoc[tag=example-instructions]

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-disabled.ts[preimport,hidden]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuDisabled.java[render,tags=snippet1,indent=0]

include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuDisabled.java[render,tags=snippet2,indent=0]

include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuDisabled.java[render,tags=snippet3,indent=0]
----
--

== Left-Click

You can use left-click to open Context Menu in situations where left-click does not have any other function, for example a Grid without selection support.

[IMPORTANT]
Open the Context Menu by clicking a Grid row.

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-left-click.ts[preimport,hidden]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuLeftClick.java[render,tags=snippet,indent=0]
----
--

== Best Practices

Context Menu is used to provide shortcuts to the user.
You should not use it as the only or primary means to complete a task.
The primary way should be accessible elsewhere in the UI.

[IMPORTANT]
Open the Context Menu by right-clicking (desktop) or long-pressing (mobile) a Grid row, or use the Menu Bar in the last column.

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-best-practices.ts[preimport,hidden]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuBestPractices.java[render,tags=snippet,indent=0]
----
--

=== Context Menu vs Menu Bar

You should use Context Menu when there is no dedicated button for opening an overlay menu, such as right-clicking a grid row.
When there is a dedicated element/component, such as an <<../menu-bar#,overflow menu>>, use Menu Bar.

=== Icons

Use icons when applicable to help improve recognition.
It is recommended to use commonly recognized icons to avoid confusion.
Use icons consistently throughout a list of options.

=== Labelling

Suffix a menu item with “...” when the associated action won't be executed, but instead reveal some UI, like a dialog, for completing the action.


== Related Components

|===
|Component |Usage recommendations

|<<../menu-bar#,Menu Bar>>
|Component for displaying a horizontal menu with multi-level sub-menus.

|===


[discussion-id]`2521898B-8802-40FC-BD68-1D5251EAB787`

