---
title: Design System Publisher
section-nav: commercial
---

= Design System Publisher

:commercial-feature: Design System Publisher
include::{articles}/flow/_commercial-banner.asciidoc[]

Design System Publisher is a tool for creating a documentation website for your own Vaadin-based design system. This is the components, theme features, UI patterns, and guidelines of which your application UIs are composed.

Having your own documentation website makes it easier for your developers and designers to keep track of features available in your UI platform, how they look, and how they can be used.

The site's content format is https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[AsciiDoc], a lightweight markup language similar to Markdown. The system supports embedding live component samples, written in Java or TypeScript, directly into the pages. The system can automatically provide code snippets for the samples for copy-pasting into code.

The default documentation content provided with the tool is a copy of the official <<{articles}/flow/components#, Vaadin Design System documentation>>. You can customize it to match your own UI features by plugging in your own <<custom-theme#,Custom Theme for Rendered UI Examples>>, and by <<editing#,adding, removing, and editing the documentation and component examples>>.

== Topics

section_outline::[]


[discussion-id]`14F4D321-696D-4C41-BC8F-E7EE373F949F`

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++