---
title: Tree Grid
page-title: Tree Grid component | Vaadin components
description: The Tree Grid component displays hierarchical tabular data grouped in expandable nodes.
meta-description: Display hierarchical data in your Vaadin applications with the Tree Grid component.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/grid}/elements/vaadin-grid-tree-column[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/treegrid/TreeGrid.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/grid}/packages/grid[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-grid-flow-parent[Java]'
---


= Tree Grid

// tag::description[]
Tree Grid is a component for displaying hierarchical tabular data grouped into expandable nodes.
// end::description[]

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/tree-grid/tree-grid-basic.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/treegrid/TreeGridBasic.java[render,tags=snippet,indent=0,group=Flow]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Person.java[group=Flow,tags=snippet]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/tree-grid/react/tree-grid-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

Tree Grid is an extension of the Grid component, so it inherits all of Grid's features, including:

* <<../grid#sorting,Sorting>>
* <<../grid#filtering,Filtering>>
* <<../grid/columns#,Columns>>
* <<../grid/selection#,Selection>>
* <<../grid/renderers#,Renderers>>
* and <<../grid#,more>>

However, Tree Grid isn't meant to be used as a navigation menu.

== Tree Column

The tree column contains the toggles for expanding and collapsing nodes. Nodes are opened and closed by clicking a tree column's cell. They can also be toggled programmatically.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/tree-grid/tree-grid-column.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/treegrid/TreeGridColumn.java[render,tags=snippet,indent=0,group=Flow]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Person.java[group=Flow,tags=snippet]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/tree-grid/react/tree-grid-column.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

== Rich Content

Like Grid, Tree Grid supports rich content.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/tree-grid/tree-grid-rich-content.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/treegrid/TreeGridRichContent.java[render,tags=snippet,indent=0,group=Flow]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Person.java[group=Flow,tags=snippet]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/tree-grid/react/tree-grid-rich-content.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

== Programmatic Scrolling

Tree Grid supports programmatic navigation to a specific item. This is particularly useful when dealing with large data sets. It saves users from having to scroll through potentially hundreds or thousands of rows.

[role="since:com.vaadin:vaadin@V25.0"]
=== Scrolling to Item (Flow only)
To use this feature, you need to specify the item you want to view. The scroll position of the grid is adjusted to bring that item into view.

If the item has collapsed parents, they expand before scrolling to the item.

[.example]
--
[source,typescript]
----
include::{root}/frontend/demo/component/tree-grid/tree-grid-imports.ts[preimport,hidden]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/treegrid/TreeGridScrollToItem.java[render,tags=snippet,indent=0]
----
--

`TreeDataProvider` supports this feature out of the box. For other data providers, you need to override and implement the following methods of [classname]`HierarchicalDataProvider`:

- [methodname]`getParent(T item)`
- [methodname]`getItemIndex(T item, HierarchicalQuery query)`

=== Scrolling to Item by Path

You can also scroll to an item by providing its hierarchical path – an array of indexes where each index refers to a child of the item at the previous index. For example, to scroll to the second child-row (index 1) of the third root-level row (index 2), you would provide the path 2, 1.
Scrolling continues until it reaches the last index in the array or encounters a collapsed item.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/tree-grid/tree-grid-scroll-to-index.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/treegrid/TreeGridScrollToIndex.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/tree-grid/react/tree-grid-scroll-to-index.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

== Drag & Drop

Tree Grid supports drag-and-drop operations. You can enable and handle them in your logic, for example, to allow users to move rows from one parent node to another:

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/tree-grid/tree-grid-drag-drop.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/treegrid/TreeGridDragDrop.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/tree-grid/react/tree-grid-drag-drop.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

For more drag-and-drop examples and API references, refer to the Grid's <<../grid/drag-drop#,Drag and Drop>> documentation.

== Related Components

[cols="1,2"]
|===
|Component |Usage Recommendation

|<<../grid#,Grid>>
|Component for showing tabular data.

|<<../grid-pro#,Grid Pro>>
|Component for showing and editing tabular data.

|<<../crud#,CRUD>>
|Component for creating, displaying, updating, and deleting tabular data.
|===


[discussion-id]`9DEF736F-975A-469A-8625-A0A6E086BF50`
