---
title: Color
order: 50
layout: page
---

= Lumo Color
ifdef::web[]
:toc: macro
:toc-title: Contents
:toclevels: 1
endif::web[]

Lumo defines a set of style modules and CSS custom properties you can use to apply a consistent color palette across your application.

ifdef::web[]
toc::[]
endif::web[]

// Needed to show embedded live previews
include::../themes-shared.asciidoc[opts=optional]


[NOTE]
====
The default color palette is not fully link:https://www.w3.org/TR/WCAG20/#visual-audio-contrast[WCAG 2.0] AA level compliant.

ifdef::web[]
Follow the https://github.com/vaadin/vaadin-lumo-styles/issues/22[issue on GitHub].
endif::web[]
====

== Base

The base color is used as the main background color for the system. The <<grayscale>> colors are designed to be used on top of it, and the <<text>> colors are designed to have sufficient contrast with it.

++++
<content-preview class="block" hidesource raw>
    <dl class="custom-properties color">
      <dt>--lumo-base-color: <span class="color-swatch" style="background-color: #FFF"></span><code>#FFF</code></dt>
    </dl>

    <h5>Primary</h5>
    <p>The most prominent color in the system. It is used to bring attention to certain elements in the interface. Accompanying text and contrast colors are also defined.</p>
    <dl class="custom-properties color">
      <dt>--lumo-primary-color-10pct: <span class="color-swatch" style="background-color: hsla(214, 90%, 52%, 0.1)"></span><code>hsla(214, 90%, 52%, 0.1)</code></dt>
      <dt>--lumo-primary-color-50pct: <span class="color-swatch" style="background-color: hsla(214, 90%, 52%, 0.5)"></span><code>hsla(214, 90%, 52%, 0.5)</code></dt>
      <dt>--lumo-primary-color: <span class="color-swatch" style="background-color: hsl(214, 90%, 52%)"></span><code>hsl(214, 90%, 52%)</code></dt>
      <dt>--lumo-primary-contrast-color: <span class="color-swatch" style="background-color: #FFF"></span><code>#FFF</code></dt>
    </dl>
</content-preview>
++++
== Grayscale
These colors form the foundation for your application colors. The grayscale colors consist of 11 different shades of “black” and “white”, each with a degree of transparency.

The tint and shade colors not always pure grayscale by default, but tinted slightly with the primary color.

The grayscale colors are useful for dividing pages into sections with different backgrounds and borders, or used as text colors, for example.

The default text colors are tested to have enough contrast on top of the <<base>> color and “Base + 5–20% Contrast color”. Avoid using a a higher Contrast color as a background color for any important content.

++++
<content-preview class="block" hidesource raw>

    <h5>Tint</h5>
    <dl class="custom-properties color">
      <dt>--lumo-tint-5pct: <span class="color-swatch" style="background-color: hsla(0, 0%, 100%, 0.3)"></span><code>hsla(0, 0%, 100%, 0.3)</code></dt>
      <dt>--lumo-tint-10pct: <span class="color-swatch" style="background-color: hsla(0, 0%, 100%, 0.37)"></span><code>hsla(0, 0%, 100%, 0.37)</code></dt>
      <dt>--lumo-tint-20pct: <span class="color-swatch" style="background-color: hsla(0, 0%, 100%, 0.44)"></span><code>hsla(0, 0%, 100%, 0.44)</code></dt>
      <dt>--lumo-tint-30pct: <span class="color-swatch" style="background-color: hsla(0, 0%, 100%, 0.5)"></span><code>hsla(0, 0%, 100%, 0.5)</code></dt>
      <dt>--lumo-tint-40pct: <span class="color-swatch" style="background-color: hsla(0, 0%, 100%, 0.57)"></span><code>hsla(0, 0%, 100%, 0.57)</code></dt>
      <dt>--lumo-tint-50pct: <span class="color-swatch" style="background-color: hsla(0, 0%, 100%, 0.64)"></span><code>hsla(0, 0%, 100%, 0.64)</code></dt>
      <dt>--lumo-tint-60pct: <span class="color-swatch" style="background-color: hsla(0, 0%, 100%, 0.7)"></span><code>hsla(0, 0%, 100%, 0.7)</code></dt>
      <dt>--lumo-tint-70pct: <span class="color-swatch" style="background-color: hsla(0, 0%, 100%, 0.77)"></span><code>hsla(0, 0%, 100%, 0.77)</code></dt>
      <dt>--lumo-tint-80pct: <span class="color-swatch" style="background-color: hsla(0, 0%, 100%, 0.84)"></span><code>hsla(0, 0%, 100%, 0.84)</code></dt>
      <dt>--lumo-tint-90pct: <span class="color-swatch" style="background-color: hsla(0, 0%, 100%, 0.9)"></span><code>hsla(0, 0%, 100%, 0.9)</code></dt>
      <dt>--lumo-tint: <span class="color-swatch" style="background-color: #FFF"></span><code>#FFF</code></dt>
    </dl>

    <h5>Shade</h5>
    <dl class="custom-properties color">
      <dt>--lumo-shade-5pct: <span class="color-swatch" style="background-color: hsla(214, 61%, 25%, 0.05)"></span><code>hsla(214, 61%, 25%, 0.05)</code></dt>
      <dt>--lumo-shade-10pct: <span class="color-swatch" style="background-color: hsla(214, 57%, 24%, 0.1)"></span><code>hsla(214, 57%, 24%, 0.1)</code></dt>
      <dt>--lumo-shade-20pct: <span class="color-swatch" style="background-color: hsla(214, 53%, 23%, 0.16)"></span><code>hsla(214, 53%, 23%, 0.16)</code></dt>
      <dt>--lumo-shade-30pct: <span class="color-swatch" style="background-color: hsla(214, 50%, 22%, 0.26)"></span><code>hsla(214, 50%, 22%, 0.26)</code></dt>
      <dt>--lumo-shade-40pct: <span class="color-swatch" style="background-color: hsla(214, 47%, 21%, 0.38)"></span><code>hsla(214, 47%, 21%, 0.38)</code></dt>
      <dt>--lumo-shade-50pct: <span class="color-swatch" style="background-color: hsla(214, 45%, 20%, 0.5)"></span><code>hsla(214, 45%, 20%, 0.5)</code></dt>
      <dt>--lumo-shade-60pct: <span class="color-swatch" style="background-color: hsla(214, 43%, 19%, 0.61)"></span><code>hsla(214, 43%, 19%, 0.61)</code></dt>
      <dt>--lumo-shade-70pct: <span class="color-swatch" style="background-color: hsla(214, 42%, 18%, 0.72)"></span><code>hsla(214, 42%, 18%, 0.72)</code></dt>
      <dt>--lumo-shade-80pct: <span class="color-swatch" style="background-color: hsla(214, 41%, 17%, 0.83)"></span><code>hsla(214, 41%, 17%, 0.83)</code></dt>
      <dt>--lumo-shade-90pct: <span class="color-swatch" style="background-color: hsla(214, 40%, 16%, 0.94)"></span><code>hsla(214, 40%, 16%, 0.94)</code></dt>
      <dt>--lumo-shade: <span class="color-swatch" style="background-color: hsl(214, 35%, 15%)"></span><code>hsl(214, 35%, 15%)</code></dt>
    </dl>

    <h5>Contrast</h5>
    <p>The contrast colors work automatically for both light and dark variations. For the light palette the shade colors are used, and for the dark palette the tint colors are used.</p>
    <dl class="custom-properties color">
      <dt>--lumo-contrast-5pct: <span class="color-swatch" style="background-color: hsla(214, 61%, 25%, 0.05)"></span><code>hsla(214, 61%, 25%, 0.05)</code></dt>
      <dt>--lumo-contrast-10pct: <span class="color-swatch" style="background-color: hsla(214, 57%, 24%, 0.1)"></span><code>hsla(214, 57%, 24%, 0.1)</code></dt>
      <dt>--lumo-contrast-20pct: <span class="color-swatch" style="background-color: hsla(214, 53%, 23%, 0.16)"></span><code>hsla(214, 53%, 23%, 0.16)</code></dt>
      <dt>--lumo-contrast-30pct: <span class="color-swatch" style="background-color: hsla(214, 50%, 22%, 0.26)"></span><code>hsla(214, 50%, 22%, 0.26)</code></dt>
      <dt>--lumo-contrast-40pct: <span class="color-swatch" style="background-color: hsla(214, 47%, 21%, 0.38)"></span><code>hsla(214, 47%, 21%, 0.38)</code></dt>
      <dt>--lumo-contrast-50pct: <span class="color-swatch" style="background-color: hsla(214, 45%, 20%, 0.5)"></span><code>hsla(214, 45%, 20%, 0.5)</code></dt>
      <dt>--lumo-contrast-60pct: <span class="color-swatch" style="background-color: hsla(214, 43%, 19%, 0.61)"></span><code>hsla(214, 43%, 19%, 0.61)</code></dt>
      <dt>--lumo-contrast-70pct: <span class="color-swatch" style="background-color: hsla(214, 42%, 18%, 0.72)"></span><code>hsla(214, 42%, 18%, 0.72)</code></dt>
      <dt>--lumo-contrast-80pct: <span class="color-swatch" style="background-color: hsla(214, 41%, 17%, 0.83)"></span><code>hsla(214, 41%, 17%, 0.83)</code></dt>
      <dt>--lumo-contrast-90pct: <span class="color-swatch" style="background-color: hsla(214, 40%, 16%, 0.94)"></span><code>hsla(214, 40%, 16%, 0.94)</code></dt>
      <dt>--lumo-contrast: <span class="color-swatch" style="background-color: hsl(214, 35%, 15%)"></span><code>hsl(214, 35%, 15%)</code></dt>
    </dl>
</content-preview>
++++
== Error

Usually a red color, used for error indicators, error messages and buttons that can cause permanent data loss. Accompanying text and contrast colors are also defined.

++++
<content-preview class="block" hidesource raw>
    <dl class="custom-properties color">
      <dt>--lumo-error-color-10pct: <span class="color-swatch" style="background-color: hsla(3, 100%, 60%, 0.1)"></span><code>hsla(3, 100%, 60%, 0.1)</code></dt>
      <dt>--lumo-error-color-50pct: <span class="color-swatch" style="background-color: hsla(3, 100%, 60%, 0.5)"></span><code>hsla(3, 100%, 60%, 0.5)</code></dt>
      <dt>--lumo-error-color: <span class="color-swatch" style="background-color: hsl(3, 100%, 61%)"></span><code>hsl(3, 100%, 61%)</code></dt>
      <dt>--lumo-error-contrast-color: <span class="color-swatch" style="background-color: #FFF"></span><code>#FFF</code></dt>
    </dl>
</content-preview>
++++
== Success

Usually a green color, used for success messages and buttons that complete a certain task. Accompanying text and contrast colors are also defined.

++++
<content-preview class="block" hidesource raw>
    <dl class="custom-properties color">
      <dt>--lumo-success-color-10pct: <span class="color-swatch" style="background-color: hsla(145, 76%, 44%, 0.12)"></span><code>hsla(145, 76%, 44%, 0.12)</code></dt>
      <dt>--lumo-success-color-50pct: <span class="color-swatch" style="background-color: hsla(145, 76%, 44%, 0.55)"></span><code>hsla(145, 76%, 44%, 0.55)</code></dt>
      <dt>--lumo-success-color: <span class="color-swatch" style="background-color: hsl(145, 80%, 42%)"></span><code>hsl(145, 80%, 42%)</code></dt>
      <dt>--lumo-success-contrast-color: <span class="color-swatch" style="background-color: #FFF"></span><code>#FFF</code></dt>
    </dl>
</content-preview>
++++

== Text

The following text colors have the desired contrast with the <<base>> color.

Note, that `--lumo-primary-text-color` is not necessarily the same as `--lumo-primary-color`. Use the main color for backgrounds and the “text” version for text. The same applies for the <<error>> and <<success>> colors as well.


.Accessibility
[NOTE]
The “tertiary” and “disabled” text colors do not have enough contrast to meet WCAG 2.0 AA level requirements (4.5:1). Only use them for text which is not crucial for the end user to see.

++++
<content-preview class="block" hidesource raw>
    <dl class="custom-properties color">
      <dt>--lumo-header-text-color: <span class="color-swatch" style="background-color: hsl(214, 35%, 15%)"></span><code>hsl(214, 35%, 15%)</code></dt>
      <dt>--lumo-body-text-color: <span class="color-swatch" style="background-color: hsla(214, 40%, 16%, 0.94)"></span><code>hsla(214, 40%, 16%, 0.94)</code></dt>
      <dt>--lumo-secondary-text-color: <span class="color-swatch" style="background-color: hsla(214, 42%, 18%, 0.72)"></span><code>hsla(214, 42%, 18%, 0.72)</code></dt>
      <dt>--lumo-tertiary-text-color: <span class="color-swatch" style="background-color: hsla(214, 45%, 20%, 0.5)"></span><code>hsla(214, 45%, 20%, 0.5)</code></dt>
      <dt>--lumo-disabled-text-color: <span class="color-swatch" style="background-color: hsla(214, 50%, 22%, 0.26)"></span><code>hsla(214, 50%, 22%, 0.26)</code></dt>
      <dt>--lumo-primary-text-color: <span class="color-swatch" style="background-color: hsl(214, 90%, 52%)"></span><code>hsl(214, 90%, 52%)</code></dt>
      <dt>--lumo-error-text-color: <span class="color-swatch" style="background-color: hsl(3, 92%, 53%)"></span><code>hsl(3, 92%, 53%)</code></dt>
      <dt>--lumo-success-text-color: <span class="color-swatch" style="background-color: hsl(145, 100%, 32%)"></span><code>hsl(145, 100%, 32%)</code></dt>
      <dt>--lumo-link-color: <code>var(--lumo-primary-text-color)</code></dt>
    </dl>
  </content-preview>
++++
== Dark palette

The custom properties are the same, but their values are different when using the dark palette.

++++
    <details>
    <summary>Show dark palette values</summary>

  <content-preview class="block" hidesource raw>
    <div theme="dark" style="margin: 0 -1em; padding: 0 1em;">

      <h5>Base color</h5>
      <dl class="custom-properties color">
        <dt>--lumo-base-color: <span class="color-swatch" style="background-color: hsl(214, 35%, 21%)"></span><code>hsl(214, 35%, 21%)</code></dt>
      </dl>

      <h5>Primary</h5>
      <dl class="custom-properties color">
        <dt>--lumo-primary-color-10pct: <span class="color-swatch" style="background-color: hsla(214, 90%, 63%, 0.1)"></span><code>hsla(214, 90%, 63%, 0.1)</code></dt>
        <dt>--lumo-primary-color-50pct: <span class="color-swatch" style="background-color: hsla(214, 86%, 55%, 0.5)"></span><code>hsla(214, 86%, 55%, 0.5)</code></dt>
        <dt>--lumo-primary-color: <span class="color-swatch" style="background-color: hsl(214, 86%, 55%)"></span><code>hsl(214, 86%, 55%)</code></dt>
        <dt>--lumo-primary-contrast-color: <span class="color-swatch" style="background-color: #FFF"></span><code>#FFF</code></dt>
      </dl>

      <h5>Tint</h5>
      <dl class="custom-properties color">
        <dt>--lumo-tint-5pct: <span class="color-swatch" style="background-color: hsla(214, 65%, 85%, 0.06)"></span><code>hsla(214, 65%, 85%, 0.06)</code></dt>
        <dt>--lumo-tint-10pct: <span class="color-swatch" style="background-color: hsla(214, 60%, 80%, 0.14)"></span><code>hsla(214, 60%, 80%, 0.14)</code></dt>
        <dt>--lumo-tint-20pct: <span class="color-swatch" style="background-color: hsla(214, 64%, 82%, 0.23)"></span><code>hsla(214, 64%, 82%, 0.23)</code></dt>
        <dt>--lumo-tint-30pct: <span class="color-swatch" style="background-color: hsla(214, 69%, 84%, 0.32)"></span><code>hsla(214, 69%, 84%, 0.32)</code></dt>
        <dt>--lumo-tint-40pct: <span class="color-swatch" style="background-color: hsla(214, 73%, 86%, 0.41)"></span><code>hsla(214, 73%, 86%, 0.41)</code></dt>
        <dt>--lumo-tint-50pct: <span class="color-swatch" style="background-color: hsla(214, 78%, 88%, 0.5)"></span><code>hsla(214, 78%, 88%, 0.5)</code></dt>
        <dt>--lumo-tint-60pct: <span class="color-swatch" style="background-color: hsla(214, 82%, 90%, 0.6)"></span><code>hsla(214, 82%, 90%, 0.6)</code></dt>
        <dt>--lumo-tint-70pct: <span class="color-swatch" style="background-color: hsla(214, 87%, 92%, 0.7)"></span><code>hsla(214, 87%, 92%, 0.7)</code></dt>
        <dt>--lumo-tint-80pct: <span class="color-swatch" style="background-color: hsla(214, 91%, 94%, 0.8)"></span><code>hsla(214, 91%, 94%, 0.8)</code></dt>
        <dt>--lumo-tint-90pct: <span class="color-swatch" style="background-color: hsla(214, 96%, 96%, 0.9)"></span><code>hsla(214, 96%, 96%, 0.9)</code></dt>
        <dt>--lumo-tint: <span class="color-swatch" style="background-color: hsl(214, 100%, 98%)"></span><code>hsl(214, 100%, 98%)</code></dt>
      </dl>

      <h5>Shade</h5>
      <dl class="custom-properties color">
        <dt>--lumo-shade-5pct: <span class="color-swatch" style="background-color: hsla(214, 0%, 0%, 0.07)"></span><code>hsla(214, 0%, 0%, 0.07)</code></dt>
        <dt>--lumo-shade-10pct: <span class="color-swatch" style="background-color: hsla(214, 4%, 2%, 0.15)"></span><code>hsla(214, 4%, 2%, 0.15)</code></dt>
        <dt>--lumo-shade-20pct: <span class="color-swatch" style="background-color: hsla(214, 8%, 4%, 0.23)"></span><code>hsla(214, 8%, 4%, 0.23)</code></dt>
        <dt>--lumo-shade-30pct: <span class="color-swatch" style="background-color: hsla(214, 12%, 6%, 0.32)"></span><code>hsla(214, 12%, 6%, 0.32)</code></dt>
        <dt>--lumo-shade-40pct: <span class="color-swatch" style="background-color: hsla(214, 16%, 8%, 0.41)"></span><code>hsla(214, 16%, 8%, 0.41)</code></dt>
        <dt>--lumo-shade-50pct: <span class="color-swatch" style="background-color: hsla(214, 20%, 10%, 0.5)"></span><code>hsla(214, 20%, 10%, 0.5)</code></dt>
        <dt>--lumo-shade-60pct: <span class="color-swatch" style="background-color: hsla(214, 24%, 12%, 0.6)"></span><code>hsla(214, 24%, 12%, 0.6)</code></dt>
        <dt>--lumo-shade-70pct: <span class="color-swatch" style="background-color: hsla(214, 28%, 13%, 0.7)"></span><code>hsla(214, 28%, 13%, 0.7)</code></dt>
        <dt>--lumo-shade-80pct: <span class="color-swatch" style="background-color: hsla(214, 32%, 13%, 0.8)"></span><code>hsla(214, 32%, 13%, 0.8)</code></dt>
        <dt>--lumo-shade-90pct: <span class="color-swatch" style="background-color: hsla(214, 33%, 13%, 0.9)"></span><code>hsla(214, 33%, 13%, 0.9)</code></dt>
        <dt>--lumo-shade: <span class="color-swatch" style="background-color: hsl(214, 33%, 13%)"></span><code>hsl(214, 33%, 13%)</code></dt>
      </dl>

      <h5>Contrast</h5>
      <dl class="custom-properties color">
        <dt>--lumo-contrast-5pct: <span class="color-swatch" style="background-color: hsla(214, 65%, 85%, 0.06)"></span><code>hsla(214, 65%, 85%, 0.06)</code></dt>
        <dt>--lumo-contrast-10pct: <span class="color-swatch" style="background-color: hsla(214, 60%, 80%, 0.14)"></span><code>hsla(214, 60%, 80%, 0.14)</code></dt>
        <dt>--lumo-contrast-20pct: <span class="color-swatch" style="background-color: hsla(214, 64%, 82%, 0.23)"></span><code>hsla(214, 64%, 82%, 0.23)</code></dt>
        <dt>--lumo-contrast-30pct: <span class="color-swatch" style="background-color: hsla(214, 69%, 84%, 0.32)"></span><code>hsla(214, 69%, 84%, 0.32)</code></dt>
        <dt>--lumo-contrast-40pct: <span class="color-swatch" style="background-color: hsla(214, 73%, 86%, 0.41)"></span><code>hsla(214, 73%, 86%, 0.41)</code></dt>
        <dt>--lumo-contrast-50pct: <span class="color-swatch" style="background-color: hsla(214, 78%, 88%, 0.5)"></span><code>hsla(214, 78%, 88%, 0.5)</code></dt>
        <dt>--lumo-contrast-60pct: <span class="color-swatch" style="background-color: hsla(214, 82%, 90%, 0.6)"></span><code>hsla(214, 82%, 90%, 0.6)</code></dt>
        <dt>--lumo-contrast-70pct: <span class="color-swatch" style="background-color: hsla(214, 87%, 92%, 0.7)"></span><code>hsla(214, 87%, 92%, 0.7)</code></dt>
        <dt>--lumo-contrast-80pct: <span class="color-swatch" style="background-color: hsla(214, 91%, 94%, 0.8)"></span><code>hsla(214, 91%, 94%, 0.8)</code></dt>
        <dt>--lumo-contrast-90pct: <span class="color-swatch" style="background-color: hsla(214, 96%, 96%, 0.9)"></span><code>hsla(214, 96%, 96%, 0.9)</code></dt>
        <dt>--lumo-contrast: <span class="color-swatch" style="background-color: hsl(214, 100%, 98%)"></span><code>hsl(214, 100%, 98%)</code></dt>
      </dl>

      <h5>Error</h5>
      <dl class="custom-properties color">
        <dt>--lumo-error-color-10pct: <span class="color-swatch" style="background-color: hsla(3, 90%, 63%, 0.1)"></span><code>hsla(3, 90%, 63%, 0.1)</code></dt>
        <dt>--lumo-error-color-50pct: <span class="color-swatch" style="background-color: hsla(3, 90%, 63%, 0.5)"></span><code>hsla(3, 90%, 63%, 0.5)</code></dt>
        <dt>--lumo-error-color: <span class="color-swatch" style="background-color: hsl(3, 90%, 63%)"></span><code>hsl(3, 90%, 63%)</code></dt>
        <dt>--lumo-error-contrast-color: <span class="color-swatch" style="background-color: #FFF"></span><code>#FFF</code></dt>
      </dl>

      <h5>Success</h5>
      <dl class="custom-properties color">
        <dt>--lumo-success-color-10pct: <span class="color-swatch" style="background-color: hsla(145, 65%, 42%, 0.1)"></span><code>hsla(145, 65%, 42%, 0.1)</code></dt>
        <dt>--lumo-success-color-50pct: <span class="color-swatch" style="background-color: hsla(145, 65%, 42%, 0.5)"></span><code>hsla(145, 65%, 42%, 0.5)</code></dt>
        <dt>--lumo-success-color: <span class="color-swatch" style="background-color: hsl(145, 65%, 42%)"></span><code>hsl(145, 65%, 42%)</code></dt>
        <dt>--lumo-success-contrast-color: <span class="color-swatch" style="background-color: #FFF"></span><code>#FFF</code></dt>
      </dl>

      <h5>Text</h5>
      <dl class="custom-properties color">
        <dt>--lumo-header-text-color: <span class="color-swatch" style="background-color: hsl(214, 100%, 98%)"></span><code>hsl(214, 100%, 98%)</code></dt>
        <dt>--lumo-body-text-color: <span class="color-swatch" style="background-color: hsla(214, 96%, 96%, 0.9)"></span><code>hsla(214, 96%, 96%, 0.9)</code></dt>
        <dt>--lumo-secondary-text-color: <span class="color-swatch" style="background-color: hsla(214, 87%, 92%, 0.7)"></span><code>hsla(214, 87%, 92%, 0.7)</code></dt>
        <dt>--lumo-tertiary-text-color: <span class="color-swatch" style="background-color: hsla(214, 78%, 88%, 0.5)"></span><code>hsla(214, 78%, 88%, 0.5)</code></dt>
        <dt>--lumo-disabled-text-color: <span class="color-swatch" style="background-color: hsla(214, 69%, 84%, 0.32)"></span><code>hsla(214, 69%, 84%, 0.32)</code></dt>
        <dt>--lumo-primary-text-color: <span class="color-swatch" style="background-color: hsl(214, 100%, 70%)"></span><code>hsl(214, 100%, 70%)</code></dt>
        <dt>--lumo-error-text-color: <span class="color-swatch" style="background-color: hsl(3, 100%, 67%)"></span><code>hsl(3, 100%, 67%)</code></dt>
        <dt>--lumo-success-text-color: <span class="color-swatch" style="background-color: hsl(145, 85%, 47%)"></span><code>hsl(145, 85%, 47%)</code></dt>
        <dt>--lumo-link-color: <code>var(--lumo-primary-text-color)</code></dt>
      </dl>

    </div>
  </content-preview>
  </detail>
++++


== Examples
=== Base
++++
<content-preview class="background-shade">
++++
[source,html]
----
<span class="base">Base color</span>

<custom-style>
  <style>
    .base {
      background-color: var(--lumo-base-color);
      color: var(--lumo-secondary-text-color);
    }
  </style>
</custom-style>
----
++++
</content-preview>

++++
=== Primary
++++
<content-preview>
++++
[source,html]
----
<span class="primary-10pct">10%</span>
<span class="primary-50pct">50%</span>
<span class="primary">100%</span>

<custom-style>
  <style>
    .primary-10pct {
      background-color: var(--lumo-primary-color-10pct);
      color: var(--lumo-primary-text-color);
    }
    .primary-50pct {
      background-color: var(--lumo-primary-color-50pct);
      color: var(--lumo-primary-contrast-color);
    }
    .primary {
      background-color: var(--lumo-primary-color);
      color: var(--lumo-primary-contrast-color);
    }
  </style>
</custom-style>
----
++++
</content-preview>

++++
=== Error
++++
<content-preview>
++++
[source,html]
----
<span class="error-10pct">10%</span>
<span class="error-50pct">50%</span>
<span class="error">100%</span>

<custom-style>
  <style>
    .error-10pct {
      background-color: var(--lumo-error-color-10pct);
      color: var(--lumo-error-text-color);
    }
    .error-50pct {
      background-color: var(--lumo-error-color-50pct);
      color: var(--lumo-error-contrast-color);
    }
    .error {
      background-color: var(--lumo-error-color);
      color: var(--lumo-error-contrast-color);
    }
  </style>
</custom-style>
----
++++
</content-preview>

++++
=== Success
++++
<content-preview>
++++
[source,html]
----
<span class="success-10pct">10%</span>
<span class="success-50pct">50%</span>
<span class="success">100%</span>

<custom-style>
  <style>
    .success-10pct {
      background-color: var(--lumo-success-color-10pct);
      color: var(--lumo-success-text-color);
    }
    .success-50pct {
      background-color: var(--lumo-success-color-50pct);
      color: var(--lumo-success-contrast-color);
    }
    .success {
      background-color: var(--lumo-success-color);
      color: var(--lumo-success-contrast-color);
    }
  </style>
</custom-style>
----
++++
</content-preview>

++++
=== Grayscale
++++
    <h4 id="tint">Tint</h4>

<content-preview class="background-shade">
++++
[source,html]
----
<span class="white-5pct">5%</span>
<span class="white-10pct">10%</span>
<span class="white-20pct">20%</span>
<span class="white-30pct">30%</span>
<span class="white-40pct">40%</span>
<span class="white-50pct">50%</span>
<span class="white-60pct">60%</span>
<span class="white-70pct">70%</span>
<span class="white-80pct">80%</span>
<span class="white-90pct">90%</span>
<span class="white">100%</span>

<custom-style>
  <style>
    .white-5pct {
      background-color: var(--lumo-tint-5pct);
    }
    .white-10pct {
      background-color: var(--lumo-tint-10pct);
    }
    .white-20pct {
      background-color: var(--lumo-tint-20pct);
    }
    .white-30pct {
      background-color: var(--lumo-tint-30pct);
    }
    .white-40pct {
      background-color: var(--lumo-tint-40pct);
    }
    .white-50pct {
      background-color: var(--lumo-tint-50pct);
    }
    .white-60pct {
      background-color: var(--lumo-tint-60pct);
      color: var(--lumo-shade-90pct);
    }
    .white-70pct {
      background-color: var(--lumo-tint-70pct);
      color: var(--lumo-shade-90pct);
    }
    .white-80pct {
      background-color: var(--lumo-tint-80pct);
      color: var(--lumo-shade-90pct);
    }
    .white-90pct {
      background-color: var(--lumo-tint-90pct);
      color: var(--lumo-shade-90pct);
    }
    .white {
      background-color: var(--lumo-tint);
      color: var(--lumo-shade-90pct);
    }
  </style>
</custom-style>
----
++++
</content-preview>

    <h4 id="shade">Shade</h4>

<content-preview>
++++
[source,html]
----
<span class="black-5pct">5%</span>
<span class="black-10pct">10%</span>
<span class="black-20pct">20%</span>
<span class="black-30pct">30%</span>
<span class="black-40pct">40%</span>
<span class="black-50pct">50%</span>
<span class="black-60pct">60%</span>
<span class="black-70pct">70%</span>
<span class="black-80pct">80%</span>
<span class="black-90pct">90%</span>
<span class="black">100%</span>

<custom-style>
  <style>
    .black-5pct {
      background-color: var(--lumo-shade-5pct);
    }
    .black-10pct {
      background-color: var(--lumo-shade-10pct);
    }
    .black-20pct {
      background-color: var(--lumo-shade-20pct);
    }
    .black-30pct {
      background-color: var(--lumo-shade-30pct);
    }
    .black-40pct {
      background-color: var(--lumo-shade-40pct);
    }
    .black-50pct {
      background-color: var(--lumo-shade-50pct);
      color: var(--lumo-tint-90pct);
    }
    .black-60pct {
      background-color: var(--lumo-shade-60pct);
      color: var(--lumo-tint-90pct);
    }
    .black-70pct {
      background-color: var(--lumo-shade-70pct);
      color: var(--lumo-tint-90pct);
    }
    .black-80pct {
      background-color: var(--lumo-shade-80pct);
      color: var(--lumo-tint-90pct);
    }
    .black-90pct {
      background-color: var(--lumo-shade-90pct);
      color: var(--lumo-tint-90pct);
    }
    .black {
      background-color: var(--lumo-shade);
      color: var(--lumo-tint-90pct);
    }
  </style>
</custom-style>
----
++++
</content-preview>

    <h4>Contrast</h4>


<content-preview>
++++
[source,html]
----
<span class="contrast-5pct">5%</span>
<span class="contrast-10pct">10%</span>
<span class="contrast-20pct">20%</span>
<span class="contrast-30pct">30%</span>
<span class="contrast-40pct">40%</span>
<span class="contrast-50pct">50%</span>
<span class="contrast-60pct">60%</span>
<span class="contrast-70pct">70%</span>
<span class="contrast-80pct">80%</span>
<span class="contrast-90pct">90%</span>
<span class="contrast">100%</span>

<custom-style>
  <style>
    .contrast-5pct {
      background-color: var(--lumo-contrast-5pct);
    }
    .contrast-10pct {
      background-color: var(--lumo-contrast-10pct);
    }
    .contrast-20pct {
      background-color: var(--lumo-contrast-20pct);
    }
    .contrast-30pct {
      background-color: var(--lumo-contrast-30pct);
    }
    .contrast-40pct {
      background-color: var(--lumo-contrast-40pct);
    }
    .contrast-50pct {
      background-color: var(--lumo-contrast-50pct);
    }
    .contrast-60pct {
      background-color: var(--lumo-contrast-60pct);
      color: var(--lumo-base-color);
    }
    .contrast-70pct {
      background-color: var(--lumo-contrast-70pct);
      color: var(--lumo-base-color);
    }
    .contrast-80pct {
      background-color: var(--lumo-contrast-80pct);
      color: var(--lumo-base-color);
    }
    .contrast-90pct {
      background-color: var(--lumo-contrast-90pct);
      color: var(--lumo-base-color);
    }
    .contrast {
      background-color: var(--lumo-contrast);
      color: var(--lumo-base-color);
    }
  </style>
</custom-style>
----
++++
</content-preview>

++++
=== Text
++++
<content-preview>
++++
[source,html]
----
<div>
  <div class="header-text">Header text</div>
  <div class="body-text">Normal text</div>
  <div class="secondary-text">Secondary text</div>
  <div class="tertiary-text">Tertiary text</div>
  <div class="disabled-text">Disabled text</div>
  <div class="primary-text">Primary text</div>
  <div class="error-text">Error text</div>
  <div class="success-text">Success text</div>
</div>

<custom-style>
  <style>
    .header-text {
      color: var(--lumo-header-text-color);
    }
    .body-text {
      color: var(--lumo-body-text-color);
    }
    .secondary-text {
      color: var(--lumo-secondary-text-color);
    }
    .tertiary-text {
      color: var(--lumo-tertiary-text-color);
    }
    .disabled-text {
      color: var(--lumo-disabled-text-color);
    }
    .primary-text {
      color: var(--lumo-primary-text-color);
    }
    .error-text {
      color: var(--lumo-error-text-color);
    }
    .success-text {
      color: var(--lumo-success-text-color);
    }
  </style>
</custom-style>
----
++++
</content-preview>


++++
