---
title: Styling
page-title: How to style Hilla applications with Lit | Vaadin
description: How to add CSS styles to views and Lit components in Hilla applications.
meta-description: Learn how to add CSS styles to views and Lit components in Hilla applications.
order: 80
---
// tag::content[]

// TODO this page could benefit from some more thought

ifdef::hilla-lit[]
= Styling Views & Layouts with CSS

== CSS Theme Folder

You can style components that extend [classname]`View` and [classname]`Layout` by placing CSS files in the `frontend/themes/<app-name>/` folder and importing them in [filename]`styles.css` using [methodname]`import()`.
Styles defined in the theme directory are available across the application.
You can also import styles from `node_modules`, like `line-awesome` in the following example:

.`frontend/themes/<app-name>/styles.css`
[source,css]
----
@import "line-awesome/dist/line-awesome/css/line-awesome.min.css";

@import "./main-layout.css";
@import "./views/example-view.css";
----
endif::hilla-lit[]

ifdef::hilla-react[]

== Styling Components with CSS

You can import CSS files directly, either plain files or CSS modules, with the [methodname]`import()` method. You can place the files anywhere in your application. The sample below has them in `views` folder for simplicity.

.`frontend/views/HelloWorld.tsx`
[source,tsx]
----
import './HelloWorld.css';
import css from './HelloWorld.module.css';
----
endif::hilla-react[]

== Using CSS Variables

Hilla apps typically use either the <<{articles}/styling/themes#,Lumo or Aura theme>> as a base for component and application styling.
Both themes are based on a set of CSS custom properties that you can use to achieve a consistent look and feel across applications.

You can use these properties in place of hard-coded units using `var()`.

[source,css]
----
.card {
  border: 1px solid var(--lumo-contrast-30pct);
  border-radius: var(--lumo-border-radius-s);
  box-shadow: var(--lumo-box-shadow-s);
}
----

// end::content[]
