---
tab-title: Usage
layout: tabbed-page
title: App Layout
page-title: App Layout component | Vaadin components
description: App Layout is a component for building common application layouts.
meta-description: Create responsive application layouts with the App Layout component in Vaadin.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/app-layout}/elements/vaadin-app-layout[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/applayout/AppLayout.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/app-layout}/packages/app-layout[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-app-layout-flow-parent[Java]'
---


= App Layout

// tag::description[]
App Layout is a component for the root layout of a Vaadin application. It provides predefined areas for the navigation drawer, the header, and the view's content.
// end::description[]

include::{articles}/components/_shared.adoc[tag=scaled-examples]
include::{articles}/components/_shared.adoc[tag=scaled-examples-responsive]

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/app-layout/app-layout-basic.ts[render,frame,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/applayout/AppLayoutBasic.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/app-layout/react/app-layout-basic.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]
--

The layout consists of three sections:

- <<#content-area,Content area>>, a view content area;
- <<#navbar,Navbar>>, a horizontal navigation bar; and
- <<#drawer,Drawer>>, a collapsible navigation drawer-

An application's main navigation blocks should be positioned in the `navbar` or the `drawer` or both, whereas views are rendered in the content area. App Layout is responsive and adjusts automatically to fit desktop, tablet, and mobile screen sizes.


== Usage as Root Layout

App Layout is designed to be the application's root layout, within which most or all views are rendered. It's not intended to be nested inside other elements.


=== Flow

With Flow, the root layout can be defined using the <<{articles}/flow/routing/layout#automatic-layout-using-layout,`@Layout` annotation>>, [since:com.vaadin:vaadin@V24.5]#which tells the router to render all routes or views inside of it#.

[source,java]
----
@Layout
public class MainLayout extends AppLayout {

}
----


=== Hilla

Files named [filename]`@layout.tsx` define the root layout for the other views defined in the same directory or its subdirectories. A [filename]`@layout.tsx` in the root of the `views` directory acts as the default root layout for all views in the application. An `<Outlet/>` element is used to tell the router where to render the contents of routes or views.

.@layout.tsx
[source,tsx]
----
export default function MainLayout() {
  return (
    <AppLayout>
      <Outlet />
    </AppLayout>
  );
}
----

See <<{articles}/hilla/guides/routing#adding-layout-routes,Hilla routing documentation>> for details.


== Content Area

The content area is where individual views are rendered. The <<#usage-as-root-layout,route layout mechanisms in Flow and Hilla>> can automatically render the contents of routes and views there, but it can be invoked manually:

[.example.show-code]
--

[source,java]
----
<source-info group="Flow"></source-info>
public class MainLayout extends AppLayout {
  public MainLayout() {
    MyView view = new MyView();
    setContent(view);
  }
}
----

[source,tsx]
----
<source-info group="React"></source-info>
<AppLayout>
  <MyView/>
</AppLayout>
----

[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-app-layout>
  <my-view></my-view>
</vaadin-app-layout>
----

--


== Navbar

The `navbar` is a header above the content area. It can contain primary or secondary navigation elements, the application's title, or view-specific content such as the title of the current view.

[.example.show-code]
--

[source,java]
----
<source-info group="Flow"></source-info>
@Layout
public class MainLayout extends AppLayout {
  public MainLayout() {
    H1 title = new H1("My App");
    addToNavbar(title);
  }
}
----

[source,tsx]
----
<source-info group="React"></source-info>
<AppLayout>
  <h1 slot="navbar">
    My App
  </h1>
</AppLayout>
----

[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-app-layout>
  <h1 slot="navbar">My App</h1>
</vaadin-app-layout>
----

--


=== Navbar Placement

The `navbar` can be located on top, or to the side of the `drawer`. When put it on top, the `navbar` is typically used as an application header. Application headers contain, for example, the application's name and branding, as well as actions that apply to the entire application (e.g., notifications, settings, etc.).

[.example.desktop]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/app-layout/app-layout-navbar-placement.ts[render,frame,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/applayout/AppLayoutNavbarPlacement.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/app-layout/react/app-layout-navbar-placement.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]
--

When placed to the side, the `navbar` is often seen as a view header, containing the view's title, as well as actions and secondary navigation that relate only to the current view.

[.example.desktop]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/app-layout/app-layout-navbar-placement-side.ts[render,frame,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/applayout/AppLayoutNavbarPlacementSide.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/app-layout/react/app-layout-navbar-placement-side.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Drawer

The `drawer` can switch between a fixed area next to the view's content and an expandable panel, toggled via the <<#drawer-toggle,drawer toggle>>. It typically contains the application's primary navigation, such as a <<../side-nav#,Side Navigation>> component.

[.example.show-code]
--

[source,java]
----
<source-info group="Flow"></source-info>
@Layout
public class MainLayout extends AppLayout {
  public MainLayout() {
    SideNav nav = new SideNav();
    addToDrawer(nav);
  }
}
----

[source,tsx]
----
<source-info group="React"></source-info>
<AppLayout>
  <SideNav slot="drawer">
    ...
  </SideNav>
</AppLayout>
----

[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-app-layout>
  <vaadin-side-nav slot="drawer">
    ...
  </vaadin-side-nav>
</vaadin-app-layout>
----

--


=== Drawer Toggle

Show and hide the `drawer` using a Drawer Toggle or a Button. The Drawer Toggle, which is represented by the hamburger icon (i.e., ☰), should always be accessible -- unless the `drawer` is empty. It's usually situated in the `navbar`.


== Scrolling Behavior

Depending on whether App Layout has a defined height, the way the content inside the layout scrolls can differ.


=== Auto Height

When the App Layout has an undefined or auto height set, which is the default, the `<body>` element is the scrolling container for the content inside the layout.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/app-layout/app-layout-height-auto.ts[render,frame,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/applayout/AppLayoutHeightAuto.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/app-layout/react/app-layout-height-auto.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]
--

The vertical scrollbar crosses the App Layout `navbar` and the content flows under it, allowing for translucent visual styles. Mobile browsers collapse and expand their toolbars when the user scrolls down and up, respectively. On iOS, you can tap the status bar (i.e., where signal strength, battery, and clock are indicated) to scroll back to the top of the page or view.

This behavior isn't compatible with vertically scrollable Grids, or other scrolling containers within the content area that's height is 100%. To support those, define 100% height for the App Layout.


=== Full Height (100%)

To allow a nested component to take all of the available vertical space inside the App Layout, you need to set an explicit height for the layout, typically 100%. A common use case is to let a data grid fill the entire content area.

[NOTE]
Make sure all parent components and elements have 100% height. The full hierarchy of components from the App Layout to the `<body>` element need to have 100% height.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/app-layout/app-layout-height-full.ts[render,frame,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/applayout/AppLayoutHeightFull.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/app-layout/react/app-layout-height-full.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]
--

The vertical scrollbar stays within the layout content area, and mobile browsers don't collapse their toolbars when the content area is scrolled down.


== Bottom Navbar on Small Touchscreens

When the `navbar` is used for navigation, the _touch-optimized_ `navbar` slot can be used to provide a separate version of the navigation at the bottom of the UI, optimized for mobile phones.

[.example.mobile]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/app-layout/app-layout-bottom-navbar.ts[render,frame,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/applayout/AppLayoutBottomNavbar.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/app-layout/react/app-layout-bottom-navbar.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Best Practices

=== Navbar vs Drawer

Choose between `navbar` and `drawer` based primarily on the number of items placed in it. The `navbar` is a good choice for a small number of items (i.e., three to five), as they can fit into the viewport without scrolling.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/app-layout/app-layout-navbar.ts[render,frame,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/applayout/AppLayoutNavbar.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/app-layout/react/app-layout-navbar.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]
--

When more items need to be displayed, or if small-screen support is a priority, the `drawer` is a better choice. It can accommodate a longer list of links without scrolling, and collapses into a hamburger menu on small screens. Furthermore, a vertical list of items is easier for the user to scan.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/app-layout/app-layout-drawer.ts[render,frame,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/applayout/AppLayoutDrawer.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/app-layout/react/app-layout-drawer.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]
--

For applications that require multilevel or hierarchical navigation, use the `drawer` to contain at least the first level. The secondary and tertiary navigation items can be placed in either the `drawer` or the `navbar`.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/app-layout/app-layout-secondary-navigation.ts[render,frame,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/applayout/AppLayoutSecondaryNavigation.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/app-layout/react/app-layout-secondary-navigation.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]
--


[discussion-id]`3005EA19-8E28-4BF2-8A0A-FC3F46C04F1B`
