---
title: Markdown
page-title: Markdown component | Vaadin components
description: Markdown allows you to render Markdown content in your application with support for basic formatting, lists, links, and more.
meta-description: Use the Vaadin Markdown component to display Markdown formatted content in Vaadin applications.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/markdown}/elements/vaadin-markdown[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/markdown/Markdown.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/markdown}/packages/markdown[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-markdown-flow-parent[Java]'
---
= Markdown

// tag::description[]
The Markdown component renders content written in the Markdown syntax as HTML.
// end::description[]
It supports basic text formatting, lists, links, and more. All content provided to the component is internally sanitized to prevent potentially dangerous HTML from being rendered.

For more information about common Markdown syntax features, see the https://www.markdownguide.org/basic-syntax/[Markdown Guide].


[.example,themes="lumo,aura"]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/markdown/markdown-basic.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/markdown/MarkdownBasic.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/markdown/react/markdown-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]

--


[role="since:com.vaadin:vaadin@V25.3"]
== Line Breaks

By default, the component follows the original Markdown specification: a single line break within a paragraph is collapsed into a space, and a blank line is needed to start a new paragraph.
Enabling the line breaks option renders single line breaks (also called _soft breaks_) as actual line breaks, the way chat and message-style Markdown behaves. Blank lines still start a new paragraph.

[.example,themes="lumo,aura"]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/markdown/markdown-line-breaks.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/markdown/MarkdownLineBreaks.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/markdown/react/markdown-line-breaks.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]

--

[discussion-id]`77B51D28-FE42-4829-A315-D0F3C8A55BED`
