version: "3"

services:
  dspublisher:
    build:
      context: ".."
      dockerfile: "deployment-example-docker/docs-app.Dockerfile"
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - docs

  docs:
    build:
      context: ".."
      dockerfile: "deployment-example-docker/docs.Dockerfile"
    restart: unless-stopped
    expose:
      - "8080"
