---
title: Columns
page-title: Configuring columns of the Vaadin Grid component
meta-description: Learn about aligning, freezing, grouping, headers and footers, visibility, and width of the Vaadin Grid component's columns.
order: 10
---


= Grid Columns


Column alignment, freezing (i.e. fixed positioning), grouping, headers and footers, visibility, and width can be configured. Users can be allowed to resize and reorder columns.


== Column Alignment

Three different column alignments are supported: left, which is the default; center; and right.

Right alignment is useful when comparing numeric values, as it helps with readability and scannability. Notice how the _Amount_ column in the example here aligns the euro values to the right. Those values would be difficult to scan visually if they were left aligned or centered. Tabular numbers -- if the font offers them -- or a monospace font could be used to further improve digit alignment.

[.example]
--

ifdef::lit[]
[source,typescript]
----

include::{root}/frontend/demo/component/grid/grid-column-alignment.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/grid/GridColumnAlignment.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/grid/react/grid-column-alignment.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Column Freezing

Columns and column groups can be frozen -- made _sticky_ -- to exclude them from horizontally scrolling a grid. This can be useful for keeping the most important columns always visible in a grid that contains so many columns they might otherwise scroll out of view. Freezing columns at the end of the grid is useful, for example, for keeping row actions always visible.

In the example here, try scrolling the data to the right and back left. Notice that the name of each person is stationary so that you can see easily which data relates to which person as you scroll. The _Edit_ button at the end also remains in place so that it's available at any point while scrolling.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/grid/grid-column-freezing.ts[render,tags=*,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/grid/GridColumnFreezing.java[render,tags=*,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/grid/react/grid-column-freezing.tsx[render,tags=*,indent=0,group=React]
----
endif::[]
--

Although it's technically possible to freeze any column, it should be used primarily to freeze columns at the start or end of the grid, leaving the remaining columns unfrozen.


== Column Grouping

It's possible to group columns. They share a common header and footer. Use this feature to better visualize and organize related or hierarchical data.

In the example below, the first and last names are grouped under _Name_. Whereas, the street address, the city, and so forth are grouped under _Address_.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/grid/grid-column-grouping.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/grid/GridColumnGrouping.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/grid/react/grid-column-grouping.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Column Headers & Footers

Each column has a customizable header and footer. A basic column header shows the name in plain text. Footers are empty by default and therefore hidden. However, if you add content for the footer, it becomes visible. Incidentally, both the header and footer can contain rich content and components -- notice the header and footer in the example here.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/grid/grid-column-header-footer.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/grid/GridColumnHeaderFooter.java[render,tags=snippet1,indent=0,group=Flow]

...

include::{root}/src/main/java/com/vaadin/demo/component/grid/GridColumnHeaderFooter.java[render,tags=snippet2,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/grid/react/grid-column-header-footer.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Column Visibility

When you want, columns and column groups can be hidden. You can provide the user with a menu for toggling column visibilities, for example, using Popover. Allowing the user to hide columns is useful when only a subset of the columns is relevant to their task, and if there are plenty of columns.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/popover/popover-anchored-dialog.ts[render,tags=gridsnippet,indent=0,group=Lit]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/popover/PopoverAnchoredDialog.java[render,tags=gridsnippet,indent=0,group=Flow]
----

[source,tsx]
----
include::{root}/frontend/demo/component/popover/react/popover-anchored-dialog.tsx[render,tags=gridsnippet,indent=0,group=React]
----
--


== Column Reordering & Resizing

Enabling the user to reorder columns is useful when they want to compare data that isn't adjacent by default. Grouped columns can only be reordered within their group. Resizing is helpful when a column's content doesn't fit and is cut off or varies in length.

Instead of hiding columns as in the earlier example, in the example here the user can resize a truncated column to be able to read it, fully. Try doing that. Hover your mouse pointer over the space on the header row between the _Street_ and _City_ columns, until the mouse pointer changes to a resizing tool. Then, while holding the left mouse button, pull on the right edge of the _Street_ column until you can see all of the street addresses.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/grid/grid-column-reordering-resizing.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/grid/GridColumnReorderingResizing.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/grid/react/grid-column-reordering-resizing.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Column Width

Unless specified, all columns are the same width. You can set a specific width for any column, though, or allow the Grid to set the width based on the content. Column widths can be fixed or non-fixed, which is the default. Fixed-width columns don't grow or shrink as the available space changes, while non-fixed-width columns do.

[NOTE]
The `em` length unit is a relative setting for font sizes. Don't use it for column widths. If the font sizes of the header, body or footer cells differ, may cause column widths to be inconsistent, leading to misaligned content. When length relative to the font size is needed, use instead the `rem` length unit -- or make sure that the font size is consistent across the cells.

In the following example, the first and last columns have fixed widths. The second column's width is set to be based on the content, while the third consumes the remaining space.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/grid/grid-column-width.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/grid/GridColumnWidth.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/grid/react/grid-column-width.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

++++
<style>
/* Try to minimize the amount of layout shifting when examples get imported and rendered */
.code-example .render {
  min-height: calc(400px + var(--docs-space-xl) * 2) !important;
}
</style>
++++
