---
title: Data Binding
page-title: How to bind data to Grid using data providers
description: Binding and displaying data in Grid
order: 50
section-nav: badge-flow
---

= Binding Data to Grid [badge-flow]#Flow#
:toclevels: 2

Grid supports connecting to different types of data sources using data providers.

== Binding Items with setItems

The `setItems` method is a convenience API in Grid that supports most common use cases like binding in-memory collections and lazy-loaded data. It sets up a data provider for you behind the scenes based on the arguments and returns either a `GridListDataView` or `GridLazyDataView` instance, which lets you configure the displayed items, for example, by applying filtering and sorting.

.Binding a collection of items using the varargs overload:
[source,java]
----
GridListDataView dataView = grid.setItems(
  new Person("George Washington", 1732),
  new Person("John Adams", 1735),
  new Person("Thomas Jefferson", 1743),
  new Person("James Madison", 1751)
);
----

.Binding a lazy-loaded data source by providing fetch and count callbacks:
[source,java]
----
GridLazyDataView dataView = grid.setItems(
  // Callback for fetching items, returns a Stream<Person>
  query -> personService.fetch(query.getOffset(), query.getLimit()),
  // Callback for counting items, returns an Integer
  query -> personService.count()
);
----

For more details and examples on using the `setItems` method, refer to the <<{articles}/flow/binding-data/data-provider#,Binding Items To Components>> article.

== Custom Data Providers

Alternatively, you can provide a data provider directly via the `setDataProvider` method, for example by passing your own class that implements the `DataProvider` interface.
