---
title: Drag and Drop
page-title: How to enable Grid Drag and Drop in Vaadin
meta-description: Add functionality for drag and drop to the Vaadin Grid component for improved interactivity.
order: 40
---


= Grid Drag & Drop

Grid supports drag-and-drop actions. This feature might be used, for example, to reorder rows and to drag rows between grids.


== Drop Mode

The drop mode of a grid determines where a drop can happen. Vaadin offers four different drop modes, which are described in the table here:

|===
|Drop Mode |Description

|<<#drag-rows-between-grids,On Grid>>
|Drops can occur on the grid as a whole, not on top of rows or between individual rows. Use this mode when the order isn't important.

|<<#row-reordering,Between>>
|Drops can happen between rows. Use this mode when the order is important.

|<<#drag-and-drop-filters,On Top>>
|Drops can take place on top of rows. This is useful when creating relationships between items or moving an item into another item, such as placing a file inside a folder.

|On Top or Between
|Drops can occur on top of rows or between them.
|===


== Row Reordering

You can drag rows to reorder them. This can be a useful and impressive feature for users. Try dragging with your mouse one of the rows of data in the example here to another place in the list.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/grid/grid-row-reordering.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/grid/GridRowReordering.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/grid/react/grid-row-reordering.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Drag Rows between Grids

Rows can be dragged from one grid to another. You might use this feature to move, copy or link items from different datasets.

In the example here, there are two grids of data. Maybe they represent people to speak at two different presentations at the same conference. One grid lists the first panel of speakers and the other the second panel. Try dragging people from one to the other, as if you were reassigning them to speak at a different panel.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/grid/grid-drag-rows-between-grids.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/grid/GridDragRowsBetweenGrids.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/grid/react/grid-drag-rows-between-grids.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


[[drag-and-drop-filters]]
== Drag & Drop Filters

Drag-and-drop filters determine which rows are draggable and which rows are valid drop targets. These filters function on a per-row basis.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/grid/grid-drag-drop-filters.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/grid/GridDragDropFilters.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/grid/react/grid-drag-drop-filters.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


++++
<style>
/* Try to minimize the amount of layout shifting when examples get imported and rendered */
.code-example .render {
  min-height: calc(400px + var(--docs-space-xl) * 2) !important;
}
</style>
++++
