---
title: Styling
description: Styling API reference for the Grid component.
order: 50
---


= Styling

include::../_styling-section-theming-props.adoc[tag=style-properties]

[cols="1,2,2"]
|===
| Feature | Property | Default Value

|Row/cell background
|`--vaadin-grid-cell-background`
|`--lumo-base-color`

|Row/cell padding
|`--vaadin-grid-cell-padding`
|`--lumo-space-xs` / `--lumo-space-m`

|===



include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-grid`


=== Rows

Row (any):: `vaadin-grid+++<wbr>+++**::part(row)**`
First row:: `vaadin-grid+++<wbr>+++**::part(first-row)**`
Last row:: `vaadin-grid+++<wbr>+++**::part(last-row)**`
Even row:: `vaadin-grid+++<wbr>+++**::part(even-row)**`
Odd row:: `vaadin-grid+++<wbr>+++**::part(odd-row)**`
Selected row:: `vaadin-grid+++<wbr>+++**::part(selected-row)**`
Hovered row:: `vaadin-grid+++<wbr>+++**::part(row):hover**`

Note:
* To set background colors based on row selectors, use the [since:com.vaadin:vaadin@V24.3]#`--vaadin-grid-cell-background` style property#.


=== Cells

Cell (any):: `vaadin-grid+++<wbr>+++**::part(cell)**`
Header row cell:: `vaadin-grid+++<wbr>+++**::part(header-cell)**`
Body cell:: `vaadin-grid+++<wbr>+++**::part(body-cell)**`
Footer row cell:: `vaadin-grid+++<wbr>+++**::part(footer-cell)**`
Focused cell:: `vaadin-grid+++<wbr>+++**::part(focused-cell)**`
Cell contents:: `vaadin-grid-cell-content`
Cell in first column:: `vaadin-grid+++<wbr>+++**::part(first-column-cell)**`
Cell in last column:: `vaadin-grid+++<wbr>+++**::part(last-column-cell)**`
Cell in first row:: `vaadin-grid+++<wbr>+++**::part(first-row-cell)**`
Cell in last row:: `vaadin-grid+++<wbr>+++**::part(last-row-cell)**`
Cell in even row:: `vaadin-grid+++<wbr>+++**::part(even-row-cell)**`
Cell in odd row:: `vaadin-grid+++<wbr>+++**::part(odd-row-cell)**`
Cell in selected row:: `vaadin-grid+++<wbr>+++**::part(selected-row-cell)**`
Cell in first header row:: `vaadin-grid+++<wbr>+++**::part(first-header-row-cell)**`
Cell in last header row:: `vaadin-grid+++<wbr>+++**::part(last-header-row-cell)**`
Cell focus ring:: `vaadin-grid+++<wbr>+++**::part(cell)::before**`
Row focus ring:: `vaadin-grid+++<wbr>+++**::part(row)::before**`
Collapsed cell:: `vaadin-grid+++<wbr>+++**::part(collapsed-row-cell)**`
Expanded cell:: `vaadin-grid+++<wbr>+++**::part(expanded-row-cell)**`

You can <<index#part-name-generator,style individual cells, rows, and columns>> by applying custom part names to them. Cell padding can be styled using the `--vaadin-grid-cell-padding` style property.


=== Selection Checkboxes

Row selection checkbox:: `vaadin-grid+++<wbr>+++** > vaadin-checkbox**`
Select All checkbox:: `vaadin-grid+++<wbr>+++** > #selectAllCheckbox**`


=== Sorters

Element:: `vaadin-grid-sorter`
Active sorter:: `vaadin-grid-sorter+++<wbr>+++**[direction]**`
Column header content:: `vaadin-grid-sorter+++<wbr>+++**::part(content)**`
Sort indicators:: `vaadin-grid-sorter+++<wbr>+++**::part(indicators)**`
Sort indicator icons:: `vaadin-grid-sorter+++<wbr>+++**::part(indicators)::before**`
Sort order indicator:: `vaadin-grid-sorter+++<wbr>+++**::part(order)**`


=== Item Details

Item details cell (spans entire row):: `vaadin-grid+++<wbr>+++**::part(details-cell)**`
Cell in row with open details:: `vaadin-grid+++<wbr>+++**::part(details-open-row-cell)**`
Row with open details:: `vaadin-grid+++<wbr>+++**::part(details-open-row)**`

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++
