---
title: Quarkus
order: 1
layout: page
---

[[quarkus.basic]]
= Using Quarkus With Vaadin

Quarkus is an open source, Kubernetes-native Java framework made for Java virtual machines and native compilation, optimizing Java specifically for containers and enabling it to become an effective platform for serverless, cloud, and Kubernetes environments.
Check https://quarkus.io/ to get more info about Quarkus.

To be able to run Quarkus the `vaadin-quarkus` and `vaadin-jandex` dependencies 
are required.
Using the `quarkus-maven-plugin` the `quarkus:dev` goal is used to start the application.

The https://github.com/vaadin/base-starter-flow-quarkus/[Quarkus base starter] project  can be used
as a starting point for your own application.

== Vaadin CDI Features

Quarkus’ dependency injection solution is based on CDI, so it's possible to use all CDI features.
See the documentation for Vaadin CDI features:
- <<../cdi/contexts#, Vaadin CDI Scopes>> 
- <<../cdi/events#, Observable Vaadin Events>> 
- <<../cdi/service-beans#, Vaadin Service Interfaces as CDI Beans>>
- <<../cdi/instantiated-beans#, Using CDI Beans>>


[[quarkus.vaadin.addons]]
== Vaadin add-ons In Quarkus Applications

Any Vaadin add-on used in a Quarkus application should contain a jandex index.
This is generated using the `jandex-maven-plugin`.
See https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index[How to Generate a Jandex Index]
If you can’t modify the dependency, you can still get Quarkus to index it by adding `quarkus.index-dependency` 
entries to your application.properties:

.application.properties
[source, properties]
----
quarkus.index-dependency.<name>.group-id=
quarkus.index-dependency.<name>.artifact-id=
quarkus.index-dependency.<name>.classifier=(this one is optional)
----


[[quarkus.vaadin.limitations]]
== Limitations


WebSockets Push doesn't work currently in the Vaadin extension for Quarkus.
As a consequence Live reload functionality is not available.