---
title: Theming
description: Each SSO provider has its own way of customizing the log-in page, with different features and limitations. Learn how to customize the log-in page for different authentication providers.
order: 110
---

= Theming

== Keycloak

Keycloak offers the most control over what can be customized, from the login page to the administration and user dashboards.
SSO Kit offers a custom theme for Keycloak based on <<{articles}/styling/lumo#,Lumo>>.
It gives the provider's login page a look and feel similar to what a Vaadin developer would experience using the <<{articles}/components/login#,Login component>>.

=== Installation

To use the Keycloak Lumo theme, you need to do a few things:

. First, download the http://tools.vaadin.com/nexus/content/repositories/vaadin-prereleases/com/vaadin/sso-kit-keycloak-theme/[`sso-kit-keycloak-lumo`] JAR file from Maven.
. Next, copy the JAR file into the [filename]`/providers` directory of your Keycloak installation.

Once you've done that, you can either set the theme for all or some clients in a realm.

- To set the theme for all clients, go to "Realm settings", "Themes". At the "Login theme" selector, choose `sso-kit-keycloak-lumo`.
- To set the theme on a specific client, go to "Clients" and find the client. At the "Login settings" section, select `sso-kit-keycloak-lumo` as the "Login theme".

=== Customizing the Lumo Theme

You can also customize the Lumo theme to suit your application's branding.
To customize the theme, you need to do a couple of things:

. Create this directory structure under the [filename]`/themes` directory of your Keycloak installation:
+
----
themes/
└── your-theme/
    ├── resources/css/
    │  └── my-theme-styles.css
    └── themes.properties
----
. In [filename]`themes.properties`, you need to define some properties such as the parent theme, and load the CSS files:
+
.themes.properties
[source,properties]
----
# Specify the parent theme
parent=sso-kit-keycloak-lumo
# Need also to load the files from the parent theme
styles=css/lumo-common.css css/lumo-styles.css css/my-theme-styles.css
----

. Next, in [filename]`my-theme-styles.css` you can add your styles. For example, you might change the primary color to suit your application's branding.
+
.`my-theme-styles.css`
[source,css]
----
include::{root}/frontend/themes/docs/keycloak-theme-example.css[]
----

While working on a custom theme, you might want to disable Keycloak theme caching. You would do that like this:

[.example]
--
[source,terminal]
----
<source-info group="Windows"></source-info>
./bin/kc.bat start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
----
[source,terminal]
----
<source-info group="macOS/Linux"></source-info>
./bin/kc.sh start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
----
--

For more instructions, see the https://www.keycloak.org/docs/latest/server_development/index.html#_themes[official Keycloak theme documentation].
