INSERT INTO manufacturer (name, headquarter_city) VALUES ('ABC Electronics', 'New York');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('XYZ Appliances', 'Los Angeles');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Tech Innovators Inc.', 'San Francisco');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('MegaCorp Tech Solutions', 'Chicago');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Global Hardware Enterprises', 'Miami');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Swift Tech Industries', 'Houston');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Prime Electronics Co.', 'Boston');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Tech World Ltd.', 'Washington, D.C.');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Vanguard Innovations', 'Dallas');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Eagle Electronics', 'San Diego');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('InnovateTech Corporation', 'San Jose');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Ace Electronics', 'Seattle');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Star Appliances', 'Phoenix');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Elite Innovations Inc.', 'Denver');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Golden Tech Enterprises', 'Las Vegas');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Liberty Electronics', 'Atlanta');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Tech Innovators East', 'Philadelphia');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Sunrise Electronics', 'Detroit');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Sunset Electronics', 'San Antonio');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('TechWise Solutions', 'Minneapolis');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Horizon Electronics', 'Portland');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('TechSource Corp.', 'St. Louis');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Bright Future Tech', 'Cleveland');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Modern Electronics', 'Kansas City');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Tech Pioneers', 'Indianapolis');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Apex Innovations', 'Charlotte');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Global Electronics Corp.', 'Orlando');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Infinite Innovations', 'Tampa');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Pinnacle Tech Solutions', 'Pittsburgh');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Smart Electronics', 'Sacramento');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('QuickTech Corporation', 'Raleigh');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('City Electronics', 'Nashville');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('AllStar Innovations', 'Hartford');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Tech Leaders Inc.', 'Louisville');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Capital Electronics', 'Austin');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Mountain Innovators', 'Salt Lake City');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('SunTech Enterprises', 'Albuquerque');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('BlueSky Electronics', 'Birmingham');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('InnovaTech Solutions', 'Richmond');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Metro Electronics', 'Memphis');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('GoldenGate Innovations', 'San Jose');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Sunny Electronics', 'Miami');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('TechStar Innovations', 'Tucson');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('BlueWave Electronics', 'Virginia Beach');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Pacific Innovators', 'Long Beach');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('TechWave Solutions', 'Oakland');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Infinite Electronics Inc.', 'Honolulu');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Crescent Tech Corp.', 'New Orleans');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Intel Corp.', 'New Orleans');
INSERT INTO manufacturer (name, headquarter_city) VALUES ('Microsoft Corp.', 'Seattle');

INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Apple', 'Fruit', 1.99, '2019-01-01', 1);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Banana', 'Fruit', 2.99, '2019-01-02', 2);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Carrot', 'Vegetable', 3.99, '2019-01-03', 3);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Eggplant', 'Vegetable', 5.99, '2019-01-05', 4);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Orange', 'Fruit', 2.49, '2019-01-06', 5);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Broccoli', 'Vegetable', 4.29, '2019-01-07', 6);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Grapes', 'Fruit', 3.79, '2019-01-08', 7);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Cucumber', 'Vegetable', 2.89, '2019-01-09', 8);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Strawberry', 'Fruit', 4.99, '2019-01-10', 9);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Tomato', 'Vegetable', 2.19, '2019-01-11', 10);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Pineapple', 'Fruit', 3.69, '2019-01-12', 11);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Spinach', 'Vegetable', 2.79, '2019-01-13', 12);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Blueberry', 'Fruit', 6.49, '2019-01-14', 13);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Bell Pepper', 'Vegetable', 1.99, '2019-01-15', 14);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Watermelon', 'Fruit', 7.99, '2019-01-16', 15);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Zucchini', 'Vegetable', 2.49, '2019-01-17', 16);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Mango', 'Fruit', 4.79, '2019-01-18', 17);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Asparagus', 'Vegetable', 3.29, '2019-01-19', 18);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Cherry', 'Fruit', 3.99, '2019-01-20', 19);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Potato', 'Vegetable', 1.49, '2019-01-21', 20);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Pear', 'Fruit', 2.59, '2019-01-22', 21);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Cantaloupe', 'Fruit', 3.99, '2019-01-23', 22);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Cauliflower', 'Vegetable', 2.19, '2019-01-24', 23);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Lemon', 'Fruit', 1.79, '2019-01-25', 24);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Cabbage', 'Vegetable', 1.69, '2019-01-26', 25);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Raspberry', 'Fruit', 5.29, '2019-01-27', 26);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Onion', 'Vegetable', 1.29, '2019-01-28', 27);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Kiwi', 'Fruit', 2.69, '2019-01-29', 28);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Green Bean', 'Vegetable', 2.39, '2019-01-30', 29);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Blackberry', 'Fruit', 4.49, '2019-01-31', 30);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Sweet Potato', 'Vegetable', 1.99, '2019-02-01', 31);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Peach', 'Fruit', 3.49, '2019-02-02', 32);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Celery', 'Vegetable', 1.89, '2019-02-03', 33);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Grapefruit', 'Fruit', 2.99, '2019-02-04', 34);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Radish', 'Vegetable', 1.29, '2019-02-05', 35);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Apricot', 'Fruit', 3.99, '2019-02-06', 36);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Brussels Sprout', 'Vegetable', 2.49, '2019-02-07', 37);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Artichoke', 'Vegetable', 3.99, '2019-02-09', 38);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Lime', 'Fruit', 1.49, '2019-02-10', 39);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Beet', 'Vegetable', 1.99, '2019-02-11', 40);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Plum', 'Fruit', 2.99, '2019-02-12', 41);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Corn', 'Vegetable', 1.49, '2019-02-13', 42);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Pomegranate', 'Fruit', 3.99, '2019-02-14', 43);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Garlic', 'Vegetable', 1.29, '2019-02-15', 44);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Papaya', 'Fruit', 4.99, '2019-02-16', 45);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Green Onion', 'Vegetable', 1.49, '2019-02-17', 46);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Ginger', 'Vegetable', 1.99, '2019-02-19', 47);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Parsley', 'Vegetable', 1.29, '2019-02-20', 48);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Parsnip', 'Vegetable', 1.99, '2019-02-21', 49);
INSERT INTO product (name, category, price, date_added, manufacturer_id) VALUES('Peas', 'Vegetable', 1.99, '2019-02-24', 50);
