INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('FreshFruit Co.', 'New York');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('GreenFields Supplies', 'Los Angeles');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Tropical Harvesters', 'Miami');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('FarmFresh Distributors', 'Houston');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Orchard Delights Inc.', 'Chicago');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('HealthyHarvest Corp.', 'San Francisco');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Sunrise Fruits Ltd.', 'Phoenix');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('BerryBounty Enterprises', 'Atlanta');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Nature''s Best Foods', 'Denver');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Vineyard Veggies', 'San Diego');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Farmers'' Choice Produce', 'Orlando');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Fruitful Gardens Inc.', 'Seattle');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Organic Orchard Supply', 'Portland');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('GoldenHarvest Farms', 'Dallas');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('FreshPicks Produce', 'Tampa');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('SunKissed Fruit Co.', 'Minneapolis');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Vegetable Valley Inc.', 'San Jose');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Evergreen Acres Distributors', 'Austin');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Harmony Harvesters', 'Las Vegas');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('FruitElegance Suppliers', 'Indianapolis');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Nature''s Bounty Produce', 'Charlotte');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('FarmFresh Select', 'Sacramento');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('GreenVista Distribution', 'San Antonio');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Orchard Delights West', 'Raleigh');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('JuicyHarvesters Corp.', 'Nashville');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('GreenGroves Farms', 'Memphis');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Sunrise Orchards Ltd.', 'Louisville');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('FarmFresh Harvesters', 'Albuquerque');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Vineyard Veggies East', 'Hartford');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Fruitful Gardens West', 'Richmond');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Organic Orchard Select', 'Kansas City');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('GoldenHarvest Produce East', 'Long Beach');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('BerryBounty Distributors', 'Oakland');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('FreshPicks Farms West', 'Honolulu');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Tropical Harvesters East', 'Birmingham');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('HealthyHarvest Corp. West', 'New Orleans');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('FarmFresh Select East', 'Virginia Beach');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Nature''s Bounty Suppliers', 'Baltimore');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('SunKissed Fruit Co. West', 'Tucson');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Orchard Delights North', 'Anchorage');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('FruitElegance Enterprises', 'Boise');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('GreenVista Distribution West', 'Des Moines');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Farmers'' Choice Produce East', 'Omaha');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Sunrise Orchards Ltd. West', 'Wichita');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Organic Orchard Supply East', 'Little Rock');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Vineyard Veggies North', 'Salt Lake City');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Evergreen Acres Distributors West', 'Fresno');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('JuicyHarvesters Corp. East', 'Spokane');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('GreenFields Supplies West', 'Billings');
INSERT INTO supplier(supplier_name, headquarter_city) VALUES ('Fruitful Gardens North', 'Sioux Falls');

INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Apple', 'Fruit', 1.99, '2019-01-01', 1);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Banana', 'Fruit', 2.99, '2019-01-02', 2);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Carrot', 'Vegetable', 3.99, '2019-01-03', 3);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Eggplant', 'Vegetable', 5.99, '2019-01-05', 4);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Orange', 'Fruit', 2.49, '2019-01-06', 5);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Broccoli', 'Vegetable', 4.29, '2019-01-07', 6);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Grapes', 'Fruit', 3.79, '2019-01-08', 7);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Cucumber', 'Vegetable', 2.89, '2019-01-09', 8);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Strawberry', 'Fruit', 4.99, '2019-01-10', 9);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Tomato', 'Vegetable', 2.19, '2019-01-11', 10);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Pineapple', 'Fruit', 3.69, '2019-01-12', 11);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Spinach', 'Vegetable', 2.79, '2019-01-13', 12);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Blueberry', 'Fruit', 6.49, '2019-01-14', 13);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Bell Pepper', 'Vegetable', 1.99, '2019-01-15', 14);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Watermelon', 'Fruit', 7.99, '2019-01-16', 15);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Zucchini', 'Vegetable', 2.49, '2019-01-17', 16);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Mango', 'Fruit', 4.79, '2019-01-18', 17);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Asparagus', 'Vegetable', 3.29, '2019-01-19', 18);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Cherry', 'Fruit', 3.99, '2019-01-20', 19);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Potato', 'Vegetable', 1.49, '2019-01-21', 20);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Pear', 'Fruit', 2.59, '2019-01-22', 21);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Cantaloupe', 'Fruit', 3.99, '2019-01-23', 22);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Cauliflower', 'Vegetable', 2.19, '2019-01-24', 23);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Lemon', 'Fruit', 1.79, '2019-01-25', 24);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Cabbage', 'Vegetable', 1.69, '2019-01-26', 25);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Raspberry', 'Fruit', 5.29, '2019-01-27', 26);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Onion', 'Vegetable', 1.29, '2019-01-28', 27);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Kiwi', 'Fruit', 2.69, '2019-01-29', 28);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Green Bean', 'Vegetable', 2.39, '2019-01-30', 29);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Blackberry', 'Fruit', 4.49, '2019-01-31', 30);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Sweet Potato', 'Vegetable', 1.99, '2019-02-01', 31);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Peach', 'Fruit', 3.49, '2019-02-02', 32);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Celery', 'Vegetable', 1.89, '2019-02-03', 33);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Grapefruit', 'Fruit', 2.99, '2019-02-04', 34);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Radish', 'Vegetable', 1.29, '2019-02-05', 35);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Apricot', 'Fruit', 3.99, '2019-02-06', 36);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Brussels Sprout', 'Vegetable', 2.49, '2019-02-07', 37);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Artichoke', 'Vegetable', 3.99, '2019-02-09', 38);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Lime', 'Fruit', 1.49, '2019-02-10', 39);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Beet', 'Vegetable', 1.99, '2019-02-11', 40);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Plum', 'Fruit', 2.99, '2019-02-12', 41);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Corn', 'Vegetable', 1.49, '2019-02-13', 42);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Pomegranate', 'Fruit', 3.99, '2019-02-14', 43);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Garlic', 'Vegetable', 1.29, '2019-02-15', 44);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Papaya', 'Fruit', 4.99, '2019-02-16', 45);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Green Onion', 'Vegetable', 1.49, '2019-02-17', 46);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Ginger', 'Vegetable', 1.99, '2019-02-19', 47);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Parsley', 'Vegetable', 1.29, '2019-02-20', 48);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Parsnip', 'Vegetable', 1.99, '2019-02-21', 49);
INSERT INTO product (name, category, price, date_added, supplier_id) VALUES('Peas', 'Vegetable', 1.99, '2019-02-24', 50);
