com.vaadin.experimental.masterDetailLayoutComponent=true
com.vaadin.experimental.sliderComponent=true
com.vaadin.experimental.messageListAttachments=true
com.vaadin.experimental.modularUpload=true
com.vaadin.experimental.badgeComponent=true
