---
title: Vaadin Modernization Toolkit Analyzer for Eclipse
description: How to use the interactive Analyzer
order: 120
---


= Preparing your Application with Modernization Toolkit Analyzer for Eclipse

Modernization Toolkit Analyzer for Eclipse is a tool to assess how well your applications fit the latest Vaadin versions when migrating with the Vaadin Modernization Toolkit. 

The Modernization Toolkit is a Vaadin product that accelerates your migration project. It has two components - a Dragonfly transpiler that does automated refactoring of your code, and a Feature Pack that identifies and isolates useful features from your application's current application platform and makes them available in Vaadin Flow.

The Analyzer works by parsing your project's Java code and resolving your application's references to the libraries you specify, and outputting the high-level results to the Eclipse IDE console. The Analyzer comes with two configuration presets for commonly occurring libraries in Swing applications and Vaadin 7 and 8 applications.

The Analyzer report is something you can copy and share with your colleagues, application stakeholders, or with Vaadin experts to discuss. This will give you some concrete data to consider and can be the start of your discovery and planning for your application’s future.


== Limitations

To satisfy organizations with strict security policies on installing tools in their network, the Modernization Toolkit Analyzer is limited as follows:
- If an internet connection is not possible from the location where the Analyzer is to be run, it is possible to download the coverage data files locally and run them there. Contact Vaadin to get information on how to set this up. By default, the Analyzer connects to the Vaadin servers to access the most up-to-date coverage data;
- The Analyzer does connect to Vaadin servers to retrieve data files but does not send any information to Vaadin. You have full discretion over what about your application or the Analyzer report you would discuss with Vaadin. The Analyzer tool does not have any feature for transmitting information so you cannot use it either accidentally or on purpose to send information;
- It doesn't change your code; and
- It writes all output to the Eclipse console, nothing to disk.


== Using Modernization Toolkit Analyzer
To use Modernization Toolkit Analyzer with Eclipse, there are a few things to do: 
<1> first, make sure Eclipse is ready to use the plugin; 
<2> check that your application projects are ready to be analyzed; 
<3> run the Analyzer; and finally 
<4> interpret the results. These steps are described below.

