---
title: Feature Pack
description: Modernize your application while preserving code expressiveness and developer productivity features
order: 120
---


= Feature pack 

Feature Pack is a part of the Modernization Toolkit. It is a collection of classes and components that isolate useful features from popular developer frameworks, and reproduce them in Vaadin Flow. The scope of Feature Pack was originally limited to Vaadin 7 and 8 features, but today it also includes Swing, AWT and select features from JGoodies and NetBeans.

Feature Pack extends and replaces the older Classic Components project which aimed to be as close as possible to drop-in replacements for a number of Vaadin 7 and 8 components and classes. As a part of the Modernization Toolkit, Feature Pack differs from Classic Components in its setup in a few ways: 

* Feature Pack shifts the emphasis from compile-time compatibility in Java and DOM equivalence, to features your developers can use. Unlike Classic Components, no part of Feature Pack is marked as "deprecated" because there is no horizon set on when the support for Feature Pack will end. Also, unlike Classic Components, most if not all empty methods have been removed that do nothing but throw an UnsupportedException at runtime, leaving you only with a collection of classes and methods that work.
* Implementing Feature Pack in your application is something you can do as part of your regular software development lifecycle, or as part of a broader modernization project. As a tool for modernization, Feature Pack has a tight integration with 



== Limitations

To satisfy organizations with strict security policies on installing tools in their network, the Modernization Toolkit Analyzer is limited as follows:

- If an internet connection is not possible from the location where the Analyzer is to be run, it is possible to download the coverage data files locally and run them there. Contact Vaadin to get information on how to set this up. By default, the Analyzer connects to the Vaadin servers to access the most up-to-date coverage data;
- The Analyzer does connect to Vaadin servers to retrieve data files but does not send any information to Vaadin. You have full discretion over what about your application or the Analyzer report you would discuss with Vaadin. The Analyzer tool does not have any feature for transmitting information so you cannot use it either accidentally or on purpose to send information;
- It doesn't change your code; and
- It writes all output to the Eclipse console, nothing to disk.


