version: "3"

services:
  docs-app:
    image: vaadin/docbuilder:latest
    environment:
      - "DOCS_PROXY_VAADIN_HOSTNAME=docs"
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: "sh -c '[ -f /root/.vaadin/proKey ] && npm run develop || echo \"Invalid Vaadin license file!\"'"

    volumes:
      - docbuilder-maven:/root/.m2
      - docbuilder-gatsby-cache:/docs-app/.cache
      - docbuilder-gatsby-public:/docs-app/public
      - ../..:/docs
      - ~/.vaadin/proKey:/root/.vaadin/proKey
    links:
      - docs

  docs:
    image: vaadin/docbuilder:latest
    expose:
      - "8080"
    restart: unless-stopped
    working_dir: /docs
    command: "sh -c '[ -f /root/.vaadin/proKey ] && mvn || echo \"Invalid Vaadin license file!\"'"
    volumes:
      - docbuilder-maven:/root/.m2
      - docbuilder-vaadin-node-modules:/root/.vaadin/node_modules
      - ../..:/docs
      - ~/.vaadin/proKey:/root/.vaadin/proKey

volumes:
  docbuilder-maven:
  docbuilder-gatsby-cache:
  docbuilder-gatsby-public:
  docbuilder-vaadin-node-modules:
