version: "3"

services:
  docs-app:
    image: vaadin/docbuilder:latest
    environment:
      - DOCS_IMPORT_EXAMPLE_RESOURCES=${DOCS_IMPORT_EXAMPLE_RESOURCES}
      - DOCS_ARTICLES_PATH=${DOCS_ARTICLES_PATH}
      - DOCS_PROXY_VAADIN_HOSTNAME=docs
      - DOCS_TITLE=${DOCS_TITLE}
      - DOCS_VERSIONS_URL=${DOCS_VERSIONS_URL}
      - DOCS_SITE_URL=${DOCS_SITE_URL}
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: "npm run docbuilder:start"

    volumes:
      - ~/.m2:/root/.m2
      - docbuilder-gatsby-cache:/docs-app/.cache
      - docbuilder-gatsby-public:/docs-app/public
      - ../..:/docs
      - ~/.vaadin/proKey:/root/.vaadin/proKey
    links:
      - docs

  docs:
    image: vaadin/docbuilder:latest
    expose:
      - "8080"
    restart: unless-stopped
    working_dir: /docs
    command: "mvn"
    volumes:
      - ~/.m2:/root/.m2
      - ../..:/docs
      - ~/.vaadin/proKey:/root/.vaadin/proKey

volumes:
  docbuilder-gatsby-cache:
  docbuilder-gatsby-public:
