---
title: Dialog
page-title: Dialog component | Vaadin components
description: Dialog is a small window that can be used to present information and user interface elements in an overlay.
meta-description: Use the Vaadin component Dialog to present information and user interface elements in an overlay.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/dialog}/elements/vaadin-dialog[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/dialog/Dialog.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/dialog}/packages/dialog[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-dialog-flow-parent[Java]'
---


= Dialog
:experimental:

// tag::description[]
Dialog is a small window that can be used to present information and user interface elements in an overlay.
// end::description[]

[.example.basic,themes="lumo,aura"]
--

ifdef::lit[]
[source,html]
----

include::{root}/frontend/demo/component/dialog/dialog-basic.ts[render,frame,tags=*,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogBasic.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/dialog/react/dialog-basic.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]
--

++++
<style>
.basic.example iframe {
  height: 400px;
}
</style>
++++


== Structure

The Dialog component has static header and footer areas, and a scrolling content area between them. The header and footer are optional, and are hidden if empty and not explicitly enabled.


=== Header

The header contains an optional title element, and a slot next to it for custom header content, such as a close button.

If the dialog has a title (set via text or custom element), the header content slot is right-aligned. If no title is present, the header content slot is left-aligned.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/dialog/dialog-header.ts[render,tags=*,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogHeader.java[render,tags=*,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/dialog/react/dialog-header.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Footer

Buttons for closure actions (e.g., _Save_, _Cancel_, _Delete_) should be placed in the footer. See the <<../button#buttons-in-dialogs,Button>> component for guidelines for the placement of buttons in Dialogs. Footer content is right-aligned by default. Components can be left-aligned by applying a margin like so:

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/dialog/dialog-footer.ts[render,tags=*,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogFooter.java[render,tags=*,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/dialog/react/dialog-footer.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Modality

A modal dialog blocks the user from interacting with the rest of the user interface while the dialog is open. A non-modal dialog, however, doesn't block interaction. Dialogs are modal by default.

Use modal dialogs for:

- Displaying important information, like system errors;
- Requesting user input as part of a workflow, for example an edit dialog;
- Confirmation of irreversible actions, such as deleting data -- Confirm Dialog is a convenient alternative for these use cases; and
- Breaking out sub-tasks into a separate user interface.

ifdef::flow[]
.Modal Parent Dialogs in Flow
[IMPORTANT]
See the <<Technical>> section for details on the behavior of modal dialogs in Vaadin Flow.
endif::flow[]

Use non-modal dialogs when the user needs access to the content below the dialog, and for less critical, optional, or support tasks.

[.example]
--
ifdef::lit[]
[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-dialog modeless>...</vaadin-dialog>
----
endif::[]

ifdef::flow[]
[source,java]
----
<source-info group="Flow"></source-info>
Dialog dialog = new Dialog();
dialog.setModality(ModalityMode.MODELESS);
----
endif::[]

ifdef::react[]
[source,html]
----
<source-info group="React"></source-info>
<Dialog modeless>...</Dialog>
----
endif::[]
--

Usually, non-modal dialogs should be draggable, so that the user can move them to access the user interface beneath.

[NOTE]
Dialog is not modal in server side by default. In some use cases you may want to enable the server side modality.

[source,java]
----
Dialog dialog = new Dialog();
dialog.setModality(ModalityMode.STRICT);
// Dialog needs to be added to layout
add(dialog);
----


== Position

By default, dialogs open in the center of the viewport. A different positioning can be set programmatically. Dialogs can also be made draggable, allowing the end user to move them around.

The position of the dialog can be set using the `top` and `left` properties:

[.example]
--
ifdef::lit[]
[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-dialog top="50px" left="50px">...</vaadin-dialog>
----
endif::[]

ifdef::flow[]
[source,java]
----
<source-info group="Flow"></source-info>
Dialog dialog = new Dialog();
dialog.setTop("50px");
dialog.setLeft("50px");
----
endif::[]

ifdef::react[]
[source,html]
----
<source-info group="React"></source-info>
<Dialog top="50px" left="50px">...</Dialog>
----
endif::[]
--

=== Draggable

Dialogs can be made draggable, enabling the user to move them around using a pointing device.

By default, the outer edges of a dialog, as well as the space between its components, can be used to move the dialog around.

The default areas from which a dialog can be dragged depend on whether the built-in header is used if the built-in header or footer is used: they function as the default drag handles of the dialog. Without the built-in header, any empty space within the dialog functions can be used as a drag handle.

Any component contained within a dialog can be marked and used as a drag handle by applying the `draggable` class name to it. You can choose whether to make the component's content draggable as well, or only the component itself.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/dialog/dialog-draggable.ts[render,tags=*,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogDraggable.java[render,tags=snippet1,indent=0,group=Flow]

...

include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogDraggable.java[render,tags=snippet2,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/dialog/react/dialog-draggable.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

Make non-modal dialogs draggable so the user can interact with content that might otherwise be obscured by the Dialog. For example, a Dialog for taking notes or for adding widgets to a dashboard by dragging can offer a better experience by allowing the user to move the Dialog around.

Modal dialogs don't benefit from being draggable, as their modality curtain (the dark overlay behind the dialog) obscures the underlying user interface.


== Size

The Dialog size can be set with the width and height on the Dialog itself. You can also set the size of the content of Dialog, whereby the Dialog scales to accommodate it. In both cases, the Dialog can also be made resizable.

[.example]
--

ifdef::lit[]
[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-dialog width="400px" height="200px">...</vaadin-dialog>
----
endif::[]

ifdef::flow[]
[source,java]
----
<source-info group="Flow"></source-info>
Dialog dialog = new Dialog();
dialog.setWidth("400px");
dialog.setHeight("200px");
----
endif::[]

ifdef::react[]
[source,html]
----
<source-info group="React"></source-info>
<Dialog width="400px" height="200px">...</Dialog>
----
endif::[]
--


=== Resizable

The Dialog can be configured to allow the end user to resize it by dragging from its edges.

Dialogs containing dynamic content or plenty of information, such as complex forms or Grids, may benefit from being resizable. This offers the user some flexibility with how much data is visible at once. It also gives the user control over which part of the underlying user interface is obscured.

Dialogs that contain very little or compact information don't need to be resizable.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/dialog/dialog-resizable.ts[render,tags=*,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogResizable.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/dialog/react/dialog-resizable.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Closing

Modal dialogs are closable in three ways: by pressing the kbd:[Esc] key; clicking outside the Dialog; or programmatically, for example through the click of a Button.

Providing an explicit button for closing a Dialog is recommended.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/dialog/dialog-closing.ts[render,tags=*,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogClosing.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/dialog/react/dialog-closing.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Best Practices

=== Use Sparingly

Dialogs are disruptive by nature and should be used sparingly. Don't use them to communicate non-essential information, such as success messages like "Logged in", "Copied", and so on. Instead, use <<../notification#,Notifications>> when appropriate.


=== Button Placement

See <<../button#buttons-in-dialogs, Buttons in Dialogs>>.


== Related Components

|===
|Component |Usage recommendations

|<<../confirm-dialog#,Confirm Dialog>>|Dialog for confirming user actions and decisions

|<<../popover#,Popover>>
|A generic overlay whose position is anchored to an element in the UI.

|===


ifdef::flow[]
== Technical

=== Multiple Dialogs and Strict Server-side Modality in Flow

By default, opening multiple Dialog components in Strict modality mode simultaneously in Flow adds each subsequent Dialog as a child of the previous one.

Due to the <<{articles}/flow/advanced/server-side-modality#server-side-modality,server-side modality mechanism in Flow>>, this means that closing a modal Dialog automatically also closes all its children, that is, any subsequent Dialogs opened after the strictly modal.

This can be avoided by explicitly adding each Dialog to the UI before opening it:

[source,java]
----
Dialog d1 = new Dialog();
d1.setModality(ModalityMode.STRICT);
Dialog d2 = new Dialog();
d2.setModality(ModalityMode.STRICT);
add(d1, d2);  // Add dialogs to the UI before opening
d1.open();
d2.open();
----
endif::[]

[discussion-id]`EBCF8110-6074-4DAB-BE6B-662C813EDDC9`
