---
tab-title: Usage
layout: tabbed-page
title: Dialog
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/dialog}/#/elements/vaadin-dialog[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/dialog/Dialog.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/dialog}/packages/dialog[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-dialog-flow-parent[Java]'
---

= Dialog
:experimental:

// tag::description[]
Dialog is a small window that can be used to present information and user interface elements in an overlay.
// end::description[]


[.example.basic]
--

ifdef::lit[]
[source,html]
----

include::{root}/frontend/demo/component/dialog/dialog-basic.ts[render,frame,tags=*,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogBasic.java[render,frame,tags=snippet,indent=0,group=Java]
----
endif::[]
--

++++
<style>
.basic.example iframe {
  height: 400px;
}
</style>
++++

== Structure

The Dialog component has static header and footer areas, and a scrolling content area between them.
The header and footer are optional, and automatically hidden if empty and not explicitly enabled.

[role="since:com.vaadin:vaadin@V23.1"]
=== Header
The header contains an optional title element, and a slot next to it for custom header content, such as a close button.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/dialog/dialog-header.ts[render,tags=*,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogHeader.java[render,tags=*,indent=0,group=Java]
----
endif::[]
--

[role="since:com.vaadin:vaadin@V23.1"]
=== Footer
Buttons for closure actions, such as _Save_, _Cancel_, _Delete_, and so on, should be placed in the footer.
See the <<../button#buttons-in-dialogs,Button>> component for guidelines for the placement of buttons in dialogs.
Footer content is right-aligned by default.
Components can be left-aligned by applying a margin:

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/dialog/dialog-footer.ts[render,tags=*,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogFooter.java[render,tags=*,indent=0,group=Java]
----
endif::[]
--

=== Padding

The content area's built-in padding can be removed by applying the `no-padding` theme variant.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/dialog/dialog-no-padding.ts[render,tags=*,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogNoPadding.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]
--

== Modality
A modal dialog blocks the user from interacting with the rest of the user interface while the dialog is open.
A non-modal dialog, however, doesn't block interaction.

Dialogs are modal by default.

Use modal dialogs for:

* displaying important information, like system errors
* requesting user input as part of a workflow, for example an edit dialog
* confirmation of irreversible actions, such as deleting data (Confirm Dialog is a convenient alternative for these use cases)
* breaking out sub-tasks into a separate user interface

.Modal parent dialogs in Flow
[IMPORTANT]
See the <<Technical>> section for details on the behavior of modal dialogs in Vaadin Flow.

Use non-modal dialogs:

* when the user needs access to the content below the dialog
* for less critical, optional, and/or support tasks

[.example]
--
[source,html]
----
<source-info group="TypeScript"></source-info>
<vaadin-dialog modeless>...</vaadin-dialog>
----

[source,java]
----
<source-info group="Java"></source-info>
Dialog dialog = new Dialog();
dialog.setModal(false);
----
--

Usually, non-modal dialogs should be draggable, so that the user can move them to access the user interface beneath.

== Draggable

Dialogs can be made draggable, enabling the user to move them around using a pointing device.

By default, the outer edges of a dialog, as well as the space between its components, can be used to move the dialog around.

The default areas from which a dialog can be dragged depend on whether the built-in header is used:

- If the built-in header or footer is used, they function as the default drag handles of the dialog
- Without the built-in header, any empty space within the dialog functions as a drag handle

Any component contained within a dialog can be marked and used as a drag handle by applying the `draggable` class name to it.
You can choose whether to make the component's content draggable as well, or only the component itself.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/dialog/dialog-draggable.ts[render,tags=*,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogDraggable.java[render,tags=snippet1,indent=0,group=Java]

...

include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogDraggable.java[render,tags=snippet2,indent=0,group=Java]
----
endif::[]
--

It's recommended to make non-modal dialogs draggable, so that the user can interact with content that might otherwise be obscured by the Dialog.
For example, a Dialog for taking notes or for adding widgets to a dashboard by dragging can offer a better experience by allowing the user to move the Dialog around.

Modal dialogs don't benefit from being draggable, as their modality curtain (the dark overlay behind the dialog) obscures the underlying user interface.

== Resizable

A resizable dialog allows the user to resize the Dialog by dragging from the edges of the Dialog with a pointing device.
Dialogs aren't resizable by default.

Dialogs containing dynamic content and/or a lot of information, such as complex forms or Grids, may benefit from being resizable, as this offers the user some flexibility with how much data is visible at once.
It also gives the user control over which part of the underlying user interface is obscured.

Dialogs that contain very little, or compact, information don't need to be resizable.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/dialog/dialog-resizable.ts[render,tags=*,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogResizable.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]
--

== Closing

Modal dialogs are closable in three ways:

. Pressing the kbd:[Esc] key
. Clicking outside the Dialog
. Programmatically, for example through the click of a Button

Providing an explicit button for closing a Dialog is recommended.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/dialog/dialog-closing.ts[render,tags=*,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/dialog/DialogClosing.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]
--

== Best Practices

=== Use Sparingly

Dialogs are disruptive by nature and should be used sparingly.
Don't use them to communicate non-essential information, such as success messages like “Logged in”, “Copied”, and so on.
Instead, use <<../notification#,Notifications>> when appropriate.

=== Button Placement

See <<../button#buttons-in-dialogs, Buttons in Dialogs>>.

== Related Components

|===
|Component |Usage recommendations

|<<../confirm-dialog#,Confirm Dialog>>|Dialog for confirming user actions and decisions

|===


== Technical

=== Multiple Dialogs and Server-side Modality in Flow

By default, opening multiple Dialog components simultaneously in Flow adds each subsequent Dialog as a child of the previous one.

Due to the <<{articles}/advanced/server-side-modality#server-side-modality,server-side modality mechanism in Flow>>, this means that closing a modal Dialog automatically also closes all its children, that is, any subsequent Dialogs opened after the modal.

This can be avoided by explicitly adding each Dialog to the UI before opening it:

[source,java]
----
Dialog d1 = new Dialog();
Dialog d2 = new Dialog();
add(d1, d2);  // Add dialogs to the UI before opening
d1.open();
d2.open();
----
