---
title: Exporting Charts as SVG
order: 9
layout: page
---

[[charts.svggenerator]]
= Exporting Charts as SVG

Charts can be exported as SVG by using the [classname]#SVGGenerator# class.
This allows you to generate an SVG string of any chart, using a [classname]#Configuration# object with the chart's data.

== Installing

Add the `vaadin-charts-flow-svg-generator` dependency to your project's `pom.xml` as follows:

[source,xml]
----
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-charts-flow-svg-generator</artifactId>
</dependency>
----

.NodeJS required
NOTE: NodeJS must be installed for the generator to work.

== Using the Generator

Create an instance of `SVGGenerator` and call the `generate()` method, passing the chart's `Configuration` as an argument.
The method returns a string with the SVG data of the chart.

Remember to close the generator when you're done using it.
It is recommended to use a `try-with-resources` block so the generator is automatically closed.

[source,java]
----
Configuration configuration = new Configuration();
// ...
try (SVGGenerator generator = new SVGGenerator()) {
    String svg = generator.generate(configuration);
}
----

== Customizing SVG Generation

Some attributes about the resulting SVG can be customized, like width, height, theme, or language.
Any customizations are handled with the `ExportOptions` class.

[source,java]
----
Configuration configuration = new Configuration();
// ...
ExportOptions options = new ExportOptions();
options.setWidth(800);
options.setHeight(600);
try (SVGGenerator generator = new SVGGenerator()) {
    String svg = generator.generate(configuration, options);
}
----

=== Executing JavaScript Functions

It is possible to execute functions from `Configuration` objects (for example: formatter functions).
Executing functions must be explicitly enabled by setting the `executeFunctions` flag to `true`.

.Only Run Trusted Code
CAUTION: Enabling this option will allow JavaScript code to run on your server.
Make sure to only allow safe and trusted code.

[source,java]
----
Configuration configuration = new Configuration();
configuration.getyAxis().getLabels().setFormatter("function () { return this.value +' mm'; }");
// ...
ExportOptions options = new ExportOptions();
options.setExecuteFunctions(true);
try (SVGGenerator generator = new SVGGenerator()) {
    String svg = generator.generate(configuration, options);
}
----
