[discrete]
==== Flow Breaking Changes

- Java version requirement changes from Java 8 to Java 11
+
For Maven update the java.version
+
[source, xml]
----
<properties>
    <java.version>11</java.version>
</properties>
----
+
or compiler.source and compiler.target
+
[source, xml]
----
<properties>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
</properties>
----

- For Java 9+ `maven-failsafe-plugin` requires jaxb-impl to be added
+
The dependency can be added directly in the plugin definition as:
+
[source, xml]
----
<plugin>
    <artifactId>maven-failsafe-plugin</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>${jaxb.version}</version>
        </dependency>
    </dependencies>
</plugin>
----

- Frontend package manager changes from pnpm to npm
+
The default package manager is now npm, but if using a version older than
8.3 it is recommended to use pnpm instead.
+
To keep using pnpm the configuration pnpm.enable should be set.
+
.Maven
[source, xml]
----
<plugin>
    <groupId>com.vaadin</groupId>
    <artifactId>flow-maven-plugin</artifactId>
    <configuration>
        <pnpmEnable>true</pnpmEnable>
    </configuration>
</plugin>
----
+
.Gradle
[source, groovy]
----
vaadin {
  pnpmEnable = true
}
----
+
Or using the system property `vaadin.pnpm.enable=true`
+
[NOTE]
Running npm without a package-lock.json will be slow for the initial installation.
Coming from a project on pnpm will not have an npm `package-lock.json` as it uses `pnpm-lock.yaml`

- Charts CSS styling mode no longer requires importing and including the default charts theme, so those should be removed.
+
[source, java]
----
/* Before */
@JsModule("@vaadin/vaadin-charts/theme/vaadin-chart-default-theme")
@CssImport(value = "my-chart-styles.css", themeFor = "vaadin-chart", include = "vaadin-chart-default-theme")

/* After */
@CssImport(value = "my-chart-styles.css", themeFor = "vaadin-chart")
----
+


////
Note to whoever converts this into a direct V14->V23 guide:

The V14->V23 upgrade instructions are as follows:

- *Vaadin Charts* now defaults to Java styling mode in Flow, instead of CSS styling mode. If you have applied custom styles to charts using CSS, you need to switch back to CSS styling mode for those to work:
+
[source, java]
----
chart.getConfiguration().getChart().setStyledMode(true);
----

- The default colors in Charts have changed in Vaadin 23 to better match the Lumo and Material themes.
You can revert to the old color scheme by switching to the “classic” theme:
+
[source,java]
----
chart.getElement().setAttribute("theme", "classic");
----
////


[discrete]
==== Changes

- Recommended minimum version of npm is v8.3
+
This is to have the support for overrides to lock transitive dependencies versions.

- When the global node is not compatible, the version in `~/.vaadin` will be used.
+
If a version does not exist or is too old it will be automatically downloaded and installed.
