---
title: Avatar
description: Avatar is a graphical representation of an object or entity, for example a person or an organization.
---

= Avatar

[source,tsx]
----
<Avatar />
<Avatar name={`${person.firstName} ${person.lastName}`} />
<Avatar
  img={person.pictureUrl}
  name={`${person.firstName} ${person.lastName}`}
/>
----

== Content

Avatar has three properties: *name*, *abbreviation*, and *image*.

=== Name and abbreviation

The name is shown on hover in a tooltip.
When a name is set, Avatar auto-generates and display an abbreviation of the specified name.
For example, “Allison Torres” becomes “AT”, “John Smith” becomes “JS”, and so on.

The abbreviation can also be set manually.
Abbreviations should be kept to a maximum of 2–3 characters.

=== Image

Avatar can be used to display images, such as user profile pictures or company logos.
Abbreviations aren't shown when images are used.

== Avatar Group
Avatar Group is used to group multiple Avatars together.
It can be used, for example, to show that there are multiple users viewing the same page or for listing members of a project.

[source,tsx]
----
<AvatarGroup
  items={persons.map((person) => ({
    name: `${person.firstName} ${person.lastName}`,
  }))}
/>
----

=== Maximum number of items
You can specify the maximum number of items an Avatar Group should display.
Items that overflow are grouped into a single Avatar that displays the overflow count.
The name of each hidden item is shown on hover in a tooltip.
Clicking the overflow item displays the overflowing avatars and names in a list.

== Background Color
By default, there are 7 different background colors you can use for Avatar.
The background color is set using a color index.

== Internationalisation (i18n)

All texts in Avatar and Avatar Group are configurable:

=== Avatar Texts

[cols="1,1,2"]
|===
| Property | Text | Description

|`anonymous`
|"Anonymous"
|Avatar's default name.
Shown on hover in a tooltip and announced by screen readers when the Avatar is focused.
|===

=== Avatar Group Texts

[cols="1,1,2"]
|===
| Property | Text | Description

|`anonymous`
|"Anonymous"
|Default name for all Avatars in the Avatar Group.

|`activeUsers.one`
|"Currently one active user"
|Announced by screen readers when there is exactly one Avatar in an Avatar Group and the Avatar is focused.
The name of the Avatar is read aloud first.

|`activeUsers.many`
|"Currently {count} active users"
|Announced by screen readers when there are multiple Avatars in an Avatar Group and an Avatar is focused.
The name of the focused Avatar is read aloud first.

*{count} is the Avatar Group item count.

|`joined`
|"{user} joined"
|Announced by screen readers when an Avatar is added to the group.

*{user} is the Avatar's name.

|`left`
|"{user} left"
|Announced by screen readers when an Avatar is removed from the group.

*{user} is the Avatar's name.
|===

== Size variants

Avatar has four available size variants:

|===
| Variant | Theme name

|Extra large
|`xlarge`

|Large
|`large`

|Small
|`small`

|Extra small
|`xsmall`

|===

Size variants should be used only in special cases.
See https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/size-space[Size and Space] for details on how to
change the default Avatar size.

== Use cases

Avatar can be paired with Menu Bar to create a user account menu.

:component-path: avatar
include::{articles}/react/components/_vaadindocs.adoc[]
