++++
<style>
.admonitionblock.note.commercial {
  border: 0;
  background-color: var(--color-gold-lighter);
  font-size: var(--docs-font-size-xs);
  font-weight: var(--docs-font-weight-emphasis);
  color: var(--color-gold-darker);
  --docs-admonitionblock-icon-color: var(--color-gold-darker);
}

.admonitionblock.note.commercial p {
  margin-bottom: 0;
}

.admonitionblock.note.commercial .buttons ul {
  margin-top: 0;
  font-size: var(--docs-font-size-2xs);
}

.admonitionblock.note.commercial .buttons ul a:any-link {
  color: var(--color-gold-darker);
  border-color: var(--color-gold-darker);
  font-weight: var(--docs-font-weight-emphasis);
}

.admonitionblock.note.commercial .buttons ul li:first-child a:any-link {
  color: var(--color-gold-lighter);
  background-color: var(--color-gold-darker);
}

.admonitionblock.note.commercial .buttons ul a:any-link::after {
  content: none;
}
</style>
++++

[.commercial]
[NOTE]
====
This component is included in Pro, Prime, and Enterprise subscriptions.

[.buttons]
- https://vaadin.com/trial[Start Free Trial^]
- https://vaadin.com/pricing[See Pricing^]
====
