---
title: Docker Deployment
description: Deploy your Vaadin application using Docker
order: 55
---

= Deploying Using Docker

A https://docs.docker.com/get-started/overview/[Docker container] is a standalone, executable package of software that includes everything needed to run an application: code, runtime, system tools, system libraries, and settings.
Building a Docker image requires creating a [filename]`Dockerfile`, a text document containing all the commands needed to assemble and run that image.

== Creating a Dockerfile for New Vaadin Applications

For a new Vaadin application, you can generate a [filename]`Dockerfile` by selecting the `Docker` option in https://start.vaadin.com/[Vaadin Start].
This approach makes building and running your container as simple as running the following two commands:

. To make a production build of the actual Vaadin application, run
+
`mvn clean install -Pproduction`

. To build your container (assuming your project name is `myapp`), run
+
`docker build . -t myapp:latest`

. To run your container on localhost
+
`docker run -p 8080:8080 myapp:latest`

[NOTE]
You need to install https://docs.docker.com/desktop/[Docker Desktop] or https://docs.docker.com/engine/install/[Docker Server] on your machine first, before you can run the above commands.

== Adding a Dockerfile to Existing Vaadin Applications

A simple Dockerfile suitable for Spring Boot based Vaadin application looks like this (same as is generated in start.vaadin.com):

.`Dockerfile`
[source,dockerfile]
----
FROM openjdk:17-jdk-slim
COPY target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app.jar"]
----

Once you have a [filename]`Dockerfile` in the project directory, you can build and run your container using the `docker build` and `docker run` commands given earlier.

You can find more information on [filename]`Dockerfile` and its available instructions at https://docs.docker.com/engine/reference/builder/.

[discussion-id]`08DE0256-3D68-4F05-9092-F8ACB1A16C64`
