---
title: Adding Views
description: Learn how to annotate and access Vaadin application views that you wish to render inside your Swing application.
order: 20
---


= Adding Vaadin Views Inside a Swing Application

== Enabling Flow Views

In your Vaadin application, add the [annotationname]`@Bridge` annotation to any views you want to render inside your Swing application. You can use the [methodname]`isSwingRendered()` method to check if a view is rendered in a normal browser or inside a Swing application,
For example:

[source,java]
----
...
import com.vaadin.swingkit.server.Bridge;

@Route("example-view")
@Bridge
public class ExampleView extends HorizontalLayout {
    public ExampleView() {
      if (SwingVaadinServer.isSwingRendered()) {
        // Code which is run only if this view is rendered inside a Swing application
      }
    }
}
----

// TODO the isSwingRendered example would need a proper use case to illustrate when that API is useful


== Rendering Flow Views in Swing

Once you have prepared your Flow views, they can be rendered as a component in your Swing application. The [classname]`JVaadinPanel` class extends the [classname]`Panel` component, and can be added to standard Swing layouts. You can check when the view has been completely rendered using the [methodname]`isReady()` method. For example:

[source,java]
----
...
import com.vaadin.swingkit.client.SwingVaadinClient;
import com.vaadin.swingkit.client.JVaadinPanel;

...
    JVaadinPanel vaadinPanel = SwingVaadinClient.getBuilder().build("example-view");
    vaadinPanel.isReady();
...
----

// TODO the isReady example would need a proper use case to illustrate when that API is useful
