---
title: Login
description: Login is a component that contains a log-in form. You can use it to authenticate the user with a username and password.
---

= Login

[source,tsx]
----
<LoginForm />
----

== Basic login component/form

The basic Login component consists of a title (*Log in*), two input fields (*Username* and *Password*), and two buttons (*Log in* and *Forgot password*).

You can customize the form's title and labels using internationalization.

The basic Login component can be used to create log-in pages featuring rich content.

.Password managers
[NOTE]
Login is incompatible with password managers if placed inside another component's footnote:[When added to a web component that uses shadow root, password managers are unable to find the input fields and thus not work.] shadow root.
This isn't an issue when using Login's modal overlay.

== Modal overlay

Login features its own modal overlay.
Use it to create simple log-in pages -- which are full-screen on mobile devices -- or to handle authentication without a dedicated log-in page.
You can also use it to handle re-authentication when the user's session has expired.

The overlay can be opened programmatically or through user interaction, for example, by using a log-in button.

=== Header

The overlay has a header and the log-in form.
By default, the header contains placeholders for the application's title and description.
Both properties are configurable.

== Validation

Login shows an error message when authentication fails.
The error message consists of a title and a message.
It's displayed directly below the title of the form.

The error message is customizable using internationalization.
It should contain instructions on how to resolve the problem.

More information can also be provided to the user, for example by linking to a page with helpful material or by displaying contact information.

== Internationalization (i18n)

Login's titles, descriptions, labels, and messages are all customizable using internationalization.

=== Header

The header is only shown for modal log-in forms.

pass:[<!-- vale Vaadin.Terms-App = NO -->]

|===
|Property |Default value

|Title
|_"App name"_

|Description
|_"Application description"_
|===

pass:[<!-- vale Vaadin.Terms-App = YES -->]

=== Form

Customize the form's title, input field and button labels.

|===
|Property |Default value

|Title
|_"Log in"_

|Username
|_"Username"_

|Password
|_"Password"_

|Submit
|_"Log in"_

|Forgot password
|_"Forgot password"_
|===

=== Error message

When authentication fails, the component shows a Login error message.
It consists of a title and message.

// Allow "Incorrect"
pass:[<!-- vale Vaadin.ComplexWords = NO -->]

|===
|Property |Default value

|Title
|_"Incorrect username or password"_

|Message
|_"Check that you have entered the correct username and password and try again."_
|===

pass:[<!-- vale Vaadin.TooWordy = NO -->]

=== Additional information

The component hides this property unless its value is explicitly set.

|===
|Property |Default value

|Additional information
|-

|===

pass:[<!-- vale Vaadin.ComplexWords = YES -->]
pass:[<!-- vale Vaadin.TooWordy = YES -->]

== Technical

=== Handling events

==== Login event

You can add a listener to log-in events and/or define an action for which a `POST` request is fired.
From the event, you can prevent the `POST` request.

The log-in button is disabled when clicked, to prevent multiple submissions.
To restore it, call [methodname]`component.setEnabled(true)`.

==== Forgotten password

You can add an event listener, which allows you to offer users instructions for password recovery.

pass:[<!-- vale Vaadin.Abbr = NO -->]

==== Cross-site request forgery (CSRF) tokens

If the page contains the following meta tags with a CSRF token, the token is automatically included in a form `POST` request:

[source,html]
----
<meta name="_csrf_parameter" content="_csrf">
<meta name="_csrf" content="71dac59f-34ee-4b31-b478-2891cbd0c55d">
----

This token is submitted as `_csrf=71dac59f-34ee-4b31-b478-2891cbd0c55d`, that is, using the `_csrf_parameter` content as the variable name and the `_csrf` content as the value.

pass:[<!-- vale Vaadin.Abbr = YES -->]

:component-path: login
include::{articles}/react/components/_vaadindocs.adoc[]
