---
title: Add Images and Icons
page-title: 
description:
meta-description:
order: 10
---

= Add Images and Icons

Introduction

== Copy-Paste into Your Project

Code-snippet of an image that you can copy-paste into your project, to try it out quickly.

Code-snippet of an icon that you can copy-paste into your project, to try it out quickly.

== Images

* Use the `Image` component, which is a wrapper around the HTML `<img>` element.
* Static resources are served by the servlet container.
  * For WAR: images must be stored in `/src/main/webapp`, such as `/src/main/webapp/images/myimage.png` -> `new Image("images/myimage.png", "My Alt Text")`
  * For JAR (Spring Boot): images must be stored in `src/main/resources/META-INF/resources`, such as `/src/main/resources/META-INF/resources/images/myimage.png` -> `new Image("images/myimage.png", "My Alt Text")`
  * When using <<../security#,securing your app>>, remember to grant access to the images as well
  * You can also use `DownloadHandler.forServletResource()` -> `Image image = new Image(DownloadHandler.forServletResource("/images/myimage.png"), "My Streamed Image");`
* Class resources are served by a Vaadin `DownloadHandler` and allows you to serve images from the Java classpath.
  * In this case, images should go into `src/main/resources`
  * Absolute path: `Image image = new Image(DownloadHandler.forClassResource(getClass(),"/images/myimage.png"), "My Streamed Image");`
  * File in the same package as `MyData.class`: `Image image = new Image(DownloadHandler.forClassResource(MyData.class,"myimage.png"), "My Streamed Image");`

== Icons

* Vaadin supports both SVG icons and font icons.
* Many built-in Vaadin components allow you to display an icon along with a title or inside the component.
* This is covered in detail in the <</components/icons#,Icons>> documentation.

