---
title: Add Dialogs and Popovers
page-title: 
description: 
meta-description: 
order: 15
---

= Add Dialogs and Popovers

Intro

== Copy-Paste into Your Project

Include a code example that can be copy-pasted directly into a project to try out dialogs. The example should be a self-contained view, in the same sense as articles/building-apps/views/add-view.adoc or articles/building-apps/forms-data/add-grid/static-data.adoc.

== Confirm Dialog

Summarize the most important parts of articles/components/confirm-dialog/*:

* What is a confirm dialog?
* When do you use it?
* How do you use it?
* Where can you find more information?

== Dialog

Summarize the most important parts of articles/components/*:

* What is a dialog?
* How does it differ from Confirm Dialog?
* When do you use it?
* How do you use it?
* Where can you find more information?

== Popover

Summarize the most important parts of articles/components/popover/*:

* What is a popover?
* How does it differ from Dialog?
* When do you use it?
* How do you use it?
* Where can you find more information


== Summary

End with a summary of when to pick which component (come up with a better section header).

