---
tab-title: Usage
layout: tabbed-page
title: Message List
---

:react:

= Message List

// tag::description[]
Message List allows you to show a list of messages, for example a chat log.
// end::description[]
You can configure the text content, information about the sender, and the time of sending for each message.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/messages/message-list-component.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]
ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/messages/MessageListComponent.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/messages/react/message-list-component.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

The messages in the list can be populated with the `items` property.
The `items` property is of type [classname]`Array`, with JSON objects in it.
Each JSON object is a single message.

== Styling

You can style individual messages by adding a theme property to some items and providing CSS for that theme.
The following example shows how to highlight the current user's own messages:

[.example]
--
[source,css]
----
include::{root}/frontend/themes/docs/message-list-theming.css[]
----
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/messages/message-list-with-theme-component.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]
ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/messages/MessageListWithThemeComponent.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/messages/react/message-list-with-theme-component.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

== Related Components

[cols="1,2"]
|===
|Component |Usage recommendations

|<<../message-input#,Message Input>>|Allow users to author and send messages.

|===



