---
title: Getting Started
order: 3
layout: page
---

= Getting Started With Vaadin Documentation

To make quick corrections or suggestions to the Vaadin Docs, simply click the *GitHub* link in the upper-right corner of any page to start making a contribution through GitHub and then do a pull request.
You should pay note to <<editing-tools.adoc#github, the instructions>> and limitations regarding editing in GitHub.

A more flexible way is to use a local editor and tools.

The basic tasks for contributing to Vaadin documentation are:

. <<editing-tools.adoc#, Install editing tools>>
. Edit documentation
. <<submitting#, Make a pull request in GitHub>>
. Make possible fixes requested by the reviewer


[[repositories]]
== Clone the Docs Repository

The documentation is maintained in the http://github.com/vaadin/docs[`github.com/vaadin/docs`] repository.

Start by cloning the repository.
You should clone it somewhere else in your file system and then create symbolic link to it as described later.

For example:

[source, shell]
----
$ git clone http://github.com/vaadin/docs -b latest
----

Then, open the folder or the pages you want to edit in your editor.
