---
title: Quick Style Guide
order: 70
layout: page
---

= Quick Style Guide
:experimental:

== A

abbreviations

“advice”

apostrophe (‘)

“application”

apposition

“as” or “like”?::
See “‘like’ or ‘as’”.

AsciiDoc::
See “The Longer View” for general guidelines on AsciiDoc formatting in Vaadin technical documentation.

“asynchronous”

“awesome”

== B

“back end”

“both”

brackets::
See “parentheses”.

== C

capitalization

“client side”

code

colon (“:”)

colloquial expressions

comma splice

commas

conditional

contractions

cultural references

currency

== D

dangling participles

dash (“–”) 

“data”

dates

definite article (“the”)

“divider”

double quotes (“)::
See “quotation marks”

“dropdown”

== E

em dash

en dash

“either”

== F

“former”

“front end”

== G

== H

“he” / “she” / “they”

headings

“hierarchy”

“his” / “her” / “their”

“hopefully”

hyphen (“-”)

== I

“if” clauses in the future

“in order to”::
Use “in order to” for clarity.
+
For example:
+
Instead of: “This the information you need to use the components correctly”, \
Use: “This is the information you need in order to use the components correctly”.

indefinite article (“a” / “an”)

“information”

introductory clauses

“its” or “it’s”

== J

== K

== L

“-l-” or “-ll-”?

Latin abbreviations

“latter”

“like” or “as”?

lists

== M

== N

“npm”

numbers

== O

“overlay”

Oxford comma

See “lists”.

== P

parentheses

passive voice

phrasal verbs

possessive

“practice”

product names

punctuation::
See the specific entries for each punctuation mark; for example, “commas”, “quotation marks”, etc.

== Q

quotation marks

== R

relative clauses

“repository”

“respectively”

== S

“s” or “z”

semi-colon (“;”)

“separator”

“server side”

single quotes (‘)::
See “quotation marks”.

slang

slash (“/”)

“software as a service”::
The abbreviation is “SaaS”.

split infinitives

== T

“that”::
If the word “that” is optional, include it for clarity.
+
For example:
+
Instead of: “... to understand your software works correctly”, \
Use: “... to understand that your software works correctly”.

“that” or “which”?::
See “‘which’ or ‘that’”.

“their” or “they’re”?

“time frame”

time clauses in the future

times

== U

“unique”

== V

== W

“which” or “that”?

“who’s” or “whose”?

X

Y

Z

“z” or “s”?::
See “‘s’ or ‘z’”.
