---
title: Customizing System Messages
description: Configuring messages for application invalid state
order: 147
layout: page
---

= Configuring Customizing System Messages

System messages are notifications that indicates a major invalid state that may require restarting the application.
The invalid states handled by system messages are session expiration, internal error and cookie disabled.

When the client falls into one of the invalid states, a notification is shown in the browser and, after the user clicks on it, the page is reloaded.
For session expiration, the default is however to reload the page without showing the notification.

The messages and the behaviour are defined in the [classname]`SystemMessages` class.

Each invalid state has four properties: a short caption, the actual message, a URL to which to redirect after displaying the message, and a property indicating whether the notification is enabled.
If the URL is not specified, the current page is reloaded.
When the notification is disabled, the reload or redirect happens without any notification to the user.
Setting both caption and message to `null` has the same effect as disabling the notification.

The default values of the properties are shown below.
Default values for system messages are also documented on [classname]`SystemMessages` class javadocs.

* [propertyname]`sessionExpiredNotificationEnabled`: false
* [propertyname]`sessionExpiredURL`: null
* [propertyname]`sessionExpiredCaption`: Session Expired
* [propertyname]`sessionExpiredMessage`: Take note of any unsaved data, and click here or press ESC key to continue.
* [propertyname]`internalErrorNotificationEnabled`: true
* [propertyname]`internalErrorURL`: null
* [propertyname]`internalErrorCaption`: Internal error
* [propertyname]`internalErrorMessage`: Please notify the administrator. Take note of any unsaved data, and click here or press ESC to continue.
* [propertyname]`cookiesDisabledNotificationEnabled`: true
* [propertyname]`cookiesDisabledURL`: null
* [propertyname]`cookiesDisabledCaption`: Cookies disabled
* [propertyname]`cookiesDisabledMessage`: This application requires cookies to function. Please enable cookies in your browser and click here or press ESC to try again.

As it can be noted, by default notification is disabled for session expiration, but enabled for internal error and cookie disabled.

System messages can be overridden by setting the [classname]`SystemMessagesProvider` in the [classname]`VaadinService`.
You need to implement the [methodname]`getSystemMessages(SystemMessagesInfo)` method, which should return a [classname]`SystemMessages` object.
The easiest way to customize the messages is to use a [classname]`CustomizedSystemMessages` object, and use provided setter methods to configured the desired properties.

The [classname]`SystemMessagesInfo` parameter provided to [methodname]`getSystemMessages()` allows to get access to the locale of UI, so that messages can be translated in the current user language.

You can set the system message provider in the [methodname]`serviceInit()` method of a <<service-init-listener#, service init listener>>, for example as follows:


[source,java]
----
public class CustomInitServiceListener implements VaadinServiceInitListener {
    @Override
    public void serviceInit(ServiceInitEvent event) {
        event.getSource().setSystemMessagesProvider(new SystemMessagesProvider() {
            @Override
            public SystemMessages getSystemMessages(SystemMessagesInfo systemMessagesInfo) {
                CustomizedSystemMessages messages = new CustomizedSystemMessages();
                messages.setSessionExpiredCaption("Session expired");
                messages.setSessionExpiredMessage("Take note of any unsaved data, and click here or press ESC key to continue.");
                messages.setSessionExpiredURL("session-expired.html");
                messages.setSessionExpiredNotificationEnabled(true);
                return messages;
            }
        });
    };
};
----