---
title: Lazy loading component JavaScript
description: How lazy loading of JavaScript works and can be configured.
order: 800
layout: page
---

= Lazy Loading JavaScript

A production build scans for `Routes` and make lazy loaded bundles of the components used in the routes.

By default, only the routes `""` and `"login"` are eager and every other route components become lazy loaded.

[NOTE]
Any components that are loaded using reflection should be named on the `Route` class using `@Uses` so that they get collected.

=== Configuring Eager Routes

To configure which views should load eagerly use the annotation `@LoadDependenciesOnStartup` on the `AppShellConfiguration` class.

Only defining `LoadDependenciesOnStartup` makes all routes eager.

[source,java]
----
@LoadDependenciesOnStartup
public class Configuration implements AppShellConfigurator {
}
----

To configure specific routes to be eagerly loaded add the route class to the value array for instance:

[source,java]
----
@LoadDependenciesOnStartup({GeneralInfo.class, DataSearch.class})
public class Configuration implements AppShellConfigurator {
}
----

This makes components, scripts and CSS used in `GeneralInfo` and `DataSearch` loaded immediately on bootstrap and any other components used in other view as they are needed.

[discussion-id]`B794EFE2-B833-466A-ACA9-7F60AA6D4332`
