---
title: Modifying the Bootstrap Page at Runtime
description: How to customize the application shell, or bootstrap page, to improve page loading speed.
order: 30
---


= Modifying the Bootstrap Page at Runtime

== Application Shell [[application-shell]]

The link:https://developers.google.com/web/fundamentals/architecture/app-shell[application shell model] aims to make your website faster by loading the 'important' parts of the web page first, so improving the user experience. The key to this is to deliver the minimum HTML, CSS and JavaScript required to display the user interface on the first visit, and eventually cache it for use on subsequent revisits.

The _Application Shell_ in Vaadin is also known as the _Bootstrap Page_, or [filename]`index.html`.

== Modifying the Application Shell

In Vaadin 15 and later, the developer has full control of the contents of [filename]`index.html`.
You can modify it in various ways:

. On the client side, by editing [filename]`frontend/index.html` when the content is static, for instance the `<viewport>` tag.
. On the server side, for changes that require some dynamic server content, or when Java syntax is preferred; for example, making the application installable by enabling the `@PWA` built-in feature.
- Implement [interfacename]`AppShellConfigurator` for cases covered by the [classname]`AppShellSettings` API, or by annotations.
- Configure an [interfacename]`IndexHtmlRequestListener` for advanced cases that modify the document structure.

== Customizing the Application Shell Template

The Vaadin servlet uses the [filename]`frontend/index.html` file as a template to generate the bootstrap page response.
The servlet processes the template and injects the following information:

  - `<base href='./relative/to/root'>`: Vaadin calculates the relative path from the current request path to the root path of the application.
  That's required for relative links in view templates to work correctly.

  - Bundled script: Vaadin automatically adds the bundled and optimized script generated from the [filename]`frontend/index.ts` file.
  It uses a pre-configured https://vitejs.dev/[Vite] instance that's included together with `vaadin-maven-plugin` as a module bundler.
  Therefore, the [filename]`frontend/index.html` template doesn't need to include the [filename]`index.ts` (or [filename]`index.js`) script explicitly.

.You can change the [filename]`frontend` directory path
[TIP]
The `frontend` directory path can be changed by providing the property `vaadin.frontend.frontend.folder` when running the Maven goals `prepare-frontend` or `build-frontend` from `vaadin-maven-plugin`.

=== Default Bootstrap Template and Entry Point [[default-bootstrap-template-and-entry-point]]

If the [filename]`index.html` or [filename]`index.ts` files in the frontend folder are missing, `vaadin-maven-plugin` generates a default corresponding file in the [filename]`target` folder.
In that case the application uses server-side routing only.
You can take control of these files by moving them into the [filename]`frontend` folder.
By default these files look similar to the following:

.Default `index.html`
[source,html]
----
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body, #outlet {
      height: 100vh;
      width: 100vw;
      margin: 0;
    }
  </style>
  <!-- index.ts is included here automatically (either by the dev server or during the build) -->
</head>
<body>
  <!-- vaadin-router in index.ts needs an outlet for displaying the views -->
  <div id="outlet"></div>
</body>
</html>
----

.Default `index.ts` [[default-index-ts]]
[source,typescript]
----
// import Vaadin client-router to handle client-side and server-side navigation
import { Router } from '@vaadin/router';

// import Flow module to enable navigation to Vaadin server-side views
import { Flow } from '@vaadin/flow-frontend';

const {serverSideRoutes} = new Flow({
  imports: () => import('../target/frontend/generated-flow-imports')
});

const routes = [
  // for client-side, place routes below (more info https://hilla.dev/docs/routing)

  // for server-side, the next magic line sends all unmatched routes:
  ...serverSideRoutes // IMPORTANT: this must be the last entry in the array
];

// Vaadin router needs an outlet in the index.html page to display views
export const router = new Router(document.querySelector('#outlet'));
router.setRoutes(routes);
----

This is the best place to customize the application shell, for example to put an analytics tag in the page.

.index.html
[source,xml]
----
...
<head>
  <title>My App</title>
</head>
<body>
  ...
  <!-- Google Analytics -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-XXXXX-Y', 'auto');
    ga('send', 'my-app-bootstrap');
  </script>
</body>
----


== Customizing the Application Shell at Runtime

=== The AppShellConfigurator Interface [[application-shell-configurator]]

In Java code, when adding dynamic content during the bootstrap process, use the [interfacename]`AppShellConfigurator` marker interface rather than editing the [filename]`index.html`.

[NOTE]
There must be a single application shell for the entire Vaadin application, so that no more than one class can implement [interfacename]`AppShellConfigurator`.
In the case of a multimodule application, the class implementing the AppShellConfigurator interface needs to be in the main module.

[NOTE]
[interfacename]`AppShellConfigurator` replaces the obsolete [interfacename]`PageConfigurator` interface.

==== The AppShellConfigurator.configurePage() Method

Override [methodname]`configurePage()` to add content to the [filename]`index.html` template by calling the following [classname]`AppShellSettings` methods:

- [methodname]`AppShellSettings.setViewport()` to set the viewport value; this replaces the viewport present in the [filename]`index.html` template.
- [methodname]`AppShellSettings.setPageTitle()` to set the initial page title; this replaces the template title tag.
- [methodname]`AppShellSettings.setBodySize()` to configure the body width and height values.
- [methodname]`AppShellSettings.addMetaTag()` to append meta tags to the head.
- [methodname]`AppShellSettings.addInlineFromFile()` to include content from resource files.
- [methodname]`AppShellSettings.addInlineWithContents()` to add arbitrary content.
- [methodname]`AppShellSettings.addLink()` to add links to the head.
- [methodname]`AppShellSettings.addFavIcon()` to configure the favicon.
- [methodname]`AppShellSettings.getLoadingIndicatorConfiguration()` to configure a loading indicator when legacy bootstrapping is used (deprecated; see the details after the code example).
- [methodname]`AppShellSettings.getReconnectDialogConfiguration()` to configure the reconnect dialog when legacy bootstrapping is used (deprecated; see the details after the code example).
- [methodname]`AppShellSettings.getPushConfiguration()` to customize the push mechanism when legacy bootstrapping is used (deprecated; see the details after the code example).

[source,java]
----
public class AppShell implements AppShellConfigurator {

  @Override
  public void configurePage(AppShellSettings settings) {
    settings.setViewport("width=device-width, initial-scale=1");
    settings.setPageTitle("A cool vaadin app");
    settings.setBodySize("100vw", "100vh");
    settings.addMetaTag("author", "bunny");
    settings.addFavIcon("icon", "icons/icon-192.png", "192x192");
    settings.addLink("shortcut icon", "icons/favicon.ico");

    settings.addInlineFromFile(
            TargetElement.BODY,
            Position.APPEND,
            "custom.html",
            Wrapping.AUTOMATIC);
    settings.addInlineWithContents(Position.PREPEND,
            "console.log(\"foo\");", Wrapping.JAVASCRIPT);
  }
}
----


[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/flow/advanced/bootstrap/ServiceListener.java[tags=snippet]
----

==== Java Annotations[[java-annotations]]

Vaadin provides a set of annotations to modify the application shell.
However, in Vaadin 15, unlike in previous versions, these annotations must be placed in the application shell class.

- `@Viewport` to set the viewport value.
- `@PageTitle` to set the initial page title.
- `@BodySize` to configure the body size.
- `@Meta` to append meta tags to the head.
- `@Inline` to include content from resource files in the [filename]`index.html`.
- `@PWA` to define application PWA properties.
- `@Push` to configure server push.

[source,java]
----
@Viewport("width=device-width, initial-scale=1")
@PageTitle("A cool vaadin app")
@BodySize(height = "100vh", width = "100vw")
@Meta(name = "author", content = "bunny")
@Inline(wrapping = Wrapping.AUTOMATIC,
        position = Position.APPEND,
        target = TargetElement.BODY,
        value = "custom.html")
@PWA(name = "Cool Vaadin App", shortName = "my-app")
@Push(value = PushMode.MANUAL, transport = Transport.WEBSOCKET)
public class AppShell implements AppShellConfigurator {
}
----

[NOTE]
Modifications in [methodname]`AppShellConfigurator.configurePage()` have priority over the equivalent annotations.

[NOTE]
Annotations don't cover all the cases that can be achieved when overriding the [methodname]`AppShellConfigurator.configurePage()` method.

=== The IndexHtmlRequestListener Interface [[IndexHtmlRequestListener-interface]]

For advanced cases not covered in the previous section, content can be modified via an [interfacename]`IndexHtmlRequestListener`.

An implementation of the listener should be added via a [classname]`ServiceInitEvent` when a [classname]`VaadinService` is initialized.
See the <<../advanced/service-init-listener#,ServiceInitListener tutorial>> for details of using Vaadin [classname]`ServiceInitListeners`.

The following example changes the body class dynamically:

[source,java]
----
public class MyIndexHtmlRequestListener implements
        IndexHtmlRequestListener {

    @Override
    public void modifyIndexHtmlResponse(
            IndexHtmlResponse indexHtmlResponse) {

        Document document = indexHtmlResponse.getDocument();
        Element body = document.body();
        body.classNames(computeBodyClassNames());
    }

    private Set<String> computeBodyClassNames() {
        // Introduce some logic to dynamically change the body class
        return Collections.singleton("my-className");
    }
}
----

This can also be achieved using a servlet container deployment property with the name `useDeprecatedV14Bootstrapping`.
Note, however, that this option is only supported if webpack is used as the frontend build tool and not if the application uses Vite (which is the default).
webpack can be enabled using its associated feature flag.
Learn more about how to enable it <<{articles}/configuration/live-reload#webpack-feature-flag, here>>.


[discussion-id]`38A2B3F1-CC6B-45DF-8CB8-9DEF23BA53B0`

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++
