extends: conditional
message: "'%s' has no definition."
level: warning
scope: text
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\b([A-Z]{3,5})\b'
second: '(?:\b[A-Z][a-z]+ )+\(([A-Z]{3,5})\)'
# ... with the exception of these:
exceptions:
  - ACME
  - AJAX
  - AJP
  - AKS
  - ANSI
  - API
  - ARIA
  - BOM
  - ASCII
  - AWT
  - CDI
  - CEO
  - CLI
  - CPU
  - CRUD
  - CSP
  - CSS
  - CSV
  - CVSS
  - DAU
  - DNS
  - DOM
  - DPI
  - DTO
  - ESC
  - EKS
  - EPSG
  - EPUB
  - FAQ
  - FDO
  - GET
  - GIF
  - GMT
  - GPS
  - GPU
  - GUI
  - HTML
  - HTTP
  - HTTPD
  - HTTPS
  - IBM
  - IDE
  - IDEA
  - ISO
  - JAR
  - JDBC
  - JDK
  - JNL
  - JOOQ
  - JPA
  - JRE
  - JSF
  - JSON
  - JSP
  - JSX
  - JVM
  - JWT
  - LLM
  - MCP
  - MDN
  - MFA
  - MIME
  - MPR
  - MTA
  - MVC
  - MVN
  - NAT
  - NGINX
  - OCR
  - OSV
  - OWASP
  - PATH
  - PDF
  - PHP
  - PNG
  - POJO
  - POM
  - POST
  - RAM
  - RFC
  - SAP
  - SBOM
  - SDK
  - SPA
  - SPI
  - SQL
  - SSH
  - SSL
  - SSO
  - SVG
  - TCP
  - TEST
  - TLS
  - TSX
  - TXT
  - REST
  - UIDL
  - URI
  - URL
  - USB
  - UTF
  - UUID
  - WAR
  - WCAG
  - XML
  - YAML
  - ZIP
