extends: conditional
message: "'%s' has no definition."
link: https://vaadin.com/docs/latest/contributing-docs/style-guidelines/#definitions-of-abbreviations
level: warning
scope: text
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\b([A-Z]{3,5})\b'
second: '(?:\b[A-Z][a-z]+ )+\(([A-Z]{3,5})\)'
# ... with the exception of these:
exceptions:
  - API
  - ASCII
  - CLI
  - CPU
  - CRUD
  - CSS
  - CSV
  - DOM
  - FAQ
  - GET
  - GIF
  - GUI
  - HTML
  - HTTP
  - HTTPS
  - IDE
  - JAR
  - JDBC
  - JDK
  - JPA
  - JSON
  - JVM
  - JWT
  - LDAP
  - PATH
  - PDF
  - PNG
  - POST
  - SQL
  - SSH
  - SSL
  - SVG
  - TCP
  - REST
  - URI
  - URL
  - UTF
  - XML
