extends: conditional
message: "'%s' has no definition."
link: https://vaadin.com/docs/latest/contributing-docs/style-guide/grammar/#abbreviations
level: warning
scope: text
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\b([A-Z]{3,5})\b'
second: '(?:\b[A-Z][a-z]+ )+\(([A-Z]{3,5})\)'
# ... with the exception of these:
exceptions:
  - AJAX
  - API
  - ARIA
  - SAP
  - ASCII
  - CDI
  - CEO
  - CLI
  - CPU
  - CRUD
  - CSS
  - CSV
  - DOM
  - DPI
  - DTO
  - EPSG
  - EPUB
  - FAQ
  - GET
  - GIF
  - GMT
  - GPS
  - GPU
  - GUI
  - HTML
  - HTTP
  - HTTPS
  - IBM
  - IDE
  - IDEA
  - ISO
  - JAR
  - JDBC
  - JDK
  - JPA
  - JRE
  - JSF
  - JSON
  - JSP
  - JSX
  - JVM
  - JWT
  - MDN
  - MIME
  - MPR
  - PATH
  - PDF
  - PHP
  - PNG
  - POJO
  - POST
  - RAM
  - RFC
  - SDK
  - SQL
  - SSH
  - SSL
  - SSO
  - SVG
  - TCP
  - TEST
  - TLS
  - REST
  - URI
  - URL
  - USB
  - UTF
  - WAR
  - XML
  - YAML
  - ZIP
