# NOTE: The annotation appears two lines above the offending admonition (Vale limitation)
extends: existence
message: 'Admonitions should have a title.'
link: https://vaadin.com/docs/contributing/docs/styleguide#admonitions
level: suggestion
scope: raw
nonword: true
tokens:
  - '\n\n\[?(?:NOTE|TIP|CAUTION|WARNING|IMPORTANT)[:\]]\s'
