extends: occurrence
message: 'Avoid using more than 3 admonitions per article.'
link: https://vaadin.com/docs/contributing/docs/styleguide#admonitions
level: suggestion
scope: raw
ignorecase: false
max: 3
token: '\[(?:NOTE|TIP|WARNING|CAUTION|IMPORTANT)\]\n|(?:NOTE: |TIP: |WARNING: |CAUTION: |IMPORTANT: )'
