# NOTE: The annotation appears two lines above the offending admonition (Vale limitation)
extends: existence
message: 'Admonitions should have a title.'
level: warning
scope: raw
nonword: true
tokens:
  - '\n\n\[?(?:NOTE|TIP|CAUTION|WARNING|IMPORTANT)[:\]]\s'
