extends: occurrence
message: 'Avoid using more than 3 admonitions per article.'
link: https://vaadin.com/docs/latest/contributing-docs/style-guidelines/#admonitions
level: warning
scope: raw
ignorecase: false
max: 3
token: '\[(?:NOTE|TIP|WARNING|CAUTION|IMPORTANT)\]\n|(?:NOTE: |TIP: |WARNING: |CAUTION: |IMPORTANT: )'
