extends: existence
message: Use 'a.m.' or 'p.m.' (preceded by a space).
link: https://vaadin.com/docs/latest/contributing-docs/style-guide/word-list/#a-m-p-m
level: warning
nonword: true
tokens:
  - '\d{1,2} ?[AP]M'
  - '\d{1,2} ?[ap]m'
  - '\d{1,2}[aApP]\.[mM]\.'
