extends: substitution
message: "Use '%s' instead of '%s'"
level: warning
ignorecase: false
# swap maps tokens in form of bad: good
swap:
  AppLayout: App Layout
  AvatarGroup: Avatar Group
  CollaborationAvatarGroup: Collaboration Avatar Group
  BigDecimalField: BigDecimal Field
  Crud: CRUD
  CheckBox: Checkbox
  CheckboxGroup: Checkbox Group
  CheckBoxGroup: Checkbox Group
  ComboBox: Combo Box
  ConfirmDialog: Confirm Dialog
  ContextMenu: Context Menu
  CookieConsent: Cookie Consent
  CustomField: Custom Field
  DatePicker: Date Picker
  DateTimePicker: Date Time Picker
  EmailField: Email Field
  FormLayout: Form Layout
  GridPro: Grid Pro
  Grid PRO: Grid Pro
  Pro Grid: Grid Pro
  ProGrid: Grid Pro
  ListBox: List Box
  MenuBar: Menu Bar
  NumberField: Number Field
  PasswordField: Password Field
  ProgressBar: Progress Bar
  RadioButton: Radio Button
  RadioButtonGroup: Radio Button Group
  RadioButton Group: Radio Button Group
  RadioGroup: Radio Button Group
  Radio Group: Radio Button Group
  RichTextEditor: Rich Text Editor
  SplitLayout: Split Layout
  TextArea: Text Area
  TextField: Text Field
  TimePicker: Time Picker
