extends: existence
message: "Don't use absolute URLs for cross references within documentation."
link: https://vaadin.com/docs/contributing/docs/styleguide/#xrefs
nonword: true
level: error
scope: raw
ignorecase: true
# The only accepted case is 'link:/docs/...' which can be used to link across documentation versions
tokens:
  - xref:https?:\/\/hilla\.dev\/docs.*?(?:\s|\[)
  - xref:\/docs.*?(?:\s|\[)
  - <<https?:\/\/hilla\.dev\/docs.*?(?:,)
  - <<\/docs.*?(?:,)
  - https?:\/\/hilla\.dev\/docs.*?(?:\s|\[)
  - link:https?:\/\/hilla\.dev\/docs.*?(?:\s|\[)
