extends: existence
message: 'Use cross references when linking within documentation.'
link: https://vaadin.com/docs/latest/guide/contributing-docs/formatting/#xrefs
nonword: true
level: error
scope: raw
ignorecase: true
# For some reason, 'http' in accept.txt cancels out this check if we use 'http' in full
tokens:
  - ttps?:\/\/vaadin\.com\/docs.*?(?:\s|\[)
