extends: existence
message: "In general, use American spelling instead of '%s'."
link: https://vaadin.com/docs/contributing/docs/styleguide#english
ignorecase: true
level: warning
tokens:
  - '(?:\w+)nised?'
  - '(?:\w+)logue'
