extends: existence
message: 'Avoid using exclamation points in text.'
link: https://vaadin.com/docs/latest/contributing-docs/style-guide/style/#exclamation-mark
nonword: true
level: warning
tokens:
  - '\w!(?:\s|$)'
