extends: existence
message: "Don't use '%s' as a gender-neutral pronoun."
link: https://vaadin.com/docs/latest/contributing-docs/style-guide/word-list/#he-she-they
level: error
ignorecase: true
tokens:
  - he/she
  - s/he
  - \(s\)he
