extends: existence
message: "Don't use rich formatting in headings (bold, italic, monospace)"
nonword: true
level: error
scope: raw
tokens:
  - = .*?\*{1,2}(.*?)\*{1,2}
  - = .*?_(.*?)_.*
  - = .*?`(.*?)`.*
