extends: existence
message: "Don't use rich formatting in headings (bold, italic, monospace)."
link: https://vaadin.com/docs/latest/contributing-docs/style-guidelines/#formatting-in-headings
nonword: true
level: error
scope: raw
tokens:
  - ^={1,6} .*?\*{1,2}(.*?)\*{1,2}
  - ^={1,6} .*?_(.*?)_.*
  - ^={1,6} .*?\x60(.*?)\x60.*
