extends: capitalization
message: "'%s' should be in sentence case."
link: https://vaadin.com/docs/latest/contributing-docs/style-guide/punctuation#headings
level: warning
scope: heading
# $title, $sentence, $lower, $upper, or a pattern.
match: $title
style: Chicago # AP or Chicago; only applies when match is set to $title.
