extends: existence
message: "Don't use rich formatting in headings (bold or italic)."
link: https://vaadin.com/docs/contributing/docs/styleguide#headings
nonword: true
level: error
scope: raw
tokens:
  - ^={1,6} .*?\*{1,2}(.*?)\*{1,2}
  - ^={1,6} .*?_(.*?)_.*
  # Allow monospace formatting in headings
  # - ^={1,6} .*?\x60(.*?)\x60.*
