extends: capitalization
message: "'%s' should be in sentence case."
link: https://vaadin.com/docs/latest/contributing-docs/style-guide/punctuation#headings
level: warning
scope: heading
# $title, $sentence, $lower, $upper, or a pattern.
match: $sentence
# style: Chicago # AP or Chicago; only applies when match is set to $title.
exceptions:
  # Product names which should not trigger the rule
  - App Layout
  - Avatar Group
  - Collaboration Avatar Group
  - Collaboration Binder
  - Collaboration Kit
  - BigDecimal Field
  - CRUD
  - Checkbox
  - Checkbox Group
  - Combo Box
  - Confirm Dialog
  - Context Menu
  - Cookie Consent
  - Custom Field
  - Date Picker
  - Date Time Picker
  - Email Field
  - Form Layout
  - Grid Pro
  - List Box
  - Lumo
  - Menu Bar
  - Message Input
  - Message List
  - Multiplatform Runtime
  - Number Field
  - Observability Kit
  - Password Field
  - Progress Bar
  - Radio Button
  - Radio Button Group
  - Rich Text Editor
  - Split Layout
  - Tab Sheet
  - TestBench
  - Text Area
  - Text Field
  - Time Picker
  - Tooltip
  - Tree Grid
  - Vaadin Designer
  - Virtual List
