extends: capitalization
message: "'%s' should be in title case."
link: https://vaadin.com/docs/latest/guide/contributing-docs/style-guidelines/#title-case
level: error
scope: heading
# $title, $sentence, $lower, $upper, or a pattern.
match: $title
style: AP # AP or Chicago; only applies when match is set to $title.
