extends: capitalization
message: "'%s' should be in title case."
link: https://vaadin.com/docs/contributing/docs/styleguide#headings
level: warning
scope: heading
# $title, $sentence, $lower, $upper, or a pattern.
match: $title
style: Chicago # AP or Chicago; only applies when match is set to $title.
