extends: existence
message: "Don't put a period at the end of a heading."
link: https://vaadin.com/docs/latest/contributing-docs/style-guide/punctuation/#headings
nonword: true
level: error
scope: heading
action:
  name: edit
  params:
    - remove
    - '.'
tokens:
  - '[a-z0-9][.]\s*$'
