extends: existence
message: "'%s' may be insensitive, try not to use it. It’s probably not that simple. Even if it is, you probably don’t need to specifically say it."
link: https://css-tricks.com/words-avoid-educational-writing/
ignorecase: true
level: warning
tokens:
  - just
  - simple
