extends: existence
message: "Avoid using '%s'. It may be insensitive."
link: https://css-tricks.com/words-avoid-educational-writing/
ignorecase: true
level: warning
tokens:
  - just
  - simply
  - obviously
