extends: substitution
message: "Use '%s' instead of '%s', surrounded by commas."
link: https://vaadin.com/docs/latest/contributing-docs/style-guide/style/#latin-abbreviations
ignorecase: true
level: warning
nonword: true
action:
  name: replace
swap:
  '\b(?:eg|e\.g\.)[\s,]': for example
  '\b(?:ie|i\.e\.)[\s,]': that is
exceptions:
  - IE
