extends: substitution
message: "Use '%s' instead of '%s', surrounded by commas."
link: https://vaadin.com/docs/contributing/docs/styleguide#latin-abbreviations
ignorecase: true
level: suggestion
nonword: true
action:
  name: replace
swap:
  '\b(?:eg|e\.g\.)[\s,]': for example
  '\b(?:ie|i\.e\.)[\s,]': that is
exceptions:
  - IE
