extends: existence
message: 'Write one sentence per line.'
link: https://vaadin.com/docs/latest/contributing-docs/style-guidelines/#source.one-line-per-sentence
nonword: true
level: warning
scope: paragraph
tokens:
  - '\S\. \S'
