extends: existence
message: 'Write one sentence per line.'
link: https://vaadin.com/docs/latest/guide/contributing-docs/style-guidelines/#source.one-line-per-sentence
nonword: true
level: warning
scope: paragraph
tokens:
  - '[^\d\n\r][.!?].*[^\n\r]'
  - '(\d\.)+ +[^\n\r]+'
