extends: existence
message: "Avoid using plurals in parentheses such as in '%s'."
link: https://vaadin.com/docs/latest/contributing-docs/style-guide/style/#plurals
level: warning
nonword: true
action:
  name: edit
  params:
    - remove
    - '(s)'
tokens:
  - '\b\w+\(s\)'
