extends: existence
message: "Use the Oxford comma in '%s'."
link: https://vaadin.com/docs/contributing/docs/styleguide#lists
scope: sentence
level: warning
nonword: true
tokens:
  - '(?:[^\s,]+,){1,} \w+ (?:and|or) \w+[.?!]'
