extends: existence
message: "Use the Oxford comma in '%s'."
link: https://vaadin.com/docs/latest/contributing-docs/style-guide/punctuation/#punctuation.oxford-comma
scope: sentence
level: warning
nonword: true
tokens:
  - '(?:[^\s,]+,){1,} \w+ (?:and|or) \w+[.?!]'
