extends: substitution
message: "Use '%s' instead of '%s'."
link: https://vaadin.com/docs/contributing/docs/styleguide#product-names
level: error
ignorecase: false
# swap maps tokens in form of bad: good
swap:
  AppLayout: App Layout
  AvatarGroup: Avatar Group
  CollaborationAvatarGroup: Collaboration Avatar Group
  (?:[Cc])ollaboration ?(?:[Ee])ngine: Collaboration Kit
  (?:[Cc])ollaboration ?(?:[Kk])it: Collaboration Kit
  BigDecimalField: BigDecimal Field
  Crud: CRUD
  CheckBox: Checkbox
  CheckboxGroup: Checkbox Group
  CheckBoxGroup: Checkbox Group
  ComboBox: Combo Box
  ConfirmDialog: Confirm Dialog
  ContextMenu: Context Menu
  CookieConsent: Cookie Consent
  CustomField: Custom Field
  DatePicker: Date Picker
  DateTimePicker: Date Time Picker
  EmailField: Email Field
  FormLayout: Form Layout
  GridPro: Grid Pro
  Grid PRO: Grid Pro
  Pro Grid: Grid Pro
  ProGrid: Grid Pro
  ListBox: List Box
  lumo: Lumo
  MenuBar: Menu Bar
  NumberField: Number Field
  PasswordField: Password Field
  ProgressBar: Progress Bar
  RadioButton: Radio Button
  RadioButtonGroup: Radio Button Group
  RadioButton Group: Radio Button Group
  RadioGroup: Radio Button Group
  Radio Group: Radio Button Group
  RichTextEditor: Rich Text Editor
  SplitLayout: Split Layout
  TabSheet: Tab Sheet
  Testbench: TestBench
  TextArea: Text Area
  TextField: Text Field
  TimePicker: Time Picker
  TreeGrid: Tree Grid
  Vaadin designer: Vaadin Designer
  Vaadin flow: Vaadin Flow
  Vaadin fusion: Vaadin Fusion
  Multi-Platform Runtime: Multiplatform Runtime
  (?:[^\s]*) ?Vaadin [pP]latform: the Vaadin platform|The Vaadin platform
  Vaadin Components: Vaadin components
  Vaadin Framework: Vaadin (or "Vaadin 7 and/or 8" if needed)
  Maven (?:Plugin|[pP]lug-in|[aA]dd-?on): Maven plugin
  Gradle (?:Plugin|[pP]lug-in|[aA]dd-?on): Gradle plugin
  Quarkus (?:Plugin|[pP]lug-in|[aA]dd-?on): Quarkus plugin
  Spring (?:[pP]lug-?in|Add-?on|addon): Spring add-on
  CDI (?:[pP]lug-?in|Add-?on|addon): CDI add-on
  the Observability Kit (?:Java [aA]gent|[aA]gent): Observability Kit
