extends: existence
message: 'Use an en dash in a range of numbers.'
link: https://vaadin.com/docs/latest/contributing-docs/style-guide/punctuation/#en-dash
nonword: true
level: warning
action:
  name: edit
  params:
    - replace
    - '-'
    - '–'
tokens:
  - '\b\d+\s?[-]\s?\d+\b'
