extends: substitution
message: "Prefer '%s' over '%s' when linking to another documentation resource."
level: suggestion
ignorecase: true
action:
  name: replace
swap:
  refer to: see
  please refer to: see
  check: see
  please check: see
