extends: substitution
message: "Prefer 'see' over 'refer to' or 'check out' when linking to another documentation resource."
level: suggestion
ignorecase: true
scope: raw
action:
  name: replace
swap:
  'refer to(?: the)? (?:<<|link|xref|https?)': see
  'check(?: out)?(?: the)? (?:<<|link|xref|https?)': see
  'check this (?:<<|link|xref|https?)': see
