extends: existence
message: 'Use semicolons judiciously, and try to simplify this sentence.'
link: https://vaadin.com/docs/latest/contributing-docs/style-guide/punctuation/#punctuation.semi-colon
nonword: true
scope: sentence
level: suggestion
tokens:
  - ';'
