extends: existence
message: "Don't use internet slang abbreviations such as '%s'."
link: 'https://developers.google.com/style/abbreviations'
ignorecase: true
level: warning
tokens:
  - 'tl;dr'
  - ymmv
  - rtfm
  - imo
  - fwiw
