extends: substitution
message: "Don't start a sentence with 'So'."
level: warning
scope: sentence
swap:
  # Allow 'So far'
  '(?:[;-]\s)so[\s,]\W|\bSo,?\s?\w+': 'So far'
exceptions:
 - Sometimes
 - Some