extends: existence
message: "Avoid writing source code inside Asciidoc content."
nonword: true
level: warning
scope: raw
tokens:
ignorecase: true
# Checks for the presence of the ; character within source code blocks
# (java, typescript, javascript, css, html), only if the character is
# followed by a white space character. Asciidoc include directive can
# use ; to delimit multiple tag names
tokens:
  - '(?s)(\[source,\s?(?:java|typescript|javascript|css|html).*?\]\n----\s+.*?;\s.*?\n----)'
