extends: existence
message: "Avoid using inline source code blocks, prefer including code snippets from source files"
nonword: true
level: warning
scope: raw
tokens:
ignorecase: true
tokens:
  - '(?s)\[source,\s?(?:java|typescript|javascript|css|html).*?\]\n----\s+.*?[<>();].*?\n----'
