extends: existence
message: "Prefer embedding source code examples from under the 'frontend' and 'src' folders, using the include::[] directive."
link: https://vaadin.com/docs/latest/contributing-docs/formatting/#code.include
nonword: true
level: suggestion
scope: raw
tokens:
ignorecase: true
# Checks for the presence of the ; character within source code blocks
# (java, typescript, javascript, css, html), only if the character is
# followed by a white space character. Asciidoc include directive can
# use ; to delimit multiple tag names
tokens:
  - '(?s)(\[source,\s?(?:java|typescript|javascript|css|html).*?\]\n----\s+.*?;\s.*?\n----)'
