extends: existence
message: "Use 'front-end' and 'back-end' when used as adjectives."
level: warning
ignorecase: true
tokens:
  # Keep in sync with Terms.yml
  - '(?:frontend|backend) (?:code|dependency|dependencies|development|developers?|teams?|sources?|resources?|files?|build|states?|tests?|testing|servers?|proxy|proxies|changes?|bundle|reloading|directory|directories|packages?|modules?|installation|compilation|customizations?|re-customizations?)'
