extends: substitution
message: "Prefer '%s' over '%s'."
level: warning
ignorecase: true
action:
  name: replace
swap:
  '(?:cell ?phone|smart ?phone)': phone|mobile phone
  '(?:kill|terminate|abort)': stop|exit|cancel|end
  '(?:file ?path|path ?name)': path
  '(?:e-mail|Email|E-mail)': email
  '(?:ok|Okay)': OK|okay
  '(?:WiFi|wifi)': Wi-Fi
  '3\-D': 3D
  Ajax: AJAX
  apps: applications
  approx\.: approximately
  #  back[-|\s]end: backend
  cellular data: mobile data
  cellular network: mobile network
  dropdown: overlay
  #  front[-|\s]end: frontend
  grayed-out: unavailable
  NPM: npm
  open-source: open source
  regex: regular expression
  repo: repository
  timeframe: time frame
  separators?: divider
  stylesheet: style sheet
  stylesheets: style sheets
