extends: substitution
message: "Prefer '%s' over '%s'."
level: warning
ignorecase: true
action:
  name: replace
swap:
  dropdown: overlay
  timeframe: time frame
  repo: repository
  app: application
