extends: substitution
message: "Prefer '%s' over '%s'."
level: warning
ignorecase: true
action:
  name: replace
swap:
  '(?:cell ?phone|smart ?phone)': phone|mobile phone
  '(?:kill|terminate|abort)': stop|exit|cancel|end
  '(?:file ?path|path ?name)': path
  '(?:[eE]-mail)': email
  '(?:ok|Okay)': OK|okay
  '(?:WiFi|wifi)': Wi-Fi
  '3\-D': 3D
  Ajax: AJAX
  apps: applications
  approx\.: approximately
  #  back[-|\s]end: backend # TODO flag "backend code|dependencies|development|source|resources|files|build|state"
  cellular data: mobile data
  cellular network: mobile network
  dropdown: drop-down
  #  front[-|\s]end: frontend # TODO flag "frontend code|dependencies|development|source|resources|files|build|state"
  grayed-out: unavailable
  NPM: npm
  open-source: open source
  regex: regular expression
  repo: repository
  timeframe: time frame
  separator: divider
  separators: dividers
  stylesheet: style sheet
  stylesheets: style sheets
  web driver: WebDriver
  web drivers: WebDrivers
