# Need to keep this as a separate rule in order to allow for 'App Layout' and 'Google App Engine'
extends: substitution
message: "Prefer 'application' over 'app'."
level: warning
ignorecase: true
swap:
  '[aA]pp (?:[^\s]*)': 'App (Layout|Engine)'
