# Need to keep this as a separate rule in order to allow for 'app layout'
extends: substitution
message: "Prefer 'application' over 'app'."
level: warning
ignorecase: true
swap:
  '[aA]pp (?:[^\s]*)': 'App Layout'
