extends: substitution
message: "Prefer '%s' over '%s'."
level: warning
ignorecase: true
action:
  name: replace
swap:
  dropdown: overlay
  timeframe: time frame
  repo: repository
  NPM: npm
  back[-|\s]end: backend
  front[-|\s]end: frontend
  separators?: divider
  stylesheets?: style sheet
