extends: substitution
message: "Prefer '%s' over '%s'."
level: warning
ignorecase: true
action:
  name: replace
swap:
  '(?:cell ?phone|smart ?phone)': phone|mobile phone
  '(?:kill|terminate|abort)': stop|exit|cancel|end
  '(?:[eE]-mail)': email
  '(?:ok|Okay)': OK|okay
  '(?:WiFi|wifi)': Wi-Fi
  '3\-D': 3D
  Ajax: AJAX
  apps: applications
  approx\.: approximately
  back end: backend
  # Keep in sync with Terms-FrontendBackend.yml
  'back-end(?! code| dependency| dependencies| development| developers?| teams?| sources?| resources?| files?| build| states?| tests?| testing| servers?| proxy| proxies| changes?| bundle| reloading| directory| directories| packages?| modules?| installation| customizations?| re-customizations?| compilation| services?| logic| applications?| traces?| spans?| endpoints?| tools?)': backend
  cellular data: mobile data
  cellular network: mobile network
  dropdown: drop-down
  front end: frontend
  # Keep in sync with Terms-FrontendBackend.yml
  'front-end(?! code| dependency| dependencies| development| developers?| teams?| sources?| resources?| files?| build| states?| tests?| testing| servers?| proxy| proxies| changes?| bundle| reloading| directory| directories| packages?| modules?| installation| customizations?| re-customizations?| compilation| services?| logic| applications?| traces?| spans?| endpoints?| tools?)': frontend
  grayed-out: unavailable
  NPM: npm
  # open-source: open source
  regex: regular expression
  repo: repository
  timeframe: time frame
  separator: divider
  separators: dividers
  Spring-boot: Spring Boot
  # stylesheet: style sheet
  # stylesheets: style sheets
  web driver: WebDriver
  web drivers: WebDrivers
  prerelease: pre-release
