extends: existence
message: "Put a nonbreaking space between the number and the unit in '%s' (Option+Space on macOS, Ctrl + Shift + Space on Windows)."
nonword: true
level: warning
tokens:
  - \d+(?:B|kB|MB|GB|TB)
  - \d+(?:ns|ms|s|min|h|d)(?:\s|\.)
