extends: existence
message: Consider using "Vaadin" instead. Use "the Vaadin platform" only if absolutely needed.
level: warning
ignorecase: true
vocab: false
tokens:
    - Vaadin Platform
    - the Vaadin platform
