extends: substitution
message: Don't capitalize "platform", and remember to include the definitive article ("the").
level: error
ignorecase: false
vocab: false
swap:
  Vaadin Platform: the Vaadin platform|The Vaadin platform
