extends: substitution
message: "Don't refer to a specific Vaadin version."
link: https://vaadin.com/docs/contributing/docs/styleguide#vaadin-versions
level: warning
vocab: false
swap:
  'Vaadin (?:version )?[0-9]+(?:\.[0-9]+)?': Vaadin
