extends: substitution
message: "Don't refer to a specific Vaadin version."
link: https://vaadin.com/docs/latest/contributing-docs/style-guidelines/#vaadin-versions
level: warning
swap:
  'Vaadin [0-9]{1,2}': Vaadin
