extends: substitution
message: "Don't refer to a specific Vaadin version."
link: https://github.com/vaadin/docs/wiki/Authoring-articles#indicating-new-and-deprecated-features
level: error
scope: raw
swap:
  'Vaadin [0-9]{1,2}': Vaadin
