extends: existence
message: "'%s' is a weasel word, consider removing it."
ignorecase: true
level: suggestion
action:
  name: remove
tokens:
  - absolutely
  - abnormally
  - absentmindedly
  - accidentally
  - additionally
  - adventurously
  - allegedly
  - angrily
  - anxiously
  - approximately
  - arrogantly
  - awkwardly
  - badly
  - bashfully
  - barely
  - beautifully
  - bitterly
  - bleakly
  - blindly
  - blissfully
  - boastfully
  - boldly
  - bravely
  - brightly
  - briefly
  - briskly
  - bristly
  - bubbly
  - broadly
  - busily
  - calmly
  - carefully
  - carelessly
  - cautiously
  - cheerfully
  - clearly
  - cleverly
  - closely
  - coldly
  - coaxingly
  - colorfully
  - continually
  - coolly
  - completely
  - consequently
  - correctly
  - courageously
  - crossly
  - crinkly
  - cruelly
  - crumbly
  - curiously
  - cuddly
  - currently
  - daily
  - daintily
  - daringly
  - dearly
  - deadly
  - deceivingly
  - definitely
  - deliberately
  - defiantly
  - delightfully
  - diligently
  - dimly
  - doubtfully
  - dreamily
  - dumbly
  - eagerly
  - early
  - easily
  # - elegantly # allow for word-list
  - energetically
  - enormously
  - enthusiastically
  - excitedly
  - equally
  - especially
  - eventually
  - exactly
  - exceedingly
  # - exclusively # also in ComplexWords
  - extremely
  - fairly
  - faithfully
  - fatally
  - famously
  - ferociously
  - fervently
  - fiercely
  - finally
  - fondly
  - few
  - foolishly
  - fortunately
  - frankly
  - frantically
   - freely
  - frenetically
  - frightfully
  - furiously
  - generally
  - generously
  - gently
  - giggly
  - gladly
  - gleefully
  - gracefully
  - gratefully
  - greatly
  # - greedily # allow for 'greedily match' for regex contexts
  - happily
  - hardly
  - hastily
  - healthily
  - heartily
  - heavily
  - helplessly
  - helpfully
  - honestly
  - hopelessly
  - hourly
  - hungrily
  - hurriedly
  - immediately
  - impatiently
  - inadequately
  - ingeniously
  - innocently
  - inquisitively
  - intensely
  - intently
  - interestingly
  - inwardly
  - irritably
  - jaggedly
  - jealously
  - jiggly
  - jovially
  - joyfully
  - joyously
  - jubilantly
  - judgmentally
  - justly
  - keenly
  - kiddingly
  - kindheartedly
  - knavishly
  - knowingly
  - knowledgeably
  - kindly
  - largely
  - lately
  # - lazily # OK: "to bind data lazily"
  - lightly
  - limply
  - likely
  - literally
  - lively
  - loftily
  - longingly
  - lonely
  - loosely
  - loudly
  - lovingly
  - loyally
  - luckily
  - madly
  - majestically
  # - many
  - meaningfully
  - mechanically
  - mentally
  - merrily
  - mildly
  - monthly
  - mortally
  - miserably
  - mockingly
  - mostly
  - mysteriously
  - naturally
  - nearly
  - neatly
  - nervously
  - nicely
  - nightly
  - noisily
  - normally
  - obediently
  - occasionally
  - obnoxiously
  - oddly
  - offensively
  # - only # OK: "should only be used for..."
  - openly
  - optimistically
  - overconfidently
  - painfully
  - particularly
  - patiently
  - perfectly
  - playfully
  - politely
  - poorly
  - positively
  - potentially
  - powerfully
  - presumably
  # - previously # also in ComplexWords
  - promptly
  - properly
  - punctually
  - quaintly
  - quarterly
  - queasily
  - queerly
  - questionably
  - quickly
  - quietly
  - quirkily
  - quizzically
  - rapidly
  - rarely
  - readily
  - really
  - reassuringly
  - recently
  - recklessly
  - regularly
  - remarkably
  - relatively
  - reluctantly
  - repeatedly
  - reproachfully
  - restfully
  - righteously
  - rightfully
  - rigidly
  - roughly
  - rudely
  - sadly
  - safely
  - scarcely
  - scarily
  - searchingly
  - sedately
  - seemingly
  - selfishly
  - separately
  - sensibly
  - seriously
  - shakily
  - sharply
  - sheepishly
  - shortly
  - shrilly
  - shyly
  - significantly
  - silently
  - simply
  - sleepily
  - slowly
  - smartly
  - smelly
  - smoothly
  - softly
  - solemnly
  - solidly
  - sparkly
  - speedily
  - stealthily
  - sternly
  - strictly
  - stupidly
  - substantially
  - successfully
  - suddenly
  - supposedly
  - surprisingly
  - suspiciously
  - sweetly
  - swiftly
  - sympathetically
  - tenderly
  - tensely
  - terribly
  - thankfully
  - thoroughly
  - thoughtfully
  - tightly
  - timely
  - tremendously
  - triumphantly
  - truthfully
  - ultimately
  - unabashedly
  - unaccountably
  - unbearably
  - unethically
  - unexpectedly
  - unfortunately
  - unimpressively
  - unnaturally
  - unnecessarily
  - urgently
  - usefully
  - uselessly
  - usually
  - utterly
  - vacantly
  - vaguely
  - vainly
  - valiantly
  - vastly
  - verbally
  - very
  - viciously
  - victoriously
  - violently
  - vivaciously
  - voluntarily
  - warmly
  - waverly
  - weakly
  - wearily
  - weekly
  - wetly
  - wholly
  - wildly
  - willfully
  - wisely
  - woefully
  - wonderfully
  - worldly
  - worriedly
  - wrinkly
  - yawningly
  - yearningly
  - yearly
  - yieldingly
  - youthfully
  - zealously
  - zestfully
  - zestily
