---
title: Select
layout: tabbed-page
tab-title: Usage
page-links: \
https://github.com/vaadin/vaadin-flow-components/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-select-flow}\[Flow {moduleMavenVersion:com.vaadin:vaadin-select-flow}], \
https://github.com/vaadin/vaadin-select/releases/tag/v{moduleNpmVersion:vaadin-select}\[Web Component {moduleNpmVersion:vaadin-select}]
---

= Select

// tag::description[]
Select is an input field component that allows users to choose a single value from a set of options presented in a dropdown list.
// end::description[]

[.example]
--

[source, typescript]
----
include::{root}/frontend/demo/component/select/select-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/select/SelectBasic.java[render,tags=snippet,indent=0,group=Java]
----

--

The dropdown can be opened with a click, up/down arrow keys, or by typing the initial character for one of the options.

== Separators

Separators can be used to group related options.
Use separators sparingly to avoid creating unnecessary visual clutter.

[.example]
--

[source, typescript]
----
include::{root}/frontend/demo/component/select/select-separators.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/select/SelectSeparators.java[render,tags=snippet,indent=0,group=Java]
----
--

[NOTE]
====
Please note that for large data sets it is preferable to use Combo Box instead of Select, as it allows users to filter the list of options.
====

== Disabled Items

Items can be disabled.
This prevents users from selecting them, while still showing that these items would be available for selection under different circumstances.

[.example]
--

[source, typescript]
----
include::{root}/frontend/demo/component/select/select-disabled.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/select/SelectDisabled.java[render,tags=snippet,indent=0,group=Java]
----
--

[NOTE]
====
Some assistive technologies do not announce disabled options.
====

== Placeholder

Use the placeholder feature instead of a default dummy item to provide an inline text prompt for the field.

[.example]
--

[source, typescript]
----
include::{root}/frontend/demo/component/select/select-placeholder.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/select/SelectPlaceholder.java[render,tags=snippet,indent=0,group=Java]
----
--

== Custom Item Presentation

Items can be rendered with rich content instead of plain text.
This can be useful to provide information in a more legible fashion than appending it to the item text.

[.example]
--

[source, typescript]
----
include::{root}/frontend/demo/component/select/select-presentation.ts[render,tags=snippet,indent=0,group=TypeScript]

...

include::{root}/frontend/demo/component/select/select-presentation.ts[tags=renderer,indent=0]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/select/SelectPresentation.java[render,tags=snippet,indent=0,group=Java]
----
--

== Best Practices

When applicable, set the most common choice as the default value.

[NOTE]
====
Select is an input field component, not a generic menu component.
Use the Menu Bar component to create dropdowns for actions.
====

== Related Components

|===
|Component |Usage recommendations

|<<../radio-button#,Radio Button>>|Better accessibility than Select, as all options are always visible.

|<<../combo-box#,Combo Box>>|Filterable list of options.
Appropriate for large sets of options.
Supports lazy loading entry of custom values.

|<<../list-box#,List Box>>|Scrollable inline list of options.
Supports single and multi-select.

|<<../menu-bar#,Menu Bar>>|Dropdown menus for items that trigger actions.
|===
