---
title: Setup Live Reload using HotswapAgent
order: 4
layout: page
---

= Setup Live Reload using HotswapAgent

Live Reload works seamlessly on development mode using HotswapAgent for runtime class and resource redefinition.
If you want to know more about the features of HotswapAgent, the documentation in the http://hotswapagent.org/[HotswapAgent webpage] is a good resource.

Currently, Live Reload works on HotswapAgent version 1.4.1-SNAPSHOT and newer. Since no versions of the DCEVM JDK are still bundled with these versions, a HotswapAgent override is required by including the newer HotswapAgent versions as a Java agent in your JVM options.

[NOTE]
HotswapAgent is made to run on IDEs on Debug mode only. If you would like to run HotswapAgent in Run mode an xref:a-runtime-hotswap[additional configuration] is needed.

== Step-by-step guide

. Download https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases[DCEVM JDK], unpack it and set `JAVA_HOME` to it's location. Alternatively, you can add the JDK to your IDE.
. Download https://github.com/HotswapProjects/HotswapAgent/releases[HotswapAgent 1.4.1-SNAPSHOT]
. Rename the downloaded HotswapAgent JAR to `hotswap-agent.jar`. Move it to the `lib/hotswap` directory of the unpacked DCEVM JDK. When prompted, replace the existing file.
. When using an IDE, follow setup guides available in http://hotswapagent.org/
. Depending on your project technology stack, you might have to apply <<Additional configurations>>
. Debug your Vaadin application in Dev Mode
. Navigate to any page in your application, edit a Java file in the project, recompile, and the browser will automatically reload

== Additional configurations

* [[a-runtime-hotswap]] If you want to use HotswapAgent on Run mode you must add an additional configuration parameter to the JVM options by adding `-javaagent:<path-to-hotswap-directory>/lib/hotswap/hotswap-agent.jar=autoHotswap=true`.
* If you have installed JRebel previously when using IntelliJ IDEA, the `Build project automatically` compiler option should be turned off since it might trigger HotswapAgent reloads without swapping classes properly. The ideal fix for this issue is having a fresh install of IDEA when using HotswapAgent.
* If you're running HotswapAgent using DCEVM 8 and Netbeans, adding the configuration parameter `=autoHotswap=true` might be needed for Live Reload to work. VM configuration for debugging (available at `Project Properties > Actions > Actions: Debug project > Set Properties`) should look like this `Env.MAVEN_OPTS=-XXaltjvm=dcevm -javaagent:<path-to-file>/hotswap-agent-1.4.1-SNAPSHOT.jar=autoHotswap=true`.
* When using Jetty as server set `<scanIntervalSeconds>` in your Vaadin application `pom.xml` to `0`
