---
title: Setup Live Reload using JRebel
order: 3
layout: page
---

= Setup Live Reload using JRebel

Live Reload works with JRebel allowing for code changes to affect Vaadin applications in real time, skipping rebuilds and redeploys.
More information about JRebel is available at https://www.jrebel.com/products/jrebel.

== Step-by-step guide

. Setup and activate JRebel in your favorite IDE by following the Quick Start guides available at https://www.jrebel.com/products/jrebel/learn. Use at least `2020.2.1` version which contains built-in live reload integration.
. Run your Vaadin application using the JRebel Agent
. Navigate to your Vaadin application on the browser, make and save some changes, and the browser will reload automatically

== Known issues

* At the moment, running a Vaadin application with JRebel might cause some related exceptions to be logged on the console. These can be safely ignored as no unexpected behavior will affect your application. These exeptions look like this:
+
----
JRebel: ERROR Class 'com.vaadin.flow.server.startup.RouteRegistryInitializer' could not be processed by org.zeroturnaround.jrebel.vaadin.cbp.RouteRegistryInitializerCBP@org.eclipse.jetty.webapp.WebAppClassLoader@139f1a94: org.zeroturnaround.bundled.javassist.CannotCompileException: [source error] getInstance(javax.servlet.ServletContext) not found in com.vaadin.flow.server.startup.ApplicationRouteRegistry
	at org.zeroturnaround.bundled.javassist.CtNewMethod.make(SourceFile:84)
	at org.zeroturnaround.bundled.javassist.CtNewMethod.make(SourceFile:50)
	at org.zeroturnaround.bundled.javassist.CtMethod.make(SourceFile:140)
  ...
----
