---
title: Setting Up Live Reload using JRebel
order: 3
layout: page
---

= Setting Up Live Reload using JRebel

Live Reload works with JRebel allowing for code changes to affect Vaadin applications in real time, skipping rebuilds and redeploys.
More information about JRebel is available at https://www.jrebel.com/products/jrebel.

== Step-by-step guide

. Setup and activate JRebel in your favorite IDE by following the Quick Start guides available at https://www.jrebel.com/products/jrebel/learn. Use at least `2020.2.1` version which contains built-in Live Reload integration.
. Run or debug your Vaadin application using the JRebel Agent.
. Navigate to your Vaadin application on the browser, make and save some changes, and the browser will reload automatically

== Additional configurations
* For Jetty make sure to disable resource scanning and automatic restarts (if using the Maven Plugin, omit or set `<scanIntervalSeconds>` to a value of  `0` or less).

== Current limitations
* Live Reload is currently not supported in projects using https://github.com/vaadin/cdi[Vaadin CDI] and JRebel.