---
title: Upgrading Guide
order: 900
---


= Upgrading from Vaadin 23

This guide goes through the changes you'll need to make in your applications when upgrading from Vaadin 23 to the latest version. After these changes, your application should compile, run, behave, and look the way it did before you upgraded.

.Upgrading from Earlier Version
[TIP]
See the link:/docs/v23/upgrading[previous upgrading guide] if you're upgrading from a version earlier than Vaadin 23.

Many of the breaking changes are needed because of fundamental changes in the Java platform and the major dependencies on which Vaadin relies. This includes the following:

*Servlet 6*::
Vaadin 24 is based on Servlet 6 specifications. It's compatible with Jakarta EE 10. Vaadin encapsulates the usage of the classes from `javax` and `jakarta` packages. Therefore, application code doesn't need to use servlets, directly. Nevertheless, this is still needed in various cases -- like accessing cookies, setting servlet parameters, etc.

*Spring Boot 3*::
Vaadin 24 uses the latest Spring Boot 3 and Spring Framework 6 versions. This leads to making breaking changes in Spring-based features, compared to earlier Spring-boot 2 and Spring Framework 5 versions.

*Java 17*::
Vaadin 24 requires Java 17 or later. This is dictated by Spring Framework and newer versions of application servers.


== Overview

Vaadin 24 doesn't fundamentally change how applications are developed and behave. Still, the upgrade process requires the following essential tasks and testing:

Preparation::
Upgrade the Vaadin version in the project's [filename]`pom.xml` file, checking for the latest Vaadin 24 release link:https://github.com/vaadin/platform/releases[in GitHub].

Jakarta EE 10::
Convert package names to Jakarta EE 10 namespace.

Upgrade Spring::
For Spring-based applications, upgrade to Spring Boot 3 or Spring Framework 6, depending on which is used in your project. For non-Spring applications, upgrade the application server version to one that's compatible with Jakarta EE 10.

Other Dependencies::
Upgrade third-party dependencies used in your project (e.g., Maven/Gradle plugins, libraries, frameworks) to the Jakarta and Spring-compatible versions.

Verify & Test::
Ensure your application is not using deprecated code fragments.
+
Make sure your application runs well on Java 17 runtime.
+
Verify that the front-end build works as it should with Vite since webpack is no longer supported.


== Limitations

Portlet and OSGi integrations are not included for two reasons: First, the latest Portlet 3 specification corresponds to Servlet 3, and it doesn't work with Servlet 6. Second, a Jakarta EE 10 compatible version of OSGi core runtime https://felix.apache.org/documentation/index.html[Apache Felix 8] is under development. The https://karaf.apache.org/[Apache Karaf] container is based on Apache Felix and doesn't have a Jakarta-compatible version.


== Preparation

Upgrade the Vaadin version in the [filename]`pom.xml` and [filename]`gradle.properties` files to the latest release like so:

include::{articles}/_vaadin-version.adoc[]

[.example]
--
[source,xml,subs="+attributes"]
----
<source-info group="pom.xml"></source-info>
<vaadin.version>{vaadin-version}</vaadin.version>
----
[source,properties,subs="+attributes"]
----
<source-info group="gradle.properties"></source-info>
vaadinVersion={vaadin-version}
----
--

See the link:https://github.com/vaadin/platform/releases[list of releases on GitHub] for the latest one.


== Jakarta EE 10 Namespaces

You can use the free tools, https://github.com/eclipse/transformer[Eclipse Transformer] and https://github.com/apache/tomcat-jakartaee-migration[Apache migration tool] for the package name conversion.

When applied to a project, they'll convert Java class imports, manifests, property files, and other resources to use `jakarta.*` namespace when needed. Conversion instructions are in each tool's [filename]`README` file.

The last versions of IntelliJ IDEA offer https://www.jetbrains.com/help/idea/2022.2/migrate.html[migration refactoring] tools, including a Java EE to Jakarta EE package converter. Make sure that the Jakarta specifications in your project have the correct versions. Refer to the full list of https://jakarta.ee/release/10/[Jakarta EE 10 specifications] for more information.

Below are a few examples:

.pom.xml
[source,xml]
----
<dependency>
    <groupId>jakarta.servlet</groupId>
    <artifactId>jakarta.servlet-api</artifactId>
    <version>6.0.0</version>
</dependency>
<dependency>
    <groupId>jakarta.annotation</groupId>
    <artifactId>jakarta.annotation-api</artifactId>
    <version>2.1.0</version>
</dependency>
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>4.0.0</version>
</dependency>
<dependency>
    <groupId>jakarta.enterprise.concurrent</groupId>
    <artifactId>jakarta.enterprise.concurrent-api</artifactId>
    <version>3.0.0</version>
</dependency>
----


== Spring Upgrade Instructions

Spring Boot 3 and Spring Framework 6 don't fundamentally change how applications are developed. The main changes are regarding Jakarta EE 10 namespaces and supported products, the Java version, and the dependency upgrades and deprecations.

Spring Boot 3 and Framework 6 use new versions of third-party dependencies: Hibernate 6, Hibernate Validator 8, servlet containers (e.g., Jetty 11, Tomcat 10.1), and many others. Spring has available the https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide[Dedicated Migration Guide for Spring-boot 3.0] and the https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x[Upgrading to Spring Framework 6.x Guide]. You may want to consult them.

To browse a full list of changes, see the https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes[Spring-boot 3.0 Release Notes] and the https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-6.x[What's New in Spring Framework 6.x] page.

Below is a general overview of the changes needed for Spring-based Vaadin applications:

*Upgrade Spring to Latest*

You'll need to upgrade Spring to the latest versions, including the starter parent dependency:

.pom.xml
[source,xml]
----
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.0.0</version>
</parent>
----

*Deprecation*

The deprecated `VaadinWebSecurityConfigurerAdapter` class was removed since Spring no longer has the `WebSecurityConfigurerAdapter` class. Use instead the `VaadinWebSecurity` base class for your security configuration. Below is an example of this:

[source,java]
----
@EnableWebSecurity
@Configuration
public class SecurityConfig extends VaadinWebSecurity {

    @Override
    public void configure(HttpSecurity http) throws Exception {
        // Delegating the responsibility of general configurations
        // of http security to the super class. It's configuring
        // the followings: Vaadin's CSRF protection by ignoring
        // framework's internal requests, default request cache,
        // ignoring public views annotated with @AnonymousAllowed,
        // restricting access to other views/endpoints, and enabling
        // ViewAccessChecker authorization.
        // You can add any possible extra configurations of your own
        // here -- the following is just an example:

        // http.rememberMe().alwaysRemember(false);

        // Configure your static resources with public access before calling
        // super.configure(HttpSecurity) as it adds final anyRequest matcher
        http.authorizeHttpRequests().requestMatchers(
                        new AntPathRequestMatcher("/admin-only/**"))
                .hasAnyRole("admin");
        http.authorizeHttpRequests().requestMatchers(
                        new AntPathRequestMatcher("/public/**"))
                .permitAll();
        super.configure(http);

        // This is important to register your login view to the
        // view access checker mechanism:
        setLoginView(http, LoginView.class);
    }

    @Override
    public void configure(WebSecurity web) throws Exception {
        // Customize your WebSecurity configuration.
        super.configure(web);
    }

    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }

    /**
     * Demo UserDetailsManager which only provides two hardcoded
     * in-memory users and their roles.
     * This shouldn't be used in real world applications.
     */
    @Bean
    public UserDetailsService userDetailsService(
            PasswordEncoder passwordEncoder) {
        InMemoryUserDetailsManager manager = new InMemoryUserDetailsManager();
        manager.createUser(User.withUsername("user")
                .password(passwordEncoder.encode("userPass"))
                .roles("USER").build());
        manager.createUser(User.withUsername("admin")
                .password(passwordEncoder.encode("adminPass"))
                .roles("USER", "ADMIN").build());
        return manager;
    }
}
----

In this example, `AuthenticationManagerBuilder` -- used in Spring Boot 2 -- is replaced by `UserDetailsService`. Also, `http.authorizeRequests().antMatchers()` is replaced with `http.authorizeHttpRequests().requestMatchers()`.



== Java Version

Java 17 or later is required. Below is an example of how to use this version:

[.example]
--
[source,xml]
----
<source-info group="Maven"></source-info>
<properties>
    <java.version>17</java.version>
    <!-- OR: -->
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
</properties>
----
[source,groovy]
----
<source-info group="Groovy"></source-info>
plugins {
    id 'java'
}

java {
    sourceCompatibility = 17
    targetCompatibility = 17
}
----
--


== Application Servers

Before migrating, find the corresponding version of the Jakarta EE 10-compatible application server used in your project. See https://jakarta.ee/compatibility/[Jakarta Compatible Products] for more information.

CDI 4.0 specification -- which is part of Jakarta EE 10 -- changes the default value of the `bean-discovery-mode` attribute to `annotated` and uses `annotated` as the default when an empty [filename]`beans.xml` file is found in a deployment. See https://jakarta.ee/specifications/cdi/4.0/[Jakarta CDI page] for more information.

To let the container scan and manage Vaadin components and views when the `bean-discovery-mode` attribute is not defined and the default is used, you should annotate Vaadin components and views with the `com.vaadin.cdi.annotation.CdiComponent` annotation to allow Vaadin components to be detected correctly as CDI beans.

As an alternative, you can set `bean-discovery-mode=all` in the [filename]`beans.xml` file if it's applicable to your project. However, this is not recommended.


== Polymer Templates

Polymer support has been deprecated since Vaadin 18 was released in November 2020, in favor of faster and simpler <<{articles}/create-ui/templates#,Lit templates>>. The built-in support for Polymer templates has been removed and is only available for Prime and Ultimate customers via an addon. However, a free conversion tool is also available to assist you in converting your Polymer templates to Lit.


=== Commercial Polymer Template Addon

If you have a Prime or Ultimate subscription, you can continue to use Polymer templates by adding the following dependency to your [filename]`pom.xml` file:

.pom.xml
[source,xml]
----
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>flow-polymer-template</artifactId>
</dependency>
----

Then you'll need to update all imports of the `PolymerTemplate` class to the new coordinates: `com.vaadin.flow.component.polymertemplate.PolymerTemplate`.


=== Polymer to Lit Conversion Tool

You can use the free conversion tool to facilitate the migration from Polymer to Lit by automatically converting basic Polymer constructions into their Lit equivalents in Java and JavaScript source files.


==== Limitations

The converter covers only basic cases. More advanced cases, such as TypeScript source files or usage of internal Polymer API, should still be converted manually.

See the https://github.com/vaadin/flow/tree/master/flow-polymer2lit[Polymer-to-Lit converter documentation] for more information about limitations and supported transformations.


==== Usage

Regarding usage, run the converter in your project's root folder as follows:

[.example]
--
[source,text]
----
<source-info group="Maven"></source-info>
mvn vaadin:convert-polymer
----
[source,groovy]
----
<source-info group="Groovy"></source-info>
./gradlew vaadinConvertPolymer
----
--

To convert a project that is based on versions before Vaadin 24, use the following:

[.example]
--
[source,text,subs="+attributes"]
----
<source-info group="Maven"></source-info>
mvn com.vaadin:vaadin-maven-plugin:{vaadin-version}:convert-polymer
----
.`build.gradle`
[source,groovy,subs="+attributes"]
----
<source-info group="Groovy"></source-info>
buildscript {
  repositories {
    classpath 'com.vaadin:flow-gradle-plugin:{vaadin-version}'
  }
}
----
--


==== Configuring

The converter needs to be configured. It accepts the following properties:

`-Dvaadin.path=path/to/your/file`::
By default, the converter scans all files that match `/.js` and `/.java` and then tries to convert them to Lit.
+
To limit conversion to a specific file or directory, you can use the `vaadin.path` property like so:
+
[.example]
--
[source,text]
----
<source-info group="Maven"></source-info>
mvn vaadin:convert-polymer -Dvaadin.path=path/to/your/file
----
[source,text]
----
<source-info group="Groovy"></source-info>
./gradlew vaadinConvertPolymer -Dvaadin.path=path/to/your/file
----
--
+
The path is always relative to your project's root folder.



`-Dvaadin.useLit1`::
By default, the converter transforms Polymer imports into their Lit 2 equivalents.
+
If your project is using Lit 1 (i.e., before Vaadin 21), you can use the vaadin.useLit1 flag to enforce Lit 1 compatible imports:
+
[.example]
--
[source,text]
----
<source-info group="Maven"></source-info>
mvn vaadin:convert-polymer -Dvaadin.useLit1
----
[source,text]
----
<source-info group="Groovy"></source-info>
./gradlew vaadinConvertPolymer -Dvaadin.useLit1
----
--

`-Dvaadin.disableOptionalChaining`::
By default, the converter transforms `\[[prop.sub.something]]` expressions into `${this.prop?.sub?.something}`.
+
If your project is using the Vaadin webpack configuration, which doesn't support the JavaScript optional chaining operator `(?.)`, you can use the `vaadin.disableOptionalChaining` flag like so:
+
[.example]
--
[source,text]
----
<source-info group="Maven"></source-info>
mvn vaadin:convert-polymer -Dvaadin.disableOptionalChaining
----
[source,text]
----
<source-info group="Groovy"></source-info>
./gradlew vaadinConvertPolymer -Dvaadin.disableOptionalChaining
----
--



== Multiplatform Runtime

Multiplatform Runtime allows the use of legacy Vaadin 7 or 8 framework components in Vaadin Flow applications. The Multiplatform Runtime artifacts remain the same: `mpr-v8` and `mpr-v7`. However, the framework server dependencies now contain an `mpr-jakarta` postfix:

.pom.xml
[source,xml]
----
<!-- Vaadin 8 -->
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-server-mpr-jakarta</artifactId>
    <version>8.19.0</version>
</dependency>

<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-compatibility-server-mpr-jakarta</artifactId>
    <version>8.19.0</version>
</dependency>

<!-- Vaadin 7 -->
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-server-mpr-jakarta</artifactId>
    <version>7.7.37</version>
</dependency>
----

Other legacy framework dependencies have the same names, but transitive dependencies to `vaadin-server` artifacts must be detected and excluded. Consult <<{articles}/tools/mpr/introduction/1-maven-v8#exclude-incompatible-framework-8-dependency, Exclude Incompatible Framework 8 Dependency>> for further details.



== Maven & Gradle Plugins

Ensure that the Maven plugins which are explicitly defined in your project, are compatible with Java 17. For example, the `nexus-staging-maven-plugin`` requires a minimum version of 1.6.13. Maven version 3.5 and later support Java 17, but avoid using 3.8.2 or 3.8.3. They break redeploy in Jetty.

To run Gradle on top of Java 17, you'll need to use version 7.5 or later. See the https://docs.gradle.org/7.5/release-notes.html[Gradle release notes] for further details. If your project uses Spring Boot, upgrade the plugin `org.springframework.boot` to version 3.0.x.

If you're using a Gradle wrapper, update it to version 7.5 by executing the following from the command line:

[source,terminal]
----
./gradlew wrapper --gradle-version 7.5
----

For Java 17 compatibility, you may need to update the `sourceCompatibility` setting in your project's build file to version 17. Check your project's build file and make any necessary changes.


== SLF4J 2.0

Vaadin 24 and Spring-boot 3 use SLF4J library version 2.0, which has breaking changes compared to earlier versions. See the https://www.slf4j.org/news.html[SLF4J release notes] for more information.


== Line-Awesome Icons Set Library

Vaadin 23 starter projects used https://icons8.com/line-awesome[`line-awesome`] icons set library. You may also need the `line-awesome` library in your project. If so, try using the Vaadin https://vaadin.com/directory/component/line-awesome-icons-for-vaadin[Line-Awesome] add-on with Vaadin 24. In Vaadin 24, this add-on doesn't require building a new bundle, so your application would then benefit from the pre-compiled bundle feature.


== Breaking Changes in Vaadin Components

Vaadin components have several breaking changes related to upgrading to the latest version.

Shrinking Badges::
Badges no longer shrink by default. This can be overridden globally with CSS `[theme~="badge"] { flex-shrink:1; }`, or for specific instances with `badge.getStyle().set("flex-shrink", "1")`, or with `layout.setFlexShrink(badge, 1)`.

Shrinking Buttons::
Buttons also no longer shrink by default. This also can be overridden globally, but with CSS `vaadin-button { flex-shrink:1; }`, or for specific instances with `btn.getStyle().set("flex-shrink", "1")` or with `layout.setFlexShrink(btn, 1)`.

CheckboxGroup::
The `CheckboxGroup::setItemLabelGenerator` no longer clears the current selection. The `CheckboxGroup.clear()` can be used to clear values, separately.

BlurNotifier::
The `BlurNotifier<CustomField>` type signature was corrected to `BlurNotifier<CustomField<T>>`.

Date Picker::
Date Picker now uses the ISO 8601 date format (i.e., `yyyy-mm-dd`) as fallback for unsupported locales -- instead of `mm-dd-yyyy`. Time Picker no longer automatically adjusts values to fit minimum and maximum constraints.

Number Field::
Number Field's default width now matches that of other text input components. The old default can be brought back with CSS `vaadin-number-field { width:8em; }`.

RichTextEditor::
`RichTextEditor::setvalue` and `getValue` now use HTML format by default, instead of Delta. Applications using the Delta format must be refactored to use the `RichTextEditor.asDelta()` API (e.g. `rte.asDelta().getValue()` and `binder.forField(rte.asDelta())`). To help avoid using the wrong setter, `RichTextEditor.setValue(String)` now throws an exception if the value looks like it's in Delta format (i.e., it starts with a `[` or `{` bracket). To set an HTML value starting with the above characters, either wrap the value in an HTML tag, or use the `RichTextEditor.asHtml()` API, which doesn't check for them.

Margins for Headings::
The default top and bottom margins of the `H1`...`H6` HTML elements have been removed. This change can be reverted by applying the following CSS:
+
.styles.css
[source,css]
----
h1,h2,h3,h4,h5,h6 { margin-top: 1.25em; }
h1 { margin-bottom: 0.75em; }
h2, h3, h4 { margin-bottom: 0.5em; }
h5 { margin-bottom: 0.25em; }
----


=== Removed Flow Component APIs

.View Removed or Renamed Flow APIs
[%collapsible]
====
The following Vaadin component APIs have been removed or renamed in Flow:

- The `Generated[ComponentName]` classes have been removed. Extend the normal component classes instead when extending components.
+
The following event classes were introduced in V23.3 as replacements for the ones in the generated classes: `DatePicker.OpenedChangeEvent`; `DatePicker.InvalidChangeEvent`; `Dialog.OpenedChangeEvent`; `Notification.OpenedChangeEvent`; and `SplitLayout.SplitterDragendEvent`.
+
The generic type parameters in these events -- introduced in V23.3 for backward compatibility -- was removed in V24.
- `Button.setDisabled()` was removed in favor of `setEnabled(false)`.
- Charts `HTMLLabels` and `HTMLLabelItem` APIs were removed -- they were broken -- in favor of `Configuration.addLabel` or `Configuration.setLabels` with `AnnotationItemLabel` objects instead of `HTMLLabel`. Coordinate information for the label can be provided using `AnnotationItemLabel.setPoint`.
- `Checkbox::setLabelAsHtml` was removed in favor of renderers (i.e., `setRenderer`).
- `CheckboxGroup` and `RadioButtonGroup` no longer implement the `HasComponents` and `HasItemComponents` interfaces and the following related methods have been removed:
	-- `add(Component...)`, `add(Collection)`, and `add(String)`;
	-- `remove(Component...)`, `remove(Collection)`, and `removeAll()`;
	-- `addComponentAtIndex(int, Component)`;
	-- `addComponentAsFirst(Component)`;
	-- `addComponents(T, Component...)`;
	-- `prependComponents(T, Component...)`; and
	-- `getItemPosition(T)`.
- `ContextMenu` `clickListener` API was removed -- it wasn't working. Apply instead click listeners to the menu's target component if needed.
- `CustomFieldI81n::parseValue` and `CustomFieldI18n::formatValue` were moved to `CustomField::parseValue` and `CustomField::formatValue`.
- `DatePickerI18n` setters and getters for `clear`, `.calendar`, and `.week` were removed since it was unused.
- `FlexLayout.getFlexDirection(HasElement elementContainer)` overload was removed -- it was pointless -- in favor of `getFlexDirection()`.
- `Grid::setHeightByRows` was removed in favor of `Grid::setAllRowsVisible`.
- `Grid.addColumn(renderer, sortingProperties)` was removed in favor of `addColumn(renderer).setSortProperty(sortingProperties)`.
- `Grid.ItemClickEvent` and `ItemDoubleClickEvent` without `columnId` were removed.
- `Grid::findInShadowRoot` was removed.
- `Grid::setVerticalScrollingEnabled` was removed: it wasn't working.
- `Map.Coordinate::fromLonLat` was removed as unnecessary since the default coordinate system is now EPSG:4326, and `new Coordinate(x,y)` is sufficient.
- `Map` APIs that used `float` values now use `double`.
- `NumberField::setMaxLength`, `setPattern`, and `setPreventInvalidInput` were removed because they didn't work.
- `NumberField::setHasControls` was renamed `setStepButtonsVisible`.
- `RichTextEditor(String value)` constructor was removed in favor of `RichTextEditor()`, followed by `setValue(String value)`.
- `Select(T... items)` constructor was removed in favor of `Select(String label, T... items)`.
- `SplitLayout.IronResizeEvent` was removed as part of a migration away from Polymer.
- `Tabs` no longer implements the `HasComponents` interface, with the following APIs removed or deprecated:
	-- `add(Collection)` was removed in favor of `add(Tab...)`;
	-- `remove(Collection)` was removed in favor of `remove(Tab...)`;
	-- `add(String)` was removed;
	-- `indexOf(Component)` was deprecated in favor of `indexOf(Tab)`;
	-- `add(Component)` was deprecated in favor of `add(Tab)`;
	-- `remove(Component)` was deprecated in favor of `remove(Tab)`;
	-- `replace(Component, Component)` was deprecated in favor of `replace(Tab, Tab)`;
	-- `getComponentAt(int)` was deprecated in favor of `getTabAt(int)`;
	-- `addComponentAtIndex(int, Component)` was deprecated in favor of `addTabAtIndex(int, Tab)`; and
	-- `addComponentAsFirst(Component)` was deprecated in favor of `addTabAsFirst(Tab)`.
- `TemplateRenderer` public API was removed in favor of `LitRenderer`.
- `TextField::setPreventInvalidInput` was removed in favor of `setAllowedCharPattern`.
- `TimePicker.setMin(String)` and `setMax(String)` were removed in favor of `setMin(LocalTime)` and `setMax(LocalTime)`.
- Upload `SelectedChangeEvent(Tabs source, boolean fromClient)` overload was removed in favor of `SelectedChangeEvent(Tabs source, Tab previousTab, boolean fromClient)`.
- `UploadI18n::setCancel` and `UploadI18n::getCancel` were removed since they were unused.

====


=== Web Component APIs

.Click and read if using Vaadin Components without Flow.
[%collapsible]
====
The following changes only affect the client-side APIs of Vaadin components:

- The label on `vaadin-checkbox` and `vaadin-radio-button` must be set using the `label` property, as the default slot has been removed.
- `vaadin-confirm-dialog.cancel` and `.reject` properties were renamed `.cancelButtonVisible` and `.rejectButtonVisible`.
- `vaadin-number-field` property `has-controls` was renamed `step-buttons-visible`.
- Deprecated `@vaadin/vaadin-xxx` (e.g., `@vaadin/vaadin-grid`) npm packages have been removed. Use instead the new `@vaadin/xxx` (e.g., `@vaadin/grid`).
- Deprecated `xxxElement` legacy class aliases (e.g., `GridElement`) have been removed. Use the plain component classes instead (e.g., `Grid`).
- Deprecated misspelled `vaadin-icons` were removed: `buss`, `funcion`, `megafone`, `palete`, and `trendind-down`.
- `notifyResize` and `updateStyles` methods were removed from various components as obsolete.
- `preventInvalidInput` in text input fields was removed in favor of `setAllowedCharPattern`.
- The read-only `theme` _property_ was removed. Use instead the `theme` _attribute_.

====


=== Update Your Component Styling

.Click and read if styled Vaadin Components.
[%collapsible]
====
include::_styling.adoc[]
====


== Field Validation Changes

Vaadin 24 introduces several major changes in field component validation, addressing various issues and UX inconsistencies that have been reported in previous versions.

=== Binder Considers Component Constraints

Every field component provides its own set of constraints, such as `required`, `minlength`, `pattern`, etc.

*Before:*

When using Binder, component constraints were ignored in earlier versions. They could still affect the client-side invalid state without reflecting this to the server.

*After:*

In the new version, component constraints are integrated into Binder validation. Binder checks the value against constraints before custom validators. The only exception is the required constraint. It doesn't participate in Binder validation since Binder provides its own `asRequired` validator.

*Known Issues:*

It's currently not possible to configure custom error messages for constraints (https://github.com/vaadin/flow-components/issues/4618[flow-components#4618]).

Also, it's currently not possible to revert Binder's behavior to ignore constraints as before, except by removing the constraints from the component, entirely (https://github.com/vaadin/flow/issues/17178[flow#17178]).


=== Blur Triggers Server-Side Validation

*Before:*

Both constraint and Binder validation were previously only triggered on `ValueChangeEvent`, while client-side validation was completely disregarded.

*After:*

The server-side validation timing is now aligned with client-side validation, meaning that whenever the web component validation occurs, it triggers the corresponding validation in the Flow component. In practice, this means that the server-side validation also is performed on blur (i.e., when the component loses focus).

*Known Issues:*

The component validates on blur even when the user leaves it without typing anything. This behavior results from the web component, which validates on blur to detect possible bad input (https://github.com/vaadin/web-components/issues/6146[web-components#6146]).

The server-side validation can be triggered more frequently than necessary. For example, if you edit a Text Field and then blur, both value-changed and blur events can fire at the same time, resulting in double validation in a single round-trip (https://github.com/vaadin/flow-components/issues/4390[flow-components#4390]).


=== Bad Input Invalidates Component

Date Picker, Integer Field, and some other similar components only accept user input that can be parsed as a `LocalDate`, `Integer`, etc. Otherwise, the value on the server falls back to `null`.

*Before:*

Previously, entering bad input didn't invalidate the component because the server treated this case as an empty value.

*After:*

The server is now aware if the user has entered any input. When the input cannot be parsed, it's considered bad input, causing constraint validation to fail once the user presses Enter or removes focus from the component.


[role="since:com.vaadin:vaadin@V24.2"]
=== Manual Validation Mode

There are applications that require a totally custom validation logic that is beyond the capabilities of validation tools provided by Vaadin. For such applications, Vaadin 24.2 introduces a manual validation mode. This mode disables the component's built-in validation, allowing developers to have manual control over the component's invalid state and error messages.

Below is an example of a custom implementation of the required validation performed on `ValueChangeEvent`:

[source,java]
----
TextField textField = new TextField();
textField.setManualValidation(true);
textField.addValueChangeListener(event -> {
    if (Objects.equals(event.getValue(), "")) {
        textField.setInvalid(true);
        textField.setErrorMessage("The field is required.");
    } else {
        textField.setInvalid(false);
    }
});
----

== Removed Deprecations

APIs that were deprecated earlier have now been removed. The following linked GitHub issue lists these removals:

- https://github.com/vaadin/flow/issues/15665[Remove deprecated API and tools in Flow 24.0]
