---
title: Upgrading
order: 70
---

= Upgrading Guide
:!toc:

pass:[<!-- Vale Vaadin.Versions = NO -->]

Instructions for upgrading to the latest Vaadin version. To run applications or components developed with Vaadin 7 or 8 inside an application written using the latest version, see <<{articles}/tools/mpr/overview#,Multiplatform Runtime>>.

pass:[<!-- Vale Vaadin.Versions = YES -->]


[source,typescript, role="render-only embedded"]
----
include::{root}/frontend/demo/upgrade-tool/upgrade-tool.ts[render, persistent]
----

////
Upgrading instructions are all loaded to the page as hidden by default.
The upgrade-tool manipulates the visibility of the instructions via their classnames depending of the user's selected options.

This is the description of the classnames:

.all:
    Upgrading instructions that should appear regardless of the user's selected configurations.

.flow-all:
    Upgrading instructions that should appear for all Flow projects, regardless of the user's other selected configurations.

.fusion-all:
    Upgrading instructions that should appear for all Fusion projects, regardless of the user's other selected configurations.

.spring-all:
    Upgrading instructions that should appear for all Spring-based projects, regardless of the user's other selected configurations.

.typescript-all:
    Upgrading instructions that should appear for all projects with Typescript views, regardless of the user's other selected configurations.

.flow-{from-version}-{to-version}:
    For example, flow-14-17, will be used by the upgrade tool to show the marked instructions if the user selects to see the instructions for the v14 -> v17 path.
    If there is no upgrading instructions directly for the v14 -> v17 path, the app will then display all the intermediary upgrade paths (i.e. v14->v15, v15->v16, and v16-v17).

.fusion-{from-version}-{to-version}:
    Same as flow-{from-version}-{to-version} for Fusion.

.spring-{from-version}-{to-version}:
    Same as flow-{from-version}-{to-version} for any Spring project (regardless of whether it's flow or fusion based).

.typescript-{from-version}-{to-version}:
    Same as flow-{from-version}-{to-version} for any Typescript project (regardless of whether it's flow or fusion based).

.flow-spring-{from-version}-{to-version}:
    Same as flow-{from-version}-{to-version}, but only displays the content if the project is a Spring-based one.

.flow-typescript-{from-version}-{to-version}:
    Same as flow-{from-version}-{to-version}, but only displays the content if the project is a TypeScript-based one.

.fusion-spring-{from-version}-{to-version}:
    Same as fusion-{from-version}-{to-version}, but only displays the content if the project is a Spring-based one.

.fusion-typescript-{from-version}-{to-version}:
    Same as fusion-{from-version}-{to-version}, but only displays the content if the project is a TypeScript-based one.

////

++++
<style>
[class*="all"], 
[class*='flow'], 
[class*='fusion'], 
[class*='spring'], 
[class*='typescript'] 
{
    display: none;
}
</style>
++++

[.all]
=== Before You Start

[.all]
--
include::_before-upgrade.asciidoc[]
--

[.spring-all]
--
include::_before-upgrade-spring.asciidoc[]
--

[.flow-14-22.fusion-14-22]
=== Upgrade Steps | 14 -> 22

[.flow-14-22]
--
include::flow-instructions/_upgrade-14-22.asciidoc[]
--

[.flow-typescript-14-22]
--
include::flow-instructions/_upgrade-14-22-typescript.asciidoc[]
--

[.fusion-14-22]
--
include::fusion-instructions/_upgrade-14-22.asciidoc[]
--

[.flow-14-15.fusion-14-15]
=== Upgrade Steps | 14 -> 15

[.flow-14-15]
--
include::flow-instructions/_upgrade-14-15.asciidoc[]
--

[.fusion-14-15]
--
include::fusion-instructions/_upgrade-14-15.asciidoc[]
--

[.flow-15-16.fusion-15-16]
=== Upgrade Steps | 15 -> 16

[.flow-15-16]
--
include::flow-instructions/_upgrade-15-16.asciidoc[]
--

[.fusion-15-16]
--
include::fusion-instructions/_upgrade-15-16.asciidoc[]
--

[.flow-16-17.fusion-16-17]
=== Upgrade Steps | 16 -> 17

[.flow-16-17]
--
include::flow-instructions/_upgrade-16-17.asciidoc[]
--

[.fusion-16-17]
--
include::fusion-instructions/_upgrade-16-17.asciidoc[]
--

[.flow-17-18.fusion-17-18]
=== Upgrade Steps | 17 -> 18

[.flow-17-18]
--
include::flow-instructions/_upgrade-17-18.asciidoc[]
--

[.fusion-17-18]
--
include::fusion-instructions/_upgrade-17-18.asciidoc[]
--

[.flow-18-19.fusion-18-19]
=== Upgrade Steps | 18 -> 19

[.flow-18-19]
--
include::flow-instructions/_upgrade-18-19.asciidoc[]
--

[.fusion-18-19]
--
include::fusion-instructions/_upgrade-18-19.asciidoc[]
--

[.flow-19-20.fusion-19-20]
=== Upgrade Steps | 19 -> 20

[.flow-19-20]
--
include::flow-instructions/_upgrade-19-20.asciidoc[]
--

[.fusion-19-20]
--
include::fusion-instructions/_upgrade-19-20.asciidoc[]
--

[.flow-20-21.fusion-20-21]
=== Upgrade Steps | 20 -> 21

[.flow-20-21]
--
include::flow-instructions/_upgrade-20-21.asciidoc[]
--

[.fusion-20-21]
--
include::fusion-instructions/_upgrade-20-21.asciidoc[]
--

[.flow-21-12.fusion-21-12]
=== Upgrade Steps | 21 -> 22

[.flow-21-22]
--
include::flow-instructions/_upgrade-21-22.asciidoc[]
--

[.fusion-21-22]
--
include::fusion-instructions/_upgrade-21-22.asciidoc[]
--

[.all]
=== After you finish

[.all]
--
include::_after-upgrade.asciidoc[]
--
