---
title: Vertical Layout
page-title: Vertical Layout component | Vaadin components
description: Vertical Layout places components top-to-bottom in a column.
meta-description: Use the Vertical Layout component to arrange components vertically in your application.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/vertical-layout}/elements/vaadin-vertical-layout[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/orderedlayout/VerticalLayout.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/vertical-layout}/packages/vertical-layout[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-ordered-layout-flow-parent[Java]'
---


= Vertical Layout

// tag::description[]
Vertical Layout places components top-to-bottom in a column.
// end::description[]
By default, it has a width of 100% and an undefined height. Its width is constrained by its parent component (i.e., it “fills” the available space). Whereas, its height is determined by the components it contains (i.e., it “hugs” its content).

See <<../horizontal-layout#, Horizontal Layout>> for information on placing components side-by-side.

[.example,themes="lumo,aura"]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/vertical-layout/vertical-layout-basic.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/verticallayout/VerticalLayoutBasic.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/vertical-layout/react/vertical-layout-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

Components in a Vertical Layout can be aligned vertically, as you'd expect. However and perhaps surprisingly, they can also be aligned horizontally in a Vertical Layout.



== Vertical Alignment

You can position components at the top, middle, or bottom. You can also position them by specifying how the excess space in a layout is distributed among them.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/vertical-layout/vertical-layout-vertical-alignment.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/verticallayout/VerticalLayoutVerticalAlignment.java[render,tags=layout,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/vertical-layout/react/vertical-layout-vertical-alignment.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


|===
|Value |Description

|`START` (default)
|Positions items at the top.

|`CENTER`
|Centers items, vertically.

|`END`
|Positions items at the bottom.

|`BETWEEN`
|Available space is distributed equally among items. However, no space is added before the first item, or after the last.

|`AROUND`
|Available space is distributed equally among items. However, the space before the first item and after the last is half of that between items.

|`EVENLY`
|Available space is distributed equally among items. The space before the first item and after the last item is the same as between others.
|===



== Horizontal Alignment

Components in a Vertical Layout are left-aligned by default, but can be centered, right-aligned or stretched horizontally.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/vertical-layout/vertical-layout-horizontal-alignment.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/verticallayout/VerticalLayoutHorizontalAlignment.java[render,tags=layout,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/vertical-layout/react/vertical-layout-horizontal-alignment.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


|===
|Value |Description

|`START` (default)
|Left-aligns items for left-to-right language text (e.g., English). For right-to-left languages (e.g., Arabic, Hebrew), it right-aligns items.

|`CENTER`
|Centers items, horizontally.

|`END`
|Right-aligns for left-to-right language text. For right-to-left languages, it left-aligns items.

|`STRETCH`
|Stretches horizontally items with undefined width.
|===

It's also possible to align horizontally individual components by overriding the general alignment setting of the layout.


[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/vertical-layout/vertical-layout-individual-alignment.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/verticallayout/VerticalLayoutIndividualAlignment.java[render,tags=layout,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/vertical-layout/react/vertical-layout-individual-alignment.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

:vertical-layout: true
include::../horizontal-layout/_troubleshooting.adoc[]


[discussion-id]`73cc0e40-d39a-11ed-afa1-0242ac120002`
