---
title: Styling
page-title: How to style the Vertical Layout | Vaadin components
description: Styling API reference for the Vertical Layout component.
meta-description: Customize the Vertical Layout component to align with your application’s theme and branding.
order: 50
---
= Vertical Layout Styling

== Style Variants

Vertical Layout supports the following style variants:

[cols="1,1"]
|===
| Variant | Supported by

|`margin`
|Aura, Lumo

|`padding`
|Aura, Lumo

|`spacing`
|Aura, Lumo

|`wrap`
|Aura, Lumo

|===

== Spacing

Spacing is used to create gaps between components in the same layout. Spacing can help prevent misclicks and distinguish content areas.

[.example,themes="lumo,aura"]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/vertical-layout/vertical-layout-spacing.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/verticallayout/VerticalLayoutSpacing.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/vertical-layout/react/vertical-layout-spacing.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

Spacing can be customized with a specific value or a CSS custom property:

[.example]
--

[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-vertical-layout style="gap: 12px"></vaadin-vertical-layout>

<vaadin-vertical-layout style="gap: var(--vaadin-gap-l)"></vaadin-vertical-layout>
----

[source,java]
----
<source-info group="Flow"></source-info>
VerticalLayout layout = new VerticalLayout();

layout.setSpacing(12, Unit.PIXELS);

layout.setSpacing("var(--vaadin-gap-l)");
----

[source,tsx]
----
<source-info group="React"></source-info>
<VerticalLayout style={{ gap: '12px' }}></VerticalLayout>

<VerticalLayout style={{ gap: 'var(--vaadin-gap-l)' }}></VerticalLayout>
----

--

For available CSS custom properties that can be used as spacing values, see <</styling/themes/base#gap,gap properties>> from the base styles and <</styling/themes/lumo/lumo-style-properties/size-space#space,space properties>> from the Lumo theme.

== Padding

Padding is the space allocated between the content in a layout and the outer border. This should not be confused with Margin, which is explained in the next section.

Padding can help distinguish the content in a layout from its surrounding. Padding is applied using the padding style variant.

[.example,themes="lumo,aura"]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/vertical-layout/vertical-layout-padding.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/verticallayout/VerticalLayoutPadding.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/vertical-layout/react/vertical-layout-padding.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Margin

Margin is the space around a layout. This is different from Padding, which is explained in the previous section.

[.example,themes="lumo,aura"]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/vertical-layout/vertical-layout-margin.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/verticallayout/VerticalLayoutMargin.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/vertical-layout/react/vertical-layout-margin.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

== Wrapping

By default, components in a layout either shrink or overflow when there isn't enough vertical space. Enable wrapping to allow components to flow onto a new column when space runs out, preventing overflow.

[.example,themes="lumo,aura"]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/vertical-layout/vertical-layout-wrapping.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/verticallayout/VerticalLayoutWrapping.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/vertical-layout/react/vertical-layout-wrapping.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

include::../_styling-section-theming-props.adoc[tag=style-properties]

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-vertical-layout-gap`
|Aura, Lumo

|`--vaadin-vertical-layout-padding`
|Aura, Lumo

|`--vaadin-vertical-layout-margin`
|Aura, Lumo

|===

include::../_styling-section-intros.adoc[tag=selectors]

Root element:: `vaadin-vertical-layout`