---
title: Styling
page-title: How to style the Vertical Layout | Vaadin components
description: Styling API reference for the Vertical Layout component.
meta-description: Customize the Vertical Layout component to align with your application’s theme and branding.
order: 50
---
= Vertical Layout Styling

== Style Variants

Vertical Layout supports the following style variants:

[cols="1,1"]
|===
| Variant | Supported by

|`margin`
|Aura, Lumo

|`padding`
|Aura, Lumo

|`spacing`
|Aura, Lumo

|`wrap`
|Aura, Lumo

|===

== Spacing

Spacing is used to create space between components in the same layout. Spacing can help prevent misclicks and distinguish content areas.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/vertical-layout/vertical-layout-spacing.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/verticallayout/VerticalLayoutSpacing.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/vertical-layout/react/vertical-layout-spacing.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

Five different spacing theme variants are available:

[.example.render-only]
--

[source,typescript,role=render-only]
----
include::{root}/frontend/demo/component/vertical-layout/vertical-layout-spacing-variants.ts[render,tags=snippet,indent=0,group=Lit]
----

--

|===
|Theme Variant |Usage Recommendation

|`spacing-xs`
|Extra-small space between items.

|`spacing-s`
|Small space between items.

|`spacing`
|Medium space between items.

|`spacing-l`
|Large space between items.

|`spacing-xl`
|Extra-large space between items.
|===


[.example]
--

ifdef::lit[]
[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-vertical-layout
  theme="spacing-xs padding">
</vaadin-vertical-layout>
----
endif::[]

ifdef::flow[]
[source,java]
----
<source-info group="Flow"></source-info>
VerticalLayout layout = new VerticalLayout();
layout.setSpacing(false);
layout.getThemeList().add("spacing-xs");
----
endif::[]

ifdef::react[]
[source,tsx]
----
<source-info group="React"></source-info>
<VerticalLayout theme="spacing-xs padding">
</VerticalLayout>
----
endif::[]

--

Alternatively, the spacing can be set to a custom value:

[.example]
--
ifdef::lit[]
[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-vertical-layout style="gap: 12px">
</vaadin-vertical-layout>
----
endif::[]

ifdef::flow[]
[source,java]
----
<source-info group="Flow"></source-info>
VerticalLayout layout = new VerticalLayout();
layout.setSpacing(12, Unit.PIXELS);
----
endif::[]

ifdef::react[]
[source,tsx]
----
<source-info group="React"></source-info>
<VerticalLayout style={{ gap: '12px' }}>
</VerticalLayout>
----
endif::[]

--

== Padding

Padding is the space allocated between the content in a layout and the outer border. This should not be confused with Margin, which is explained in the next section.

Padding can help distinguish the content in a layout from its surrounding. Padding is applied using the padding theme variant.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/vertical-layout/vertical-layout-padding.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/verticallayout/VerticalLayoutPadding.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/vertical-layout/react/vertical-layout-padding.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Margin

Margin is the space around a layout. This is different from Padding, which is explained in the previous section.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/vertical-layout/vertical-layout-margin.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/verticallayout/VerticalLayoutMargin.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/vertical-layout/react/vertical-layout-margin.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

== Wrapping

By default, components in a layout either shrink or overflow when there isn't enough vertical space. Enable wrapping to allow components to flow onto a new column when space runs out, preventing overflow.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/vertical-layout/vertical-layout-wrapping.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/verticallayout/VerticalLayoutWrapping.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/vertical-layout/react/vertical-layout-wrapping.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

include::../_styling-section-theming-props.adoc[tag=style-properties]

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-vertical-layout-gap`
|Aura, Lumo

|`--vaadin-vertical-layout-padding`
|Aura, Lumo

|`--vaadin-vertical-layout-margin`
|Aura, Lumo

|===

include::../_styling-section-intros.adoc[tag=selectors]

Root element:: `vaadin-vertical-layout`