---
title: Chart Types
page-title: Explore various chart types for Vaadin Charts component
description: A list of chart types available with information on using and configuring them.
meta-description: See a list of various chart types available for Vaadin Charts and learn about their implementation in applications.
order: 4
---


[[charts.charttypes]]
= Chart Types

Charts come with over a dozen different types. You normally specify the chart type in the constructor of the [classname]`Chart` object. The available chart types are defined in the [classname]`ChartType` enum. You can later read or set the chart type with the [literal]`++chartType++` property of the chart model, which you can get with [methodname]`getConfiguration().getChart()`.

The supported chart types are:

[cols="4*"]
|===
| <<area#charts.charttypes.area, `area`>> | <<area-and-column-range#charts.charttypes.rangecharts, `arearange`>> | <<area#charts.charttypes.area, `areaspline`>> | <<area-and-column-range#charts.charttypes.rangecharts, `areasplinerange`>>
| <<column-and-bar#charts.charttypes.columnbar, `bar`>> | <<box-plot#charts.charttypes.boxplot, `boxplot`>> | <<bubble#charts.charttypes.bubble, `bubble`>> | <<bullet#charts.charttypes.bullet, `bullet`>>
| <<ohlc-and-candlestick#charts.charttypes.ohlc, `candlestick`>> | <<column-and-bar#charts.charttypes.columnbar, `column`>> | <<area-and-column-range#charts.charttypes.rangecharts, `columnrange`>> | <<error-bars#charts.charttypes.errorbar, `errorbar`>>
| <<flags#charts.charttypes.flags, `flags`>> | <<funnel-and-pyramid#charts.charttypes.funnel, `funnel`>> | <<gantt#charts.charttypes.gantt, `gantt`>> | <<gauge#charts.charttypes.gauge, `gauge`>>
| <<heatmap#charts.charttypes.heatmap, `heatmap`>> | <<line-and-spline#charts.charttypes.line, `line`>> | <<ohlc-and-candlestick#charts.charttypes.ohlc, `ohlc`>> | <<organization#charts.charttypes.organization, `organization`>>
| <<pie#charts.charttypes.pie, `pie`>> | <<polygon#charts.charttypes.polygon, `polygon`>> | <<funnel-and-pyramid#charts.charttypes.funnel, `pyramid`>> | <<sankey#charts.charttypes.sankey, `sankey`>>
| <<scatter#charts.charttypes.scatter, `scatter`>> | <<solid-gauge#charts.charttypes.solidgauge, `solidgauge`>> | <<line-and-spline#charts.charttypes.line, `spline`>> | <<timeline#charts.charttypes.timeline, `timeline`>>
| <<treemap#charts.charttypes.treemap, `treemap`>> | <<waterfall#charts.charttypes.waterfall, `waterfall`>> | <<xrange#charts.charttypes.xrange, `xrange`>> |
|===

Most chart types with two axes can also be drawn in <<polar#charts.charttypes.polar,polar coordinates>>, and most types can be given a <<3d#charts.charttypes.3d,three-dimensional projection>>.

Each chart type has its specific plot options and supports its specific collection of chart features. They also have specific requirements for the data series. Configuring <<data-labels#charts.charttypes.datalabels, `Data Labels`>> is common to all chart types. Configuring <<markers#charts.charttypes.markers, `Markers`>> is available for all chart types displaying point data.


== Topics

section_outline::[]

[discussion-id]`7D9B93CE-C74C-4440-869F-9594622310AD`
