---
title: Checkbox
layout: tabbed-page
tab-title: Usage
page-links: \
https://github.com/vaadin/vaadin-checkbox-flow/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-checkbox-flow}[{moduleMavenVersion:com.vaadin:vaadin-checkbox-flow}], \
https://github.com/vaadin/vaadin-checkbox/releases/tag/v{moduleNpmVersion:vaadin-checkbox}[{moduleNpmVersion:vaadin-checkbox}]
---
= Checkbox

// tag::description[]
Checkbox is an input field representing a binary choice.
Checkbox Group is a group of related binary choices.
// end::description[]

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/checkbox/checkbox-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/checkbox/CheckboxBasic.java[render,tags=snippet,indent=0,group=Java]
----
--

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/checkbox/checkbox-group.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/checkbox/CheckboxGroup.java[render,tags=snippet,indent=0,group=Java]
----
--

Use Checkbox Group to group related items.
Individual checkboxes should be used for options that are not related to each other in any way.

== States

=== Disabled

Disable a field to mark it as currently unavailable.
Disabled state is used for fields that are not editable and do not need to be readable.
Disabled elements cannot be focused and may be inaccessible to assistive technologies like screen readers.

Disabling can be preferable to hiding an element to prevent changes in layout when the element’s visibility changes, and to make users aware of its existence even when currently unavailable.


[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/checkbox/checkbox-disabled.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/checkbox/CheckboxDisabled.java[render,tags=snippet,indent=0,group=Java]
----
--

.Note
[NOTE]
====
Checkbox does not currently support read-only state.
====

=== Indeterminate

In addition to checked and unchecked, Checkbox has an indeterminate state.
This state can be used for a parent checkbox to indicate that there is a mix of checked and unchecked child items in a list, as well as to change the state of all child items at once.

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/checkbox/checkbox-indeterminate.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/checkbox/CheckboxIndeterminate.java[render,tags=snippet,indent=0,group=Java]
----
--

Indeterminate state is also often used when allowing the user to edit multiple items simultaneously, and the items being edited have different values for a given property.

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/checkbox/checkbox-edit-multiple.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/checkbox/CheckboxEditMultiple.java[render,tags=snippet,indent=0,group=Java]
----
--

When an indeterminate checkbox is clicked it becomes checked.
Users should be allowed to get back to the indeterminate state via a Cancel or Reset button when used in a form.

== Orientation

The component's default orientation is horizontal but vertical orientation is recommended whenever possible as it's easier for the user to scan a vertical list of options:

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/checkbox/checkbox-vertical.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/checkbox/CheckboxVertical.java[render,tags=snippet,indent=0,group=Java]
----
--

In cases where vertical space needs to be conserved, horizontal orientation can be used, but no more than 3 options are recommended:

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/checkbox/checkbox-horizontal.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/checkbox/CheckboxHorizontal.java[render,tags=snippet,indent=0,group=Java]
----
--

== Custom Item Presentation
Items can be customised to include more than a single line of text:

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/checkbox/checkbox-custom-presentation.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/checkbox/CheckboxCustomPresentation.java[render,tags=snippet,indent=0,group=Java]
----
--

== Best Practices

Checkboxes should not trigger immediate actions.
Use Buttons for this instead.

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/checkbox/checkbox-trigger.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/checkbox/CheckboxTrigger.java[render,tags=snippet,indent=0,group=Java]
----
--

=== Labeling

Aim for short and descriptive labels using positive wording.
*Avoid negations*.

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/checkbox/checkbox-labeling.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/checkbox/CheckboxLabeling.java[render,tags=snippet,indent=0,group=Java]
----
--

It is important to provide labels for Checkbox Groups to clearly distinguish adjacent groups.

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/checkbox/checkbox-adjacent-groups.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source, java]
----
include::{root}/src/main/java/com/vaadin/demo/component/checkbox/CheckboxAdjacentGroups.java[render,tags=snippet,indent=0,group=Java]
----
--

== Related Components

|===
|Header 1 |Header 2

|<<../select#,Select>>|A dropdown field for selecting an item from a list of options.
Recommended when there is insufficient space for a Radio Button Group.

|<<../combo-box#,Combo Box>>|A filterable, lazy loading alternative to Select, recommended for ten or more items.

|<<../list-box#,List Box>>|Scrollable list of options.
Supports single and multi-select.

|<<../radio-button#,Radio Button Group>>|Corresponding component for mutually exclusive options, or “single-select”.
|===
