---
title: Using Existing Components
page-title: How to create composite components in Vaadin Flow
description: Creating a component by combining existing components together.
meta-description: Learn to build composite components by combining existing Vaadin Flow components.
order: 5
---


= Creating a Component Using Existing Components

This section demonstrates how to create a `Composite` component using existing components.

The example creates a `TextField` component by combining existing `Div`, `NativeLabel` and `Input` HTML components into this hierarchy:

* `Div`
** `NativeLabel`
** `Input`

.Create the component based on a Composite
[NOTE]
Creating the component based on a `Composite` is the best practice in these circumstances.
It's possible to create a new component by extending the `Div` HTML component, but this isn't advisable, because it unnecessarily exposes `Div` API methods, such as [methodname]`add(Component)`, to the user.

*Example*: Creating a `TextField` component by extending [classname]`Composite<Div>`.
[source,java]
----
public class TextField extends Composite<Div> {

    private NativeLabel label;
    private Input input;

    public TextField(String labelText, String value) {
        label = new NativeLabel();
        label.setText(labelText);
        input = new Input();
        input.setValue(value);

        getContent().add(label, input);
    }
}
----

* The `Composite` automatically creates the root component, specifying it by using generics (`Composite<Div>`).
* You can access the root component through the [methodname]`getContent()` method.
* In the constructor, you only need to create the child components and add them to the root `Div`.
* Set the value by using [methodname]`setValue()` method in the `Input` component.

== Adding an API

To make the component easier to use, you can add an API to get and set the value and label text.
You do this by delegating to the `Input` and `NativeLabel` components.

*Example*: Adding an API to get and set the value and label.

[source,java]
----
public String getValue() {
    return input.getValue();
}
public void setValue(String value) {
    input.setValue(value);
}

public String getLabel() {
    return label.getText();
}
public void setLabel(String labelText) {
    label.setText(labelText);
}
----

* The public API only exposes the defined methods, and a few generic methods defined in the [interface]#Component# interface.

.Keeping overhead to a minimum
[TIP]
Using a `Component` (instead of an `Element`) or a `Composite` doesn't result in extra overhead.


[discussion-id]`6047C25F-34E4-4192-BAAF-D9057BF74F0D`
