---
title: Router Layouts pass:[&] Nested Router Targets
description: Explains router layouts and nested router targets.
order: 40
---


= Router Layouts & Nested Router Targets

All parent layouts of a navigation target component have to implement the [interfacename]`RouterLayout` interface. You can define a parent layout by adding the [annotationname]`@Layout` annotation on the class, or by using the optional element `layout` from the `@Route` annotation.

The example below renders all routes inside [classname]`MainLayout`:

[source,java]
----
@Layout
public class MainLayout extends Div
        implements RouterLayout {
}
----

This next example renders [classname]`CompanyComponent` inside [classname]`MainLayout` by defining the layout for the route:

[source,java]
----
@Tag("div")
@Route(value = "company", layout = MainLayout.class)
public class CompanyComponent extends Component {
}
----

.Default Render Location
[NOTE]
When using the <<route#,`@Route("path")`>> annotation to define a route, the component renders by default in the `<body>` tag on the page when there is no `@Layout` for `RouterLayout`. This is because the element returned by [methodname]`HasElement.getElement()` is attached to the `<body>` tag.


=== Layout Matching Routes

To configure which routes a [annotationname]`@Layout` annotated [classname]`RouterLayout` handles, the prefix of the route can be given for the value. For example, a value of `/user` would match routes starting with a route path `/user/`:

[source,java]
----
@Layout(value="/user/")
----

This would match `/user/info`, for instance. The default value is `/`, which matches all paths.


=== Multiple Router Target Components

Where multiple router target components use the same parent layout, the parent layout instances remain the same when the user navigates between the child components.

See <<page-titles#,Updating Page Title on Navigation>> for more.


=== Multiple Parent Layouts

Use the `@ParentLayout` annotation to define a parent layout for components in the routing hierarchy.

You can create a parent layout for a parent layout, where necessary.

In the example below, `MainLayout` is used for everything and `MenuBar` reused for views:

[source,java]
----
public class MainLayout extends Div
        implements RouterLayout {
}

@Layout
@ParentLayout(MainLayout.class)
public class MenuBar extends Div
        implements RouterLayout {
    public MenuBar() {
        addMenuElement(TutorialView.class, "Tutorial");
        addMenuElement(IconsView.class, "Icons");
    }
    private void addMenuElement(
            Class<? extends Component> navigationTarget,
            String name) {
        // implementation omitted
    }
}

@Route(value = "tutorial")
public class TutorialView extends Div {
}

@Route(value = "icons")
public class IconsView extends Div {
}
----

`MainLayout` encapsulates `MenuBar`, which in turn encapsulates `TutorialView` or `IconsView`, depending on where the user has navigated.


== ParentLayout Route Control

Annotating a parent layout with `@RoutePrefix("prefix_to_add")` adds a prefix to its children's route.

In the example here, `PathComponent` receives the `some` prefix from its parent, resulting in `some/path` as its final route:

[source,java]
----
@Route(value = "path", layout = SomeParent.class)
public class PathComponent extends Div {
    // Implementation omitted
}

@RoutePrefix("some")
public class SomeParent extends Div
        implements RouterLayout {
    // Implementation omitted
}
----


=== Absolute Routes

A child component can bypass the parent's route _prefix_ by adding `absolute = true` to its own `@Route` or `@RoutePrefix` annotations.

This example shows building a [classname]`MyContent` class to add "something" to multiple places in the `SomeParent` layout, without adding the route prefix to the navigation path:

[source,java]
----
@Route(value = "content", layout = SomeParent.class,
       absolute = true)
public class MyContent extends Div {
    // Implementation omitted
}
----

Even though the full path would typically be `some/content`, the result is actually only `content`, because it has been defined as "absolute".

The example here defines `absolute = true` in the middle of the chain:

[source,java]
----
@RoutePrefix(value = "framework", absolute = true)
@ParentLayout(SomeParent.class)
public class FrameworkSite extends Div
        implements RouterLayout {
    // Implementation omitted
}

@Route(value = "tutorial", layout = FrameworkSite.class)
public class Tutorials extends Div {
    // Implementation omitted
}
----

The bound route is `framework/tutorial`, even though the full chain is `some/framework/tutorial`.

If a parent layout defines a `@RoutePrefix`, the "default" child could have its route defined as `@Route("")` and be mapped to the parent layout route.
For example, `Tutorials` with route `""` would be mapped as `framework/`.


[discussion-id]`7A96749F-CD19-4422-A2A2-B4ACD719C9FA`
