---
tab-title: Usage
layout: tabbed-page
title: Tree Grid
description: Tree Grid is a component for displaying hierarchical tabular data grouped into expandable nodes.
---


:react:

= Tree Grid

// tag::description[]
Tree Grid is a component for displaying hierarchical tabular data grouped into expandable nodes.
// end::description[]

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/tree-grid/tree-grid-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/treegrid/TreeGridBasic.java[render,tags=snippet,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Person.java[group=Java,tags=snippet]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/tree-grid/react/tree-grid-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

.Features Shared with Grid
[NOTE]
Tree Grid is an extension of the Grid component. Therefore, all of Grid's features are available in Tree Grid.


== Tree Column

The tree column is a column that contains the toggles for expanding and collapsing nodes. Nodes are opened and closed by clicking a tree column's cell. They can also be toggled programmatically.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/tree-grid/tree-grid-column.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/treegrid/TreeGridColumn.java[render,tags=snippet,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Person.java[group=Java,tags=snippet]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/tree-grid/react/tree-grid-column.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Rich Content

Like Grid, Tree Grid supports rich content.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/tree-grid/tree-grid-rich-content.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/treegrid/TreeGridRichContent.java[render,tags=snippet,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Person.java[group=Java,tags=snippet]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/tree-grid/react/tree-grid-rich-content.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Best Practices

Tree Grid isn't meant to be used as a navigation menu.

== Related Components

[cols="1,2"]
|===
|Component |Usage Recommendation

|<<../grid#,Grid>>
|Component for showing tabular data.

|<<../grid-pro#,Grid Pro>>
|Component for showing and editing tabular data.

|<<../crud#,CRUD>>
|Component for creating, displaying, updating, and deleting tabular data.

|===




++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++
