---
title: Flow
page-title: TODO Write page-title
description: TODO Write description
meta-description: TODO Write meta-description
order: 5
---


= Populate a Form in Flow
:toclevels: 2

TODO

This guide covers the basics to get you started. For more details, see the <<{articles}/flow/binding-data#,Flow Forms & Data Binding Reference Guide>>.



You can choose to call the setter method directly after a field has been changed. This is called _non-buffered mode_ and means that the form model and the form are in synch with each other. This is useful if you're doing validation inside the form model. This is, however, not the only way to validate a form -- see the <<../validate-form#,Validate a Form>> guide for details.

You can also choose to call the setter methods when the form is saved, right before the bean is sent to an application service for processing. This is called _buffered mode_ (i.e., the form buffers the changes until it is time to save them).


== Populating the Form

When you populate a form with existing data, you first retrieve the data object -- a bean or a record -- from an application service. You then ask the binder to *read data from the data object*. The API for this is slightly different depending on whether you're using beans or records.

The following examples assume the application service has an interface that looks like this:

.ProposalService.java
[source,java]
----
public interface ProposalService {
    Optional<Proposal> findById(Long proposalId);    
}
----

== Reading from a Bean

TODO


== Reading from a Record

To populate a form from a record, you call the `readRecord()` method on the binder.

[source,java]
----
@Route
public class ProposalFormView extends VerticalLayout 
        implements HasUrlParameter<Long> { // <1>

    private final ProposalService proposalService;
    private final Binder<ProposalRecord> binder;

    public ProposalFormView(ProposalService proposalService) {
        this.proposalService = proposalService;
        // Creating and adding fields omitted for clarity
        // ...
// tag::snippet[]
        binder = new Binder<>(Proposal.class); // <2>
// end::snippet[]

        // Field bindings omitted for clarity
        // ...
    }

    @Override
    public void setParameter(BeforeEvent beforeEvent, 
            @OptionalParameter Long propsalId) { // <3>
        if (proposalId != null) {
            proposalService.findById(proposalId).ifPresent(Binder::readRecord);
        }
    }
}
----

// TODO Add mini tutorial later. It should be about creating a proper form for adding new tasks to the todo list.