---
title: Servlet Container
page-title: How to deploy Hilla apps to servlet containers | Vaadin
description: Deploying a Hilla application to a traditional servlet container, such as Tomcat or Jetty.
meta-description: Deploy Hilla applications to servlet containers for enhanced flexibility.
order: 20
---

= Deploying Using a Servlet Container

Deploying a Hilla application to traditional servlet containers, such as Tomcat, Jetty or any Java/Jakarta EE server, is really no different from other web applications.
You just need to ensure that you use the production profile in your build in order to get optimal performance.

Follow the official documentation of your servlet container for best practices for production deployment.

Note: If you are using our Spring Boot starter, that first needs to be converted to a `WAR` file packaging.

== Embedded Servlet Containers

As is done by default in Spring Boot applications, many servlet containers can be embedded in your application and so be packaged as executable `JAR` files.
Follow examples from your favorite Servlet container.
