---
title: Board
description: Board is a powerful and easy-to-use layout element for building responsive views.
section-nav: commercial
---

= Board

:commercial-feature: Board
include::{articles}/_commercial-banner.asciidoc[opts=optional]

It reorders the components inside it on different screen sizes while maximizing the use of available space.

Use Board to create responsive views and dashboards that work on any screen size.

== Responsive

Board is responsive by default, meaning that it doesn't require any custom development.
Its layout is automatically optimized and adjusted based on the screen size, ensuring that the components use all available space.

== Rows & Columns

Board contains rows.
Each row supports up to four columns and can contain up to four components.

=== Nested Rows

Rows can be nested for finer-grained control of how certain areas of the layout behave on resize, and how they are rendered.

=== Column Wrapping

Columns automatically wrap on to new lines as the viewport narrows.

// Allowing "equally"
pass:[<!-- vale Vaadin.Weasel = NO -->]

=== Column Span

By default, the components in a row share the space equally.
By setting its column span, a component can stretch across two or three columns.

pass:[<!-- vale Vaadin.Weasel = YES -->]


== Breakpoints

Board adjusts its layout based on the layout container width.
The following three container widths, called breakpoints, trigger a layout change:

|===
| Breakpoint | Container width | Max number of columns

| large
| ≥ 960 pixels
| 4

| medium
| 600–959 pixels
| 2 or 3footnote:[A row with three equal-width components doesn't wrap until the small breakpoint.]

| small
| < 600 pixels
| 1
|===

Breakpoints can be customized by overriding the CSS custom properties `--vaadin-board-width-small` and `--vaadin-board-width-medium`.

=== Breakpoint-Specific Styling

You can apply different styles for each breakpoint, for example to change the font size and space between components.

:component-path: board
include::{articles}/react/components/_vaadindocs.adoc[]
