---
title: Styling
order: 50
---
= Styling

include::../_styling-section-intros.adoc[tag=selectors]


=== Tabsheet
[Horizontal, labelwidth=33]
Root element:: `vaadin-tabsheet`
Tabs wrapper:: `vaadin-tabsheet+++<wbr>+++**::part(tabs-container)**`
Content wrapper:: `vaadin-tabsheet+++<wbr>+++**::part(content)**`
Content loading indicator:: `vaadin-tabsheet+++<wbr>+++**::part(loader)**`


=== Tabs
[Horizontal, labelwidth=33]
Root element:: `vaadin-tabs`
Horizontal tabs:: `vaadin-tabs+++<wbr>+++**[orientation="horizontal"]**`
Vertical tabs:: `vaadin-tabs+++<wbr>+++**[orientation="vertical"]**`
Tab container:: `vaadin-tabs+++<wbr>+++**::part(tabs)**`
Back button:: `vaadin-tabs+++<wbr>+++**::part(back-button)**`
Back button icon:: `vaadin-tabs+++<wbr>+++**::part(back-button)::after**`
Forward button:: `vaadin-tabs+++<wbr>+++**::part(forward-button)**`
Forward button icon:: `vaadin-tabs+++<wbr>+++**::part(forward-button)::after**`


=== Tab
[Horizontal, labelwidth=33]
Root element:: `vaadin-tab`
Selected:: `vaadin-tab+++<wbr>+++**[selected]**`
Focused:: `vaadin-tab+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-tab+++<wbr>+++**[focus-ring]**`
Pressed:: `vaadin-tab+++<wbr>+++**[active]**`
Hovered:: `vaadin-tab+++<wbr>+++**::hover**`
Disabled:: `vaadin-tab+++<wbr>+++**[disabled]**`
Selection indicator:: `vaadin-tab+++<wbr>+++**::before**`
