---
title: Component Variants
order: 50
layout: page
---

= Component Variants

[.lead]
Many Vaadin components have so-called theme variants that provide different styles for the component.
These are defined as part of the built-in Lumo and Material themes, and documented for each component.

For example, Button has a "primary" variant, which can be used as follows:

[.example]
--

.Java
[source,java]
----
Button btn = new Button("Primary variant");
btn.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
----

.TypeScript
[source,typescript]
----
<vaadin-button theme="primary">Primary variant</vaadin-button>
----

--

Multiple theme variants can be simultaneously applied to a component, although not all variants are designed to be used together.

[.example]
--

[source,java]
----
Button btn = new Button("Primary + Small");
btn.addThemeVariants(ButtonVariant.LUMO_PRIMARY, ButtonVariant.LUMO_SMALL);
----

[source,typescript]
----
<vaadin-button theme="primary small">Primary + Small</vaadin-button>
----
--

== Variant Inheritance

Theme variants differ from CSS class names mainly in that they are automatically applied to sub-components within the shadow DOM of the component to which they are applied.
For example, <<{articles}/components/crud#, CRUD>> contains a <<{articles}/components/grid#, Grid>> in its shadow DOM, so theme variants applied to a CRUD are automatically passed down to the Grid inside.
This means that you can apply Grid variants to a CRUD, even though the variants aren't defined in the CRUD theme.

[.example]
--

[source,java]
----
Crud<Person> crud = new Crud<>();

// Apply a Grid theme variant to the CRUD
crud.getElement().getThemeList().add(GridVariant.LUMO_ROW_STRIPES.getVariantName());
----

[source,html]
----
<vaadin-crud theme="row-stripes"></vaadin-crud>
----
--

Variant inheritance only works for sub-components in the shadow DOM, not with regular “light DOM” children of a component.
For example, Accordion Panel components inside an Accordion need to have their variants <<{articles}/components/accordion/#theme-variants, applied to each panel>>.

== Custom Variants

You can define your own component theme variants using component-specific style sheets in a <<{articles}/styling/custom-theme/creating-custom-theme#, custom theme>>.

.[filename]#vaadin-button.css#
[example,css]
----
:host([theme~="rounded"]) {
  border-radius: 1em;
}
----

You can then apply the theme variant similarly to the built-in variants:

[.example]
--

[source,java]
----
Button btn = new Button("Rounded");
btn.getThemeList().add("rounded");
----

[source,typescript]
----
<vaadin-button theme="rounded">Rounded</vaadin-button>
----
--

These are inherited to sub-components similarly to the built-in variants.

See <<styling-components#, Styling Components>> to learn how to target the internal parts of Vaadin components.


[.discussion-id]
59B1D952-A932-4AA1-BFA6-B7831FFFF18C

