---
title: Styling
order: 50
---
= Styling

include::../_styling-section-intros.adoc[tag=selectors]

[Horizontal, labelwidth=33]
Root element:: `vaadin-email-field`


=== States
[Horizontal, labelwidth=33]
Required:: `vaadin-email-field+++<wbr>+++**[required]**`
Focused:: `vaadin-email-field+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-email-field+++<wbr>+++**[focus-ring]**`
Read-only:: `vaadin-email-field+++<wbr>+++**[readonly]**`
Disabled:: `vaadin-email-field+++<wbr>+++**[disabled]**`
Not empty:: `vaadin-email-field+++<wbr>+++**[has-value]**`
Hovered:: `vaadin-email-field+++<wbr>+++**:hover**`


=== Field
[Horizontal, labelwidth=33]
Field surface (background, border):: `vaadin-email-field+++<wbr>+++**::part(input-field)**`
Native input element:: `vaadin-email-field+++<wbr>+++** > input**`
Input field with placeholder shown:: `vaadin-email-field+++<wbr>+++** > input:placeholder-shown**`
Clear button:: `vaadin-email-field+++<wbr>+++**::part(clear-button)**`
Clear button icon:: `vaadin-email-field+++<wbr>+++**::part(clear-button)::before**`
Prefix element:: `vaadin-email-field+++<wbr>+++** > [slot="prefix"]**`
Suffix element:: `vaadin-email-field+++<wbr>+++** > [slot="suffix"]**`


=== Label
[Horizontal, labelwidth=33]
Field with label:: `vaadin-email-field+++<wbr>+++**[has-label]**`
Label:: `vaadin-email-field+++<wbr>+++**::part(label)**`
Label text:: `vaadin-email-field+++<wbr>+++** > label**`
Required indicator:: `vaadin-email-field+++<wbr>+++**::part(required-indicator)**`


=== Helper and Validation Error
[Horizontal, labelwidth=33]
Field with helper:: `vaadin-email-field+++<wbr>+++**[has-helper]**`
Helper:: `vaadin-email-field+++<wbr>+++**::part(helper-text)**`
Helper text:: `vaadin-email-field+++<wbr>+++** > [slot="helper"]**`
Invalid field:: `vaadin-email-field+++<wbr>+++**[invalid]**`
Error message:: `vaadin-email-field+++<wbr>+++**::part(error-message)**`
Error message text:: `vaadin-email-field+++<wbr>+++** > [slot="error-message"]**`