---
title: Styling
page-title: How to style the Radio Button component | Vaadin components
description: Styling API reference for the Radio Button and Radio Button Group components.
meta-description: Customize the look of the Vaadin Radio Button component in your applications to align with your design system.
order: 50
---
= Radio Button Styling

// Style Variants

include::{articles}/components/_input-field-common-features.adoc[tags=styles-start;helper-above-field;styles-end]

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/radiobutton/radio-button-group-styles.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/radiobutton/RadioButtonGroupStyles.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/radiobutton/react/radio-button-group-styles.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--



include::../_styling-section-theming-props.adoc[tag=style-properties]

include::../_styling-section-theming-props.adoc[tag=input-fields]

=== Radio Button Properties

[cols="2,1"]
|===
| Property | Supported By

|`--vaadin-radio-button-background`
|Aura, Lumo

|`--vaadin-radio-button-background-hover`
|Lumo

|`--vaadin-radio-button-border-color`
|Aura

|`--vaadin-radio-button-border-width`
|Aura

|`--vaadin-radio-button-disabled-background`
|Lumo

|`--vaadin-radio-button-disabled-dot-color`
|Lumo

|`--vaadin-radio-button-dot-color`
|Aura, Lumo

|`--vaadin-radio-button-dot-size`
|Aura, Lumo

|`--vaadin-radio-button-gap`
|Aura

|`--vaadin-radio-button-label-color`
|Lumo

|`--vaadin-radio-button-label-font-size`
|Lumo

|`--vaadin-radio-button-label-padding`
|Lumo

|`--vaadin-radio-button-marker-color`
|Aura

|`--vaadin-radio-button-marker-size`
|Aura

|`--vaadin-radio-button-size`
|Aura, Lumo

|===

include::../_styling-section-theming-props.adoc[tag=label-helper-error]

include::../_styling-section-intros.adoc[tag=selectors]


=== Radio Button

Root element:: `vaadin-radio-button`
Focused:: `vaadin-radio-button+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-radio-button+++<wbr>+++**[focus-ring]**`
Disabled:: `vaadin-radio-button+++<wbr>+++**[disabled]**`
Hovered:: `vaadin-radio-button+++<wbr>+++**:hover**`
Pressed:: `vaadin-radio-button+++<wbr>+++**[active]**`
Selected:: `vaadin-radio-button+++<wbr>+++**[checked]**`
Indeterminate:: `vaadin-radio-button+++<wbr>+++**[indeterminate]**`
Radio ring:: `vaadin-radio-button+++<wbr>+++**::part(radio)**`
Selection dot:: `vaadin-radio-button+++<wbr>+++**::part(radio)::after**`
Label:: `vaadin-radio-button+++<wbr>+++** > label**`


=== Radio Button Group

Root element:: `vaadin-radio-group`


==== States

Focused:: `vaadin-radio-group+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-radio-group+++<wbr>+++**[focus-ring]**`
Disabled:: `vaadin-radio-group+++<wbr>+++**[disabled]**`
Hovered:: `vaadin-radio-group+++<wbr>+++**:hover**`
Has selection:: `vaadin-radio-group+++<wbr>+++**[has-value]**`


==== Parts

Radio button wrapper:: `vaadin-radio-group+++<wbr>+++**::part(group-field)**`
Radio buttons:: `vaadin-radio-group+++<wbr>+++** > vaadin-radio-button**`


==== Label

Radio group with label:: `vaadin-radio-group+++<wbr>+++**[has-label]**`
Label:: `vaadin-radio-group+++<wbr>+++**::part(label)**`
Label text:: `vaadin-radio-group+++<wbr>+++** > label**`
Required indicator:: `vaadin-radio-group+++<wbr>+++**::part(required-indicator)**`


==== Helper and Validation Error

Field with helper:: `vaadin-radio-group+++<wbr>+++**[has-helper]**`
Helper:: `vaadin-radio-group+++<wbr>+++**::part(helper-text)**`
Helper text:: `vaadin-radio-group+++<wbr>+++** > [slot="helper"]**`
Invalid field:: `vaadin-radio-group+++<wbr>+++**[invalid]**`
Field with error message:: `vaadin-radio-group+++<wbr>+++**[has-error-message]**`
Error message:: `vaadin-radio-group+++<wbr>+++**::part(error-message)**`
Error message text:: `vaadin-radio-group+++<wbr>+++** > [slot="error-message"]**`
