---
title: Styling
description: Styling API reference for the Radio Button and Radio Button Group components.
order: 50
---
= Styling

include::../_styling-section-theming-props.adoc[tag=style-properties]

include::../_styling-section-theming-props.adoc[tag=input-fields]

=== Radio Button Properties

[cols="1,2,2"]
|===
| Feature | Property | Default Value

|Radio background
|`--vaadin-radio-button-background`
|`--lumo-contrast-20pct`

|Radio background, hover
|`--vaadin-radio-button-background-hover`
|`--lumo-contrast-30pct`

|Radio dot size
|`--vaadin-radio-button-dot-size`
|`3px`

|Radio dot color
|`--vaadin-radio-button-dot-color`
|`--lumo-primary-contrast-color`

|Label color
|`--vaadin-radio-button-label-color`
|`--lumo-body-text-color`

|Label font size
|`--vaadin-radio-button-label-font-size`
|`--lumo-font-size-m`

|Label padding
|`--vaadin-radio-button-label-padding`
|`--lumo-space-xs`

|===

include::../_styling-section-theming-props.adoc[tag=label-helper-error]

include::../_styling-section-intros.adoc[tag=selectors]


=== Radio Button

Root element:: `vaadin-radio-button`
Focused:: `vaadin-radio-button+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-radio-button+++<wbr>+++**[focus-ring]**`
Disabled:: `vaadin-radio-button+++<wbr>+++**[disabled]**`
Hovered:: `vaadin-radio-button+++<wbr>+++**:hover**`
Pressed:: `vaadin-radio-button+++<wbr>+++**[active]**`
Selected:: `vaadin-radio-button+++<wbr>+++**[checked]**`
Indeterminate:: `vaadin-radio-button+++<wbr>+++**[indeterminate]**`
Radio ring:: `vaadin-radio-button+++<wbr>+++**::part(radio)**`
Selection dot:: `vaadin-radio-button+++<wbr>+++**::part(radio)::after**`
Label:: `vaadin-radio-button+++<wbr>+++** > label**`


=== Radio Button Group

Root element:: `vaadin-radio-group`


==== States

Focused:: `vaadin-radio-group+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-radio-group+++<wbr>+++**[focus-ring]**`
Disabled:: `vaadin-radio-group+++<wbr>+++**[disabled]**`
Hovered:: `vaadin-radio-group+++<wbr>+++**:hover**`
Has selection:: `vaadin-radio-group+++<wbr>+++**[has-value]**`


==== Parts

Radio button wrapper:: `vaadin-radio-group+++<wbr>+++**::part(group-field)**`
Radio buttons:: `vaadin-radio-group+++<wbr>+++** > vaadin-radio-button**`


==== Label

Radio group with label:: `vaadin-radio-group+++<wbr>+++**[has-label]**`
Label:: `vaadin-radio-group+++<wbr>+++**::part(label)**`
Label text:: `vaadin-radio-group+++<wbr>+++** > label**`
Required indicator:: `vaadin-radio-group+++<wbr>+++**::part(required-indicator)**`


==== Helper and Validation Error

Field with helper:: `vaadin-radio-group+++<wbr>+++**[has-helper]**`
Helper:: `vaadin-radio-group+++<wbr>+++**::part(helper-text)**`
Helper text:: `vaadin-radio-group+++<wbr>+++** > [slot="helper"]**`
Invalid field:: `vaadin-radio-group+++<wbr>+++**[invalid]**`
Error message:: `vaadin-radio-group+++<wbr>+++**::part(error-message)**`
Error message text:: `vaadin-radio-group+++<wbr>+++** > [slot="error-message"]**`

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++
