---
tab-title: Usage
layout: tabbed-page
title: Side Navigation
description: How to add a vertical list of navigation links, generally placed to one side of a view.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/side-nav}/#/elements/vaadin-side-nav[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/sidenav/SideNav.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/side-nav}/packages/side-nav[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-side-nav-flow-parent[Java]'
---

++++
<style>
[class^=PageHeader-module-descriptionContainer] {display: none;}
</style>
++++


= Side Navigation

// tag::description[]
The Side Navigation component provides a vertical list of navigation links with support for collapsible, nested sections.
// end::description[]

.Preview Feature
[IMPORTANT]
====
This is a preview release of the Side Navigation component. Its behavior, API, and look and feel might change. In order to use this component, it must be explicitly enabled with a feature flag. See the <<Feature Flag>> section to learn how to do this.
====

.Navigation Disabled in Samples
[NOTE]
====
For technical reasons actual navigation is disabled in the samples on this page.
====


[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/side-nav/side-nav-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/sidenav/SideNavBasic.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/side-nav/react/side-nav-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

The navigation item whose path matches the current URL is highlighted as active. The Side Navigation component can be used, for example, in the drawer of an <<../app-layout#,App Layout>>.


== Prefix & Suffix Elements

Navigation items have slots for prefix and suffix elements. The prefix slot is primarily intended for icons, while the suffix slot can be used, for example, for notification badges.

Interactive prefix and suffix elements aren't recommended since the entire item row acts as a link.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/side-nav/side-nav-suffix.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/sidenav/SideNavSuffix.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/side-nav/react/side-nav-suffix.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Hierarchy

Navigation items can contain sub-items, which are collapsed by default. There's no technical limitation on the number of nesting levels, but a maximum of three levels is recommended for better usability.

Parent items can be links. Clicking them expands their sub-items in addition to navigating. Non-link parent items can be achieved by omitting the target path.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/side-nav/side-nav-hierarchy.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/sidenav/SideNavHierarchy.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/side-nav/react/side-nav-hierarchy.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Labelled Collapsible List

A label can be applied to the top of the navigation list. This can be useful for cases with multiple adjacent Side Navigation lists. A labeled Side Navigation list can be made collapsible.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/side-nav/side-nav-labelled.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/sidenav/SideNavLabelled.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/side-nav/react/side-nav-labelled.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Scrolling

The Side Navigation component doesn't contain a scroll area. Instead, it can be made scrollable by wrapping it inside a <<../scroller#,Scroller>>.


== Keyboard Usage

[cols="1,2"]
|===
|Shortcut |Function

|kbd:[Tab]
|Navigation between list items.

|kbd:[Tab]
|Navigation between link and expand/collapse button.

|kbd:[Enter] / kbd:[Space]
|Toggles expand/collapse.

|kbd:[Enter]
|Trigger link.

|===


== Styling Individual Items

Individual navigation items can be styled by applying a CSS class name to them.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/side-nav/side-nav-styling.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/sidenav/SideNavStyling.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

[source,css]
----
include::{root}/frontend/themes/docs/nav-item-styling.css[tags=snippet,indent=0]
----


ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/side-nav/react/side-nav-styling.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Feature Flag

In order to use the Side Navigation component, it must be explicitly enabled with a feature flag. To do this, there are two methods: use Vaadin Developer Tools; or add a Feature Flags properties file.

To use Developer Tools, click its icon button in your running application. Then open the [guilabel]*Feature Flags* tab. Enable the [guilabel]*SideNav component* feature and restart the application.

To add a Feature Flags properties file, first create a [filename]#src/main/resources/vaadin-featureflags.properties# file in your application folder. Add to it `com.vaadin.experimental.sideNavComponent=true`. Then restart the application.


[discussion-id]`10387B24-0DDF-4FC8-B5F9-B6319633D354`
