---
title: Styling
page-title: How to style Side Navigation | Vaadin components
description: Styling API reference for the Side Nav component.
meta-description: Explore styling options for creating a visually appealing side navigation in your Vaadin applications.
order: 50
---
= Side Navigation Styling

== Style Variants

Side navigation supports the following style variants.

[cols="1,3,1"]
|===
| Variant | Description | Supported by

|`filled`
|Uses a solid background color for active item
|Aura

|===

include::../_styling-section-theming-props.adoc[tag=style-properties]

==== Side Nav Properties

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-side-nav-label-color`
|Aura

|`--vaadin-side-nav-label-font-size`
|Aura

|`--vaadin-side-nav-label-font-weight`
|Aura

|`--vaadin-side-nav-label-line-height`
|Aura

|===

==== Side Nav Item Properties

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-side-nav-item-background`
|Aura

|`--vaadin-side-nav-item-border-color`
|Aura

|`--vaadin-side-nav-item-border-radius`
|Aura

|`--vaadin-side-nav-item-border-width`
|Aura

|`--vaadin-side-nav-item-font-size`
|Aura

|`--vaadin-side-nav-item-font-weight`
|Aura

|`--vaadin-side-nav-item-line-height`
|Aura

|`--vaadin-side-nav-item-gap`
|Aura

|`--vaadin-side-nav-item-padding`
|Aura

|`--vaadin-side-nav-item-text-color`
|Aura

|===

include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-side-nav`


== Parts

Header (above list):: `vaadin-side-nav+++<wbr>+++**::part(label)**`
Label:: `vaadin-side-nav+++<wbr>+++** > [slot="label"]**`
Expand/collapse toggle:: `vaadin-side-nav+++<wbr>+++**::part(toggle-button)**`
Expand/collapse icon:: `vaadin-side-nav+++<wbr>+++**::part(toggle-button)::before**`

== States

Collapsible list:: `vaadin-side-nav+++<wbr>+++**[collapsible]**`
Collapsed list:: `vaadin-side-nav+++<wbr>+++**[collapsed]**`


== Navigation Item

Item root element:: `vaadin-side-nav-item`
Current view/page item:: `vaadin-side-nav-item+++<wbr>+++**[current]**`
Item with link:: `vaadin-side-nav-item+++<wbr>+++**[path]**`
Item without link:: `vaadin-side-nav-item+++<wbr>+++**:not([path])**`
Item contents (excl. children):: `vaadin-side-nav-item+++<wbr>+++**::part(content)**`
Link label (incl. prefix/suffix):: `vaadin-side-nav-item+++<wbr>+++**::part(link)**`
Item prefix element:: `vaadin-side-nav-item+++<wbr>+++** > [slot="prefix"]**`
Item suffix element:: `vaadin-side-nav-item+++<wbr>+++** > [slot="suffix"]**`
Item icon:: `vaadin-side-nav-item+++<wbr>+++** > vaadin-icon**`


=== Parent and Child Items

Expand/collapse toggle:: `vaadin-side-nav-item+++<wbr>+++**::part(toggle-button)**`
Expand/collapse toggle icon:: `vaadin-side-nav-item+++<wbr>+++**::part(toggle-button)::before**`
Expanded item:: `vaadin-side-nav-item+++<wbr>+++**[expanded]**`
Child item:: `vaadin-side-nav-item+++<wbr>+++**[slot="children"]**`
