---
tab-title: Usage
layout: tabbed-page
title: Multi-Select Combo Box
description: Adding a combo box to a project for users to be able to make multiple selections.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:multi-select-combo-box}/#/elements/vaadin-multi-select-combo-box[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/combobox/MultiSelectComboBox.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:multi-select-combo-box}/packages/multi-select-combo-box[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-combo-box-flow-parent[Java]'
---


= [since:com.vaadin:vaadin@V23.2]#Multi-Select Combo Box#
:experimental:

// tag::description[]
Multi-Select Combo Box allows the user to choose one or more values from a filterable list of options presented in an overlay.
// end::description[]
The component <<../combo-box#,supports the same features as the regular Combo Box>>, such as lazy loading or allowing custom typed values. This page explains how to add this component to your project and how to configure it.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/multi-select-combo-box/multi-select-combo-box-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/generated/com/vaadin/demo/domain/Country.ts[group=TypeScript]
----
endif::[]


ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxBasic.java[render,tags=snippet,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Country.java[group=Java,tags=*,indent=0]
----
endif::[]


ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/multi-select-combo-box/react/multi-select-combo-box-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

The overlay opens when the user clicks the field using a pointing device. Using the kbd:[Up] and kbd:[Down]arrow keys or typing a character (that occurs in at least one of the options) when the field is focused also opens the popup.


== Common Combo Box Features

Multi-Select Combo Box supports the following features from the regular Combo Box. All the linked examples and code snippets can be applied by replacing the Combo Box with a Multi-Select Combo Box.

- <<../combo-box#custom-value-entry, Custom Value Entry>>
- <<../combo-box#custom-item-representation, Custom Item Presentation>>
- <<../combo-box#auto-open, Auto Open>>
- <<../combo-box#placeholder, Placeholder>>
- <<../combo-box#custom-filtering, Custom Filtering>>
- <<../combo-box#popup-width, Popup Width>>, using the `--vaadin-multi-select-combo-box-overlay-width` style, instead of `--vaadin-combo-box-overlay-width`


== Selection

The component allows selecting multiple values, each of which is displayed as a chip inside the component. If there isn't enough space in the component to display chips for all selected values, then some values are collapsed into an overflow chip. The example below shows a Multi-Select Combo Box with multiple preselected values, some of which are collapsed into the overflow chip:

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/multi-select-combo-box/multi-select-combo-box-selection.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/generated/com/vaadin/demo/domain/Country.ts[group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxSelection.java[render,tags=snippet,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Country.java[group=Java,tags=*,indent=0]
----
endif::[]


ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/multi-select-combo-box/react/multi-select-combo-box-selection.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

When the overlay is closed, items can be removed one by one (starting with the most recently selected item) using the kbd:[Backspace] key. The first kbd:[Backspace] press moves focus to the last chip; the second press removes that chip, and the corresponding item, from the selection.


=== Selection Change

The following example demonstrates how to listen for selection changes:

[.example]
--

Use the `selected-items-changed` event to react to the user changing the selection.

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/multi-select-combo-box/multi-select-combo-box-selection-change.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/generated/com/vaadin/demo/domain/Country.ts[group=TypeScript]
----
endif::[]

Use [methodname]`addValueChangeListener()` to be notified about the user changing the selection. Alternatively, [methodname]`addSelectionChangeListener()` can be used to get more detailed information about the selection change.

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxSelectionChange.java[render,tags=snippet,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Country.java[group=Java,tags=*,indent=0]
----
endif::[]


ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/multi-select-combo-box/react/multi-select-combo-box-selection-change.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Read-Only

The component can be set to read-only, which prevents the user from modifying its value. A read-only Multi-Select Combo Box still allows opening the overlay, which then shows only the selected values, instead of all the options. This can be useful if selected values have been collapsed into the overflow chip.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/multi-select-combo-box/multi-select-combo-box-read-only.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxReadOnly.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]


ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/multi-select-combo-box/react/multi-select-combo-box-read-only.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

[role="since:com.vaadin:vaadin@V24.3"]
== Auto Expand

The component can be configured to auto-expand in order to accommodate chips for selected items. It is possible to expand both horizontally (until max-width is reached) and vertically (in which case the field with chips wraps in multiple lines). These modes can be also used together.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/multi-select-combo-box/multi-select-combo-box-auto-expand.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxAutoExpand.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]


ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/multi-select-combo-box/react/multi-select-combo-box-auto-expand.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


[role="since:com.vaadin:vaadin@V24.3"]
== Selected Items on Top

The component can be configured to group selected items at the top of the overlay. When selection changes, a set of items to be shown in the top group is only updated after the overlay is closed.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/multi-select-combo-box/multi-select-combo-box-selected-items-on-top.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxSelectedItemsOnTop.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]


ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/multi-select-combo-box/react/multi-select-combo-box-selected-items-on-top.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Internationalization (i18n)

Multi-Select Combo Box allows localizing the following messages. These texts are only used in screen reader announcements, and can't be observed visually.

[cols="1,1,3"]
|===
| Message | Default | Description

|`cleared`
|"Selection cleared"
|Announced by screen readers when the clear button is clicked

|`focused`
|" focused. Press Backspace to remove"
|Announced by screen readers when a chip is focused

|`selected`
|" added to selection"
|Announced by screen readers when an item is added to the selection.

|`deselected`
|" removed from selection"
|Announced by screen readers when an item is removed from the selection.

|`total`
|"\{count} items selected"
|Announced by screen readers to inform about the total number of selected items.
The string must contain a `\{count}` placeholder, which is replaced with the actual count of selected items by the component.
|===

The following example demonstrates how to localize the component's messages into German:

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/multi-select-combo-box/multi-select-combo-box-i18n.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxI18nDemo.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]


ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/multi-select-combo-box/react/multi-select-combo-box-i18n.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Best Practices

Multi-Select Combo Box supports lazy loading for large datasets. It reduces the initial load time, and consumes less bandwidth and resources.

For consistency, the default width of the Multi-Select Combo Box matches that of other input fields. You should increase the width of the component when using items with long labels, or if you expect users to select several items, to avoid collapsing selected items into the overflow chip.

.Example of Increasing Component Width
[.example]
--
ifdef::lit[]
[source,html]
----
<vaadin-multi-select-combo-box
  style="width: 300px"
></vaadin-multi-select-combo-box>
----
endif::[]
ifdef::flow[]
[source,Java]
----
comboBox.setWidth("300px");
----
endif::[]
ifdef::react[]
[source,tsx]
----
<MultiSelectComboBox style={{ width: '300px' }} />
----
endif::[]
--


== Related Components

[cols="1,2"]
|===
|Component |Usage recommendations

|<<../combo-box#,Combo Box>>
|Same feature set, but for selecting a single value.

|<<../list-box#,List Box>>
|Scrollable inline list of options. Supports single and multi-select.

|<<../checkbox#,Checkbox Group>>
|Serves the same purpose in a more user-friendly format, but takes up more vertical space.
|===

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++
