---
title: Multi-Select Combo Box
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:multi-select-combo-box}/#/elements/vaadin-multi-select-combo-box[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/combobox/MultiSelectComboBox.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:multi-select-combo-box}/packages/vaadin-multi-select-combo-box[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-combo-box-flow-parent[Java]'
---

= Multi-Select Combo Box

// tag::description[]
Multi-Select Combo Box allows the user to choose one or more values from a filterable list of options presented in an overlay.
// end::description[]
The component <<../combo-box#,supports the same features as the regular Combo Box>>, such as lazy loading or allowing custom typed values.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/multi-select-combo-box/multi-select-combo-box-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/generated/com/vaadin/demo/domain/Country.ts[group=TypeScript]
----


[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxBasic.java[render,tags=snippet,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Country.java[group=Java,tags=*,indent=0]
----

--

The overlay opens when the user clicks the field using a pointing device.
Using the Up/Down arrow keys or typing a character (found in at least one of the options) when the field is focused also opens the popup.


== Common Combo Box Features

Multi Select Combo Box supports the following features from the regular Combo Box. All the linked examples and code snippets can be applied by replacing the Combo Box with a Multi Select Combo Box.

* <<../combo-box#custom-value-entry, Custom Value Entry>>
* <<../combo-box#custom-item-representation, Custom Item Presentation>>
* <<../combo-box#auto-open, Auto Open>>
* <<../combo-box#placeholder, Placeholder>>
* <<../combo-box#custom-filtering, Custom Filtering>>


== Selection

The component allows selecting multiple values, each of which is displayed as a chip inside the component.
If there is not enough space in the component to display chips for all selected values, then some values will be collapsed into an overflow chip.
The example below shows a Multi-Select Combo Box with multiple preselected values, some of which are collapsed into the overflow chip:

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/multi-select-combo-box/multi-select-combo-box-selection.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/generated/com/vaadin/demo/domain/Country.ts[group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxSelection.java[render,tags=snippet,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Country.java[group=Java,tags=*,indent=0]
----

--

When the overlay is closed, items can be removed by keyboard one by one (starting with the most recently selected item) using the kbd:[Backspace] key: the first kbd:[Backspace] press moves focus to the last chip, and the second press removes that chip, and the corresponding item, from the selection.


== Best Practices

Multi Select Combo Box supports lazy loading for large datasets. It reduces the initial load time, consumes less bandwidth and resources.

For consistency, the default width of the Multi-Select Combo Box matches that of other Vaadin input fields. We recommend increasing the width of the component when using items with long labels, or if you expect users to select several items, in order to avoid collapsing selected items into the overflow chip.

.Example for increasing component width
[.example]
--
[source,html]
----
<vaadin-multi-select-combo-box
  style="width: 300px"
></vaadin-multi-select-combo-box>
----
[source,Java]
----
comboBox.setWidth("300px");
----
--


== Related Components

[cols="1,2"]
|===
|Component |Usage recommendations

|<<../combo-box#,Combo Box>>
|Same feature set, but for selecting a single value.

|<<../list-box#,List Box>>
|Scrollable inline list of options. Supports single and multi-select.

|<<../checkbox#,Checkbox Group>>
|Serves the same purpose in a more user-friendly format, but takes more vertical space.
|===
