---
title: Styling
page-title: Styling the Multi-Select Combo Box component | Vaadin
description: Styling API reference for the Multi-Select Combo Box component.
meta-description: Customize the look and behavior of multi-select combo boxes in your Vaadin applications for a better user experience.
order: 50
---
= Multi-Select Combo Box Styling

// Style Variants

include::{articles}/components/_input-field-common-features.adoc[tags=styles-start;small-variant;helper-above-field;styles-end]


include::../_styling-section-theming-props.adoc[tag=style-properties]

include::../_styling-section-theming-props.adoc[tag=input-fields]

include::../_styling-section-theming-props.adoc[tag=input-surface]

include::../_styling-section-theming-props.adoc[tag=label-helper-error]

include::../_styling-section-theming-props.adoc[tag=input-icons]

=== Overlay

[cols="2,1"]
|===
| Property | Supported By

|`--vaadin-multi-select-combo-box-overlay-width`
|Aura, Lumo

|`--vaadin-multi-select-combo-box-overlay-max-height`
|Aura, Lumo

|===


=== Miscellaneous

[cols="2,1"]
|===
| Property | Supported By

|`--vaadin-multi-select-combo-box-chip-min-width`
|Aura, Lumo

|`--vaadin-multi-select-combo-box-input-min-width`
|Aura, Lumo

|===


include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-multi-select-combo-box`


=== States

Required:: `vaadin-multi-select-combo-box+++<wbr>+++**[required]**`
Focused:: `vaadin-multi-select-combo-box+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-multi-select-combo-box+++<wbr>+++**[focus-ring]**`
Read-only:: `vaadin-multi-select-combo-box+++<wbr>+++**[readonly]**`
Disabled:: `vaadin-multi-select-combo-box+++<wbr>+++**[disabled]**`
Not empty:: `vaadin-multi-select-combo-box+++<wbr>+++**[has-value]**`
With open overlay:: `vaadin-multi-select-combo-box+++<wbr>+++**[opened]**`
Loading items:: `vaadin-multi-select-combo-box+++<wbr>+++**[loading]**`
Hovered:: `vaadin-multi-select-combo-box+++<wbr>+++**:hover**`


=== Field

Field surface (background, border):: `vaadin-multi-select-combo-box+++<wbr>+++**::part(input-field)**`
Native input element:: `vaadin-multi-select-combo-box+++<wbr>+++** > input**`
Input field with placeholder shown:: `vaadin-multi-select-combo-box+++<wbr>+++** > input:placeholder-shown**`
Clear and Toggle buttons:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(field-button)**`
Toggle Button:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(toggle-button)**`
Clear button:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(clear-button)**`
Clear button icon:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(clear-button)::before**`
Prefix element:: `vaadin-multi-select-combo-box+++<wbr>+++** > [slot="prefix"]**`
Suffix element:: `vaadin-multi-select-combo-box+++<wbr>+++** > [slot="suffix"]**`


=== Label

Field with label:: `vaadin-multi-select-combo-box+++<wbr>+++**[has-label]**`
Label:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(label)**`
Label text:: `vaadin-multi-select-combo-box+++<wbr>+++** > label**`
Required indicator:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(required-indicator)**`


=== Helper and Validation Error

Field with helper:: `vaadin-multi-select-combo-box+++<wbr>+++**[has-helper]**`
Helper:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(helper-text)**`
Helper text:: `vaadin-multi-select-combo-box+++<wbr>+++** > [slot="helper"]**`
Invalid field:: `vaadin-multi-select-combo-box+++<wbr>+++**[invalid]**`
Field with error message:: `vaadin-multi-select-combo-box+++<wbr>+++**[has-error-message]**`
Error message:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(error-message)**`
Error message text:: `vaadin-multi-select-combo-box+++<wbr>+++** > [slot="error-message"]**`


=== Chips

Chip element:: `vaadin-multi-select-combo-box-chip`
Focused chip:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**[focused]**`
Hovered chip:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**:hover**`
Chip label:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**::part(label)**`
Chip remove button:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**::part(remove-button)**`
Chip remove button icon:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**::part(remove-button)::before**`
Overflow Chip:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**[slot="overflow"]**`
Overflow-chip with 2 items:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**[count="2"]**`
Chip container inside field:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(chips)**`


=== Overlay

Overlay background:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(overlay)**`
Overlay content wrapper:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(content)**`
Overlay loading indicator:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(loader)**`


=== Items

Item element:: `vaadin-multi-select-combo-box-item`
Selected item:: `vaadin-multi-select-combo-box-item+++<wbr>+++**[selected]**`
Item selection indicator:: `vaadin-multi-select-combo-box-item+++<wbr>+++**::part(checkmark)**`
Item selection indicator icon:: `vaadin-multi-select-combo-box-item+++<wbr>+++**::part(checkmark)::before**`
Focused item:: `vaadin-multi-select-combo-box-item+++<wbr>+++**[focused]**`
Item content wrapper:: `vaadin-multi-select-combo-box-item+++<wbr>+++**::part(content)**`
Hovered item:: `vaadin-multi-select-combo-box-item+++<wbr>+++**:hover**`
