---
title: Designer
section-nav: commercial
---


[[designer.overview]]
= Designer

// Allow 'drag and drop'
pass:[<!-- vale Vaadin.Wordiness = NO -->]

:commercial-feature: Designer
include::{articles}/flow/_commercial-banner.asciidoc[opts=optional]

Vaadin Designer is a visual tool where you can drag and drop - and configure - web components on a canvas. With Designer, you always have the end result in front of you. Any change you do is instantly reflected in the live preview of the UI you are building.

xref:getting-started/setting-up-your-environment#[Get started using Designer, role="button primary water"]


== Features

WYSIWYG Design Canvas::
Drag and drop web components. Updates when the design properties or styles are changed.
+
<<using-designer/designing#,Designing>>

Quick Layout Editing::
Control VerticalLayout, HorizontalLayout, and other flex containers quickly with flexbox controls.
+
<<using-designer/layout#,Laying Out Views>>

Sizing & Spacing Panel::
Set width, height, margin, padding, spacing properties with CSS values, or Lumo presets using a drop-down.
+
<<using-designer/layout#designer.sizing.and.spacing,Sizing and spacing>>

Viewport Controls::
Quickly check the responsiveness of the design.
+
<<using-designer/previewing#designer.previewing.resize,Resizing viewport and presets>>

Palette Shows Snippets & Components::
Pre-built snippets for Vaadin components. Use any web components from the project.

Outline to Display Component Hierarchy::
Change component hierarchy using drag and drop. Connect components to the Java companion file.

Preview in Browser or Device::
View design on a mobile device with one click. Share the preview link to others.
+
<<using-designer/previewing#designer.previewing.preview,Previewing>>

Work within your Project::
Work with designs directly in your Java project. Use a Java companion file to connect design to backend data.
+
<<using-designer/java#,Connect to Java>>


[discussion-id]`C5F0925C-7BC3-429F-A253-FF5853F0FA06`

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++