---
title: Styling
description: How to add CSS styles to views and components in Hilla applications.
order: 80
---
// tag::content[]

// TODO this page could benefit from some more thought

= Styling views and layouts with CSS

== CSS theme folder

You can style components that extend [classname]`View` and [classname]`Layout` by placing CSS files in the `frontend/themes/<app-name>/` folder and importing them in [filename]`styles.css` using [methodname]`import()`.
Styles defined in the theme directory are available across the application.
You can also import styles from `node_modules`, like `line-awesome` in the following example:

.`frontend/themes/<app-name>/styles.css`
[source,css]
----
@import "line-awesome/dist/line-awesome/css/line-awesome.min.css";

@import "./main-layout.css";
@import "./views/example-view.css";
----


== Using CSS variables

Hilla uses the https://vaadin.com/docs/latest/ds/foundation[Vaadin Design System] as a base for component and application themes.
The design system defines CSS variables that can be used to achieve a consistent look and feel across the application.
The variables are documented in the Design System documentation:

- https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/typography[Typography]
- https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/color[Color]
- https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/size-space[Size and Space]
- https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/shape[Shape]
- https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/elevation[Elevation]
- https://vaadin.com/docs/latest/styling/lumo/lumo-style-properties/interaction[Interaction]

You can use the variables in place of hard-coded units using `var()`.

[source,css]
----
.card {
  border: 1px solid var(--lumo-contrast-30pct);
  border-radius: var(--lumo-border-radius-s);
  box-shadow: var(--lumo-box-shadow-s);
}
----

// end::content[]
