---
title: Date Time Picker
description: Date Time Picker is an input field for selecting a date and time.
---

= Date Time Picker

[source,tsx]
----
<DateTimePicker label="Meeting date and time" />
----

The date and time can be entered directly using the keyboard in the format of the current locale, or by selecting the date and time from the Date Time Picker's two overlays. The overlays open when their respective fields are clicked or any input is entered when the fields are focused.

// TODO: define {article} and fix relative link
:component-name: DateTimePicker
:text-field-features: true
include::../_shared.asciidoc[tag=field-features]


== Step

Date Time Picker's step parameter defines the time interval in seconds between the items displayed in the time picker overlay. It also specifies the amount by which the time increases or decreases using the up/down arrow keys when the overlays are disabled.

The default step is one hour (i.e., `3600` seconds). Unlike <<../number-field#,Number Field>>, Date Time Picker accepts values that don't align with the specified step.

[source,tsx]
----
<DateTimePicker
  label="Meeting date and time"
  step={60 * 30}
  value="2020-06-12T12:30"
/>
----

.Use Even Steps
[NOTE]
A step must divide an hour or day, evenly. For example, _"15 minutes"_ and _"30 minutes"_ are valid steps for an hour, and _"2 hours"_ is a valid step for a day, whereas _"42 minutes"_ isn't valid for either.

The displayed time format changes based on the step.

[source,tsx]
----
<DateTimePicker
  label="Message received"
  step={1}
  value="2020-06-12T15:45:08"
/>
----

:component-path: date-time-picker
include::{articles}/react/components/_vaadindocs.adoc[]
