---
title: Global Audience
order: 70
layout: page
---

= Global Audience
:experimental:

== Inclusiveness
Vaadin’s technical documentation is obviously aimed at an audience that has a certain level of technical awareness.
However, we must be careful not to make too many assumptions about an individual reader’s knowledge and skill set.

As we cannot know exactly what each reader’s level of knowledge is, we have to use our judgment about what we can reasonably expect them to know, and what we need to explain.

Nevertheless, we hope that our customers will find using our products to be an enjoyable and satisfying experience – perhaps even an educational one.
For this reason, if you have some doubt about whether to explain some aspect more fully, it is probably better to provide too much explanation than too little.
However, this will always remain a judgment call; we still want our users to be able to get the core information from our documentation acceptably quickly, without having to read through too much unnecessary text.

Since we are technical authors, it is possible that our level of knowledge is higher than that of the average reader – at least in the technical area that we are writing about.
We need to keep the target audience in mind at all times.
We do not want to exclude readers who may be at an earlier stage in their learning process.

We are writing for people of all kinds, so we should remember to use inclusive language.
We have no preconceptions about our audience’s race, gender, ability or any other aspect of their being.
Still, we need to remember to demonstrate this by not falling into the traps posed by some set expressions and language forms that come from an earlier age.

The English language has one common issue that can make things difficult in this connection.
English does not have a gender-neutral word to replace “he or she”, “him or her” or “his or her”.

The most obvious way to address this is simply to write “he or she” or “his or her” every time, as appropriate.
However, the problem with this is that it can quickly become awkward and repetitive.

The generally accepted workaround is to replace these phrases with “they”, “them” and “their”, respectively.
The resulting sentences may sound strange to a non-native author and, indeed, strictly speaking, they are often not grammatically correct. However, this is an example of what is sometimes referred to as “non-correct standard English”.
In other words, it is the way that native speakers speak and write, and it is considered to be acceptable usage.

For example, consider the following sentence:

If a user forgets his or her password, he or she should contact the support desk.

This is clearly awkward and repetitive. An acceptable, and less awkward alternative would be:

If a user forgets their password, they should contact the support desk.

In this particular case, you might also consider using the plural form to avoid the issue altogether:

Users who forget their password should contact the support desk.
