---
title: Overview
order: 1
layout: page
---

= Contributing to Vaadin Documentation

You can simply click the *Edit this article* link at the bottom of any page to start making a contribution through GitHub.
After editing, make a pull request.
You should pay note to <<editing-tools.adoc#github, the instructions>> and limitations regarding editing in GitHub.

.GitHub editor has limitations
[NOTE]
The preview in the GitHub editor has limitations.

If you make code contributions that change the behavior of Vaadin products, the new behavior always needs to be documented.
Documentation should be done along with any such feature additions or changes.
Hence, if you develop any features for the Vaadin products, you need to be familiar with the documentation tools and processes.

<<editing-tools.adoc#, Editing Tools>>::
  Gives instructions for editing and previewing documentation.
  The easiest way is to edit GitHub, but it has limitations.
  You can use any editor, but some support highlighting and previewing.
  You can also do preview with various external tools.

<<guidelines.adoc#, Content Guidelines>>::
 Gives tips regarding the basic structure and content of product or feature documentation.
 Describes various aspects which you could consider for the documentation.

<<formatting-organization#, Formatting with AsciiDoc>>::
  Vaadin documentation is currently written in the AsciiDoc format.
  We follow certain special conventions of using AsciiDoc.
  This document gives introduction to basic document structure and format.
  Emphasis should be done with special style names, and so forth.

<<style-guidelines.adoc#, "Style Guidelines">>::
  Gives style guidelines for formatting and the use of English language in various special cases.

<<process.adoc#, "Documentation Process">>::
 Explains how documentation should be done as part of the software development process.

== Contributing to Vaadin Products

Source code for Vaadin products is available from GitHub at http://github.com/vaadin[`github.com/vaadin`].
Its ticket system is the primary way to file bug reports and make feature requests.

== AsciiDoc Resources

* http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference]

* http://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writer's Guide]

* http://asciidoctor.org/docs/user-manual/[AsciiDoctor Manual]
