
== Before You Start

* Delete the `node_modules` folder and either lock file: `package-lock.json` (with npm) or `pnpm-lock.yaml` (with pnpm)

* Edit the `pom.xml` file and change the Vaadin version to the latest Vaadin 23 version available.

== Update to Java 11

- Java version requirement changes from Java 8 to Java 11
+
For Maven update the java.version
+
[source, xml]
----
<properties>
    <java.version>11</java.version>
</properties>
----
+
or compiler.source and compiler.target
+
[source, xml]
----
<properties>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
</properties>
----

- For Java 9+ `maven-failsafe-plugin` requires jaxb-impl to be added
+
The dependency can be added directly in the plugin definition as:
+
[source, xml]
----
<plugin>
    <artifactId>maven-failsafe-plugin</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>${jaxb.version}</version>
        </dependency>
    </dependencies>
</plugin>
----

== Update Spring Settings

=== Update Spring Version

Vaadin is compatible with Spring 5.3.0 or newer, and Spring Boot 2.4.0 or newer.
If your application uses an older version of Spring, update it to a compatible version:

[source,xml]
----
include::../../../../pom.xml[tag=spring-version, indent=0]
----

.Cyclic dependency in Bakery starter
[NOTE]
====
If your project is based on the link:https://vaadin.com/docs/v14/flow/starters/bakeryflow[V14 Bakery starter] and you encounter an error regarding cyclic dependencies after updating the Spring version, it could be due having an [annotationname]`@Autowired` field of type [classname]`PasswordEncoder` and a method that provides the bean for the same type in the [classname]`SecurityConfiguration` class.

Fix this by moving them to separate classes, or preferably, remove the field in favor of using <<{articles}/flow/integrations/spring/view-based-access-control#, Vaadin Spring Security helpers>>.
====

=== Update Spring Security

If your application uses Spring security, ensure that [filename]#offline-stub.html# and [filename]#sw-runtime-resources-precache.js# files are added to the list of static resources that are allowed to bypass Spring security.
This can be done by updating [methodname]`WebSecurityConfigurerAdapter.configure(WebSecurity web)` to look something as follows:

[source,java]
----
@Override
public void configure(WebSecurity web) {
    web.ignoring().antMatchers(
            ...

            "/offline-stub.html",
            "/sw-runtime-resources-precache.js",

            ...
    );
}
----

== Enable Server-Side Bootstrapping 

Vaadin 23 uses a client-side bootstrapping approach that is different from the server-side mode that is used in Vaadin 14.
This change requires some alteration to your Vaadin 14 codebase.
However, to quickly get your application up and running in Vaadin 23, you can enable the Vaadin 14 server-side bootstrapping using the `useDeprecatedV14Bootstrapping` flag. We describe later in this guide the code changes required to use the new bootstrapping mode.

To do that in a Spring project, you can add the following to [filename]#application.properties#.

.`application.properties`
[source]
----
vaadin.useDeprecatedV14Bootstrapping=true
----

Alternatively, if yours is a plain Java project, you can enable `useDeprecatedV14Bootstrapping` by adjusting the `vaadin-maven-plugin` configuration in [filename]#pom.xml# as follows:

.`pom.xml`
[source]
----
<plugin>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-maven-plugin</artifactId>
    <configuration>
        <useDeprecatedV14Bootstrapping>true</useDeprecatedV14Bootstrapping>
    </configuration>
</plugin>
----

To migrate the deprecated server-side bootstrapping to the modern client-side one, see the <<../final-steps/#bootstrapping-changes, required Bootstrapping Changes>> section.

== Replace API Usage

A set of API breaking changes and their replacements are listed below:

- `AbstractListDataView` now requires an extra constructor argument - a callback, which is invoked each time when the component's filter and/or sorting changes through the data view API.
- Property synchronization methods in `Element` are replaced with similar API in `DomListenerRegistration`: `getSynchronizedPropertyEvents`, `getSynchronizedProperties`, `removeSynchronizedPropertyEvent`, `removeSynchronizedProperty`, `addSynchronizedPropertyEvent`, `addSynchronizedProperty`,  `synchronizeProperty`.
- Methods `JsModule#loadMode()` and `Page#addJsModule(String, LoadMode)` for setting the load mode of JsModule are removed since it does not function with JavaScript modules.
- The construction methods `BeforeEvent(NavigationEvent, Class<?>)` and `BeforeEvent(Router, NavigationTrigger, Location, Class<?>, UI)` in `BeforeEvent` are replaced with `BeforeEvent(NavigationEvent, Class, List)` and `BeforeEvent(Router, NavigationTrigger, Location, Class, UI, List)`
-  Methods `getUrl()`, `getUrlBase()` and `getRoutes()` in `Router` are replaced with methods `getUrl()`, `getUrlBase()` and `getAvailableRoutes()` in `RouterConfiguration`. The `resolve()` method in `Router` is replaced with the `resolve()` method in `RouteUtil`. The `getRoutesByParent()` method in `Router` is removed and has no replacement.
- `ServletHelper` is replaced with `HandlerHelper`
- The `getBodyAttributes` method in `AbstractTheme`, `Lumo` and `Material` is replaced with `getHtmlAttributes`
- The `removeDataGenerator` method in `HasDataGenerators` and `CompositeDataGenerator` is removed in favor of using the registration returned from `addDataGenerator(DataGenerator)`
- The methods `preventsDefault` and `stopsPropagation` in `ShortcutRegistration` are replaced with `isBrowserDefaultAllowed ` and `isEventPropagationAllowed`
-  The `safeEscapeForHtml` method in `VaadinServlet` is removed in favor of using `org.jsoup.nodes.Entities#escape(String)`
- The static method `getInstance` in `ApplicationRouteRegistry` is removed in favor of the instance method.
- The [methodname]`enableInstallPrompt` parameter of the `@PWA` annotation has been removed without a replacement.
See this https://github.com/vaadin/flow/issues/8038[GitHub issue] for the motivation of this removal.
- The protected instance method `getApplicationUrl` from `VaadinServlet` is removed
-  https://github.com/vaadin/web-components/issues/3275[Removed support for using positive `tabindex` values] (for example, `setTabIndex(1)`) on all input field components. 
This will not cause errors but has no effect.
However, setting `tabindex` to `0` or `-1` is still supported.
It is recommended to ensure that input fields are in the correct order in the DOM, instead of overriding the tab order with `tabindex`.
- If necessary, add a `router-ignore` attribute to the anchor elements whose navigation should be bypassing Vaadin router.
This is needed, for example, if an anchor is used to log users out in Spring Security.
Without the `router-ignore` attribute, Vaadin router will intercept the navigation to `/logout`, preventing Spring Security from handling logout as intended.
To fix this, add the `router-ignore` attribute as in the following example:

[source, java]
----
Anchor logoutLink = new Anchor("/logout", "Logout from app");
logoutLink.getElement().setAttribute("router-ignore", true);
----

== Update Selenium Version


In the case your application is based on the `spring-boot-starter-parent` and you use Vaadin TestBench for
running integration tests, you need to update the `selenium.version` property in the `pom.xml` file to `4.X`.
This is to override the outdated Selenium version that gets inherited from the Spring Boot parent.

.`pom.xml`
[source,xml]
----
<properties>
    <!-- Overrides the old version specified by the Spring Boot parent -->
    <selenium.version>4.1.2</selenium.version>
</properties>
----
