---
title: Styling
page-title: How to style the Message Input component | Vaadin components
description: Styling API reference for the Message Input component.
meta-description: Style the Vaadin Message Input component to align with your application's design and enhance user experience.
order: 50
---
= Message Input Styling

include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-message-input`
Disabled:: `vaadin-message-input+++<wbr>+++**[disabled]**`

=== Field

Input field wrapper:: `vaadin-message-input+++<wbr>+++** > vaadin-text-area**`
Input field:: `vaadin-message-input+++<wbr>+++** > vaadin-text-area::part(input-field)**`
Hovered input field:: `vaadin-message-input+++<wbr>+++** > vaadin-text-area:hover**`
Focused input field:: `vaadin-message-input+++<wbr>+++** > vaadin-text-area[focused]**`
Non-empty input field:: `vaadin-message-input+++<wbr>+++** > vaadin-text-area[has-value]**`

=== Button

Send button:: `vaadin-message-input+++<wbr>+++** > vaadin-button**`
Send button text:: `vaadin-message-input+++<wbr>+++** > vaadin-button::part(label)**`
Hovered button:: `vaadin-message-input+++<wbr>+++** > vaadin-button:hover**`
Focused button:: `vaadin-message-input+++<wbr>+++** > vaadin-button[focused]**`
Button for non-empty field:: `vaadin-message-input+++<wbr>+++** > vaadin-text-area[has-value] ~ vaadin-button**`
