---
title: Styling
page-title: How to style the Message Input component | Vaadin components
description: Styling API reference for the Message Input component.
meta-description: Style the Vaadin Message Input component to align with your application's design and enhance user experience.
order: 50
---
= Message Input Styling

== Style Variants

Message Input supports the following style variants:

[cols="1,3,1"]
|===
| Variant | Description | Supported by

|`icon-button`
|Renders the send button with an icon only
|Aura

|===

include::../_styling-section-theming-props.adoc[tag=style-properties]

include::../_styling-section-theming-props.adoc[tag=input-fields]

include::../_styling-section-theming-props.adoc[tag=input-surface]

.Send Button Properties
[TIP]
The send button appearance can be adjusted using the <<{articles}/components/button/styling#style-properties,Button style properties>>.

include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-message-input`
Disabled:: `vaadin-message-input+++<wbr>+++**[disabled]**`

=== Field

Input field wrapper:: `vaadin-message-input+++<wbr>+++** > vaadin-text-area**`
Input field:: `vaadin-message-input+++<wbr>+++** > vaadin-text-area::part(input-field)**`
Hovered input field:: `vaadin-message-input+++<wbr>+++** > vaadin-text-area:hover**`
Focused input field:: `vaadin-message-input+++<wbr>+++** > vaadin-text-area[focused]**`
Non-empty input field:: `vaadin-message-input+++<wbr>+++** > vaadin-text-area[has-value]**`

=== Button

Send button:: `vaadin-message-input-button**`
Send button text:: `vaadin-message-input-button+++<wbr>+++**::part(label)**`
Hovered button:: `vaadin-message-input-button+++<wbr>+++**:hover**`
Focused button:: `vaadin-message-input-button+++<wbr>+++**[focused]**`
Button for non-empty field:: `**vaadin-text-area[has-value] ~ vaadin-message-input-button**`
