---
title: Getting Started
order: 2
layout: page
---

= Getting Started with Observability Kit

This documentation will go over the following topics:

- Setting up infrastructure for collecting and viewing observability data such as traces and metrics
- Downloading the Observability Kit Java agent, and configuring it to export data to the infrastructure
- Running a Vaadin application with the Java agent.

== Setup Infrastructure

For this tutorial, we are using Jaeger to process traces and Prometheus to process metrics.
These are both run locally and are suitable for development and testing.
For integration with other Vendors, see <<./integrations#,Integrations>>.

include::./integrations/jaeger-prometheus.asciidoc[tag=jaeger-setup]

include::./integrations/jaeger-prometheus.asciidoc[tag=prometheus-setup]

== Getting and Configuring the Agent

Observability Kit is packaged as a Java agent based on the OpenTelemetry agent.
For more information, see <<./advanced/observability-agent#,Observability Kit Agent>>.

Click on the following button to download the agent (jar file):

http://tools.vaadin.com/nexus/content/repositories/vaadin-prereleases/com/vaadin/observability/vaadin-opentelemetry-javaagent/[Download agent,role="button secondary water"]

Next, the agent needs to be configured to export traces to Jaeger, and metrics to Prometheus.
For this create an `agent.properties` file with the following contents:

include::./integrations/jaeger-prometheus.asciidoc[tag=agent-properties]

== Run the Application

Start your application using one of the methods provided below.
If you don't have an application to use, you can download an app from https://start.vaadin.com[Vaadin Start], and run a production build using `mvn package -Pproduction`. Then run the packaged Jar file from the `target` folder as described below.

include::./integrations/_run-app.asciidoc[]
