---
title: Getting Started
description: Step-by-step guide showing how to add Observability Kit to your application.
order: 10
---

= Getting Started with Observability Kit
:sectnums:

This guide covers the following topics:

- downloading Observability Kit, and configuring it to export data to the infrastructure;
- setting up infrastructure for collecting and viewing observability data, such as traces and metrics;
- running a Vaadin application with Observability Kit.

== Download and Configure Observability Kit

Observability Kit is packaged as a Java agent based on the OpenTelemetry standard.
For more information, see <<{articles}/tools/observability/reference#,Reference>>.

link:https://repo1.maven.org/maven2/com/vaadin/observability/vaadin-opentelemetry-javaagent/1.0.0/vaadin-opentelemetry-javaagent-1.0.0.jar[Download Observability Kit, role="button secondary water"]

Next, Observability Kit needs to be configured to export traces to Jaeger, and metrics to Prometheus.
For this, create an [filename]`agent.properties` file with the following contents:

include::./integrations/jaeger-prometheus.asciidoc[tag=agent-properties]

== Setup Infrastructure

Use Jaeger to process traces and Prometheus to process metrics.
They both run locally and are suitable for development and testing.
For integration with other vendors, see <<{articles}/tools/observability/integrations#,Integrations>>.

include::./integrations/jaeger-prometheus.asciidoc[tag=jaeger-setup]

include::./integrations/jaeger-prometheus.asciidoc[tag=prometheus-setup]

== Run the Application

If you don't have an application to use, you can download an application from https://start.vaadin.com[Vaadin Start], and create a production build with the following command:

```terminal
./mvnw package -Pproduction
```

Then run the packaged JAR file from the [filename]`target` folder:

include::./integrations/_run-app.asciidoc[]

include::./integrations/jaeger-prometheus.asciidoc[tag=view-traces-metrics]
