---
title: Getting Started
order: 2
layout: page
---

= Getting Started With Observability Kit

Getting started with the Observability Kit involves:

- Setting up infrastructure for collecting and viewing observability data such as traces and metrics
- Downloading the Observability Kit Java agent, and configuring it to export data to the infrastructure
- Running a Vaadin application with the Java agent.
Ideally you have your own application, otherwise we provide a demo app that can be used.

== Setup Infrastructure

For this tutorial, we are using Jaeger to process traces and Prometheus to process metrics.
These are both run locally and are suitable for development and testing.
For integration with other Vendors, see <<./integrations#,Integrations>>.

include::./integrations/jaeger-prometheus.asciidoc[tag=jaeger-setup]

include::./integrations/jaeger-prometheus.asciidoc[tag=prometheus-setup]

== Agent Setup

Observability Kit is packaged as a Java agent based on the OpenTelemetry agent.
For more information, see <<./advanced/observability-agent#,Observability Kit Agent>>.

Click on the following button to download the agent (jar file):

https://vaadin-opentelemetry-javaagent.jar[Download agent,role="button secondary water"]

Next, the agent needs to be configured to export traces to Jaeger, and metrics to Prometheus.
For this create an `agent.properties` file with the following contents:

include::./integrations/jaeger-prometheus.asciidoc[tag=agent-properties]

== Run the Application

Start your application using one of the methods provided below.
If you don't have an application to use, you can download a demo app here:

https://observability-demo.jar[Download demo,role="button secondary water"]

Then start it using the Jar file method.

include::./integrations/_run-app.asciidoc[]
