---
title: Browser Access
page-title: How to handle browser access in Vaadin applications
description: Accessing the browser page using the Page object.
meta-description: Learn how to manage and restrict browser access to secure your Vaadin applications effectively.
order: 200
---


= Accessing the Browser Page

Besides using the [classname]`Element` API to manipulate the DOM in the browser, you can also interact with the browser page by adding style sheets, executing JavaScript, and receiving browser resize events.

These features are available through the [classname]`Page` object.
You can access the page of the current request with [methodname]`UI.getCurrentOrThrow().getPage()`.


== Getting the Window Location URL

Use the [methodname]`Page.fetchCurrentURL()` method to fetch the current URL from the browser.

For example:

.Getting the browser URL
[source,java]
----
UI.getCurrentOrThrow().getPage().fetchCurrentURL(currentUrl -> {
    // This is your own method that you may do something with the url.
    // Note that this method runs asynchronously
    storeCurrentURL(currentUrl);
});
----

== Accessing Browser Information

During the initial HTTP request, Vaadin reads the user-agent information supplied by the browser and stores it in a [classname]`WebBrowser` instance, which is accessible from the current [classname]`VaadinSession`.

Use [methodname]`getUserAgent()` to get the raw user-agent string. For structured browser detection (e.g., browser name, version, or operating system), use a parsing library such as https://github.com/ua-parser/uap-java[ua-parser/uap-java].

[source,java]
----
WebBrowser browser = VaadinSession.getCurrent().getBrowser();
String userAgent = browser.getUserAgent();
// Use a parsing library for structured detection, for example:
// Parser parser = new Parser();
// Client client = parser.parse(userAgent);
// String browserName = client.userAgent.family; // "Chrome"
// String os = client.os.family; // "Windows"
----

[since:com.vaadin:vaadin@V25]
[NOTE]
The browser and OS detection methods in [classname]`WebBrowser` -- such as [methodname]`getBrowserApplication()`, [methodname]`isChrome()`, [methodname]`isWindows()`, and [methodname]`getBrowserMajorVersion()` -- are deprecated. Use [methodname]`getUserAgent()` with a parsing library instead.


== Getting the Extended Client-Side Details

Use [methodname]`retrieveExtendedClientDetails()` in the current [classname]`Page` object to retrieve extended client-side details.
The method accepts a callback that, when called after client response, gets an [classname]`ExtendedClientDetails` object with various client-side data.

For example, the following can be used to get the screen width:


.Getting the screen width
[source,java]
----
UI.getCurrentOrThrow().getPage().retrieveExtendedClientDetails(details -> {
    // This is your own method that you may do something with the screen width.
    // Note that this method runs asynchronously
    handleScreenWidth(details.getScreenWidth());
});
----

== Executing JavaScript in the Browser

You can use server-side Java to execute JavaScript snippets in the browser.
You can also pass parameters to the executed script as variables named `$0`, `$1`, and so on.
Vaadin automatically serializes and escapes the parameter values.

You can execute JavaScript in the browser and pass parameters as follows:

[source,java]
----
public static void logElementSize(String name,
        Element element) {
    Page page = UI.getCurrentOrThrow().getPage();

    page.executeJs(
            "console.log($0 + ' size:', "
            + "$1.offsetWidth, $1.offsetHeight)",
            name, element);
}
----

The supported parameter types are: `String`, `Boolean`, `Integer`, `Double`, `JsonValue`, and `Element`.

The script is executed after the DOM tree has been updated based on server-side changes.
The parameter value is `null` for a parameter of type [classname]`Element` that isn't attached after the update (according to the server-side component structure).

The script is executed asynchronously, so you can't directly pass values back to the server.
Instead, you can use the returned [classname]`PendingJavaScriptResult` instance to add a callback that's called when the result is available.

== Scrolling a Component into View

You can scroll any component into the visible area of the browser window using [methodname]`scrollIntoView()`. This calls the browser's native `scrollIntoView()` on the component's element.

.Scrolling a component into view
[source,java]
----
component.scrollIntoView();
----

Use [classname]`ScrollIntoViewOption` to control scrolling behavior and alignment:

.Smooth scrolling
[source,java]
----
component.scrollIntoView(ScrollIntoViewOption.Behavior.SMOOTH);
----

.Scrolling to align the component at the bottom of the viewport
[source,java]
----
component.scrollIntoView(ScrollIntoViewOption.Block.END);
----

Options can be combined. [classname]`Behavior` controls the scrolling animation, [classname]`Block` controls vertical alignment, and [classname]`Inline` controls horizontal alignment.

.Combining multiple options
[source,java]
----
component.scrollIntoView(
        ScrollIntoViewOption.Behavior.SMOOTH,
        ScrollIntoViewOption.Block.END,
        ScrollIntoViewOption.Inline.CENTER);
----

The available alignment values for both [classname]`Block` and [classname]`Inline` are `START`, `CENTER`, `END`, and `NEAREST`.


== Browser Window Resize Events

The [classname]`Page` class allows you to register a listener for events that affect the web page and the browser window in which the Vaadin UI lives.
The [classname]`Page` instance corresponding to a given [classname]`UI` is accessed by the [methodname]`getPage()` method of the [classname]`UI`.

You can get the browser window size by adding a resize listener, as follows:

[source,java]
----
Page page = UI.getCurrentOrThrow().getPage();
var listener = page.addBrowserWindowResizeListener(
        event -> Notification.show("Window width="
                + event.getWidth()
                + ", height=" + event.getHeight()));
----

[NOTE]
To avoid memory leaks when using [classname]`BrowserWindowResizeListener` you need to unregister it when you don't need to listen the events anymore. For example you can do this when component detaches.

[source,java]
----
@Override
protected void onDetach(DetachEvent detachEvent) {
    // Listener needs to be eventually removed to avoid resource leak
    listener.remove();
    super.onDetach(detachEvent);
}
----


[discussion-id]`0DF2CC14-4401-49E4-B97D-920CAFEAAF8D`
