---
title: Menu Registry
description: Collecting menu annotated routes for menu generation
order: 115
---

= Menu Registry
:toc:

To generate a custom menu there exists a [classname]`MenuRegistry` for collecting defined server and client routes.

Client routes are collected from the FileSystem routes definition and server routes are collected for routes annotated with [annotationname]`@Menu`.

The collected menu items are automatically filtered by access control from the [classname]`UI` ([classname]`NavigationAccessControl` and [classname]`ViewAccessChecker`).
If the application has login and route defines `Roles` the returned list is filtered to only available routes.

== Creating Routes Menu

For a Flow application any route annotated with [annotationname]`@Menu` is eligible for automatic collection.

To get the available menu routes call the static method `MenuRegistry.collectMenuItems()` which returns a [classname]`Map<String, AvailableViewInfo>`.
The key in the returned map is the route path that should be used for navigation.
This would make creating a simple menu using [classname]`Anchor` look like:

[source,java]
----
Map<String, AvailableViewInfo> menuItems = MenuRegistry.collectMenuItems();
menuItems.forEach((path, info) -> layout.add(new Anchor(path, info.menu().title())));
----

==== Only Server Routes For Hybrid Application

For a hybrid application where only server menu items are wanted there is the static method [methodname]`collectAndAddServerMenuItems` which takes in the [classname]`RouteConfiguration` to use and a [classname]`Map` to populate the routes into.

This could for example be called as follows:

[source,java]
----
Map<String, AvailableViewInfo> menuRoutes = new HashMap<>();
MenuRegistry.collectAndAddServerMenuItems(RouteConfiguration.forApplicationScope(), menuRoutes);
----

== Creating Client Routes Menu On The Server

For client routes the same static method `MenuRegistry.collectMenuItems()` can be used to get also server routes.

==== Only Client Routes For Hybrid Application

To only collect the client routes [classname]`MenuRegistry` has the method [methodname]`getClientRoutes(boolean filterClientViews, AbstractConfiguration configuration)`.
The `boolean filterClientViews` is used to define if not accessible client routes should be removed from the result.
The required configuration can be gotten from the [classname]`VaadinService` method [methodname]`getDeploymentConfiguration()`.

For a full list there exists also the shorthand method [methodname]`getClientRoutes()` in [classname]`FrontendUtils`.

For creating a client menu see <<../../hilla/guides/routing#creating-menu-from-routes,Creating Menu From Routes>>.

== Data Returned For Menu Items

The [classname]`AvailableViewInfo` for the route contains information on the route.
Using this data it is possible to automatically populate a menu.

The data contained is:

`title`::
The [annotationname]`@PageTitle` if defined else the class simple name.
For the client title is populated from the FS router data.

`rolesAllowed`::
Array of roles that are allowed for the item.

`loginRequired`::
If menu route requires a login to be viewed.

`route`::
Route for the view.
On the server this should match the array key, but for client routes this may be missing parent path parts if any.

`lazy`::
Not in use. Later marks the route as lazy loaded from a different bundle.

`register`::
If route should be automatically registered into a menu.

`menu`::
[classname]`MenuData` on the [annotationname]`@Menu`. See down for menu definitions.

`children`::
Hierarchy information on routes below the given view. For client routes only.

`routeParameters`::
Defines any route parameters and their [classname]`RouteParamType`


Data in [classname]`MenuData`

`title`::
Title set in the annotation or the same as [classname]`AvailableViewInfo.title`.

`order`::
Order number for the menu item if defined.

`exclude`::
If item should be excluded for the automatic menu.

`icon`::
Icon to use in the menu. Value can go inside a `<vaadin-icon>` element's `icon` attribute which accepts icon group and name like `vaadin:file`. Or it can go to a `<vaadin-icon>` element's `src` attribute which takes path to the icon. E.g. `line-awesome/svg/lock-open-solid.svg`.

[discussion-id]`647922A8-D542-4FA7-AAF6-44D40FC6A33B`
