---
title: Menu Configuration
description: Collecting menu annotated routes for menu generation.
order: 115
---


= Menu Configuration

To generate a custom menu there's the [classname]`MenuConfiguration` for collecting defined server and client routes. Client routes are collected from the FileSystem routes definition. Server routes are collected for routes annotated with [annotationname]`@Menu`.

The collected menu items are filtered by access control from the [classname]`UI` ([classname]`NavigationAccessControl` and [classname]`ViewAccessChecker`). If the application has login and route defined `Roles`, the returned list is filtered for only available routes.


== Creating Routes Menu

For a Flow application, any route annotated with [annotationname]`@Menu` is eligible for automatic collection.

To get the available menu routes, call the static method `MenuConfiguration.getMenuEntries()`. This returns a [classname]`List<MenuEntry>` sorted primarily by order, then by path alphabetically and locale-sensitively. It would make creating a simple menu using [classname]`Anchor` look like this:

[source,java]
----
List<MenuEntry> menuEntries = MenuConfiguration.getMenuEntries();
menuEntries.forEach(entry -> layout.add(new Anchor(entry.path(), entry.title())));
----

== Data Returned for Menu Entries

The [classname]`MenuEntry` for the route contains information on the route. Using this data, it's possible to populate a menu, automatically.

The data contained is as follows:

`path`::
Route path that should be used for navigation.

`title`::
Title set in the [annotationname]`@Menu` annotation or the [annotationname]`@PageTitle` if defined; else the class simple name. For the client, title is populated from the FS router data.

`order`::
Order number for the menu entry if defined.

`icon`::
Icon to use in the menu. The value can be entered inside a `<vaadin-icon>` element's `icon` attribute. This accepts icon group and a name like `vaadin:file`. Or the value can be given in `<vaadin-icon>` element's `src` attribute, which takes the path to the icon (e.g., `line-awesome/svg/lock-open-solid.svg`).

`menuClass`::
Source class of the [annotationname]`@Menu` annotation. Always null for client routes.

[discussion-id]`647922A8-D542-4FA7-AAF6-44D40FC6A33B`
