---
title: Custom Error Handling
order: 105
layout: page
---


= Custom Error Handling

You can customize the error views related to navigation between different routes as described in the <<{articles}/flow/routing/tutorial-routing-exception-handling#, Router Exception Handling>> section.

For other unhandled runtime exceptions, an `ErrorHandler` class can be used to gracefully let users know that something went wrong. In order to do so,
first create your custom `ErrorHandler` class, then use that class to override the default error handler via `VaadinSession.getCurrent().setErrorHandler(ErrorHandler)`.

For example, the following `CustomErrorHandler` class logs the error and displays a friendly notification to the user.

[source,java]
----
public class CustomErrorHandler implements ErrorHandler {

    private static final Logger logger = LoggerFactory.getLogger(CustomErrorHandler.class);

    @Override
    public void error(ErrorEvent errorEvent) {
        logger.error("Something wrong happened", errorEvent.getThrowable());
        if(UI.getCurrent() != null) {
            UI.getCurrent().access(() -> {
                Notification.show("An internal error has occurred." +
                        "Please contact support.");
            });
        }
    }
}
----

To the logic in this class to take effect, you can then assign it to the current user session using `VaadinSession.getCurrent().setErrorHandler(new CustomErrorHandler());`.


