---
title: Uploads
page-title: Uploading files from client to server
description: Using UploadHandler to receive an incoming data stream.
meta-description: Learn to receive content using UploadHandler API in Vaadin Flow.
order: 130
---

= Using UploadHandler to Receive an Incoming Data Stream

To receive an upload from the client, you need to register an [classname]`UploadHandler` that accepts a URL to handle receiving an upload stream.
The recommended way to upload files is to use the <<{articles}/components/upload/file-handling#,Upload component>>, where as this documentation shows use of more customized components.

To create an [classname]`UploadHandler`, you need implement the [methodname]`handleUploadRequest` to handle the upload or use one of the provided UploadHandlers.
The existing [classname]`UploadHandler` implementations are accessible through the static methods in [classname]`UploadHandler`, e.g. `UploadHandler.toTempFile(SerializableBiConsumer<UploadMetadata, File> successHandler)`

[NOTE]
When receiving a multipart upload the [methodname]`handleUploadRequest` will be called separately for each file in the upload.

Then the handler can be registered through the [classname]`Element` API after registering it to the [classname]`StreamResourceRegistration`.

[source,java]
----
List<File> outputFiles = new ArrayList<>(1);
UploadHandler uploadHandler = UploadHandler.toTempFile((uploadMetadata, file) -> outputFiles.add(file));

StreamRegistration streamRegistration = VaadinSession.getCurrent()
        .getResourceRegistry()
        .registerResource(uploadHandler, getElement());

getElement().setAttribute("target", streamRegistration.getResource());
----

The element can be a form on the client that sends file data using form submission:

[source,html]
----
<iframe name="dummyFrame" id="dummyFrame" display="none"/>
<form method="post" enctype="multipart/form-data" action="Element.getAttribute('target')" target="dummyFrame">
  <input type="file" name="file"/>
  <input type="submit"/>
</form>
----

The dummyFrame iframe is to keep the post from navigating to the action url on submit.
For multiple files add the attribute `multiple` to the file type input e.g. `<input type="file" name="file" multiple/>`.

Using the element API this could be done as:

[source,java]
----
InMemoryUploadHandler inMemoryUploadHandler = UploadHandler.inMemory(
    (uploadMetadata, bytes) -> {
        // handle Uploaded data here
    });
StreamRegistration streamRegistration = VaadinSession.getCurrent()
    .getResourceRegistry().registerResource(inMemoryUploadHandler);

// Generate dummy iframe for navigation on submit action
IFrame dummy = new IFrame();
dummy.setName("dummy");
dummy.setId("dummy");
dummy.getStyle().set("display", "none");

// Setup the form using the element api
Element formElement = new Element("form").setAttribute("method", "post")
    .setAttribute("enctype", "multipart/form-data")
    .setAttribute("action", streamRegistration.getResource())
    .setAttribute("target", "dummy");
Element files = new Element("input").setAttribute("type", "file")
    .setAttribute("name", "file");
Element submit = new Element("input").setAttribute("type", "submit");
formElement.appendChild(files).appendChild(submit);

add(dummy);
getElement().appendChild(formElement);
----

Another possibility is to do a `fetch` action from javascript to send the data to the server.
This could be done as:

[source,java]
----
Span container = new Span();
Input input = new Input();
input.setType("file");

NativeButton uploadButton = new NativeButton("Upload",
    (event) -> event.getSource().getElement().executeJs("""
        const file = $0.files[0];
        if (!file) {
          alert("No file selected");
          return;
        }
        const formData = new FormData();
        formData.append("file", file);
        fetch(this.getAttribute("endpoint"), {
          method: "POST",
          body: formData
        }).then(response => {
          if (response.ok) {
            alert("Upload successful");
          } else {
            alert("Upload failed");
          }
        });
        """, input.getElement()));

InMemoryUploadHandler inMemoryUploadHandler = UploadHandler.inMemory(
    (uploadMetadata, bytes) -> {
        // handle Uploaded data here
    });
StreamRegistration streamRegistration = VaadinSession.getCurrent().getResourceRegistry()
    .registerResource(inMemoryUploadHandler,uploadButton.getElement());
uploadButton.getElement()
    .setAttribute("endpoint", streamRegistration.getResource());

container.add(input, uploadButton);
----


[discussion-id]`4482D0BF-E742-4FEA-A888-854B758FE576`
