---
title: Navigate to a View
page-title: How to navigate to a view in a Vaadin application 
description: TODO Write a description
meta-description: TODO Write a meta-description
layout: tabbed-page
tab-title: Overview
order: 15
---


= Navigate to a View

You can navigate to a view either programmatically through an API, by clicking a link, or by changing the URL of the browser.

In a Vaadin application, navigation is handled by a router. The router takes care of rendering the correct view (i.e. the route target) and keeping the URL in sync. If the view accepts view parameters, the router also extracts them from the URL and passes them on to the view.

It is possible to plug your own code into the router. For example, you could redirect to another route on the fly, or prevent the user from navigating away from the current view. This is called _conditional routing_.

Flow and React views are handled by the same router. You can navigate to a Flow view from a React view, and vice versa. 

The following guides teach you how to navigate between views in Vaadin:

* <<flow#,Navigation in Flow>>
* <<react#,Navigation in React>>

// TODO Explain that navigation is a big topic and has been split up into multiple guides. Then add links to them here.

// TODO Write a deep-dive about routing
