---
title: Combo Box
layout: tabbed-page
tab-title: Usage
page-links:
  - https://github.com/vaadin/flow-components/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-combo-box-flow}[Flow {moduleMavenVersion:com.vaadin:vaadin-combo-box-flow}]
  - https://github.com/vaadin/web-components/releases/tag/v{moduleNpmVersion:vaadin-combo-box}[Web Component {moduleNpmVersion:vaadin-combo-box}]
---

= Combo Box

// tag::description[]
Combo Box is an input field that allows the user to choose a value from a set of options presented in a overlay list that can be filtered by typing into the field.
// end::description[]
It supports lazy loading and can be configured to accept custom typed values.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/combobox/combo-box-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/generated/com/vaadin/demo/domain/Country.ts[group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/combobox/ComboBoxBasic.java[render,tags=snippet,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Country.java[group=Java,tags=*,indent=0]
----
--

The overlay opens when the user clicks the field using a pointing device.
Using the Up/Down arrow keys or typing a character (found in at least one of the options) when the field is focused also opens the popup.

:component-name: Combo Box
:text-field-features: true
include::../_shared.asciidoc[tag=field-features]

== Custom Value Entry

Combo Box can be configured to allow entering custom values that are not included in the list of options.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/combobox/combo-box-custom-entry-1.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/combobox/ComboBoxCustomEntry1.java[render,tags=snippet,indent=0,group=Java]
----
--

Allowing custom entry is useful when you need to present the most common choices but still give users the freedom to enter their own options.

Custom values can also be stored and added to the list of options:

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/combobox/combo-box-custom-entry-2.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/combobox/ComboBoxCustomEntry2.java[render,tags=snippet,indent=0,group=Java]
----
--

== Custom Item Presentation

See <<../select#custom-item-presentation, Select, Custom Item Presentation.>>

Items can be customised to display more information than a single line of text.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/combobox/combo-box-presentation.ts[render,tag=combobox,indent=0,group=TypeScript]

...

include::{root}/frontend/demo/component/combobox/combo-box-presentation.ts[render,tag=renderer,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/generated/com/vaadin/demo/domain/Person.ts[group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/combobox/ComboBoxPresentation.java[render,tag=combobox,indent=0,group=Java]

...

include::{root}/src/main/java/com/vaadin/demo/component/combobox/ComboBoxPresentation.java[render,tag=renderer,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Person.java[group=Java,tags=*,indent=0]
----
--

Use a custom filter to allow the user to search by the rendered properties.
It is recommended to make filtering case insensitive.

== Auto Open

The overlay opens automatically when the field is focused using a pointer (mouse or touch), or when the user types in the field.
You can disable that to only open the overlay when the toggle button or Up/Down arrow keys are pressed.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/combobox/combo-box-auto-open.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/generated/com/vaadin/demo/domain/Country.ts[group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/combobox/ComboBoxAutoOpen.java[render,tags=snippet,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Country.java[group=Java,tags=*,indent=0]
----
--

== Popup Width

The width of the popup is, by default, the same width as the input field.
The popup width can be overridden to any fixed width in cases where the default width is too narrow.


[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/combobox/combo-box-popup-width.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,typescript]
----
include::{root}/frontend/generated/com/vaadin/demo/domain/Person.ts[group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/combobox/ComboBoxPopupWidth.java[render,tags=snippet,indent=0,group=Java]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/domain/Person.java[group=Java,tags=*,indent=0]
----
--

== Placeholder

Use the placeholder feature to provide an inline text prompt for the field. Do not create, or use, a separate item for this purpose.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/combobox/combo-box-placeholder.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/combobox/ComboBoxPlaceholder.java[render,tags=snippet,indent=0,group=Java]
----
--

== Custom Filtering

Combo Box's filtering, by default, is configured to only show items that contain the entered value:

[source,html, role=render-only]
----
include::{root}/frontend/demo/component/combobox/combo-box-filtering-1.ts[render,tags=snippet,indent=0]
----

Custom filtering is also possible.
For example, if we only want to show items that start with the user's input:

[.example]
--

[source,typescript]
----
include::{root}/frontend/demo/component/combobox/combo-box-filtering-2.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/combobox/ComboBoxFiltering2.java[render,tags=snippet,indent=0,group=Java]
----
--

== Usage as Autocomplete Field

As the user is typing, the Combo Box will filter out the options that don't match.
Once the correct value has been found, the user can use the Up/Down arrow keys to navigate the list and the Enter key to set the value, essentially using the Combo Box as an autocomplete field.

== Best Practices

Combo Box supports lazy loading for large datasets.
It reduces the initial load time, consumes less bandwidth and resources.

.Do not use as a menu
[NOTE]
Combo Box is an input field component, not a generic menu component.
Use the Menu Bar component to create overlays for actions.

== Related Components

[cols="1,2"]
|===
|Component |Usage recommendations

|<<../select#,Select>>
|Simpler overlay selection field without filtering, lazy loading or custom value entry.

|<<../radio-button#,Radio Button>>
|Better accessibility than Combo Box, as all options are visible without user interaction.

|<<../list-box#,List Box>>
|Scrollable inline list of options.
Supports single and multi-select.

|<<../menu-bar#,Menu Bar>>
|Overlay menus for items that trigger actions.
|===
