---
title: Card
page-title: Card component | Vaadin components
description: The Card component is a versatile container for grouping related content and actions, with several customization options for layout and appearance.
meta-description: The Card component is a versatile container for grouping related content and actions, with several customization options for layout and appearance.
version: since:com.vaadin:vaadin@V24.8
layout: tabbed-page
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/card}/elements/vaadin-card[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/card/Card.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/card}/packages/card[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-card-flow-parent[Java]'
---

= Card
:toclevels: 2

// tag::description[]
The Card component is a versatile container for grouping related content and actions, with several customization options for layout and appearance.
// end::description[]

[.example.render-only.embedded]
--
[source,html]
----
include::{root}/frontend/demo/component/card/card-features.ts[render,persistent]
----
--


== Key Features

- *Multiple slots*: Flexible content placement with distinct slots for media, title, subtitle, header, footer, and more.
- *Customizable appearance*: Extensive theming options for shadows, borders, and backgrounds.


== Slots

The Card component provides the following slots:


=== Content Slot

Place any content here, and as many elements as needed.

[.example.centered.show-code]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/card/card-content.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/card/CardContent.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/card/react/card-content.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Media

Place for an image, video, or an icon. Can also be used for other content, but it's intended for illustration purposes. Displays before all other content in the card.

Use the <<styling#stretch-media, `stretch-media`>> and <<styling#cover-media, `cover-media`>> style variants to control how media content is sized.

[.example.show-code]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/card/card-media.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/card/CardMedia.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/card/react/card-media.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Title

Textual content with predefined styling. Only one element can be placed in this slot.

[.example.centered.show-code]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/card/card-title.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/card/CardTitle.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/card/react/card-title.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Subtitle

Textual content with predefined styling, presented below the title element. Only one element can be placed in this slot. Should be used together with the title slot.

[.example.centered.show-code]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/card/card-subtitle.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/card/CardSubtitle.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/card/react/card-subtitle.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Header

Generic slot for any header content. This slot does not add styles for the content and overrides the title and subtitle slots. Only one element can be placed in this slot. Useful, for example, if you want complete control of the heading text styling or layout.

[.example.centered.show-code]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/card/card-header.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/card/CardHeader.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/card/react/card-header.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

You should add the title before the subtitle in the DOM order to make it the first announced element for screen reader users. You can use flexbox and the `order` CSS property to visually place the subtitle before the title without affecting the DOM order.

=== Header Prefix

Any content before the title, subtitle, or header content. Only one element can be placed in this slot.

[.example.centered.show-code]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/card/card-header-prefix.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/card/CardHeaderPrefix.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/card/react/card-header-prefix.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Header Suffix

Any content after the title, subtitle, or header content. Only one element can be placed in this slot.

[.example.centered.show-code]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/card/card-header-suffix.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/card/CardHeaderSuffix.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/card/react/card-header-suffix.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Footer

Can contain any content. Typically used for actions, badges, or supplementary content. The footer stays anchored to the bottom of the card if the card grows taller than the content in it.

[.example.centered.show-code]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/card/card-footer.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/card/CardFooter.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/card/react/card-footer.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--



== Accessibility

The Card component has a default ARIA `role="region"`.

When the card's title is set through the string API

* It is rendered with `role="heading"`;
* Its heading level is set to 2 (corresponding to an `<h2>` element);
* The heading is associated with the Card root element using `aria-labelledby`.

The Card's `role` and the heading level of the title can be customized:

[.example]
--
.Flow
[source,java]
----
card.setAriaRole("listitem");
card.setTitleHeadingLevel(3);
----

.React
[source,tsx]
----
<Card role="listitem" titleHeadingLevel={3}>
----

.Lit
[source,html]
----
<vaadin-card role="listitem" title-heading-level="3">
----
--


++++
<style>
.example.centered .render > * {
  max-width: fit-content;
  margin: auto;
}

.example.bg-contrast {
  --docs-example-render-background-color: transparent;
}
</style>
++++
