---
title: Overview
order: 1
---

= Integrating Vaadin

You can integrate Vaadin with many Java and other technologies.

Some of the most common ones are as follows:

<<spring/overview#, Using Vaadin with Spring>>::
Vaadin is well suited for using it with the Spring Framework.
Spring is part of the recommended toolchain, and in fact Vaadin applications are by default Spring Boot applications.

<<cdi/overview#, Using Vaadin with CDI>>::
CDI or Contexts and Dependency Injection is a framework for injecting dependency objects in different contexts.
It is part of the Java EE platform, but similar in purpose to autowiring in Spring.

<<embedding/overview#, Embedding Applications>>::
In addition to running Vaadin a application in a web page, you can embed it in a web page, which could be part of some other application.

<<osgi/basic#, OSGi>>::
OSGi is an open source specification that describes a modular system and a dynamic service platform for Java.
Application and component bundles can be remotely installed, started, stopped, updated, and uninstalled without requiring a reboot.

<<osgi/karaf#, Karaf>>::
Apache Karaf is based on OSGi and provides a lightweight container onto which various components and applications can be deployed.
It provides some enterprise-ready features like shell console, remote access, hot deployment, and dynamic configuration.
