---
title: Quarkus
order: 250
layout: page
---

[[quarkus.basic]]
= Using Quarkus With Vaadin

Quarkus is an open source, Kubernetes-native Java framework made for Java virtual machines and native compilation.
It optimizes Java specifically for containers, enabling it to become an effective platform for serverless, cloud, and Kubernetes environments.
See https://quarkus.io/[+quarkus.io+] for more information about Quarkus.

To be able to run Quarkus, you need to add the `vaadin-quarkus` and `vaadin-jandex` dependencies in the project, as well as configure the `quarkus-maven-plugin`.
Then, you can start the application with the `quarkus:dev` goal provided by the plugin.

You can use the https://github.com/vaadin/base-starter-flow-quarkus/[Quarkus base starter] project as a starting point for your own application.
There is also the https://github.com/vaadin/base-starter-flow-quarkus/tree/gradle[base starter for Gradle].

== Vaadin CDI Features

Quarkus’ dependency injection solution is based on CDI, so it is possible to use all CDI features.

See the documentation for Vaadin CDI features:

* <<cdi/contexts#, Vaadin CDI Scopes>> 
* <<cdi/events#, Observable Vaadin Events>> 
* <<cdi/service-beans#, Vaadin Service Interfaces as CDI Beans>>
* <<cdi/instantiated-beans#, Using CDI Beans>>


[[quarkus.vaadin.addons]]
== Vaadin Add-Ons in Quarkus Applications

Any Vaadin add-on used in a Quarkus application should contain a Jandex index.
You can generate it using the `jandex-maven-plugin`.
See https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index[How to Generate a Jandex Index].

If you cannot modify the dependency, you can still get Quarkus to index it by adding `quarkus.index-dependency` entries to your [filename]#application.properties#:

.[filename]#application.properties#
[source, properties]
----
quarkus.index-dependency.<name>.group-id=
quarkus.index-dependency.<name>.artifact-id=
quarkus.index-dependency.<name>.classifier=(this one is optional)
----

[[quarkus.vaadin.limitations]]
== Limitations

WebSockets Push does not currently work in the Vaadin extension for Quarkus.
As a consequence, Live Reload functionality is not available.