---
title: Getting Started
description: Step-by-step guide showing how to use SSO Kit in your application.
order: 10
---

= Getting Started with SSO Kit
:sectnums:

SSO Kit builds upon https://spring.io/projects/spring-security[Spring Security], and it comes with a starter module that takes care of configuring the security settings you need to authenticate against your identity provider.

== Add the SSO Kit Dependency

To get started you first need to add SSO Kit as a dependency to your application, for example to your Maven project:

.pom.xml
[source,xml]
----
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>sso-kit-starter</artifactId>
</dependency>
----

Then, you need to set some configuration properties to connect SSO Kit to your OpenID Connect provider.
These properties can be added to your [filename]`application.properties` file where you define the provider URL and the client registration details, such as credentials and scope.

Provider definition is configured within the `spring.security.oauth2.provider` namespace where you define a key to identify your provider (for example `keycloak`).
Then you can use the same key to register the client for that provider within the `spring.security.oauth2.registration` namespace, where you specify client credentials and the requested scope.
The scope is a list of keywords to request the provider for a specific set of information, such as user `profile`, `email` or `roles`.
This is an example of the properties to set to enable a Keycloak instance to perform authentication:

[.example]
--
.application.properties
[source,properties]
----
spring.security.oauth2.client.provider.keycloak.issuer-uri=https://my-keycloak.io/realms/my-realm
spring.security.oauth2.client.registration.keycloak.client-id= my-client
spring.security.oauth2.client.registration.keycloak.client-secret=very-secret-value
spring.security.oauth2.client.registration.keycloak.scope=profile,openid,email,roles
----
.application.yaml
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://my-keycloak.io/realms/my-realm
        registration:
          keycloak:
            client-id: my-client
            client-secret: very-secret-value
            scope:
            - profile
            - openid
            - email
            - roles
----
--

Once you have at least one client configured, you're ready to secure your views.

== Securing Views

The default configuration redirects to the provider's login page requests to any view.
You can set which views require authentication annotating them as described in <<{articles}/security/enabling-security#annotating-the-view-classes, Securing Spring Boot Applications: Annotating the View Classes>>.
For example:

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/sso/ProfileView.java[render,tags=full-class;!class-content,indent=0,group=Java]
----

== Single Sign-On

SSO Kit provides the [classname]`SingleSignOnConfiguration` auto-configuration class to setup Vaadin and Spring to allow single sign-on against external identity providers.

.Customized security configuration
[NOTE]
If you need a customized security configuration, you can disable this auto-configuration class by setting the `vaadin.sso.auto-configure` property to `false` and define your own configuration class.

This configuration enables login for the identity providers defined in the application configuration.
It instructs the application to accept requests for the login route, which can be configured setting the `vaadin.sso.login-route` property, which defaults to `/login`.
If there is no view defined for this route, Spring auto-generates a page with links to each of the configured providers login forms.
If you want to automatically redirect the users to the provider login form, you can set this property to `/oauth2/authorization/{provider-key}` where `{provider-key}` is the key used to configure the provider in `application.properties` file.

[.example]
--
.application.properties
[source,properties]
----
vaadin.sso.login-route=/oauth2/authorization/keycloak
----
.application.yaml
[source,yaml]
----
vaadin:
  sso:
    login-route: /oauth2/authorization/keycloak
----
--

.Custom Login Page
[TIP]
Some providers support custom theme for their login pages, find out more in <<theming#, Theming>>.

== Authentication Context

Upon successful authentication the provider redirects the user back to the protected view.
To access the authenticated user's information (such as name, email and roles), SSO Kit provides the [classname]`AuthenticationContext` bean that can be used as a view constructor argument.
Then you can get the authenticated user with the [methodname]`getAuthenticatedUser()`, which returns a [classname]`Optional` object containing the user instance if the session has an authenticated user or empty otherwise.

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/sso/ProfileView.java[render,tags=profile-view;authenticated-user;!logout,indent=0,group=Java]
----

By default, the user object returned by [methodname]`getAuthenticatedUser()` is an instance of [classname]`OidcUser`.
If your application defines a custom user service to provide a specialized implementation of `OidcUser`, you can use the [methodname]`getAuthenticatedUser(Class<U> userType)`, where `userType` is your own type that implements `OidcUser`.

== Single Sign-Off

SSO Kit provides two methods for logging out the user, defined by the OpenID Connect specification:

- https://openid.net/specs/openid-connect-rpinitiated-1_0.html:[RP-Initiated Logout]
- https://openid.net/specs/openid-connect-backchannel-1_0.html:[Back-Channel Logout]

=== RP-Initiated Logout

RP-Initiated Logout (RP stands for Relaying Party, the application) enables the user to logout from the application itself, taking care of terminating also the connected provider session.
The [classname]`AuthenticationContext` bean provides the [methodname]`logout()` method to initiate the logout process programmatically, for example inside a button click-listener:

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/sso/ProfileView.java[render,tags=full-class;!authenticated-user,indent=0,group=Java]
----

After a successful logout the user is redirected to the configured logout redirect route, that can set with the `vaadin.sso.logout-redirect-route` property:

[.example]
--
.application.properties
[source,properties]
----
vaadin.sso.logout-redirect-route=/logout-successful
----
.application.yaml
[source,yaml]
----
vaadin:
  sso:
    logout-redirect-route: /logout-successful
----
--

The default value of this property is the application root.

=== Back-Channel Logout

Back-Channel Logout is a feature that enables the provider to close user sessions from outside the application, for example from the provider's user dashboard or from another application.
To enable the feature, you need to set the `vaadin.sso.back-channel` property to `true`:

[.example]
--
.application.properties
[source,properties]
----
vaadin.sso.back-channel-logout=true
----
.application.yaml
[source,yaml]
----
vaadin:
  sso:
    back-channel-logout: true
----
--

Then, the client should be configured on the provider's dashboard to send logout requests to a specific application URL: `/logout/back-channel/{registration-key}` where `{registration-key}` is the provider key.
