---
title: SSO Kit (deprecated)
page-title: How to configure single sign-on (SSO) in Vaadin
description: Integrate Vaadin applications with third-party identity providers, and allow your users to benefit from single sign-on capabilities. Deprecated, and won't be available in Vaadin 26.
meta-description: SSO Kit integrates Vaadin applications with third-party identity providers for single sign-on. It's deprecated and won't be available in Vaadin 26.
section-nav: commercial
order: 90
banner: SSO Kit is deprecated and won't be available in Vaadin 26. See link:./sso/migrating-to-spring-security[Migrating to Spring Security].
banner-id: sso-kit-deprecated
banner-style: caution
---


= [deprecated:com.vaadin:vaadin@V25.3]#SSO Kit#

:commercial-feature: SSO Kit
:kit-start-trial: true
include::{articles}/_commercial-banner.adoc[opts=optional]

// tag::deprecation-notice[]
ifdef::admonition[]
[WARNING]
====
endif::admonition[]
SSO Kit is deprecated and won't be available in Vaadin 26.

A replacement is already in place: all of the kit's major features are now available directly in Spring Security and in Vaadin's Spring Security integration. See <<{articles}/tools/sso/migrating-to-spring-security#,Migrating from SSO Kit to Spring Security>> for how to move an existing application, and which features you have to build yourself.
ifdef::admonition[]
====
endif::admonition[]
// end::deprecation-notice[]

SSO Kit provides all of the configuration needed to add single sign-on capabilities to your Vaadin applications, based on https://openid.net/connect/[OpenID Connect]. However, it depends on Spring Boot and Spring Security.

The following identity providers are supported:

- https://www.okta.com/[Okta]
- https://www.keycloak.org/[Keycloak]
- https://azure.microsoft.com/en-us/products/active-directory/[Azure Active Directory (Microsoft Entra ID)]

SSO Kit needs at least one OpenID Connect client configured on an instance of these providers.

== Topics

section_outline::[]
