---
title: Presence Manager
order: 1
layout: page
---

[[ce.presence-manager]]
= Manage User Presence

Collaboration Engine includes a manager to set the user presence in a topic, keep track of the users who are currently present, and react to changes in the presence.
It provides a simple and flexible way to manage topic data related to user presence and makes it easy to create custom components with collaborative features.

The following example has a custom component that shows the list of active users in a topic using the presence manager:

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/ce/PresenceManagerExample.java[tags=snippet,indent=0]
----

<1> Creating a [classname]#PresenceManager# takes:
* a component to bind the  manager connection context to the UI,
* an instance of [classname]#UserInfo# that represents the current local user, and
* the ID of the topic to connect to.

<2> The [methodname]#markAsPresent()# method is used to configure the manager to mark the local user as present in the topic as soon as a connection is established.

<3> The [methodname]#setNewUserHandler# method sets a callback to handle a new user joining the topic.
It gets the [classname]#UserInfo# for the new user as the parameter.

<4> The callback returns another callback, a registration, that is called to remove the same user when the user leaves the topic.
