---
title: Start a Project
tab-title: Project Starters
layout: tabbed-page
order: 20
---

= Start a Project
:wizard-name: Start Vaadin
:toclevels: 2

[.cards.quiet.large.hide-title]
== Starters

[.breakout]
--
The recommended way to start a new Vaadin project is to use *{wizard-name}*.
It allows you to configure and download a customized starting point for your application.

Choose whether to build your application using <<{articles}/flow/overview#,Flow>> or <<{articles}/fusion/overview#,Fusion>>.

.You can change your mind later
[NOTE]
Don't worry about making "a wrong choice".
You can switch between Flow and Fusion in a project later if you want to.

--

[.card.large]
=== Start With Flow
image::../../_images/flow.svg[opts=inline, role=icon]
Build your application entirely using Java.

https://start.vaadin.com?preset=latest[Open {wizard-name}, role="button"]

[.card.large]
=== Start With Fusion
image::../../_images/fusion.svg[opts=inline, role=icon]
Build your backend services using Java and UIs using TypeScript and HTML.

https://start.vaadin.com?preset=fusion[Open {wizard-name}, role="button"]

[.breakout]
=== Non-Spring Boot Starters
The applications created using {wizard-name} are based on Spring Boot.
Starters for other stacks like JavaEE or plain servlet are available in GitHub.

https://github.com/vaadin?q=starter&type=source&language=[Browse starter projects on GitHub]


== Next Steps

Once you have downloaded a starter project and have it extracted in a local folder, you can import it to your favorite IDE (integrated development environment) and start developing it further.

=== Import to IDE

// TODO link to Using an IDE section under Flow and Fusion

Recommenced IDEs for Flow:

- IntelliJ IDEA
- Eclipse
- NetBeans

Recommended for Fusion:

- Visual Studio Code

=== Run the Application

You can also run the application locally from the terminal and view it in your browser.
Open a terminal in the folder, and run the following:

----
mvn
----

include::../_terminal.asciidoc[]

Then you can open `\http://localhost:8080` in your browser.
