---
title: Best Practices
order: 40
layout: page
---

= Security Best Practices

// tag::authentication-authorization[]
== Authentication and Authorization

Vaadin lets you choose which authentication and authorization framework you want to use, instead of bundling any specific one.
Vaadin is fully compatible with the most used security solutions in the Java ecosystem, including but not limited to Spring Security, JAAS and Apache Shiro.
The Vaadin-Spring addon has helpers for developers to integrate into the security mechanisms of those respective frameworks.

Since Vaadin is a server-side framework, credential processing always happens on the server, away from any possible attack surface.
Credentials are never transmitted to the client unless explicitly done so by the developer.

Generally, it is recommended that the developer double-checks user identity and access rights for each call from the client.
This can be automated with, for example, Spring Security and view-based authentication using roles.
What typically can't be automated by these frameworks is data-based access rights, such as limiting access to specific entities.

As an example, if the server receives an ID of a User object to be displayed in, for example, a URL request parameter (`{yourapp.com}/users/4/edit`), then the ID in question can be freely changed by an attacker.
The application needs to be aware of this and check if the currently logged in user has access rights to this entity.
This is something that is common for all UI frameworks, and not specific to Vaadin.

// end::authentication-authorization[]
// tag::spring-security-integration-ref[]
Examples for integrating Spring Security can be found in
// end::spring-security-integration-ref[]
https://vaadin.com/tutorials/securing-your-app-with-spring-security[Securing your app with Spring Security].

== Application State

The server is always aware of your application state. Compared to client side applications, this means that the server is aware of what is currently visible on the end-user's screen. Hence Vaadin denies actions to components that are not currently visible on the screen, or components that have been disabled on the server.

For instance, if the developer sets a component to be disabled, this effect is set both on the server and the client. On the client, an attacker can circumvent this (attackers have full control over anything in the browser), but the server will block any attempt to interact with the component and a warning is printed to the server logs.

[source,java]
----
Button button = new Button("Click me for effect!");
button.setEnabled(false);
button.addClickListener(e -> {
    // If the Button is disabled, this listener will not run,
    // even if an attacker enables the button client side.
});
----
// tag::data-validation[]
== Data Validation

In a Vaadin application, the data binding API supports data validation on the server, which cannot be by-passed with client-side attacks. 
Vaadin components do support client-side validation to increase the responsiveness of the application, but the developer should be aware that these should be used purely for convenience, since they are easily circumvented in the browser.

As with other web applications, all data coming from the client should always be validated once it reaches the server. 
It is not safe to rely on only client-side validation. 
Vaadin provides a set of pre-created server side validators for this purpose. 
In addition, the developer is free to use any Java API for validating the data, including connecting to external services. 
Vaadin also has a built-in integration with Java's Bean Validation (JSR 303) standard.

Data coming from a data store (such as a database) and inserted as HTML into DOM elements (for example, setting innerHTML for elements or using HTML mode in component captions) should also be escaped. 
Please see the chapter for XSS for more information.

// end::data-validation[]
== Web Services

No public Web Services are necessary in Vaadin applications. 
All communication in Vaadin goes through a single HTTP request handler used for RPC requests using the standard Servlet Java API. 
With Vaadin, you never open up your business logic as web services and thus there are less attack entry points to your Vaadin application.

// tag::ssl-https[]
== SSL and HTTPS

Vaadin always recommend developers to set up secure server endpoints and run all communication exclusively under HTTPS. 
Vaadin works out-of-the-box with HTTPS, and there is nothing for the developer to configure in your application code. 
Please refer to the documentation of your servlet container for details on how to set up HTTPS on your server.
// end::ssl-https[]
