---
tab-title: Usage
layout: tabbed-page
title: Text Field
description: Text Field allows users to enter text.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/text-field}/#/elements/vaadin-text-field[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/textfield/TextField.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/text-field}/packages/text-field[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-text-field-flow-parent[Java]'
---
:tag-name: vaadin-text-field


= Text Field

// tag::description[]
Text Field allows users to enter text.
// end::description[]
Prefix and suffix components, such as icons, are also supported.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/textfield/text-field-basic.ts[tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/textfield/TextFieldBasic.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/textfield/react/text-field-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


// Basic Features

include::{articles}/components/_input-field-common-features.adoc[tags=basic-intro;label;helper;placeholder;tooltip;clear-button;prefix-and-suffix;aria-labels]

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/textfield/text-field-basic-features.ts[tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/textfield/TextFieldBasicFeatures.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/textfield/react/text-field-basic-features.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


// Constraints

include::{articles}/components/_input-field-common-features.adoc[tags=constraints-intro;required;pattern;min-and-max-length;allowed-chars]

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/textfield/text-field-constraints.ts[tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/textfield/TextFieldConstraints.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/textfield/react/text-field-constraints.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


// Readonly and disabled

include::{articles}/components/_input-field-common-features.adoc[tag=readonly-and-disabled]

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/textfield/text-field-readonly-and-disabled.ts[tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/textfield/TextFieldReadonlyAndDisabled.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/textfield/react/text-field-readonly-and-disabled.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


// Style Variants

include::{articles}/components/_input-field-common-features.adoc[tags=styles-intro;text-alignment;small-variant;helper-above-field;borders]

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/textfield/text-field-styles.ts[tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/textfield/TextFieldStyles.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/textfield/react/text-field-styles.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--



== Autoselect

When a field is set to `autoselect`, its content is selected when the field is focused. Use `autoselect` when the user might to want to replace the entire value rather than adjust it.

[options="header"]
|===
|Autoselect |Focused with |Result
|`ON`|Pointing device or keyboard navigation.|Content selected.
|`OFF`|Pointing device.|Cursor placed where clicked.
|`OFF`|Keyboard navigation +
kbd:[Tab]|Cursor at the end of the input value.
|`OFF`|Keyboard navigation +
kbd:[Shift+Tab]|Contents selectedfootnote:[Consequent keyboard navigation results in the contents being selected until the selection is changed, by either arrow navigation or mouse click.]
|===



== Related Components

A variety of components are available for different types of input:

[cols="1,2"]
|===
|Component |Usage Recommendation

|<<../text-area#,Text Area>>
|Free-form multi-line text input, for text longer than can typically fit on a single line.

|<<../email-field#,Email Field>>
|For email addresses.

|<<../number-field#,Number Field>>
|Allows only numeric input.

|<<../text-field#,Password Field>>
|For securely entering passwords.

|<<../combo-box#,Combo Box>>
|For selecting from a predefined set of options. Allows filtering and entering custom values.

|<<../date-picker#,Date Picker>>
|Input field for entering or selecting a specific date.

|<<../time-picker#,Time Picker>>
|Input field for entering or selecting a specific time.
|===


[discussion-id]`E6D6D93F-BDB7-425A-AE47-343981004746`

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++
