---
title: Automatic Restart with Jetty Maven Plugin
order: 5
layout: page
---

= Automatic Restart with Jetty Maven Plugin

The https://www.eclipse.org/jetty/documentation/jetty-9/index.html#jetty-maven-plugin[Jetty Maven plugin] with the `scanIntervalSeconds` configuration set to a positive value performs complete application restart when the given number of seconds have elapsed since the last Java change.
For instance:

[source,xml]
----
<plugins>
    <plugin>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-maven-plugin</artifactId>
        <version>9.4.27.v20200227</version>
        <configuration>
            <scanIntervalSeconds>2</scanIntervalSeconds>
        </configuration>
    </plugin>

    <!-- more plugins -->
</plugins>
----

[NOTE]
We recommend using Jetty Maven Plugin `9.4.27.v20200227` or higher.
There is a known issue in the previous versions that causes `RouteNotFoundException` when trying to reload Java changes automatically.

Since the plugin performs a full server restart, all Java changes are picked up.
This includes modifications to server startup listeners as well as changes to code that connects frontend and backend components, such as adding a new `LitTemplate` class, or adding a new CSS import and using it in Java via `@CssImport` annotation.

However, the session is not preserved during the restart.
