---
title: Tools
order: 600
layout: index
---

= Tools

Speed up development with official Vaadin tools.

[.cards.large.quiet.hide-title]
== Developer Tools

[.card]
=== Collaboration Engine
image::{articles}/_images/ce.svg[opts=inline, role=icon]
The simplest way to build real-time collaboration into web apps.
<<{articles}/tools/ce#,See Collaboration Engine>>

[.card]
=== Designer
image::{articles}/_images/designer.svg[opts=inline, role=icon]
Create UIs visually by dragging and dropping components on a canvas.
<<{articles}/tools/designer#,See Designer>>

[.card]
=== Multiplatform Runtime
image::{articles}/_images/flow.svg[opts=inline, role=icon]
Run applications and components written with Vaadin 7/8 inside a Vaadin 10+ Flow application.
<<{articles}/tools/mpr#,See Multiplatform Runtime>>

[.card]
=== Design System Publisher
image::{articles}/_images/dsp.svg[opts=inline, role=icon]
Create a documentation website for your own Vaadin-based design system.
<<{articles}/tools/dspublisher#,See Design System Publisher>>

[.card]
=== Observability Kit
image::{articles}/_images/observability-kit.svg[opts=inline, role=icon]
Get insight into Flow applications at runtime and in production by monitoring application health, detecting unhandled errors and performance issues, and observing user behavior.
<<{articles}/tools/observability#,See Observability Kit>>
