---
title: Tools
page-title: Vaadin tools overview | Optimize your development workflow
description: Speed up development with official Vaadin tools.
meta-description: Explore Vaadin tools designed to enhance application development, styling, and deployment.
order: 60
layout: index
section-nav: flat
---

= Tools

// tag::all-tools[]
:tools-path-prefix: {articles}/tools/
:tools-icon-path-prefix: {root}/articles/flow/

[.cards.large.quiet.hide-title]
== Development Tools

[.card.large.commercial]
=== Copilot [badge-hilla]#Hilla#

Edit your application directly in the browser yourself or ask the AI copilot to do it for you, and see the changes applied right there in the browser.

[.sr-only]
<<{tools-path-prefix}copilot#,See Copilot>>


[.card.large]
=== Start

Kickstart your Vaadin project with ready-made view templates and get the project up and running without manual configuration.

[.sr-only]
<<{tools-path-prefix}start#,See Start>>



[.cards.large.quiet]
== Acceleration Kits

[.card.commercial]
=== AppSec Kit

Identify and manage security vulnerabilities in third-party dependencies.

[.sr-only]
<<{tools-path-prefix}appsec#,See AppSec Kit>>


[.card.commercial]
=== Azure Cloud Kit

image::{tools-icon-path-prefix}_images/cloud-upload-alt-solid.svg[opts=inline, role=icon,32,32]

Create scalable, highly-available, easily upgradable Vaadin applications, and deploy them to Azure Cloud.

[.sr-only]
<<{tools-path-prefix}azure-cloud#,Azure Cloud Kit Overview>>


[.card]
=== Collaboration Kit [badge-flow]#Flow#

image::{tools-icon-path-prefix}_images/users-solid.svg[opts=inline, role=icon,32,32]

The simplest way to build real-time collaboration into web applications.

[.sr-only]
<<{tools-path-prefix}collaboration#,See Collaboration Kit>>


[.card.commercial]
=== Kubernetes Kit

image::{tools-icon-path-prefix}_images/cloud-solid.svg[opts=inline, role=icon,32,32]

Deploy your Vaadin application to Kubernetes, enabling scalability, high availability, and rolling updates.

[.sr-only]
<<{tools-path-prefix}kubernetes#,See Kubernetes Kit>>


[.card.commercial]
=== Observability Kit

image::{tools-icon-path-prefix}_images/eye.svg[opts=inline, role=icon,32,32]

Get insights into Flow applications at runtime and in production by monitoring application health, detecting unhandled errors and performance issues, and observing user behavior.

[.sr-only]
<<{tools-path-prefix}observability#,See Observability Kit>>


[.card.commercial]
=== SSO Kit

image::{tools-icon-path-prefix}_images/lock-solid.svg[opts=inline, role=icon,32,32]

Integrate your Vaadin application with third-party identity providers, and give users single sign-on capabilities.

[.sr-only]
<<{tools-path-prefix}sso#,See SSO Kit>>


[.card.commercial]
=== Swing Kit

image::{tools-icon-path-prefix}_images/sync-solid.svg[opts=inline, role=icon,32,3w]

Swing Kit is designed to render Vaadin views inside Swing applications. You can gradually modernize your existing Swing application using Vaadin, upgrading the application view-by-view.

[.sr-only]
<<{tools-path-prefix}swing#,See Swing Kit>>


[.cards.large.quiet]
== Other Tools


[.card.commercial]
=== Multiplatform Runtime [badge-flow]#Flow#

image::{tools-icon-path-prefix}_images/rocket-solid.svg[opts=inline, role=icon,32,32]

Run applications and components written with Vaadin 7/8 inside a Vaadin 10+ Flow application.

[.sr-only]
<<{tools-path-prefix}mpr#,See Multiplatform Runtime>>


[.card.commercial]
=== Design System Publisher

image::{tools-icon-path-prefix}_images/folder-open.svg[opts=inline, role=icon,32,32]

Create a documentation website for your own Vaadin-based design system.

[.sr-only]
<<{tools-path-prefix}dspublisher#,See Design System Publisher>>


[.card.commercial]
=== Designer

image::{tools-icon-path-prefix}_images/paint-brush-solid.svg[opts=inline, role=icon,32,32]

Create UIs visually by dragging and dropping components on a canvas.

[.sr-only]
<<{tools-path-prefix}designer#,See Designer>>


[.card]
=== AI Form Filler

image::{tools-icon-path-prefix}_images/brain-solid.svg[opts=inline, role=icon,32,3w]

Use natural language input sources to automatically fill forms created with Flow using AI LLM models.

[.sr-only]
<<{tools-path-prefix}ai-form-filler#,See AI Form Filler>>

// end::all-tools[]
