---
title: Tools
order: 600
layout: index
---

= Tools

Speed up development with official Vaadin tools.

[.cards.large.quiet.hide-title]
== Developer Tools

[.card]
=== Collaboration Engine
image::{articles}/_images/ce.svg[opts=inline, role=icon]
The simplest way to build real-time collaboration into web apps.
<<{articles}/tools/ce#,See Collaboration Engine>>

[.card]
=== Designer
image::{articles}/_images/designer.svg[opts=inline, role=icon]
Create UIs visually by dragging and dropping components on a canvas.
<<{articles}/tools/designer#,See Designer>>

[.card]
=== Multiplatform Runtime
image::{articles}/_images/flow.svg[opts=inline, role=icon]
Run applications and components written with Vaadin 7/8 inside a Vaadin 10+ Flow application.
<<{articles}/tools/mpr#,See Multiplatform Runtime>>

[.card]
=== Design System Publisher
image::{articles}/_images/dsp.svg[opts=inline, role=icon]
Create a documentation website for your own Vaadin-based design system.
<<{articles}/tools/dspublisher#,See Design System Publisher>>

[.card]
=== SSO Kit
image::{articles}/_images/sso.svg[opts=inline, role=icon]
Integrate your Vaadin application with 3rd-party identity providers, and allow your users to benefit from single sign-on capabilities.
<<{articles}/tools/sso#,See SSO Kit>>

[.card]
=== Observability Kit
image::{articles}/_images/observability-kit.svg[opts=inline, role=icon]
Get insight into Flow applications at runtime and in production by monitoring application health, detecting unhandled errors and performance issues, and observing user behavior.
<<{articles}/tools/observability#,See Observability Kit>>

[.card]
=== Azure Kit
image::{articles}/_images/azure-kit.svg[opts=inline, role=icon]
Deploy your Vaadin apps to the cloud.
<<{articles}/tools/azure#,See Azure Kit>>

[.card]
=== Swing Kit
// image::{articles}/_images/dsp.svg[opts=inline, role=icon]
Swing Kit is a tool designed to render Vaadin views inside Swing applications.
You can gradually modernize your existing Swing application using Vaadin, upgrading the application view-by-view.
<<{articles}/tools/swing#,See Swing Kit>>
