---
title: Vaadin 14 to 23 Upgrade Instructions
order: 10
---

= Vaadin 14 to 23 Upgrade Instructions

This chapter contains the list of changes required to upgrade a Vaadin 14 application to Vaadin 23.
It includes the essential instructions needed for the project to compile, run, and behave in Vaadin 23 as it did in Vaadin 14.

The <<recommended-changes#,Recommended Changes>> chapter lists further changes that are recommended to conform with Vaadin 23 best practices and to avoid the usage of deprecated APIs and features.


[NOTE,role=small]
This guide provides instructions to upgrade from Vaadin 14 to 23.
If you are upgrading from an earlier version, follow the <<../../../v14/flow/upgrading#,upgrading instructions here>> to bring your application to version 14 first, before continuing with this guide.
You can also use applications or components developed with Vaadin 7 or 8 inside an application written using the latest version using <<{articles}/tools/mpr/overview#,Multiplatform Runtime>>.


include::instructions/_common.adoc[]

== Update Your CSS
.Click and read if you have styled Vaadin components.
[%collapsible]
====
include::instructions/_styling.adoc[]
====

== Update Your Templates
.Click and read if you are using Lit templates.
[%collapsible]
====
include::instructions/_typescript.adoc[]
====

== After the Upgrade
include::instructions/_after-upgrade.adoc[]
