---
title: Other
page-title: How to style other visual component styles with Aura in Vaadin
description: Aura style properties related to sizing, spacing, corner shapes, shadows, and other visual styles.
meta-description: Explore other visual styling options using the Aura theme in Vaadin.
order: 40
---

= Aura: Other Properties

`--aura-base-size`::
Aura redefines the base style <<../base#gap,gap>> and <<../base#padding,padding>> properties, and those values are computed based on this property. The property value is a number without a unit (i.e., _not_ a CSS length value). Suitable values range from 12 to 24. The resulting `--vaadin-gap` and `--vaadin-padding` values are defined with the `px` unit and are rounded to nearest 1px.

`--aura-base-radius`::
Aura redefines the base style <<../base#radius,radius>> properties, and those values are computed based on this property. The property is a number without a unit (i.e., _not_ a CSS length value). Suitable values range from 0 to 10, depending on the `--aura-base-size` value.
+
Setting the base radius to zero doesn't make all corners square. If you wish to remove all rounded corners, override the <<../base#radius,base style radius properties>> directly.

`--aura-shadow-m`::
`--aura-shadow-color`::

`--aura-overlay-shadow`::
`--aura-overlay-outline-color`::
`--aura-overlay-inner-outline-color`::
`--aura-overlay-backdrop-filter`::
