---
title: Typography
page-title: How to style typography with Aura in Vaadin
description: Tables of Aura style properties related to displaying and formatting text.
meta-description: Explore typography styling options using the Aura theme in Vaadin.
order: 20
---

= Aura Typography


== Font Family

[.property-table]
`--aura-font-family`::
The font family used for the application. Set on the `<body>` element. Defaults to `--aura-font-family-instrument-sans`.

`--aura-font-family-system` xref:./#read-only-properties[Read-only,role=badge]::
The system font stack, where the default sans-serif font of the operating system is used.

`--aura-font-family-instrument-sans` xref:./#read-only-properties[Read-only,role=badge]::
A font stack using the Instrument Sans font by default, and falling back to the system font stack if the web font fails to load.

`--aura-font-smoothing`::
Set to `auto` to disable grayscale/anti-aliased font smoothing and use the default sub-pixel anti-aliasing.


== Font Size

[.property-table]
`--aura-base-font-size`::
A number without a unit (e.g., `16` instead of `16px`) that represents the medium font size in pixels. The default is `14`.

The base font size is used to compute the following font size properties. The font sizes are defined with the `rem` unit and rounded to the nearest full pixel size.

[.property-table]
`--aura-font-size-xs` xref:./#read-only-properties[Read-only,role=badge]::
Extra small font size. The default corresponds to `11px`.

`--aura-font-size-s` xref:./#read-only-properties[Read-only,role=badge]::
Small font size. The default corresponds to `13px`.

`--aura-font-size-m` xref:./#read-only-properties[Read-only,role=badge]::
Medium font size. The default corresponds to `14px`.

`--aura-font-size-l` xref:./#read-only-properties[Read-only,role=badge]::
Large font size. The default corresponds to `16px`.

`--aura-font-size-xl` xref:./#read-only-properties[Read-only,role=badge]::
Extra large font size. The default corresponds to `18px`.

Aura supports the https://developer.apple.com/design/human-interface-guidelines/typography#Supporting-Dynamic-Type[Dynamic Type feature on iOS and iPadOS], which allows the user to set a font size preference in the OS settings.


== Line Height

[.property-table]
`--aura-base-line-height`::
A number without a unit (e.g., `1.5` instead of `24px`), relative to the corresponding font size. The default is `1.4`.

The base line height is used to compute the following line height properties. The line heights are defined with the `rem` unit and rounded to the nearest 2 pixels. Each line height is designed to be used together with the corresponding font size.

[.property-table]
`--aura-line-height-xs` xref:./#read-only-properties[Read-only,role=badge]::
Extra small line height. The default corresponds to `16px`.

`--aura-line-height-s` xref:./#read-only-properties[Read-only,role=badge]::
Small line height. The default corresponds to `18px`.

`--aura-line-height-m` xref:./#read-only-properties[Read-only,role=badge]::
Medium line height. The default corresponds to `20px`.

`--aura-line-height-l` xref:./#read-only-properties[Read-only,role=badge]::
Large line height. The default corresponds to `22px`.

`--aura-line-height-xl` xref:./#read-only-properties[Read-only,role=badge]::
Extra large line height. The default corresponds to `26px`.


== Font Weight

Static font weight properties.

[.property-table]
`--aura-font-weight-regular`::
Regular font weight. The default is `400`.

`--aura-font-weight-medium`::
Medium font weight. The default is `500`. Used for input field labels, buttons, menu/nav/tab items, grid headers, etc.

`--aura-font-weight-semibold`::
Semi-bold font weight. The default is `600`. Used for headings and dialog titles.
