---
title: Threads
description: How to use threads in your Vaadin Flow user interface.
order: 10
section-nav: badge-flow
---


= User Interface Threads [badge-flow]#Flow#

Developers often use server push to update the user interface from background jobs (see <<{articles}/building-apps/application-layer/background-jobs/interaction#,Background Jobs - UI Interaction>>). However, in Vaadin Flow, there are also cases where you want to start a separate thread for use by the user interface itself. You might, for instance, want to show the server date and time in "real time".

If you've used Swing before, you might be tempted to use a `Timer`, or to start a new `Thread` manually. In Flow, this is not a good idea. The reason is that Flow applications are multi-user applications, with potentially thousands of concurrent users. If each user creates its own `Timer`, or starts its own `Thread`, you may run out of threads. If that happens, the application crashes.

Instead, you should use virtual threads, or Spring's `TaskExecutor` and `TaskScheduler`.

[NOTE]
The examples on this page only work with push enabled. For information about how to do that, see the <<.#enabling-push-flow,Server Push>> documentation page.


== Virtual Threads

If you use a Java version that supports virtual threads, you can start up a new virtual thread whenever you need one. 

Here is an example of a button click listener that starts a new virtual thread:

[source,java]
----
button.addClickListener(clickEvent -> {
    Thread.ofVirtual().start(UI.getCurrent().accessLater(() -> {
        // Perform the UI operation here.
    }, null));
});
----

This is the easiest way of starting a new user interface thread. If you are able to use virtual threads, they should be your first choice. If you run into problems, switch to the `TaskExecutor`.

For scheduled tasks, you should still use the `TaskScheduler`. This is covered later in this documentation page.


== Task Executor

Setting up Spring's `TaskExecutor` and `TaskScheduler` is covered in the <<{articles}/building-apps/application-layer/background-jobs#,Background Jobs>> documentation page. You can use them to start tasks directly from the user interface as well. However, before you do, you should make sure your task is actually UI-related and not a background job.

To use the `TaskExecutor` or `TaskScheduler`, you inject them into your view, and then call them when needed. 

Here is an example of a view that gets the `TaskExecutor` as a constructor parameter:

[source,java]
----
@Route
public class MyView extends VerticalLayout {

    private final TaskExecutor taskExecutor;

    public MyView(TaskExecutor taskExecutor) {
        this.taskExecutor = taskExecutor;
        ...
    }
}
----

Here is an example of a button click listener that starts a UI operation in a background thread:

[source,java]
----
button.addClickListener(clickEvent -> {
    taskExecutor.execute(UI.getCurrent().accessLater(() -> {
        // Perform the UI operation here.
    }, null));
});
----

Because of the call to `UI.accessLater()`, the user interface is automatically updated through a server push when the task finishes.

[CAUTION]
Do not use the `@Async` annotation in your Flow views. It turns them into proxies that do not work with Vaadin.


== Task Scheduler

You can use the `TaskScheduler` to schedule tasks. In this case, you have to schedule the task when the component is attached, and cancel it when it is detached.

The following example schedules a task to be executed every second. The task sets the text of `currentTimeLabel` to the current date and time of the server. When the component is detached, the task is cancelled:

[source,java]
----
@Override
protected void onAttach(AttachEvent attachEvent) {
    var task = taskScheduler.scheduleAtFixedRate(
        attachEvent.getUI().accessLater(() -> {
            currentTimeLabel.setText(Instant.now().toString());
        }, null), Duration.ofSeconds(1)
    );
    addDetachListener(detachEvent -> {
        detachEvent.unregisterListener();
        task.cancel(true);
    });
}
----

The tasks that you execute in the task scheduler should be fast. If you need to schedule long-running tasks, you should hand them over to `TaskExecutor` for execution.

[CAUTION]
Do not use the `@Scheduled` annotation in your Flow views. It turns them into proxies that do not work with Vaadin.
