---
title: Advanced Topics
order: 3
layout: page
---


[[appseckit.advanced]]
= Advanced Topics

This page highlights some advanced topics related to AppSec Kit.

== AppSec Kit Configuration

This section describes the configuration options and their default values. The AppSec Kit has the `AppSecConfiguration` class. An instance of this class can be set to configure the `AppSecService` like so:

[source,java]
----
AppSecConfiguration configuration = new AppSecConfiguration();
configuration.setAutoScanInterval(Duration.ofDays(2));

AppSecService.getInstance().setConfiguration(appSecConfiguration);
----

You can set or override the following configuration values in the `AppSecConfiguration`:

- `dataFilePath` is the path of the data file for storing information about the vulnerabilities;
- `bomFilePath` is the path of the SBOM (Software Bill Of Materials) file used as a source of dependencies;
- `taskExecutor` is the executor used to run asynchronous tasks during the vulnerability scanning;
- `autoScanInterval` is the duration of the interval between automatic scanning for vulnerabilities; and
- `osvApiRatePerSecond` is the rate per second for the OSV (Open Source Vulnerability) API calls.


=== Data File Path

In the `Vulnerability Details View`, you can add analysis of the vulnerability. When this analysis is saved with the vulnerability information, it's stored in a data file in JSON format. Its default path and file name are `vaadin.appsec.data/appsec-data.json`.


=== SBOM File Path

Your application dependencies in the `Dependencies View` are populated from this file. The file should contain the dependencies in link:https://cyclonedx.org/specification/overview/[CycloneDX JSON schema] format. The default path and file name are `/resources/bom.json`.


=== Task Executor

You can set a custom executor for the background and scheduled jobs run by the AppSec Kit. For example, scheduled jobs are run when an automatic or manual vulnerability scan happens. The default task executor is a single-thread executor.


=== Auto Scan Interval

You can configure the duration of the interval between automatic scanning for vulnerabilities. The default interval is 1 day.


=== OSV Rate Per Second

You can configure the rate per second value for the OSV (Open Source Vulnerability) link:https://google.github.io/osv.dev/api/[API] calls. The default value is 25.
