---
title: Troubleshooting
page-title: Troubleshooting for Vaadin Control Center
description: Troubleshooting tips for Control Center.
meta-description: Learn about how to fix problems that may happen when using Vaadin's Control Center tool.
order: 80
---


= Troubleshooting

When installing Control Center or deploying an application using Control Center, you may encounter issues that are not caused by Control Center itself, but by external factors such as cluster resource limits, DNS propagation delays, or misconfigured dependencies.


== Insufficient Cluster Resources

When Control Center instance is slow to respond.

=== Solution

- Check resource allocation:

[source,shell]
----
kubectl describe node
----

- Increase CPU/memory limits.

== DNS Record Propagation Delays

When Control Center's URL or a deployed application's URL is not resolving after being deployed.

=== Solution

- Verify DNS records:

[source,shell]
----
nslookup <domain>
----

- Wait for propagation.
- Check external DNS settings.

== Crash Loop

When a deployed application never becomes available because it keeps crashing on startup.
This might be caused due to using an invalid docker image, or by Kubernetes killing a deployment that takes too long to startup thinking it is just dead since its liveness probe would not respond successfully.

=== Solution

Double-check the image of the deployed application. If the image is invalid, the deployment won't ever become available.

Check the application logs and make sure they do not show any problematic message.
If a specific error is shown in the logs, address it accordingly.
If no specific error is shown in the logs, increase the startup delay time just enough to give it time to finish.
