---
title: Styling
page-title: How to style the Combo Box component | Vaadin components
description: Styling API reference for the Combo Box component.
meta-description: Customize and style the Vaadin Combo Box component to fit your app's design system.
order: 50
---
= Combo Box Styling

include::../_styling-section-theming-props.adoc[tag=style-properties]

include::../_styling-section-theming-props.adoc[tag=input-fields]

include::../_styling-section-theming-props.adoc[tag=input-surface]

include::../_styling-section-theming-props.adoc[tag=label-helper-error]

include::../_styling-section-theming-props.adoc[tag=input-icons]

include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-combo-box`


=== States

Required:: `vaadin-combo-box+++<wbr>+++**[required]**`
Focused:: `vaadin-combo-box+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-combo-box+++<wbr>+++**[focus-ring]**`
Read-only:: `vaadin-combo-box+++<wbr>+++**[readonly]**`
Disabled:: `vaadin-combo-box+++<wbr>+++**[disabled]**`
Not empty:: `vaadin-combo-box+++<wbr>+++**[has-value]**`
With open overlay:: `vaadin-combo-box+++<wbr>+++**[opened]**`
Loading items:: `vaadin-combo-box+++<wbr>+++**[loading]**`
Hovered:: `vaadin-combo-box+++<wbr>+++**:hover**`


=== Field

Field surface (background, border):: `vaadin-combo-box+++<wbr>+++**::part(input-field)**`
Native input element:: `vaadin-combo-box+++<wbr>+++** > input**`
Input field with placeholder shown:: `vaadin-combo-box+++<wbr>+++** > input:placeholder-shown**`
Clear and Toggle buttons:: `vaadin-combo-box+++<wbr>+++**::part(field-button)**`
Toggle Button:: `vaadin-combo-box+++<wbr>+++**::part(toggle-button)**`
Clear button:: `vaadin-combo-box+++<wbr>+++**::part(clear-button)**`
Clear button icon:: `vaadin-combo-box+++<wbr>+++**::part(clear-button)::before**`
Prefix element:: `vaadin-combo-box+++<wbr>+++** > [slot="prefix"]**`


=== Label

Field with label:: `vaadin-combo-box+++<wbr>+++**[has-label]**`
Label:: `vaadin-combo-box+++<wbr>+++**::part(label)**`
Label text:: `vaadin-combo-box+++<wbr>+++** > label**`
Required indicator:: `vaadin-combo-box+++<wbr>+++**::part(required-indicator)**`


=== Helper and Validation Error

Field with helper:: `vaadin-combo-box+++<wbr>+++**[has-helper]**`
Helper:: `vaadin-combo-box+++<wbr>+++**::part(helper-text)**`
Helper text:: `vaadin-combo-box+++<wbr>+++** > [slot="helper"]**`
Invalid field:: `vaadin-combo-box+++<wbr>+++**[invalid]**`
Field with error message:: `vaadin-combo-box+++<wbr>+++**[has-error-message]**`
Error message:: `vaadin-combo-box+++<wbr>+++**::part(error-message)**`
Error message text:: `vaadin-combo-box+++<wbr>+++** > [slot="error-message"]**`


=== Overlay

Overlay background:: `vaadin-combo-box+++<wbr>+++**::part(overlay)**`
Overlay content wrapper:: `vaadin-combo-box+++<wbr>+++**::part(content)**`
Overlay loading indicator:: `vaadin-combo-box+++<wbr>+++**::part(loader)**`


=== Items

Item element:: `vaadin-combo-box-item`
Selected item:: `vaadin-combo-box-item+++<wbr>+++**[selected]**`
Item selection indicator:: `vaadin-combo-box-item+++<wbr>+++**::part(checkmark)**`
Item selection indicator icon:: `vaadin-combo-box-item+++<wbr>+++**::part(checkmark)::before**`
Focused item:: `vaadin-combo-box-item+++<wbr>+++**[focused]**`
Item content wrapper:: `vaadin-combo-box-item+++<wbr>+++**::part(content)**`
Hovered item:: `vaadin-combo-box-item+++<wbr>+++**:hover**`
