---
title: Styling
page-title: How to style the Combo Box component | Vaadin components
description: Styling API reference for the Combo Box component.
meta-description: Customize and style the Vaadin Combo Box component to fit your app's design system.
order: 50
---
= Combo Box Styling


// Style Variants

include::{articles}/components/_input-field-common-features.adoc[tags=styles-start;text-alignment;small-variant;helper-above-field;styles-end]

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/combobox/combo-box-styles.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/combobox/ComboBoxStyles.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/combobox/react/combo-box-styles.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


include::../_styling-section-theming-props.adoc[tag=style-properties]

include::../_styling-section-theming-props.adoc[tag=input-fields]

include::../_styling-section-theming-props.adoc[tag=input-surface]

include::../_styling-section-theming-props.adoc[tag=label-helper-error]

include::../_styling-section-theming-props.adoc[tag=input-icons]

// tag::overlay-style-props[]
=== Overlay

ifndef::overlay-width-prop[]
:overlay-width-prop: --vaadin-combo-box-overlay-width
endif::[]
ifndef::overlay-max-height-prop[]
:overlay-max-height-prop: --vaadin-combo-box-overlay-max-height
endif::[]

[cols="2,1"]
|===
| Property | Supported by

|`{overlay-width-prop}`
|Aura, Lumo

|`{overlay-max-height-prop}`
|Aura, Lumo

|`--vaadin-item-overlay-padding`
|Aura

|`--vaadin-overlay-background`
|Aura

|`--vaadin-overlay-border-color`
|Aura

|`--vaadin-overlay-border-radius`
|Aura

|`--vaadin-overlay-border-width`
|Aura

|`--vaadin-overlay-shadow`
|Aura

|`--vaadin-spinner-color`
|Aura

|`--vaadin-spinner-width`
|Aura

|`--vaadin-spinner-size`
|Aura

|`--vaadin-spinner-animation-duration`
|Aura

|===
// end::overlay-style-props[]

include::../_styling-section-theming-props.adoc[tag=overlay-items]

include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-combo-box`

Overlay root element:: `vaadin-combo-box-overlay`


=== States

Required:: `vaadin-combo-box+++<wbr>+++**[required]**`
Focused:: `vaadin-combo-box+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-combo-box+++<wbr>+++**[focus-ring]**`
Read-only:: `vaadin-combo-box+++<wbr>+++**[readonly]**`
Disabled:: `vaadin-combo-box+++<wbr>+++**[disabled]**`
Not empty:: `vaadin-combo-box+++<wbr>+++**[has-value]**`
With open overlay:: `vaadin-combo-box+++<wbr>+++**[opened]**`
Loading items:: `vaadin-combo-box+++<wbr>+++**[loading]**`
Hovered:: `vaadin-combo-box+++<wbr>+++**:hover**`


=== Field

Field surface (background, border):: `vaadin-combo-box+++<wbr>+++**::part(input-field)**`
Native input element:: `vaadin-combo-box+++<wbr>+++** > input**`
Input field with placeholder shown:: `vaadin-combo-box+++<wbr>+++** > input:placeholder-shown**`
Clear and Toggle buttons:: `vaadin-combo-box+++<wbr>+++**::part(field-button)**`
Toggle Button:: `vaadin-combo-box+++<wbr>+++**::part(toggle-button)**`
Clear button:: `vaadin-combo-box+++<wbr>+++**::part(clear-button)**`
Clear button icon:: `vaadin-combo-box+++<wbr>+++**::part(clear-button)::before**`
Prefix element:: `vaadin-combo-box+++<wbr>+++** > [slot="prefix"]**`


=== Label

Field with label:: `vaadin-combo-box+++<wbr>+++**[has-label]**`
Label:: `vaadin-combo-box+++<wbr>+++**::part(label)**`
Label text:: `vaadin-combo-box+++<wbr>+++** > label**`
Required indicator:: `vaadin-combo-box+++<wbr>+++**::part(required-indicator)**`


=== Helper and Validation Error

Field with helper:: `vaadin-combo-box+++<wbr>+++**[has-helper]**`
Helper:: `vaadin-combo-box+++<wbr>+++**::part(helper-text)**`
Helper text:: `vaadin-combo-box+++<wbr>+++** > [slot="helper"]**`
Invalid field:: `vaadin-combo-box+++<wbr>+++**[invalid]**`
Field with error message:: `vaadin-combo-box+++<wbr>+++**[has-error-message]**`
Error message:: `vaadin-combo-box+++<wbr>+++**::part(error-message)**`
Error message text:: `vaadin-combo-box+++<wbr>+++** > [slot="error-message"]**`


=== Overlay

Overlay background:: `vaadin-combo-box+++<wbr>+++**::part(overlay)**`
Overlay content wrapper:: `vaadin-combo-box+++<wbr>+++**::part(content)**`
Overlay loading indicator:: `vaadin-combo-box+++<wbr>+++**::part(loader)**`


=== Items

Item element:: `vaadin-combo-box-item`
Selected item:: `vaadin-combo-box-item+++<wbr>+++**[selected]**`
Item selection indicator:: `vaadin-combo-box-item+++<wbr>+++**::part(checkmark)**`
Item selection indicator icon:: `vaadin-combo-box-item+++<wbr>+++**::part(checkmark)::before**`
Focused item:: `vaadin-combo-box-item+++<wbr>+++**[focused]**`
Item content wrapper:: `vaadin-combo-box-item+++<wbr>+++**::part(content)**`
Hovered item:: `vaadin-combo-box-item+++<wbr>+++**:hover**`
