---
title: Importing to an IDE
description: How to import a starter application into an IDE.
layout: tabbed-page
tab-title: Overview
order: 25
---


= Importing to an IDE

Once you've downloaded and unpacked a starter application, you're ready to import it to your IDE. See <<{articles}/guide/start#, Starting a Project>> for instructions for creating or downloading a starter project, or creating one from a Maven archetype.

== Commonly Used IDEs

Different IDEs have different levels of support for Java and TypeScript.
The following table gives a rough evaluation of language support in the most commonly used IDEs.

.Commonly used IDEs
[%header, cols="3,1,1"]
|====
| IDE | Java  | TypeScript
| Eclipse | &star;&star;&star; | &star;&star;
| IntelliJ IDEA Community Edition| &star;&star;&star; | –
| IntelliJ IDEA Ultimate| &star;&star;&star; | &star;&star;&star;
| NetBeans | &star;&star;&star; | &star;
| VS Code | &star;&star; | &star;&star;&star;
|====
&star; &ndash; Supported with a commercial add-on or a very limited free add-on

&star;&star; &ndash; Limited built-in support or a free add-on with some limitations

&star;&star;&star; &ndash; Good built-in support or a good free add-on easy to install

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++