---
title: Flow components in Hilla view
description: Embedding Custom Flow components in Hilla views.
order: 500
---


= Custom Flow Components in Hilla

Custom Flow components can be embedded in a Hilla view by implementing a [classname]`WebComponentExporter` and using it in the view. A [classname]`WebComponentExporter` can target any Flow Component.

Below is an example for a component that follows:

[source,java]
----
public class CustomComponent extends Div {

    public CustomComponent(@Autowired GreetService service) {
        Button button = new Button("Say hello", e -> {
            Notification.show("Hello!");
        });

        add(button);
    }
}
----

This would then be embedded into a [classname]`WebComponent` like so:

[source,java]
----
public class MyFlowComponentExporter
        extends WebComponentExporter<CustomComponent> {

    public static final String TAG = "my-flow-component";

    public MyFlowComponentExporter() {
        super(TAG);
    }

    @Override
    protected void configureInstance(WebComponent<CustomComponent> webComponent,
                                     CustomComponent component) {
    }
}
----

For more information, see <<{articles}/flow/integrations/embedding/exporter#,Creating an Embedded Vaadin Application>>.

[NOTE]
The [classname]`WebComponentExporter` needs to have a public no-argument constructor. Otherwise, it won't be instantiated or generated.

To add the exported [classname]`WebComponent` to a Hilla view, import `createWebComponent` from Flow and create a `React.DOMElement` for the [classname]`WebComponent` `TAG`. Then use the element inside the view layout like this:

[source,typescriptjsx]
----
import { VerticalLayout } from "@vaadin/react-components/VerticalLayout";
import { createWebComponent } from "Frontend/generated/flow/Flow";

function MyFlowComponent() {
  return createWebComponent("my-flow-component");
}

export default function HillaView() {
  return (
    <>
      <VerticalLayout className={'centered-content'}>
        <h3>Hilla View</h3>
        <MyFlowComponent/>
      </VerticalLayout>
    </>
  );
}
----

When a component needs attributes or other custom parts in `React.createElement`, instead of importing `createWebComponent`, import `loadComponentScript` and create the element in the function.

This can be necessary when the [classname]`WebComponent` exposes properties to the client.

.Custom Properties for Flow WebComponent
[source,typescriptjsx]
----
import { VerticalLayout } from "@vaadin/react-components/VerticalLayout";
import { loadComponentScript } from "Frontend/generated/flow/Flow";
import React from "react";

function MyFlowComponent() {
  loadComponentScript("my-flow-component");
  // Create element with property hellomsg
  return React.createElement("my-flow-component", {
    hellomsg: 'Hi from the client!'
  });
}

export default function HillaView() {
  return (
    <>
      <VerticalLayout className={'centered-content'}>
        <h3>Hilla View</h3>
        <MyFlowComponent/>
      </VerticalLayout>
    </>
  );
}
----

.WebComponent with Exposed Properties
[source,java]
----
public class MyFlowComponentExporter
        extends WebComponentExporter<CustomComponent> {

    public static final String TAG = "my-flow-component";

    public MyFlowComponentExporter() {
        super(TAG);
        addProperty("hellomsg", "Hello!")
            .onChange(CustomComponent::setHelloMessage);
    }

    @Override
    protected void configureInstance(WebComponent<CustomComponent> webComponent,
                                     CustomComponent component) {
    }
}
----

.Flow Component with Property
[source,java]
----
public class CustomComponent extends Div {
    String helloMessage;

    public CustomComponent(@Autowired GreetService service) {
        Button button = new Button("Say hello", e -> {
            Notification.show(helloMessage);
        });

        add(button);
    }

    public void setHelloMessage(String helloMessage) {
        this.helloMessage = helloMessage;

    }
}
----

[discussion-id]`920dc03d-5eb4-4826-8934-4416b58a9a3e`
