[.example]
--

Run the application using the Java binary and pass the respective arguments for the Agent and configuration:
[source,terminal]
----
<source-info group="JAR file"></source-info>
java -javaagent:PATH/TO/vaadin-opentelemetry-javaagent-VERSION.jar \
     -Dotel.javaagent.configuration-file=PATH/TO/agent.properties \
     -jar myapp.jar
----

First create a file [filename]`setenv.bat` in your Tomcat installation's [filename]`bin` folder.
This script runs automatically with the startup script.
Add the content from below to that file, but with your particular installation's file paths.
Then start Tomcat using [filename]`bin/startup.bat`.
[source,terminal]
----
<source-info group="Tomcat (Windows)"></source-info>
set CATALINA_OPTS=%CATALINA_OPTS% -javaagent:PATH\TO\vaadin-opentelemetry-javaagent-VERSION.jar
set OTEL_JAVAAGENT_CONFIGURATION_FILE=PATH\TO\agent.properties
----

First create a file [filename]`setenv.sh` in your Tomcat installation's [filename]`bin` folder.
This script runs automatically with the startup script.
Add the content from below to that file, but with your particular installation's file paths.
Then start Tomcat using [filename]`bin/startup.sh`.
[source,terminal]
----
<source-info group="Tomcat (macOS/Linux)"></source-info>
export CATALINA_OPTS="$CATALINA_OPTS -javaagent:PATH/TO/vaadin-opentelemetry-javaagent-VERSION.jar"
export OTEL_JAVAAGENT_CONFIGURATION_FILE=PATH/TO/agent.properties
----

Start Jetty and pass the respective arguments for the Java agent and the agent configuration:
[source,terminal]
----
<source-info group="Jetty"></source-info>
java -javaagent:PATH/TO/vaadin-opentelemetry-javaagent-VERSION.jar \
     -Dotel.javaagent.configuration-file=PATH/TO/agent.properties \
     -jar /PATH/TO/jetty_home/start.jar
----

If you want to run an application with the agent through Maven for testing purposes, set the `MAVEN_OPTS` variable as shown below.
Then run your Maven goal, for example, `mvn jetty:run`.
[source,terminal]
----
<source-info group="Maven (Windows)"></source-info>
set MAVEN_OPTS="-javaagent:PATH\TO\vaadin-opentelemetry-javaagent-VERSION.jar -Dotel.javaagent.configuration-file=PATH\TO\agent.properties"
----

If you want to run an application with the agent through Maven for testing purposes, set the `MAVEN_OPTS` variable as shown below.
Then run your Maven goal, for example, `mvn jetty:run`.
[source,terminal]
----
<source-info group="Maven (macOS/Linux)"></source-info>
export MAVEN_OPTS="-javaagent:PATH/TO/vaadin-opentelemetry-javaagent-VERSION.jar -Dotel.javaagent.configuration-file=PATH/TO/agent.properties"
----
--

.Replace placeholder paths and version
[NOTE]
Remember to correct the path to the [filename]`agent.properties` file, as well as the path and version of the Observability Kit Agent `.jar` file.
