---
title: New Relic
tab-title: New Relic
order: 10
layout: page
---

= New Relic Integration

https://newrelic.com[New Relic] supports the export of metrics, traces and logs.

== Sign Up for a New Relic Account

A New Relic account can be created from https://newrelic.com/signup[here].
There is no cost for exporting up to 100GB of data per month.

== Limitations

New Relic will ignore all messages above a certain size.
To avoid losing data, messages can be automatically truncated using the property `otel.attribute.value.length.limit` (see below).

== Create Agent Properties File

Create a new properties file named `agent.properties` and add the following lines to it:

.`*agent.properties*`
[source,properties]
----
otel.traces.exporter=otlp
otel.logs.exporter=otlp
otel.metrics.exporter=otlp
otel.exporter.otlp.endpoint=ENDPOINT_URL
otel.exporter.otlp.headers=Api-Key=LICENSE_KEY
otel.exporter.otlp.protocol=http/protobuf
otel.attribute.value.length.limit=4095
----

[NOTE]
The `ENDPOINT_URL` can be found from the table in the https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup/#review-settings[New Relic documentation].

[NOTE]
The `LICENSE_KEY` can be found in your New Relic account settings under `API Keys`.
Be sure to use the license key of type `INGEST-LICENSE`.


== Running the App

include::./_run-app.asciidoc[opts=optional]

== Reading Telemetry Data

After using the application for a while (the traces will show up with a delay) log in to New Relic.

From the view `All entities`, select under `Services - OpenTelemetry` your service name (`vaadin` if you didn't specify your own).

Now you will have a menu where you can look through the telemetry data from you application.


|===
|Telemetry data |Data view |Documentation |View information

|Traces
|Monitor - Distributed tracing
|https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-distributed-tracing-page[Distributed tracing]
|Application traces showing count, duration and errors

|Logs
|Monitor - Logs
|https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-logs-page[Logs]
|Application logs that link to traces with `trace.id`

|Metrics
|Data - Metrics explorer
|https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-metrics-explorer-page[Metrics]
|Explore all reported metrics
|===

== Dashboard

We provide a preconfigured dashboard for New Relic that contains several metrics such as request throughput, error rate and JVM stats.

To use the dashboard, enter your New Relic account ID below and then click on `Generate`.

[NOTE]
You can get your account ID from the New Relic URL in the browser.

[source,html, role=render-only]
----
include::{root}/frontend/demo/tools/observability/newrelic/dashboard-generator.ts[render,tags=snippet,indent=0]
----

Then:

* Copy the dashboard JSON from above
* Open the New Relic UI in the browser.
* Open the `Dashboards` view, and then click on `Import dashboard` in the top-right.
* Paste the JSON that you copied from above, and then click on `Import dashboard`.
