---
title: Styling
description: Styling API reference for the Checkbox component.
order: 50
---
= Styling

include::../_styling-section-intros.adoc[tag=selectors]


=== Checkbox

Root element:: `vaadin-checkbox`
Focused:: `vaadin-checkbox+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-checkbox+++<wbr>+++**[focus-ring]**`
Disabled:: `vaadin-checkbox+++<wbr>+++**[disabled]**`
Hovered:: `vaadin-checkbox+++<wbr>+++**:hover**`
Pressed:: `vaadin-checkbox+++<wbr>+++**[active]**`
Checked:: `vaadin-checkbox+++<wbr>+++**[checked]**`
Indeterminate:: `vaadin-checkbox+++<wbr>+++**[indeterminate]**`
Checkbox box:: `vaadin-checkbox+++<wbr>+++**::part(checkbox)**`
Checkmark:: `vaadin-checkbox+++<wbr>+++**::part(checkbox)::after**`
Label:: `vaadin-checkbox+++<wbr>+++** > label**`


=== Checkbox Group

Root element:: `vaadin-checkbox-group`


==== States

Focused:: `vaadin-checkbox-group+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-checkbox-group+++<wbr>+++**[focus-ring]**`
Disabled:: `vaadin-checkbox-group+++<wbr>+++**[disabled]**`
Hovered:: `vaadin-checkbox-group+++<wbr>+++**:hover**`
One or more checkboxes checked:: `vaadin-checkbox-group+++<wbr>+++**[has-value]**`


==== Parts

Checkbox wrapper:: `vaadin-checkbox-group+++<wbr>+++**::part(group-field)**`
Checkboxes:: `vaadin-checkbox-group+++<wbr>+++** > vaadin-checkbox**`


==== Label

Checkbox group with label:: `vaadin-checkbox-group+++<wbr>+++**[has-label]**`
Label:: `vaadin-checkbox-group+++<wbr>+++**::part(label)**`
Label text:: `vaadin-checkbox-group+++<wbr>+++** > label**`
Required indicator:: `vaadin-checkbox-group+++<wbr>+++**::part(required-indicator)**`


==== Helper and Validation Error

Field with helper:: `vaadin-checkbox-group+++<wbr>+++**[has-helper]**`
Helper:: `vaadin-checkbox-group+++<wbr>+++**::part(helper-text)**`
Helper text:: `vaadin-checkbox-group+++<wbr>+++** > [slot="helper"]**`
Invalid field:: `vaadin-checkbox-group+++<wbr>+++**[invalid]**`
Error message:: `vaadin-checkbox-group+++<wbr>+++**::part(error-message)**`
Error message text:: `vaadin-checkbox-group+++<wbr>+++** > [slot="error-message"]**`

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++
