---
title: Using Playwright for end-to-end testing
description: How to setup and write e2e tests in TypeScript with Playwright.
order: 20
---
:lit:

= Playwright

If you prefer writing end-to-end tests in TypeScript, the following tools are recommended to use:

* https://playwright.dev/[Playwright] for writing and running tests in the browser.

This section is about setting up end-to-end tests for the Hilla application.
You can find detailed information in the Playwright https://playwright.dev/[documentation].

== Preparations

Run the following command in your application's root.

.terminal
[source,terminal]
----
npm init playwright@latest
----

Answer the questions and wait until Playwright is initialized.

== Test suites

Consider an application with the following entities.

.UsersEndpoint.java
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/hilla/testing/UsersEndpoint.java[tags=snippet,indent=0]
----

.User.java
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/hilla/testing/User.java[tags=snippet,indent=0]
----

.UserRepository.java
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/hilla/testing/UserRepository.java[tags=snippet,indent=0]
----

At the frontend side, the home page prints all available users to a list.

ifdef::lit[]
.users-page.ts
[source,typescript]
----
include::{root}src/main/resources/hilla/testing/frontend/lit/users-page.ts[tags=snippet,indent=0]
----
endif::lit[]
ifdef::react[]
.users-page.tsx
[source,typescriptjsx]
----
include::{root}/src/main/java/com/vaadin/demo/hilla/testing/UserRepository.java[tags=snippet,indent=0]
----
endif::react[]

To add the first test, create a file in the directory you have specified for the Playwright.
Replace `tests` in the paths of the command to the path of your directory.

[.example]
--
[source,terminal]
----
<source-info group="Unix"></source-info>
touch tests/UsersPage.test.ts
----

[source,terminal]
----
<source-info group="Windows"></source-info>
echo nul > tests\UsersPage.test.ts
----
--

Now you can add some tests for `UsersPage`.

.UsersPage.test.ts
[source,typescript]
----
include::{root}src/main/resources/hilla/testing/e2e/UsersPage.test.ts[tags=snippet,indent=0]
----

