---
title: Using Vaadin TestBench for End-to-End Testing
description: How to setup and write e2e tests in Java with TestBench.
order: 10
---
:lit:

// tag::content[]
= TestBench

:commercial-feature: TestBench
include::{articles}/_commercial-banner.asciidoc[opts=optional]

If you prefer writing end-to-end tests in Java, a couple of tools may be useful: For running tests in the browser, there's https://vaadin.com/testbench[Vaadin TestBench]. For writing and asserting, use https://junit.org/junit5[JUnit v5].

This section is about setting up end-to-end tests for the Hilla application. You can find detailed information in the  https://vaadin.com/docs/latest/testing/end-to-end[TestBench documentation].

[TIP]
If you prefer writing end-to-end tests in TypeScript, you can use instead Playwright. Setting up end-to-end tests with Playwright is described in the <<playwright#, Playwright documentation>>.


== Preparation

To prepare to do some end-to-end testing, add the following dependencies to the configuration file:

[.example]
--
[source,xml]
----
<source-info group="Maven"></source-info>
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-testbench-junit5</artifactId>
    <scope>test</scope>
</dependency>
----

[source,groovy]
----
<source-info group="Gradle"></source-info>
Not supported yet.
----
--



== Test Suites

Consider an application with the following entities in the `com/example/application/endpoints` directory:

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/hilla/testing/UsersEndpoint.java[tags=snippet,indent=0]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/hilla/testing/User.java[tags=snippet,indent=0]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/hilla/testing/UserRepository.java[tags=snippet,indent=0]
----

At the frontend side, the home page prints all available users to a list.

ifdef::lit[]

[source,typescript]
----
include::{root}/src/main/resources/hilla/testing/frontend/lit/users-page.ts[tags=snippet,indent=0]
----

endif::lit[]
ifdef::react[]

[source,typescriptjsx]
----
include::{root}/src/main/java/com/vaadin/demo/hilla/testing/UserRepository.java[tags=snippet,indent=0]
----

endif::react[]

To add the first test, create a file in the Java `test` directory. Instead of `com/example`, use the name of your package.

[.example]
--
[source,bash]
----
<source-info group="Unix"></source-info>
mkdir -p src/test/java/com/example && touch $_/UsersPageTest.java
----

[source,bash]
----
<source-info group="Windows"></source-info>
mkdir src\test\java\com\example; echo nul > src\test\java\com\example\UsersPageTest.java
----
--

Now you can add some tests for `UsersPage` like so:

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/hilla/testing/UsersPageTest.java[tags=snippet,indent=0]
----

// end::content[]
