---
title: Using Vaadin TestBench for end-to-end testing
description: How to setup and write e2e tests in Java with TestBench.
order: 10
---
:lit:

// tag::content[]
= TestBench

If you prefer writing end-to-end tests in Java, the following tools are recommended to use:

* https://vaadin.com/testbench[Vaadin TestBench] for running tests in the browser.
* https://junit.org/junit5/[JUnit 5] for writing tests.

:commercial-feature: TestBench
include::{articles}/_commercial-banner.asciidoc[opts=optional]

This section is about setting up end-to-end tests for the Hilla application.
You can find detailed information in the TestBench https://vaadin.com/docs/latest/testing/end-to-end[documentation].

[TIP]
If you prefer writing end-to-end tests in TypeScript, you can use Playwright.
Setting up end-to-end tests with Playwright is described in the relevant article.

== Preparations

Add the following dependencies to the configuration file.

[.example]
--
[source,xml]
----
<source-info group="Maven"></source-info>
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-testbench-junit5</artifactId>
    <scope>test</scope>
</dependency>
----

[source,groovy]
----
<source-info group="Gradle"></source-info>
Not supported yet.
----
--

== Test suites

Consider an application with the following entities.

.UsersEndpoint.java
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/hilla/testing/UsersEndpoint.java[tags=snippet,indent=0]
----

.User.java
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/hilla/testing/User.java[tags=snippet,indent=0]
----

.UserRepository.java
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/hilla/testing/UserRepository.java[tags=snippet,indent=0]
----

At the frontend side, the home page prints all available users to a list.

ifdef::lit[]
.users-page.ts
[source,typescript]
----
include::{root}src/main/resources/hilla/testing/frontend/lit/users-page.ts[tags=snippet,indent=0]
----
endif::lit[]
ifdef::react[]
.users-page.tsx
[source,typescriptjsx]
----
include::{root}/src/main/java/com/vaadin/demo/hilla/testing/UserRepository.java[tags=snippet,indent=0]
----
endif::react[]

To add the first test, create a file in the Java `test` directory.
Instead of `com/vaadin/demo/hilla/testing` use the name of your package.

[.example]
--
[source,terminal]
----
<source-info group="Unix"></source-info>
mkdir -p src/test/java/com/vaadin/demo/hilla/testing && touch $_/UsersPageTest.java
----

[source,terminal]
----
<source-info group="Windows"></source-info>
mkdir src\test\java\com\vaadin\demo\hilla\testing; echo nul > src\test\java\com\vaadin\demo\hilla\testing\UsersPageTest.java
----
--

Now you can add some tests for `UsersPage`.

.UsersPageTest.java
[source,java]
----
include::{root}/src/test/java/com/vaadin/demo/hilla/testing/UsersPageTest.java[tags=snippet,indent=0]
----

// end::content[]
