---
title: Styling
page-title: How to style the Accordion component | Vaadin components
description: Styling API reference for the Accordion component.
meta-description: Explore options to customize the appearance of the Accordion component in your Vaadin apps.
order: 50
---
= Accordion Styling


== Style Variants

Accordion supports the following style variants. Variants must be applied to individual panels, not to the Accordion itself.

[cols="1,3,1"]
|===
| Variant | Description | Supported by

|`filled`
|Makes the panel’s boundaries visible
|Aura, Lumo

|`no-padding`
|Removes the padding from the panel content area
|Aura

|`small`
|Used for compact UIs
| Lumo

|`reverse`
|Places the toggle icon after the summary contents
|Aura, Lumo

|===


=== Filled Panels

The `filled` style variant makes the panel's boundaries visible. This helps tie its content together visually and distinguishes it from the surrounding UI.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/accordion/accordion-filled-panels.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/accordion/AccordionFilledPanels.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/accordion/react/accordion-filled-panels.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

=== Small Panels

Use the `small` style variant for compact UIs.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/accordion/accordion-small-panels.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/accordion/AccordionSmallPanels.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/accordion/react/accordion-small-panels.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

=== Reverse Panels

The `reverse` style variant places the toggle icon after the summary contents. This can be useful for aligning visually the summary with other content.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/accordion/accordion-reverse-panels.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/accordion/AccordionReversePanels.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/accordion/react/accordion-reverse-panels.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

include::../_styling-section-theming-props.adoc[tag=style-properties]

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-accordion-heading-background`
|Aura

|`--vaadin-accordion-heading-border-color`
|Aura

|`--vaadin-accordion-heading-border-radius`
|Aura

|`--vaadin-accordion-heading-border-width`
|Aura

|`--vaadin-accordion-heading-font-size`
|Aura

|`--vaadin-accordion-heading-font-weight`
|Aura

|`--vaadin-accordion-heading-gap`
|Aura

|`--vaadin-accordion-heading-height`
|Aura

|`--vaadin-accordion-heading-padding`
|Aura

|`--vaadin-accordion-heading-text-color`
|Aura

|===

include::../_styling-section-intros.adoc[tag=selectors]

Root element:: `vaadin-accordion`


=== Panels
Panel element:: `vaadin-accordion-panel`
Opened panel:: `vaadin-accordion-panel+++<wbr>+++**[opened]**`
Disabled panel:: `vaadin-accordion-panel+++<wbr>+++**[disabled]**`
Panel body content wrapper:: `vaadin-accordion-panel+++<wbr>+++**::part(content)**`


=== Panel Heading
Heading element:: `vaadin-accordion-heading`
Toggle:: `vaadin-accordion-heading+++<wbr>+++**::part(toggle)**`
Toggle icon:: `vaadin-accordion-heading+++<wbr>+++**::part(toggle)::before**`
Panel header content wrapper:: `vaadin-accordion-heading+++<wbr>+++**::part(content)**`
