---
title: Deploying to Production
page-title: How to deploy Vaadin to Production
description: How to to compile and package an application to deploy to a production server.
meta-description: How to to compile and package your Vaadin application to deploy to a production server.
order: 210
---


= Deploying to Production

Deploying to a production server involves compiling and packaging the application to be suitable and optimized for the server.

Although you may have launched your server directly from your IDE during development, you need to deploy the application as a `WAR` file (Java Servlet) or `JAR` file that includes your application server (Spring Boot and other embedded servers) for production.

When you launch a Vaadin application from your IDE or using `spring-boot:run`, it runs in development mode.
When you package the application into a JAR or WAR file, it runs in production mode.
Development tools, such as the Vite dev server and live-reload, are available when you add the `vaadin-dev` dependency to your project.
When deploying your application to your users, make sure that development tools aren't included in the production build.

You can also run the application in production mode without packaging it, which can be useful for testing. With Maven, use:

[source,terminal]
----
mvn spring-boot:run -Dvaadin.productionMode
----

With Gradle, use:

[source,terminal]
----
./gradlew bootRun -Dvaadin.productionMode
----

The main difference between development and production mode is that, in production mode, the client resources can be optimized and minified to reduce the load on the network and browser even further. Furthermore, debug information (e.g., about the available routes) that is present in development mode is removed in production mode to ensure that no sensitive information leaks to the client.

== Topics

section_outline::[]
