---
title: Cookie Consent
description: Cookie Consent aims to help you comply with privacy laws such as General Data Protection Regulation (GDPR) and California Consumer Privacy Act (CCPA).
---

= Cookie Consent

:commercial-feature: Cookie Consent
include::{articles}/_commercial-banner.asciidoc[opts=optional]

They require users to be informed and explicitly give consent to the usage of cookies.

[source,tsx]
----
<CookieConsent />
----

By default, the banner is shown at the top of the screen with a predefined text, a link to https://www.cookiesandyou.com[cookiesandyou.com] which explains what cookies are, and a consent button.

== Localization

Cookie Consent is fully customizable.
You can customize the message, the "Learn More" link, the "Dismiss" button, as well as the component's position.

[source,tsx]
----
<CookieConsent
  message="Tämä sivusto käyttää evästeitä parhaan kokemuksen tarjoamiseksi"
  dismiss="Selvä"
  learnMore="Lue lisää"
  learnMoreLink="https://vaadin.com/terms-of-service"
/>
----

== Positioning

Cookie Consent can be positioned in the viewport in 4 non-stretched positions, or stretched across the top or bottom:

[cols="<,>"]
|===
|Top left
|Top right

|Bottom left
|Bottom right
|===

[cols="^"]
|===
|Top (stretch, default)
|Bottom (stretch)
|===

On smaller viewports, the component always takes up the entire width of the viewport.

== Theming

Cookie Consent's theme is modified using CSS.

:component-path: cookie-consent
include::{articles}/react/components/_vaadindocs.adoc[]
