---
title: Cookie Consent
description: Cookie Consent can help you to comply with privacy laws, such as General Data Protection Regulation (GDPR) and California Consumer Privacy Act (CCPA).
section-nav: commercial
---


= Cookie Consent

:commercial-feature: Cookie Consent
include::{articles}/_commercial-banner.asciidoc[opts=optional]

Privacy laws such as these require users to be informed and give consent explicitly to the usage of cookies.

[source,tsx]
----
<CookieConsent />
----

By default, a banner is positioned at the top of the screen with predefined text, along with a link to https://www.cookiesandyou.com[cookiesandyou.com] which explains the cookies, and a consent button.


== Localization

Cookie Consent is fully customizable. You can customize the message, the "Learn More" link, the "Dismiss" button, and the component's position. The example below shows text to be displayed to the user in Finnish:

[source,tsx]
----
<CookieConsent
  message="Tämä sivusto käyttää evästeitä parhaan kokemuksen tarjoamiseksi"
  dismiss="Selvä"
  learnMore="Lue lisää"
  learnMoreLink="https://vaadin.com/terms-of-service"
/>
----


== Positioning

Cookie Consent can be positioned in the viewport in four non-stretched positions, or stretched across the top or bottom. The tables below list and visually demonstrate these positions:

[cols="<,>"]
|===
|Top Left
|Top Right

|Bottom Left
|Bottom Right
|===

[cols="^"]
|===
|Top -- stretch, default
|Bottom -- stretch
|===

On smaller viewports, the component always spans the entire width of the viewport.


== Theming

Cookie Consent's theme is modified using CSS.

:component-path: cookie-consent
include::{articles}/react/components/_vaadindocs.adoc[]
