---
title: Context Menu
page-title: Context Menu component | Vaadin components
description: Context Menu is a component that can be attached to any component to display a context menu.
meta-description: Implement and configure context menus for better user interaction in your Vaadin applications.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/context-menu}/elements/vaadin-context-menu[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/contextmenu/ContextMenu.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/context-menu}/packages/context-menu[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-context-menu-flow-parent[Java]'
---


= Context Menu

// tag::description[]
Context Menu is a component that you can attach to any component to display a context menu.
// end::description[]
The menu appears on the right by default, or with a left click. On a touch device, a long press opens the context menu.

// tag::example-instructions[]
[IMPORTANT]
Open the Context Menu by right-clicking (i.e., with a mouse), or by long-pressing (i.e., on a touch screen), a Grid row.
// end::example-instructions[]

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-basic.ts[render,tag=snippet,indent=0,group=Lit]

<!-- ... -->

include::{root}/frontend/demo/component/contextmenu/context-menu-basic.ts[render,tag=snippethtml,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuBasic.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/contextmenu/react/context-menu-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Dividers

You can use dividers to separate and group related content. Use dividers sparingly to avoid creating unnecessary visual clutter.

include::index.adoc[tag=example-instructions]

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-dividers.ts[render,tag=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuDividers.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/contextmenu/react/context-menu-dividers.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Checkable Menu Items

Checkable Menu Items can be used to toggle a setting on and off.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-checkable.ts[render,tag=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuCheckable.java[render,tags=snippet1,indent=0,group=Flow]

...

include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuCheckable.java[render,tags=snippet2,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/contextmenu/react/context-menu-checkable.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Hierarchical Menu

Context Menu, like Menu Bar, supports multi-level sub-menus. You can use a hierarchical menu to organize a large set of options and group related items.

include::index.adoc[tag=example-instructions]

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-hierarchical.ts[render,tag=snippet,indent=0,group=Lit]

// ...

include::{root}/frontend/demo/component/contextmenu/context-menu-hierarchical.ts[render,tag=snippethtml,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuHierarchical.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/contextmenu/react/context-menu-hierarchical.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Custom Items

You can customize the items to include more than a single line of text.

include::index.adoc[tag=example-instructions]

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-presentation.ts[render,tag=snippet,indent=0,group=Lit]

...

include::{root}/frontend/demo/component/contextmenu/context-menu-presentation.ts[render,tag=snippethtml,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuPresentation.java[render,tags=snippet1,indent=0,group=Flow]
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuPresentation.java[render,tags=snippet2,indent=0,group=Flow]

// ...

include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuPresentation.java[render,tags=snippet3,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/contextmenu/react/context-menu-presentation.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Styling Menu Items

Individual menu items can be styled by [since:com.vaadin:vaadin@V24.3]#applying custom class names# to them, and writing CSS style blocks targeting those class names.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-classname.ts[render,tag=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuClassname.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/contextmenu/react/context-menu-classname.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

.Theme Names, Not Class Names
[NOTE]
In versions prior to 24.3, theme names must be used instead (i.e., `theme` property / `addThemeNames` Java method). The CSS syntax for targeting a theme name is `[theme~="custom-theme"]`


== Disabled Menu Items

You can disable menu items to show that they are unavailable.

include::index.adoc[tag=example-instructions]

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-disabled.ts[render,tag=snippet,indent=0,group=Lit]

// ...

include::{root}/frontend/demo/component/contextmenu/context-menu-disabled.ts[render,tag=snippethtml,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuDisabled.java[render,tags=snippet1,indent=0,group=Flow]

include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuDisabled.java[render,tags=snippet2,indent=0,group=Flow]

include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuDisabled.java[render,tags=snippet3,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/contextmenu/react/context-menu-disabled.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


[role="since:com.vaadin:vaadin@V24.6"]
=== Disable on Click (Flow)

To prevent duplicate clicks while the server is processing a request, call the `setDisableOnClick(true)` method on a menu item instance to disable immediately that menu item on the client-side when it's clicked.

[.example]
--

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuDisableOnClick.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

--


== Left-Click

You can use left-click to open Context Menu in situations where left-click doesn't have any other function (e.g., a Grid without selection support).

[IMPORTANT]
Open the Context Menu by clicking a Grid row.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-left-click.ts[render,tag=snippet,indent=0,group=Lit]

// ...

include::{root}/frontend/demo/component/contextmenu/context-menu-left-click.ts[render,tag=snippethtml,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuLeftClick.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/contextmenu/react/context-menu-left-click.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


[role="since:com.vaadin:vaadin@V24.7"]
== Custom Item Data

Context Menu allows you to associate custom data with menu items. This can be useful for storing additional information about the item, such as an item type or a value. The data can then be used to trigger actions when an item is selected.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-custom-item-data.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuCustomItemData.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/contextmenu/react/context-menu-custom-item-data.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Best Practices

Context Menu is used to provide shortcuts to the user. You shouldn't use it as the only or primary means to complete a task. The primary way should be accessible elsewhere in the UI.

[IMPORTANT]
Open the Context Menu by right-clicking (i.e., for desktops) or long-pressing (i.e., for mobile devices) a Grid row, or use the Menu Bar in the last column.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/contextmenu/context-menu-best-practices.ts[render,tag=snippet,indent=0,group=Lit]

// ...

include::{root}/frontend/demo/component/contextmenu/context-menu-best-practices.ts[render,tag=snippethtml,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuBestPractices.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/contextmenu/react/context-menu-best-practices.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Context Menu vs. Menu Bar

You should use Context Menu when there is no dedicated button for opening an overlay menu, such as right-clicking a grid row. When there is a dedicated element or component, such as an <<../menu-bar#,overflow menu>>, use Menu Bar.


=== Icons

Use icons when applicable to help improve recognition. It's recommended to use commonly recognized icons to avoid confusion. Use icons consistently throughout a list of options.


=== Labelling

Suffix a menu item with "..." when the associated action won't be executed, but instead reveal some UI, like a dialog, for completing the action.


== Related Components

|===
|Component |Usage Recommendations

|<<../menu-bar#,Menu Bar>>
|Component for displaying a horizontal menu with multi-level sub-menus.

|<<../popover#,Popover>>
|A generic overlay whose position is anchored to an element in the UI.

|===


[discussion-id]`760AB528-B02C-4B6C-BB27-D7EFEDAE706E`
