flowchart LR
    Browser[Browser] --> NavigationAccessControl[Navigation Access Control]    
    NavigationAccessControl --> DelegateEvaluation((Evaluate\nnavigation\npermission))
    DecisionResolver{Decision Resolver}
    subgraph SecurityRules
        direction TB
        ViewAccessChecker[Annotated View Checker]
        RoutePathAccessChecker[Route Path Checker]
        CustomAccessChecker1[Custom Access Checker 1]
        CustomAccessCheckerN[Custom Access Checker N]
    end
    DelegateEvaluation -.-> ViewAccessChecker
    DelegateEvaluation -.-> RoutePathAccessChecker
    DelegateEvaluation -.-> CustomAccessChecker1
    DelegateEvaluation -.-> CustomAccessCheckerN
    ViewAccessChecker -. Allow/Deny .-> DecisionResolver
    RoutePathAccessChecker -. Allow/Deny .-> DecisionResolver
    CustomAccessChecker1 -. Allow/Deny .-> DecisionResolver
    CustomAccessCheckerN -. Allow/Deny .-> DecisionResolver
    DecisionResolver --> Result[Allow or Deny]

