---
title: Grid Pro
page-title: Grid Pro component | Vaadin components
description: Grid Pro, an extension of Grid, provides inline editing with full keyboard navigation.
meta-description: Explore the advanced features of Vaadin Grid Pro component for efficient data editing and display.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/grid-pro}/elements/vaadin-grid-pro[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/gridpro/GridPro.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/grid-pro}/packages/grid-pro[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-grid-pro-flow-parent[Java]'
section-nav: commercial
---


= Grid Pro
:experimental:

:commercial-feature: Grid Pro
include::{articles}/_commercial-banner.adoc[opts=optional]

// tag::description[]
Grid Pro is an extension of the Grid component that provides inline editing with full keyboard navigation.
// end::description[]

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/gridpro/grid-pro-basic.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/gridpro/GridProBasic.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/gridpro/react/grid-pro-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

.Features Shared with Grid
[NOTE]
Grid Pro is an extension of the <<../grid#,Grid>> component. As a result, all of Grid's features are also available with Grid Pro.


== Usage

To use Grid Pro, begin by double-clicking on an editable cell. Then press kbd:[Enter], kbd:[Space], or type an alphanumeric character when an editable cell is focused.

When editing, there are a few keyboard shortcuts available:

- kbd:[Esc] discards the changes and exits edit mode.
- kbd:[Enter] and kbd:[Shift + Enter] save changes and exit edit mode.
- kbd:[Tab] and kbd:[Shift + Tab] save changes and move focus to the next or previous editable cell, respectively, while remaining in edit mode.


== Modes

Grid Pro has a few modes: edit on single-click; single cell edit; and enter next row. These are described in the sub-sections that follow.

=== Edit on Single-Click

Single-Click Edit is a mode that enables the user to begin editing by single-clicking on an editable cell.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/gridpro/grid-pro-single-click.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/gridpro/GridProSingleClick.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/gridpro/react/grid-pro-single-click.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Single Cell Edit

By default, when in edit mode, kbd:[Tab] moves the focus to the next cell and kbd:[Shift+Tab] moves the focus to the previous editable cell -- while remaining in edit mode. With Single Cell Edit, tabbing from one cell to another will exit from edit mode.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/gridpro/grid-pro-single-cell-edit.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/gridpro/GridProSingleCellEdit.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/gridpro/react/grid-pro-single-cell-edit.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Enter Next Row

Pressing kbd:[Enter] or kbd:[Shift+Enter] saves any changes and exits edit mode, by default. However, kbd:[Enter] can be made to move focus to the editable cell in the next row, by using the Enter Next Row mode. The same can be done for kbd:[Shift+Enter], but to move the focus to the editable cell in the previous row.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/gridpro/grid-pro-enter-next-row.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/gridpro/GridProEnterNextRow.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/gridpro/react/grid-pro-enter-next-row.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Edit Column

Editing is enabled on a per-column basis.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/gridpro/grid-pro-edit-column.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/gridpro/GridProEditColumn.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/gridpro/react/grid-pro-edit-column.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Recommended Built-in Editors

Grid Pro features three recommended built-in editors: Text Field; Checkbox; and Select. They're described in the table here.

[cols=2, options=header]
|===
|Editor
|Usage Recommendation

|Text
|Editing basic text.

|Checkbox
|Editing boolean (binary) values.

|Select
|Selecting a single value from a set of options.
|===

Although Grid Pro can be configured to use any input field for editing, the built-in editors have better keyboard usability and rendering.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/gridpro/grid-pro-editors.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/gridpro/GridProEditor.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/gridpro/react/grid-pro-editors.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Prevent Saving Changes

Whenever you enter incorrect or invalid data, it's possible to rollback changes.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/gridpro/grid-pro-prevent-save.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/gridpro/GridProPreventSave.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/gridpro/react/grid-pro-prevent-save.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


[role="since:com.vaadin:vaadin@V24.4"]
== Conditional Editability

In some situations you may need to disable editing of specific cells in an edit column. This can be done through a function that determines the editability of each cell. This function is automatically re-evaluated when an item in the Grid is modified.  As a result, modifying the value in one cell can immediately affect the editability of other cells.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/gridpro/grid-pro-cell-editability.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/gridpro/GridProCellEditability.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/gridpro/react/grid-pro-cell-editability.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Distinguish Editable from Read-Only

Editable cells are indicated with a hover effect, by default. You can also distinguish them by highlighting either editable or read-only cells. This is good for grids containing both types of cells.


=== Highlight Editable

Editable cells can be highlighted by applying the `highlight-editable-cells` theme variant.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/gridpro/grid-pro-highlight-editable-cells.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/gridpro/GridProThemeHighlightEditableCells.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/gridpro/react/grid-pro-highlight-editable-cells.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

You can also apply custom styling to editable cells by targeting the `editable-cell` part in CSS. The following example shows how to apply custom styling to all Grid Pro elements that have the `editable-custom-effect` class name:

[.example]
--
[source,css]
----
/* Add this to your global CSS, for example in: */
/* frontend/theme/[my-theme]/styles.css */

vaadin-grid-pro.editable-custom-effect::part(editable-cell):hover,
vaadin-grid-pro.editable-custom-effect::part(editable-cell focused-cell) {
  background: var(--lumo-contrast-10pct);
}

vaadin-grid-pro.editable-custom-effect::part(editable-cell) {
  background: var(--lumo-contrast-5pct);
}
----
--


=== Highlight Read-Only

Read-only cells can be highlighted by applying the `highlight-read-only-cells` theme variant.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/gridpro/grid-pro-highlight-read-only-cells.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/gridpro/GridProThemeHighlightReadOnlyCells.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/gridpro/react/grid-pro-highlight-read-only-cells.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Best Practices

=== Inline vs. Non-Inline Editing

Inline editing is recommended when the user will usually need to make many small changes to different items, and when quick editing is essential.

Non-inline editing is preferable when there are plenty of columns or fields, and when users typically need to edit only one item at a time. It's also preferred when adding new items is common, as you might want to have edit and create modes work the same way, and creating new items with inline editing isn't recommended with Grid Pro.

Use non-inline editing when any of the editors need to be larger than a simple field (e.g., Text Area and multi-select fields), or when fields alone may be insufficient (e.g., when helpers, validation errors or other features are needed). Also, use it when explicit save or cancel actions are beneficial, for example, to prevent accidental edits.

Incidentally, if your situation would benefit more from non-inline editing, consider using <<../crud#, CRUD>>.


== Related Components

|===
|Component | Usage Recommendations

|<<../crud#, CRUD>>
|Component for creating, displaying, updating and deleting tabular data.

|<<../grid#, Grid>>
|Component for showing tabular data.

// |<<../tree-grid#, Tree Grid>>
// |Component for showing hierarchical data.

|===


[discussion-id]`AACED59D-0972-417E-BA70-9464FEA8895C`
