---
title: Styling
page-title: How to style the Grid Pro component | Vaadin components
description: Styling API reference for the Grid Pro component.
meta-description: Learn to style the Grid Pro component for your Vaadin applications with examples and best practices.
order: 50
---
= Grid Pro Styling

== Style Variants

Grid Pro supports the following style variants:

[cols="1,3,1"]
|===
| Variant | Description | Supported by

|`highlight-editable-cells`
|Highlights editable cells with a background color
|Aura, Lumo

|`highlight-read-only-cells`
|Highlights read-only cells with a background color
|Aura, Lumo

|===

In addition, Grid Pro also supports all <<../grid/styling#style-variants,Grid Style Variants>>.

=== Highlight Editable

Editable cells are indicated with a hover effect, by default. They can be highlighted by applying the `highlight-editable-cells` style variant.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/gridpro/grid-pro-highlight-editable-cells.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/gridpro/GridProThemeHighlightEditableCells.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/gridpro/react/grid-pro-highlight-editable-cells.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

You can also apply custom styling to editable cells by targeting the `editable-cell` part in CSS. The following example shows how to apply custom styling to all Grid Pro elements that have the `editable-custom-effect` class name:

[.example]
--
[source,css]
----
vaadin-grid-pro.editable-custom-effect::part(editable-cell):hover,
vaadin-grid-pro.editable-custom-effect::part(editable-cell focused-cell) {
  background: var(--lumo-contrast-10pct);
}

vaadin-grid-pro.editable-custom-effect::part(editable-cell) {
  background: var(--lumo-contrast-5pct);
}
----

--


=== Highlight Read-Only

Read-only cells can be highlighted by applying the `highlight-read-only-cells` style variant.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/gridpro/grid-pro-highlight-read-only-cells.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/gridpro/GridProThemeHighlightReadOnlyCells.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/gridpro/react/grid-pro-highlight-read-only-cells.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]

--

include::../_styling-section-theming-props.adoc[tag=style-properties]

[cols="3,1"]
|===
| Property | Supported by

|`--vaadin-grid-pro-editable-cell-background-color`
|Aura

|===

In addition, Grid Pro also supports all <<../grid/styling#style-properties,Grid Style Properties>>.


include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-grid-pro`


=== Cells

Cell (any):: `vaadin-grid-pro+++<wbr>+++**::part(cell)**`
Header row cell:: `vaadin-grid-pro+++<wbr>+++**::part(header-cell)**`
Body cell:: `vaadin-grid-pro+++<wbr>+++**::part(body-cell)**`
Footer row cell:: `vaadin-grid-pro+++<wbr>+++**::part(footer-cell)**`
Focused cell:: `vaadin-grid-pro+++<wbr>+++**::part(focused-cell)**`
Editable cell:: `vaadin-grid-pro+++<wbr>+++**::part(editable-cell)**`
Cell contents:: `vaadin-grid-cell-content`
Cell in first column:: `vaadin-grid-pro+++<wbr>+++**::part(first-column-cell)**`
Cell in last column:: `vaadin-grid-pro+++<wbr>+++**::part(last-column-cell)**`
Cell in first row:: `vaadin-grid-pro+++<wbr>+++**::part(first-row-cell)**`
Cell in last column:: `vaadin-grid-pro+++<wbr>+++**::part(last-row-cell)**`
Cell in odd row:: `vaadin-grid-pro+++<wbr>+++**::part(odd-row-cell)**`
Cell in even row:: `vaadin-grid-pro+++<wbr>+++**::part(even-row-cell)**`
Cell in selected row:: `vaadin-grid-pro+++<wbr>+++**::part(selected-row-cell)**`
Cell in first header row:: `vaadin-grid-pro+++<wbr>+++**::part(first-header-row-cell)**`
Cell in last header row:: `vaadin-grid-pro+++<wbr>+++**::part(last-header-row-cell)**`
Cell focus ring:: `vaadin-grid+++<wbr>+++**::part(cell)::before**`
Row focus ring:: `vaadin-grid+++<wbr>+++**::part(row)::before**`


=== Selection Checkboxes

Row selection checkbox:: `vaadin-grid-pro+++<wbr>+++** > vaadin-checkbox**`
Select All checkbox:: `vaadin-grid-pro+++<wbr>+++** > #selectAllCheckbox**`


=== Sorters

Element:: `vaadin-grid-sorter`
Active sorter:: `vaadin-grid-sorter+++<wbr>+++**[direction]**`
Column header content:: `vaadin-grid-sorter+++<wbr>+++**::part(content)**`
Sort indicators:: `vaadin-grid-sorter+++<wbr>+++**::part(indicators)**`
Sort indicator icons:: `vaadin-grid-sorter+++<wbr>+++**::part(indicators)::before**`
Sort order indicator:: `vaadin-grid-sorter+++<wbr>+++**::part(order)**`


=== Item Details

Item details cell (spans entire row):: `vaadin-grid-pro+++<wbr>+++**::part(details-cell)**`
Cell in row with open details:: `vaadin-grid-pro+++<wbr>+++**::part(details-open-row-cell)**`
Row with open details:: `vaadin-grid-pro+++<wbr>+++**::part(details-open-row)**`


=== Editors

Text field editor:: `vaadin-grid-pro-edit-text-field`
Checkbox editor:: `vaadin-grid-pro-edit-checkbox`
Select editor:: `vaadin-grid-pro-edit-select`

_See <<../text-field/styling#,Text Field>>, <<../select/styling#,Select>> and <<../checkbox/styling#,Checkbox>> selectors for details on styling the editors_
