---
title: Accessibility
order: 60
layout: page
---

= Accessibility
:experimental:

include::../_custom-styles.asciidoc[]

== Introduction
It’s important that we should remember at all times that not everybody reads web pages in the same way.
For this reason, web content needs to be created in a way that is easily understood by screen readers.

== Principles of Accessibility
What does this mean in practice?
Here are a few principles that are worth bearing in mind. +
It will not always be possible to follow them absolutely but, nevertheless, they are good aims.

pass:[<!-- vale Vale.Repetition = NO -->]

In text, spell out, rather than use symbols::
Spell out words like _and_ and _plus_, rather than using symbols such as “&” and “+”.
Screen readers may vary in how they interpret such symbols.

pass:[<!-- vale Vale.Repetition = YES -->]

Do not use text-formatting characters::
Do not use hard carriage returns and tab characters to format sentences and paragraphs.
These may not work as intended when windows are resized or text is enlarged.

Do not describe screen location using direction::
Avoid using terms like _on the left_, _above_ or _below_ to describe the location of something on the screen; these terms are not useful for screen readers.

Use graphics with consideration for all readers::
Graphics can be very useful as a way of conveying information quickly and succinctly.
However, we need to be conscious that not everybody will be able to see graphics clearly or at all.
+
For this reason, we should also employ alternative ways of communicating the information shown in any given graphic.
Take care that a reader can obtain the same information in either way &ndash; text or graphic.


[.discussion-id]
DEDC1C56-6AF0-4971-9217-5666172EA342

