---
title: Starting a Project
layout: page
order: 20
---

= Starting a Project
:wizard-name: Vaadin Start
:toclevels: 2

[.cards.quiet.large.hide-title]
== Vaadin Start

[.breakout]
--
The recommended way to start a new Vaadin project is to use *{wizard-name}*.
It allows you to configure and download a customized starting point for your application.
--

https://start.vaadin.com?preset=fusion[Open {wizard-name}, role="button primary water"]


== Next Steps

Once you have downloaded a starter project and have it extracted in a local folder, you can import it to your favorite IDE (integrated development environment) and start developing it further.

.Ways to create and run a new project
[.subtle]
image::images/newproject-flowchart.svg[New project flowchart, width=100%]

If you create a project outside an IDE, you need to import it in the IDE.
During development, you can run the project with a Maven target, depending on the technology stack you are using.

After you have the project in your IDE, you can go ahead and run or debug it.
