---
title: Styling
page-title: How to style the Notification component | Vaadin components
description: Styling API reference for the Notification component.
meta-description: Style the Vaadin Notification component in your application for a cohesive user experience.
order: 50
---


= Notification Styling

== Style Variants

Notification supports the following style variants.

[cols="1,3,1"]
|===
| Variant | Description | Supported by

|`primary`
|Used for important informational messages or to draw extra attention
|Lumo

|`success`
|Used to display success messages
|Lumo

|`warning`
|Used to display warnings
|Lumo

|`error`
|Used to display errors
|Lumo

|`contrast`
|Used to distinguish the notification from the rest of the UI
|Lumo

|===


=== Success

The `success` variant can be used to display success messages, such as when a task or operation is completed.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/notification/notification-success.ts[render,frame,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/notification/NotificationSuccess.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/notification/react/notification-success.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]

--

Users shouldn't be notified always, or even frequently, of successful operations. Too many notifications can be more distracting than helpful to users. Use success notifications only for operations whose successful completion may otherwise be difficult to discern.


=== Warning

The `warning` variant can be used to display warnings.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/notification/notification-warning.ts[render,frame,tags=snippet,indent=0,group=Lit]

<!-- ... -->

include::{root}/frontend/demo/component/notification/notification-warning.ts[tags=renderer,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/notification/NotificationWarning.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/notification/react/notification-warning.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]

--

Warning notifications should be persistent, and provide the user with a button that closes the notification or allows the user to take appropriate action.



=== Error

The `error` variant can be used to display errors.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/notification/notification-error.ts[render,frame,tags=snippet,indent=0,group=Lit]

<!-- ... -->

include::{root}/frontend/demo/component/notification/notification-error.ts[tags=renderer,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/notification/NotificationError.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/notification/react/notification-error.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]

--

Error notifications should be persistent, and provide the user with a button that closes the notification or allows the user to take appropriate action.

Notifications are non-modal and can be ignored. Therefore, they're usually inappropriate for displaying unexpected technical errors that prevent the application from functioning, or situations that require immediate user action. Use instead a modal <<../dialog#, Dialog>> in such situations.

The built-in error message feature, included with input field components, should be used for field-specific input validation errors.


=== Primary

The `primary` variant can be used for important informational messages or to draw extra attention to a notification.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/notification/notification-primary.ts[render,frame,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/notification/NotificationPrimary.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/notification/react/notification-primary.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]

--


=== Contrast

The `contrast` variant can improve legibility and distinguish the notification from the rest of the UI.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/notification/notification-contrast.ts[render,frame,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/notification/NotificationContrast.java[render,frame,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/notification/react/notification-contrast.tsx[render,frame,tags=snippet,indent=0,group=React]
----
endif::[]

--



include::../_styling-section-theming-props.adoc[tag=style-properties]

==== Notification Card Properties

The following properties apply to the `vaadin-notification-card` element:

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-notification-background`
|Aura

|`--vaadin-notification-border-color`
|Aura

|`--vaadin-notification-border-radius`
|Aura

|`--vaadin-notification-border-width`
|Aura

|`--vaadin-notification-padding`
|Aura

|`--vaadin-notification-shadow`
|Aura

|`--vaadin-notification-width`
|Aura

|===

==== Notification Container Properties

The following properties apply to the `vaadin-notification-container` element:

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-notification-container-gap`
|Aura

|`--vaadin-notification-viewport-inset`
|Aura

|===

include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-notification-card`


=== Parts

Notification card:: `vaadin-notification-card+++<wbr>+++**::part(overlay)**`
Content wrapper:: `vaadin-notification-card+++<wbr>+++**::part(content)**`
