---
title: Configuration
page-title: How to configure Hilla applications
description: Customizing a Hilla application configuration for both the development environment and for execution.
meta-description: Explore configuration options for Hilla applications to optimize performance.
---
:hilla-react:
include::{root}/articles/hilla/lit/reference/configuration.adoc[tag=content]


== Core & Pro Vaadin React Components

Vaadin React components include free, core components and commercial (i.e., professional) components. They're shipped in separate npm packages: `@vaadin/react-components`, which is only free; and `@vaadin/react-components-pro`, which is only commercial. Vaadin adds both of these packages to [filename]`package.json` if `com.vaadin:vaadin` artifact is in the project's configuration:

[source,xml]
.pom.xml
----
<dependency>
	<groupId>com.vaadin</groupId>
	<artifactId>vaadin</artifactId>
</dependency>
----

It adds only `@vaadin/react-components` if `com.vaadin:vaadin-core` is used:

[source,xml]
.pom.xml
----
<dependency>
	<groupId>com.vaadin</groupId>
	<artifactId>vaadin-core</artifactId>
</dependency>
----

== Enable React 19

Hilla uses by default React 18, but is tested against both React 18 and 19. Thus you can enable React 19 using feature flag. 

Edit the [filename]`src/main/resources/vaadin-featureflags.properties` file in your application folder, to enable the feature flag.

.`vaadin-featureflags.properties`
[source,properties]
----
com.vaadin.experimental.react19=true
----
