---
title: Database
page-title: How to manage databases in Vaadin Control Center
description: Provision a database for your Vaadin application and manage migrations and backups.
meta-description: Learn how to configure a database for Vaadin applications in Vaadin Control Center.
order: 70
---

= [since:com.vaadin:vaadin@V24.8]#Database#

Control Center provides a simple way to provision a database for your Vaadin application. It also allows you to manage database migrations and backups. These features allow you to easily set up and maintain a database for your application, ensuring that your data is always safe and up to date.

== Provisioning a Database

You can enable the Database feature either during the deployment of your application or for an application that is already deployed. When enabled, Control Center automatically provisions a dedicated PostgreSQL database exclusively for that application. If your application is configured to use a Spring datasource, the necessary connection details are set up automatically.


== Database Migrations

A database migration is a process that manages incremental, reversible changes to a database schema over time. Migrations allow you to evolve your database structure safely and predictably, ensuring that your application and its data remain consistent as requirements change.

Control Center integrates with Flyway for managing database migrations. For more information about how to use Flyway migrations with Control Center, see the <<./flyway-migrations#,Flyway Migrations>> page.
