---
title: Styling
order: 50
---
= Styling

include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-multi-select-combo-box`


=== States

Required:: `vaadin-multi-select-combo-box+++<wbr>+++**[required]**`
Focused:: `vaadin-multi-select-combo-box+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-multi-select-combo-box+++<wbr>+++**[focus-ring]**`
Read-only:: `vaadin-multi-select-combo-box+++<wbr>+++**[readonly]**`
Disabled:: `vaadin-multi-select-combo-box+++<wbr>+++**[disabled]**`
Not empty:: `vaadin-multi-select-combo-box+++<wbr>+++**[has-value]**`
With open overlay:: `vaadin-multi-select-combo-box+++<wbr>+++**[opened]**`
Hovered:: `vaadin-multi-select-combo-box+++<wbr>+++**:hover**`


=== Field

Field surface (background, border):: `vaadin-multi-select-combo-box+++<wbr>+++**::part(input-field)**`
Native input element:: `vaadin-multi-select-combo-box+++<wbr>+++** > input**`
Input field with placeholder shown:: `vaadin-multi-select-combo-box+++<wbr>+++** > input:placeholder-shown**`
Toggle Button:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(toggle-button)**`
Clear button:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(clear-button)**`
Clear button icon:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(clear-button)::before**`
Prefix element:: `vaadin-multi-select-combo-box+++<wbr>+++** > [slot="prefix"]**`
Suffix element:: `vaadin-multi-select-combo-box+++<wbr>+++** > [slot="suffix"]**`


=== Label

Field with label:: `vaadin-multi-select-combo-box+++<wbr>+++**[has-label]**`
Label:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(label)**`
Label text:: `vaadin-multi-select-combo-box+++<wbr>+++** > label**`
Required indicator:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(required-indicator)**`


=== Helper and Validation Error

Field with helper:: `vaadin-multi-select-combo-box+++<wbr>+++**[has-helper]**`
Helper:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(helper-text)**`
Helper text:: `vaadin-multi-select-combo-box+++<wbr>+++** > [slot="helper"]**`
Invalid field:: `vaadin-multi-select-combo-box+++<wbr>+++**[invalid]**`
Error message:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(error-message)**`
Error message text:: `vaadin-multi-select-combo-box+++<wbr>+++** > [slot="error-message"]**`


=== Chips

Chip element:: `vaadin-multi-select-combo-box-chip`
Focused chip:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**[focused]**`
Hovered chip:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**:hover**`
Chip label:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**::part(label)**`
Chip remove button:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**::part(remove-button)**`
Chip remove button icon:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**::part(remove-button)::before**`
Overflow Chip:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**[slot="overflow"]**`
Overflow-chip with 2 items:: `vaadin-multi-select-combo-box-chip+++<wbr>+++**[count="2"]**`
Chip container inside field:: `vaadin-multi-select-combo-box+++<wbr>+++**::part(chips)**`


=== Overlay

Overlay element:: `vaadin-multi-select-combo-box-overlay`
Overlay background:: `vaadin-multi-select-combo-box-overlay+++<wbr>+++**::part(overlay)**`
Overlay content wrapper:: `vaadin-multi-select-combo-box-overlay+++<wbr>+++**::part(content)**`
Overlay in loading state:: `vaadin-multi-select-combo-box-overlay+++<wbr>+++**[loading]**`
Overlay loading indicator:: `vaadin-multi-select-combo-box-overlay+++<wbr>+++**::part(loader)**`


=== Items

Item element:: `vaadin-multi-select-combo-box-item`
Selected item:: `vaadin-multi-select-combo-box-item+++<wbr>+++**[selected]**`
Item selection indicator:: `vaadin-multi-select-combo-box-item+++<wbr>+++**::part(checkmark)**`
Item selection indicator icon:: `vaadin-multi-select-combo-box-item+++<wbr>+++**::part(checkmark)::before**`
Focused item:: `vaadin-multi-select-combo-box-item+++<wbr>+++**[focused]**`
Item content wrapper:: `vaadin-multi-select-combo-box-item+++<wbr>+++**::part(content)**`
Hovered item:: `vaadin-multi-select-combo-box-item+++<wbr>+++**:hover**`
