---
title: Horizontal Layout
page-title: Horizontal Layout component | Vaadin components
description: Horizontal Layout places components side-by-side in a row.
meta-description: Learn how to use Vaadin Horizontal Layout component to arrange components side by side. Explore customization options, styling tips, and practical examples.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/horizontal-layout}/#/elements/vaadin-horizontal-layout[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/orderedlayout/HorizontalLayout.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/horizontal-layout}/packages/horizontal-layout[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-ordered-layout-flow-parent[Java]'
---


= Horizontal Layout

// tag::description[]
Horizontal Layout places components side-by-side in a row.
// end::description[]
By default, it defines its width and height automatically, determined by the components it contains (i.e., it “hugs” the content).

See <<../vertical-layout#, Vertical Layout>> for placing components top-to-bottom.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayout.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

Components in a Horizontal Layout can be aligned horizontally, as you'd expect, but also vertically.



== Vertical Alignment

You can position components at the top, middle, or bottom. You can also stretch items or position them along the text baseline in the layout.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-vertical-alignment.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutVerticalAlignment.java[render,tags=layout,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-vertical-alignment.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--
|===
|Value |Description

|`STRETCH` (default)
|Vertically stretches items that have undefined height.

|`START`
|Positions items at the top of the layout.

|`CENTER`
|Centers items, vertically.

|`END`
|Positions items at the bottom of the layout.

|`BASELINE`
|Positions items along the layout's text baseline.
|===

It's also possible to set a different vertical alignment for individual items by overriding the general alignment setting of the layout.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-individual-alignment.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutIndividualAlignment.java[render,tags=layout,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-individual-alignment.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Horizontal Alignment

Components in a Horizontal Layout can be left-aligned, centered or right-aligned. You can also position components by specifying how the excess space in a layout is distributed among them.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-horizontal-alignment.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutHorizontalAlignment.java[render,tags=layout,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-horizontal-alignment.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--
|===
|Value |Description

|`START` (default)
|Left-aligns for left-to-right language items. For right-to-left languages, right-aligns items.

|`CENTER`
|Centers items, horizontally.

|`END`
|Right-aligns for left-to-right language items. For right-to-left languages, left-aligns items.

|`BETWEEN`
|Available space is distributed evenly between items. No space is added before the first item, or after the last.

|`AROUND`
|Available space is distributed evenly around items. The space before the first item and after the last, is half of that between items.

|`EVENLY`
|Available space is distributed evenly between items. The space before the first item, between items, and after the last item is the same.
|===


== Spacing

Spacing is used to create space among components in the same layout. Spacing can help prevent misclicks and distinguish content areas.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-spacing.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutSpacing.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-spacing.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

Five different spacing theme variants are available:

[.example.render-only]
--

[source,typescript,role=render-only]
----
include::{root}/frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-spacing-variants.ts[render,tags=snippet,indent=0]
----

--

|===
|Theme Variant |Usage Recommendation

|`spacing-xs`
|Extra-small space between items.

|`spacing-s`
|Small space between items.

|`spacing`
|Medium space between items.

|`spacing-l`
|Large space between items.

|`spacing-xl`
|Extra-large space between items.
|===

[.example]
--
ifdef::lit[]
[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-horizontal-layout
  theme="spacing-xs padding">
</vaadin-horizontal-layout>
----
endif::[]

ifdef::flow[]
[source,java]
----
<source-info group="Flow"></source-info>
HorizontalLayout layout = new HorizontalLayout();
layout.setSpacing(false);
layout.getThemeList().add("spacing-xs");
----
endif::[]

ifdef::react[]
[source,tsx]
----
<source-info group="React"></source-info>
<HorizontalLayout
  theme="spacing-xs padding">
</HorizontalLayout>
----
endif::[]

--


== Padding

Padding is the space between the outer border and the content in a layout. Padding can help distinguish the content in a layout from its surrounding. Padding is applied using the padding theme variant.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-padding.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutPadding.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-padding.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Margin

Use margin to create space around a layout.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-margin.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutMargin.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-margin.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

[role="since:com.vaadin:vaadin@V24.6"]
== Wrapping

By default, components in a layout either shrink or overflow when there isn't enough horizontal space. Enable wrapping to allow components to flow onto a new line when space runs out, preventing overflow.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-wrapping.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutWrapping.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-wrapping.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Expanding Items

Components can be made to expand and take up any excess space a layout may have.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/basiclayouts/basic-layouts-expanding-items.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsExpandingItems.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/basiclayouts/react/basic-layouts-expanding-items.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

When multiple components expand, they do so relative to each other. For example, having two items with expand ratios of 2 and 1 results in the first item taking up twice as much of the available space as the second item.

== Troubleshooting Layouts

=== Avoid Using Full Width Children

Configuring layout children to use the full width, for example when using `HasSize.setWidthFull` or setting the `width` CSS style to `100%`, is problematic due to how the underlying CSS Flexbox model used by Horizontal Layout works. A width of `100%` means "Use the full width of the layout container" and not "Take up the remaining space after reserving space for all other children". This can result in the following issues:

* Other layout children that have an explicit width, for example `200px`, may end up being smaller than that. Children are allowed to shrink by default, and the layout tries to reserve as much space as possible for the child that uses the full width.
* The child that uses the full width may end up overflowing its container. A child is not allowed to shrink below the size of its contents by default, so if the contents of the child are larger than the remaining space in the container it results in overflow. This is the case even if the child itself would have its `overflow` CSS style properly set to show scrollbars.

If you want to make a child use up the remaining width, use the following styles instead:

[.example]
--
ifdef::lit[]
[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-horizontal-layout>
  <!-- Fixed size child, not allowed to shrink -->
  <div style="width: 200px; flex: 0 0 auto;"></div>
  <!-- Child taking up the remaining space by allowing it to grow and shrink -->
  <!-- Also reduce minimum width to be able to shrink below the size of its contents -->
  <div style="flex: 1; min-width: 0;"></div>
</vaadin-horizontal-layout>
----
endif::[]

ifdef::flow[]
[source,java]
----
<source-info group="Flow"></source-info>
// Fixed size child, not allowed to shrink
child1.getStyle()
        .setWidth("200px")
        .setFlexGrow("0 0 auto");

// Child taking up the remaining space by allowing it to grow and shrink
// Also reduce minimum width to be able to shrink below the size of its contents
child2.getStyle()
        .setFlexGrow("1")
        .setMinWidth("0");
----
endif::[]

ifdef::react[]
[source,tsx]
----
<source-info group="React"></source-info>
<HorizontalLayout>
  { /* Fixed size child, not allowed to shrink */ }
  <div style={{ width: '200px', flex: '0 0 auto' }} />
  { /* Child taking up the remaining space by allowing it to grow and shrink */ }
  { /* Also reduce minimum width to be able to shrink below the size of its contents */ }
  <div style={{ flex: '1', minWidth: '0' }} />
</HorizontalLayout>
----
endif::[]

--

.[since:com.vaadin:vaadin@V24.7]#Layout Improvements for Flow's HasSize API#
[NOTE]
Specifically for the Flow `HasSize.setWidthFull` and `HasSize.setSizeFull` APIs, the respective `flex` and `min-width` styles are applied automatically when adding the component as a child of Horizontal Layout. Currently, this behavior is opt-in, and you must enable the `layoutComponentImprovements` feature flag to use it. See <<{articles}/flow/configuration/feature-flags#,Feature Flags>> for more information.


[discussion-id]`61c42eee-d39a-11ed-afa1-0242ac120002`
