---
title: Horizontal Layout
page-title: Horizontal Layout component | Vaadin components
description: Horizontal Layout places components side-by-side in a row.
meta-description: Learn how to use Vaadin Horizontal Layout component to arrange components side by side. Explore customization options, styling tips, and practical examples.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/horizontal-layout}/#/elements/vaadin-horizontal-layout[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/orderedlayout/HorizontalLayout.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/horizontal-layout}/packages/horizontal-layout[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-ordered-layout-flow-parent[Java]'
---


= Horizontal Layout

// tag::description[]
Horizontal Layout places components side-by-side in a row.
// end::description[]
By default, it defines its width and height automatically, determined by the components it contains (i.e., it “hugs” the content).

See <<../vertical-layout#, Vertical Layout>> for placing components top-to-bottom.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-basic.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutBasic.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

Components in a Horizontal Layout can be aligned horizontally, as you'd expect, but also vertically.



== Vertical Alignment

You can position components at the top, middle, or bottom. You can also stretch items or position them along the text baseline in the layout.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-vertical-alignment.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutVerticalAlignment.java[render,tags=layout,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-vertical-alignment.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--
|===
|Value |Description

|`STRETCH` (default)
|Vertically stretches items that have undefined height.

|`START`
|Positions items at the top of the layout.

|`CENTER`
|Centers items, vertically.

|`END`
|Positions items at the bottom of the layout.

|`BASELINE`
|Positions items along the layout's text baseline.
|===

It's also possible to set a different vertical alignment for individual items by overriding the general alignment setting of the layout.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-individual-alignment.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutIndividualAlignment.java[render,tags=layout,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-individual-alignment.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Horizontal Alignment

There are two ways to align items horizontally: _individual alignment_ of items, and _justification_. These two methods cannot be used simultaneously.


[role="since:com.vaadin:vaadin@V24.7"]
=== Aligning Individual Items

Each item in the layout can be grouped to the start, center and end of the layout.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-slots.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutSlots.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-slots.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Justification

Justification modes determine how items in the layout are distributed within the available space. Six justification modes are available:

|===
|Value |Description

|`START` (default)
|Left-aligns for left-to-right language items. For right-to-left languages, right-aligns items.

|`CENTER`
|Centers items, horizontally.

|`END`
|Right-aligns for left-to-right language items. For right-to-left languages, left-aligns items.

|`BETWEEN`
|Available space is distributed evenly between items. No space is added before the first item, or after the last.

|`AROUND`
|Available space is distributed evenly around items. The space before the first item and after the last, is half of that between items.

|`EVENLY`
|Available space is distributed evenly between items. The space before the first item, between items, and after the last item is the same.
|===


[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-horizontal-alignment.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutHorizontalAlignment.java[render,tags=layout,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-horizontal-alignment.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Spacing

Spacing is used to create space among components in the same layout. Spacing can help prevent misclicks and distinguish content areas.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-spacing.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutSpacing.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-spacing.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

Five different spacing theme variants are available:

[.example.render-only]
--

[source,typescript,role=render-only]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-spacing-variants.ts[render,tags=snippet,indent=0]
----

--

|===
|Theme Variant |Usage Recommendation

|`spacing-xs`
|Extra-small space between items.

|`spacing-s`
|Small space between items.

|`spacing`
|Medium space between items.

|`spacing-l`
|Large space between items.

|`spacing-xl`
|Extra-large space between items.
|===

[.example]
--
ifdef::lit[]
[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-horizontal-layout
  theme="spacing-xs padding">
</vaadin-horizontal-layout>
----
endif::[]

ifdef::flow[]
[source,java]
----
<source-info group="Flow"></source-info>
HorizontalLayout layout = new HorizontalLayout();
layout.setSpacing(false);
layout.getThemeList().add("spacing-xs");
----
endif::[]

ifdef::react[]
[source,tsx]
----
<source-info group="React"></source-info>
<HorizontalLayout
  theme="spacing-xs padding">
</HorizontalLayout>
----
endif::[]

--

[since:com.vaadin:vaadin@V24.7]#Alternatively, the spacing can be set to a custom value:#

[.example]
--
ifdef::lit[]
[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-horizontal-layout style="gap: 12px">
</vaadin-horizontal-layout>
----
endif::[]

ifdef::flow[]
[source,java]
----
<source-info group="Flow"></source-info>
HorizontalLayout layout = new HorizontalLayout();
layout.setSpacing(12, Unit.PIXELS);
----
endif::[]

ifdef::react[]
[source,tsx]
----
<source-info group="React"></source-info>
<HorizontalLayout style={{ gap: '12px' }}>
</HorizontalLayout>
----
endif::[]

--

== Padding

Padding is the space between the outer border and the content in a layout. Padding can help distinguish the content in a layout from its surrounding. Padding is applied using the padding theme variant.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-padding.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutPadding.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-padding.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Margin

Use margin to create space around a layout.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-margin.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutMargin.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-margin.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

[role="since:com.vaadin:vaadin@V24.6"]
== Wrapping

By default, components in a layout either shrink or overflow when there isn't enough horizontal space. Enable wrapping to allow components to flow onto a new line when space runs out, preventing overflow.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-wrapping.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutWrapping.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-wrapping.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Wrapping Horizontally Aligned Items

Wrapping may not behave as desired when combined with either of the two <<#horizontal-alignment,horizontal alignment>> methods. One common solution is group items that should wrap together into sub-layouts:

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-slots-wrapping.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutSlotsWrapping.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-slots-wrapping.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Expanding Items

Components can be made to expand and take up any excess space a layout may have.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-expanding-items.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutExpandingItems.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-expanding-items.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

When multiple components expand, they do so relative to each other. For example, having two items with expand ratios of 2 and 1 results in the first item taking up twice as much of the available space as the second item.

:horizontal-layout: true
include::./_troubleshooting.adoc[]

[discussion-id]`61c42eee-d39a-11ed-afa1-0242ac120002`
