---
title: Styling
page-title: How to style the Horizontal Layout | Vaadin components
description: Styling API reference for the Horizontal Layout component.
meta-description: Customize the Horizontal Layout component to align with your application’s theme and branding.
order: 50
---
= Horizontal Layout Styling

== Style Variants

Horizontal Layout supports the following style variants:

[cols="1,1"]
|===
| Variant | Supported by

|`margin`
|Aura, Lumo

|`padding`
|Aura, Lumo

|`spacing`
|Aura, Lumo

|`wrap`
|Aura, Lumo

|===

=== Spacing

Spacing is used to create space among components in the same layout. Spacing can help prevent misclicks and distinguish content areas.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-spacing.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutSpacing.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-spacing.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

Five different spacing theme variants are available:

[.example.render-only]
--

[source,typescript,role=render-only]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-spacing-variants.ts[render,tags=snippet,indent=0]
----

--

|===
|Theme Variant |Usage Recommendation

|`spacing-xs`
|Extra-small space between items.

|`spacing-s`
|Small space between items.

|`spacing`
|Medium space between items.

|`spacing-l`
|Large space between items.

|`spacing-xl`
|Extra-large space between items.
|===

[.example]
--
ifdef::lit[]
[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-horizontal-layout
  theme="spacing-xs padding">
</vaadin-horizontal-layout>
----
endif::[]

ifdef::flow[]
[source,java]
----
<source-info group="Flow"></source-info>
HorizontalLayout layout = new HorizontalLayout();
layout.setSpacing(false);
layout.getThemeList().add("spacing-xs");
----
endif::[]

ifdef::react[]
[source,tsx]
----
<source-info group="React"></source-info>
<HorizontalLayout
  theme="spacing-xs padding">
</HorizontalLayout>
----
endif::[]

--

Alternatively, the spacing can be set to a custom value:

[.example]
--
ifdef::lit[]
[source,html]
----
<source-info group="Lit"></source-info>
<vaadin-horizontal-layout style="gap: 12px">
</vaadin-horizontal-layout>
----
endif::[]

ifdef::flow[]
[source,java]
----
<source-info group="Flow"></source-info>
HorizontalLayout layout = new HorizontalLayout();
layout.setSpacing(12, Unit.PIXELS);
----
endif::[]

ifdef::react[]
[source,tsx]
----
<source-info group="React"></source-info>
<HorizontalLayout style={{ gap: '12px' }}>
</HorizontalLayout>
----
endif::[]

--

=== Padding

Padding is the space between the outer border and the content in a layout. Padding can help distinguish the content in a layout from its surrounding. Padding is applied using the padding theme variant.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-padding.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutPadding.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-padding.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Margin

Use margin to create space around a layout.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-margin.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutMargin.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-margin.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

=== Wrapping

By default, components in a layout either shrink or overflow when there isn't enough horizontal space. Enable wrapping to allow components to flow onto a new line when space runs out, preventing overflow.

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-wrapping.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutWrapping.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-wrapping.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Wrapping Horizontally Aligned Items

Wrapping may not behave as desired when combined with either of the two <<#horizontal-alignment,horizontal alignment>> methods. One common solution is group items that should wrap together into sub-layouts:

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/horizontal-layout/horizontal-layout-slots-wrapping.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutSlotsWrapping.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/horizontal-layout/react/horizontal-layout-slots-wrapping.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


include::../_styling-section-theming-props.adoc[tag=style-properties]

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-horizontal-layout-gap`
|Aura, Lumo

|`--vaadin-horizontal-layout-padding`
|Aura, Lumo

|`--vaadin-horizontal-layout-margin`
|Aura, Lumo

|===

include::../_styling-section-intros.adoc[tag=selectors]

Root element:: `vaadin-horizontal-layout`