---
title: Flow components in Hilla view
description: Embedding Custom Flow components in Hilla views.
order: 500
---


= Custom Flow Components in Hilla

Custom Flow components can be embedded in a Hilla view by implementing a [classname]`WebComponentExporter` and using it in the view. A [classname]`WebComponentExporter` can target any Flow Component. 

Below is an example for a component that follows:

[source,java]
----
public class CustomComponent extends Div {

    public CustomComponent(@Autowired GreetService service) {
        Button button = new Button("Say hello", e -> {
            Notification.show("Hello!");
        });

        add(button);
    }
}
----

This would then be embedded into a [classname]`WebComponent` like so:

[source,java]
----
public class MyFlowComponentExporter
        extends WebComponentExporter<CustomComponent> {

    public static final String TAG = "my-flow-component";

    public MyFlowComponentExporter() {
        super(TAG);
    }

    @Override
    protected void configureInstance(WebComponent<CustomComponent> webComponent,
                                     CustomComponent component) {
    }
}
----

For more information, see <<{articles}/flow/integrations/embedding/exporter,Creating an Embedded Vaadin Application>>.

[NOTE]
The [classname]`WebComponentExporter` needs to have a public no-argument constructor. Otherwise, it won't be instantiated or generated.

To add the exported [classname]`WebComponent` to a Hilla view, import `createWebComponent` from Flow and create a `React.DOMElement` for the [classname]`WebComponent` `TAG`. Then use the element inside the view layout like this:

[source,typescriptjsx]
----
import { VerticalLayout } from "@vaadin/react-components/VerticalLayout";
import { createWebComponent } from "Frontend/generated/flow/Flow";

function MyFlowComponent() {
  return createWebComponent("my-flow-component");
}

export default function HillaView() {
  return (
    <>
      <VerticalLayout className={'centered-content'}>
        <h3>Hilla View</h3>
        <MyFlowComponent/>
      </VerticalLayout>
    </>
  );
}
----

=== Using Attributes

Adding attributes for the element can be done by giving a [interface]`Properties` object with `string` value pairs to the [method]`createWebComponent`.
The [interface]`Properties` is defined as `[key: string]: string;`.

This can be used when the [classname]`WebComponent` exposes properties to the client.

.Custom Properties for Flow WebComponent
[source,typescriptjsx]
----
import { VerticalLayout } from "@vaadin/react-components/VerticalLayout";
import { createWebComponent } from "Frontend/generated/flow/Flow";
import React from "react";

function MyFlowComponent() {
  // Create element with property hellomsg
  return createWebComponent("my-flow-component", {
    hellomsg: 'Hi from the client!'
  });
}

export default function HillaView() {
  return (
    <>
      <VerticalLayout className={'centered-content'}>
        <h3>Hilla View</h3>
        <MyFlowComponent/>
      </VerticalLayout>
    </>
  );
}
----

The properties can also be linked to the element attributes using a custom properties type:

.Custom Properties With Attribute Link
[source,typescriptjsx]
----
import { VerticalLayout } from "@vaadin/react-components/VerticalLayout";
import { createWebComponent } from "Frontend/generated/flow/Flow";
import React from "react";

type MyProperties = {
  hellomsg: string
}

function MyFlowComponent(props: MyProperties) {
  // Create element with property hellomsg
  return createWebComponent("my-flow-component", {
    hellomsg: props.hellomsg
  });
}

export default function HillaView() {
  return (
    <>
      <VerticalLayout className={'centered-content'}>
        <h3>Hilla View</h3>
        <MyFlowComponent hellomsg={'Hi from the client!'}/>
      </VerticalLayout>
    </>
  );
}
----

This way the changing of the attribute will also update the [classname]`WebComponent` property value.

The corresponding server-side code for the attribute component is made as following sample shows.

.WebComponent with Exposed Properties
[source,java]
----
public class MyFlowComponentExporter
        extends WebComponentExporter<CustomComponent> {

    public static final String TAG = "my-flow-component";

    public MyFlowComponentExporter() {
        super(TAG);
        addProperty("hellomsg", "Hello!")
            .onChange(CustomComponent::setHelloMessage);
    }

    @Override
    protected void configureInstance(WebComponent<CustomComponent> webComponent,
                                     CustomComponent component) {
    }
}
----

.Flow Component with Property
[source,java]
----
public class CustomComponent extends Div {
    String helloMessage;

    public CustomComponent(@Autowired GreetService service) {
        Button button = new Button("Say hello", e -> {
            Notification.show(helloMessage);
        });

        add(button);
    }

    public void setHelloMessage(String helloMessage) {
        this.helloMessage = helloMessage;

    }
}
----

=== Onload Event For WebComponent

It is possible to listen to the `onload` event for the [classname]`WebComponent` script by giving a callback to the [methodname]`createWebComponent` as the 3rd parameter.

[source,typescriptjsx]
----
import { VerticalLayout } from "@vaadin/react-components/VerticalLayout";
import { createWebComponent } from "Frontend/generated/flow/Flow";
import React from "react";

type MyProperties = {
  hellomsg: string
}

function MyFlowComponent(props: MyProperties) {
  // Create element with property hellomsg
  return createWebComponent("my-flow-component",
          undefined,
          () => {
            console.log("Component script loaded!");
          });
}

export default function HillaView() {
  return (
    <>
      <VerticalLayout className={'centered-content'}>
        <h3>Hilla View</h3>
        <MyFlowComponent hellomsg={'Hi from the client!'}/>
      </VerticalLayout>
    </>
  );
}
----

[discussion-id]`920dc03d-5eb4-4826-8934-4416b58a9a3e`

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++