---
title: Flow components in Hilla view
order: 500
---

= Use Custom Flow Components In Hilla

Custom Flow components can be embedded into Hilla views by implementing a [classname]`WebComponentExporter` and using it in the view.

A [classname]`WebComponentExporter` can target any Flow Component, for instance the following component:

[source,java]
----
public class CustomComponent extends Div {

    public CustomComponent(@Autowired GreetService service) {
        Button button = new Button("Say hello", e -> {
            Notification.show("Hello!");
        });

        add(button);
    }
}
----

would be made into a [classname]`WebComponent` like:

[source,java]
----
public class MyFlowComponentExporter
        extends WebComponentExporter<CustomComponent> {

    public static final String TAG = "my-flow-component";

    public MyFlowComponentExporter() {
        super(TAG);
    }

    @Override
    protected void configureInstance(WebComponent<CustomComponent> webComponent,
                                     CustomComponent component) {
    }
}
----

For more information see <<{articles}/flow/integrations/embedding/exporter,Creating an Embedded Vaadin Application>>

To add the exported [classname]`WebComponent` to a Hilla view import `createWebComponent` from Flow and create a React.DOMElement for the [classname]`WebComponent` `TAG` and then use the element inside the view layout.

[source,typescriptjsx]
----
import { VerticalLayout } from "@vaadin/react-components/VerticalLayout";
import { createWebComponent } from "Frontend/generated/flow/Flow";

function MyFlowComponent() {
  return createWebComponent("my-flow-component");
}

export default function HillaView() {
  return (
    <>
      <VerticalLayout className={'centered-content'}>
        <h3>Hilla View</h3>
        <MyFlowComponent/>
      </VerticalLayout>
    </>
  );
}
----

If the component needs attributes or other custom parts in `React.createElement` then instead of importing `createWebComponent` import `loadComponentScript` and create the element in the function.

This can be needed for instance when the [classname]`WebComponent` exposes properties to the client.

.Custom Properties For Flow WebComponent
[source,typescriptjsx]
----
import { VerticalLayout } from "@vaadin/react-components/VerticalLayout";
import { loadComponentScript } from "Frontend/generated/flow/Flow";
import React from "react";

function MyFlowComponent() {
  loadComponentScript("my-flow-component");
  // Create element with property hellomsg
  return React.createElement("my-flow-component", {
    hellomsg: 'Hi from the client!'
  });
}

export default function HillaView() {
  return (
    <>
      <VerticalLayout className={'centered-content'}>
        <h3>Hilla View</h3>
        <MyFlowComponent/>
      </VerticalLayout>
    </>
  );
}
----

.WebComponent With Exposed Properties
[source,java]
----
public class MyFlowComponentExporter
        extends WebComponentExporter<CustomComponent> {

    public static final String TAG = "my-flow-component";

    public MyFlowComponentExporter() {
        super(TAG);
        addProperty("hellomsg", "Hello!")
            .onChange(CustomComponent::setHelloMessage);
    }

    @Override
    protected void configureInstance(WebComponent<CustomComponent> webComponent,
                                     CustomComponent component) {
    }
}
----

.Flow Component With Property
[source,java]
----
public class CustomComponent extends Div {
    String helloMessage;

    public CustomComponent(@Autowired GreetService service) {
        Button button = new Button("Say hello", e -> {
            Notification.show(helloMessage);
        });

        add(button);
    }

    public void setHelloMessage(String helloMessage) {
        this.helloMessage = helloMessage;

    }
}
----

[discussion-id]`920dc03d-5eb4-4826-8934-4416b58a9a3e`

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++