---
title: IntelliJ IDEA Editor Settings
order: 10
layout: page
---

:experimental:
:commandkey: &#8984;

= IntelliJ IDEA Editor Settings

This page describes the noticeable changes made to the default code formatting settings in Intellij IDEA. This is also a chance to review some of these changes to validate or tweak them if necessary. 
None of these is essential for a pull request, but they will all help. They can also be added after the original pull request but before a merge.

== General

- Line length is 80 characters
- Use spaces instead of tabs for indentation
- Use UTF-8 encoding
- Use unix-style line endings (`\n`)

== Code Conventions

. Install the _Eclipse Code Formatter_ plugin, then restart IDEA
. Open Settings (kbd:[Ctrl + Alt + S] or kbd:[{commandkey} + ,])
. On the menu:Other Settings[Eclipse Code Formatter] page
.. Check _Use the Eclipse code formatter_
.. In the _Supported file types_ section, check _Enable Java_
.. In _Eclipse Java Formatter config file_, browse to your local copy of link:https://github.com/vaadin/flow/blob/master/eclipse/VaadinJavaConventions.xml[VaadinJavaConventions.xml]
. Go to menu:Editor[Code Style], and set _Hard wrap at (columns)_ to *80*

== Imports

. Open Settings (kbd:[Ctrl + Alt + S] or kbd:[{commandkey} + ,])
. Go to menu:Editor[General > Auto Import] and uncheck _Optimize imports on the fly_
. Go to menu:Editor[Code Style > Java] and on the _Imports_ tab
.. Make sure that _Use single class import_ is checked
.. Set both _Class count to use import with ‘+++*+++’_ and _Names count to use static import with ‘+++*+++’_ to *99*
.. On the _Import Layout_ pane, make sure that _Layout static imports separately_ is checked
.. Remove all the packages in the list _Packages to Use Import with ‘+++*+++’_
.. Organize Java imports to comply to the convention defined below:
+
[source,java]
----
import javax.*
import java.*
<blank line>
import all other imports
<blank line>
import com.google.gwt.*
import com.vaadin.*
<blank line>
import elemental.*
import static all other imports
----

== Copyright

. Open Settings (kbd:[Ctrl + Alt + S] or kbd:[{commandkey} + ,])
. Go to menu:Editor[Copyright > Copyright Profiles] and create a new profile named *Vaadin*, with the copyright text as defined below:
+
----
Copyright 2000-$today.year Vaadin Ltd.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
----

. Go one level higher, to menu:Editor[Copyright], and set _Default project copyright_ to the *Vaadin* profile you just created