---
title: Eclipse Editor Settings
order: 20
layout: page
---

:experimental:
:commandkey: &#8984;

= Eclipse Editor Settings

This page describes the noticeable changes made to the default code formatting settings in Eclipse. 
This is also a chance to review some of these changes to validate or tweak them if necessary. 
None of these is essential for a pull request, but they will all help. 
They can also be added after the original pull request but before a merge.

== General

- Line length is 80 characters
- Use spaces instead of tabs for indentation
- Use UTF-8 encoding
- Use unix-style line endings (`\n`)

== Code Conventions

. Open menu:Window[Preferences] (Windows) or menu:Eclipse[Preferences] (Mac)
. On the menu:Java[Code Style > Formatter] page, import your local copy of link:https://github.com/vaadin/flow/blob/master/eclipse/VaadinJavaConventions.xml[VaadinJavaConventions.xml]
. On the menu:Java[Code Style > Organize Imports] page, import your local copy of link:https://github.com/vaadin/flow/blob/master/eclipse/flow.importorder[flow.importorder]
. On the menu:Editor[Save Actions] tab, make sure that in case [guilabel]#Format source code# is active, the [guilabel]#Format edited lines option# is selected. 
Never use the [guilabel]#Format all lines# option, as that may introduce loads of unnecessary code changes, making code reviews a nightmare!
. Go to menu:General[Workspace]
.. Set [guilabel]#Text file encoding# to *UTF-8*
.. Set [guilabel]#New text file line delimiter# to *Unix*
. Go to menu:XML[XML Files > Editor] and ensure the settings are configured as follows:
- [guilabel]#Line width#: *72*
- [guilabel]#Format comments#: *true*
- [guilabel]#Join lines#: *true*
- [guilabel]#Insert whitespace before closing empty end-tags#: *true*
- [guilabel]#Indent using spaces#: *true*
- [guilabel]#Indentation size#: *4*

== Copyright

. Open menu:Window[Preferences] (Windows) or menu:Eclipse[Preferences] (Mac)
. On the menu:Java[Code Style > Code Templates] page, edit the menu:Comments[Files] template to add the copyright text:
+
```
Copyright 2000-${currentDate:date('yyyy')} Vaadin Ltd.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this file except in compliance with the License. You may obtain a copy of
the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
```

