---
title: Style Guide
description: Writing style guidelines for documentation writers.
order: 20
---

= Documentation Style Guide
include::_custom-styles.adoc[]

== Global Audience

Vaadin documentation is provided in English for the benefit of users all around the world. For many of these users, though, English isn't their native language. For this reason, you'll need to write in a style that's as clear and as accessible as possible. The following principles can help you to achieve this goal.

.Use Short, Simple Sentences
[%collapsible]
====
Consider this example:

[example]
=====
Vaadin components do support client-side validation to increase the responsiveness of the application, but the developer should be aware that these should be used purely for convenience, since they can be circumvented in the browser.
=====

This could be made more understandable as follows:

[example]
=====
Vaadin components support client-side validation to increase the responsiveness of the application. However, as a developer, you'd use this only for convenience, as it's easy to circumvent client-side validation in the browser.
=====

Here is another example, but in which longer, more complicated sentences can be reduced to shorter, simpler ones:

[example]
=====
For instance, if the developer sets a component to be disabled, this effect is set both on the server and the client. On the client, an attacker can circumvent this (attackers have full control over anything in the browser), but the server blocks any interaction with the component and a warning is printed to the server logs.
=====

This could be improved as follows:

[example]
=====
For example, if the developer disables a component, it's disabled on both the server and client. An attacker may be able to circumvent this on the client since they have full control over their browser. However, the server blocks any interaction with the disabled component. The server also writes a warning message to the server logs.
=====
====

.Keep the Verb Near the Subject
[%collapsible]
====
Try not to separate the subject from the verb with too many words. This can make a sentence difficult to interpret. Consider the following sentence:

[example]
=====
Data coming from a data store (such as a database) and inserted as HTML into DOM elements (for example, setting innerHTML for elements or using HTML mode in component captions) should also be escaped.
=====

This could be improved as follows:

[example]
=====
If you insert data from a data store into DOM elements as HTML, be sure to escape the data first. This would be necessary, for example, if you were using data from a database to set innerHTML, or using HTML mode in component captions.
=====
====

.Use Only One Verb in a Sentence.
[%collapsible]
====
For simplicity and ease of understanding, it's a good general goal to try to have only one verb in each sentence. However, when there is a strong logical connection between clauses (such as, implied by words like “while”, “when”, “because”, “so”, “since” and “although”), it may be better to use multiple verbs in a sentence. Here's an example of this:

[example]
=====
The request isn't available in background threads, so the `isAuthenticated()` method shows authentication state only in Vaadin request processing threads, otherwise it would always return false.
=====

This could be improved as follows:

[example]
=====
The request isn't available in background threads. Therefore, the `isAuthenticated()` method shows the authentication state only in Vaadin request processing threads. Otherwise, it returns false.
=====
====


== Inclusiveness & Accessibility

In simple terms, _inclusiveness_ means _not excluding_ people on an arbitrary basis. For instance, you wouldn't exclude people or readers based their gender, age, disability, race, religion or sexual orientation.

As much as reasonable, try to _include_ people from a wide range of technical abilities. Although Vaadin's technical documentation is aimed at an audience that has a certain level of technical awareness, you should be careful not to make too many assumptions about an individual reader's knowledge and skill set.

It's important to remember that not everyone reads web pages with the same types of devices and in the same way. For instance, some read the documentatoin on their telephone or on a tablet, while others on a desktop computer. Some tilt hand-held devices sideways, and some use larger fonts to aid their vision.  For this reason, web content needs to be created in a way that's easily viewable by various devices and accessible for screen readers.

// TODO needs examples


== Voice & Tone

_Voice_ refers to how you say things. Likewise, when explaining something, you should adopt an appropriate _tone_.

pass:[<!-- vale Vaadin.We = NO -->]

=== Voice

When you write documentation, there's certain things you'll want to communicate to the reader. But there are many ways you can express that information.

We have certain ways of talking to each other, ways which say plenty about who we are and how we see the world. In our documentation, we want to provide important information as clearly as possible. We would also like people to have a favorable impression of us and what we stand for as an organization.

When you write documentation, you're essentially acting as the public face of the organization. That may sound like a lot of responsibility, but it's not so difficult. We're all able to be friendly and helpful -- and that's all that's required. Write like a someone who cares about the reader -- which you obvously do if you're contributing.

pass:[<!-- vale Vaadin.We = YES -->]

// TODO needs examples

=== Tone

Tone is more about finding the correct balance between being overly formal and rigid, and being too casual. You can take great care to explain issues thoroughly and thoughtfully. However, if you use language that's so formal that the material sounds unapproachable, or so informal that it sounds unreliable, you risk losing the reader.

You should be aiming for a professional, friendly tone.

// TODO needs more examples


[[english]]
== Style of English

The English language originated in England. However, there are many deviations and dialects of English. Given the influence of the United States in the marketplace and with software developers worldwide, we strive to use American English in the documentation. Here are some simple spelling examples:

[example.recommend]
Customize
[example.avoid]
Customise

[example.recommend]
Color
[example.avoid]
Colour


== Cultural References

Be aware that users of the documentation come from many different cultures. Hence, avoid making references that depend on familiarity with any particular culture may lose some readers. For instance, providing examples that require an understanding or familiarity with a specific sport or a regligious ritual might be confusing to some.

// TODO needs examples


== Congratulations
Avoid congratulating the reader, for example, for working through a tutorial and completing the process that the tutorial describes. It sounds patronizing. For example:

pass:[<!-- vale Vaadin.Exclamation = NO -->]
[example.recommend]
You've now completed the tutorial.
[example.avoid]
*Well done!* You've now completed the tutorial successfully.


[[exclamations]]
== Exclamation Mark ("!")
Avoid using exclamation marks in technical documentation, unless it's as part of some code syntax. Its use in normal text is distracting and detracts from the professional tone. For example:

[example.recommend]
You've now created your component.
[example.avoid]
You've now created your component**!**

pass:[<!-- vale Vaadin.Exclamation = YES -->]

One of the problems with this is that if the reader had difficulty with the tutorial or was unsuccessful, they'll be particularly irritated by being congratulated and might feel stupid for having problems.


== Present Tense

In general, use present tense rather than future tense. It tends to give a fresher feel to the text. In particular, try to avoid using the word _will_ where possible. For example:
pass:[<!-- vale Vaadin.Will = NO -->]

[example.recommend]
When the compilation is complete, the program *displays* summary information.
[example.avoid]
When the compilation is complete, the program *will display* summary information.

Sometimes future tense is unavoidable because you're actually talking about the future. Attempting to predict the future in a document is usually a bad idea, but sometimes it's necessary.

However, the fact that the reader will be writing and running code in the future isn't a good reason alone to use future tense. Stay with present tense where possible.

[example.recommend]
Press [guibutton]*OK*. A new dialog *opens*.
[example.avoid]
Press [guibutton]*OK*. A new dialog *will open*.

[example.recommend]
If there is no authenticated user, the method *returns* null.
[example.avoid]
If there is no authenticated user, the method *will return* null.

pass:[<!-- vale Vaadin.Will = YES -->]


pass:[<!-- vale Vale.Repetition = NO -->]

[[symbols]]
== Words over Symbols

In text, spell out words like _and_, _plus_, and _or_, rather than using the symbols “&”, “+”, and "/". Screen readers may vary in how they interpret such symbols. You can, however, use the ampersand character ("&") in headings and titles to make them shorter and easier to scan. In the same way, unless you're referring to values, try not to use numbers.

[example.recommend]
The DOM structure of VerticalLayout *and* HorizontalLayout was developed to maintain the same set of elements and …
[example.avoid]
The DOM structure of VerticalLayout *&* HorizontalLayout.

[example.recommend]
Voice *&* Tone _(in a heading or a title)_
[example.avoid]
The voice *&* tone of the documentation is professional and friendly.

[example.recommend]
The identifier consists of its tag *plus* a running counter.
[example.avoid]
The identifier consists of its tag *+* a running counter.

[example.recommend]
Login as *admin or root* before proceeding.
[example.avoid]
Login as *admin/root* before proceeding.

[example.recommend]
The user is allowed only *3* attempts if the variable is set to a value of *3*.
[example.avoid]
The user is allowed only *three* attempts if the variable is set to a value of *3*.

pass:[<!-- vale Vale.Repetition = YES -->]


== Directional Language

Avoid using terms like _on the left_, _above_ or _below_ to describe the location of something on the screen. These terms aren't useful and can be confusing for screen readers.

[example.recommend]
In the previous example.
[example.avoid]
In the example above.


== Latin Abbreviations

Don't use the Latin abbreviations like "i.e." and "e.g." in the main text of sentences. Instead, write them in English. Using them inside parenthesis is acceptable when you want to clarify the meaning of a sentence without distracting or diverging the reader too much.

[[for-example]]
=== "For Example" (E.g.)
Rather use expression like _such as_, _for example_, or _for instance_.

The phrase _for example_ http://www.myenglishteacher.net/forexample.html[always requires] surrounding commas, while _such as_ may only need a preceding comma when it's used in the beginning of a restrictive clause.

For example:

[example.recommend]
You may find, *for example*, JSF or Flash more suitable for such purposes.
[example.avoid]
You may find, *e.g.*, JSF or Flash more suitable for such purposes.

[example.recommend]
*For example*, consider that you have the following composite class.
[example.avoid]
*E.g.*, consider that you have the following composite class.

[example.recommend]
You may find frameworks *such as* JSF or Flash more suitable for such purposes.

[example.recommend]
Some frameworks, *such as* JSF or Flash, can be more suitable for such purposes.

[example.recommend]
Due to the way overlays *(e.g., Dialog)* are rendered in embedded Flow UIs, the utility classes don't work in them.


[[that-is]]
=== "That Is" (i.e.)
The abbreviation "i.e." means "_that is_" in Latin. When used in the main text of a sentence, don't use the Latin abbreviation. Use the English text instead -- surrounded with commas.

[example.recommend]
The parameter is the class name of the widget set, *that is*, without the extension.
[example.avoid]
The parameter is the class name of the widget set, *i.e.*, without the extension.

The exception to this is when the text is contained within parentheses. Then it's optional as to whether to use the Latin abbreviation or the English equivalent. Remember to follow either with a comma, though.

[example.recommend]
Switches focus between sections of the grid (*i.e.*, header, body, footer).


[[etc]]
=== "And So Forth" (Etc.)
This Latin abbreviation "etc."" in English is basically, "and so on". It's find to use it sometimes. However, it's sometimes better to use expressions such as _and so forth_. If the Latin abbreviation is used, though, it should be preceded by comma and followed by period.

[example.recommend]
You would normally implement some views, *etc*.
[example.recommend]
You would normally implement some views, *and so forth*.

Unlike other Latin abbreviations, this one may be used outside a parenthetical comment, in the main text of a sentence.


== Product Names
Product names, such as _Combo Box_, should be capitalized in the same way as proper nouns. Some product names are the same as some class names. Be careful not to inadvertently use combined, camel-case when referring to the product. When reffering to a class name, camel-case is used, but remember to use monospace formatting. Here are some examples:

pass:[<!-- vale Vaadin.ProductName = NO -->]

[example.recommend]
*Combo Box* allows the user to choose a value from a filterable list of options presented in an overlay.
[example.avoid]
*Combo box* allows the user to choose a value from a filterable list of options presented in an overlay.
[example.avoid]
*ComboBox* allows the user to choose a value from a filterable list of options presented in an overlay.

pass:[<!-- vale Vaadin.ProductName = YES -->]

[example.recommend]
The `ComboBox` class extends the `ComboBoxBase` class.


[[vaadin-versions]]
== Vaadin Version Numbers
Avoid using explicit Vaadin version numbers in text (e.g., _Vaadin 24_). Instead, use something like `[role="since:com.vaadin:vaadin@V24"]` for parts of the documentation that apply starting from a specific version.

[example.recommend]
====
`Using the integrated content areas in *+++[since:com.vaadin:vaadin@V23.3]#Tab Sheet#+++* is the easiest way to switch between the different content for each tab.`
====

[example.avoid]
====
`Using the integrated content areas in Tab Sheet *(available in Vaadin 23.3 and later)* is the easiest way to switch between the different content for each tab.`
====

Try to write the documentation for features with the assumption that they're available for general use in their final form, even if they're still under development or only available in a pre-release. This is more agreeable to readers once a feature is available in a stable release. Otherwise, they'll have to pause and consider if the documentation is relevant for them. Similarly, don't assume the reader is familiar with how things worked in earlier versions of Vaadin; avoid such comparisons.



== Admonitions

Admonition blocks such as `[NOTE]`, `[TIP]`, and `[WARNING]` can be used to emphasize important information. However, don't overuse them. They can interfere with the flow of the text. In general, there should be only a few of them in a document -- no more than three, typically. Also, they should almost never be use at the start of a document, right after a page title or a section heading.

Where useful, include a title for an admonition.  Preferably, use short, succinct titles. For brevity, you can sometimes exclude articles and use ampersand instead of "and".  Be sure to format the title with title-case.

Sparingly use brief sentences. Usually, a sentence in place of a title succinctly summarizes the main text of the admonition or could perhaps be an excerpt from it. Regardless of which, maintain a proper sentence structure -- including ending with a period -- and don't use title case. Here are some examples:

[example]
====
.Admonition Interruptions
[WARNING]
Overusing admonition blocks tend to interrupt the flow of the text for the reader.
====

[example]
====
.Don't overuse admonitions.
[WARNING]
Overusing admonition blocks tend to interrupt the flow of the text for the reader.
====


== Capitalization

You should use title or headline case for all titles, including page, section, and sub-section titles. This means using capital letters for the first letter of each word in a title or heading, but not usually for smaller words (e.g., "of", "in", "with").

[example]
====
= Style Guidelines for Vaadin Documentation
====

For a detailed description of capitalization rules, see http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html[Rules for Capitalization in Titles of Articles].



== Emphasis
Use the emphasis styles, such as `+++[+++classname+++]#+++ClassName+++#+++` emphasis for class names and `+++[+++methodname+++]#+++methodName()+++#+++` for methods.

[%header, cols="2,4,2"]
|====
|Style Element | AsciiDoc Example Code | Result
|Class Names | `+++[classname]`Component`+++` | [classname]`Component`
|Interface Names | `+++[interfacename]`EventListener`+++` | [interfacename]`EventListener`
|Method Names | `+++[methodname]`setValue()`+++` | [methodname]`setValue()`
|Annotation Names | `+++[annotationname]`@Route`+++` | [annotationname]`@Route`
|GUI Buttons | `+++[guibutton]#OK#+++` | [guibutton]#OK#
|GUI Labels | `+++[guilabel]#OK#+++` | [guilabel]#OK#
|File Names | `+++[filename]`readme.txt`+++` | [filename]`readme.txt`
|Other Monospace | `+++`appName`+++` | `appName`
|Key Caps | `+++kbd:[Ctrl+Shift+C]+++` | kbd:[Ctrl+Shift+C]
|Menu Choices | `+++"Help > Updates"+++` or
`+++menu:Help[Updates]+++`| "Help > Updates"
|====



== Method Names

Use empty parentheses at the end of method names to denote that they're methods. In general, don't list parameter types for methods, unless this is required to refer to a specific version of a method. It may also be necessary to specify a parameter when it's relevant in the context. For example:

[example.recommend]
Call `setEnabled()` to control if a component is enabled or disabled.
[example.avoid]
Call `setEnabled` to control if a component is enabled or disabled.

[example.recommend]
Call `setEnabled(false)` to disable it.


[[lists]]
== Lists & Oxford Comma

Items in a list can be separated by commas. If a list contains three or more items, and the last item is preceded by a conjunction (i.e., _and_, _or_), place a comma before the conjunction. This use of a comma is called the _Oxford comma_. For example:

[example]
====
_The team includes analysts, developers**, and testers**._

_Leave a comment in the forum if you have any doubts, queries**, or suggestions**._
====

// Allow 'separators'
pass:[<!-- vale Vaadin.Terms = NO -->]

To avoid confusion in more complex lists for which each item is composed of phrases that require commas, use semi-colons to separate items. For example:

pass:[<!-- vale Vaadin.Terms = YES -->]

[example]
====
Classic Components includes the following: HorizontalLayout, VerticalLayout, Panel, Label, GridLayout, and FormLayout.

Several built-in HTML elements may be used: `<div>` and `</div>`**,** which are used for indicating web page sections**;** and `<p>` and `</p>`**,** which are used for paragraphs.
====


== Graphics & Images
Graphics can be useful as a way of conveying information quickly and succinctly. However, not everyone is able to see graphics clearly or at all.

For this reason, you should also use alternative ways of communicating the information shown in any given graphic. When using graphics, make sure the reader is given the same information in text. The graphic should be an enhancement to what you're saying in the text -- not instead of writing text.


// TODO passive voice
// TODO contractions
// TODO cross references
// TODO note-that
// TODO so
// TODO please
// TODO refer to
// TODO just-simply
// TODO heading formatting
// TODO source-code
