= Deploying Using Cloud Providers

Vaadin applications are standard Java Web Applications, and as such can be deployed on most cloud services that support Java applications.

If your deployment uses multiple servers, be sure to configure sticky sessions to the load balancer.
This improves performance and makes your application development much easier.

[NOTE]
Sticky sessions are a load balancer feature that makes sure all requests from a particular user (session) are sent to the same server in a cluster.
This means that sessions do not need to be replicated between servers, significantly reducing server cluster complexity.

Some providers will require a pre-built JAR or WAR file, while some allow you to deploy, for example, directly from GitHub.
For this reason, we have split up the documentation to cover each cloud provider in their own article.

Even though the deployment itself varies from provider to provider, the <<.#, Production Mode>> article is recommended reading before delving into the tutorials, as it explains some common things, such as what a production build is and how to do such a build.

All articles for deploying onto specific cloud providers can be found in our Learning Center:

https://vaadin.com/learn/tutorials/cloud-deployment/[Cloud deployment tutorials]
