---
title: Styling
page-title: How to style the Upload component | Vaadin components
description: Styling API reference for the Upload component.
meta-description: Learn how to style and customize the Vaadin Upload component for your application.
order: 50
---
= Upload Styling

== Style Variants

Upload supports the following style variants:

[cols="1,3,1"]
|===
| Variant | Description | Supported by

|`no-border`
|Removes border around the upload component
|Aura

|===


include::../_styling-section-theming-props.adoc[tag=style-properties]

=== Upload Properties

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-upload-background`
|Aura

|`--vaadin-upload-border-color`
|Aura

|`--vaadin-upload-border-radius`
|Aura

|`--vaadin-upload-border-width`
|Aura

|`--vaadin-upload-padding`
|Aura

|`--vaadin-upload-drop-label-color`
|Aura

|`--vaadin-upload-drop-label-font-size`
|Aura

|`--vaadin-upload-drop-label-font-weight`
|Aura

|`--vaadin-upload-drop-label-gap`
|Aura

|`--vaadin-upload-drop-label-line-height`
|Aura

|===

=== File List Properties

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-upload-file-list-divider-color`
|Aura

|`--vaadin-upload-file-list-divider-width`
|Aura

|===

=== File Properties

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-upload-file-border-radius`
|Aura

|`--vaadin-upload-file-button-background`
|Aura

|`--vaadin-upload-file-button-border-color`
|Aura

|`--vaadin-upload-file-button-border-radius`
|Aura

|`--vaadin-upload-file-button-border-width`
|Aura

|`--vaadin-upload-file-button-text-color`
|Aura

|`--vaadin-upload-file-button-padding`
|Aura

|`--vaadin-upload-file-done-color`
|Aura

|`--vaadin-upload-file-error-color`
|Aura

|`--vaadin-upload-file-error-font-size`
|Aura

|`--vaadin-upload-file-error-font-weight`
|Aura

|`--vaadin-upload-file-error-line-height`
|Aura

|`--vaadin-upload-file-gap`
|Aura

|`--vaadin-upload-file-name-color`
|Aura

|`--vaadin-upload-file-name-font-size`
|Aura

|`--vaadin-upload-file-name-font-weight`
|Aura

|`--vaadin-upload-file-name-line-height`
|Aura

|`--vaadin-upload-file-padding`
|Aura

|`--vaadin-upload-file-status-color`
|Aura

|`--vaadin-upload-file-status-font-size`
|Aura

|`--vaadin-upload-file-status-font-weight`
|Aura

|`--vaadin-upload-file-status-line-height`
|Aura

|`--vaadin-upload-file-warning-color`
|Aura

|===

include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-upload`


=== States

Upload with drop area disabled:: `vaadin-upload+++<wbr>+++**[nodrop]**`
Upload with file dragged over:: `vaadin-upload+++<wbr>+++**[dragover]**`
Upload with file dragged over and validated:: `vaadin-upload+++<wbr>+++**[dragover-valid]**`


=== Button and Drop Label

Button and drop label wrapper:: `vaadin-upload+++<wbr>+++**::part(primary-buttons)**`
Upload button:: `vaadin-upload+++<wbr>+++** > vaadin-button**`
Upload button text:: `vaadin-upload+++<wbr>+++** > vaadin-button::part(label)**`
Hovered button:: `vaadin-upload+++<wbr>+++** > vaadin-button:hover**`
Focused button:: `vaadin-upload+++<wbr>+++** > vaadin-button[focused]**`
Disabled button:: `vaadin-upload+++<wbr>+++** > vaadin-button[disabled]**`
Drop label:: `vaadin-upload+++<wbr>+++**::part(drop-label)**`
Drop label text:: `vaadin-upload+++<wbr>+++** > [slot="drop-label"]**`
Drop label icon wrapper:: `vaadin-upload+++<wbr>+++** > [slot="drop-label-icon"]**`
Drop label icon:: `vaadin-upload+++<wbr>+++** > [slot="drop-label-icon"]::before**`


=== File List

File list wrapper:: `vaadin-upload-file-list`
File list:: `vaadin-upload-file-list+++<wbr>+++**::part(list)**`


=== File

File element:: `vaadin-upload-file`
Meta information wrapper:: `vaadin-upload-file+++<wbr>+++**::part(meta)**`
File name:: `vaadin-upload-file+++<wbr>+++**::part(name)**`
Status text:: `vaadin-upload-file+++<wbr>+++**::part(status)**`
Error message:: `vaadin-upload-file+++<wbr>+++**::part(error)**`

==== File States

Focused file:: `vaadin-upload-file+++<wbr>+++**[focused]**`
Hovered file:: `vaadin-upload-file+++<wbr>+++**:hover**`
File uploaded successfully:: `vaadin-upload-file+++<wbr>+++**[complete]**`
File that failed with an error:: `vaadin-upload-file+++<wbr>+++**[error]**`
File with upload in progress:: `vaadin-upload-file+++<wbr>+++**[uploading]**`
File with unknown remaining time estimate:: `vaadin-upload-file+++<wbr>+++**[indeterminate]**`
Icon: upload completed:: `vaadin-upload-file+++<wbr>+++**::part(done-icon)**`
Icon: upload failed:: `vaadin-upload-file+++<wbr>+++**::part(warning-icon)**`

==== File Actions

Actions wrapper:: `vaadin-upload-file+++<wbr>+++**::part(commands)**`
Start upload button:: `vaadin-upload-file+++<wbr>+++**::part(start-button)**`
Retry button:: `vaadin-upload-file+++<wbr>+++**::part(retry-button)**`
Remove button:: `vaadin-upload-file+++<wbr>+++**::part(remove-button)**`

==== Progress Bar

Progress bar element:: `vaadin-upload-file+++<wbr>+++** > vaadin-progress-bar**`
Progress bar track:: `vaadin-upload-file+++<wbr>+++** > vaadin-progress-bar::part(bar)**`
Progress bar indicator:: `vaadin-upload-file+++<wbr>+++** > vaadin-progress-bar::part(value)**`
Indeterminate progress bar (unknown estimate):: `vaadin-upload-file+++<wbr>+++** > vaadin-progress-bar[indeterminate]**`
