---
title: Basics
page-title: How to create a basic component in Vaadin Flow
description: Create a Vaadin component with a client-side element and a server-side Java API.
meta-description: Discover how to create basic components to extend your Vaadin Flow applications using the Element API.
order: 2
---


= Creating a Component Using the Element API
:toclevels: 2

All Vaadin components consist of a client-side HTML element and a server-side Java component. The server-side components extend the [classname]`com.vaadin.flow.component.Component` base class. Vaadin provides support for keeping the client-side element and server-side component in sync.


== Defining a Root Element

Every component is associated with a root `Element`, which is accessible from the [methodname]`component.getElement()` method. The `@Tag` annotation specifies the HTML tag name of the root element.

You use the Element API to interact with the client-side elements, for example by manipulating attributes, properties and styles, and reacting to events. See the <<element-api/#,Element API>> reference guide for more information.

*Example*: Creating a `TextField` component based on an `<input>` element:

[source,java]
----
@Tag("input")
public class TextField extends Component {

    public TextField(String value) {
        getElement().setProperty("value",value);
    }
}
----

You can use predefined constants in the `@Tag` annotation. For example, the `@Tag("input")` annotation is equivalent to `@Tag(Tag.INPUT)`. Most tag names have a constant, but not all.


=== Multiple Elements

A component can consist of multiple elements in the DOM tree. In this case, the root element is still defined using the `@Tag` annotation, and other elements are created and appended to the root element using the Element API.

*Example*: Creating a `TextField` component with `<input>` and `<label>` elements inside a `<div>` root element:

[source,java]
----
@Tag("div")
public class TextField extends Component {

    private final Element labelElement = new Element("label");
    private final Element inputElement = new Element("input");

    public TextField() {
        getElement().appendChild(labelElement, inputElement);
    }
}
----

This generates the following DOM-tree structure in the browser:

[source,html]
----
<div>
    <label></label>
    <input>
</div>
----


== Creating a Java API

The Element API provides low-level access to the client-side element. You typically want to create a higher-level Java API that hides these details from the users of your component.

A Vaadin component API consists of:

* Properties for accessing and setting values. This is covered in the <<properties#,Component Properties>> reference guide.
* Events and event listeners for reacting to user actions. This is covered in the <<events#,Declaring and Firing Component Events>> reference guide.
* Other methods that act on the component. Some of them may use the Element API to call JavaScript functions on the client side. This is covered in the <<client-server-rpc#,Remote Procedure Calls>> reference guide.


*Example*: An API for getting and setting the `value` property, and reacting to value changes:

[source,java]
----
@Synchronize("change")
public String getValue() {
    return getElement().getProperty("value");
}

public void setValue(String value) {
    getElement().setProperty("value", value);
    fireEvent(new ValueChangeEvent(this, false));
}

public Registration addValueChangeListener(
        ComponentEventListener<ValueChangeEvent> listener) {
    return addListener(ValueChangeEvent.class, listener);
}

----


== Setting Id

You can set an `Id` for any component. The `Id` is passed to the client side as the `id` of the corresponding element. However, an `Id` *must be unique within the page*, as it can be used to select the element in JavaScript code or CSS rules.

*Example*: Setting a component `Id`:

[source,java]
----
component.setId("my-component");
----


[discussion-id]`2E20FB94-B5FD-4105-B53B-3EECA329EFF3`
