---
title: Development Tools
page-title: How to use dev tools in development mode | Vaadin
description: Vaadin tools available when running applications in development mode.
meta-description: Discover how to configure and utilize Vaadin Dev Tools to streamline development and debugging processes.
order: 209
---


= [deprecated:com.vaadin:vaadin@V24.4]#Vaadin Development Tools#

// tag::deprecation-notice[]
ifdef::admonition[]
[WARNING]
====
endif::admonition[]
Vaadin Development Tools have been replaced with <<{articles}/tools/copilot#,Copilot>> since version 24.4 of Vaadin.
ifdef::admonition[]
====
endif::admonition[]
// end::deprecation-notice[]

Boost productivity with the Vaadin Development Tools, such as Component Locator, that are available when running applications in development mode.

Current and future functionality of Vaadin Development Tools may offer developers ways to alter the application configuration or even application code. Therefore, it may not be desirable to enable access to Development Tools for everyone -- even when running an application in development mode.

By default, Development Tools can be accessed only from loopback addresses. To configure hosts for Development Tools access, please see `devmode.hostsAllowed` <</flow/configuration/properties/#properties,configuration property>>.


== Topics

section_outline::[]
