stateDiagram-v2
    direction LR
    Browser: Browser
    NavigationAccessControl: Navigation Access Control
    ViewAccessChecker: View Access Checker
    RoutePathAccessChecker: Route Path Access Checker
    CustomAccessChecker: Custom Access Checker
    DecisionResolver: Decision Resolver
    Result: Allow or Deny
    state checkers <<fork>>
    Browser --> NavigationAccessControl
    NavigationAccessControl --> checkers
    checkers --> ViewAccessChecker
    checkers --> RoutePathAccessChecker
    checkers --> CustomAccessChecker
    state compute_result <<join>>
    ViewAccessChecker --> compute_result
    RoutePathAccessChecker --> compute_result
    CustomAccessChecker --> compute_result
    compute_result --> DecisionResolver
    DecisionResolver --> Result
