---
title: UI Unit Testing
description: UI unit testing removes the need to run both the browser and the servlet container, to test your Vaadin-based applications faster.
order: 10
page-links:
  - https://vaadin.com/api/com.vaadin/vaadin-testbench-unit[API]
section-nav: commercial
---

= [since:com.vaadin:vaadin@V23.2]#UI Unit Testing#

:commercial-feature: TestBench
include::{articles}/_commercial-banner.asciidoc[opts=optional]

// tag::intro[]
UI unit testing is *browser-less*, so you look up components straight from [methodname]`UI.getCurrent()`, bypassing the browser and the JavaScript -> server bridge.
You call methods directly on your server-side view classes and on the server-side Java Vaadin components.

Because UI unit testing is also *container-less*, you do not need to launch the servlet container.
The [classname]`UIUnitTest` class handles creating the Vaadin session, the UI and other necessary Vaadin classes right in the JVM that runs your JUnit tests.
// end::intro[]

== Advantages of UI Unit Testing

Advantages of UI unit testing over end-to-end testing:

* *Fast*: browser-less tests are typically 100&times; faster than end-to-end tests and run in 5-60 milliseconds, depending on their complexity.
* Reliable: no arbitrary sleeps are needed, as the test is executed on the server side and it can wait until the request is fully processed.
No random failures because of incompatibility between the Selenium drivers used in end-to-end testing and the browser.
* Headless: the tests run headless, as there is no browser.
No need to set up the screen in your CI environment.
* Robust: the test runs in the same JVM as the server-side components.
If the server-side bootstrap fails and throws an exception, the test method fails with the same exception.
No need to go hunting for exceptions in a log located somewhere on a CI server.
* No need to write a massive set of Page Objects.
You are already on the server, and you have access to the actual Java components that are already providing you with high-level APIs, exactly as Page Objects do.
* Full access to the database.
You are on the server side, so you can access the database from your tests in the same way your business logic accesses the database.
You can run a bunch of SQL statements to restore the database to a known state before every test.
Even better, you can run the test in a transaction, then roll back after the test to perform a fast database revert to a known state.

With this technique, you can run 600 UI tests in 7 seconds, as opposed to 1 to 2 hours with the end-to-end testing approach.
Because of the speed, you can let the UI tests run after every commit via your continuous integration server.
Bypassing the browser and talking to the Vaadin server API directly eliminates the need to start the servlet container.
You can add the server `JARs` to the testing classpath and call the Vaadin server API, which, in turn, invokes your server logic.

== Limitations

Testing using [classname]`UIUnitTest` is designed to bypass the browser and the servlet container.
This means that it is impossible to test JavaScript code, templates, and other client-side functionalities.
If you need to test client-side features, you need to use browser-based integration tests with TestBench.


[.discussion-id]
17590340-7B0A-463B-846B-FEDB1F1AE1B3
