---
title: Configuration
page-title: Kubernetes configuration for Vaadin deployment
description: Configuration options for Kubernetes Kit.
meta-description: Configure Kubernetes Kit for deploying Vaadin applications with ease.
order: 120
---


= Configuring Kubernetes Kit

== Packages Inspected during Serialization

When a session is serialized, Kubernetes Kit inspects classes for transient fields that can be injected during deserialization (see <<session-replication#,session replication>>).

Kubernetes Kit provides two properties to limit the packages to be inspected. The `include-package` property defines all of the packages that should be inspected. If this is undefined, all packages are assessed. For this reason, it's recommended that you specify the top-level package for your application in the `include-packages` property.

The `exclude-package` property lists packages that should not be assessed.

[.example]
--
.application.properties
[source,properties]
----
vaadin.serialization.include-packages=com.example.application
vaadin.serialization.exclude-packages=com.example.application.service
----

.application.yaml
[source,yaml]
----
vaadin:
  serialization:
    include-packages: com.example.application
    exclude-packages: com.example.application.service
----
--


== Hazelcast for Session Replication

The `service-name` property defines the name of the Hazelcast service deployment within a cluster.

The optional `namespace` property is used when the Hazelcast service is deployed in a namespace other than `default`.

[.example]
--
.application.properties
[source,properties]
----
vaadin.kubernetes.hazelcast.service-name=hazelcast-service
vaadin.kubernetes.hazelcast.namespace=namespace
----

.application.yaml
[source,yaml]
----
vaadin:
  kubernetes:
    hazelcast:
      service-name: hazelcast-service
      namespace: namespace
----
--


== Redis for Session Replication

This property defines the name of the Redis service deployment within a cluster.

[.example]
--
.application.properties
[source,properties]
----
spring.data.redis.host: redis-service
----

.application.yaml
[source,yaml]
----
spring:
  redis:
    host: redis-service
----
--

== Backend Session Expiration Policy

The backend session expiration policy allows you to define an expiration timeout for the backend stored session. By default, no expiration is set. However, expiration can be activated by setting the `vaadin.kubernetes.backend-session-expiration-tolerance` property. The property defines the amount of time to be added to the HTTP session timeout to determine the expiration of the backend session. If a time unit is not given, milliseconds is assumed. Another option is to provide a custom `SessionExpirationPolicy` bean, which allows you to define a custom expiration timeout, independent of the HTTP session timeout value.

[.example]
--
Given an HTTP session timeout of 30 minutes, the session stored in the backend will expire after 35 minutes of inactivity.
[source,properties]
----
<source-info group="application.properties"></source-info>
vaadin.kubernetes.backend-session-expiration-tolerance: 5m
----

Given an HTTP session timeout of 30 minutes, the session stored in the backend will expire after 35 minutes of inactivity.
[source,yaml]
----
<source-info group="application.yaml"></source-info>
vaadin:
  kubernetes:
    backend-session-expiration-tolerance: 5m
----

The session stored in the backend will expire after 35 minutes of inactivity, regardless of the HTTP session timeout.
[source,java]
----
<source-info group="Java bean"></source-info>
@Bean
SessionExpirationPolicy sessionExpirationPolicy() {
    return sessionTimeout -> Duration.ofMinutes(35);
}
----
--
