---
title: Licensing pass:[&] Pricing
order: 3
layout: page
---

[[ce.developing]]
= Licensing and Pricing Model

[role="since:com.vaadin:vaadin@V14.7 standalone"]
--
--

[Collaboration Engine](https://vaadin.com/collaboration) is licensed under the https://vaadin.com/license/cvrl-1.0[Commercial Vaadin Runtime License (CVRL)].
You can try Collaboration Engine out and develop applications with it without charge.
When you take your application to production, you need a valid license file.
To get started, follow the <<tutorial#,Quick Start Guide>> to learn about adding Collaboration Engine to your Vaadin application, and using its high-level APIs.

While your application is in development mode, you can use all the features of Collaboration Engine without restrictions.
You do not need a development license or a separate trial.
Development mode is the default mode of a Vaadin application and is used when not explicitly configured to do a production build.

[[ce.developing.pricing-model]]
== Billing Model

Collaboration Engine is billed at run-time, based on the number of unique users per month using collaboration features in an application.

To take an application using Collaboration Engine into production, there are two options:

* Free "Universal" License
* Commercial License

[[ce.developing.free-universal-license]]
== Free "Universal" License

The "Universal" License is free for all Vaadin developers.
It allows up to 20 unique  users in a Vaadin application to use features that rely on Collaboration Engine each month.
Developers do not require a commercial Vaadin subscription (Pro, Prime, or Enterprise) to use this license.
To download this license, visit the <<going-to-production#, "When you take your application to production">> section of the documentation.


[[ce.developing.paid-commercial-license]]
== Commercial License

This license requires an active commercial Vaadin subscription (Pro, Prime, or Enterprise).
Each commercial Vaadin subscription is entitled to a bundled quota of users.

* Pro subscribers get 50 bundled users per month.
* Prime subscribers get 150 bundled users per month.
* Enterprise subscribers can negotiate a custom quota.

A https://vaadin.com/collaboration#pricing[starting package] of 500 users per month can be purchased without the need of another commercial subscription. 
Custom bundles are also possible.

If you already have a commercial Vaadin subscription, please https://vaadin.com/collaboration#contact-us[contact our team to request a license]. Otherwise, please visit the https://vaadin.com/pricing[pricing page] to purchase a commercial Vaadin subscription.
