/**
 * Highlights content changed in the current PR on preview deployments.
 *
 * Fetches /preview-changes.json (generated by scripts/generate-preview-changes.mjs
 * and only present in preview deployments), highlights rendered blocks whose
 * text matches added source lines, inserts markers showing removed content, and
 * shows a floating panel that lists all changed pages and lets you step through
 * changes. Disabled unless the build set the preview flag (see below).
 *
 * Navigation:
 * - n / p          jump to the next / previous change on the current page
 * - N / P          go to the next / previous changed page
 * The same actions are available as buttons in the panel.
 */

// Injected by the build via vite `define` (vite.dspublisher.ts): true only when
// DOCS_PREVIEW_DIFF=true was set, i.e. for preview deployments. Referenced with
// `typeof` below so a build that doesn't define it doesn't throw.
declare const __DOCS_PREVIEW_DIFF__: boolean;

interface Deletion {
  // Anchor needles for the surviving blocks before / after the removed content.
  before: string | null;
  after: string | null;
  // The removed source lines, shown verbatim in the marker.
  text: string[];
}

interface ChangedPage {
  path: string;
  file: string;
  status: string;
  added: number;
  removed: number;
  needles: string[];
  deletions?: Deletion[];
}

interface ChangesManifest {
  pages: ChangedPage[];
}

const HIGHLIGHT_CLASS = 'preview-diff-changed';
const DELETION_CLASS = 'preview-diff-deletion';
// Wrapper for deletions whose anchor wasn't found; deliberately NOT DELETION_CLASS
// so the wrapper itself isn't treated as a navigation target.
const DELETION_GROUP_CLASS = 'preview-diff-deletion-group';
const ACTIVE_CLASS = 'preview-diff-active';
const PANEL_ID = 'preview-diff-panel';
const BLOCK_SELECTOR =
  'p, li, h1, h2, h3, h4, h5, h6, td, th, dt, dd, pre, blockquote, caption, figcaption';
// Blocks whose text is longer than this are skipped during matching to keep the
// (repeated, per-retry) scan cheap. Far above any real prose or code-example block.
const MAX_BLOCK_TEXT_LENGTH = 50000;

// sessionStorage key used to carry "scroll to a change" intent across a
// cross-page navigation (a full page load on this static site).
const AUTOSCROLL_KEY = 'preview-diff:autoscroll';

// Module state for the current page, refreshed on every apply().
let manifestPages: ChangedPage[] = [];
let changedBlocks: HTMLElement[] = [];
let currentIndex = -1;
let counterEl: HTMLElement | null = null;
// Path of the page the highlights were last applied to. apply() runs several
// times per page (the SPA re-apply retries), so this distinguishes a genuine
// page change from a repeated apply on the same page.
let appliedPath: string | null = null;

// Must match the normalization in scripts/generate-preview-changes.mjs
function normalize(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function currentPagePath(): string {
  return decodeURIComponent(window.location.pathname).replace(/\/+$/, '').replace(/^\//, '');
}

function findCurrentPageIndex(): number {
  const current = currentPagePath();
  const exact = manifestPages.findIndex((page) => page.path === current);
  if (exact !== -1) {
    return exact;
  }
  // Fall back to the longest matching path suffix, so "bar/foo" is preferred
  // over "foo" when the URL ends with "/bar/foo".
  let best = -1;
  let bestLength = -1;
  manifestPages.forEach((page, i) => {
    if (page.path !== '' && current.endsWith(`/${page.path}`) && page.path.length > bestLength) {
      best = i;
      bestLength = page.path.length;
    }
  });
  return best;
}

/**
 * The URL path prefix the docs are served under, derived from the current page
 * (e.g. "docs" when the current URL is "/docs/components/button" and the
 * matched manifest path is "components/button"). Empty for root deployments.
 */
function currentPathPrefix(): string {
  const current = currentPagePath();
  const index = findCurrentPageIndex();
  if (index === -1) {
    return '';
  }
  const matched = manifestPages[index].path;
  if (matched === '') {
    return current;
  }
  if (current === matched) {
    return '';
  }
  // current ends with "/" + matched (guaranteed by findCurrentPageIndex)
  return current.slice(0, current.length - matched.length - 1);
}

/** Builds an absolute href for a manifest page, preserving any path prefix. */
function pageHref(targetPath: string): string {
  const full = [currentPathPrefix(), targetPath].filter(Boolean).join('/');
  return `/${full}`;
}

function injectStyles() {
  if (document.getElementById('preview-diff-styles')) {
    return;
  }
  const style = document.createElement('style');
  style.id = 'preview-diff-styles';
  style.textContent = `
    .${HIGHLIGHT_CLASS} {
      position: relative;
      background-color: rgba(46, 160, 67, 0.16);
      box-shadow: -0.75rem 0 0 0 rgba(46, 160, 67, 0.16), inset 3px 0 0 0 transparent;
      border-radius: 2px;
      scroll-margin-top: 5rem;
    }
    .${HIGHLIGHT_CLASS}::before {
      content: '';
      position: absolute;
      margin-left: -0.95rem;
      width: 3px;
      height: 1.2em;
      background: rgb(46, 160, 67);
      border-radius: 2px;
    }
    .${HIGHLIGHT_CLASS}.${ACTIVE_CLASS} {
      outline: 2px solid rgb(46, 160, 67);
      outline-offset: 3px;
      background-color: rgba(46, 160, 67, 0.28);
    }
    body.preview-diff-hidden .${HIGHLIGHT_CLASS} {
      background-color: transparent;
      box-shadow: none;
      outline: none;
    }
    body.preview-diff-hidden .${HIGHLIGHT_CLASS}::before {
      display: none;
    }
    body.preview-diff-hidden .${DELETION_CLASS},
    body.preview-diff-hidden .${DELETION_GROUP_CLASS} {
      display: none;
    }
    .${DELETION_GROUP_CLASS} {
      margin: 1.5rem 0;
    }
    .${DELETION_GROUP_CLASS} .preview-diff-deletion-group-note {
      margin-bottom: 0.25rem;
      font-family: system-ui, sans-serif;
      font-size: 0.75rem;
      color: var(--docs-secondary-text-color, #5b7282);
    }
    .${DELETION_CLASS} {
      margin: 0.5rem 0;
      border-left: 3px solid rgb(207, 34, 46);
      background-color: rgba(207, 34, 46, 0.08);
      border-radius: 2px;
      scroll-margin-top: 5rem;
      font-family: system-ui, sans-serif;
    }
    .${DELETION_CLASS}.${ACTIVE_CLASS} {
      outline: 2px solid rgb(207, 34, 46);
      outline-offset: 3px;
    }
    .${DELETION_CLASS} .preview-diff-deletion-toggle {
      display: flex;
      align-items: center;
      gap: 0.4rem;
      width: 100%;
      box-sizing: border-box;
      padding: 0.25rem 0.5rem;
      font: inherit;
      font-size: 0.8125rem;
      color: rgb(140, 20, 28);
      background: transparent;
      border: 0;
      cursor: pointer;
      text-align: left;
    }
    .${DELETION_CLASS} .preview-diff-deletion-toggle::before {
      content: '−';
      font-weight: 700;
    }
    .${DELETION_CLASS} .preview-diff-deletion-body {
      margin: 0;
      padding: 0.25rem 0.5rem 0.5rem 1rem;
      overflow-x: auto;
      white-space: pre-wrap;
      font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      font-size: 0.75rem;
      line-height: 1.45;
      color: rgb(110, 20, 26);
      text-decoration: line-through;
      text-decoration-color: rgba(207, 34, 46, 0.4);
    }
    [theme~="dark"] .${DELETION_CLASS} {
      background-color: rgba(207, 34, 46, 0.18);
    }
    [theme~="dark"] .${DELETION_CLASS} .preview-diff-deletion-toggle,
    [theme~="dark"] .${DELETION_CLASS} .preview-diff-deletion-body {
      color: rgb(255, 170, 170);
    }
    #${PANEL_ID} {
      position: fixed;
      bottom: 1rem;
      right: 1rem;
      z-index: 10000;
      max-width: 22rem;
      max-height: 70vh;
      overflow: auto;
      font-family: system-ui, sans-serif;
      font-size: 0.8125rem;
      line-height: 1.4;
      background: var(--docs-surface-color-2, #fff);
      color: var(--docs-body-text-color, #213343);
      border: 1px solid var(--docs-divider-color-1, #dde4eb);
      border-radius: 0.5rem;
      box-shadow: 0 2px 12px rgba(0, 0, 0, 0.2);
      padding: 0.5rem 0.75rem;
    }
    #${PANEL_ID} summary {
      cursor: pointer;
      font-weight: 600;
      user-select: none;
    }
    #${PANEL_ID} ul {
      margin: 0.5rem 0 0;
      padding-left: 1.25rem;
    }
    #${PANEL_ID} li {
      margin: 0.25rem 0;
    }
    #${PANEL_ID} li.current {
      font-weight: 600;
    }
    #${PANEL_ID} .preview-diff-meta {
      color: var(--docs-secondary-text-color, #5b7282);
      font-size: 0.75rem;
      margin-top: 0.5rem;
    }
    #${PANEL_ID} .preview-diff-nav {
      display: flex;
      align-items: center;
      gap: 0.25rem;
      margin-top: 0.5rem;
    }
    #${PANEL_ID} .preview-diff-nav-label {
      width: 3.25rem;
      flex-shrink: 0;
      color: var(--docs-secondary-text-color, #5b7282);
      font-size: 0.75rem;
    }
    #${PANEL_ID} .preview-diff-counter {
      flex: 1;
      text-align: center;
      font-variant-numeric: tabular-nums;
      font-size: 0.75rem;
    }
    #${PANEL_ID} button {
      font: inherit;
      font-size: 0.75rem;
      cursor: pointer;
      padding: 0.125rem 0.5rem;
      border-radius: 0.25rem;
      border: 1px solid var(--docs-divider-color-1, #dde4eb);
      background: transparent;
      color: inherit;
    }
    #${PANEL_ID} button:disabled {
      opacity: 0.4;
      cursor: default;
    }
    #${PANEL_ID} .preview-diff-toggle {
      margin-top: 0.5rem;
    }
  `;
  document.head.appendChild(style);
}

function getArticleContainer(): Element {
  return (
    document.querySelector('main article') ||
    document.querySelector('article') ||
    document.querySelector('main') ||
    document.body
  );
}

function highlightBlocks(page: ChangedPage, container: Element) {
  // Clear previous run (SPA navigation re-applies on the same document)
  document.querySelectorAll(`.${HIGHLIGHT_CLASS}`).forEach((el) => {
    el.classList.remove(HIGHLIGHT_CLASS, ACTIVE_CLASS);
  });

  if (page.needles.length === 0) {
    return;
  }

  container.querySelectorAll(BLOCK_SELECTOR).forEach((block) => {
    // Skip the panel and any deletion marker/group (a previous run's markers may
    // still be in the DOM during the SPA retry, and their <pre> bodies would
    // otherwise be matched and highlighted as false positives).
    if (block.closest(`#${PANEL_ID}, .${DELETION_CLASS}, .${DELETION_GROUP_CLASS}`)) {
      return;
    }
    const raw = block.textContent || '';
    // Skip pathologically large blocks so the per-retry scan stays cheap.
    if (raw.length < 4 || raw.length > MAX_BLOCK_TEXT_LENGTH) {
      return;
    }
    const text = normalize(raw);
    if (text.length < 4) {
      return;
    }
    if (page.needles.some((needle) => text.includes(needle))) {
      block.classList.add(HIGHLIGHT_CLASS);
    }
  });

  // A list item and the paragraph inside it can both match; keep only the
  // innermost match so the highlight is as precise as possible.
  document.querySelectorAll(`.${HIGHLIGHT_CLASS}`).forEach((el) => {
    if (el.querySelector(`.${HIGHLIGHT_CLASS}`)) {
      el.classList.remove(HIGHLIGHT_CLASS);
    }
  });
}

/** Finds the rendered block whose text contains the given needle. */
function findBlockByNeedle(container: Element, needle: string | null): HTMLElement | null {
  if (!needle) {
    return null;
  }
  const blocks = container.querySelectorAll<HTMLElement>(BLOCK_SELECTOR);
  for (const block of Array.from(blocks)) {
    if (block.closest(`#${PANEL_ID}, .${DELETION_CLASS}, .${DELETION_GROUP_CLASS}`)) {
      continue;
    }
    const raw = block.textContent || '';
    if (raw.length > MAX_BLOCK_TEXT_LENGTH) {
      continue;
    }
    if (normalize(raw).includes(needle)) {
      return block;
    }
  }
  return null;
}

// Unique id source for wiring a toggle button to the body it controls (aria).
let deletionBodySeq = 0;

/** Shows or hides a deletion marker's removed content, keeping aria state in sync. */
function setDeletionExpanded(marker: HTMLElement, expanded: boolean) {
  const body = marker.querySelector<HTMLElement>('.preview-diff-deletion-body');
  const toggle = marker.querySelector<HTMLElement>('.preview-diff-deletion-toggle');
  if (body) {
    body.hidden = !expanded;
  }
  if (toggle) {
    toggle.setAttribute('aria-expanded', String(expanded));
  }
}

/** Builds the collapsible "removed content" marker element for one deletion. */
function buildDeletionMarker(deletion: Deletion): HTMLElement {
  const marker = document.createElement('div');
  marker.className = DELETION_CLASS;
  marker.tabIndex = -1;

  const bodyId = `preview-diff-removed-${deletionBodySeq++}`;
  const lineCount = deletion.text.length;
  const toggle = document.createElement('button');
  toggle.type = 'button';
  toggle.className = 'preview-diff-deletion-toggle';
  toggle.textContent = `${lineCount} line${lineCount === 1 ? '' : 's'} removed`;
  toggle.setAttribute('aria-expanded', 'false');
  toggle.setAttribute('aria-controls', bodyId);

  const body = document.createElement('pre');
  body.className = 'preview-diff-deletion-body';
  body.id = bodyId;
  body.hidden = true;
  body.textContent = deletion.text.join('\n');

  toggle.addEventListener('click', () => {
    setDeletionExpanded(marker, toggle.getAttribute('aria-expanded') !== 'true');
  });

  marker.appendChild(toggle);
  marker.appendChild(body);
  return marker;
}

// Block anchors whose parent (table row, list, definition list) can't host a
// <div> sibling; for these the marker is placed beside the enclosing container.
const RELOCATE_ANCHOR = 'td, th, tr, caption, li, dt, dd';

/**
 * Inserts a block-level marker next to an anchor. A <div> can't be a valid
 * sibling of a table cell/row or a list/definition item, so when the anchor is
 * one of those the marker is placed beside the enclosing table/list instead.
 */
function placeMarker(marker: HTMLElement, anchor: HTMLElement, where: 'before' | 'after') {
  const target: Element = anchor.matches(RELOCATE_ANCHOR)
    ? anchor.closest('table, ul, ol, dl') || anchor
    : anchor;
  if (where === 'after') {
    target.after(marker);
  } else {
    target.before(marker);
  }
}

/**
 * Inserts a marker for each deletion, anchored next to the surviving block it
 * was adjacent to. Deletions whose anchor can't be located are grouped at the
 * end of the article so the removed content is still visible.
 */
function renderDeletions(page: ChangedPage, container: Element) {
  document
    .querySelectorAll(`.${DELETION_CLASS}, .${DELETION_GROUP_CLASS}`)
    .forEach((el) => el.remove());

  const deletions = page.deletions || [];
  const orphans: Deletion[] = [];

  for (const deletion of deletions) {
    const marker = buildDeletionMarker(deletion);
    const beforeBlock = findBlockByNeedle(container, deletion.before);
    if (beforeBlock) {
      placeMarker(marker, beforeBlock, 'after');
      continue;
    }
    const afterBlock = findBlockByNeedle(container, deletion.after);
    if (afterBlock) {
      placeMarker(marker, afterBlock, 'before');
      continue;
    }
    orphans.push(deletion);
  }

  if (orphans.length > 0) {
    // The wrapper uses its own class (not DELETION_CLASS) so it isn't picked up
    // as a navigation target; only the real markers inside it are.
    const group = document.createElement('div');
    group.className = DELETION_GROUP_CLASS;
    const note = document.createElement('div');
    note.className = 'preview-diff-deletion-group-note';
    note.textContent = `${orphans.length} removed section${
      orphans.length === 1 ? '' : 's'
    } (original location not found)`;
    group.appendChild(note);
    for (const deletion of orphans) {
      // Each orphan is a real marker (toggle + aria, individually navigable),
      // expanded by default since there's no surrounding context to orient from.
      const marker = buildDeletionMarker(deletion);
      setDeletionExpanded(marker, true);
      group.appendChild(marker);
    }
    container.appendChild(group);
  }
}

/**
 * Applies highlights and deletion markers, returning every changed element
 * (highlighted blocks and deletion markers) in document order for stepping.
 */
function markChanges(page: ChangedPage): HTMLElement[] {
  const container = getArticleContainer();
  highlightBlocks(page, container);
  renderDeletions(page, container);
  return Array.from(
    document.querySelectorAll<HTMLElement>(`.${HIGHLIGHT_CLASS}, .${DELETION_CLASS}`)
  );
}

function updateCounter() {
  if (!counterEl) {
    return;
  }
  if (changedBlocks.length === 0) {
    counterEl.textContent = 'no changes located';
  } else if (currentIndex < 0) {
    counterEl.textContent = `${changedBlocks.length} change${
      changedBlocks.length === 1 ? '' : 's'
    }`;
  } else {
    counterEl.textContent = `${currentIndex + 1} / ${changedBlocks.length}`;
  }
}

/** Marks an element active, revealing the removed content if it's a deletion marker. */
function markActive(el: HTMLElement) {
  el.classList.add(ACTIVE_CLASS);
  if (el.classList.contains(DELETION_CLASS)) {
    setDeletionExpanded(el, true);
  }
}

/** Scrolls to and visually marks the change at the given index (wraps around). */
function focusChange(index: number) {
  if (changedBlocks.length === 0) {
    return;
  }
  const wrapped = ((index % changedBlocks.length) + changedBlocks.length) % changedBlocks.length;
  currentIndex = wrapped;
  changedBlocks.forEach((b) => b.classList.remove(ACTIVE_CLASS));
  const el = changedBlocks[wrapped];
  markActive(el);
  const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  el.scrollIntoView({ behavior: reducedMotion ? 'auto' : 'smooth', block: 'center' });
  updateCounter();
}

function nextChange(): boolean {
  if (changedBlocks.length === 0) {
    return false;
  }
  focusChange(currentIndex + 1);
  return true;
}

function prevChange(): boolean {
  if (changedBlocks.length === 0) {
    return false;
  }
  focusChange(currentIndex <= 0 ? changedBlocks.length - 1 : currentIndex - 1);
  return true;
}

/**
 * Navigates to another changed page. `where` selects the first or last change
 * to focus once that page loads (carried across the page load via sessionStorage).
 */
function gotoPage(delta: number): boolean {
  if (manifestPages.length < 2) {
    return false;
  }
  const current = findCurrentPageIndex();
  let target: number;
  if (current === -1) {
    target = delta > 0 ? 0 : manifestPages.length - 1;
  } else {
    target = (((current + delta) % manifestPages.length) + manifestPages.length) % manifestPages.length;
  }
  const page = manifestPages[target];
  try {
    sessionStorage.setItem(AUTOSCROLL_KEY, delta < 0 ? 'last' : 'first');
  } catch (e) {
    // Ignore storage failures; navigation still works, just without auto-scroll.
  }
  window.location.assign(pageHref(page.path));
  return true;
}

function renderPanel(currentPage: ChangedPage | undefined) {
  document.getElementById(PANEL_ID)?.remove();
  counterEl = null;
  if (manifestPages.length === 0) {
    return;
  }

  const panel = document.createElement('details');
  panel.id = PANEL_ID;
  panel.open = currentPage !== undefined;

  const summary = document.createElement('summary');
  summary.textContent = `PR changes (${manifestPages.length} page${
    manifestPages.length === 1 ? '' : 's'
  })`;
  panel.appendChild(summary);

  // On-page change stepper
  if (currentPage) {
    const nav = document.createElement('div');
    nav.className = 'preview-diff-nav';

    const label = document.createElement('span');
    label.className = 'preview-diff-nav-label';
    label.textContent = 'On page';
    nav.appendChild(label);

    const prevBtn = document.createElement('button');
    prevBtn.type = 'button';
    prevBtn.textContent = '↑ Prev';
    prevBtn.title = 'Previous change on this page (p)';
    prevBtn.disabled = changedBlocks.length === 0;
    prevBtn.addEventListener('click', prevChange);
    nav.appendChild(prevBtn);

    counterEl = document.createElement('span');
    counterEl.className = 'preview-diff-counter';
    nav.appendChild(counterEl);

    const nextBtn = document.createElement('button');
    nextBtn.type = 'button';
    nextBtn.textContent = 'Next ↓';
    nextBtn.title = 'Next change on this page (n)';
    nextBtn.disabled = changedBlocks.length === 0;
    nextBtn.addEventListener('click', nextChange);
    nav.appendChild(nextBtn);

    panel.appendChild(nav);
    updateCounter();
  }

  // Cross-page stepper
  if (manifestPages.length > 1) {
    const pageNav = document.createElement('div');
    pageNav.className = 'preview-diff-nav';

    const label = document.createElement('span');
    label.className = 'preview-diff-nav-label';
    label.textContent = 'Pages';
    pageNav.appendChild(label);

    const prevPageBtn = document.createElement('button');
    prevPageBtn.type = 'button';
    prevPageBtn.textContent = '← Prev page';
    prevPageBtn.title = 'Previous changed page (P)';
    prevPageBtn.style.flex = '1';
    prevPageBtn.addEventListener('click', () => gotoPage(-1));
    pageNav.appendChild(prevPageBtn);

    const nextPageBtn = document.createElement('button');
    nextPageBtn.type = 'button';
    nextPageBtn.textContent = 'Next page →';
    nextPageBtn.title = 'Next changed page (N)';
    nextPageBtn.style.flex = '1';
    nextPageBtn.addEventListener('click', () => gotoPage(1));
    pageNav.appendChild(nextPageBtn);

    panel.appendChild(pageNav);
  }

  // Page list
  const list = document.createElement('ul');
  for (const page of manifestPages) {
    const item = document.createElement('li');
    const link = document.createElement('a');
    link.href = pageHref(page.path);
    link.textContent = page.path || 'front page';
    // Plain internal anchors are hijacked into a client-side (SPA) navigation
    // by Gatsby, after which the highlights don't re-apply. Force a full page
    // load like the Prev/Next page buttons (gotoPage), which work reliably, and
    // carry the autoscroll intent so it lands on the first change.
    link.addEventListener('click', (e) => {
      if (e.metaKey || e.ctrlKey || e.shiftKey || e.altKey || e.button !== 0) {
        return;
      }
      e.preventDefault();
      try {
        sessionStorage.setItem(AUTOSCROLL_KEY, 'first');
      } catch (err) {
        // Ignore storage failures; navigation still works, just without auto-scroll.
      }
      window.location.assign(link.href);
    });
    item.appendChild(link);
    if (page === currentPage) {
      item.classList.add('current');
      item.appendChild(document.createTextNode(' — this page'));
    }
    list.appendChild(item);
  }
  panel.appendChild(list);

  if (currentPage) {
    const meta = document.createElement('div');
    meta.className = 'preview-diff-meta';
    meta.textContent =
      changedBlocks.length > 0
        ? 'Green = added, red = removed. Use n / p to step through changes, N / P to switch pages.'
        : 'This page changed, but the changes could not be located in the rendered output (e.g. markup-only changes).';
    panel.appendChild(meta);
  }

  const toggle = document.createElement('button');
  toggle.type = 'button';
  toggle.className = 'preview-diff-toggle';
  const updateLabel = () => {
    toggle.textContent = document.body.classList.contains('preview-diff-hidden')
      ? 'Show highlights'
      : 'Hide highlights';
  };
  toggle.addEventListener('click', () => {
    document.body.classList.toggle('preview-diff-hidden');
    updateLabel();
  });
  updateLabel();
  panel.appendChild(toggle);

  document.body.appendChild(panel);
}

function apply(manifest: ChangesManifest) {
  injectStyles();
  manifestPages = manifest.pages;

  const path = currentPagePath();
  const samePage = path === appliedPath;
  appliedPath = path;
  // Preserve the step position across same-page re-applies (the SPA retry runs
  // and any manual stepping the user did between them).
  const prevIndex = samePage ? currentIndex : -1;

  const index = findCurrentPageIndex();
  const currentPage = index === -1 ? undefined : manifestPages[index];

  changedBlocks = currentPage ? markChanges(currentPage) : [];
  currentIndex = -1;
  if (!currentPage) {
    document.querySelectorAll(`.${HIGHLIGHT_CLASS}`).forEach((el) => {
      el.classList.remove(HIGHLIGHT_CLASS, ACTIVE_CLASS);
    });
    document
      .querySelectorAll(`.${DELETION_CLASS}, .${DELETION_GROUP_CLASS}`)
      .forEach((el) => el.remove());
  }

  renderPanel(currentPage);

  // Re-mark the previously active block (without re-scrolling) so repeated
  // applies don't lose the user's place.
  if (prevIndex >= 0 && prevIndex < changedBlocks.length) {
    currentIndex = prevIndex;
    markActive(changedBlocks[prevIndex]);
    updateCounter();
    return;
  }

  // Honor a pending "scroll to change" intent from a cross-page jump. Consume
  // it only once blocks exist, so it survives until async content has rendered.
  if (changedBlocks.length > 0) {
    let intent: string | null = null;
    try {
      intent = sessionStorage.getItem(AUTOSCROLL_KEY);
    } catch (e) {
      // Ignore storage failures.
    }
    if (intent) {
      try {
        sessionStorage.removeItem(AUTOSCROLL_KEY);
      } catch (e) {
        // Ignore storage failures.
      }
      focusChange(intent === 'last' ? changedBlocks.length - 1 : 0);
    }
  }
}

function isTypingTarget(target: EventTarget | null): boolean {
  const el = target as HTMLElement | null;
  if (!el) {
    return false;
  }
  return (
    el.isContentEditable ||
    el.tagName === 'INPUT' ||
    el.tagName === 'TEXTAREA' ||
    el.tagName === 'SELECT'
  );
}

function onKeydown(e: KeyboardEvent) {
  if (manifestPages.length === 0 || e.defaultPrevented) {
    return;
  }
  if (e.metaKey || e.ctrlKey || e.altKey) {
    return;
  }
  // composedPath()[0] is the real (possibly shadow-DOM) target, so typing in a
  // web-component field (e.g. the docs search <vaadin-text-field>) isn't hijacked.
  const target = e.composedPath?.()[0] ?? e.target;
  if (isTypingTarget(target)) {
    return;
  }
  let handled = false;
  switch (e.key) {
    case 'n':
      handled = nextChange();
      break;
    case 'p':
      handled = prevChange();
      break;
    case 'N':
      handled = gotoPage(1);
      break;
    case 'P':
      handled = gotoPage(-1);
      break;
  }
  // Only swallow the key if it actually did something, so unrelated typing of
  // n/p/N/P elsewhere on the page is preserved.
  if (handled) {
    e.preventDefault();
  }
}

/**
 * Fetches the change manifest. Tries the site root first (where the preview
 * Dockerfile serves it), then a <base>-relative URL so a deployment served
 * under a path prefix (e.g. /docs/) also resolves it.
 */
async function fetchManifest(): Promise<ChangesManifest | null> {
  const candidates = ['/preview-changes.json'];
  try {
    const baseRelative = new URL('preview-changes.json', document.baseURI).pathname;
    if (!candidates.includes(baseRelative)) {
      candidates.push(baseRelative);
    }
  } catch (e) {
    // Ignore malformed baseURI.
  }
  for (const url of candidates) {
    try {
      const response = await fetch(url);
      if (response.ok) {
        return await response.json();
      }
    } catch (e) {
      // Try the next candidate.
    }
  }
  return null;
}

async function init() {
  // Guard against the module being evaluated twice in one document (e.g. HMR),
  // which would otherwise double-wrap history.pushState and double-schedule.
  if ((window as unknown as Record<string, unknown>).__previewDiffInit) {
    return;
  }
  (window as unknown as Record<string, unknown>).__previewDiffInit = true;

  // Preview-only feature, gated by a build-time flag rather than the hostname.
  // If the flag is explicitly false (a normal production build), do nothing.
  // If it's missing entirely (the define didn't reach this bundle), fall back
  // to the manifest-presence check below, which is itself preview-only.
  const previewFlag = typeof __DOCS_PREVIEW_DIFF__ !== 'undefined' ? __DOCS_PREVIEW_DIFF__ : undefined;
  if (previewFlag === false) {
    return;
  }

  const manifest = await fetchManifest();
  if (!manifest || !Array.isArray(manifest.pages)) {
    return;
  }

  window.addEventListener('keydown', onKeydown);

  // Re-apply after SPA navigations. The new page content renders
  // asynchronously, so retry a few times after each navigation.
  const schedule = () => {
    [100, 500, 1500].forEach((delay) => setTimeout(() => apply(manifest), delay));
  };
  ['pushState', 'replaceState'].forEach((method) => {
    const original = (history as any)[method];
    (history as any)[method] = function (...args: any[]) {
      const result = original.apply(this, args);
      schedule();
      return result;
    };
  });
  window.addEventListener('popstate', schedule);

  apply(manifest);
  schedule();
}

if (typeof window !== 'undefined') {
  init();
}
