---
title: Button
layout: tabbed-page
tab-title: Usage
page-links:
  - https://github.com/vaadin/vaadin-flow-components/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-button-flow}[Flow {moduleMavenVersion:com.vaadin:vaadin-button-flow}]
  - https://github.com/vaadin/vaadin-button/releases/tag/v{moduleNpmVersion:vaadin-button}[Web Component {moduleNpmVersion:vaadin-button}]
section-nav: incomplete
---

= Button

// tag::description[]
The Button component allows users to perform actions. 
// end::description[]
It comes in several different style variants, and supports icons in addition to text labels.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/button/button-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source,java]
// ----
// include::../../../../src/main/java/com/vaadin/demo/component/button/ButtonBasic.java[render,tags=snippet,indent=0,group=Java]
// ----

--

== Styles

The following variants can be used to distinguish between actions of different importance in the UI:

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/button/button-styles.ts[render,tags=snippet,indent=0,group=TypeScript]
----

--

[%header, cols="1,3a"]
|===
|Variant
|Usage recommendations

|Primary
|* The most important action in a view or part of a view.
* The main closure or continuation action (such as Save) in a form or dialog.
* Avoid presenting the user with more than one at any time.

|Secondary
|* Default style recommended for most actions.
* Alternate or negative closure actions (e.g. Cancel) in a form or dialog.

|Tertiary
|* Lower importance actions
* Especially in parts of the UI with less space, such as cards, or for repeated actions for items in lists, tables, etc.
* Caution: Can easily be mistaken for non-interactive text
|===

.Work In Progress
[NOTE]
====
The usage examples for this component are currently in progress. In the meantime, you can view the previous examples for the web component and the Java/Flow component.

[.buttons]
- https://vaadin.com/components/vaadin-button/html-examples[Web Component Examples]
- https://vaadin.com/components/vaadin-button/java-examples[Java Component Examples]
====
