---
title: Button
layout: tabbed-page
tab-title: Usage
page-links:
  - https://github.com/vaadin/vaadin-flow-components/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-button-flow}[Flow {moduleMavenVersion:com.vaadin:vaadin-button-flow}]
  - https://github.com/vaadin/vaadin-button/releases/tag/v{moduleNpmVersion:vaadin-button}[Web Component {moduleNpmVersion:vaadin-button}]
section-nav: incomplete
---

= Button

// tag::description[]
The Button component allows users to perform actions. 
// end::description[]
It comes in several different style variants, and supports icons in addition to text labels.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/button/button-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source,java]
// ----
// include::../../../../src/main/java/com/vaadin/demo/component/button/ButtonBasic.java[render,tags=snippet,indent=0,group=Java]
// ----

--

== Styles

The following variants can be used to distinguish between actions of different importance in the UI:

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/button/button-styles.ts[render,tags=snippet,indent=0,group=TypeScript]
----

--

[%header, cols="1,3a"]
|===
|Variant
|Usage recommendations

|Primary
|* The most important action in a view or part of a view.
* The main closure or continuation action (such as Save) in a form or dialog.
* Avoid presenting the user with more than one at any time.

|Secondary
|* Default style recommended for most actions.
* Alternate or negative closure actions (e.g. Cancel) in a form or dialog.

|Tertiary
|* Lower importance actions
* Especially in parts of the UI with less space, such as cards, or for repeated actions for items in lists, tables, etc.
* Caution: Can easily be mistaken for non-interactive text
|===

=== Danger / Error Variants

A special style for distinguishing actions related to dangers, warnings or errors.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/button/button-error.ts[render,tags=snippet,indent=0,group=TypeScript]
----

--

Use this style for:

* Dangerous actions, such as those that will lose or destroy data.
* Primary danger buttons should only be used when the dangerous action is the most likely action, such as the affirmative Delete action in a deletion confirmation dialog.
* Secondary and Tertiary variants can also be used for actions related to current errors (such as resolving them or viewing their details).

=== Size Variants

The following size variants are available for Button instances whose size needs to be different from the default:

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/button/button-sizes.ts[render,tags=snippet,indent=0,group=TypeScript]
----

--

[cols="1,3"]
|===
|Variant |Usage recommendations

|Large
|For especially important call-to-action buttons, where extra emphasis is needed.

|Normal
|Default size.

|Small
|Compact option for cramped parts of the UI, if a Tertiary variant is not deemed appropriate.
|===

.Default button size can be customized
[TIP]
Size variants should only be used in special cases. See <<../../foundation/size-space#size-and-space,Size and Space>> for details on how to change the default button size.

=== Miscellaneous Style Variants

The *Tertiary Inline* variant omits all white-space around the label, which is useful for embedding a Button as part of text content or another component. 
It should not be confused with a link:[Link], however.
// the link in the line above should not send the user anywhere

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/button/button-tertiary-inline.ts[render,tags=snippet,indent=0,group=TypeScript]
----

--


The *Success* and *Contrast* variants should provide additional color options for buttons.

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/button/button-success.ts[render,tags=snippet,indent=0,group=TypeScript]
----

--


[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/button/button-contrast.ts[render,tags=snippet,indent=0,group=TypeScript]
----

--


The *Tertiary + Contrast* combination should be avoided due to its similarity to non-interactive text elements.

.Default button colors can be customized
[TIP]
Note that the standard Button colors can be adjusted using <<../../foundation/color#,theme features>>, sho these variants should not be used to replace standard buttons just to achieve a different color.

== Buttons with icons

Buttons can have icons instead of text, or on either side in addition to text:

[.example]
--

[source,html]
----
include::{root}/frontend/demo/component/button/button-icons.ts[render,tags=snippet,indent=0,group=TypeScript]
----

--

Usage recommendations:

* *Use icons sparingly*. Most actions are difficult to reliably represent with icons, and the benefit of icons in addition to text should be weighed against the additional visual noise this creates.
* *Icon-only* buttons should be primarily used for *extremely common recurring actions* with highly standardized, universally understood icons (e.g. a cross for close), and for actions that are *repeated e.g. in lists and tables*.
* Icon-only buttons should provide a *textual alternative for screen readers* using the `aria-label` attribute.

.Icon-only button style variant
[NOTE]
Use the `icon` / `LUMO_ICON` theme variant on icon-only buttons to reduce the white space on either side of the icon.

.Work In Progress
[NOTE]
====
The usage examples for this component are currently in progress. In the meantime, you can view the previous examples for the web component and the Java/Flow component.

[.buttons]
- https://vaadin.com/components/vaadin-button/html-examples[Web Component Examples]
- https://vaadin.com/components/vaadin-button/java-examples[Java Component Examples]
====
