version: "3"

services:
  dspublisher:
    image: vaadin/dspublisher:latest
    working_dir: /docs-app
    environment:
      - DOCS_IMPORT_EXAMPLE_RESOURCES=${DOCS_IMPORT_EXAMPLE_RESOURCES:-}
      - DOCS_ARTICLES_PATH=${DOCS_ARTICLES_PATH:-}
      - DOCS_THEME_PATH=${DOCS_THEME_PATH:-}
      - DOCS_IMPORT_HEADER_IN_DEV=${DOCS_IMPORT_HEADER_IN_DEV:-}
      - DOCS_PATH_PREFIX=${DOCS_PATH_PREFIX:-}
      - DOCS_EXAMPLES_INCLUDE_URL_PREFIX=${DOCS_PATH_PREFIX:-}/vaadin/web-component/
      - DOCS_VAADIN_CONNECT_PREFIX=${DOCS_PATH_PREFIX:-}/connect
      - DOCS_TITLE=${DOCS_TITLE:-}
      - DOCS_VERSIONS_URL=${DOCS_VERSIONS_URL:-}
      - DOCS_SITE_URL=${DOCS_SITE_URL:-}
    command: "sh -c 'npm run dspublisher:build && rm -rf /out/public && cp -r /docs-app/public /out/'"
    volumes:
      - ~/.m2:/root/.m2
      - ..:/docs
      - ./out:/out
      - ~/.vaadin/proKey:/root/.vaadin/proKey

  docs:
    image: vaadin/dspublisher:latest
    working_dir: /docs
    command: "sh -c 'mvn -C clean package -DskipTests -Pproduction && rm -rf /out/*.jar && cp -r /docs/target/*.jar /out/docs.jar'"
    volumes:
      - ~/.m2:/root/.m2
      - ./out:/out
      - ..:/docs
