---
title: Custom Theme
description: The rendered UI examples within the documentation pages can use a custom theme, which is the same theme you would use for the applications you create using your design system.
order: 60
---


= Custom Theme for Rendered UI Examples

A theme for rendered UI examples is used from a Maven repository, such as Maven Central or a local repository. Once you've <<{articles}/styling/application-theme#,created an application theme>> and <<{articles}/styling/advanced/multi-app-themes#,packaged it as a JAR file>>, you can install it to a repository.

Once the theme is installed in a repository, you can use it by adding a dependency for it to the [filename]`pom.xml` in the documentation project's root folder:

.[filename]`pom.xml`
[source,xml]
----
<dependencies>
  ...
  <dependency>
    <groupId>com.example</groupId>
    <artifactId>exampletheme</artifactId>
    <version>1.0</version>
  </dependency>
</dependencies>
----

Next, the theme needs to be applied to the component examples. Change the <<{articles}/styling/application-theme/#applying-a-theme, `@Theme` annotation>> in `src/main/java/com/vaadin/demo/DemoExporter.java` as shown in the following:

.[filename]`src/main/java/com/vaadin/demo/DemoExporter.java`
[source,java]
----
@Theme("exampletheme")
public abstract class DemoExporter<T extends Component> extends WebComponentExporter<T> {
  ...
}
----

The website needs to be rebuilt -- or restarted in development mode -- in order for the change to take effect.

.Theme for UI Examples vs. Website Styling
[NOTE]
This page is about the theme used for rendered UI examples, which is distinct from the documentation website's styles covered in the <<customization#,Site Customization>> documentation.


[discussion-id]`28290DCF-3F92-4ECE-B72D-32641359C096`

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++