---
title: Overview
order: 10
---

= Design System Publisher

Design System Publisher is a tool for creating a documentation website for your own Vaadin-based design system, meaning the components, theme features, UI patterns and guidelines that your application UIs are composed of.

Having your own documentation website makes it easier for your developers and designers to keep track of the features available in your UI platform, what they look like, and how they can be used.

:commercial-feature-included: Design System Publisher is
:subscription-tiers: Prime and Enterprise
include::{root}/articles/_commercial-banner.asciidoc[]

The site's content format is https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[AsciiDoc], a lightweight markup language similar to MarkDown.
The system supports embedding live component samples, written in Java and/or TypeScript, directly into the pages.
The system can automatically provide code snippets for the samples for copy-pasting into code.

The default documentation content provided with the tool is a copy of the official <<{articles}/ds/overview#, Vaadin Design System documentation>>.
You can customize it to match your own UI features by plugging in your own <<{articles}/ds/customization/custom-theme#, custom theme>>, and by adding, removing, and editing the documentation and component samples.
