---
title: Getting Started
order: 20
---

= Getting Started With Design System Publisher

== Setting Up Your Environment

Before using the Design System Publisher tool, you'll need to have the necessary environment requirements set up.
On Windows the only supported environment is WSL2, due to Docker limitations on file change events for shared volumes (see <<troubleshooting#, Troubleshooting>> for details).

As the documentation contains a Vaadin project for rendering UI samples, JDK and Node.js are required.
See the <<{articles}/guide/install#, Installing>> instructions for setting up the environment for Vaadin projects.

The project is initialized using the `vaadin-cli` command line tool.
Follow the https://vaadin.com/labs/cli[installation instructions] to get the cli set up locally.

The CLI tool uses https://git-scm.com/[Git] to clone an initial copy of the documentation project so make sure to have Git installed.

Since the Design System Publisher tool runs within a Docker container, you need to have Docker (with `docker-compose`) installed to use the tool.
See the https://docs.docker.com/get-docker/[Docker installation guide] for instructions for setting it up.


== Create a New Project

Run the following command to create a new design system website project:

[source,terminal]
----
vaadin ds-init
----

include::{root}/articles/guide/_terminal.asciidoc[]

The tool asks for a name for your design system, which is used for things like the visible page title, and a folder name for the website project.

The initialization script should take about a minute to finish.
Once done, you should have the website project in your current working directory.
The project uses Git for version control.
After the initialization process is finished, the repository has some file changes that you should look into, possibly edit and once you're happy with the changes commit them:

----
my-docs
├── articles/ds/
│   ├──404.asciidoc      <1>
│   ├──index.asciidoc    <2>
│   └──components/foundation
│      └──index.asciidoc <3>
├── dspublisher/
│   ├──docs-theme        <4>
│   └──.env              <5>
└── LICENSE              <6>
----
<1> The 404 (not found) -page content
<2> The front page content
<3> The two main sections have an addition in the front matter to have them expanded by default in the side menu
<4> The custom theme for the documentation application. See <<customization#,Site Customization>> for more information
<5> A set of environment variables used by the Design System Publisher. See <<customization#settings,Settings>> for more information
<6> The project license file


== Folder Structure

The folder structure generated by the initialization script is as follows:

----
my-docs             <1>
├── articles/       <2>
├── frontend/       <3>
├── src/main/java/  <4>
├── dspublisher/    <5>
└── pom.xml         <6>
----
<1> The root folder name is the short name provided to the initialization script
<2> Page content in AsciiDoc files
<3> TypeScript component samples
<4> Java component samples
<5> Website configuration
<6> Maven POM for theme and component dependencies
