---
tab-title: Usage
layout: tabbed-page
title: Master Detail Layout
page-title: Master Detail component | Vaadin components
description: Master Detail Layout is a component with with a master (or primary) area and a detail (or secondary) area.
meta-description: Learn to create layouts in your Vaadin application with the Master Detail Layout component.
version: since:com.vaadin:vaadin@V24.8
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/split-layout}/#/elements/vaadin-split-layout[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/splitlayout/SplitLayout.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/split-layout}/packages/split-layout[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-split-layout-flow-parent[Java]'
---

= Master Detail Layout

:preview-feature: Master Detail Layout
:feature-flag: com.vaadin.experimental.masterDetailLayoutComponent
include::{articles}/_preview-banner.adoc[opts=optional]

// tag::description[]
Master Detail Layout is component for building UIs with a master (or primary) area and a detail (or secondary) area that is displayed next to, or overlaid on top of, the master area, depending on configuration and viewport size.
// end::description[]

++++
<style>
.example.render-only iframe {
  height: 500px;
}
</style>
++++

include::{articles}/components/_shared.adoc[tag=merge-examples]
include::{articles}/components/_shared.adoc[tag=scaled-examples]

[.example.render-only.merge]
--
[source,typescript]
----
include::include::{root}/frontend/demo/component/master-detail-layout/react/master-detail-layout-basic.tsx[render,frame]
----
--

[.example]
--
ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/masterdetaillayout/MasterDetailLayoutBasic.java[tags=snippet,indent=0,group=Flow]
----
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/masterdetaillayout/PersonList.java[indent=0,group=Flow]
----
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/masterdetaillayout/PersonDetail.java[indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/master-detail-layout/react/master-detail-layout-basic.tsx[tags=snippet,indent=0,group=React]
----
[source,tsx]
----
include::{root}/frontend/demo/component/master-detail-layout/react/PersonList.tsx[indent=0,group=React]
----
[source,tsx]
----
include::{root}/frontend/demo/component/master-detail-layout/react/PersonDetail.tsx[indent=0,group=React]
----
endif::[]
--

== Orientation

Master Detail Layout can be configured to use vertical orientation. It changes the way how master and
detail area are placed next to each other.

[.example.render-only.merge]
--
[source,typescript]
----
include::{root}/frontend/demo/component/master-detail-layout/react/master-detail-layout-vertical.tsx[render,frame]
----
--

[.example]
--

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/masterdetaillayout/MasterDetailLayoutVertical.java[tags=snippet,indent=0,group=Flow]
----
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/masterdetaillayout/PersonList.java[indent=0,group=Flow]
----
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/masterdetaillayout/PersonDetail.java[indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/master-detail-layout/react/master-detail-layout-vertical.tsx[tags=snippet,indent=0,group=React]
----
[source,tsx]
----
include::{root}/frontend/demo/component/master-detail-layout/react/PersonList.tsx[indent=0,group=React]
----
[source,tsx]
----
include::{root}/frontend/demo/component/master-detail-layout/react/PersonDetail.tsx[indent=0,group=React]
----
endif::[]
--

== Responsiveness

[.example]
--
ifdef::flow[]
[source,Java]
----
layout.setMasterMinSize("600px");
layout.setDetailSize("300px");
layout.setStackThreshold("600px");
----
endif::[]
ifdef::react[]
[source,tsx]
----
<MasterDetailLayout
  masterMinSize="600px"
  detailSize="300px"
  stackThreshold="600px"
/>
----
endif::[]
--

== Overlay mode

You can enforce the overlay mode to be always used by the specific layout:

[.example]
--
ifdef::flow[]
[source,Java]
----
layout.setForceOverlay(true);
----
endif::[]
ifdef::react[]
[source,tsx]
----
<MasterDetailLayout forceOverlay />
----
endif::[]
--

== Containment mode

The detail overlay (in overlay or stack modes) can be configured to render only over the master area, or over the entire viewport by specifying corresponding containment:

[.example]
--
ifdef::flow[]
[source,Java]
----
layout.setContainment(MasterDetailLayout.Containment.VIEWPORT);
----
endif::[]
ifdef::react[]
[source,tsx]
----
<MasterDetailLayout containment="viewport" />
----
endif::[]
--

== Router Integration

Master Detail Layout can be used either as the application's root layout or as a nested layout.
It is also possible to have multiple Master Detail Layout nested within each other.

[.example.show-code]
--

[source,java]
----
<source-info group="Flow"></source-info>
// Category view with a list of products as the master area
@Route("category/:categoryName")
public class CategoryView extends MasterDetailLayout { ... }

// Product view rendered inside the category view detail area
@Route(value = "category/:categoryName/product/:productId", layout = CategoryView.class)
public class ProductView extends VerticalLayout { ... }
----
--
