---
tab-title: Usage
layout: tabbed-page
title: Master Detail Layout
page-title: Master Detail component | Vaadin components
description: Master Detail Layout is a component with with a master (or primary) area and a detail (or secondary) area.
meta-description: Learn to create layouts in your Vaadin application with the Master Detail Layout component.
version: since:com.vaadin:vaadin@V24.8
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/split-layout}/#/elements/vaadin-split-layout[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/splitlayout/SplitLayout.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/split-layout}/packages/split-layout[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-split-layout-flow-parent[Java]'
---


= Master Detail Layout

// tag::description[]
Master Detail Layout is component for building UIs with a master (or primary) area and a detail (or secondary) area that is displayed next to, or overlaid on top of, the master area, depending on configuration and viewport size.
// end::description[]

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/master-detail-layout/master-detail-layout-basic.ts[render,tags=snippet;snippethtml,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/masterdetaillayout/MasterDetailLayoutBasic.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/master-detail-layout/react/master-detail-layout-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

== Orientation

Master Detail Layout can be configured to use vertical orientation. It changes the way how master and
detail area are placed next to each other.

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/master-detail-layout/master-detail-layout-vertical.ts[render,tags=snippet;snippethtml,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/masterdetaillayout/MasterDetailLayoutVertical.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/master-detail-layout/react/master-detail-layout-vertical.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

== Size Properties

You can provide fixed size on master and detail areas using corresponding API.

[.example]
--
ifdef::lit[]
[source,html]
----
<vaadin-master-detail-layout
  master-size="600px"
  detail-size="300px"
></vaadin-master-detail-layout>
----
endif::[]
ifdef::flow[]
[source,Java]
----
layout.setMasterSize("600px");
layout.setDetailSize("300px");
----
endif::[]
ifdef::react[]
[source,tsx]
----
<MasterDetailLayout masterSize="300px" detailSize="300px" />
----
endif::[]
--

== Overlay mode

// TODO live example

You can enforce the overlay mode to be always used by the specific layout:

[.example]
--
ifdef::lit[]
[source,html]
----
<vaadin-master-detail-layout
  force-overlay
></vaadin-master-detail-layout>
----
endif::[]
ifdef::flow[]
[source,Java]
----
layout.setForceOverlay(true);
----
endif::[]
ifdef::react[]
[source,tsx]
----
<MasterDetailLayout forceOverlay />
----
endif::[]
--


== Stack mode

[.example]
--

ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/master-detail-layout/master-detail-layout-stack.ts[render,tags=snippet;snippethtml,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/masterdetaillayout/MasterDetailLayoutStack.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/master-detail-layout/react/master-detail-layout-stack.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Containment mode

The detail overlay (in overlay or stack modes) can be configured to render only over the master area, or over the entire viewport by specifying corresponding containment:

[.example]
--
ifdef::lit[]
[source,html]
----
<vaadin-master-detail-layout
  containment="viewport"
></vaadin-master-detail-layout>
----
endif::[]
ifdef::flow[]
[source,Java]
----
layout.setContainment(MasterDetailLayout.Containment.VIEWPORT);
----
endif::[]
ifdef::react[]
[source,tsx]
----
<MasterDetailLayout containment="viewport" />
----
endif::[]
--


== Router Integration

Master Detail Layout can be used either as the application's root layout or as a nested layout.
It is also possible to have multiple Master Detail Layout nested within each other.

// TODO React code example

[.example.show-code]
--

[source,java]
----
<source-info group="Flow"></source-info>
// Category view with a list of products as the master area
@Route("category/:categoryName")
public class CategoryView extends MasterDetailLayout { ... }

// Product view rendered inside the category view detail area
@Route(value = "category/:categoryName/product/:productId", layout = CategoryView.class)
public class ProductView extends VerticalLayout { ... }
----
--
