---
tab-title: Usage
layout: tabbed-page
title: Time Picker
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/time-picker}/#/elements/vaadin-time-picker[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/timepicker/TimePicker.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/time-picker}/packages/time-picker[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-time-picker-flow-parent[Java]'
---


= Time Picker

:experimental:

// tag::description[]
Time Picker is an input field for entering or selecting a specific time.
// end::description[]

[.example]
--
[source,html]
----
include::{root}/frontend/demo/component/timepicker/time-picker-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/timepicker/TimePickerBasic.java[render,tags=snippet,indent=0,group=Java]
----
--

The time can be entered directly using a keyboard or by choosing a value from a set of predefined options presented in an overlay. The overlay opens when the field is clicked or any input is entered when the field is focused.


== Step

Time Picker's step parameter defines the interval in seconds between the items displayed in the overlay. It also specifies the amount by which the time increases or decreases using the kbd:[Up]/kbd:[Down] arrow keys -- when the overlay is disabled.

The default step is one hour (i.e., `3600` seconds). Unlike <<../number-field#,Number Field>>, Time Picker accepts values that don't align with the specified step.

[.example]
--
[source,html]
----
include::{root}/frontend/demo/component/timepicker/time-picker-minutes-step.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/timepicker/TimePickerMinutesStep.java[render,tags=snippet,indent=0,group=Java]
----
--

.Use Common Steps
[NOTE]
A step must divide an hour or day, evenly. For example, _"15 minutes"_, _"30 minutes"_ are valid steps for an hour, and _"2 hours"_ is a valid step for a day, whereas _"42 minutes"_ isn't valid for either.

The displayed time format changes based on the step.

[.example]
--
[source,html]
----
include::{root}/frontend/demo/component/timepicker/time-picker-seconds-step.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/timepicker/TimePickerSecondsStep.java[render,tags=snippet,indent=0,group=Java]
----
--

// Allow FFF
pass:[<!-- vale Vaadin.Abbr = NO -->]

|===
|Step |Format

|Less than 60 seconds.
|HH:MM:SS

|Less than 1 second.
|HH:MM:SS:FFF
|===

pass:[<!-- vale Vaadin.Abbr = YES -->]

.Limit the Number of Steps
[NOTE]
The overlay doesn't appear for steps less than 900 seconds (i.e., 15 minutes), to avoid showing an impractical number of choices.



== Auto Open

The overlay opens automatically when the field is focused using a pointer (i.e., mouse or touch), or when the user types in the field. You can disable this so that the overlay opens only when the toggle button or the kbd:[Up]/kbd:[Down] arrow keys are pressed.

[.example]
--
[source,html]
----
include::{root}/frontend/demo/component/timepicker/time-picker-auto-open.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/timepicker/TimePickerAutoOpen.java[render,tags=snippet,indent=0,group=Java]
----
--



== Validation

=== Minimum & Maximum Value

You can define a minimum and maximum value for Time Picker if you need to restrict the input to a specific range:

[.example]
--
[source,html]
----
include::{root}/frontend/demo/component/timepicker/time-picker-min-max.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/timepicker/TimePickerMinMax.java[render,tags=snippet,indent=0,group=Java]
----
--


=== Custom Validation

If the minimum and maximum values aren't sufficient for validation, you can also apply custom validation.

[.example]
--
[source,html]
----
include::{root}/frontend/demo/component/timepicker/time-picker-custom-validation.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/timepicker/TimePickerCustomValidation.java[render,tags=snippet,indent=0,group=Java]
----
--


// Basic Features

include::{articles}/components/_input-field-common-features.adoc[tags=basic-intro;label;helper;placeholder;tooltip;clear-button;prefix]

[.example]
--
[source,typescript]
----
include::{root}/frontend/demo/component/timepicker/time-picker-basic-features.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/timepicker/TimePickerBasicFeatures.java[render,tags=snippet,indent=0,group=Java]
----
--


// Readonly and disabled

include::{articles}/components/_input-field-common-features.adoc[tag=readonly-and-disabled]

[.example]
--
[source,typescript]
----
include::{root}/frontend/demo/component/timepicker/time-picker-readonly-and-disabled.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/timepicker/TimePickerReadonlyAndDisabled.java[render,tags=snippet,indent=0,group=Java]
----
--


// Style Variants

include::{articles}/components/_input-field-common-features.adoc[tags=styles-intro;text-alignment;small-variant;helper-above-field;borders]

[.example]
--
[source,typescript]
----
include::{root}/frontend/demo/component/timepicker/time-picker-styles.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/timepicker/TimePickerStyles.java[render,tags=snippet,indent=0,group=Java]
----
--


== Best Practices

Use Time Picker when the user needs to choose a time of day. Don't use it for durations, such as for a stopwatch or timer.



== Related Components


[cols="1,2"]
|===
|Component |Usage Recommendation

|<<../date-picker#,Date Picker>>
|Input field for entering or selecting a specific date.

|<<../date-time-picker#,Date Time Picker>>
|Input field for entering or selecting a specific date and time.
|===


[discussion-id]`299E8D5A-A465-4F72-A029-BB24A4902CD3`
