---
title: Overview
order: 1
layout: page
---

[[application.overview]]
= Creating a Flow Application

Continuing from the introduction given in <<../../guide/introduction/introduction-overview#, Introduction>>, this chapter gives a more thorough and a more practical overview of Vaadin application basics.
The various topics in this chapter are described in more detail throughout the further documentation.

The basic elements of a typical application are:

* Views
* Navigation
* Binding views to data
* Service layer
* Backend connectivity
* Authentication and authorization
* Progressive web application (PWA) features

Some of the topics are described in detail in other chapters.

////
TODO V15+
All of the basic elements can be handled both in the Java and TypeScript API.
You can also combine the models.
////

////
TODO
== Starter Applications

The starter and example applications downloadable from https://vaadin.com/start[vaadin.com/start] should offer good starting points for building your application.
////