---
title: End-to-end testing
order: 130
page-title: "Running end-to-end browser tests with Vaadin TestBench"
description: Learn how to do full-stack tests on a Flow application using Vaadin TestBench.
---

= Testing Vaadin Applications in the Browser with End-To-End Tests

End-to-end (e2e) tests are used to test the entire application.
They are far more coarse-grained than unit or integration tests.
This makes them well suited to checking that the application works as a whole, and catching any regressions that may be missed by more specific tests.

End-to-end tests are executed in a browser window. Vaadin TestBench controls browser window using Selenium WebDriver.


.Vaadin TestBench is a commercial product
[NOTE]
====
The end-to-end tests in this tutorial use https://vaadin.com/testbench[Vaadin TestBench], which is a commercial tool that's a part of the Vaadin Pro Subscription.
You can get a free trial at https://vaadin.com/trial.
All Vaadin Pro tools and components are free for students through the https://education.github.com/pack[GitHub Student Developer Pack]. If you need an open source alternative for TestBench, you can approach similar results also with plain https://www.selenium.dev[Selenium WebDriver] or https://playwright.dev[Playwright].
====


== Creating the Base Test Class

Vaadin TestBench contains handy base classes that you can use aa a bases for your e2e tests.
The JUnit5 version is called `BrowserTestBase`.
It can be used alone if you orchestrate starting and stopping your server, with for example a Maven executions in `pre-integration-test` and `posot-integration-test` and execute the actual test in integration test phase.
In Spring Boot applications, it is easier to use the same @SpringBootTest annotation that you already used in the previous phase to ensure a running server during the browser test execution.

Create a new class, [classname]`LoginE2ETest` in the `com.example.application.it` package.
Be sure to place it in `src/test/java` and not `src/main/java`.


.`LoginE2ETest.java`
[source,java]
----
package com.example.application.it;

import com.vaadin.flow.component.login.testbench.LoginFormElement;
import com.vaadin.testbench.BrowserTest;
import com.vaadin.testbench.BrowserTestBase;
import com.vaadin.testbench.annotations.RunLocally;
import com.vaadin.testbench.parallel.Browser;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.env.Environment;

import static org.junit.jupiter.api.Assertions.assertFalse;

//@RunLocally(Browser.FIREFOX) // <1>
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT) 
public class LoginE2ETest extends BrowserTestBase { // <2> 

    @Autowired
    Environment env;

    static {
        // Prevent Vaadin Development mode to launch browser window
        System.setProperty("vaadin.launch-browser", "false"); 
    }

    @BeforeEach
    void openBrowser() {
        getDriver().get("http://localhost:" +
            env.getProperty("local.server.port") + "/"); // <3>
    }
    
    @BrowserTest // <4>
    public void loginAsValidUserSucceeds() {
        // Find the LoginForm used on the page, using a
        // typed selector API provided by TestBench
        LoginFormElement form = $(LoginFormElement.class).first();
        // Enter the credentials and log in
        form.getUsernameField().setValue("user");
        form.getPasswordField().setValue("password");
        form.getSubmitButton().click();

        // Behind the scenes TestBench uses lower level WebDriver API
        // Here we can configure it on the fly
        getDriver().manage().timeouts().implicitlyWait(Duration.of(1, ChronoUnit.SECONDS));
        // Here finding an element on the actual main layout (after login),
        // using pure WebDriver API, BTW. There is also AppLayoutElement for TB
        getDriver().findElement(By.tagName("vaadin-app-layout"));

        // Ensure the login form is no longer visible
        assertFalse($(LoginFormElement.class).exists());
    }

}
----
<1> This optional annotation specifies the test to be run on the local machine and using Firefox. 
The default is Chrome.
<2> The super class `BrowserTestBase` provides handy helper methods and configures TestBench.
<3> The `openBrowser` method is annotated to be executed before each actual tests.
The URL points to local test server with the random port SpringBootTest has selected.
The browser should be automatically redirected to the login screen.
<4> BrowserTest annotation is a TestBench extension of the better known `Test` annotation, that is handy if you decide to extend your end-to-end tests to cover multiple browsers at some point.

Right-click [classname]`LoginE2ETest.java` and select *Run 'LoginE2ETest'*.

The first time you run the test, you're asked to start a trial or to validate your existing license.
Follow the instructions in the browser window that opens.

== Creating a View Object

You can now add a second test: validating that you can't log in with an invalid password.

For this test, you need to write the same code to access the components in the view as you did for the first test.
To make your tests more maintainable, you can create a view object (otherwise known as a call page object or element class) for each view.
A view object provides a high-level API to interact with the view and hides the implementation details.

For the login view, create the [classname]`LoginViewElement` class in a new package, `com.example.application.it.elements`:

.`LoginViewElement.java`
[source,java]
----
package com.example.application.it.elements;

import com.vaadin.flow.component.login.testbench.LoginFormElement;
import com.vaadin.flow.component.orderedlayout.testbench.VerticalLayoutElement;
import com.vaadin.testbench.annotations.Attribute;
import org.openqa.selenium.By;

import java.time.Duration;
import java.time.temporal.ChronoUnit;
import java.util.concurrent.TimeUnit;

@Attribute(name = "class", contains = "login-view")
public class LoginViewElement extends VerticalLayoutElement {

    public boolean login(String username, String password) {
        LoginFormElement form = $(LoginFormElement.class).first();
        form.getUsernameField().setValue(username);
        form.getPasswordField().setValue(password);
        form.getSubmitButton().click();

        try {
            getDriver().manage().timeouts().implicitlyWait(Duration.of(1, ChronoUnit.SECONDS));
            getDriver().findElement(By.tagName("vaadin-app-layout"));
            return true;
        } catch (Exception e) {
            return false;
        }
    }

}----

.Class hierarchies must match
[CAUTION]
====
To make the correct functionality available from superclasses, the hierarchy of the view object should match the hierarchy of the view (`public class LoginView extends VerticalLayout` vs `public class LoginViewElement extends VerticalLayoutElement`).
====

Adding the `@Attribute(name = "class", contains = "login-view")` annotation allows you to find the [classname]`LoginViewElement` using the TestBench query API, for example:

.Finding a LoginViewElement using the TestBench query API
[source,java]
----
LoginViewElement loginView = $(LoginViewElement.class).onPage().first();
----

The annotation searches for the `login-view` class name, which is set for the login view in the constructor.
The [methodname]`onPage()` call ensures that the whole page is searched.
By default, a `$` query starts from the active element.

Now that you have the [classname]`LoginViewElement` class, you can simplify your [methodname]`loginAsValidUserSucceeds()` test to be:

.`LoginE2ETest.java`
[source,java]
----
@BrowserTest
public void loginAsValidUserSucceeds() {
    LoginViewElement loginView = $(LoginViewElement.class).onPage().first();
    assertTrue(loginView.login("user", "password"));
}
----

Add a test to use an invalid password as follows:

.`LoginE2ETest.java`
[source,java]
----
@BrowserTest
public void loginAsInvalidUserFails() {
    LoginViewElement loginView = $(LoginViewElement.class).onPage().first();
    assertFalse(loginView.login("user", "invalid"));
}
----

Continue testing the other views by creating similar view objects and IT classes.

If you are building a large application, it probably makes sense to make slower end-to-end tests executed only when requested separately. You can do this with for example using https://maven.apache.org/surefire/maven-failsafe-plugin/[Maven Failsafe plugin] or using the https://junit.org/junit5/docs/current/user-guide/#writing-tests-tagging-and-filtering[tagging feature in JUnit 5].

The next chapter covers how to make a production build of the application and deploy it to a cloud platform.

include::{root}/articles/tutorial/_ebook-banner.adoc[opts=optional]


[discussion-id]`0DDF0F9E-DCF0-4AEC-9DD4-C241699CC7F7`
