---
title: Production Deployment
order: 160
page-title: "Deploying a Vaadin Flow Application on Heroku"
description: Learn how to prepare a Vaadin application for production and to deploy it on Heroku.
---

= Deploying a Vaadin Flow Application on Heroku

In this final chapter in the series, you learn how to deploy a Spring Boot application on https://heroku.com[Heroku].

This chapter covers:

* Vaadin production builds.
* Configuring PostgreSQL for production.
* Creating a Heroku account.
* Installing the Heroku CLI.
* Creating and deploying a Heroku application.


.Vaadin can be deployed on any cloud provider
[TIP]
You can also deploy your application onto other cloud platforms.
Read the <<{articles}/production/cloud-providers#, Cloud Deployment tutorials>> for more options.

include::_heroku-steps.adoc[]

== Conclusion and Next Steps

Congratulations.
You have now built a full-stack PWA and deployed it to Heroku.

Did you like the tutorial?
Did you find anything that did not seem right?
Reach out to me on Twitter https://twitter.com/marcushellberg[@marcushellberg] or https://discord.gg/vaadin[Vaadin's Discord chat] server.

Now that you have a running application, you can use it to experiment further or as a foundation for your next idea.

Happy hacking, and ping us https://twitter.com/vaadin[@vaadin] on Twitter to show off the cool stuff you have built.

=== Helpful Links

- https://github.com/vaadin-learning-center/crm-tutorial[Source code GitHub repository]
- https://discord.gg/vaadin[Vaadin Discord chat]
- https://stackoverflow.com/questions/ask?tags=vaadin[Stack Overflow]
- <<{articles}/overview#,Flow documentation>>
- <<{articles}/components#,Vaadin components>>
- https://vaadin.com/comparison[Compare Vaadin with React, Angular, and Vue]

include::{root}/articles/tutorial/_ebook-banner.adoc[opts=optional]


[discussion-id]`01A3D231-9D1B-4D4D-A6BB-CB4D37E01CBE`
