[discrete]
==== Lit Templates Use Lit 2

Previously, Lit templates were based on LitElement 2.x and lit-html 1.x.
New Lit 2.0 (which includes LitElement 3.x and lit-html 2.x) is used for Lit templates in the latest Vaadin version.
Some changes are required to be able to use your existing template with Lit 2.0.
Please refer to the https://lit.dev/docs/releases/upgrade/#update-packages-and-import-paths[Lit Upgrade Guide] to find all the necessary changes.
Most of the necessary changes are with imports.

Use the `lit` package.
For example, change imports of `html` and [classname]`LitElement` from:

[source, typescript]
----
import { html, LitElement } from 'lit-element';
----

to:

[source, typescript]
----
import { html, LitElement } from 'lit';
----

Update decorator imports.
Decorators have been moved to a separate module.
For example, change `customElement` and `property` decorator imports from:

[source, typescript]
----
import { customElement, property } from 'lit-element';
----

to:

[source, typescript]
----
import { customElement, property } from 'lit/decorators.js';
----

Update directive imports from:

[source, typescript]
----
import { repeat } from 'lit-html/directives/repeat.js';
----

to:

[source, typescript]
----
import { repeat } from 'lit/directives/repeat.js';
----

Some Lit APIs have been renamed.
The most noticeable change is that the `@internalProperty` decorator has been renamed to `@state`.

[discrete]
==== The Vaadin Web Components No Longer Support <template>

The Vaadin Web Components no longer support `<template>` to render content.
Please, use renderer functions instead.
Alternatively, you can use the `@vaadin/vaadin-template-renderer` package which is created to maintain backward compatibility.

[discrete]
===== Installation

Install `vaadin-template-renderer` as follows:

[source,terminal]
----
npm i @vaadin/vaadin-template-renderer --save
----

Import `vaadin-template-renderer` before any other components:

[source, typescript]
----
import '@vaadin/vaadin-template-renderer';
----

[discrete]
===== Deprecation Warning

By default, `vaadin-template-renderer` shows a deprecation warning when `<template>` is used with a component.

To suppress the warning, add the `suppress-template-warning` attribute to the component:

[source,html]
----
<vaadin-combo-box suppress-template-warning>
    <template>
        Content
    </template>
</vaadin-combo-box>
----
