= Autoscaling

There are three different types of autoscaling possible:

- The Horizontal Pod Autoscaler
- The Vertical Pod Autoscaler
- The Cluster Autoscaler

== Horizoncal Pod Autoscaler

The https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)[Horizontal Pod Autoscaler] controls the scale of a Deployment and its ReplicaSet.
It is implemented as a Kubernetes API resource and a controller and cannot be deployed with this Terraform.
It is usually deployed together with the application as scaling is dependent on the load requirements of the application.

There is a https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/[walkthrough example] of using horizontal pod autoscaling.

== Vertical Pod Autoscaler

The https://learn.microsoft.com/en-us/azure/aks/vertical-pod-autoscaler[Vertical Pod Autoscaler] tries to automatically set resource requests and limits on running containers based on past usage.

== Cluster Autoscaler

The https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler[Azure Cluster Autoscaler] component can watch for pods in your cluster that can't be scheduled because of resource constraints.
When issues are detected, the number of nodes in a node pool is increased to meet the application demand.

To enable autoscaling with Terraform you need to set up variables in [filename]`variables.tf` file:

- enable_auto_scaling: true
- min_count: Minimum number of nodes in cluster
- max_count: Maximum number of nodes in cluster

NOTE: By default there are quotas in Azure on how many specific type resources you can have.
For example vCPU amounts can be limited to as low as 10 per subscription.
This will limit the cluster size unless you increase the quota.
These limits can usually be increased in the portal https://learn.microsoft.com/en-us/azure/quotas/per-vm-quota-requests[Quotas] section.

You can find more info about Microsoft Azure subscription limit on https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits[Azure subscription and service limits, quotas, and constraints] page.

== Set Resource Requests and Limits

This is different for Vertical Pod Autoscaling.

For scaling to work better you should use resource requests and limits in your application deployments.
There are lots of best practices guides out there, and it really depends on your application what is the best.
Read more on https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[Resource Management for Pods and Containers] page.

For example:
[source,yaml]
----
containers:
- name: prodcontainer1
  image: ubuntu
  resources:
    requests:
      memory: “64Mi”
      cpu: “300m”
    limits:
      memory: “128Mi”
----

Links:

- https://www.containiq.com/post/setting-and-rightsizing-kubernetes-resource-limits[Setting and rightsizing Kubernetes resource limits]
- https://home.robusta.dev/blog/kubernetes-memory-limit[Kubernetes memory limits]
- https://home.robusta.dev/blog/stop-using-cpu-limits[Stop using CPU limits]
