---
title: Configuration
description: Configuration options for Azure Kit.
order: 20
---

= Configuring Azure Kit

== Include and Exclude Packages to be Inspected During Serialization

When the session is serialized, Azure Kit will inspect
classes for transient fields that can be injected during
deserialization (see <<{articles}/tools/azure/session-replication,session replication>>).

Azure Kit provides two properties to limit the packages
to be inspected. The `include-package` property
defines all the packages that should be inspected. If this
is undefined, all packages are assessed. For this
reason, it is recommended that you specify the top-level
package for your application in the `include-packages`
property.

The `exclude-package` property lists packages that should
not be assessed.

[.example]
--
.application.properties
[source,properties]
----
vaadin.serialization.include-packages=com.example.application
vaadin.serialization.exclude-packages=com.example.application.service
----

.application.yaml
[source,yaml]
----
vaadin:
  serialization:
    include-packages: com.example.application
    exclude-packages: com.example.application.service
----
--

== Use Hazelcast for Session Replication

The `service-name` property defines the name of the Hazelcast
service deployment within the cluster.

The optional `namespace` property is used when the Hazelcast
service is deployed in a namespace other than `default`.

[.example]
--
.application.properties
[source,properties]
----
vaadin.azure.hazelcast.kubernetes.service-name=hazelcast-service
vaadin.azure.hazelcast.kubernetes.namespace=namespace
----

.application.yaml
[source,yaml]
----
vaadin:
  azure:
    hazelcast:
      kubernetes:
        service-name: hazelcast-service
        namespace: namespace
----
--

== Use Redis for Session Replication

This property defines the name of the Redis service
deployment within the cluster.

[.example]
--
.application.properties
[source,properties]
----
spring.redis.host: redis-service
----

.application.yaml
[source,yaml]
----
spring:
  redis:
    host: redis-service
----
--
