---
title: Getting Started
description: Step-by-step guide showing how to use the Azure Kit to deploy your application to Azure Cloud
order: 10
---

= Getting Started with Azure Kit
:sectnums:

Azure Kit lets you quickly deploy your Vaadin application to Microsoft's Azure Cloud.
Azure Kit is based on Kubernetes Kit, which means that all the features of Kubernetes Kit are also available in Azure Kit.

The Azure Kit includes a set of Terraform blueprints that helps you to deploy your application to Azure Cloud, specifically to Azure Kubernetes Service (AKS).
Terraform is an open-source infrastructure as code (IaC) software tool that provides a consistent CLI workflow that allows you to safely and predictably create, change, and improve your cloud infrastructure.

== Prerequisites

To use the Azure Kit, you need the following:

- Azure subscription
- https://www.terraform.io/downloads[Terraform]
- https://learn.microsoft.com/en-us/cli/azure/install-azure-cli[Azure CLI]

== Download the Azure Kit

Download the Azure Kit from https://github.com/vaadin/kubernetes-kit[github.com/vaadin/kubernetes-kit] and unzip it to a local folder.

== Configure Azure CLI

To start, you need to use Azure CLI from a terminal to login to your Azure account and select the Azure subscription you want to use for your deployment.

. Login to Azure
[source,terminal]
az login
. Select the Azure subscription you want to use for your deployment
[source,terminal]
az account set --subscription <SUBSCRIPTION_ID>
. Verify that you are logged in and the correct subscription is selected
[source,terminal]
az account show

== Prepare environment for Terraform state

To use the Azure Kit, you need to create a storage account and a container for Terraform state.
Terraform state is used to keep track of the resources that have been created.
Terraform uses this information to determine what changes need to be made when you run the `terraform apply` command, which is used to deploy your application to Azure.

The Azure Kit provides a script, `create_terraform_storage.sh`, that creates a storage account and a container for Terraform state for you in the Azure subscription you selected.

To run the script, open a terminal and navigate to the folder where you unzipped the Azure Kit.
Then run:
[source,terminal]
create_terraform_storage.sh

The output of the script contains the name of the storage account, `storageaccount`. This name is randomly generated and unique for your Azure subscription. You need to use this name in the next step. So, make sure you save the `storageaccount` value.
    
== Initialize terraform

Next, you need to initialize the directory where you unzipped the Azure Kit as a Terraform working directory.
To do this, open a terminal and navigate to the folder where you unzipped the Azure Kit.
Then run:

[source,terminal]
terraform init

Terraform will then download the Azure provider and other required plugins.
During the initialization, Terraform will ask you to provide the name of the storage account that you created in the previous step.

[source,terminal]
----
    Initializing modules...
    - acr in modules/acr
    - aks in modules/aks
    - keyvault in modules/keyvault
    - network in modules/network

    Initializing the backend...
    storage_account_name
    The name of the storage account.
    
    Enter a value: <enter storageaccount name>

    Successfully configured the backend "azurerm"! Terraform will automatically
    use this backend unless the backend configuration changes.

    Initializing provider plugins...
    ...
----

== Customize Terraform for your setup

The Azure Kit stores all the configuration that defines your deployment in two files, [filename]`variables.tf` and [filename]`settings.tf`. 
You will find these files in the root folder of the Azure Kit.

The [filename]`variables.tf` file contains most the variables that describe the deployment. These variables include:
- The name of your application and the name of your environment
- The Azure region where you want to deploy your application
- The number of nodes in your Kubernetes cluster
- The size of the nodes
- etc.


The [filename]`settings.tf` file contains the network settings for your deployment.


[filename]`variables.tf` and [filename]`settings.tf` are already populated with default values.
But you can customize these files to match your needs.

== Run `terraform plan`

Before you deploy your application to Azure, you should run the `terraform plan` command to see what resources will be created.
This command will not create any resources, but it will show you what resources will be created if you run the `terraform apply` command.
This is a good way to verify that the configuration is correct and that you are happy with the resources that will be created.

[source,terminal]
terraform plan -out=plan.out

Verify the output on screen and proceed if proposed setup is good.

== Run `terraform apply`
    
When you are happy with the output of the `terraform plan` command, you can run the `terraform apply` command to deploy your application to Azure.
This command will create all the resources that are defined in the [filename]`variables.tf` and [filename]`settings.tf` files.

[source,terminal]
----
    $ terraform apply "plan.out"
    azurerm_resource_group.resource_group: Creating...
    ...
    Apply complete! Resources: 8 added, 0 changed, 0 destroyed.
----


== Use kubectl to connect to created kubernetes cluster

To connect to the Kubernetes cluster that was created by the Azure Kit, you need to use the `kubectl` command.

[source,terminal]
----
    $ export KUBECONFIG="./kubeconfig"
    $ kubectl get nodes
    NAME                               STATUS   ROLES   AGE     VERSION
    aks-nodepool-31060480-vmss000000   Ready    agent   3m   v1.23.12
    aks-nodepool-31060480-vmss000001   Ready    agent   3m   v1.23.12
----

In order to get the ingress ip, you should use the following command:

[source,terminal]
----
    $ kubectl -n kube-system get service ingress-nginx-controller 
    NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                      AGE
    ingress-nginx-controller             LoadBalancer   10.240.97.40    a.b.c.d   80:30799/TCP,443:31928/TCP   106m
----

== Cleanup terraform deployed items


If you want to remove all the resources that were created by the Azure Kit, you can run the `terraform destroy` command.
[source,terminal]
terraform destroy

You need to remove the storageccount and resourcegroup "Terraform-ResourceGroup" created by sh script manually from Azure portal.

[discussion-id]`3EFFB1E4-FEF7-4836-90A4-30B9B6CB455E`
