---
title: Azure Kit
description: Deploy Vaadin Flow applications into MS Azure cloud.
section-nav: commercial
---

= Azure Kit

:commercial-feature: Observability Kit
:kit-trial: true
include::{articles}/_commercial-banner.asciidoc[opts=optional]

// Is this opening text sufficient?  Is there more that we can say?

Microsoft Azure is a cloud service provided by Microsoft for application management and related services: software as a service (SaaS); platform as a service (PaaS); and infrastructure as a service (IaaS).

The Vaadin Azure Kit is used to integrate your applications with Azure, to be able to deploy your Vaadin Flow applications to the cloud.

The Azure Kit enables teams to deploy seamlessly and operate Vaadin Java-based applications built using Flow on Azure Cloud. The Kit helps teams quickly to create Vaadin applications that are scalable, highly available, and user-friendly. The Kit is also based on Kubernetes to minimize the risk of cloud-provider lock-in.

Download the latest version from the following link:

http://tools.vaadin.com/nexus/content/repositories/vaadin-prereleases/com/vaadin/azure-kit//[Download Azure Kit,role="button primary water"]

== Topics

section_outline::[]

// Is there a discussion ID for Azure Kit?

[discussion-id]`E885B747-E8E1-4446-8220-6EC4C6A94ECF`
