[discrete]
=== Fusion Breaking Changes

[discrete]
==== Frontend npm Package

Fusion frontend code was moved from `@vaadin/flow-frontend` to `@vaadin/fusion-frontend`.
Fusion module imports need to be updated correspondingly.

For example, importing Fusion `EndpointError` needs to be changed as follows, from:

[source, typescript]
----
import { EndpointError } from '@vaadin/flow-frontend';
----

to:

[source, typescript]
----
import { EndpointError } from '@vaadin/fusion-frontend';
----

[discrete]
==== TypeScript 4.4 Default Catch Variable Type

Vaadin has changed the TypeScript dependency version to 4.4.
Starting from this version, the default catch variable type changes in TypeScript from `any` to `unknown`.
As a result, there need to be changes to the error handling code that did not involve `instanceof` guards.

For example:

[source, typescript]
----
try {
  await DataEndpoint.getViewData();
} catch (error) {
  console.log(error.message); // Error TS2571: Object is of type 'unknown'.

  if (error instanceof Error) {
    console.log(error.message); // Works.
  }
}

try {
  await DataEndpoint.getViewData();
} catch (error: any) {
  console.log(error.message); // Works, but using `any` is not recommended.
}
----

See also: https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables:[the TypeScript change announcement].

[discrete]
==== Positive tabindex no longer supported on input fields

Setting the tabindex attribute to a value > 0 is no longer supported on input field components.
However, tabindex values of 0 and -1 are still supported.