[discrete]
=== Hilla as a Standalone Platform
Fusion used to be part of the Vaadin platform, now it is separated from Vaadin and packaged as a standalone platform called Hilla.
Hilla and Vaadin work seamlessly together, as long as the versions match. 
They share the same minor and patch versions; the difference is that Vaadin has 23 as the major version, while Hilla has 1.

[discrete]
=== Use Hilla dependency instead of Vaadin
For a pure Fusion application, you can update the Vaadin dependency and related artifacts to Hilla.
The benefit is that some unnecessary dependencies will be excluded, for example, the server-side Flow components. 
Here is an example of [filename]#pom.xml# file updates:

[source,xml]
----
<!-- use hilla version instead of vaadin -->
<hilla.version>1.0.0</hilla.version>

<!-- use hilla bom instead of vaadin -->
<dependency>
    <groupId>dev.hilla</groupId>
    <artifactId>hilla-bom</artifactId>
    <version>${hilla.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

<!-- use hilla dependency instead of vaadin -->
<dependency>
    <groupId>dev.hilla</groupId>
    <artifactId>hilla</artifactId>
</dependency>

<!-- use hilla-spring-boot-starter instead of vaadin-spring-boot-starter -->
<dependency>
    <groupId>dev.hilla</groupId>
    <artifactId>hilla-spring-boot-starter</artifactId>
</dependency>

<!-- use hilla-maven-plugin instead of vaadin-maven-plugin -->
<groupId>dev.hilla</groupId>
<artifactId>hilla-maven-plugin</artifactId>
<version>${hilla.version}</version>
----
Note that there is no `hilla-core` dependency; both `vaadin` and `vaadin-core` should be replaced with `hilla`.

[discrete]
=== Flow-Hilla Hybrid Projects

If a Flow application needs the Hilla features, such as Endpoint, it can be updated to also include the `hilla` dependency in the [filename]#pom.xml# file.
Here is an example of how to do that:
[source,xml]
----
<vaadin.version>23.0.0</vaadin.version>
<!-- add the hilla version -->
<hilla.version>1.0.0</hilla.version>

<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-bom</artifactId>
    <version>${vaadin.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

<!-- add the hilla bom -->
<dependency>
    <groupId>dev.hilla</groupId>
    <artifactId>hilla-bom</artifactId>
    <version>${hilla.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin</artifactId>
</dependency>

<!-- add the hilla dependency -->
<dependency>
    <groupId>dev.hilla</groupId>
    <artifactId>hilla</artifactId>
</dependency>
----

[discrete]
==== Java Package Renaming
We renamed the `com.vaadin.fusion` package to `dev.hilla`, so the Java imports need to be updated accordingly. 

For example, importing `Endpoint` needs to be changed as follows, from:
[source,java]
----
import com.vaadin.fusion.Endpoint;
----

to:

[source,java]
----
import dev.hilla.Endpoint;
----


[discrete]
==== Front-end npm Package Renaming

The front-end code was moved from `@vaadin/flow-frontend` to `@vaadin/fusion-frontend`, and from `@vaadin/form` to `@hilla/form`.
The module imports need to be updated correspondingly.

For example, importing `EndpointError`, `Binder` and `field` need to be changed as follows, from:

[source,typescript]
----
import { EndpointError } from '@vaadin/fusion-frontend';
import { Binder, field } from '@vaadin/form';
----

to:

[source,typescript]
----
import { EndpointError } from '@hilla/frontend';
import { Binder, field } from '@hilla/form';
----

[discrete]
==== Add Hilla Package to whitelisted-packages List
Make sure that `dev.hilla` is added to the `vaadin.whitelisted-packages` property inside [filename]#application.properties# file.
For example, the property should be changed to look something as follows:

.[filename]#src/main/java/resources/application.properties#
[source,properties]
----
vaadin.whitelisted-packages = com.vaadin,org.vaadin,com.example.application,dev.hilla
----
