---
title: Build a Component
page-title: How to build a Vaadin component
description: Learn how to build a Vaadin component from scratch.
meta-description: TODO
order: 5
---

= Build a Component

Main points:

- This is a hands-on tutorial based on the reference material in <</flow/component-internals#,Component Internals Reference>>. Readers should refer to that guide for details.
- Even though views are also technically Vaadin component, this guide focuses on smaller components that you'd typically use when constructing a view.
- First choice: Compose or Extend?
  - Composite components:
    - Useful if you don't want to deal with the underlying DOM
    - Useful if you can compose the component out of existing Vaadin components rather than building something completely new
    - Gives you better control over the component <</building-apps/architecture/api-spi#,API>> as `Composite` exposes very few methods.
    - Create: A real-world, copy-pastable example of a component
  - Extending Component:
    - Useful when you want to control the underlying DOM
    - You can still implement everything in Java and manipulate the DOM using the <</flow/component-internals/element-api#,Elements API>>.
    - Create: A real-world, copy-pastable example of a component
  - Extending another component:
    - Useful when you want to add more features to an already existing Vaadin component
    - Risky if the component was not designed to be extended
- Second choice: The Java API
  - <</flow/component-internals/properties#,Properties>>
  - <</flow/component-internals/events#,Events>>
  - <</flow/ui-state#,Signals>>
  - Think about how the component will be used by clients
  - Outsource as much logic as possible to the client
  - The simpler the component, the more it can be reused
  - Think about how the component can be reused. If the component is going to be extended, think about which methods should be protected, final, etc. If you don't want the component extended, mark it final. It can still be reused through composition.
- Third choice: <</flow/component-internals/mixins#,Mixin Interfaces>>
  - You don't have to build everything from scratch. Use existing APIs for common functionalitites.
  