---
title: Styling
page-title: How to style the Form Layout component | Vaadin components
description: Styling API reference for the Form Layout component.
meta-description: Customize the Vaadin Form layout component to match your application's style and improve user experience.
order: 50
---
= Form Layout Styling

include::../_styling-section-theming-props.adoc[tag=style-properties]

=== Spacing

Form Layout allows you to configure the spacing between columns, rows, and between the label and input field when labels are positioned on the side.

Use the following CSS properties on individual `vaadin-form-layout` elements, or globally on the `html` element. The Flow API also provides setters for these properties.

[cols="2,3,2"]
|===
|Spacing |CSS Property |Flow API

|Between columns
|`--vaadin-form-layout-column-spacing`
|`setColumnSpacing`

|Between rows
|`--vaadin-form-layout-row-spacing`
|`setRowSpacing`

|Between side label and field
|`--vaadin-form-layout-label-spacing`
|`setLabelSpacing`
|===

=== Sizing

Form Layout allows you to configure the width of the labels when they are positioned on the side.

[cols="2,3,2"]
|===
| Feature | CSS Property | Flow API

|Side label width
|`--vaadin-form-layout-label-width`
|`setLabelWidth`
|===

include::../_styling-section-theming-props.adoc[tag=style-properties]

=== Form Item

[cols="2,1"]
|===
| Property | Supported by

|`--vaadin-input-field-label-color`
|Aura, Lumo

|`--vaadin-input-field-label-font-size`
|Aura, Lumo

|`--vaadin-input-field-label-font-weight`
|Aura, Lumo

|`--vaadin-input-field-label-line-height`
|Aura

|`--vaadin-form-item-label-color`
|Aura (deprecated, use `--vaadin-input-field-label-color` instead)

|`--vaadin-form-item-label-font-size`
|Aura (deprecated, use `--vaadin-input-field-label-font-size` instead)

|`--vaadin-form-item-label-font-weight`
|Aura (deprecated, use `--vaadin-input-field-label-font-weight` instead)

|`--vaadin-form-item-label-line-height`
|Aura (deprecated, use `--vaadin-input-field-label-line-height` instead)

|===

include::../_styling-section-intros.adoc[tag=selectors]

Form Layout:: `vaadin-form-layout`
Form Row:: `vaadin-form-row`
Form Item:: `vaadin-form-item`
Form Item Label:: `vaadin-form-item+++<wbr>+++**::part(label)**`
Form Item Label Text:: `vaadin-form-item+++<wbr>+++** > label**`
Form Item Required Indicator:: `vaadin-form-item+++<wbr>+++**::part(required-indicator)**`
Form Item with Required Field:: `vaadin-form-item+++<wbr>+++**[required]**`
