import type { CSSResultGroup } from 'lit';
import auraCss from '@vaadin/aura/aura.css?inline';
import lumoCss from '@vaadin/vaadin-lumo-styles/lumo.css?inline';
import docsCss from 'Frontend/themes/docs/styles.css?inline';

function createStylesheet(css: CSSResultGroup | string): CSSStyleSheet {
  const stylesheet = new CSSStyleSheet();
  // CSS imported with ?inline is actually a string in DSP, but typed as CSSResultGroup due to TS
  // types generated by Flow.
  // eslint-disable-next-line @typescript-eslint/no-base-to-string
  stylesheet.replaceSync(css.toString());
  return stylesheet;
}

const lumoStyleSheet = createStylesheet(lumoCss);
const auraStyleSheet = createStylesheet(auraCss);
const docsStyleSheet = createStylesheet(docsCss);

function getRootHost(root: DocumentOrShadowRoot) {
  let host: Element;
  if (root instanceof ShadowRoot) {
    host = root.host;
  } else {
    host = (root as Document).documentElement;
  }
  return host;
}

function setExampleTheme(root: DocumentOrShadowRoot, exampleTheme: string | null) {
  const adoptedStyleSheets = root.adoptedStyleSheets.filter(
    (styleSheet) => ![lumoStyleSheet, auraStyleSheet, docsStyleSheet].includes(styleSheet)
  );
  if (exampleTheme === 'Aura') {
    adoptedStyleSheets.push(auraStyleSheet);
  }
  if (exampleTheme === 'Lumo') {
    adoptedStyleSheets.push(lumoStyleSheet);
  }
  root.adoptedStyleSheets = [...adoptedStyleSheets, docsStyleSheet];
}

export function applyTheme(root: DocumentFragment | DocumentOrShadowRoot | HTMLElement) {
  if (root instanceof ShadowRoot || root instanceof Document) {
    const host = getRootHost(root);
    setExampleTheme(root, host.getAttribute('example-theme'));

    new MutationObserver(() => {
      setExampleTheme(root, host.getAttribute('example-theme'));
    }).observe(host, { attributes: true, attributeFilter: ['example-theme'] });
  }
}

export function addStylesheet(css: CSSResultGroup | string) {
  const stylesheet = createStylesheet(css);
  document.adoptedStyleSheets = [...document.adoptedStyleSheets, stylesheet];
}
