import '@vaadin/vaadin-lumo-styles/src/props/icons.css';
import type { CSSResultGroup } from 'lit';
import auraCss from '@vaadin/aura/aura.css?inline';
import lumoCss from '@vaadin/vaadin-lumo-styles/lumo.css?inline';
import docsCss from 'Frontend/themes/docs/styles.css?inline';

function createStylesheet(css: CSSResultGroup | string): CSSStyleSheet {
  const stylesheet = new CSSStyleSheet();
  // CSS imported with ?inline is actually a string in DSP, but typed as CSSResultGroup due to TS
  // types generated by Flow.
  // eslint-disable-next-line @typescript-eslint/no-base-to-string
  const cssString = css.toString();
  stylesheet.replaceSync(cssString);
  return stylesheet;
}

const lumoStyleSheet = createStylesheet(lumoCss);
const auraStyleSheet = createStylesheet(auraCss);
const docsStyleSheet = createStylesheet(docsCss);

function getRootHost(root: DocumentOrShadowRoot) {
  let host: Element;
  if (root instanceof ShadowRoot) {
    host = root.host;
  } else {
    host = (root as Document).documentElement;
  }
  return host;
}

export function applyTheme(root: DocumentFragment | DocumentOrShadowRoot | HTMLElement) {
  if (root instanceof ShadowRoot || root instanceof Document) {
    const host = getRootHost(root);

    const updateTheme = () => {
      const adoptedStyleSheets = root.adoptedStyleSheets.filter(
        (styleSheet) => ![lumoStyleSheet, auraStyleSheet, docsStyleSheet].includes(styleSheet)
      );

      if (host.matches('[theme~="aura"]')) {
        adoptedStyleSheets.push(auraStyleSheet);
      } else {
        adoptedStyleSheets.push(lumoStyleSheet);
      }

      root.adoptedStyleSheets = [...adoptedStyleSheets, docsStyleSheet];
    };

    new MutationObserver(updateTheme).observe(host, {
      attributes: true,
      attributeFilter: ['theme'],
    });

    updateTheme();
  }
}

export function addStylesheet(css: CSSResultGroup | string) {
  const stylesheet = createStylesheet(css);
  document.adoptedStyleSheets = [...document.adoptedStyleSheets, stylesheet];
}
