---
title: Getting Started
tab-title: Overview
order: 1
layout: tabbed-page
---

= Getting Started With Vaadin Observability

== Download the Demo Project

To begin, download and import the demo application project.
This project is used throughout this tutorial in order to demonstrate the features of Vaadin Observability.

Click on the following button to download the demo application (zip file):

https://observability-demo.zip[Download demo,role="button secondary water"]

== Download the Vaadin Observability Agent

Vaadin Observability is packaged as a Java agent based on the OpenTelemetry agent.
For more information, see <<../advanced/observability-agent#,Vaadin Observability Agent>>.

Click on the following button to download the agent (jar file):

https://vaadin-opentelemetry-javaagent.jar[Download agent,role="button secondary water"]

== Setup Telemetry Export

For this tutorial, we are using Jaeger to process traces and Prometheus to process metrics.
These are both run locally and are suitable for development.

For a more production-ready solution, we have also provided instructions for New Relic, which can process logs, metrics and traces.

xref:../integrations/jaeger-prometheus#[Jaeger and Prometheus,role="button secondary water"] or xref:../integrations/newrelic#[New Relic,role="button secondary water"]
