---
title: Importing the Parking Demo
order: 4
layout: page
---

[[mobile.installation.parking-demo]]
= Importing the Parking Demo

The Parking Demo, illustrated in
<<dummy/../../touchkit/mobile-overview#figure.mobile.overview.touchkit,"The
Parking Demo for Vaadin TouchKit">> in the overview, showcases most of the
functionality in Vaadin TouchKit. You can try out the demo online with a
TouchKit-compatible browser at
link:http://demo.vaadin.com/parking[demo.vaadin.com/parking].

You can browse the sources on-line or, more conveniently, import the project in
Eclipse (or other IDE). As the project is Maven-based, Eclipse users need to
install the m2e plugin to be able to import Maven projects, as well as EGit to
be able to import Git repositories. Once they are installed, you should be able
to import Parking Demo as follows.

. Select "File > Import"
. Select "Maven > Check out Maven Project from SCM", and click [guibutton]#Next#.
. You may need to install the EGit SCM connector if you have not done so
previously. If Git is not available in the SCM list, click [guibutton]#m2e
marketplace#, select the EGit connector, and click [guibutton]#Finish#. You need
to restart Eclipse and redo the earlier steps above.

+
Instead of using m2e EGit connector, you can also check out the project with
another Git tool and then import it in Eclipse as a Maven project.

. In [guilabel]#SCM URL#, select [guilabel]#git# and enter the repository URL [uri]#https://github.com/vaadin/parking-demo#.
. Click [guibutton]#Finish#.
. Compile the widget set either by clicking [guibutton]#Compile Widgetset# in the Eclipse toolbar or by running the [literal]#++vaadin:compile++# goal with Maven.
. Deploy the application to a server. See <<dummy/../../framework/getting-started/getting-started-first-project#getting-started.first-project.server,"Setting Up and Starting the Web Server">> for instructions for deploying in Eclipse.
. Open the URL [uri]#http://localhost:8080/parking# with a mobile device or a WebKit-compatible browser, such as Safari or Chrome, to run the Parking Demo.



