---
title: Progress Bar
description: Progress Bar shows the completion status of a task or process.
---


= Progress Bar

The progress can be determinate or indeterminate. Use Progress Bar to show an ongoing process that takes a noticeable amount of time to finish.

[source,tsx]
----
<ProgressBar value={0.5} />
----

.Global Loading Indicator
[NOTE]
A global loading indicator shows at the top of the viewport while processing a server request, after a configurable delay. You don't need to give an explicit Progress Bar for these situations.

== Modes

=== Determinate

Use a determinate Progress Bar when progress can be computed.

=== Indeterminate

Use an indeterminate Progress Bar to show that progress is ongoing but can't be computed.

[source,tsx]
----
<div style={{ color: "var(--lumo-secondary-text-color)" }}>
  <div>Generating report...</div>
  <ProgressBar indeterminate />
</div>
----

== Bounds & Initial Value

The progress value defaults to a range from 0 to 1, with an initial value of 0. This range can be changed to any numeric values.

== Theme Variants

Progress Bar comes with three theme variants: `contrast`, `success`, and `error`.

|===
|Variant |Theme Name |Usage Recommendation

|Success
|`success`
| When progress is satisfactory or nearing completion. This is the visual preference.

|Error
|`error`
| When progress is unsatisfactory. This draws the user's attention to a stalled or failed process.

|Contrast
|`contrast`
| This is a visual preference.

|===


== Best Practices

=== Labels

Use labels to give context to a Progress Bar. Labels can also show the progress of a determinate progress bar in text, in addition to a graphical representation. Examples of this is the percentage of completion, or the number of items processed.


=== State Switching

Switch from indeterminate to determinate if the progress becomes computable. Similarly, switch from determinate to indeterminate if it becomes incomputable.


=== Estimate Completion Time

Give estimates whenever possible. For instance, if a process takes about 20 minutes, communicate that to the user.


=== Asynchronous Processes

If the user is waiting for a process to finish, consider using a Notification to tell them upon its completion or failure. This is useful if the process takes place off-screen or the user is doing something else while waiting.

.Avoid Blocking Processes
[NOTE]
Use asynchronous processes whenever possible so as not to block the user from completing other tasks while waiting for the process to finish.


=== When to Use

If a backend process takes longer than 1 second, use a Progress Bar to show the user that something is happening. This is important when it blocks the user's workflow.

=== Placement

A Progress Bar's location in the UI implies its scope and whether the surrounding UI is operable during its progression. For example, a Vaadin application's built-in loading indicator is placed at the top of the viewport to show that it affects the entire application. The UI is not operable during pending server requests.

Placing a Progress Bar in a dialog, a details panel, or an otherwise defined section implies that the process displayed is specific to that section. Depending on the use case, the user may or may not be able to interact with the UI.


== Related Components

[cols="1,2"]
|===
|Component |Usage Recommendation

|<<../upload#,Upload>>
|Component for uploading files.
|===

:component-path: progress-bar
include::{articles}/react/components/_vaadindocs.adoc[]
