---
title: Feature Flags
page-title: How to configure feature flags in Vaadin Flow
description: How to test experimental features or switch temporarily back to legacy and deprecated features.
meta-description: Feature Flags allow you to enable and test experimental features in your Vaadin application, or switch temporarily back to legacy and deprecated behavior.
order: 160
---


= Feature Flags

Feature Flags allow you to
* Enable and test experimental features;
* Enable legacy features or switch back to legacy behavior;
* Enable opt-in features that don't have other APIs.

The following list contains all of the experimental and legacy features. They're also listed in the [classname]`com.vaadin.experimental.FeatureFlags` (https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/experimental/FeatureFlags.html[Javadoc]) class.


== Experimental Feature Flags

// Prevent names from wrapping
++++
<style>
dl code {
  word-break: initial !important;
}
</style>
++++

`accessibleDisabledButtons`::
Make disabled buttons focusable and hoverable.

`collaborationEngineBackend`::
<<{articles}/tools/collaboration#, Collaboration Kit>> backend for clustering support

`copilotExperimentalFeatures`::
Experimental Vaadin Copilot features.

`flowFullstackSignals`::
Enables <<{articles}/flow/ui-state#, Flow Full-stack Signals>>.

`masterDetailLayoutComponent`::
Enables the <<{articles}/components/master-detail-layout#, Master-Detail Layout>> component.

`tailwindCss`::
Enables experimental <<{articles}/styling/utility-classes#tailwind, Tailwind CSS support>>.

`defaultAutoResponsiveFormLayout`::
<<{articles}/components/form-layout#, Form Layout>> auto-responsive mode enabled by default

`layoutComponentImprovements`::
Experimental HorizontalLayout and VerticalLayout <<{articles}/components/horizontal-layout#enable-layout-improvements-flow-only-experimental,improvements>>.


== Legacy Feature Flags

`themeComponentStyles`::
Enables loading shadow DOM component styles from the `frontend/themes/<themename>/components` folder as in previous Vaadin versions.


== Hilla Feature Flags

`fullstackSignals`::
Enables <<{articles}/hilla/guides/full-stack-signals#, Hilla Full-stack Signals>>


== Managing Feature Flags

Feature flags can be managed in different ways: by using Vaadin Copilot; by editing the feature flags properties file; or by setting Java system properties. Each of these methods is described in the sub-sections that follow. As you read, keep in mind that system properties always have the highest priority. Since they're not written into the feature flags properties file, they're valid only for a single execution.


=== Vaadin Copilot

It's easy to manage feature flags using Vaadin Copilot. When running your browser in development mode, click the Vaadin Copilot activation button in your application. It's located at bottom right corner.

Next, open the [guilabel]*Feature Flags* panel in right drawer, and then click the toggle buttons to enable or disable features.

When finished, restart the application for your changes to take effect.


=== Editing the Properties File

As mentioned, you can also manage feature flags by editing the properties file. To do so by this method, edit the [filename]`src/main/resources/vaadin-featureflags.properties` file in your application folder -- or create the file if it doesn't already exist.

When you have that file open, add a line for each feature in the format of `com.vaadin.experimental.<FEATURE_NAME>=true`. Here's an example of how this might look:

.`vaadin-featureflags.properties`
[source,properties]
----
com.vaadin.experimental.masterDetailLayoutComponent=true
----

To disable a feature, remove the corresponding line or set its value to `false`.

When you're finished enabling or disabling feature flags, save the properties file and restart the application.


=== Setting Java System Properties

The last method for managing feature flags is to set the Java system properties. From the command-line, use the IDE launch configuration or a tool configuration -- such as, Spring Boot Maven plugin -- to set a system property for each feature flag to be enabled or disabled.

The property name should be in the format, `vaadin.<FEATURE_NAME>`, like so:

[source,terminal]
-Dvaadin.masterDetailLayoutComponent=true

To temporarily disable a feature, set its property value to `false`.
