---
title: Connection Context
order: 8
layout: page
---


[[ce.external]]
= Connection Context

Users are connected to a topic by connections that can become active or inactive. Activation of the connections is handled by a connection context. By default, [classname]`ComponentConnectionContext` activates the connections when at least one of the connected UI components are attached to the UI. It deactivates the connections when the UI components are detached. You may want to have different behavior, though, for specific cases.

In addition to managing connection state, a context also handles synchronization of data changing events delivered to application code.

You can create your own connection context by implementing the [classname]`ConnectionContext` interface, or by using one of the provided implementations. A [classname]`SystemConnectionContext` is currently available, in addition to the [classname]`ComponentConnectionContext`, which is the default.

You can then pass the context to the collaboration manager's constructor, or to [methodname]`openTopicConnection()` as follows:

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/collaboration/ConnectionContextExample.java[tags=pass-a-connection-context,indent=0]
----


== Component Connection Context

[classname]`ComponentConnectionContext` implements a connection context based on the attached state of a set of component instances. It activates the topic connection whenever the target component is attached. It deactivates it when the component is detached. All attached components must belong to the same UI instance. This UI instance is used to dispatch actions with its [methodname]`access()` method.

[classname]`ComponentConnectionContext` is used internally by all high-level components (e.g., [classname]`CollaborationAvatarGroup`), and by shorthand methods and constructors that take a component instance instead of the context.

The following example illustrates how to create a Collaboration Manager and how to open a connection to a topic inside a component. In this case, the component (i.e., `this`) is passed as the first parameter. Internally, a [classname]`ComponentConnectionContext` is created in each call. The connection becomes active when the component is attached and is deactivated when it's detached.

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/collaboration/ConnectionContextExample.java[tags=component,indent=0]
----

You can also pass it to the collaboration manager's constructor, or to [methodname]`openTopicConnection()` as follows:

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/collaboration/ConnectionContextExample.java[tags=component-context,indent=0]
----


== System Connection Context

[classname]`SystemConnectionContext` is a connection context that's always active. This context is intended to be used in situations that aren't directly associated with a UI, such as from a background thread or when integrating with external services.

You can acquire an instance with [methodname]`SystemConnectionContext.getInstance()` after a [methodname]`VaadinService` is initialized. In other situations, you can use [methodname]`CollaborationEngine.getSystemContext()` or create a new context instance using the constructor.

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/collaboration/ConnectionContextExample.java[tags=system-connection-context,indent=0]
----

In the following example, an asynchronous job uses a [classname]`SystemConnectionContext` to send a system message:

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/collaboration/ConnectionContextExample.java[tags=async-task,indent=0]
----
<1> The asynchronous function uses Spring's [classname]`@Async` annotation. It needs to receive the [classname]`CollaborationEngine` as a parameter because [methodname]`CollaborationEngine.getInstance()` would throw an exception when running in a background thread. For example, the following would fail:
+
[source,java]
----
collaborationEngine = CollaborationEngine.getInstance(); // Throws an exception
----
<2> The [classname]`SystemConnectionContext` is acquired through [methodname]`CollaborationEngine.getSystemContext()`.
<3> It's then used to create a [classname]`MessageManager` that's activated immediately.
<4> The message is sent and the [classname]`MessageManager` is closed immediately.

[discussion-id]`A51422A2-DAFE-4419-8C57-9A6068F72151`
