---
title: Tools
description: Speed up development with official Vaadin tools.
order: 600
layout: index
---



= Tools
:tools-icon-path-prefix: /


[.cards.large.quiet.hide-title]
== Developer Tools

// tag::all-tools[]

[.card.commercial]
=== AppSec Kit

Identify and manage security vulnerabilities in third-party dependencies.

[.sr-only]
<<{articles}/flow/tools/appsec#,See AppSec Kit>>


[.card.commercial]
=== Azure Cloud Kit

image::{articles/flow}{tools-icon-path-prefix}_images/cloud-upload-alt-solid.svg[opts=inline, role=icon,32,32]

Create scalable, highly-available, easily upgradable Vaadin applications, and deploy them to Azure Cloud.

[.sr-only]
<<{articles}/flow/tools/azure-cloud#,Azure Cloud Kit Overview>>


[.card]
=== Collaboration Kit

image::{articles/flow}{tools-icon-path-prefix}_images/users-solid.svg[opts=inline, role=icon,32,32]

The simplest way to build real-time collaboration into web applications.

[.sr-only]
<<{articles}/flow/tools/collaboration#,See Collaboration Kit>>


[.card.commercial]
=== Design System Publisher

image::{articles/flow}{tools-icon-path-prefix}_images/folder-open.svg[opts=inline, role=icon,32,32]

Create a documentation website for your own Vaadin-based design system.

[.sr-only]
<<{articles}/flow/tools/dspublisher#,See Design System Publisher>>


[.card.commercial]
=== Designer

image::{articles/flow}{tools-icon-path-prefix}_images/paint-brush-solid.svg[opts=inline, role=icon,32,32]

Create UIs visually by dragging and dropping components on a canvas.

[.sr-only]
<<{articles}/flow/tools/designer#,See Designer>>


[.card.commercial]
=== Kubernetes Kit

image::{articles/flow}{tools-icon-path-prefix}_images/cloud-solid.svg[opts=inline, role=icon,32,32]

Deploy your Vaadin application to Kubernetes, enabling scalability, high availability, and rolling updates.

[.sr-only]
<<{articles}/flow/tools/kubernetes#,See Kubernetes Kit>>


[.card.commercial]
=== Multiplatform Runtime

image::{articles/flow}{tools-icon-path-prefix}_images/rocket-solid.svg[opts=inline, role=icon,32,32]

Run applications and components written with Vaadin 7/8 inside a Vaadin 10+ Flow application.

[.sr-only]
<<{articles}/flow/tools/mpr#,See Multiplatform Runtime>>


[.card.commercial]
=== Observability Kit

image::{articles/flow}{tools-icon-path-prefix}_images/eye.svg[opts=inline, role=icon,32,32]

Get insights into Flow applications at runtime and in production by monitoring application health, detecting unhandled errors and performance issues, and observing user behavior.

[.sr-only]
<<{articles}/flow/tools/observability#,See Observability Kit>>


[.card.commercial]
=== SSO Kit

image::{articles/flow}{tools-icon-path-prefix}_images/lock-solid.svg[opts=inline, role=icon,32,32]

Integrate your Vaadin application with third-party identity providers, and give users single sign-on capabilities.

[.sr-only]
<<{articles}/flow/tools/sso#,See SSO Kit>>


[.card.commercial]
=== Swing Kit

image::{articles/flow}{tools-icon-path-prefix}_images/sync-solid.svg[opts=inline, role=icon,32,3w]

Swing Kit is designed to render Vaadin views inside Swing applications. You can gradually modernize your existing Swing application using Vaadin, upgrading the application view-by-view.

[.sr-only]
<<{articles}/flow/tools/swing#,See Swing Kit>>


[.card]
=== Theme Editor

image::{articles/flow}{tools-icon-path-prefix}_images/palette-solid.svg[opts=inline, role=icon,32,32]

Change the web component color, font size, and more in your views without doing code.

[.sr-only]
<<{articles}/flow/tools/theme-editor#,See Theme Editor>>


[.card]
=== View Builder

image::{articles/flow}{tools-icon-path-prefix}_images/view-builder.svg[opts=inline, role=icon,32,3w]

Create new views with custom layouts and components without touching code.

[.sr-only]
<<{articles}/flow/tools/view-builder#,See View Builder>>


[.card]
=== Component Locator

image::{articles/flow}{tools-icon-path-prefix}_images/map-pin-solid.svg[opts=inline, role=icon,32,3w]

Use Component Locator to identify components in views and find their source code in your IDE.

[.sr-only]
<<{articles}/flow/configuration/development-mode/dev-tools/component-locator#,See Component Locator>>

[.card]
=== AI Form Filler

image::{articles/flow}{tools-icon-path-prefix}_images/brain-solid.svg[opts=inline, role=icon,32,3w]

Use natural language input sources to fill automatically forms created with Flow using AI LLM models.

[.sr-only]
<<{articles}/flow/tools/ai-form-filler#,See AI Form Filler>>

// end::all-tools[]

++++
<style>
[class^=PageHeader-module--descriptionContainer] {display: none;}
</style>
++++