[discrete]
==== Use Hilla dependency instead of Vaadin
For a pure Fusion application, you can update the vaadin dependency and related artifacts to hilla.
The benefit is that some unnecessary dependencies will be excluded, for example, the server-side Flow components. 
Here is an example of `pom.xml` file updates:

[source, xml]
----
<!-- use hilla version instead vaadin -->
<hilla.version>1.0.0</hilla.version>

<!-- use hilla bom instead vaadin -->
<dependency>
    <groupId>dev.hilla</groupId>
    <artifactId>hilla-bom</artifactId>
    <version>${hilla.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

<!-- use hilla dependnecy instead vaadin -->
<dependency>
    <groupId>dev.hilla</groupId>
    <artifactId>hilla</artifactId>
</dependency>

<!-- use hilla-spring-boot-starter instead vaadin-spring-boot-starter -->
<dependency>
    <groupId>dev.hilla</groupId>
    <artifactId>hilla-spring-boot-starter</artifactId>
</dependency>

<!-- use hilla-maven-plugin instead vaadin-maven-plugin -->
<groupId>dev.hilla</groupId>
<artifactId>hilla-maven-plugin</artifactId>
<version>${hilla.version}</version>
----
Note that there is no `hilla-core` dependency, both `vaadin` and `vaadin-core` should be replaced with `hilla`. 

[discrete]
===== Java Package renaming
We renamed the `com.vaadin.fusion` package to `dev.hilla`, so the Java imports need to be updated accordingly. 

For example, importing `Endpoint` needs to be changed as follows, from:
[source, java]
----
import com.vaadin.fusion.Endpoint;
----

to:

[source, java]
----
import dev.hilla.Endpoint;
----


[discrete]
===== Frontend npm Package renaming

The frontend code was moved from `@vaadin/flow-frontend` to `@vaadin/fusion-frontend` and `@vaadin/form` to `@hilla/form`.
The module imports need to be updated correspondingly.

For example, importing `EndpointError`, `Binder` and `field` need to be changed as follows, from:

[source, typescript]
----
import { EndpointError } from '@vaadin/fusion-frontend';
import { Binder, field } from '@vaadin/form';
----

to:

[source, typescript]
----
import { EndpointError } from '@hilla/frontend';
import { Binder, field } from '@hilla/form';
----
