---
title: Overview
order: 1
layout: page
---

[[fusion.security.overview]]
= Overview

Vaadin Fusion is a combined client- and server-side model.
As an application developer, you make a decision about how much of the application state is stored on the server and how much is stored in the user's browser.
The sections below describe the best practices for securing such applications.

<<intro#, Security in Fusion Applications>>::
An introduction to the Vaadin Fusion security architecture and how it works in practice.

<<configuring#, Configuring Security>>::
Fusion supports role-based access control at endpoint level.
Explains how to specify the access rules as annotations for the endpoint class or its individual methods.

<<spring-login#, Adding a Login Form with Spring Security>>::
Describes how to configure authentication with Spring Security using its default login form.

<<custom-spring-login#, Adding a Custom Login Form with Spring Security>>::
Describes how to configure authentication with Spring Security and a custom login form.

<<authentication#, Accessing Authentication Data>>::
Describes accessing authentication data such as username and roles on the server side, as well as transferring the data to the client.

<<handle-session-expiration#, Handling Session Expiration>>::
How to detect session expiration, for example, to show a login view to the user.
