---
title: List Box
description: List Box allows the user to select one or more values from a scrollable list of items.
---

= List Box

[source,tsx]
----
<ListBox multiple selectedValues={[0, 2]}>
  <Item>Show assignee</Item>
  <Item>Show due date</Item>
  <Item>Show statux</Item>
</ListBox>
----

Although functionally similar to <<../checkbox#,Checkbox Group>> and <<../radio-button#,Radio Button Group>>, List Box is designed to be used as a lightweight scrollable selection list, rather than as a form input field.

== Dividers

You can use dividers to group related items.
Use them sparingly to avoid creating unnecessary visual clutter.

== Disabled items

Disable items to show that they are unavailable for selection.

.Accessibility
[NOTE]
====
Some assistive technologies don't announce disabled items.
====

== Selection

List Box supports both single and multiple selection.
Single selection allows the user to select only one item, whereas multiple selection enables more than one item to be selected.

== Custom item presentation

pass:[<!-- vale Vaadin.TooWordy = NO -->]

Items can be rendered with rich content instead of plain text.
This can be useful to give more information in a more legible fashion than appending it to the item text.

pass:[<!-- vale Vaadin.TooWordy = YES -->]

[source,tsx]
----
<ListBox multiple selectedValues={[0, 2]}>
  {persons.map((person) => (
    <Item
      key={person.id}
      style={{ lineHeight: "var(--lumo-line-height-m)" }}
    >
      <HorizontalLayout style={{ alignItems: "center" }} theme="spacing">
        <Avatar
          img={person.pictureUrl}
          name={`${person.firstName} ${person.lastName}`}
        />
        <VerticalLayout>
          <span>{`${person.firstName} ${person.lastName}`}</span>
          <span
            style={{
              color: "var(--lumo-secondary-text-color)",
              fontSize: "var(--lumo-font-size-s)",
            }}
          >
            {person.profession}
          </span>
        </VerticalLayout>
      </HorizontalLayout>
    </Item>
  ))}
</ListBox>
----

== Best practices

List Box isn't designed to be used as an input field in forms, and lacks features such as label, helper, and validation errors.
See related components later for better options for use in forms.
List Box is best suited for use as a lightweight, scrollable, single-column list for single or multi-selection of items.

== Related components

|===
|Component |Usage recommendations

|<<../checkbox#,Checkbox Group>>
|Input field for selecting multiple options from a list.

|<<../combo-box#,Combo Box>>
|Select a value from a filterable overlay. Appropriate for large sets of options. Supports lazy loading and entry of custom values.

|<<../radio-button#,Radio Button Group>>
|Select a single option from a list. Optimal accessibility, as all options are visible without any user action.

|<<../select#,Select>>
|Input field for selecting a value from a overlay. More compact than a Radio Button Group.

|<<../grid#,Grid>>
|A more advanced list component for cases where multiple columns, filtering or lazy loading is required.
|===

:component-path: list-box
include::{articles}/react/components/_vaadindocs.adoc[]
