
.Before You Start
[NOTE]
====
- Check the list of link:https://github.com/vaadin/platform/releases/tag/23.0.0[minimum requirements and supported technologies] for Vaadin 23 to ensure that it conforms with your own requirements.

- Check the compatibility of the link:https://vaadin.com/directory/[add-ons] you're using to see if they work with Vaadin 23.

- If for any reason you need to downgrade to an earlier Vaadin version, make sure to clean generated resources by using Maven or Gradle clean functionality: `mvn vaadin:clean-frontend` or `gradle vaadinClean`. Check the <<{articles}/production/production-build/#clean-frontend,documentation>> to see what is removed by the command.

====


== Preliminary Steps

- Delete the `node_modules` folder and lock file &ndash; either [filename]`package-lock.json` with `npm` or [filename]`pnpm-lock.yaml` with `pnpm`.

- Edit the [filename]`pom.xml` file and change the Vaadin version to the latest-available Vaadin 23 version.


== Update to Java 11+

- The Java version requirement has changed from Java 8 to Java 11 or greater -- Java 17 is also supported.
+
For Maven, update `java.version`:
+
[source, xml]
----
<properties>
    <java.version>11</java.version>
</properties>
----
+
Or `compiler.source` and `compiler.target`:
+
[source, xml]
----
<properties>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
</properties>
----

- If the `maven-failsafe-plugin` version is explicitly set in your project, ensure the version is set to `2.21.0` or higher for the plugin to be https://maven.apache.org/surefire/maven-failsafe-plugin/java9.html[compatible with Java 9+].


== Update Spring Settings

Spring has various settings you may need to update. They're listed in the sections below.


=== Update Spring Version

Vaadin is compatible with Spring 5.3.18 or later, and Spring Boot 2.6.6 or later. If your application uses an older version of Spring, though, update it to a compatible version:

.`pom.xml`
[source, xml]
----
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.6.6</version>
</parent>
----

Upgrading the Spring version might require some non-Vaadin-related changes to your application. See the link:https://github.com/spring-projects/spring-boot/wiki[Spring Boot release notes] for the list of required changes.

.Cyclic Dependency in Bakery Starter
[NOTE]
====
If your project is based on the link:/docs/v14/flow/starters/bakeryflow[V14 Bakery starter,role="skip-xref-check"] and you encounter an error due to cyclic dependencies after updating the Spring version, it could be the result of having an [annotationname]`@Autowired` field of type [classname]`PasswordEncoder` and a method that provides the bean for the same type in the [classname]`SecurityConfiguration` class.

Fix this by moving them to separate classes or, preferably, remove the field in favor of using <<{articles}/security/enabling-security#, Vaadin Spring Security helpers>>.
====


=== Update Spring Security

If your application uses Spring security, ensure that the [filename]`offline-stub.html` and [filename]`sw-runtime-resources-precache.js` files are added to the list of static resources that are allowed to bypass Spring security. This can be done by providing a [classname]`SecurityFilterChain` bean similar to the following:

[source,java]
----
@Bean
public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
    http.authorizeRequests().antMatchers(
        ...

        "/offline-stub.html",
        "/sw-runtime-resources-precache.js",

        ...
    ).permitAll();
    return http.build();
}
----


== Enable Server-Side Bootstrapping

Vaadin 23 uses a client-side bootstrapping approach that's different from the server-side mode that's used in Vaadin 14. This change requires some alteration to your Vaadin 14 codebase. However, to expedite migrating your application to Vaadin 23, you can enable Vaadin 14 server-side bootstrapping using the `useDeprecatedV14Bootstrapping` flag. 

This guide describe the code changes required to use the new bootstrapping mode in a later section. To do this in a Spring project, you can add the following to [filename]`application.properties`:

.`application.properties`
[source]
----
vaadin.useDeprecatedV14Bootstrapping=true
----

Alternatively, if you have a plain Java project, you can enable `useDeprecatedV14Bootstrapping` by adjusting the `vaadin-maven-plugin` configuration in [filename]`pom.xml` as follows:

.`pom.xml`
[source]
----
<plugin>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-maven-plugin</artifactId>
    <configuration>
        <useDeprecatedV14Bootstrapping>true</useDeprecatedV14Bootstrapping>
    </configuration>
</plugin>
----

To migrate the deprecated server-side bootstrapping to the modern client-side bootstrapping, see the <<../recommended-changes/#bootstrapping-changes, required Bootstrapping Changes>> section.


== Changed APIs

A set of breaking API changes and their replacements are listed below:

- [classname]`AbstractListDataView` now requires an extra constructor argument &ndash; a callback which is invoked each time the component's filter or sorting changes through the data view API.
- Property synchronization methods in [classname]`Element` are replaced by a similar API in [classname]`DomListenerRegistration`: [methodname]`getSynchronizedPropertyEvents()`, [methodname]`getSynchronizedProperties()`, [methodname]`removeSynchronizedPropertyEvent()`, [methodname]`removeSynchronizedProperty()`, [methodname]`addSynchronizedPropertyEvent()`, [methodname]`addSynchronizedProperty()`, and [methodname]`synchronizeProperty()`.
- The methods [methodname]`JsModule#loadMode()` and [methodname]`Page#addJsModule(String, LoadMode)`, which were used to set the load mode of JsModule, have been removed since they don't work with JavaScript modules.
- The construction methods [methodname]`BeforeEvent(NavigationEvent, Class<?>)` and [methodname]`BeforeEvent(Router, NavigationTrigger, Location, Class<?>, UI)` in [classname]`BeforeEvent` are replaced by [methodname]`BeforeEvent(NavigationEvent, Class, List)` and [methodname]`BeforeEvent(Router, NavigationTrigger, Location, Class, UI, List)`.
- The methods [methodname]`getUrl()`, [methodname]`getUrlBase()` and [methodname]`getRoutes()` in [classname]`Router` are replaced by the methods [methodname]`getUrl()`, [methodname]`getUrlBase()` and [methodname]`getAvailableRoutes()` in [classname]`RouterConfiguration`.
The [methodname]`resolve()` method in [classname]`Router` is replaced by the [methodname]`resolve()` method in [classname]`RouteUtil`.
The [methodname]`getRoutesByParent()` method in [classname]`Router` is removed and has no replacement.
- [classname]`ServletHelper` is replaced by [classname]`HandlerHelper`.
- The [methodname]`getBodyAttributes()` method in [classname]`AbstractTheme`, [classname]`Lumo` and [classname]`Material` is replaced by [methodname]`getHtmlAttributes()`.
- The [methodname]`removeDataGenerator()` method in [interfacename]`HasDataGenerators` and [classname]`CompositeDataGenerator` is removed in favor of using the registration returned from [methodname]`addDataGenerator(DataGenerator)`.
- The methods [methodname]`preventsDefault()` and [methodname]`stopsPropagation()` in [classname]`ShortcutRegistration` are replaced by [methodname]`isBrowserDefaultAllowed()` and [methodname]`isEventPropagationAllowed()`.
- The [methodname]`safeEscapeForHtml()` method in [classname]`VaadinServlet` is removed in favor of using [methodname]`org.jsoup.nodes.Entities#escape(String)`.
- The static method [methodname]`getInstance()` in [classname]`ApplicationRouteRegistry` is removed in favor of the instance method.
- The [methodname]`enableInstallPrompt()` parameter of the [annotationname]`@PWA` annotation has been removed without a replacement. See this https://github.com/vaadin/flow/issues/8038[GitHub issue] to understand the motive for this removal.
- The protected instance method [methodname]`getApplicationUrl()` from [classname]`VaadinServlet` is removed.
- The [interfacename]`HasOrderedComponents`, [interfacename]`HasEnabled`, [interfacename]`HasValidation` and [interfacename]`HasText` interfaces are no longer generic. Therefore, type parameters should be removed.
- The constructor [methodname]`PlotLine(Number value)` in Charts no longer exists. Use the no-arg constructor and then set the value explicitly with [methodname]`setValue(Number value)` method, instead.
- The `ComboBox` has new constructor overloads that prevent `new ComboBox<>(null)` from compiling. Instead, use a cast for the null value so that the correct constructor can be identified (e.g., `new ComboBox<>((String) null)`).
- The [annotationname]`@Theme` annotation now takes a <<../recommended-changes#custom-theme-folder,theme folder>> name as its `value` parameter. Use the `themeClass` parameter to specify a theme class instead:

+
[source,java,role="before"]
----
@Theme(Material.class)
----
+
[source,java,role="after"]
----
@Theme(themeClass = Material.class)
----
+
Correspondingly, combined with a theme variant:
+
[source,java,role="before"]
----
@Theme(value = Lumo.class, variant = Lumo.DARK)
----
+
[source,java,role="after"]
----
@Theme(themeClass = Lumo.class, variant = Lumo.DARK)
----


== Miscellaneous Changes

The following features have changes in their behavior, although their APIs are unchanged.

- If necessary, add a `router-ignore` attribute to the anchor elements whose navigation should bypass the Vaadin router. This is needed, for example, if an anchor is used to log users out in Spring Security. Without the `router-ignore` attribute, the Vaadin router intercepts the navigation to `/logout`, preventing Spring Security from handling logout as intended.
To fix this, add the `router-ignore` attribute as in the following example:
+
[source, java]
----
Anchor logoutLink = new Anchor("/logout", "Logout from app");
logoutLink.getElement().setAttribute("router-ignore", true);
----

- The <<{articles}/advanced/server-side-modality#, server-side modality mechanism>> introduced in V23 changes the behavior of modal Dialogs. Opening another Dialog when a modal Dialog is already open automatically makes the new Dialog a child of the previously opened one. Closing the "parent" modal also closes all subsequently opened Dialogs. To keep other Dialogs open when closing a modal Dialog, add them to the UI explicitly before opening:
+
[source, java]
----
Dialog firstDialog = new Dialog(new Span("First"));
Dialog secondDialog = new Dialog(new Span("Second"));

// Add dialogs explicitly to UI
add(firstDialog, secondDialog);

// Later open dialogs
firstDialog.open();
secondDialog.open();
----

- Positive `tabindex` values (e.g., [methodname]`setTabIndex(5)`) are no longer supported on input fields. Doing this doesn't cause errors, but it also doesn't have any effect on the tab order. However, `tabindex` values of `0` (i.e., to add a tab stop) and `-1` (i.e., to remove a tab stop) are still supported. It's recommended to ensure that input fields are in the correct order in the DOM, instead of overriding the tab order with [methodname]`setTabIndex()`.

- The DOM structure of many components has changed since V14. While this has no effect on their regular Java APIs, code that utilizes Flow's Element API to access a component's internal elements may be affected.

- For Vaadin Charts, if [classname]`XAxis` or [classname]`YAxis` is added to a chart, the ticks of those axes are now hidden by default. To display the ticks, provide the axes with a tick width greater than 0 using [methodname]`XAxis.setTickWidth()` and [methodname]`YAxis.setTickWidth()`.

- In V23.1 and later, required indicators on input fields are no longer hidden when the field has a value. The old behavior -- which required field shown only when the field is empty -- can be brought back using the following (global) CSS:
+
.`styles.css`
[source,css]
----
[required][has-value]::part(required-indicator)::after {
  opacity: 0;
}
----

- In V14, when doing non-router navigation -- i.e., via direct link or an [classname]`Anchor` within the application -- to a specific route, the return value of [methodname]`VaadinRequest.getPathInfo()` includes the route portion of the path. In V23, a `/` without the route part is always returned for such requests. This causes cookies set using route-specific paths not to work correctly. A workaround, to achieve functionality similar to V14, is to set the `eagerServerLoad` configuration parameter to `true`. See <<{articles}/configuration/properties/#properties,properties>> for more information.


== Update Selenium Version

If your application is based on the `spring-boot-starter-parent` and you use Vaadin TestBench to run integration tests, you'll need to update the `selenium.version` property in the [filename]`pom.xml` file to `4.X`. This is to override the outdated Selenium version that gets inherited from the Spring Boot parent.

.`pom.xml`
[source,xml]
----
<properties>
    <!-- Overrides the old version specified by the Spring Boot parent -->
    <selenium.version>4.1.2</selenium.version>
</properties>
----
