---
title: Styling
order: 50
---
= Styling

include::../_styling-section-intros.adoc[tag=selectors]


=== Checkbox
[Horizontal, labelwidth=33]
Root element:: `vaadin-checkbox`
Focused:: `vaadin-checkbox+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-checkbox+++<wbr>+++**[focus-ring]**`
Disabled:: `vaadin-checkbox+++<wbr>+++**[disabled]**`
Hovered:: `vaadin-checkbox+++<wbr>+++**:hover**`
Pressed:: `vaadin-checkbox+++<wbr>+++**[active]**`
Checked:: `vaadin-checkbox+++<wbr>+++**[checked]**`
Indeterminate:: `vaadin-checkbox+++<wbr>+++**[indeterminate]**`
Checkbox box:: `vaadin-checkbox+++<wbr>+++**::part(checkbox)**`
Checkmark:: `vaadin-checkbox+++<wbr>+++**::part(checkbox)::after**`
Label:: `vaadin-checkbox+++<wbr>+++** > label**`


=== Checkbox Group
[Horizontal, labelwidth=33]
Root element:: `vaadin-checkbox-group`


==== States
[Horizontal, labelwidth=33]
Focused:: `vaadin-checkbox-group+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-checkbox-group+++<wbr>+++**[focus-ring]**`
Disabled:: `vaadin-checkbox-group+++<wbr>+++**[disabled]**`
Hovered:: `vaadin-checkbox-group+++<wbr>+++**:hover**`
One or more checkboxes checked:: `vaadin-checkbox-group+++<wbr>+++**[has-value]**`


==== Parts
[Horizontal, labelwidth=33]
Checkbox wrapper:: `vaadin-checkbox-group+++<wbr>+++**::part(group-field)**`
Checkboxes:: `vaadin-checkbox-group+++<wbr>+++** > vaadin-checkbox**`


==== Label
[Horizontal, labelwidth=33]
Checkbox group with label:: `vaadin-checkbox-group+++<wbr>+++**[has-label]**`
Label:: `vaadin-checkbox-group+++<wbr>+++**::part(label)**`
Label text:: `vaadin-checkbox-group+++<wbr>+++** > label**`
Required indicator:: `vaadin-checkbox-group+++<wbr>+++**::part(required-indicator)**`


==== Helper and Validation Error
[Horizontal, labelwidth=33]
Field with helper:: `vaadin-checkbox-group+++<wbr>+++**[has-helper]**`
Helper:: `vaadin-checkbox-group+++<wbr>+++**::part(helper-text)**`
Helper text:: `vaadin-checkbox-group+++<wbr>+++** > [slot="helper"]**`
Invalid field:: `vaadin-checkbox-group+++<wbr>+++**[invalid]**`
Error message:: `vaadin-checkbox-group+++<wbr>+++**::part(error-message)**`
Error message text:: `vaadin-checkbox-group+++<wbr>+++** > [slot="error-message"]**`