---
title: PWA Offline Page
order: 6
layout: page
---

= PWA Offline Page

Vaadin automatically generates and serves an offline page. This is a simple page that:

* Includes the application name and icon.
* Communicates to the user that the application is offline, because there is no network connection.

== Creating a Custom Offline Page

To override the default offline page:

. Create a file named `offline.html`.
. Add the file to your `src/main/webapp/` folder. 

You can change the name of the offline page file using the `offlinePath` parameter in the <<tutorial-pwa-pwa-with-flow#,`@PWA` annotation>>. 

The offline page can only use resources found in the cache. By default, only the offline page, <<tutorial-pwa-web-app-manifest#,manifest>>, and <<tutorial-pwa-icons#,icons>> are cached. If your page needs additional resources (such as CSS, images, Web Components), you can define them using the `offlineResources` parameter in the <<tutorial-pwa-pwa-with-flow#,`@PWA` annotation>>. See <<tutorial-pwa-service-worker#defining-custom-cache-resources,Defining Custom Cache Resources>> for more. 
