---
title: Upload
layout: tabbed-page
tab-title: Usage
page-links:
  - https://github.com/vaadin/vaadin-flow-components/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-upload-flow}[Flow {moduleMavenVersion:com.vaadin:vaadin-upload-flow}]
  - https://github.com/vaadin/vaadin-upload/releases/tag/v{moduleNpmVersion:vaadin-upload}[Web Component {moduleNpmVersion:vaadin-upload}]
---

= Upload

// tag::description[]
Upload is a component for uploading one or more files.
It shows the upload progression and status of each file.
Files can be uploaded using the Upload button or via drag and drop.
// end::description[]

.Work In Progress
[NOTE]
====
The Java examples for this component are currently in progress.
In the meantime, you can view the previous examples.

[.buttons]
- https://vaadin.com/components/vaadin-upload/java-examples[Java Component Examples]
====

[.example]
--
[source, html]
----
include::{root}/frontend/demo/component/upload/upload-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::{root}/src/main/java/com/vaadin/demo/component/upload/UploadBasic.java[render,tags=snippet,indent=0,group=Java]
// ----
--

== Drag & Drop

Upload supports drag and drop for uploading files. Multiple files can be dropped simultaneously.
**By default, it's enabled on desktop and disabled on touch devices. **
By explicitly setting it to enabled or disabled affects both desktop and mobile devices.

[.example]
--
[source, html]
----
include::{root}/frontend/demo/component/upload/upload-drag-and-drop.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::{root}/src/main/java/com/vaadin/demo/component/upload/UploadDragAndDrop.java[render,tags=snippet,indent=0,group=Java]
// ----
--

== Auto Upload

By default, files are uploaded immediately as they are added to the queue.
Auto upload can be disabled, for example, to allow the user to review the list of files before initiating their upload by clicking the ▶️ button for each file.
It is recommended to change the button label to indicate that uploads do not start automatically.

[.example]
--
[source, typescript]
----
include::{root}/frontend/demo/component/upload/upload-auto-upload-disabled.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::{root}/src/main/java/com/vaadin/demo/component/upload/UploadAutoUploadDisabled.java[render,tags=snippet,indent=0,group=Java]
// ----
--

Uploads can be initiated programmatically when auto upload is disabled, for example if you want to provide the user with a single button to start all uploads.

[.example]
--
[source, typescript]
----
include::{root}/frontend/demo/component/upload/upload-all-files.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::{root}/src/main/java/com/vaadin/demo/component/upload/UploadAllFiles.java[render,tags=snippet,indent=0,group=Java]
// ----
--

== Upload Restrictions

You can set three types of restrictions: file format, file count and file size.

Exceptions that arise from the user violating any of the imposed restrictions aren't shown in the UI by default.
Use a <<#listeners, File Rejected listener>> to catch these exceptions and, for example, a <<../notification#, Notification>> to inform the user about the problem at hand and any potential solutions.

However, the user should be informed upfront about any file upload restrictions.
Maximum number of files allowed, file size and format limitations should all be communicated clearly to avoid exceptions whenever possible.

=== File Format

Upload can be configured to only accept files of specific formats.
The acceptable file formats are set using MIME type patterns or file extensions, for example `"video/*"`, `"image/tiff"` or `".pdf"` and `"audio/mp3"`.

[.example]
--
[source, html]
----
include::{root}/frontend/demo/component/upload/upload-file-format.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::{root}/src/main/java/com/vaadin/demo/component/upload/UploadFileFormat.java[render,tags=snippet,indent=0,group=Java]
// ----
--

.Prefer MIME-type
[NOTE]
====
While https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types[MIME types] are widely supported, file extensions are only implemented https://caniuse.com/input-file-accept[in certain browsers] and should be avoided.
====

=== File Count

Upload does not limit the number of files that can be uploaded by default.
If you set the maximum to one the native file browser prevents selecting multiple files.


[.example]
--
[source, typescript]
----
include::{root}/frontend/demo/component/upload/upload-file-count.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// If Upload's Receiver doesn't implement MultiFileReceiver then Upload will automatically only accept one file.
// 
// [source, java]
// ----
// include::{root}/src/main/java/com/vaadin/demo/component/upload/UploadFileCount.java[render,tags=snippet,indent=0,group=Java]
// ----
--

=== File Size

Upload allows you to limit the file size by setting a maximum.
The limit is defined in bytes. It's unlimited by default.

[.example]
--
[source, typescript]
----
include::{root}/frontend/demo/component/upload/upload-file-size.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::{root}/src/main/java/com/vaadin/demo/component/upload/UploadFileSize.java[render,tags=snippet,indent=0,group=Java]
// ----
--

.Revalidate the size limit in the server
[NOTE]
====
This constraint is set on the client and is checked before contacting the server.
====

== File Actions

Each file has a certain set of associated actions available depending on its upload state.
A file always has a "Clear/Remove" button.
This button cancels the upload (if applicable) and removes the file from the list.

The "Clear/Remove" button is the only available action during and after a successful upload.

[.example.render-only]
--
[source, typescript]
----
include::{root}/frontend/demo/component/upload/upload-clear-button.ts[render]
----
--

.Remember to remove the file from the back end
[NOTE]
====
The "Clear/Remove" button does not remove a successfully uploaded file from the server file system or database.
It is only removed from Upload's file list.
====

If an error or exception occurs Upload displays a "Retry" button that attempts to upload the file again when pressed.

[.example.render-only]
--
[source, typescript]
----
include::{root}/frontend/demo/component/upload/upload-retry-button.ts[render]
----
--

When a file is queued (auto upload disabled) it has a "Start" Button that the user must press to begin the upload process.

[.example.render-only]
--
[source, typescript]
----
include::{root}/frontend/demo/component/upload/upload-start-button.ts[render]
----
--

== Internationalization (i18n)

All of Upload's labels and messages are configurable.
For a complete list please refer to the https://cdn.vaadin.com/vaadin-upload/{moduleNpmVersion:vaadin-upload}/#/elements/vaadin-upload#property-i18n[API documentation].

[.example]
--
[source, typescript]
----
include::{root}/frontend/demo/component/upload/upload-internationalization.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::{root}/src/main/java/com/vaadin/demo/component/upload/UploadInternationalization.java[render,tags=snippet,indent=0,group=Java]
// ----
--

== Customization

You can replace the default upload button.
For example, if Upload needs a stronger emphasis you can use a primary button.

[.example]
--
[source, html]
----
include::{root}/frontend/demo/component/upload/upload-button-theme-variant.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::{root}/src/main/java/com/vaadin/demo/component/upload/UploadButtonThemeVariant.java[render,tags=snippet,indent=0,group=Java]
// ----
--

You can also change the drop label's icon.

[.example]
--
[source, html]
----
include::{root}/frontend/demo/component/upload/upload-icon.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::{root}/src/main/java/com/vaadin/demo/component/upload/UploadIcon.java[render,tags=snippet,indent=0,group=Java]
// ----
--

.Use a large drop target
[NOTE]
====
When customizing the Upload component make sure not to make the drop target too small.
A large drop target is easier to use and less error prone.
====

== Technical

=== Listeners

Upload has listeners for the following events:

[cols="1,2"]
|===
|Event|Description

|_All Finished_
|Triggered when Upload has processed all the files in its queue, regardless of whether all the uploads were successful or not

|_Failed_
|When the upload is received but the reception is interrupted for some reason

|_File Rejected_
|Sent when the file selected for upload doesn't meet the constraints, for example, file size

|_Finished_
|Sent when Upload receives a file regardless of whether the upload was successful or not (to distinguish between the two cases use either Succeeded or Failed listeners)

|_Progress_
|Event for tracking upload progress

|_Started_
|Triggered when the upload starts

|_Succeeded_
|Sent when the upload has been successfully received
|===

== Best Practices

=== Labelling

Choose labels that are informative and instructional.
For example, if the user is to upload a single PDF file, it's better to have the button label say "Upload PDF..." instead of "Upload File…".
The task becomes clearer and improves accessibility for the user, especially if they're using a screen reader as the button's label is read aloud when focused.

[.example]
--
[source, typescript]
----
include::{root}/frontend/demo/component/upload/upload-labelling.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::{root}/src/main/java/com/vaadin/demo/component/upload/UploadLabelling.java[render,tags=snippet,indent=0,group=Java]
// ----
--

Likewise, if the user is expected to upload a spreadsheet but multiple file formats are accepted, have the button say "Upload Spreadsheet" with helpers to inform the user which formats are accepted.

[.example]
--
[source, typescript]
----
include::{root}/frontend/demo/component/upload/upload-helper.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::{root}/src/main/java/com/vaadin/demo/component/upload/UploadHelper.java[render,tags=snippet,indent=0,group=Java]
// ----
--

=== Error Messages

Try to provide meaningful feedback and error messages when an exception or error occurs.
Avoid technical jargon and instead try to provide solutions/instructions on how to fix the error.

A "Server Unavailable" might suffice for tech savvy users but for some it might not be helpful at all.
Your error messages should be written with your users in mind.

[.example]
--
[source, typescript]
----
include::{root}/frontend/demo/component/upload/upload-error-messages.ts[render,tags=snippet,indent=0,group=TypeScript]
----

// [source, java]
// ----
// include::{root}/src/main/java/com/vaadin/demo/component/upload/UploadErrorMessages.java[render,tags=snippet,indent=0,group=Java]
// ----
--

== Related Components

|===
|<<../progress-bar#,Progress Bar>> |Component for showing task completion progress.
|===
