---
title: Overview
order: 1
layout: page
---

= Developing a Flow Application

Once you have installed the basic development tools for Vaadin applications as described in <<{articles}/guide/install#, Installing>> and created a project as described in <<{articles}/guide/start#, Start a Project>>, you are ready to import the project to your IDE.

While creating the project with Vaadin Start is recommended, you can also create one from a Maven archetype.
You can do that on command line as described in <<{articles}/guide/start/maven-archetype#, Start a Project: Maven Archetype>>, or you can do it in your IDE.
In the latter case, you can skip importing the project to the IDE.

After you have the project in your IDE, you can go ahead and run or debug it.

.Ways to create and run a new project
[.subtle]
image::images/newproject-flowchart.svg[New project flowchart, width=100%]

If you create a project outside an IDE, you need to import it in the IDE.
During development, you can run the project with a Maven target, depending on the technology stack you are using.
