---
title: Overview
order: 1
layout: page
---

[[starter.overview]]
= Starter Applications Overview

The starter and example applications that you can download from https://vaadin.com/start[vaadin.com/start] should offer good starting points for building your application.

.Subscription required
[NOTE]
A paid _Pro or Prime subscription is required_ for creating a new software project from a Starter template. After its creation, results can be used, developed and distributed freely, but licenses for the used commercial components are required during development. The Starter or its parts cannot be redistributed as a code example or template. For full terms, see the link:https://vaadin.com/license/cvtl-1[Commercial Vaadin Template License.]

Only Flow starters are currently available.

<<bakeryflow/overview#, Flow Bakery>>::
Bakery is a starter business application based on Vaadin Flow and Spring.
+
It includes an end-to-end technology stack covering each layer that is needed to build a production-grade application.
The Bakery is opinionated and reflects Vaadin's view on what is the best way to build business applications.

<<business-app/overview#, Flow Business App>>::
Business App Starter is a commercial Vaadin starter for building responsive business web apps.
It contains a collection of components, view templates, theming utilities and best practises that can help teams save more than a week of development time at the start of a new project.
It makes use of Vaadin's free and open source framework and components, as well as commercial components and tools like Charts and TestBench.
