import Employee from 'Frontend/generated/com/vaadin/demo/fusion/crud/Employee';
import Gender from '../../generated/com/vaadin/demo/fusion/crud/Employee/Gender';
import { CrudMockService } from 'Frontend/demo/services/CrudService';

const employeeData: Employee[] = [
  {
    firstName: 'John',
    lastName: 'Doe',
    gender: Gender.MALE,
    startDate: '2020-03-10',
    shiftStartsAt: '09:00',
    active: true,
    description: 'Senior Software Engineer',
  },
  {
    firstName: 'Alice',
    lastName: 'Smith',
    gender: Gender.FEMALE,
    startDate: '2018-06-25',
    shiftStartsAt: '09:00',
    active: false,
    description: 'HR Manager',
  },
  {
    firstName: 'Michael',
    lastName: 'Brown',
    gender: Gender.NON_BINARY,
    startDate: '2019-11-15',
    shiftStartsAt: '09:00',
    active: true,
    description: 'Sales Representative',
  },
  {
    firstName: 'Emily',
    lastName: 'Davis',
    gender: Gender.FEMALE,
    startDate: '2017-07-20',
    shiftStartsAt: '09:00',
    active: true,
    description: 'Sales Manager',
  },
  {
    firstName: 'Daniel',
    lastName: 'Wilson',
    gender: Gender.OTHER,
    startDate: '2016-04-30',
    shiftStartsAt: '09:00',
    active: false,
    description: 'Marketing Specialist',
  },
  {
    firstName: 'Sarah',
    lastName: 'Johnson',
    gender: Gender.FEMALE,
    startDate: '2014-01-10',
    shiftStartsAt: '09:00',
    active: false,
    description: 'Marketing Manager',
  },
  {
    firstName: 'Robert',
    lastName: 'Lee',
    gender: Gender.MALE,
    startDate: '2020-09-05',
    shiftStartsAt: '09:00',
    active: true,
    description: 'Product Engineer',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Adams',
    gender: Gender.FEMALE,
    startDate: '2019-02-15',
    shiftStartsAt: '09:00',
    active: false,
    description: 'Product Manager',
  },
  {
    firstName: 'David',
    lastName: 'Miller',
    gender: Gender.MALE,
    startDate: '2015-03-25',
    shiftStartsAt: '09:00',
    active: true,
    description: 'Customer Support Specialist',
  },
  {
    firstName: 'Susan',
    lastName: 'Wilson',
    gender: Gender.FEMALE,
    startDate: '2013-08-10',
    shiftStartsAt: '09:00',
    active: true,
    description: 'Customer Support Manager',
  },
  {
    firstName: 'Mark',
    lastName: 'Taylor',
    gender: Gender.MALE,
    startDate: '2018-09-10',
    active: true,
    description: 'Financial Analyst',
  },
  {
    firstName: 'Laura',
    lastName: 'White',
    gender: Gender.NON_BINARY,
    startDate: '2016-01-15',
    shiftStartsAt: '09:00',
    active: true,
    description: 'Finance Manager',
  },
  {
    firstName: 'James',
    lastName: 'Clark',
    gender: Gender.MALE,
    startDate: '2021-05-20',
    active: true,
    description: 'Research Scientist',
  },
  {
    firstName: 'Sarah',
    lastName: 'Brown',
    gender: Gender.FEMALE,
    startDate: '2019-12-05',
    shiftStartsAt: '09:00',
    active: false,
    description: 'Research Manager',
  },
  {
    firstName: 'Matthew',
    lastName: 'Anderson',
    gender: Gender.OTHER,
    startDate: '2017-06-20',
    active: true,
    description: 'QA Tester',
  },
  {
    firstName: 'Emily',
    lastName: 'Parker',
    gender: Gender.FEMALE,
    startDate: '2015-08-15',
    shiftStartsAt: '09:00',
    active: true,
    description: 'QA Manager',
  },
  {
    firstName: 'Christopher',
    lastName: 'Hall',
    gender: Gender.MALE,
    startDate: '2019-11-25',
    active: true,
    description: 'Product Manager',
  },
  {
    firstName: 'Anna',
    lastName: 'Lewis',
    gender: Gender.FEMALE,
    startDate: '2017-03-12',
    shiftStartsAt: '09:00',
    active: false,
    description: 'Senior Product Manager',
  },
  {
    firstName: 'Nathan',
    lastName: 'Johnson',
    gender: Gender.MALE,
    startDate: '2016-04-10',
    shiftStartsAt: '09:00',
    active: false,
    description: 'Customer Service Representative',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Smith',
    gender: Gender.NON_BINARY,
    startDate: '2014-08-05',
    active: true,
    description: 'Customer Service Manager',
  },
];

let id = 0;

const employees = employeeData.map((employee) => ({
  ...employee,
  id: ++id,
  version: 0,
}));

export default new CrudMockService(employees);
