import Employee from 'Frontend/generated/com/vaadin/demo/fusion/crud/Employee';
import Gender from '../../generated/com/vaadin/demo/fusion/crud/Employee/Gender';
import { CrudMockService } from 'Frontend/demo/services/CrudService';

const employeeData: Employee[] = [
  {
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    dateOfBirth: '1990-05-15',
    gender: Gender.MALE,
    startDate: '2020-03-10',
    endDate: '2022-11-30',
    team: 'Engineering',
    manager: 'Alice Smith',
    active: true,
    description: 'Senior Software Engineer',
  },
  {
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alice.smith@example.com',
    dateOfBirth: '1985-08-20',
    gender: Gender.FEMALE,
    startDate: '2018-06-25',
    endDate: '2021-12-15',
    team: 'Human Resources',
    manager: 'David Johnson',
    active: false,
    description: 'HR Manager',
  },
  {
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@example.com',
    dateOfBirth: '1993-02-05',
    gender: Gender.NON_BINARY,
    startDate: '2019-11-15',
    team: 'Sales',
    manager: 'Emily Davis',
    active: true,
    description: 'Sales Representative',
  },
  {
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@example.com',
    dateOfBirth: '1980-12-10',
    gender: Gender.FEMALE,
    startDate: '2017-07-20',
    team: 'Sales',
    active: true,
    description: 'Sales Manager',
  },
  {
    firstName: 'Daniel',
    lastName: 'Wilson',
    email: 'daniel.wilson@example.com',
    dateOfBirth: '1987-09-25',
    gender: Gender.OTHER,
    startDate: '2016-04-30',
    endDate: '2023-08-31',
    team: 'Marketing',
    manager: 'Sarah Johnson',
    active: false,
    description: 'Marketing Specialist',
  },
  {
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@example.com',
    dateOfBirth: '1975-03-15',
    gender: Gender.FEMALE,
    startDate: '2014-01-10',
    endDate: '2021-07-05',
    team: 'Marketing',
    active: false,
    description: 'Marketing Manager',
  },
  {
    firstName: 'Robert',
    lastName: 'Lee',
    email: 'robert.lee@example.com',
    dateOfBirth: '1991-06-30',
    gender: Gender.MALE,
    startDate: '2020-09-05',
    team: 'Product Development',
    manager: 'Jennifer Adams',
    active: true,
    description: 'Product Engineer',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Adams',
    email: 'jennifer.adams@example.com',
    dateOfBirth: '1983-04-02',
    gender: Gender.FEMALE,
    startDate: '2019-02-15',
    endDate: '2022-10-30',
    team: 'Product Development',
    active: false,
    description: 'Product Manager',
  },
  {
    firstName: 'David',
    lastName: 'Miller',
    email: 'david.miller@example.com',
    dateOfBirth: '1988-11-20',
    gender: Gender.MALE,
    startDate: '2015-03-25',
    team: 'Customer Support',
    manager: 'Susan Wilson',
    active: true,
    description: 'Customer Support Specialist',
  },
  {
    firstName: 'Susan',
    lastName: 'Wilson',
    email: 'susan.wilson@example.com',
    dateOfBirth: '1970-07-12',
    gender: Gender.FEMALE,
    startDate: '2013-08-10',
    endDate: '2022-04-15',
    team: 'Customer Support',
    active: true,
    description: 'Customer Support Manager',
  },
  {
    firstName: 'Mark',
    lastName: 'Taylor',
    email: 'mark.taylor@example.com',
    dateOfBirth: '1992-03-12',
    gender: Gender.MALE,
    startDate: '2018-09-10',
    team: 'Finance',
    manager: 'Laura White',
    active: true,
    description: 'Financial Analyst',
  },
  {
    firstName: 'Laura',
    lastName: 'White',
    email: 'laura.white@example.com',
    dateOfBirth: '1984-07-25',
    gender: Gender.NON_BINARY,
    startDate: '2016-01-15',
    team: 'Finance',
    active: true,
    description: 'Finance Manager',
  },
  {
    firstName: 'James',
    lastName: 'Clark',
    email: 'james.clark@example.com',
    dateOfBirth: '1995-11-08',
    gender: Gender.MALE,
    startDate: '2021-05-20',
    team: 'Research and Development',
    manager: 'Sarah Brown',
    active: true,
    description: 'Research Scientist',
  },
  {
    firstName: 'Sarah',
    lastName: 'Brown',
    email: 'sarah.brown@example.com',
    dateOfBirth: '1986-04-18',
    gender: Gender.FEMALE,
    startDate: '2019-12-05',
    endDate: '2022-08-31',
    team: 'Research and Development',
    active: false,
    description: 'Research Manager',
  },
  {
    firstName: 'Matthew',
    lastName: 'Anderson',
    email: 'matthew.anderson@example.com',
    dateOfBirth: '1990-09-29',
    gender: Gender.OTHER,
    startDate: '2017-06-20',
    team: 'Quality Assurance',
    manager: 'Emily Parker',
    active: true,
    description: 'QA Tester',
  },
  {
    firstName: 'Emily',
    lastName: 'Parker',
    email: 'emily.parker@example.com',
    dateOfBirth: '1983-01-30',
    gender: Gender.FEMALE,
    startDate: '2015-08-15',
    team: 'Quality Assurance',
    active: true,
    description: 'QA Manager',
  },
  {
    firstName: 'Christopher',
    lastName: 'Hall',
    email: 'christopher.hall@example.com',
    dateOfBirth: '1993-06-14',
    gender: Gender.MALE,
    startDate: '2019-11-25',
    team: 'Product Management',
    manager: 'Anna Lewis',
    active: true,
    description: 'Product Manager',
  },
  {
    firstName: 'Anna',
    lastName: 'Lewis',
    email: 'anna.lewis@example.com',
    dateOfBirth: '1980-10-08',
    gender: Gender.FEMALE,
    startDate: '2017-03-12',
    endDate: '2023-06-30',
    team: 'Product Management',
    active: false,
    description: 'Senior Product Manager',
  },
  {
    firstName: 'Nathan',
    lastName: 'Johnson',
    email: 'nathan.johnson@example.com',
    dateOfBirth: '1987-12-19',
    gender: Gender.MALE,
    startDate: '2016-04-10',
    endDate: '2022-10-15',
    team: 'Customer Service',
    manager: 'Jennifer Smith',
    active: false,
    description: 'Customer Service Representative',
  },
  {
    firstName: 'Jennifer',
    lastName: 'Smith',
    email: 'jennifer.smith@example.com',
    dateOfBirth: '1978-02-28',
    gender: Gender.NON_BINARY,
    startDate: '2014-08-05',
    team: 'Customer Service',
    active: true,
    description: 'Customer Service Manager',
  },
];

let id = 0;

const employees = employeeData.map((employee) => ({
  ...employee,
  id: ++id,
  version: 0,
}));

export default new CrudMockService(employees);
