---
tab-title: Usage
layout: tabbed-page
title: Date Time Picker
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/date-time-picker}/#/elements/vaadin-date-time-picker[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/datetimepicker/DateTimePicker.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/date-time-picker}/packages/date-time-picker[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-date-time-picker-flow-parent[Java]'
---


= Date Time Picker

// tag::description[]
Date Time Picker is an input field for selecting both a date and a time.
// end::description[]

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerBasic.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-basic.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

The date and time can be entered directly using the keyboard in the format of the current locale or through the Date Time Picker's two overlays. The overlays open when their respective fields are clicked or any input is entered when the fields are focused.


== Step

Date Time Picker's step parameter defines the time interval in seconds between the items displayed in the time picker overlay. It also specifies the amount by which the time increases or decreases using the up and down arrow keys when the overlays are disabled.

The default step is one hour (that is, `3600`). Unlike with <<../number-field#,Number Field>>, Date Time Picker accepts values that don't align with the specified step.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-minutes-step.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerMinutesStep.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-minutes-step.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

.Use Even Steps
[NOTE]
The step must divide evenly an hour or a day. For example, _"15 minutes"_, _"30 minutes"_ and _"2 hours"_ are valid steps, while _"42 minutes"_ isn't.

The displayed time format changes based on the step.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-seconds-step.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerSecondsStep.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-seconds-step.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--
// Allow FFF
pass:[<!-- vale Vaadin.Abbr = NO -->]

|===
|Step |Format

|Less than 60 seconds
|HH:MM:SS

|Less than 1 second
|HH:MM:SS:FFF
|===

pass:[<!-- vale Vaadin.Abbr = YES -->]

.Limit Number of Steps
[NOTE]
The overlay doesn't appear for steps less than 900 seconds (i.e., 15 minutes) to avoid showing an impractical number of choices.


== Auto Open

The overlay opens automatically when the field is focused using a pointer (i.e., mouse or touch), or when the user types in the field. You can disable this so that the overlay opens only when the toggle button or the kbd:[Up]/kbd:[Down] arrow keys are pressed.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-auto-open.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerAutoOpen.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-auto-open.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Validation

=== Min & Max Values

You can define a `min` and `max` value for Date Time Picker if you need to restrict the input to a specific range:

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-min-max.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerMinMax.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-min-max.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== Custom Validation

If the `min` and `max` values aren't enough, you can also apply custom validation.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-custom-validation.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerCustomValidation.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-custom-validation.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Week Numbers

You can configure Date Time Picker to show week numbers in the date picker overlay.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-week-numbers.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerWeekNumbers.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-week-numbers.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

The week numbers are displayed according to https://www.iso.org/iso-8601-date-and-time-format.html[ISO-8601]. They can only be displayed with the first day of the week set to Monday.


== Initial Position

Date Time Picker's initial position parameter defines which date is focused in the calendar overlay when the overlay is opened. Use this feature to minimize the need for any additional navigation or scrolling when the user's input is expected to be between certain dates.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-initial-position.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerInitialPosition.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-initial-position.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Internationalization (i18n)

Date Time Picker allows localizing texts and labels, such as month names and button labels.

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-internationalization.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerInternationalization.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-internationalization.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

See also how to <<../date-picker#date-format,configure a custom date format>>.


// Basic Features

include::{articles}/components/_input-field-common-features.adoc[tags=basic-intro;label;helper;placeholder;tooltip;]

[#aria-labels]
.[since:com.vaadin:vaadin@V24.1]#Invisible Labels (ARIA)#
[%collapsible]
====
If the built-in label cannot be used, an invisible label should be provided for users of assistive technologies like screen readers. The date and time sub-fields can also be assigned invisible suffixes (e.g., `date` and `time`) that are appended to their invisible labels.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{articles}/components/_shared-code-snippets.adoc[tags=aria-label-dtp-typescript,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{articles}/components/_shared-code-snippets.adoc[tags=aria-label-dtp-java,indent=0,group=Java]
----
endif::[]
--
====

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-basic-features.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerBasicFeatures.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-basic-features.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


// Readonly and disabled

include::{articles}/components/_input-field-common-features.adoc[tag=readonly-and-disabled]

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-readonly-and-disabled.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerReadonlyAndDisabled.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-readonly-and-disabled.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


// Style Variants

include::{articles}/components/_input-field-common-features.adoc[tags=styles-intro;text-alignment;small-variant;helper-above-field;borders]

[.example]
--
ifdef::lit[]
[source,typescript]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-styles.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerStyles.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-styles.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Usage Patterns

=== Date Time Range

You can accomplish a date time range picker using two Date Time Pickers.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-range.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerRange.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-range.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

To disable the days before the start date in the end date picker, you need to handle the selection in the start date picker and change the range in the end date picker.


== Best Practices

Use Date Time Picker when the user needs to choose both a date and time of day. If you only need a date or time of day, use <<../date-picker#,Date Picker>> or <<../time-picker#,Time Picker>>, respectively.


=== Picking vs. Typing

The calendar overlay is useful when the user needs to choose a day that's close to the current date or when information such as day of the week, week number, valid dates, and so on, can aid in choosing the best option.

For far off dates (i.e., years ago or years from now) and for known dates (i.e., holidays and birthdays), typing the date can be a faster and easier approach. It's important to verify that the user can enter dates according to their locale.


=== Providing Input Guidance

Use a helper text to show the expected date and time formats, and placeholders to help users identify the two sub-fields, correctly.

[.example]
--
ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/datetimepicker/date-time-picker-input-format.ts[render,tags=snippet,indent=0,group=TypeScript]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerInputFormat.java[render,tags=snippet,indent=0,group=Java]
----
endif::[]

ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/datetimepicker/react/date-time-picker-input-format.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


== Related Components

[cols="1,2"]
|===
|Component |Usage Recommendation

|<<../time-picker#,Time Picker>>
|Input field for entering or selecting a specific time.

|<<../date-picker#,Date Picker>>
|Input field for entering or selecting a specific date.
|===


[discussion-id]`58305ABE-B962-4ED0-A1C7-36BB906C9452`
