---
title: Styling
order: 50
---
= Styling

include::../_styling-section-intros.adoc[tag=selectors]

[Horizontal, labelwidth=33]
Root element:: `vaadin-date-time-picker`


=== States
[Horizontal, labelwidth=33]
Required:: `vaadin-date-time-picker+++<wbr>+++**[required]**`
Focused:: `vaadin-date-time-picker+++<wbr>+++**[focused]**`
Keyboard focused:: `vaadin-date-time-picker+++<wbr>+++**[focus-ring]**`
Read-only:: `vaadin-date-time-picker+++<wbr>+++**[readonly]**`
Disabled:: `vaadin-date-time-picker+++<wbr>+++**[disabled]**`
Not empty:: `vaadin-date-time-picker+++<wbr>+++**[has-value]**`
Hovered:: `vaadin-date-time-picker+++<wbr>+++**:hover**`


=== Sub-Fields
[Horizontal, labelwidth=33]
Date Picker:: `vaadin-date-time-picker-date-picker`
Time Picker:: `vaadin-date-time-picker-time-picker`

_See <<../date-picker/styling#,Date Picker>> and <<../time-picker/styling#,Time Picker>> selectors for details_

=== Label
[Horizontal, labelwidth=33]
Field with label:: `vaadin-date-time-picker+++<wbr>+++**[has-label]**`
Label:: `vaadin-date-time-picker+++<wbr>+++**::part(label)**`
Label text:: `vaadin-date-time-picker+++<wbr>+++** > label**`
Required indicator:: `vaadin-date-time-picker+++<wbr>+++**::part(required-indicator)**`


=== Helper and Validation Error
[Horizontal, labelwidth=33]
Field with helper:: `vaadin-date-time-picker+++<wbr>+++**[has-helper]**`
Helper:: `vaadin-date-time-picker+++<wbr>+++**::part(helper-text)**`
Helper text:: `vaadin-date-time-picker+++<wbr>+++** > [slot="helper"]**`
Invalid field:: `vaadin-date-time-picker+++<wbr>+++**[invalid]**`
Error message:: `vaadin-date-time-picker+++<wbr>+++**::part(error-message)**`
