---
title: New Relic
description: New Relic is an observability SaaS platform with support for metrics, traces, and logs. Learn how to use New Relic together with Observability Kit.
page-links:
  - https://newrelic.com[Website]
---

= New Relic Integration

.New Relic ignores all messages above a certain size
[CAUTION]
To avoid losing data, messages can be truncated automatically using the property `otel.attribute.value.length.limit`.
See <<configuration-file>> for instructions.


== Sign Up for a New Relic Account

You can create a New Relic account can at https://newrelic.com/signup.
You can export up to 100 GB of data per month without cost.

[[configuration-file]]
== Observability Kit Configuration

Create a new properties file named `agent.properties` and add the following lines to it:

.agent.properties
[source,properties]
----
otel.traces.exporter=otlp
otel.logs.exporter=otlp
otel.metrics.exporter=otlp
otel.exporter.otlp.endpoint=ENDPOINT_URL
otel.exporter.otlp.headers=Api-Key=LICENSE_KEY
otel.exporter.otlp.protocol=http/protobuf
otel.attribute.value.length.limit=4095
----

You can find the `ENDPOINT_URL` from the table in the https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup/#review-settings[New Relic documentation].

You can find the `LICENSE_KEY` in your New Relic account settings under [guilabel]*API Keys*.
Be sure to use the license key of type `INGEST-LICENSE`.


== Running the App

include::./_run-app.adoc[]

== Viewing Data

After using the application for a while – the traces show up with a delay – log in to New Relic.

From the [guilabel]*All entities* view, select your service name under [guilabel]*Services - OpenTelemetry*: `vaadin` if you didn't specify one.

Now you get a menu where you can look through the telemetry data from your application.

=== Viewing Traces

Open the [guilabel]*Monitor - Distributed tracing* view, which shows application traces showing count, duration, and errors.

See New Relic documentation for the https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-distributed-tracing-page[Distributed tracing page] for more information on how to use this view.

=== Viewing Metrics

Open the [guilabel]*Data - Metrics explorer* view, where you can explore all reported metrics.

See New Relic documentation for the https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-metrics-explorer-page[Metrics explorer page] for more information on how to use this view.


=== Viewing Logs

Open the [guilabel]*Monitor - Logs* view, which shows application logs that link to traces with `trace.id`.

See New Relic documentation for the https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-logs-page[Logs page] for more information on how to use this view.


== Observability Kit Dashboard

You can create a pre-configured dashboard for New Relic that contains several metrics, such as request throughput, error rate, and JVM stats with this generator.

Enter your New Relic account ID below and then click [guibutton]*Generate*.
You can get your account ID from the New Relic URL in the browser.

[source,html,role=render-only]
----
include::{root}/frontend/demo/fusion/acceleration-kits/observability-kits/newrelic/dashboard-generator.ts[render]
----

Next, you need to do the following:

* copy the dashboard JSON from above;
* open the New Relic UI in the browser;
* open the [guilabel]*Dashboards* view, and then click on [guilabel]*Import dashboard* in the top-right; and
* paste the JSON that you copied from above, and then click [guibutton]*Import dashboard*.
