---
title: Using Charts 9+ in V14
order: 8
layout: page
---

[[charts.migratingfromearlierversions]]
= Using Charts 9+ in V14

Vaadin Charts 9 comes with new chart types and brings back the API to style from Java.
Since there are breaking changes introduced on Vaadin Charts 9, these changes cannot be backported to V14 as part of the platform.

This guide will help you update your V14 project to use the latest Charts.

== Summary

Below, you can see the main changes done for Charts 9 compared to previous versions:

* Upgraded to HighCharts 8.1
* Styling can be done either with CSS or Java API (default)
* New chart types:
** <<{root}/latest/ds/components/charts/java-api/charttypes/#charts.charttypes.bullet,Bullet Chart>>
** <<{root}/latest/ds/components/charts/java-api/charttypes/#charts.charttypes.organization,Organization Chart>>
** <<{root}/latest/ds/components/charts/java-api/charttypes/#charts.charttypes.timeline,Timeline Chart>>
** <<{root}/latest/ds/components/charts/java-api/charttypes/#charts.charttypes.xrange,X-Range Chart>>
* Java API for lazy drilldown

== Installing The Latest Charts In V14

While the newer Charts was released for V17, a project running V14 in *npm mode* can use the new Charts by overriding the version at the project's POM file:

[source, xml]
----
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-charts-flow</artifactId>
    <version>19.0.2</version>
</dependency>
----

.Latest Version
[NOTE]
====
Check the latest version on the https://github.com/vaadin/vaadin-flow-components/releases[Vaadin Flow Components release page].
====

== Migration guide

If you are planning to use Vaadin Charts 9 on a V14 platform, there are different approaches depending on the styling option picked.

.One Styling Option By Project
[CAUTION]
====
While no error is thrown if different styling options are used on a same project, *only one option should be used across all charts*, since having both could lead to unexpected results.
====

=== Using Java API Styling

Vaadin Charts 9+ uses Java API for styling by default.
This is more suitable for new projects or projects where the amount of charts is small or not heavily customised.

For example, that's how the <<../css-styling/#css.styling.example1,Example 1 from the CSS Styling session>> would look like using the Java API:

[source, java]
----
Chart chart = new Chart();
Configuration configuration = chart.getConfiguration();

configuration.getChart().setType(ChartType.LINE);

configuration.getxAxis().setCategories("Jan", "Feb", "Mar", "Apr");

DataSeries ds = new DataSeries();
ds.setData(7.0, 6.9, 9.5, 14.5);

DataLabels callout = new DataLabels(true);
callout.setShape(Shape.CALLOUT);
callout.setY(-12);
// Setting the color to the data labels
callout.setColor(SolidColor.RED);
ds.get(1).setDataLabels(callout);
ds.get(2).setDataLabels(callout);
configuration.addSeries(ds);

// Adding a plot options to set the color to the markers
PlotOptionsLine plotOptions = new PlotOptionsLine();
plotOptions.getMarker().setFillColor(SolidColor.YELLOW);
chart.getConfiguration().setPlotOptions(plotOptions);

add(chart);
----


=== Using CSS Styling

If you want to upgrade Vaadin Charts, but want to keep using CSS styling, there are a few steps needed to make it work:

. Enable CSS style on every instance by calling `setStyledMode(true)`:
+
[source, java]
----
Chart chart = new Chart();
Configuration conf = chart.getConfiguration();
conf.getChart().setStyledMode(true);
----
. Import the charts default theme module to your view with:
+
[source, java]
----
@JsModule("@vaadin/vaadin-charts/theme/vaadin-chart-default-theme")
----

For more detailed instructions, please check the
<<css-styling#,"CSS Styling guide">>

