---
title: Application Themes for Embedded Components
order: 90
---

= Application Themes for Embedded Components

It's possible to <<{articles}/integrations/embedding#, embed>> an entire Vaadin application, parts of one or custom Flow-based components, into other web pages. The mechanism for doing so generates a custom Web Component that wraps the embedded UI inside its <<shadow-dom-styling#, Shadow DOM>>. This has certain implications for theming, which are covered in more detail in the <<{articles}/integrations/embedding/theming#, Theming Embedded Applications>> section. Below is a brief summary of things to keep in mind related to this:

* The `@Theme` annotation can be used to apply a theme to the embedded UI. It's applied to the class extending the `WebComponentExporter` class.
* The applied theme is injected into the Shadow DOM of the wrapper Web Component. Because of this...
* Any CSS applied to the `html` or `body` root element selectors must also be applied to the `:host()` root selector of the embedded UI. So use the selector `html,:host() {...}` if you want the styles to work both in embedded and non-embedded contexts.
* The theme's CSS must be divided into two stylesheets:
** `document.css`: any CSS that needs to work in an overlay (e.g. a Dialog), as well as `@font-face` declarations. These styles are loaded into the root of the parent page.
** `styles.css`: any CSS that should _not_ be loaded into the parent page, e.g. for risk of conflicts with the parent page's CSS.
* <<../lumo/utility-classes#, Lumo Utility Classes>> do not work in overlays (e.g. Dialog) in embedded UIs.