---
title: Application Themes for Embedded Components
order: 90
---

= Application Themes for Embedded Components

It’s possible to #embed# an entire Vaadin application, parts of one or custom Flow-based components, into other web pages. The mechanism for doing so generates a custom Web Component that wraps the embedded UI inside its #Shadow DOM#. This has certain implications for theming, which are covered in more detail in the #Theming Embedded Applications# section. Below is a brief summary of things to keep in mind related to this:

* The `@Theme` annotation can be used to apply a theme to the embedded UI. It’s applied to the class extending the `WebComponentExporter` class.
* Because of the Shadow DOM wrapping the embedded UI, styling must be done partially through #Shadow DOM injection#.
* Any CSS applied to the `html` or `body` root element selectors must also be applied to the `:host()` root selector of the embedded UI. So use the selector `html,:host() {...}` if you want the styles to work both in embedded and non-embedded contexts.
* Font-face declarations in CSS must be declared in a stylesheet called `document.css` in the root of the theme folder to work. This ensures that they are applied at the page root level rather than the Shadow DOM root.