---
tab-title: Usage
layout: tabbed-page
title: Dashboard
description: A component for building static dashboard layouts and dynamic, user-configurable dashboards.
page-links:
  - 'API: https://cdn.vaadin.com/vaadin-web-components/{moduleNpmVersion:@vaadin/dashboard}/#/elements/vaadin-dashboard[TypeScript] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/dashboard/Dashboard.html[Java]'
  - 'Source: https://github.com/vaadin/web-components/tree/v{moduleNpmVersion:@vaadin/dashboard}/packages/dashboard[TypeScript] / https://github.com/vaadin/flow-components/tree/{moduleMavenVersion:com.vaadin:vaadin}/vaadin-dashboard-flow-parent[Java]'
section-nav: commercial badge-preview
version: since:com.vaadin:vaadin@V24.6
---


= Dashboard
:experimental:

// tag::description[]
A component for building static dashboard layouts and dynamic, user-configurable dashboards.
// end::description[]

:commercial-feature: Dashboard
include::{articles}/_commercial-banner.adoc[opts=optional]

:preview-feature: Dashboard
:feature-flag: com.vaadin.experimental.dashboardComponent
include::{articles}/_preview-banner.adoc[opts=optional]

[.example]
--
// TODO: main sample
--

Widgets are placed in columns and rows automatically, in the order supplied, based on the Dashboard's width and the column configuration. As the Dashboard's width changes, the number of columns is automatically adjusted based on their configured minimum and maximum width, and the widget positions are adjusted accordingly. Widgets can not be explicitly placed in a particular column or row.

The Dashboard provides built-in vertical scrolling, provided that its height has been specified.

There are two ways to use the Dashboard component:

* <<#static-dashboards,Static>>: declaratively / imperatively defining the widgets. The React and Web Components for this are `<DashboardLayout>` and `<vaadin-dashboard-layout>` respectively.
* <<#dynamic-dashboards,Dynamic>>: widgets generated from data using a renderer; supports edit mode that allows the end user to move, resize and remove widgets. The React and Web Components for this are `<Dashboard>` and `<vaadin-dashboard>`, respectively.

In Flow, the same `Dashboard` class is used for both approaches.


== Configuration

The following configuration options are available for the dashboard:

=== Columns and Rows

Column width can vary between a minimum and maximum size. The default maximum width is `1fr`, which allows the columns to expand to fill any available space. If a fixed length value is provided, empty space will be left at the end of rows once the columns reach their maximum width.

By default there is no limit on the number of columns, but one can be provided if needed.

The height of each dashboard row is determined by the tallest widget currently in that row (whose height in turn is determined by its contents). A minimum row height determines the height of empty rows, such as when a widget's row span is stretched into a previously unoccupied row. The minimum height can be configured.

[.example]
--
////
TODO: Code snippet for setting custom
- Min and max col width
- Max col count
- Min row height
////
--

=== Whitespace

The horizontal and vertical spacing between widgets, and the padding along the dashboard's edges, can be configured.

[.example]
--
////
TODO: Code snippet for setting custom
- Spacing
- Padding
////
--

=== Dense Layout
This mode uses the dense packing algorithm in the CSS grid layout model, which attempts to fill in empty slots in the layout by placing smaller widgets in them, potentially affecting the order of the widgets. It should be used with caution in user-configurable dashboards, as the automatic reordering of widgets may be confusing during editing.

[.example]
--
////
TODO: Code snippet (w/o sample) that shows how to toggle dense mode.
////
--

[.example]
--
////
TODO: Sample that can switch between dense and normal layout, without code snippet.
(No need to use proper widgets here – some kind of placeholder content is sufficient to demonstrate the difference)
////
--


== Widgets

Widgets consist of a content area and a header containing the widget's title and a slot for additional elements.

[.example]
--
////
TODO: Sample of a widget with title, some simple content, and something in the header content area.
////
--

The column span and row span can be set to make the widget take up more than one column or row in the dashboard's layout. The actual number of columns a widget spans is limited by the number of columns currently in the dashboard, however.


=== Widget Content Sizing

The height of a widget's contents determine its default height, which can be expanded by row span and/or other widgets on the same dashboard row. The widget does not scroll, so the contents may need to incorporate a scrollable aread of its own (e.g. by way of a <<../scroller#,Scroller>>) to accommodate a height smaller than its contents.

The widget's width, on the other hand, is determined by the current column width and the widget's column span.

Contents that should cover the entire widget area should therefore be configured with 100% width and height, as well as a minimum height corresponding to its desired default height.


[#static-dashboards]
== Static Dashboards

Static dashboards are populated declaratively (in React and Lit) / imperatively (in Flow), like normal layouts. They're a good choice for hardcoded dashboards.

[cols="1,1m"]
|===

|Flow
|Dashboard

|React
|<DashboardLayout>

|Lit Web Component
|<vaadin-dashboard-layout>

|===

[.example]
--
////
TODO: Sample of a static dashboard (let's repeat the main example here)
////
--


[#dynamic-dashboards]
== Dynamic, Editable Dashboards

Dynamic dashboards provide end user editability out of the box. They're populated through a databinding API coupled with a widget renderer function, so that their contents can be easily persisted to and loaded from storage, such as a database.

[cols="1,1m"]
|===

|Flow
|Dashboard

|React
|<Dashboard>

|Lit Web Component
|<vaadin-dashboard>

|===

[.example]
--
////
TODO: Dynamic dashboard example:
Dynamically loaded dashboard, defaulting to the same widgets as the static sample.
Toolbar above provides:
- Edit mode switch (replaced by a Apply button in edit mode)
- “Load widgets” button that loads widgets from local storage (disabled until saved)
- “Save widgets” button that saves widgets to local storage
- Select for adding more widgets (enabled once a widget has been removed)
- Reset button for resetting the dashboard to the default content
////
--


=== Editing

Dynamic dashboards can be made user editable by toggling on editing mode, as seen in the sample above.

.Editing mode should be temporary
[NOTE]
====
Editing mode is intended as a temporary state that is engaged when the end user wants to edit the dashboard's contents, and disengaged when they're done editing, at which point the widget configuration is typically persisted to storage.
====

The following operations are available in editing mode:

==== Widget Selection by Keyboard

In editing mode, widgets can be selected by keyboard by moving focus to the desired widget using the kbd:[Tab] key and pressing kbd:[Space] or kbd:[Enter]. Once selected, arrow keys can be used to move and resize widgets, and to engage the accessible move and resize modes.

Widget selection is not required for editing by pointer device.

==== Moving Widgets

In editing mode, widgets can be moved around by

* Drag & drop
* Arrow keys, once the widget has been selected
* An accessible move-mode engaged by clicking the drag-handle in the widget's top left corner. Move-mode is disengaged by clicking the apply-button in the widget's center, or by pressing kbd:[Esc].

(Currently widgets can only be moved backwards and forwards; moving a widget past the start or end of a row moves it to the preceding or following row.)

==== Resizing Widgets

In editing mode, widgets can be resized by increasing and decreasing their column span and row span by

* Dragging from the drag-handle in the widget's bottom right corner
* kbd:[Shift] + arrow keys, once the widget has been selected
* An accessible resize-mode engaged by clicking the resize-handle. Resize-mode is disengaged by clicking the apply-button in the widget's center, or by pressing kbd:[Esc].

==== Removing Widgets

In editing mode, widgets can be removed by clicking the remove-button in the widget's top right corner.

==== Adding Widgets

There is no built-in mechanism for adding new widgets to the dashboard, but this can easily be implemented using an external widget selector, such as a <<../select#,Select>> dropdown, that adds the corresponding item to the dashboard.

==== Screen Reader Announcements

Although widget selection is announced via the widget's title, and the various buttons all have accessible names, the component does not provide announcements of changes to the widget's position and size out of the box. These can be provided by listening to related events emitted by the component and updating custom live regions with appropriate announcements.

[.example]
--
////
TODO: Sample of a dashboard in editing mode with visible live areas updated when widgets are moved and resized. (Let's use the same widgets as in the main sample.)
////
--


=== Persisting and Loading Widgets

// TODO


== Dashboard Sections

Complex dashboards can benefit from being divided into titled sections. Dashboard Sections always span the full width of the dashboard, and follow the same column and row configuration as the dashboard itself. They support the same moving and removal operations in editing mode as widgets.

[.example]
--
////
TODO: Sample of dashboard with sections:
Same widgets as in main sample, but
- The 3 KPI widgets in a section titled "Monthly Funnel Stats"
- The other widgets in a section titled "Visior Details"
////
--


== Internationalization

The following texts in the dashboard can be localized through the internationalization object:


[cols="1m,2"]
|===
| Property | Description

|selectWidget
|Widget selection trigger

|deselectWidget
|Widget deselection trigger

|selectSection
|Section selection trigger

|deselectSection
|Section deselection trigger

|move
|Button that engages move-mode

|moveForward
|Move forward button (in move-mode)

|moveBackward
|Move backward button (in move-mode)

|moveApply
|Button that disengages move-mode

|resize
|Button that engages resize-mode

|resizeGrowWidth
|Grow width button (in resize-mode)

|resizeShrinkWidth
|Shrink width button (in resize-mode)

|resizeGrowHeight
|Grow height button (in resize-mode)

|resizeShrinkHeight
|Shrink height button (in resize-mode)

|resizeApply
|Button that disengages resize-mode

|remove
|Remove button

|===


[.example]
--
// TODO: Code snippet showing how to localize the strings through the i18n object
--

////
UNCOMMENT ONCE CARD PAGE EXISTS

== Related Components

|===
|Component | Usage Recommendations
|<<../card#, Card>>
|Generic card component that can be used in any layout
|===
////

[discussion-id]`d59db2ee-c3dd-446d-bd0d-40224b1f141e`
