---
title: Border
order: 40
layout: page
---

= Lumo Border

Custom properties which affect the visual style of component borders.

== Border Radius
The border radius values are defined as `em` by default, so they scale with the font size.

[NOTE]
If you want to set a border radius property to zero, you need to specify a unit for it as well (for example `0px`), as it can be used in `calc` functions which will be undefined if the border radius is a unitless value.

++++
<content-preview class="block" hidesource raw>
  <dl class="custom-properties">
    <dt>--lumo-border-radius-s: <code>0.25em</code></dt>
      <dd>Use for small elements. To ensure they never turn into full circles, keep this value below <code>0.5em</code>.</dd>
    <dt>--lumo-border-radius-m: <code>0.25em</code></dt>
      <dd>The most commonly used roundness. It’s recommended to keep the value between <code>0em</code> and <code>calc(var(--lumo-size-m) / 2)</code></dd>
    <dt>--lumo-border-radius-l: <code>0.5em</code></dt>
      <dd>Use for large containers, such as cards and dialogs. It’s recommended to keep the value between <code>0em</code> and <code>0.5em</code></dd>
    <dt>--lumo-border-radius: <code>0.25em</code></dt>
      <dd>Deprecated. Use <code>--lumo-border-radius-m</code> instead.</dd>
  </dl>
</content-preview>
++++
== Examples
++++
<content-preview class="block">
++++
[source,html]
----
<div class="box s radius">S</div>
<div class="box m radius">M</div>
<div class="box l radius">L</div>

<custom-style>
  <style>
    .radius.s {
      border-radius: var(--lumo-border-radius-s);
    }
    .radius.m {
      border-radius: var(--lumo-border-radius-m);
    }
    .radius.l {
      border-radius: var(--lumo-border-radius-l);
    }
  </style>
</custom-style>
----
++++
</content-preview>
++++
