---
title: Text Area
layout: tabbed-page
tab-title: Usage
page-links: \
https://github.com/vaadin/vaadin-text-field-flow/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-text-field-flow}[{moduleMavenVersion:com.vaadin:vaadin-text-field-flow}], \
https://github.com/vaadin/vaadin-text-field/releases/tag/v{moduleNpmVersion:vaadin-text-field}[{moduleNpmVersion:vaadin-text-field}]
---

= Text Area

// tag::description[]
Text Area is an input field component for multi-line text input.
// end::description[]

[.example]
--
[source,html]
----
include::../../../../frontend/demo/component/textarea/text-area-helper-1.ts[render,tags=snippet,indent=0,group=TypeScript]
----
--

Text Area is typically used for descriptions, comments, and other longer free-form content.

== Automatic Height Adjustment

Unless set to a fixed height, Text Area adjusts its height automatically based on its content.
The default and minimum height is two rows of text.

[.example]
--
[source,html]
----
include::../../../../frontend/demo/component/textarea/text-area-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----
--

=== Minimum and Maximum Height

The automatic resizing can be restricted to a minimum and maximum height:

[.example]
--
[source,html]
----
include::../../../../frontend/demo/component/textarea/text-area-height.ts[render,tags=snippet,indent=0,group=TypeScript]
----
--

== Character Counter

Longer free-form inputs are often capped at a certain character limit.
The current character count and upper limit should be indicated to the user, e.g. by using the Helper feature:

[.example]
--
[source,html]
----
include::../../../../frontend/demo/component/textarea/text-area-helper-2.ts[render,tags=snippet,indent=0,group=TypeScript]
----
--

== Related Components

|===
|Web Component |Usage recommendations

|<<../text-field#,Text Field>>
|Basic single-line text input.

|<<../rich-text-editor#,Rich Text Editor>>
|Multi-line text entry with rich formatting support.
|===
