---
title: Text Area
layout: tabbed-page
tab-title: Usage
page-links: \
https://github.com/vaadin/vaadin-flow-components/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-text-field-flow}\[Flow {moduleMavenVersion:com.vaadin:vaadin-text-field-flow}], \
https://github.com/vaadin/vaadin-text-field/releases/tag/v{moduleNpmVersion:vaadin-text-field}\[Web Component {moduleNpmVersion:vaadin-text-field}]
---
= Text Area

// tag::description[]
Text Area is an input field component for multi-line text input.
// end::description[]

[.example]
--
[source,html]
----
include::../../../../frontend/demo/component/textarea/text-area-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::../../../../src/main/java/com/vaadin/demo/component/textarea/TextAreaBasic.java[render,tags=snippet,indent=0,group=Java]
----
--

Text Area is typically used for descriptions, comments, and other longer free-form content.

== Automatic Height Adjustment

Unless set to a fixed height, Text Area adjusts its height automatically based on its content.
The default and minimum height is two rows of text.

[.example]
--
[source,html]
----
include::../../../../frontend/demo/component/textarea/text-area-auto-height.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::../../../../src/main/java/com/vaadin/demo/component/textarea/TextAreaAutoHeight.java[render,tags=snippet,indent=0,group=Java]
----
--

=== Minimum and Maximum Height

The automatic resizing can be restricted to a minimum and maximum height:

[.example]
--
[source,html]
----
include::../../../../frontend/demo/component/textarea/text-area-height.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::../../../../src/main/java/com/vaadin/demo/component/textarea/TextAreaHeight.java[render,tags=snippet,indent=0,group=Java]
----
--

== Character Counter

Longer free-form inputs are often capped at a certain character limit.
The current character count and upper limit should be indicated to the user, e.g. by using the <<{articles}/design-system/components/input-fields#helper,Helper>> feature:

[.example]
--
[source,html]
----
include::../../../../frontend/demo/component/textarea/text-area-helper.ts[render,tags=snippet,indent=0,group=TypeScript]
----

[source,java]
----
include::../../../../src/main/java/com/vaadin/demo/component/textarea/TextAreaHelper.java[render,tags=snippet,indent=0,group=Java]
----
--

== Related Components

|===
|Component |Usage recommendations

|<<../text-field#,Text Field>>
|Basic single-line text input.

|<<../rich-text-editor#,Rich Text Editor>>
|Multi-line text entry with rich formatting support.
|===
