---
title: Starting a Project
tab-title: Starter Projects
layout: tabbed-page
order: 20
---

= Starting a Project
:wizard-name: Vaadin Start
:toclevels: 2

[.cards.quiet.large.hide-title]
=== Vaadin Start

[.breakout]
--
The recommended way to start a new Vaadin project is to use *{wizard-name}*.
It allows you to configure and download a customized starting point for your application.
--

https://start.vaadin.com?preset=latest[Open {wizard-name}, role="button primary water"]

[.breakout]
=== Non-Spring Boot Starters
The applications created using {wizard-name} are based on Spring Boot.
Vaadin Flow starters for other stacks, such as JavaEE or plain servlet, are available in GitHub.

* https://github.com/vaadin/skeleton-starter-flow[Plain Java starter]
* https://github.com/vaadin/skeleton-starter-flow-cdi[CDI and JakartaEE starter]
* https://github.com/vaadin/base-starter-flow-osgi[OSGi starter]

More https://github.com/search?q=org%3Avaadin+starter&type=repositories[Vaadin starter projects] are available on GitHub.


=== Next Steps

Once you have downloaded a starter project and have it extracted in a local folder, you can import it to your favorite IDE (integrated development environment) and start developing it further.

.Ways to create and run a new project
[.subtle]
image::images/newproject-flowchart.svg[New project flowchart, width=100%]

If you create a project outside an IDE, you need to import it in the IDE.
During development, you can run the project with a Maven target, depending on the technology stack you are using.

After you have the project in your IDE, you can go ahead and run or debug it.
