++++
<style>
.admonitionblock.note.prerelease {
  border: 0;
  background-color: var(--blue-50);
  font-size: var(--docs-font-size-xs);
  font-weight: var(--docs-font-weight-emphasis);
  color: var(--blue-900);
  --docs-admonitionblock-icon-color: var(--blue-600);
}

.admonitionblock.note.prerelease .title {
  font-weight: var(--docs-font-weight-strong);
}

.admonitionblock.note.prerelease .title,
.admonitionblock.note.prerelease p {
  margin-bottom: 0;
}

.admonitionblock.note.prerelease .icon {
  font-size: var(--docs-font-size-m);
  line-height: 1.25;
}

.admonitionblock.note.prerelease .buttons ul {
  font-size: var(--docs-font-size-2xs);
}

.admonitionblock.note.prerelease .buttons ul a:any-link {
  color: var(--blue-900);
  border-color: var(--blue-500);
  font-weight: var(--docs-font-weight-emphasis);
}

.admonitionblock.note.prerelease .buttons ul li:first-child a:any-link {
  color: var(--base-white);
  background-color: var(--blue-600);
}

.admonitionblock.note.prerelease .buttons ul a:any-link::after {
  content: none;
}

[theme~="dark"] .admonitionblock.note.prerelease {
  background-color: var(--blue-900);
  color: var(--blue-50);
  --docs-admonitionblock-icon-color: var(--blue-400);
}

[theme~="dark"] .admoninition.prerelease .buttons ul a:any-link {
  color: inherit;
}
</style>
++++

ifndef::prerelease-feature[]
:prerelease-feature: This feature
endif::[]

ifndef::prerelease-banner-content[]
:prerelease-banner-content: {prerelease-feature} has not yet been released and is only available through the pre-release repository.
endif::[]

.Pre-release feature
[.prerelease.skip-search-index]
[NOTE]
====
{prerelease-banner-content}

.Add the following to your pom.xml repositories section:
[source,xml]
----
<repository>
    <id>vaadin-prereleases</id>
    <url>https://maven.vaadin.com/vaadin-prereleases/</url>
</repository>
----

ifdef::artifact-id+version[]
.Add the following to your pom.xml dependencies section:
[source,xml]
----
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>{artifact-id}</artifactId>
    <version>{version}</version>
</dependency>
----
endif::[]
====
