---
title: Supported Technologies
page-title: Vaadin compatibility guide
description: Lists the minimum required version of compatible technologies for Vaadin 24.
meta-description: Learn about Vaadin’s compatibility with browsers, frameworks, and environments. See minimum required version of compatible technologies for Vaadin 24.
order: 901
---


= List of Supported Technologies

This page shows the minimum required versions of supported technologies for Vaadin 24. See the https://github.com/vaadin/platform/releases/tag/24.0.0[release notes] for more details.

[cols="1,1"]
|===
|Technology|Version

| Java| 21 or later
| Spring Boot| 4.0 or later
| Node.js| 24 or later
| Maven| 3.8 or later
| Gradle| 8.14 or later
| Servlet| 6 or later
| Application Servers
a|

- Apache Tomcat 10.1
- Open Liberty 23
- RedHat JBoss Enterprise Application Platform (EAP) 8.1
- WildFly 36
- Jetty 12
- Payara Server 6
- Payara Micro 6
| Quarkus| 3.27 or later
| Portlet| Not supported yet
| OSGi| Not supported yet
| Karaf| Not supported yet
|===


== Browser Compatibility

Vaadin 25 is supported by several web browsers. The following is a list of compatible desktop browsers and mobile browsers.

=== Desktop Browsers

[cols="1,1"]
|===
| Browser | Version

| Chrome | Evergreen
| Firefox | Evergreen, ESR
| Safari | 17 or later
| Edge | Evergreen, Chromium
|===

=== Mobile Browsers

[cols="1,1"]
|===
| Browser | Version

| Chrome | Evergreen
| Safari | 17 or later
|===
