---
root: true
title: Docs
layout: index
page-links:
  - https://github.com/vaadin/platform/releases/tag/{moduleMavenVersion:com.vaadin:vaadin}[{moduleMavenVersion:com.vaadin:vaadin}]
---

= Vaadin 14 Docs

[.lead]
Vaadin is an open-source platform for building web applications.
It consists of a library of UI components and a framework for creating user interfaces using Java only.
Vaadin also offers commercial tools that speed up your development workflow.

xref:guide/install#[Get Started, role="button primary water"]

.Vaadin Fusion
[TIP, role="breakout small"]
Documentation for [since:com.vaadin:vaadin@V15]#link:https://vaadin.com/fusion[Fusion]#, including component examples, is available in the documentation for the current release in our latest / non-LTS release track. Fusion will be added the LTS release track starting with our next LTS major version (expected in Q4 2021). link:../latest/[Browse latest documentation ›, role=skip-xref-check]


// docs-app applies styles on <em> tags in the card headings
pass:[<!-- vale Vaadin.HeadingFormatting = NO -->]

[.cards.quiet.large.hide-title]
== Sections

[.card]
=== Flow
image::_images/flow.svg[opts=inline, role=icon]
Build progressive web applications using Java.
<<flow/overview#,See Flow>>

[.card]
=== Collaboration Engine
image::_images/ce.svg[opts=inline, role=icon]
The simplest way to build real-time collaboration into web apps
<<ce/overview#,See Collaboration Engine>>

[.card]
=== Charts
image::_images/charts.svg[opts=inline, role=icon]
Feature-rich interactive graph library that answers the data visualization needs of modern web applications.
<<ds/charts#,See Charts>>

[.card]
=== Designer
image::_images/designer.svg[opts=inline, role=icon]
Create UIs visually by dragging and dropping components on a canvas.
<<tools/designer/overview#,See Designer>>

[.card]
=== TestBench
// For some weird reason Vale.Spelling picks on 'testbench' if it is repeated in both the image url and the cross reference path
image::_images/testbench.svg[opts=inline, role=icon]
Create end-to-end integration tests, including visual regression tests.
<<tools/testbench/overview#,See TestBench>>



++++
<style>
nav[aria-label=breadcrumb] {
  display: none;
}

[class*=layout][class*=index] {
  padding-left: var(--docs-space-xl);
  padding-right: var(--docs-space-xl);
  margin-left: auto;
  margin-right: auto;
  max-width: 55em;
}

a.button.primary.water {
  color: var(--button-color-dark-text);
}
</style>
++++
