---
root: true
title: Docs
layout: index
---

= Vaadin 10 Docs

++++
<style>
nav[aria-label=breadcrumb] {
  display: none;
}

[class*=layout][class*=index] {
  margin-left: var(--docs-space-xl);
  margin-right: var(--docs-space-xl);
}
</style>
++++

.Maintenance version
[IMPORTANT]
Vaadin 10 is an older version which is no longer in active development. It still receives regular maintenance, but we recommend that new projects start with a newer version of Vaadin. https://vaadin.com/docs[View latest docs]

[.cards.quiet.large.hide-title]
== Sections

[.card]
=== Flow
image::_images/flow.svg[opts=inline, role=icon]
Use Java to build progressive web applications.
<<flow/overview#,See the Flow Framework>>

[.card]
=== Designer
image::_images/designer.svg[opts=inline, role=icon]
Create UIs visually by dragging and dropping components on a canvas.
<<designer/getting-started/designer-overview#,See Designer>>

[.card]
=== Charts
image::_images/charts.svg[opts=inline, role=icon]
Feature-rich interactive graph library that answers the data visualization needs of modern web applications.
<<charts/charts-overview#,See Charts>>

[.card]
=== TestBench
// For some weird reason Vale.Spelling picks on 'testbench' if it is repeated in both the image url and the cross reference path
image::_images/testbenchicon.svg[opts=inline, role=icon]
Create end-to-end integration tests, including visual regression tests.
<<testbench/testbench-overview#,See TestBench>>
