---
title: Docs
description: Official documentation for Hilla, a full-stack web application framework.
root: true
layout: index
---

= Hilla documentation

[highlight-text]*Choose your preferred UI technology*. The Java back end is the same for both, but you can choose to build the front end using Lit or React.

[.cards.large.hide-title]
== Choose UI technology


=== image:lit/lit-logo.svg[opts=inline,role=icon,height=32] Lit
[.sr-only]
<<lit#,Use Hilla together with Lit>>

=== image:react/react-logo.svg[opts=inline,role=icon,height=32] React [badge since:com.vaadin:vaadin@v1.3]#New#
[.sr-only]
<<react#,Use Hilla together with React>>

[.cards.quiet.hide-title]
== What's the difference?

=== About Lit
[.secondary-text]
Lit is a modern and lightweight alternative to React, built-on top of web standards, with a similar programming model. It's not as popular as React, or have as good tooling or IDE support.

https://lit.dev[Learn more [sr-only]#about Lit#]

=== About React
[.secondary-text]
React is the de-facto industry standard front-end library for building UIs. React has great tooling and IDE support, a large ecosystem of libraries and components, and a huge community of developers.

https://reactjs.org[Learn more [sr-only]#about React#]

++++
<style>
html {
  --docs-article-max-width: 38rem;
}

[class*=breadcrumb],
[class*=pageNavigation] {
  display: none !important;
}

.badge {
  font-size: var(--docs-font-size-2xs);
  display: inline-block;
  padding: 0.2em 0.5em;
  margin: 0 0.5em;
  vertical-align: middle;
  /*background-color: var(--docs-purple-800);*/
  border: 1px solid var(--green-700);
  color: var(--green-400);
  border-radius: var(--docs-border-radius-m);
}

.badge::after {
  content: ' in ' var(--version) !important;
  font-size: inherit !important;
}
</style>
++++
