---
root: true
title: Docs
layout: index
page-links:
  - https://github.com/vaadin/platform/releases/tag/{moduleMavenVersion:com.vaadin:vaadin}[{moduleMavenVersion:com.vaadin:vaadin}]
---


[.hero]
--
[discrete]
= Vaadin Docs

++++
<div class="column">
<h2>Develop Web Apps on Java Backends</h2>
<p class="lead">Build scalable UIs in Java or TypeScript, using the integrated tooling, components, and design system.
<div class="buttons">
<a href="guide/install" class="button primary water">Get Started</a>
<a href="flow/tutorials/quick-start-tutorial" class="button small secondary water">Flow Quick Start</a>
<a href="fusion/tutorials/quick-start-tutorial" class="button small secondary water">Fusion Quick Start</a>
</div>
</p>
</div>
++++

[.column.hero-illustration]
image:_images/code-editor-illustration.svg[opts=inline]
--

[.cards.quiet.large]
== Frameworks

[.card.large]
=== Flow
image::_images/flow.svg[opts=inline, role=icon, width=48]
The most productive web framework for Java developers.

xref:flow/overview#[Flow Overview]

[.card.large]
=== Fusion
image::_images/fusion.svg[opts=inline, role=icon, width=48]
Use TypeScript, HTML, and Java to build progressive web applications.

xref:fusion/overview#[Fusion Overview]

=== Flow or Fusion?
If you are unsure which framework to choose, check out the comparison.
https://vaadin.com/comparison?compare=flow_vs_fusion[View Comparison]

[.cards.quiet.large]
== Design System

[.card.large]
=== Components
image::_images/components.svg[opts=inline, role=icon, width=48]
Browse the UI component library, with Java and TypeScript code examples and design guidelines.

xref:ds/components#[Browse Components]

=== Foundation
Reference documentation for the visual foundation, including colors, typography, spacing, elevation, and more.
xref:ds/foundation#[Foundation Overview]

=== Customization
Learn how to customize the design system to fit your brand, and how to package it for reuse across multiple applications.
xref:ds/customization#[Customization Overview]


[.cards.quiet.large]
== Collaboration Engine

[.card.large]
=== Overview
image::_images/ce.svg[opts=inline, role=icon, width=48]
The simplest way to build real-time collaboration into web apps.

xref:ce/overview#[Collaboration Engine Overview]

=== Get Started
Follow the tutorial and get your first collaborative application up and running.
xref:ce/tutorial#[Quick Start Guide]

=== Licensing & Pricing
Start for free, and get a license when you need to scale up.
xref:ce/developing-with-ce#[Licensing & Pricing]

[.cards.quiet.large]
== Tools

[.card.large]
=== Designer
image::_images/designer.svg[opts=inline, role=icon]
Create UIs visually by dragging and dropping components on a canvas.

xref:tools/designer/overview#[Designer Overview]

[.card.large]
=== TestBench
image::_images/testbench.svg[opts=inline, role=icon]
Create end-to-end integration tests, including visual regression tests.

xref:tools/testbench/overview#[TestBench Overview]

[.card.large]
=== Design System Publisher
image::_images/dsp.svg[opts=inline, role=icon, width=48]
Create a documentation website for your own Vaadin-based design system.

xref:tools/dspublisher/overview#[Design System Publisher Overview]



++++
<style>
nav[aria-label=breadcrumb] {
  display: none;
}

.hero {
  padding: var(--docs-space-m) var(--docs-space-xl);
  margin: 0 calc(var(--docs-space-m) * -1);
  background-color: var(--docs-surface-color-2);
  border-radius: var(--docs-border-radius-l);
  overflow: hidden;
}

.hero .content {
  display: flex;
  flex-wrap: wrap;
}

.hero header {
  width: 100%;
  margin: 1rem 0;
  display: block;
}

.hero header div {
  margin: 0;
}

.hero h1 {
  font-size: var(--docs-font-size-h5) !important;
  color: var(--docs-tertiary-text-color) !important;
  letter-spacing: 0 !important;
}

.hero h2 {
  font-size: var(--docs-font-size-h1);
  margin-top: 0;
}

.hero .column {
  width: 50%;
  min-width: 15rem;
  flex: auto;
}

.hero-illustration {
  height: 280px;
  margin-inline-end: calc(var(--docs-space-xl) * -1);
}

.hero-illustration svg {
  height: 460px;
}

.hero .buttons {
  display: flex;
  flex-wrap: wrap;
  gap: var(--docs-space-m);
  white-space: nowrap;
  margin: 1.5em 0;
}

.hero .buttons a {
  flex-grow: 1;
}

.hero .buttons a:first-child {
  width: 100%;
}
</style>
++++
