---
root: true
title: Docs
layout: index
---

= Vaadin 7 Docs

++++
<style>
nav[aria-label=breadcrumb] {
  display: none;
}
</style>
++++

.Official support for Vaadin 7 has ended
[IMPORTANT]
Official support for Vaadin 7 ended in February 2019. Extended commercial support is available up until 2029. See https://vaadin.com/support/vaadin-7-extended-maintenance[Vaadin 7 extended maintenance] for more information.

[.cards.quiet.large.hide-title]
== Sections

[.card]
=== Framework
image::_images/flow.svg[opts=inline, role=icon]
Use Java to build web applications.
<<framework/introduction/intro-overview#,See Framework>>

[.card]
=== Designer
image::_images/designer.svg[opts=inline, role=icon]
Create UIs visually by dragging and dropping components on a canvas.
<<designer/designer-overview#,See Designer>>

[.card]
=== Charts
image::_images/charts.svg[opts=inline, role=icon]
Feature-rich interactive graph library that answers the data visualization needs of modern web applications.
<<charts/charts-overview#,See Charts>>

[.card]
=== TestBench
image::_images/testbenchicon.svg[opts=inline, role=icon]
Create end-to-end integration tests, including visual regression tests.
<<testbench/testbench-overview#,See TestBench>>

[.card]
=== Spreadsheet
Edit Excel spreadsheets in your Vaadin applications.
<<spreadsheet/spreadsheet-overview#,See Spreadsheet>>

[.card]
=== TouchKit
Create web applications that give the look and feel of native mobile applications.
<<touchkit/mobile-overview#,See TouchKit>>
