---
root: true
title: Docs
layout: index
page-links: https://github.com/vaadin/platform/releases/tag/{moduleMavenVersion:com.vaadin:vaadin}[{moduleMavenVersion:com.vaadin:vaadin}]
---

= Vaadin Docs

++++
<style>
nav[aria-label=breadcrumb] {
  display: none;
}

[class*=layout][class*=index] {
  margin-left: var(--docs-space-xl);
  margin-right: var(--docs-space-xl);
}
</style>
++++

[.lead]
Vaadin is an open-source platform for building progressive web applications (PWAs).
It consists of a library of reusable web components and web frameworks for creating user interfaces for Java back ends.
Vaadin also offers commercial tools that speed up your development workflow.

// docs-app applies styles on <em> tags in the card headings
pass:[<!-- vale Vaadin.HeadingFormatting = NO -->]

[.cards.quiet.large.hide-title]
== Sections

[.card]
=== Beginner's Guide
image::_images/guides.svg[opts=inline, role=icon]
Introduction to Vaadin Platform and how to set up, create a project, and deploy it.
<<guide/overview#,See Framework>>

[.card]
=== Flow
image::_images/flow.svg[opts=inline, role=icon]
Use Java to build progressive web applications.
<<flow/overview#,See the Flow Framework>>

[.card]
=== Fusion
image::_images/flow.svg[opts=inline, role=icon]
Use TypeScript to build progressive web applications.
<<fusion/overview#,See the Fusion Framework>>

[.card]
=== _Design System_ Components
image::_images/components.svg[opts=inline, role=icon]
Browse the UI component library.
Both web components and Java components.
<<ds/overview#toc,See Components>>

[.card]
=== _Design System_ Charts
image::_images/charts.svg[opts=inline, role=icon]
Feature-rich interactive graph library that answers the data visualization needs of modern web applications.
<<ds/components/charts#,See Charts>>

[.card]
=== Design System
image::_images/design-system.svg[opts=inline, role=icon]
Create consistent UIs with high quality, and ease the collaboration between designers and developers.
<<ds/overview#,See Design System>>

[.card]
=== Collaboration Engine
image::_images/ce.svg[opts=inline, role=icon]
The simplest way to build real-time collaboration into web apps
<<ce/overview#,See Collaboration Engine>>

[.card]
=== Theming
image::_images/themes.svg[opts=inline, role=icon]
Learn how to customize the look and feel of the built-in web components and your application.
<<theming/overview#,See Theming>>

[.card]
=== Designer
image::_images/designer.svg[opts=inline, role=icon]
Create UIs visually by dragging and dropping components on a canvas.
<<designer/getting-started/designer-what-is-designer#,See Designer>>

[.card]
=== TestBench
// For some weird reason Vale.Spelling picks on 'testbench' if it is repeated in both the image url and the cross reference path
image::_images/testbenchicon.svg[opts=inline, role=icon]
Create end-to-end integration tests, including visual regression tests.
<<testbench/overview#,See TestBench>>
