---
title: Docs
description: Official documentation for Hilla, a full-stack web application framework.
root: true
layout: index
---

= Hilla documentation

[highlight-text]*Choose your preferred UI technology*. The Java backend is the same for both, but you can choose to build the frontend using Lit or React.

[.cards.large.hide-title]
== Choose UI technology

[.nav-link]
=== image:lit/lit-logo.svg["",opts=inline,role=icon,height=32] Lit
[.sr-only]
<<lit#,Use Hilla together with Lit>>

[.nav-link]
=== image:react/react-logo.svg["",opts=inline,role=icon,height=32] React [badge since:dev.hilla:hilla@v1.3]#New#
[.sr-only]
<<react#,Use Hilla together with React>>



[.cards.quiet.hide-title.about-footer]
== What's the difference?


=== About Lit
[.secondary-text]
Lit is a modern and lightweight alternative to React, built on top of web standards, with a similar programming model.

pass:[<!-- vale Vale.Terms = NO -->]
https://lit.dev[lit.dev]

pass:[<!-- vale Vale.Terms = YES -->]

=== About React
[.secondary-text]
React is the de-facto industry standard front-end library for building user interfaces.

https://reactjs.org[reactjs.org]

++++
<style>
html {
  --docs-article-max-width: 38rem;
}

[class*=breadcrumb],
[class*=pageNavigation] {
  display: none !important;
}

.badge {
  font-size: var(--docs-font-size-2xs);
  display: inline-block;
  padding: 0.2em 0.5em;
  margin: 0 0.5em;
  vertical-align: middle;
  border: 1px solid var(--docs-admonitionblock-tip-border-color);
  color: var(--docs-admonitionblock-tip-icon-color);
  border-radius: var(--docs-border-radius-m);
}

.badge::after {
  content: ' in ' var(--version) !important;
  font-size: inherit !important;
}

.nav-link {
  margin-top: var(--docs-space-s);
}

.nav-link::after {
  font-family: 'docs-app-icons';
  content: var(--docs-app-icons-chevron-down);
  position: absolute;
  top: 50%;
  right: var(--docs-space-m);
  font-size: 1.5rem;
  transform: translate(-50%, -50%) rotate(-90deg);
  color: var(--docs-tertiary-text-color);
}

.about-footer {
  padding-top: var(--docs-space-3xl);
}
</style>
++++
