---
root: true
title: Docs
layout: index
page-links:
  - https://github.com/vaadin/platform/releases/tag/{moduleMavenVersion:com.vaadin:vaadin}[{moduleMavenVersion:com.vaadin:vaadin}]
---

[.hero]
--
[discrete]
= Vaadin Docs

++++
<div class="column">
<h2>Develop Web Apps on Java Backends</h2>
<p class="lead">Build scalable UIs in Java or TypeScript, using the integrated tooling, components, and design system.
<a href="guide/install" class="button primary water">Get Started</a>
</p>
</div>
++++

[.column.hero-illustration]
image:_images/code-editor-illustration.svg[opts=inline]
--


[.cards.quiet.large.hide-title]
== Sections

[.card]
=== Flow
image::_images/flow.svg[opts=inline, role=icon]
Build progressive web applications using Java.
<<flow/overview#,See Flow>>

[.card]
=== Collaboration Engine
image::_images/ce.svg[opts=inline, role=icon]
The simplest way to build real-time collaboration into web apps
<<ce/overview#,See Collaboration Engine>>

[.card]
=== Charts
image::_images/charts.svg[opts=inline, role=icon]
Feature-rich interactive graph library that answers the data visualization needs of modern web applications.
<<ds/components/charts#,See Charts>>

[.card]
=== Designer
image::_images/designer.svg[opts=inline, role=icon]
Create UIs visually by dragging and dropping components on a canvas.
<<tools/designer/overview#,See Designer>>

[.card]
=== TestBench
// For some weird reason Vale.Spelling picks on 'testbench' if it is repeated in both the image url and the cross reference path
image::_images/testbench.svg[opts=inline, role=icon]
Create end-to-end integration tests, including visual regression tests.
<<tools/testbench/overview#,See TestBench>>



++++
<style>
nav[aria-label=breadcrumb] {
  display: none;
}

.hero {
  padding: var(--docs-space-m) var(--docs-space-xl);
  margin: 0 calc(var(--docs-space-xl) * -1);
  background-color: var(--docs-surface-color-2);
  border-radius: var(--docs-border-radius-l);
  overflow: hidden;
}

.hero .content {
  display: flex;
  flex-wrap: wrap;
}

.hero header {
  width: 100%;
  margin: 1rem 0;
  display: block;
}

.hero header > div {
  margin: 0;
}

.hero h1 {
  font-size: var(--docs-font-size-h5) !important;
  color: var(--docs-tertiary-text-color) !important;
}

.hero h2 {
  font-size: var(--docs-font-size-h1);
  margin-top: 0;
}

.hero .column {
  width: 50%;
  min-width: 15rem;
  flex: auto;
}

.hero-illustration {
  height: 280px;
  margin-inline-end: calc(var(--docs-space-xl) * -1);
}

.hero-illustration svg {
  height: 460px;
}

a.button.primary.water {
  display: flex;
  color: var(--button-color-dark-text);
  width: min-content;
  white-space: nowrap;
  margin: 1.5em 0;
}
</style>
++++
