---
title: Licenses
page-title: How to configure Vaadin licenses for your project
description: How commercial product license validation works, and how to get and use license keys.
meta-description: Learn how commercial product license validation works, and how to get and use license keys for your Vaadin projects. 
order: 150
---


= License Validation & Troubleshooting
:hide-uri-scheme:

Vaadin core includes an extensive set of technologies and components that are free to use.
Vaadin core is available under the terms of the Apache License 2.0, which allows you to use what's included in any project -- even commercially.

You need a commercial license only if you use one of the commercial components (e.g., Vaadin Charts) or one of the tools (e.g., Vaadin TestBench). If a project includes such components or tools, a commercial license is needed for development, and to build a production application.

Vaadin requires a production runtime license only for a Premium subscription which counts <<{articles}/flow/configuration/licenses/daily-active-users#, Daily Active Users>>. Starting in version 24.5, Collaboration Kit is free. Previously, it was priced per end-user (see <<{articles}/tools/collaboration/developing-with-ce#,Collaboration Kit documentation>>). 

For other use cases, you don't need a license after deploying an application to production.


[[online-license-key]]
== Local License Validation

On a local machine, the licenses for commercial components and tools are checked automatically using your Vaadin account. The first time you use a commercial component or tool, you'll be asked to log into `vaadin.com` to validate your license.

Once validated, you can continue developing your project. A license key is created on your machine in the following location:

[.example]
--
[source,filesystem]
----
<source-info group="Windows"></source-info>
%userprofile%\.vaadin\proKey
----

[source,filesystem]
----
<source-info group="macOS/Linux"></source-info>
~/.vaadin/proKey
----
--


[since:com.vaadin:vaadin@V23.2]
[[offline-license-key]]
=== Offline License Key

If your local development environment is offline and can't reach `vaadin.com`, you'll need to get an offline license key.

Each offline license key is tied to the machine ID, in the form of `mid-xxxxxxxx-xxxxxxxx`. You'll have to submit that to `https://vaadin.com/myaccount/licenses`, so as to download an offline license key.

Once you've downloaded the [filename]`offlineKey` file -- remove any [filename]`.txt` suffix-- you should place it in your home directory:

[.example]
--
[source,filesystem]
----
<source-info group="Windows"></source-info>
%userprofile%\.vaadin\offlineKey
----

[source,filesystem]
----
<source-info group="macOS/Linux"></source-info>
~/.vaadin/offlineKey
----
--


==== Machine ID

You can find your machine ID in the logs when you try to use a commercial component or tool offline without an existing license key. You can also find it by running the following commands on your machine:

[.example]
--
[source,terminal]
----
<source-info group="Windows"></source-info>
mvn dependency:get -Dartifact=com.vaadin:license-checker-machineid:1.8.1
java -jar %userprofile%\.m2\repository\com\vaadin\license-checker-machineid\1.8.1\license-checker-machineid-1.8.1.jar
----

[source,terminal]
----
<source-info group="macOS/Linux"></source-info>
mvn dependency:get -Dartifact=com.vaadin:license-checker-machineid:1.8.1 && java -jar ~/.m2/repository/com/vaadin/license-checker-machineid/1.8.1/license-checker-machineid-1.8.1.jar
----
--


[[server-license-key]]
== Validation on CI/CD or Build Server

For CI/CD/build servers, you'll need to download a server license key. These can only be used for production builds. You can download such a key (i.e., an [filename]`offlineKey` file) from `https://vaadin.com/myaccount/licenses`.

You should place the [filename]`offlineKey` file in the home directory of the CI server like so:

[.example]
--
[source,filesystem]
----
<source-info group="Windows"></source-info>
%userprofile%\.vaadin\offlineKey
----

[source,filesystem]
----
<source-info group="macOS/Linux"></source-info>
~/.vaadin/offlineKey
----
--

You can also give the license key by using the `vaadin.offlineKey` system property or the `VAADIN_OFFLINE_KEY` environment variable. Copy the license key string value from the [filename]`offlineKey` file.

[.example]
--
[source,terminal]
----
<source-info group="System property"></source-info>
mvn -Dvaadin.offlineKey=[contents of offlineKey file here] ...
----

[source,terminal]
----
<source-info group="Environment variable"></source-info>
VAADIN_OFFLINE_KEY=[contents of offlineKey file here] mvn ...
----
--


== Troubleshooting

If you encounter license‑related issues such as receiving a trial message despite having a valid license, offline validation errors, or CI/CD build issues, see our https://vaadin.com/licensing-faq-and-troubleshooting[Licensing FAQ and Troubleshooting Guide] for detailed assistance.

include::{root}/articles/flow/kb/index.adoc[tag=licenses]

[discussion-id]`D56655EB-4310-49FF-8A81-E790235E1420`
