---
title: Licenses
description: How commercial product license validation works, and how to get and use license keys.
order: 150
---


= License Validation & Troubleshooting
:hide-uri-scheme:

Vaadin core includes an extensive set of technologies and components that are free to use.
Vaadin core is available under the terms of the Apache License 2.0, which allows you to use what's included in any project -- even commercially.

You need a commercial license only if you use one of the commercial components (e.g., Vaadin Charts) or tools (e.g., Vaadin TestBench). If a project includes such components or tools, a commercial license is needed for development and to build the production application.

Vaadin requires production runtime license only for a Premium subscription that counts <<{articles}/flow/configuration/licenses/daily-active-users#, Daily Active Users>>. Before for Vaadin 24.5, the Collaboration Kit is priced per end-user -- see <<{articles}/tools/collaboration/developing-with-ce#,Collaboration Kit documentation>> for details. Starting in Vaadin 24.5, Collaboration Kit is free.

For other use cases, you don't need a license after deploying an application to production.


[[online-license-key]]
== Local License Validation

On a local machine, the licenses for commercial components and tools are checked automatically using your Vaadin account. The first time you use a commercial component or tool, you'll be asked to log in to `vaadin.com` to validate your license.

Once validated, you can continue developing your project. A license key is created on your machine in the following location:

[.example]
--
[source,filesystem]
----
<source-info group="Windows"></source-info>
%userprofile%\.vaadin\proKey
----

[source,filesystem]
----
<source-info group="macOS/Linux"></source-info>
~/.vaadin/proKey
----
--


[since:com.vaadin:vaadin@V23.2]
[[offline-license-key]]
=== Offline License Key

If your local development environment is offline and can't reach `vaadin.com`, you'll need to download an offline license key.

Each offline license key is tied to a machine ID, in the form of `mid-xxxxxxxx-xxxxxxxx`. You'll have to submit that to `https://vaadin.com/myaccount/licenses`, so as to download an offline license key.

Once you have downloaded the [filename]`offlineKey` file -- remove any [filename]`.txt` suffix-- you should place it in your home directory:

[.example]
--
[source,filesystem]
----
<source-info group="Windows"></source-info>
%userprofile%\.vaadin\offlineKey
----

[source,filesystem]
----
<source-info group="macOS/Linux"></source-info>
~/.vaadin/offlineKey
----
--


==== Machine ID

You can find your machine ID in the logs when you try to use a commercial component or tool offline without an existing license key. You can also find it by running the following commands on your machine:

[.example]
--
[source,terminal]
----
<source-info group="Windows"></source-info>
mvn dependency:get -Dartifact=com.vaadin:license-checker-machineid:1.8.1
java -jar %userprofile%\.m2\repository\com\vaadin\license-checker-machineid\1.8.1\license-checker-machineid-1.8.1.jar
----

[source,terminal]
----
<source-info group="macOS/Linux"></source-info>
mvn dependency:get -Dartifact=com.vaadin:license-checker-machineid:1.8.1 && java -jar ~/.m2/repository/com/vaadin/license-checker-machineid/1.8.1/license-checker-machineid-1.8.1.jar
----
--


[[server-license-key]]
== Validation on CI/CD or Build Server

For CI/CD/build servers, you'll need to download a server license key. These can only be used for production builds. You can download such a key (i.e., an [filename]`offlineKey` file) from `https://vaadin.com/myaccount/licenses`.

You should place the [filename]`offlineKey` file in the home directory of the CI server like so:

[.example]
--
[source,filesystem]
----
<source-info group="Windows"></source-info>
%userprofile%\.vaadin\offlineKey
----

[source,filesystem]
----
<source-info group="macOS/Linux"></source-info>
~/.vaadin/offlineKey
----
--

You can also give the license key using the `vaadin.offlineKey` system property or the `VAADIN_OFFLINE_KEY` environment variable. Copy the license key string value from the [filename]`offlineKey` file.

[.example]
--
[source,terminal]
----
<source-info group="System property"></source-info>
mvn -Dvaadin.offlineKey=[contents of offlineKey file here] ...
----

[source,terminal]
----
<source-info group="Environment variable"></source-info>
VAADIN_OFFLINE_KEY=[contents of offlineKey file here] mvn ...
----
--


== Troubleshooting

include::{root}/articles/flow/kb/index.adoc[tag=licenses]

[discussion-id]`D56655EB-4310-49FF-8A81-E790235E1420`
