---
title: Licenses
page-title: How to configure Vaadin licenses for your project
description: How commercial product license validation works, and how to get and use license keys.
meta-description: Learn how commercial product license validation works, and how to get and use license keys for your Vaadin projects.
order: 150
---


= License Validation & Troubleshooting
:hide-uri-scheme:

Vaadin core includes an extensive set of technologies and components that are free to use.
Vaadin core is available under the terms of the Apache License 2.0, which allows you to use what's included in any project -- even commercially.

You need a commercial license only if you use one of the commercial components (e.g., Vaadin Charts) or one of the tools (e.g., Vaadin TestBench). If a project includes such components or tools, a commercial license is needed for development, and to build a production application.

For other use cases, you don't need a license after deploying an application to production.

== Using Free Trials

The Vaadin Trial experience lets you evaluate all Vaadin commercial features - such as Vaadin Copilot, commercial components (e.g., Charts), Acceleration Kits and Control Center - with minimal effort:

- 7‑day Trial (no registration needed): Start instantly by clicking a button in the development tooling of a started Vaadin application,
- 30‑day Commercial Trial (registration required): Extend your evaluation by signing in to `vaadin.com`.

Both trials enable commercial features in development. Production builds during trials are allowed with an opt‑in flag and will display a visible runtime banner.

A trial period can be activated through Vaadin Dev Tools by clicking the `}>` button in the right bottom corner of the application's page and also through the automatic splash screen shown when a commercial component is used without a license.

=== 7-day Trial Workflow (Seven-Day, No Registration)

When you use a commercial feature (for example, place a commercial component on a view or trigger a Vaadin Copilot function that makes changes to source code) and no valid license is found, a modal splash screen appears in development mode once you navigate to a view that uses a commercial component. It explains that a subscription or trial is required and offers two choices:

- Try for 7 days (no registration): Starts the 7‑day trial immediately.
- Log in / Sign up (to acquire or extend a license/trial): Opens Vaadin web-site to sign in and retrieve a license key or start the 30‑day trial.

It also shows the following information:
- Link to the commercial license terms
- Examples of Vaadin commercial products you have full access to.

=== 30‑Day Commercial Trial Workflow (Registration Required)

If you choose Log in / Sign up from the splash screen, or when your 7-day Trial has expired, you’ll be guided to authenticate and start a 30‑day trial. This enables all commercial features for 30 days.

When a 7-day Trial expires, the splash screen shows guidance to "Extend trial 30 days" (via the login path). Once button is clicked, the trial starts immediately.

The 30‑day trial can be started again after 90 days per user/account.

=== Production Builds While Using a Trial

Production builds do not enable commercial features if you don’t have a valid license. However, you can opt‑in to enable commercial features in production builds by adding a `-Dvaadin.commercialWithBanner` system property or `commercialWithBanner` Vaadin plugin parameter that shows a visible persistent banner on the bottom of the page in runtime.

The banner links to the https://vaadin.com/commercial-license-info[Commercial License Info] page. It is closable, but reappears on page reload.

[.example]
--
[source,terminal]
----
<source-info group="Maven"></source-info>
mvn package -Pproduction -Dvaadin.commercialWithBanner
----
[source,groovy]
----
<source-info group="Groovy"></source-info>
./gradlew build -Pvaadin.productionBuild -Pvaadin.commercialWithBanner
----
--

[[online-license-key]]
== Local License Validation

On a local machine, the licenses for commercial components and tools are checked automatically using your Vaadin account. The first time you use a commercial component or tool, you'll be asked to log into `vaadin.com` to validate your license.

Once validated, you can continue developing your project. A license key is created on your machine in the following location:

[.example]
--
[source,filesystem]
----
<source-info group="Windows"></source-info>
%userprofile%\.vaadin\proKey
----

[source,filesystem]
----
<source-info group="macOS/Linux"></source-info>
~/.vaadin/proKey
----
--


[since:com.vaadin:vaadin@V23.2]
[[offline-license-key]]
=== Offline License Key

If your local development environment is offline and can't reach `vaadin.com`, you'll need to get an offline license key.

Each offline license key is tied to the machine ID, in the form of `mid-xxxxxxxx-xxxxxxxx`. You'll have to submit that to `https://vaadin.com/myaccount/licenses`, so as to download an offline license key.

Once you've downloaded the [filename]`offlineKey` file -- remove any [filename]`.txt` suffix-- you should place it in your home directory:

[.example]
--
[source,filesystem]
----
<source-info group="Windows"></source-info>
%userprofile%\.vaadin\offlineKey
----

[source,filesystem]
----
<source-info group="macOS/Linux"></source-info>
~/.vaadin/offlineKey
----
--


==== Machine ID

You can find your machine ID in the logs when you try to use a commercial component or tool offline without an existing license key. You can also find it by running the following commands on your machine:

[.example]
--
[source,terminal]
----
<source-info group="Windows"></source-info>
mvn dependency:get -Dartifact=com.vaadin:license-checker-machineid:1.8.1
java -jar %userprofile%\.m2\repository\com\vaadin\license-checker-machineid\1.8.1\license-checker-machineid-1.8.1.jar
----

[source,terminal]
----
<source-info group="macOS/Linux"></source-info>
mvn dependency:get -Dartifact=com.vaadin:license-checker-machineid:1.8.1 && java -jar ~/.m2/repository/com/vaadin/license-checker-machineid/1.8.1/license-checker-machineid-1.8.1.jar
----
--


[[server-license-key]]
== Validation on CI/CD or Build Server

For CI/CD/build servers, you'll need to download a server license key. These can only be used for production builds. You can download such a key (i.e., an [filename]`offlineKey` file) from `https://vaadin.com/myaccount/licenses`.

You should place the [filename]`offlineKey` file in the home directory of the CI server like so:

[.example]
--
[source,filesystem]
----
<source-info group="Windows"></source-info>
%userprofile%\.vaadin\offlineKey
----

[source,filesystem]
----
<source-info group="macOS/Linux"></source-info>
~/.vaadin/offlineKey
----
--

You can also give the license key by using the `vaadin.offlineKey` system property or the `VAADIN_OFFLINE_KEY` environment variable. Copy the license key string value from the [filename]`offlineKey` file.

[.example]
--
[source,terminal]
----
<source-info group="System property"></source-info>
mvn -Dvaadin.offlineKey=[contents of offlineKey file here] ...
----

[source,terminal]
----
<source-info group="Environment variable"></source-info>
VAADIN_OFFLINE_KEY=[contents of offlineKey file here] mvn ...
----
--


== Troubleshooting

If you encounter license‑related issues such as receiving a trial message despite having a valid license, offline validation errors, or CI/CD build issues, see our https://vaadin.com/licensing-faq-and-troubleshooting[Licensing FAQ and Troubleshooting Guide] for detailed assistance.

include::{root}/articles/flow/kb/index.adoc[tag=licenses]

[discussion-id]`D56655EB-4310-49FF-8A81-E790235E1420`
