---
title: Designing Apps
description: The basics of designing user interfaces for Vaadin applications.
order: 790
section-nav: flat expanded
---


= Designing Applications the Vaadin Way

.Work in Progress
[IMPORTANT]
This section of the documentation is still being written. Its content is useful, but several parts have not yet been added.

The primary focus when designing an application should be the user. Understanding their needs, goals, and challenges is key to creating a meaningful user experience. An application is only as good as its ability to solve problems efficiently and intuitively.

Ideally, developers should engage directly with users to grasp fully what they're trying to accomplish. This can be done through interviews, surveys, or usability tests. These can provide valuable insights into users' motivations and pain points. However, developers don't always have direct access to users. Therefore, you'll have to imagine the user experience while using the application.

Many common challenges can be addressed by applying established UI/UX best practices. This includes focusing on clarity, simplicity, and ease of navigation. Avoid what's often referred to as 'Developer UX'. This is a method in which the application becomes a reflection of a database or a feature dump. This approach typically leads to a cluttered, overwhelming experience -- particularly for non-technical users. It makes the application unnecessarily difficult to use.

A user-centered design approach should involve constant reflection on what users need at each stage. By prioritizing key features, using layouts that are easy to follow, and adhering to design principles like accessibility, performance, and consistency, you can create a streamlined, practical UI.

Ultimately, successful design balances functionality with user empathy, paying attention to visual hierarchy, responsiveness, simplicity, and user feedback—even when actual user input is limited.


== Topics

section_outline::[]
