---
title: Icons
layout: tabbed-page
tab-title: Lumo Icons
---

= Lumo Icons

Lumo icons are designed to fit in with the default Lumo theme style.

[source, typescript, role="render-only embedded"]
----
include::../../../../frontend/demo/foundation/lumo-icons.ts[render, persistent]
----

The icons are drawn on a 24&times;24 pixel canvas.
There is a safe area of approximately 4 pixels around the icon – giving a 16&times;16 pixel active area for the icon itself – allowing for optimizing each icon for visual/optical balance.


== Usage

In server-side views (Flow/Java):

[source, java]
----
Icon icon = new Icon('lumo:photo');
----

In client-side views (Fusion/TypeScript):

[source, typescript]
----
import { html, LitElement, customElement } from 'lit-element';
import '@vaadin/vaadin-lumo-styles/icons';

@customElement('photo-icon-example')
export class PhotoIconExample extends LitElement {
  render() {
    return html`<iron-icon icon="lumo:photo"></iron-icon>`;
  }
}
----

See the documentation for the <<../../components/icon#,Icon>> component for more information.


=== Advanced usage (Fusion/TypeScript usage)

If you need to be in control of when or how https://www.webcomponents.org/element/PolymerElements/iron-icon[iron-icon] is imported, you may import `iconset.js` instead of `icons.js`.
The `iconset.js` file imports only the icon definitions (`iron-iconset-svg`) without automatically importing the `iron-icon` element.


== Size

++++
<style>
.space.custom-property-preview {
  font-size: var(--lumo-font-size-m);
}
.space.custom-property-preview::before {
  padding: calc(var(--value) * 0.5);
  border-radius: var(--docs-border-radius-s);
}
</style>
++++

Use the icon size custom properties to set consistent sizes for all icons across your application.
The Lumo icons are drawn on a 24&times;24 pixel canvas – the **M size** fits that by default.

In client-side views (Fusion/TypeScript), you need to import the <<size-space#,sizing>> style sheet to use the sizing properties.

[source, typescript]
----
import '@vaadin/vaadin-lumo-styles/sizing';
----

[.property-listing.previews, cols="1,>1"]
|===
| Description | CSS Custom Property

| [.preview(--lumo-icon-size-l).space]*Large icon* +
| [custom-property]#--lumo-icon-size-l#

| [.preview(--lumo-icon-size-m).space]*Medium icon* +
Default size
| [custom-property]#--lumo-icon-size-m#

| [.preview(--lumo-icon-size-s).space]*Small icon* +
| [custom-property]#--lumo-icon-size-s#
|===
