---
title: Styling
page-title: How to style the Rich Text Editor | Vaadin components
description: Styling API reference for the Rich Text Editor component.
meta-description: Customize the Vaadin Rich Text Editor component to align with your application’s theme and branding.
order: 50
---
= Rich Text Editor Styling

== Theme Variants

=== Compact

[cols="1,3,1"]
|===
| Variant | Description | Supported by

|`compact`
| Makes the toolbar more compact
| Lumo
|===

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/richtexteditor/rich-text-editor-theme-compact.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorThemeCompact.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]


ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/richtexteditor/react/rich-text-editor-theme-compact.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--


=== No Border

[cols="1,3,1"]
|===
| Variant | Description | Supported by

|`no-border`
| Removes the border around the editor
| Lumo
|===

[.example]
--

ifdef::lit[]
[source,html]
----
include::{root}/frontend/demo/component/richtexteditor/rich-text-editor-theme-no-border.ts[render,tags=snippet,indent=0,group=Lit]
----
endif::[]

ifdef::flow[]
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorThemeNoBorder.java[render,tags=snippet,indent=0,group=Flow]
----
endif::[]


ifdef::react[]
[source,tsx]
----
include::{root}/frontend/demo/component/richtexteditor/react/rich-text-editor-theme-no-border.tsx[render,tags=snippet,indent=0,group=React]
----
endif::[]
--

include::../_styling-section-intros.adoc[tag=properties]


[cols="1,3,1"]
|===
| Property | Supported by

| `--vaadin-rich-text-editor-toolbar-background`
| Aura

| `--vaadin-rich-text-editor-toolbar-padding`
| Aura

| `--vaadin-rich-text-editor-toolbar-gap`
| Aura

| `--vaadin-rich-text-editor-toolbar-button-background`
| Aura

| `--vaadin-rich-text-editor-toolbar-button-border-radius`
| Aura

| `--vaadin-rich-text-editor-toolbar-button-padding`
| Aura

| `--vaadin-rich-text-editor-toolbar-button-text-color`
| Aura

| `--vaadin-rich-text-editor-background`
| Aura

|===


include::../_styling-section-intros.adoc[tag=selectors]


Root element:: `vaadin-rich-text-editor`


=== States

Read-only:: `vaadin-rich-text-editor+++<wbr>+++**[readonly]**`
Disabled:: `vaadin-rich-text-editor+++<wbr>+++**[disabled]**`
Hovered:: `vaadin-rich-text-editor+++<wbr>+++**:hover**`


=== Toolbar

Toolbar:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar)**`
Toolbar button groups:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-group)**`
History button group:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-group-history)**`
Toolbar buttons:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button)**`
Toolbar button toggled on:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-pressed)**`
Undo button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-undo)**`
Redo button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-redo)**`
Emphasis button group:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-group-emphasis)**`
Bold button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-bold)**`
Italic button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-italic)**`
Underline button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-underline)**`
Strikeout button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-strike)**`
Style button group:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-group-style)**`
Text color button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-color)**`
Background button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-background)**`
Heading button group:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-group-heading)**`
H1 button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-h1)**`
H2 button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-h2)**`
H3 button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-h3)**`
Glyph transformation button group:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-group-glyph-transformation)**`
Subscript button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-subscript)**`
Superscript button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-superscript)**`
List button group:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-group-list)**`
Ordered list button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-list-ordered)**`
Bullet list button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-list-bullet)**`
Alignment button group:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-group-alignment)**`
Align left button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-align-left)**`
Align center button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-align-center)**`
Align right button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-align-right)**`
Rich content button group:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-group-rich-text)**`
Image button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-image)**`
Link button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-link)**`
Text block button group:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-group-block)**`
Block quote button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-blockquote)**`
Code block button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-code-block)**`
Format button group:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-group-format)**`
Clean formatting button:: `vaadin-rich-text-editor+++<wbr>+++**::part(toolbar-button-clean)**`


=== Content

Content area:: `vaadin-rich-text-editor+++<wbr>+++**::part(content)**`
