---
title: Themes
order: 20
layout: page
---

= Themes

Themes are a collection of style sheets, fonts, and icons that define the look and feel of components.
A theme can also define utility styles that you can use in application views.

The built-in themes are customizable and provide a great starting point for an application.

== Applying a Theme

Set the [classname]#@Theme# annotation on the application shell class.

[source, Java]
----
@Theme(themeClass = Lumo.class)
public class Application extends SpringBootServletInitializer {
  ...
}
----

== Customizing a Theme

See <<custom-theme#, Custom Theme>>.

== No Theme

You can opt-out of loading any theme if you want to control the importing of style sheets manually.
This means that you rely on application-specific style sheets to also handle component styling.
You are also responsible for any lazy-loading or code-splitting of the style sheets.

Use the [classname]#@NoTheme# annotation to opt-out of loading any theme style sheets.

[source,java]
----
@NoTheme
public class Application extends SpringBootServletInitializer {
  ...
}
----

In client-side views/templates, to get a minimal starting point, import the un-themed version of each component.
For Vaadin components, the un-themed versions are located in the [filename]`src` folder of each component package.

[source, TypeScript]
----
// For example, if you are using the <vaadin-button> component,
// import the un-themed version
import '@vaadin/vaadin-button/src/vaadin-button.js';
----


== Theme Resolving Order

pass:[<!-- vale Vaadin.Passive = NO -->]

The following logic is used to determine which theme is used:

. If the `@Theme` annotation is found on the application shell class, the theme set in the annotation is used
. If the `@NoTheme` annotation is found on the application shell class, no theme style sheets are loaded
. If the `com.vaadin.flow.theme.lumo.Lumo` class is available in the classpath, the Lumo theme is used

Resolving stops when a match is found.
No theme is used if none of the conditions are met.

pass:[<!-- vale Vaadin.Passive = YES -->]


== Limitations

Themes can't be switched at runtime::
Full page reload is required.
You can't for example use different themes for different views.

Component themes can't be mixed::
For example, you can't use the Lumo theme for Date Picker and the Material theme for Button at the same time, because Date Picker internally uses the Button component.
If you did, both themes would be applied simultaneously and would cause style conflicts.
+
This mainly affects client-side development, where you have fine-grained control over the component imports which you use in your views and templates.
