name: 'First interaction'
description: 'Greet new contributors when they create their first issue or open their first pull request'
author: 'Vaadin'
inputs:
  repo-token:
    description: {{ secrets.GITHUB_TOKEN }}
    required: true
  pr-message:
    description: 'Thank you for submitting your first PR! If you plan to contribute more extensively to the Vaadin documentation, you should familiarize yourself with the [documentation contribution guidelines](https://vaadin.com/docs/latest/contributing-docs/overview).'
runs:
  using: 'docker'
  image: 'Dockerfile'
