name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      continue-on-error: true
      with:
        repo-token: ${{ secrets.repo_greeting }}
        issue-message: 'Thanks for using Vaadin! We appreciate helping us to have better documentation and we’ll take care of this as soon as possible.'
        pr-message: 'Thank you for submitting your first PR! If you plan to contribute more extensively to the Vaadin documentation, you should familiarize yourself with the [documentation contribution guidelines](https://vaadin.com/docs/latest/contributing-docs/overview).'
