name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      continue-on-error: true
      with:
        repo-token: ${{ secrets.repo_greeting }}
        issue-message: 'Thanks for using Hilla! We appreciate you helping us to have better documentation and we’ll take care of this as soon as possible.'
