name: Lint
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: errata-ai/vale-action@master
        with:
          config: https://raw.githubusercontent.com/vaadin/docs/vale-config/.github/.vale-pr.ini
          files: __onlyModified
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
