name: lint
on:
  pull_request:
    types: [reopened, synchronize, labeled, unlabeled]
  repository_dispatch:
    types: [trigger-required-labels]
jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: errata-ai/vale-action@master
        with:
          config: https://raw.githubusercontent.com/vaadin/docs/vale-config/.github/.vale-pr.ini
          files: __onlyModified
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  labels:
    name: Content labels are resolved
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: 'AsciiDoc, Java, TypeScript'
