name: PR Writing Style Report

on:
  pull_request:

jobs:
  review-docs-pr:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout scripts directory
          uses: actions/checkout@v3
          with:
            repository: vaadin/docs
            path: .
            sparse-checkout: scripts/

        - uses: actions4gh/setup-gh@v1.0.2

        - name: Fetch changes and review them
          id: review
          run: |
            # Run the script to fetch changes and send them to OpenAI
            R=`./scripts/ratePR.sh ${{ github.event.pull_request.number }} ${{ github.repository }}` || exit 1

            # show response from OpenAI
            set -x
            R=`echo "$R" | jq -r '.choices[0].message.content'` || exit 1
            set +x

            # store response in output variable 'result'
            echo "result<<EOF" >> $GITHUB_OUTPUT
            echo -e "## AI Review \n\n$R" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          shell: bash

        - if: ${{ success() && steps.review.outputs.result }}
          uses: peter-evans/find-comment@v1
          id: fc
          with:
            issue-number: ${{ github.event.pull_request.number }}
            body-includes: AI Review

        - if: ${{ success() && steps.review.outputs.result }}
          uses: peter-evans/create-or-update-comment@v1
          with:
            comment-id: ${{ steps.fc.outputs.comment-id }}
            issue-number: ${{ github.event.pull_request.number }}
            body: ${{ steps.review.outputs.result }}

