name: PR Writing Style Report

on:
  pull_request:

jobs:
  review-docs-pr:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout scripts directory
          uses: actions/checkout@v3
          with:
            repository: vaadin/docs
            path: .
            sparse-checkout: scripts/

        - uses: actions4gh/setup-gh@v1.0.2

        - name: Fetch changes and review them
          id: fetch_and_review_changes
          run: |
            R=`./scripts/ratePR.sh ${{ github.event.pull_request.number }} ${{ github.repository }}` || exit 1
            set -x
            R=`echo "$R" | jq -r '.choices[0].message.content'` || exit 1
            set +x

            echo "result<<EOF" >> $GITHUB_OUTPUT
            echo -e "$R" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          shell: bash

        - name: Post comment on PR
          if: ${{ success() && steps.fetch_and_review_changes.outputs.result && github.event_name == 'pull_request' }}
          uses: peter-evans/create-or-update-comment@v1
          with:
           issue-number: ${{ github.event.pull_request.number }}
           body: ${{ steps.fetch_and_review_changes.outputs.result }}
