---
title: Install a JDK
page-title: Install a Java Development Kit (JDK) for Vaadin
description: Install a Java Development Kit (JDK) for Vaadin development if you don't have one already.
meta-description: Install a JDK for Vaadin development. Step-by-step instructions for Eclipse Temurin on Windows, macOS, and Linux, plus SDKMAN and other OpenJDK distributions.
order: 5
---

include::{articles}/_vaadin-version.adoc[]

= Install a JDK

Vaadin requires a Java Development Kit (JDK), version {vaadin-start-java-version} or newer. If you don't have one already, install link:https://adoptium.net/temurin/releases/[Eclipse Temurin], a free OpenJDK distribution that works well with Vaadin. Pick the latest Long Term Support (LTS) version.


== Install Eclipse Temurin

. Go to the link:https://adoptium.net/temurin/releases/[Temurin releases page] and select the latest LTS version, your operating system, and your processor architecture.
. Download the installer: the `.msi` package on Windows, or the `.pkg` package on macOS. On Linux, use your distribution's package manager if it offers Temurin. Otherwise, download the `.tar.gz` archive and extract it.
. Run the installer with the default options. On Windows, also select the option to set the `JAVA_HOME` variable, since IDEs and build tools use it to find the JDK.
. Open a new terminal and verify the installation:
+
[source,terminal]
----
java -version
----
+
The output should name a Temurin build of the version you installed.

Your JDK is now ready. Continue by <<install-ide#,installing an IDE>>.


== Other Options

Any JDK distribution based on link:https://openjdk.org/[OpenJDK] works with Vaadin. If you're unsure which one to pick, see the link:https://whichjdk.com/[whichjdk.com] website for independent, yet opinionated recommendations.


=== SDKMAN for macOS and Linux

If you use macOS or Linux, a more flexible way of installing a JDK is to use SDKMAN. SDKMAN is a tool that lets you install and switch between multiple JDKs through a command line interface.

Install SDKMAN by following the link:https://sdkman.io/install[SDKMAN installation instructions]. After that, install the latest stable version of Java by running the following command:

[source,terminal]
----
sdk install java
----

You can also install a specific version of a specific JDK. See the link:https://sdkman.io/usage[SDKMAN usage instructions] for more information.
