---
title: Using Parent Layout
order: 19
banner: Polymer support is deprecated. Use link:../[Lit templates] instead.
banner-id: polymer-templates
banner-style: caution
---

= [deprecated:com.vaadin:vaadin@V18]#Using Parent Layout#

:admonition:
include::index.asciidoc[tag=deprecation-notice]

A `PolymerTemplate` can be used as a parent layout by using the `<slot>` in the position where the child view should be displayed.

You can see in the example the JavaScript Polymer template showing the actual view, [classname]`MainLayout`, below a heading and menu:

[source,javascript]
----
import { PolymerElement, html } from '@polymer/polymer/polymer-element.js';

class MainLayout extends PolymerElement {
  static get template() {
    return html`
      <h1>Site title</h1>
      <div class="menu">...</div>
      <!-- child content comes here -->
      <slot></slot>
    `;
  }

  static get is() {
    return 'main-layout';
  }
}

customElements.define(MainLayout.is, MainLayout);
----

To use this template file, you need a basic Java template class that's mapped to the JavaScript template file -- using the `@JsModule` annotation -- and that implements the [interfacename]`RouterLayout` interface.

This example shows a mapped Java template class that imports the JavaScript template and implements [interfacename]`RouterLayout`:

[source,java]
----
@Tag("main-layout")
@JsModule("./com/example/main-layout.js")
public class MainLayout extends PolymerTemplate<TemplateModel>
        implements RouterLayout {
}
----

The [methodname]`showRouterLayoutContent(HasElement)` method in the [interfacename]`RouterLayout` interface has a default implementation. This makes it unnecessary to write additional code, but you can override and re-implement it, if necessary.

You can now use [classname]`MainLayout` as a parent layout using the `@Route` or `@ParentLayout` annotations.

This example is using the `layout` parameter in the `@Route` annotation to mark [classname]`MainLayout` as the parent layout:

[source,java]
----
@Route(value="editor", layout=MainLayout.class)
public class Editor extends Div {
}
@ParentLayout(MainLayout.class)
public class MenuBar extends Div {
}
----

See <<{articles}/routing/layout#,Router Layouts and Nested Router Targets>> for more about parent views, and <<polymer-template-basic#,Creating a Simple Component Using the Template API>> for general information about the `PolymerTemplate` API.


[discussion-id]`24E23F32-0623-456B-8F09-EE90F9605FA4`
