---
title: Editor Settings
description: How to organize your development environment for Vaadin documentation contributions.
order: 10
---


= Editor Settings for Contributors
:experimental:
:commandkey: &#8984;

Setting up your development environment as do Vaadin employees makes it easier to review and accept code contributions.

== General Formatting Rules

- *Spaces instead of tabs*
- *UTF-8 encoding*
- *Unix-style line endings* `\n`

== Code Conventions

++++
<style>
.hide-source-title [class*=sourcesAndControls] {
  display: none;
}
</style>
++++

[.example.hide-source-title]
--
. Open menu:Window[Preferences] (Windows) or menu:Eclipse[Preferences] (Mac)
. On the menu:Java[Code Style > Formatter] page, import your local copy of link:https://github.com/vaadin/flow/blob/master/eclipse/VaadinJavaConventions.xml[VaadinJavaConventions.xml]
. On the menu:Java[Code Style > Organize Imports] page, import your local copy of link:https://github.com/vaadin/flow/blob/master/eclipse/flow.importorder[flow.importorder]
. On the menu:Editor[Save Actions] tab, make sure that in case [guilabel]*Format source code* is active, the [guilabel]*Format edited lines option* is selected.
Never use the [guilabel]*Format all lines* option, as that may introduce loads of unnecessary code changes, making code reviews a nightmare.
. Go to menu:General[Workspace]
.. Set [guilabel]*Text file encoding* to *UTF-8*
.. Set [guilabel]*New text file line delimiter* to *Unix*
. Go to menu:XML[XML Files > Editor] and ensure the settings are configured as follows:
- [guilabel]*Line width*: *72*
- [guilabel]*Format comments*: *true*
- [guilabel]*Join lines*: *true*
- [guilabel]*Insert whitespace before closing empty end-tags*: *true*
- [guilabel]*Indent using spaces*: *true*
- [guilabel]*Indentation size*: *4*

[source,java]
----
<source-info group="Eclipse"></source-info>
----

. Install the [guilabel]*Eclipse Code Formatter* plugin, then restart IDEA
. Open [guilabel]*Settings* (kbd:[Ctrl + Alt + S] or kbd:[{commandkey} + ,])
. On the menu:Other Settings[Eclipse Code Formatter] page
.. Check [guilabel]*Use the Eclipse code formatter*
.. In the [guilabel]*Supported file types* section, check [guilabel]*Enable Java*
.. In [guilabel]*Eclipse Java Formatter config file*, browse to your local copy of link:https://github.com/vaadin/flow/blob/master/eclipse/VaadinJavaConventions.xml[VaadinJavaConventions.xml]
. Go to menu:Editor[Code Style], and set [guilabel]*Hard wrap at (columns)* to *80*

*Imports*

. Open [guilabel]*Settings* (kbd:[Ctrl + Alt + S] or kbd:[{commandkey} + ,])
. Go to menu:Editor[General > Auto Import] and un-check [guilabel]*Optimize imports on the fly*
. Go to menu:Editor[Code Style > Java] and on the [guilabel]*Imports* tab
.. Make sure that [guilabel]*Use single class import* is checked
.. Set both [guilabel]*Class count to use import with '+++*+++'* and [guilabel]*Names count to use static import with '+++*+++'* to *99*
.. On the [guilabel]*Import Layout* pane, make sure that [guilabel]*Layout static imports separately* is checked
.. Remove all the packages in the list [guilabel]*Packages to Use Import with '+++*+++'*
.. Organize Java imports to comply to the convention defined below:

[source,java]
----
<source-info group="IntelliJ IDEA"></source-info>
import javax.*
import java.*
<blank line>
import all other imports
<blank line>
import com.google.gwt.*
import com.vaadin.*
<blank line>
import elemental.*
import static all other imports
----
--

== Copyright Notice

All source code files need to include a copyright notice at the beginning of the file.

[.example]
--
. Open menu:Window[Preferences] (Windows) or menu:Eclipse[Preferences] (Mac)
. On the menu:Java[Code Style > Code Templates] page, edit the menu:Comments[Files] template to add the copyright text:

[.wrap-lines]
[source,txt]
----
<source-info group="Eclipse"></source-info>
Copyright 2000-${currentDate:date('yyyy')} Vaadin Ltd.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under
the License.
----


. Open [guilabel]*Settings* (kbd:[Ctrl + Alt + S] or kbd:[{commandkey} + ,])
. Go to menu:Editor[Copyright > Copyright Profiles] and create a new profile named *Vaadin*, with the copyright text as defined below.
. Go one level higher, to menu:Editor[Copyright], and set [guilabel]*Default project copyright* to the *Vaadin* profile you created

[.wrap-lines]
[source,txt]
----
<source-info group="IntelliJ IDEA"></source-info>
Copyright 2000-$today.year Vaadin Ltd.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under
the License.
----
--

== Known Problems in Configuration

IntelliJ IDEA has a known problem with link:https://youtrack.jetbrains.com/issue/IDEA-192220[importing sources of other modules as resources]. This affects the Flow project where `flow-client` has `flow-server` sources as a resource.

The fix for this is to comment out the `flow-server` resource for the `flow-client/pom.xml` (https://github.com/vaadin/flow/blob/master/flow-client/pom.xml#L166-L168[source]) during development.

To build the `flow-client` package, remember to un-comment the resource. And don't commit this change to the repository.

.`flow-client/pom.xml`
[source,xml]
----
<!--
    <resource>
        <directory>../flow-server/src/main/java</directory>
    </resource>
-->
----

[discussion-id]`A0EF8ED7-DED5-454E-A5D0-DA4F9669F650`

++++
<style>
[class^=PageHeader-module-descriptionContainer] {display: none;}
</style>
++++